### ISSUE TITLE
Release channel OTA always from default channel, but not the release-channel set during build

### ISSUE THREAD

**Issue by hesyifei** [expo/expo#10304]
### Summary of Issue 
I build my app with `expo build:ios --release-channel prod-v1`. But `expo publish --release-channel prod-v1` doesn't push the OTA update to that build. Instead, I have to `expo publish` (with the default channel) to push the OTA update to that build.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```

  Expo CLI 3.27.7 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.11.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.2
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 3.27.7
    Expo Workflow: managed

```

### Steps to Reproduce
1. `expo build:ios --release-channel prod-v1` a project and upload this build to TestFlight. (I also briefly tested Android build and found the same problem)
2. Update any JS code in the project.
3. `expo publish --release-channel prod-v1`

### Expected Behavior vs Actual Behavior

**Expected Behavior:** The JS updates should be reflected in the build after relaunching twice (my `fallbackToCacheTimeout` is `0`). Moreover, `expo publish` should not affect this build.

**Actual Behavior:** No matter how many times I opened the app, stayed in the app for > 30 seconds, and relaunched the app, the app did not receive the new update. Instead, when I do `expo publish`, the update shows up in the build (even though this should be publishing to the default channel, not the `prod-v1` channel).

**Comment by dataforce-campbell** [comment]
I am experiencing this issue as well, I believe there is an issue with the `expo-updates` package. 

I have just built a iOS standalone app and confirmed that the `releaseChannel` value in the EXShell.info is set (in my case to prod-2.2) but the `Expo-Release-Channel` header is set to default when retrieving the update manifest.

**Comment by CampbellMG** [comment]
I am experiencing this issue as well, I believe there is an issue with the expo-updates package. 

I have just built a iOS standalone app and confirmed that the `releaseChannel` value in the EXShell.info is set (in my case to `prod-2.2`) but the `Expo-Release-Channel` header is set to default when retrieving the update manifest.

**Comment by geydson** [comment]
I'm facing the same problem, after updating to SDK 39 I generated an APK with "--release-chanel homol", and when trying to run "expo publish --release-channel homol", I don't get the update to form any, I just ran "expo publish "(in this case the standard) and I immediately received the update via OTA :/

**Comment by TreeMan360** [comment]
I also am experiencing the same issue. Definitely seems to be a problem with ```expo-updates```.

**Comment by calvinkei** [comment]
same issue. it happens after updating to SDK39

**Comment by jnoleau** [comment]
same issue after upgrading to SDK39

**Comment by Stavorinus** [comment]
same issue after upgrading to SDK39

**Comment by ide** [comment]
We'll most likely be able to look into this starting next Wednesday. To our knowledge, this issue impacts SDK 39 in all environments including the app store development client and standalone apps for both Android and iOS. Until a fix goes out we recommend using SDK 38 if you rely on release channels.

**Comment by HVHMobileDeveloper** [comment]
Please help us as soon as possible, so This issue impact to me, I have released to store so.... can’t use hot fix for release.

**Comment by brentvatne** [comment]
@HVHMobileDeveloper - until this is resolved, your options are:

- rollback to sdk 38 and do another build, ship that to store
- publish to the `default` channel to ship an update

the latter option seems safe given that it will only impact apps with sdk-39. aside from release channel, compatible updates are chosen based on sdk version and platform. so old binaries on the default release channel would not get the update, it would only go to binaries built against sdk-39.

**Comment by Aryk** [comment]
> We'll most likely be able to look into this starting next Wednesday. To our knowledge, this issue impacts SDK 39 in all environments including the app store development client and standalone apps for both Android and iOS. Until a fix goes out we recommend using SDK 38 if you rely on release channels.

Which I think 90% of people with Expo apps in production do ;)

Does it make sense as a practice moving forward to add high-impact bugs like this that affect all users to the SDK Release page so that others know what awaits them. Probably there are another 3-4 high-impact obvious things that may be broken that should also be there besides this one.

Yes, obviously one can peruse through the github issues...but without literally clicking on each one and reading all of the comments...it's not clear if its been a) identified by Expo and b) will be fixed soon.

**Comment by Aryk** [comment]
Is anyone experiencing OTA that do not work even with the default channel?

I started a sister thread here, please chime in:

https://github.com/expo/expo/issues/10417

**Comment by connor-odoherty** [comment]
To piggyback what Aryk said, it's concerning that:

a) There is very little visibility into these high-impact breakages
and
b) There isn't any sort of testing in place to protect against such a major breakage

At the very least, updating the "Upgrade to 39" blog post with a list of known issues, warning users before they commit time to upgrading and subsequently debugging the broken upgrade, would have have been appreciated. There have been multiple app breaking changes that are only discovered upon digging through GitHub issues, which is unacceptable when the only way to know of these high-impact issues is to experience them firsthand after an upgrade.

Release channels are critical to any organization with an Expo app currently in production. It worries me that both this, and the broken "from dead state" push notification handler made it out into a release (with the latter taking a full release to be patched).

Is there a plan to improve the way these releases are managed? As users, should SOP be waiting a month for the release to stabilize before upgrading? Normally, this would seem like best practice, but it isn't always viable (like when a new version of iOS is released, or when needing a fix for issues from a previous release).

I apologize for all the negativity, especially considering how great Expo has been for our organization as a whole. You all have been great in support so far, and we appreciate the hardwork, I assume we can chalk this up to growing pains

**Comment by tevonsb** [comment]
Has anyone else experienced a complete failure to run the apps (gets stuck on downloading update screen) after upgrading to SDK 39?

I am also having the issue described above where release channels do not update via OTA.

Additionally, a possibly related bug: after publishing the app, it becomes completely unresponsive, stuck on the "loading update" screen. If it is being run in the expo client, it will freeze when the menu is pulled up. If it is being loaded in a standalone, then only the splashscreen will be shown forever.

This is a massive issue for us.

**Comment by gregfenton** [comment]
Total dart shoot here, but might there be some relation between this issue and https://github.com/expo/expo/issues/10140 ?

**Comment by CampbellMG** [comment]
We had a similar problem when trying to publish to a release channel. We hadn't published to the default channel in a long time meaning errors were thrown as the build it was retrieving from the default channel wouldn't run on the current client because the target SDK was too old. The fix was to publish the current build to the default channel.

**Comment by ide** [comment]
@Aryk @connor-odoherty I hear your frustration and feel pretty bummed we let you down. One of the most important values for the Expo team is to build developer trust -- this helps us make day-to-day decisions and when we succeed at it, it's good for everyone. Unexpected bugs that show up after you've invested time updating your project understandably erode that trust and I'm disappointed too. Feelings don't fix bugs, though, but I want to communicate how we think about things because when you rely on software it's useful to understand the priorities of the people who work on the software and how they make decisions.

The SDK 39 release was not QA'd close to as well as was needed. To address this issue around release channels and a slew of other meaningful issues, @brentvatne will be leading a minor update to the SDK 39 clients and libraries. He has put together a list of top issues that are listed at the top of [the SDK 39 release notes](https://blog.expo.io/expo-sdk-39-is-now-available-4c10aa825e3f). There are few other ways to succinctly communicate as much assurance as saying that Brent is overseeing the bugfixes.

> I apologize for all the negativity, especially considering how great Expo has been for our organization as a whole. You all have been great in support so far, and we appreciate the hard work, I assume we can chalk this up to growing pains.

We appreciate the note -- we're developers too (literally every member of the Expo team is on GitHub) and get that at the end of the day a big part of whether your own code works is whether your dependencies -- in this case, Expo -- work. It also helps a lot when the posts in issue threads are coherent contributions and raises the likelihood we get to heart of the matter earlier, so thank you for that too.

**Comment by Aryk** [comment]
Thanks @ide for your response and thoughts. I think it would be great for those interested to discuss what will be done for next SDK 40 release to ensure that there aren't any common-use case 100% impacting bugs like on this and the previous release. Where would it be best for me to write down my ideas? In a forum posting?

**Comment by ide** [comment]
@Aryk mind if I send you a note at the email in your GH profile?

**Comment by Aryk** [comment]
@ide That would be great, looking forward to your email.

**Comment by flo-butterfly** [comment]
@ide Do you know if we'll have to wait for the next major release (40) or will it come as a patch soon?

Thank you

**Comment by ide** [comment]
It will come in an update to 39 c.f. https://github.com/expo/expo/issues/10464.

**Comment by brentvatne** [comment]
this is now resolved! see https://github.com/expo/expo/issues/10464#issuecomment-703178030

**Comment by gang544043963** [comment]
Hi @brentvatne ,
The OTA seems still not work well in SDK 39.0.3.

What I did:
1. update expo-cli to 3.27.14
2. change my react-native version to https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz.
3. update expo client
4. delete "node_modules" and "yarn.lock"
5. run "yarn upgrade".

OTA config:
`
"updates": {
      "enabled": true,
      "fallbackToCacheTimeout": 0
    },
`
It doesn't work when I build in our channel "ab_qa", but work well in default channel.

Please take a look at this. I have spend more than 2 days on this issue. 

Thank you in advance.

**Comment by mikkelwf** [comment]
Hi @brentvatne 

My managed app is still not working with OTA updates:

Steps I've taken:
* Set `"react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz"`
* Set `"expo": "^39.0.3"`
* Updated cli to 3.27.14 and build app, deployed to play store
* Updated cli to 3.28.0 and build app, deployed to play store

I use release channel named `staging` for my non-production build.

When building, the cli reports that the API-version is `39.0.0`, isn't that supposed to be `39.0.3`..?

My Expo disagnostics:

```
  Expo CLI 3.28.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.3 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-navigation: ^4.x => 4.4.1 
    npmGlobalPackages:
      expo-cli: 3.28.0
    Expo Workflow: managed
```

**Comment by mikkelwf** [comment]
Force-closing the app and re-opening it a couple of times forces the update..
But its not pretty..

**Comment by brentvatne** [comment]
@mikkelwf - feel free to configure that behavior in your app: https://docs.expo.io/guides/configuring-ota-updates/

loading anything is always a tradeoff: block until it's ready, or load asynchronously in the background? we chose asynchronously in the background. if you close the app while it's still downloading, it will need to restart.

<hr />

the release channel issue that this issue was about was resolved two weeks ago so i will lock this issue. create a new issue and follow the issue template if you can demonstrate that you are experiencing something similar, thanks!
