### ISSUE TITLE
[expo-facebook][expo-ads-facebook] Upgrade iOS FBSDK

### ISSUE THREAD

**Issue by donutsahoy** [expo/expo#10987]
### Summary of Issue 
Ads not appearing in my app.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.28.5 environment info:
    System:
      OS: Linux 5.8 Manjaro Linux
      Shell: 5.0.18 - /bin/bash
    Binaries:
      Node: 15.0.1 - /usr/bin/node
      npm: 6.14.8 - /usr/bin/npm
    npmPackages:
      expo: ^39.0.0 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed

App is developed for iOS and Android

### Reproducible Demo
https://snack.expo.io/@donutsahoy/hot-crackers

https://gitlab.com/donutsahoy/facebookadtest

Only changes are the addition of the Facebook Expo Ads, add the keys in app.json and adding the ad in App.js

 
### Steps to Reproduce

Running the app, ads or test ads won't display, receive Synthetic Error
### Expected Behavior vs Actual Behavior
Expected Behavior: Ads or Test Ads populate
Actual Behavior: No ads show and it gives an error, Synthetic Error with no further explanation of what it is or what it means.

Error message in its entirety: https://gitlab.com/donutsahoy/facebookadtest/-/blob/master/error.txt

Instructions I followed to implement Facebook Ads: https://docs.expo.io/versions/latest/sdk/facebook-ads/

Thank you!

**Comment by cruzach** [comment]
you should use Facebook's test IDs in development, as we state here- https://docs.expo.io/versions/latest/sdk/facebook-ads/#development-vs-production

```
      <FacebookAds.BannerAd
        placementId="IMG_16_9_APP_INSTALL#YOUR_PLACEMENT_ID"
        type="standard"
        onPress={() => console.log('click')}
        onError={(error) => console.log('error', error)}
      />
```

renders without a problem for me (tested on Android)

**Comment by donutsahoy** [comment]
Hi @cruzach testing on iOS, this is my code block from my test app that I did as a barebones test.

`    <View style={styles.container}>
      <Text>Display</Text>
      <FacebookAds.BannerAd
        placementId="IMG_16_9_LINK#[REDACTED]"
        type="standard"
        onPress={() => console.log('click')}
        onError={error => console.log('error', error)}
      />
      <StatusBar style="auto" />
    </View>`

Really strange that it's throwing a Synthetic error but not mentioning an error past that. 

Is there a compatibility issue with SDK 39 and the latest version of the expo-ads-facebook?

**Comment by cruzach** [comment]
the actual error message looks to be available under `error.nativeEvent.message`, I'm seeing
```
New bundles must use latest available Audience Network SDK.
```

Let me know if you are too

**Comment by donutsahoy** [comment]
Updated to 8.4.1 for expo-ads-facebook and I am getting this error. 

`The SDK version in the ad request is no longer supported for new apps. Please upgrade to one of the latest versions of the SDK`

So same error different wording?

**Comment by cruzach** [comment]
Hm, probably. Looks like we'll have to upgrade these underlying libraries @donutsahoy , thanks for bringing this up

**Comment by cruzach** [comment]
Unfortunately this is going to take a little bit more work as usual, since the more recent version of the FBSDK are written with Swift, so we’ll need to make sure we fully support then when we upgrade

**Comment by bozzmob** [comment]
@cruzach I am not asking for an ETA, but, I just wanted to know if this is currently being worked on.

**Comment by cruzach** [comment]
Like I said above, it requires more than just upgrading the FBSDK. Right now we’re planning on having this addressed in SDK 41

**Comment by bozzmob** [comment]
@cruzach Makes sense. Thank you.

**Comment by lisamillercool** [comment]
I am facing the same issue. Not able to use the ads module. :(

**Comment by lludol** [comment]
@cruzach Same here. We tried everything but it's not working at all!
Our client is losing money now because of that. We have ads on Android but not on iOS.

The error:
```New bundles must use latest available Audience Network SDK```.
We are already using the latest modules versions.

**What can we do? It's very urgent!**

**Comment by brentvatne** [comment]
we don't have a solution for the managed workflow at the moment. you can work around it by [ejecting your app](https://docs.expo.io/workflow/customizing/) and adding whichever fb sdk version you like. you can continue still [eas build](https://docs.expo.io/build/introduction/) instead of `expo build` to produce your app store binary if you like.

**Comment by guillaume-g** [comment]
@brentvatne We are actually using the Bare Workflow on our application.
The ads works perfectly on Android, but it does not on iOS.
The only difference I see is the **AudienceNetwork** version which is **5.11** on **Android** and **5.9** on **iOS**.

The error:
New bundles must use latest available Audience Network SDK.

We are using the latest version of **expo-ads-facebook**.
Is the error related to the AudienceNetwork versions or something else ? Any clue to point at us ?

Thanks for your amazing job anyway!

**Comment by raymond59** [comment]
Hi @cruzach @brentvatne ,
Is the problem solved in expo ads facebook 9.0.0 ?
Is it compatible with expo sdk40?

**Comment by kellvembarbosa** [comment]
Will you work on it?

**Comment by pdugan20** [comment]
I'm getting the exact error message cycle from https://github.com/expo/expo/issues/3339 where it first throws a 1012 error 
- "The SDK version in the ad request is no longer supported..."

...and then if I refresh a 1002 error:
- "Ad was re-loaded too frequently"

Assuming this is related since it seemed like it was an unsupported SDK issue in 2019?

**Comment by cruzach** [comment]
this will be fixed by https://github.com/expo/expo/pull/11921

**Comment by pdugan20** [comment]
Im still getting the following error on the SDK 41 beta:
```
Facebook Ads could not load (code 1001): No fill
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:364026:33 in <unknown>
at node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:10 in emit at [native code]:null in callFunctionReturnFlushedQueue
```

I'm both adding a test device:
```
export function addTestDevice() {
    if (__DEV__) {
        FacebookAds.AdSettings.addTestDevice(
            FacebookAds.AdSettings.currentDeviceHash,
        );
    }
}
```

...and using different test placementIds (e.g. IMG_16_9_APP_INSTALL#177239343756731_177243237089675), but can't get anything to render on the iOS simulator.

**Comment by brentvatne** [comment]
https://developers.facebook.com/docs/audience-network/guides/test/checklist-errors/

![Screen Shot 2021-03-31 at 7 07 42 PM](https://user-images.githubusercontent.com/90494/113233560-612a4380-9254-11eb-89ef-10d835199923.png)

**Comment by pdugan20** [comment]
@brentvatne thanks I did see this as well, so it sounds like it's not possible to view test ads on the simulator and these can only be viewed on a physical iOS device with the facebook app installed?

**Comment by cruzach** [comment]
Fixed in SDK 41, and the beta is available now! https://blog.expo.io/expo-sdk-41-beta-is-now-available-958edcd78991

**Comment by pdugan20** [comment]
@cruzach thanks so much!

**Comment by prakashtank** [comment]
Hello,

I'm using SDK 40 in my expo app, but still not visible in production build app (.apk), development phase working fine in android app, Please guide me, what should i do ?
