### ISSUE TITLE
[expo-branch] [Android] Warning. Session initialization already happened.

### ISSUE THREAD

**Issue by Svarto** [expo/expo#11098]
### Summary of Issue
When using the expo-branch on android it throws the following error when clicking on deep links if the app is already running in the background:

`Error from Branch: Warning. Session initialization already happened. To force a new session, set intent extra, "branch_force_new_session", to true.`

Sometimes also restarts / crashes the app.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

This is an android only problem.

 Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.6.0 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.3 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
      react-navigation: ^4.4.1 => 4.4.3 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed

### Reproducible Demo
Hard to do in a snack as the expo-branch only works in standalone builds, it throws an error if I try and make a snack with it.

The error has already been identified in the original Branch React Native repository, see link here (https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/572), and they have 2 potential solutions (one is to remove all reInitSession and other is to define SingleTask in AndroidManifest). I tried looking through the expo-branch package but I don't know java so struggled to find a way to try this out / fix it.
 
### Steps to Reproduce
1) Start new expo project
2) Install Branch and set it up
3) Create a deep link and click on it while logging errors on Android

### Expected Behavior vs Actual Behavior
The deep link should be handled by Branch without any crashing nor errors being thrown.

**Comment by AdamJNavarro** [comment]
Hey @Svarto, if this is a blocker for you I would recommend migrating your project from the Managed workflow to the Bare workflow so that you get access to the native directories. It seems that the issue is still present in the rn-branch library so the onus may fall on you to fix it locally. The earliest a fix could be included in the Managed workflow would be SDK41 which is a couple months away.

Cheers,
Adam

**Comment by cruzach** [comment]
> they have 2 potential solutions (one is to remove all reInitSession and other is to define SingleTask in AndroidManifest

I think those are possible causes, not solutions. We define SingleTask in the androidmanifest file already, and do not call `reInitSession` ourselves. I think you should subscribe to that issue in branch's repo for further updates (since this seems to be a branch problem and not a bug with the Expo SDK)

**Comment by Svarto** [comment]
@cruzach @AdamJNavarro thanks both for the reply, I will keep following the branch thread and see if they come with a solution!

**Comment by Svarto** [comment]
@cruzach @AdamJNavarro Hi both, I followed up this with Branch support and had a look through the expo-branch implementation. I am not proficient in Java, nor expo linking modules to RN, so apologies if what I say contains errors - just trying to find a solution to this issue.

In my exchange with Branch support they said this: "RNBranchModule.onNewIntent(intent) part of the SDK implementation manages new and existing session initializations and it does not have to be managed in your java code explicitly."

Looking at the expo-branch code, it looks like this is attempted to be handled within the Android java code, instead of just implementing the standard branch approach. I am not sure why and I was wondering if this might be a legacy implementation and the handling of new vs. already initialized session should be moved to be handled completely by the Branch RNBranchModule?

[Ref link](https://help.branch.io/developers-hub/docs/react-native#android-2)

Moving away from setIntent to the RNBranchModule.onNewIntent is explicitly mentioned in the upgrade notes to v5.0.0:
![image](https://user-images.githubusercontent.com/24279217/105627914-7d170080-5e31-11eb-947f-de21cf09989c.png)

And the branch documentation implementation onNewIntent differ from the expo-branch approach:
![image](https://user-images.githubusercontent.com/24279217/105627783-cc106600-5e30-11eb-9a42-23c171f3117b.png)


Currently the expo-branch module seems to initialize it manually like this:
```
public static void onNewIntent(@Nonnull Intent intent) {
mActivity.setIntent(intent);
mNewIntent = true;
reInitSession(mActivity);
}
```

Which then passes the mActivity intent to:

```
public static void reInitSession(Activity reactActivity) {
Branch branch = Branch.getInstance();
Intent intent = reactActivity.getIntent();
if (intent != null) {
intent.putExtra("branch_force_new_session", true);
notifyJSOfInitSessionStart(reactActivity, intent.getData());
Branch.sessionBuilder(reactActivity).withCallback(referralInitListener).reInit();
} else {
Log.w(REACT_CLASS, "reInitSession was called but the Intent is null");
}
}
```

As said, I am not a Java master so might be totally wrong, also as in comments the documentation approach is referenced but not implemented there is likely a reason for this custom approach taken. However, in my exploration with Branch support that is likely the cause of this error. Branch handles reinitialization within their own module, while this module is not used in the expo-branch implementation and instead tries to handle reinitializations in a custom way.

**Comment by Squishy47** [comment]
Hey, do we have an update on this, is it gonna be fixed in sdk 41?? i've recently implemented Expo-Branch in my app and come up against this error.

**Comment by arjen1981** [comment]
We have been facing this issue for a while now on Android. We updated to SDK41 and folowed the documentation and added android.intentFilters. But SDK41 did not resolve the issue for us. Are there any updates or ideas when this could get fixed?

Also see: https://github.com/BranchMetrics/android-branch-deep-linking-attribution/issues/839

**Comment by dmitryame** [comment]
any update on this? I'm on expo 43 now and still facing this issue. The 44 just got released, and it does not seem there are any mentions of fixing this issue in the release notes -- frustrating.

**Comment by jakequade** [comment]
Bumping to keep it from being closed. Any updates?

**Comment by Svarto** [comment]
Bump, to keep it open as it's still relevant

**Comment by Svarto** [comment]
Bump

**Comment by Svarto** [comment]
Still happening

**Comment by niladreeb** [comment]
Still happening with "@config-plugins/react-native-branch": "^8.0.0"
