### ISSUE TITLE
error when compiling expo-image-picker 9.1.1(kotlin)

### ISSUE THREAD

**Issue by theambidextrous** [expo/expo#11100]
## 🐛 Bug Report
 kotlin cannot compile with expo-image-picker 9.1.1
### Summary of Issue 
i get the error below when i build project in android studio.

`...node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/VideoResultTask.kt: (30, 112): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type String?`

Project gradle:

```
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        //FCM
        classpath("com.google.gms:google-services:4.3.4")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.28.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.2/12B5025f - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.3 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.0
    Expo Workflow: bare

### Reproducible Demo

Everything is working in simulators and even expo client. no problem is during compile.
 
### Steps to Reproduce
compile project with the above gradle settings

### Expected Behavior vs Actual Behavior

Project should build successfully. In my case the following lines in expo-image-picker fails.

```
 putInt("width", mediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH).toInt())
 putInt("height", mediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_HEIGHT).toInt())
putInt("rotation", mediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_ROTATION).toInt())
putInt("duration", mediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION).toInt())
```

**Comment by lejager** [comment]
@theambidextrous I'm getting this too. Did you figure out the issue?

**Comment by theambidextrous** [comment]
> @theambidextrous I'm getting this too. Did you figure out the issue?

Unfortunately it never worked for me. I was forced to downgrade my env to 

```
"expo": "^38.0.8",
"react": "~16.11.0",
 "react-native": "~0.62.2",
"expo-image-picker": "~8.3.0",
```

**Comment by iwantadventureinthegreatwidesomewhere** [comment]
@theambidextrous I'm getting this error as well on RN 0.63.2. If you eject your app, you can give https://github.com/react-native-image-picker/react-native-image-picker a shot. But it's almost an identical implementation to expo-image-picker, so it makes me doubtful. Also I know ejecting from expo may not ideal for everyone. I'm gonna give it a try now as I prefer not to downgrade RN.

**Comment by lejager** [comment]
@theambidextrous Thanks for following up! I ejected and went with react-native-image-picker. That worked for me.

**Comment by Duell10111** [comment]
Error happens on my site too with Version 9.2.0 on a ejected project. With this gradle config
`buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 26
        compileSdkVersion = 30
        targetSdkVersion = 30
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}`

**Comment by brentvatne** [comment]
what kotlin version are you using? this works fine on a new project initialized with `expo init` (choose a bare workflow project) and kotlin 1.3.50: https://github.com/expo/expo/blob/master/packages/expo-image-picker/android/build.gradle#L83

**Comment by Duell10111** [comment]
In my main gradle.build I dont spcified the kotlin version. So I expect I use some version specified in the dependencies that use kotlin. My experience in using kotlin is very low, so I dont know where I could find my using kotlin version.
My project got inizialized with expo init as bare workflow project ;)

**Comment by brentvatne** [comment]
@Duell10111 - provide a reproducible example? here is a bare project initialized with expo-cli. i added expo-image-picker and the required config, then built it. worked fine. copied the gradle config from op, worked fine.

so we would need to know more about what is configured in your project such that this would not compile

**Comment by lukmccall** [comment]
Fixed by https://github.com/expo/expo/pull/11552. Please check the newest versions -> 10.0.0.

**Comment by dorthwein** [comment]
This is still happening with v10.2.0 and upgrading to react-native v0.64.2

**Comment by lukmccall** [comment]
@dorthwein, which version of Kotlin are you using?

**Comment by mic7010** [comment]
@dorthwein - did you resolve this?

**Comment by tkrajina** [comment]
@lukmccall I can confirm this is still a problem. I downloaded the latest Android Studio (beta, since that's the only one working on my M1 Mac).

The kotlin runtime it uses is:

```
$ JAVA_HOME=Contents/jre/Contents/Home ./Contents/plugins/Kotlin/kotlinc/bin/kotlin          
Welcome to Kotlin version 1.5.10-release-891 (JRE 11.0.10+0-b96-7249189)
Type :help for help, :quit for quit
>>> 
```

**Comment by evanlarkin10** [comment]
I'm getting this issue as well

**Comment by mic7010** [comment]
I resolved it by setting the following in the android/build.gradle file

Under dependencies:-
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.0"

ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 23
        compileSdkVersion = 29
        targetSdkVersion = 29
        kotlinVersion = "1.4.0"
        androidXCore = "1.6.0"
}

Hope that helps

**Comment by Mauv-hub** [comment]
I resolved this issue by updating react-native-unimodules. 
Here's how to set it.
[docs](https://docs.expo.io/bare/installing-unimodules/)

**Comment by haveamission** [comment]
Updating react-native-unimodules was also the only thing that worked for me
