### ISSUE TITLE
Detach Error: "Cannot read property '_isCommandError' of undefined

### ISSUE THREAD

**Issue by digitaledge** [expo/expo#1113]
To reproduce this error:

1. exp init > enter name & blank project
2. add ios.bundleIdentifier and android.package to app.json
3. exp detach

Result:
![bildschirmfoto 2017-12-14 um 16 41 29](https://user-images.githubusercontent.com/3514563/34000519-cdfde686-e0ed-11e7-97c1-fc11bfa28d97.png)

**Comment by digitaledge** [comment]
after upgrading exp to the latest version the error message changed:

![bildschirmfoto 2017-12-14 um 17 16 09](https://user-images.githubusercontent.com/3514563/34002329-9b7a2864-e0f2-11e7-8e17-d75be844f520.png)

**Comment by digitaledge** [comment]
Just want to ask if you are going to fix this issue with SDK 24 or with the next monthly release?

Actually i am forced to work with SDK 22, because of broken Payments in 23 and 24 is impossible to detach for android as described above.

**Comment by terribleben** [comment]
Hi there, I believe @jesseruder is currently looking at the "can't determine exponent directory" issue, and I'm not sure whether the two issues you've seen are related.

**Comment by terribleben** [comment]
See also https://github.com/expo/expo/issues/1133

**Comment by jesseruder** [comment]
Sorry about this. Fixed in exp version 47.1.2

**Comment by wrsx** [comment]
I'm still getting this issue trying to detach on iOS. I was able to detach for android without issue on windows.

`Moving iOS project files...`
`(node:857) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '_isCommandError' of undefined`

CLI 47.4.4
Expo 24.0.0
react 16.2.0
react-native 0.51.0
