### ISSUE TITLE
Reports of `exp start` hanging

### ISSUE THREAD

**Issue by terribleben** [expo/expo#1130]
https://forums.expo.io/t/exp-start-hangs-in-terminal-with-no-output/5648

> steps to reproduce: not sure, it happens randomly. setting EXPO_DEBUG=true doesn’t work in this case.
> 
> Deleting ~/.expo does not work. As soon as I enter in my password it hangs at “Success. You are now logged in”.
> 
> Using latest version of exp but this has happened with older versions as well.
> 
> XDE however does work fine! I just prefer the command line.

**Comment by peterpme** [comment]
Just reached out if I can help in any way

**Comment by fedden** [comment]
Hey folks! I just got this problem of exp hanging with no output upon running `exp start`.

Not sure if this helpful or a red-herring, I fixed this issue by killing a process named:  `adb -P 5037 fork-server server`

Cheers for the great tool!

**Comment by Niryo** [comment]
still happens on expo-cli 2.2.0 on mac. expo start hangs forever, no output at all. is there a way to debug this issue?
