### ISSUE TITLE
Regression: Blank screen display when Updates.reloadAsync() instead of splash screen

### ISSUE THREAD

**Issue by feliperaul** [expo/expo#12000]
**Summary**

Blank screen display when Updates.reloadAsync() instead of splash screen

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

39

**Environment**

Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/dev/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.1
        System Images: android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-navigation: ^4.4.3 => 4.4.3
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

Happens in any project.

We just udpated from SDK 37 to SDK 39.

We now noticed that on SDK 37, when we invoked `Updates.reloadAsync()`, the user would be immediately shown the app's splash screen while the app reloaded.

Now, they are shown an undesired white screen while the app reloads.

**Comment by HarelTussi** [comment]
Getting this issue as well :(

**Comment by m-deacon** [comment]
Hi Expo Team

Any update on this? Occurring for us on SDK39 too.

**Comment by feliperaul** [comment]
Just updated to SDK 41, issue persists.

**Comment by Codelica** [comment]
This seems to be the case w/ SDK 42 also. :/

**Comment by sajadghawami** [comment]
I upgraded expo from 41 to 43 and now i am having the same issue with `await Updates.reloadAsync();`.

Anyone know a workaround? Also, there doesn't seem a way to force-show the `SplashScreen` as a possible solution...

**Comment by RodolfoGS** [comment]
> I upgraded expo from 41 to 43 and now i am having the same issue with `await Updates.reloadAsync();`.
> 
> Anyone know a workaround? Also, there doesn't seem a way to force-show the `SplashScreen` as a possible solution...

I'm upgrading to SDK 43 too and I'm having a white flash screen, I don't know if is related with expo-updates, but could be.
Upgrading from `expo:42.0.3, expo-splash-screen:0.11.2` to `expo:43.0.1, expo-splash-screen:0.13.4`

**Comment by jwoo92** [comment]
I am also experiencing this after upgrading from SDK 42 to 43, bare workflow using expo-dev-client@0.6.3. 

App loaded fine initially and after fetching the update's json, white screen appears. proxied the network request and confirmed the update config is correct.

**Comment by sajadghawami** [comment]
anyone having a quick fix for the meantime?

**Comment by RodolfoGS** [comment]
> anyone having a quick fix for the meantime?

I had the issue but was not related with `expo-splash-screen`, was related with `@react-navigation/native` when I switch between screens.

I fixed adding a view to contain the `NavigatorContainer` like this:
```
<View style={{flex: 1, backgroundColor: theme.colors.background}}>
  <NavigationContainer ...>
    ...
  </NavigationContainer>
</View>
```

**Comment by sajadghawami** [comment]
@RodolfoGS 

thanks for the reply! Unfortunately i also got that wrapper view and still have that issue with the blank-screen only when there is a new OTA and i restart the app.

**Comment by dqii** [comment]
I'm having this issue in SDK 44 as well

**Comment by adailson2** [comment]
me too, I'm using SDK 44.

anyone have some solution even if temporary about this issue?

**Comment by Daniel-Cross** [comment]
Having same issue on SDK 44.

Would be nice if I could just show a screen that's the same colour as the app background or a loading spinner instead of a random white screen.

Anyone have a workaround?

**Comment by alexweltman** [comment]
Any update on this? Seeing it on 43 and 44

**Comment by daxaxelrod** [comment]
Expo 45 here, started getting this when I upgraded us to @react-navigation/native-stack from react-navigation/stack. Reproduced and am 99% sure its an issue with native-stack

**Comment by ilyausorov** [comment]
Hey guys, especially those running SDK 43, 44, or 45 (after the move to expo modules), I made a PR which I think fixes the issue so that the splash screen shows when you do expo-updates reloadAsync. If you're able to add it as a patch to your project right away, go for it https://github.com/expo/expo/pull/17592

**Comment by cloudy-ninja** [comment]
How can we use this patch on bare workflow?
