### ISSUE TITLE
expo-notifications /  Custom Notifications does not work via api 

### ISSUE THREAD

**Issue by philipp-spark** [expo/expo#12562]
### Summary

Hi, 

i try send a notification via api. The notification appears but it will ignore my "categoryId" and not show the notification actions :( 

i found several similar issues: 

https://github.com/expo/expo/issues/10467
https://github.com/expo/expo/issues/10314
https://forums.expo.io/t/sdk-39-interactive-notifications-dont-seem-to-work/43186

or maybe categoryId is not supported anymore ?

thanks for your time 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.3.5 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.3.5
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@pbisson/notify

**Comment by brentvatne** [comment]
hi! this is supported in sdk 41, which we just released yesterday :) https://blog.expo.io/expo-sdk-41-12cc5232f2ef

**Comment by philipp-spark** [comment]
width the upgraded version(41) i have still the same problem. it will not show the notification actions via api
