### ISSUE TITLE
useLastNotificationResponse returns null after clicking on a notification

### ISSUE THREAD

**Issue by Svarto** [expo/expo#12854]
### Summary

When testing the useLastNotificationResponse, it returns null even when clicking on a notification when testing it using the Expo Go app. Same bug has been observed in production.

If the app is open, the useLastNotificationResponse hook correctly picks up the notification details when it is tapped on.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.6.0 - /usr/local/bin/node
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.12.45 => 0.12.68 
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.1 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. `expo init my-project`
2. `expo install expo-notifications`
3. Go to app.js and paste in the below
4. Open the app with a physical device through the Expo Go app
5. Close the opened app to make sure it is killed
4. Send notification to the physical device Expo Token and click on it
5. The app opens but the below `console.log(useLastNotificationResponse)` shows up as first undefined and then null

```
import { StatusBar } from "expo-status-bar";
import React from "react";
import { StyleSheet, Text, View } from "react-native";
import * as Notifications from "expo-notifications";

export default function App() {
  const lastNotificationResponse = Notifications.useLastNotificationResponse();

  console.log(lastNotificationResponse);
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});


```

**Comment by cruzach** [comment]
This was fixed in SDK 41 - https://github.com/expo/expo/issues/11933

**Comment by AsserHamad** [comment]
I'm on SDK 41 and the problem still persists. As stated above, when the app is closed the notification is undefined then null, however, if the app is in the background then it correctly picks up the notification.

**Comment by mfmurray** [comment]
I'm on SDK 42 and I'm seeing the problem as well. Does anyone know any workarounds?

**Comment by cruzach** [comment]
Please provide a reproducible demo: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by mfmurray** [comment]
Please let me know if you need anything else.

### Environment
Expo CLI 4.12.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\mike\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ~42.0.1 => 42.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

```
...
import * as Notifications from "expo-notifications";

export default function App() {
  const lastNotificationResponse = Notifications.useLastNotificationResponse();

  React.useEffect(() => {
    console.log({ lastNotificationResponse });
  }, [lastNotificationResponse]);

  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <Route />
      </PersistGate>
    </Provider>
  );
}

```

**Comment by tjaaronrich** [comment]
I'm on SDK 43 and the same thing happens for me. If the app is closed when the notification is clicked, useLastNotificationResponse returns undefined then null. addNotificationResponseReceivedListener returns nothing.

**Comment by ErikAndersen81** [comment]
This behaviour perists on SDK 45

**Comment by iamromec** [comment]
This behavior persist on SDK "expo": "~46.0.19",

[Only (addNotificationResponseReceivedListener) works in iOS]

**Comment by samskinner32** [comment]
I'm confused, why is this closed? Surely the expected behavior for this hook is that when the app is opened via a notification, it'll return the notification object that was pressed. Only working if the app is foregrounded feels pretty useless.

**Comment by matanume** [comment]
I'm on 
expo 47.0.13
expo-notifications 0.18.1
This behaviour persists.

**Comment by rdlogout** [comment]
problem persist even in expo 49.0.21

for me Notifications.addNotificationResponseReceivedListener or Notifications.useLastNotificationResponse(), non of them are working.

behavior ->

the same code is working, i,e when u click on local or push notification  in expo go addNotificationResponseReceivedListener is fired but that is not firing in production (testflight)
[source.txt](https://github.com/expo/expo/files/13839872/source.txt)

I used https://docs.expo.dev/versions/latest/sdk/notifications/ code as it is 

Again behaviour -> Trigger is firing in expo go but not in production build downloaded from testflight.

Thank you ;

**Comment by zfrankdesign** [comment]
This is happening to me on iOS, Expo 49. Android works. I'm firing a expo local notification from a data message from FCM. When I tap the message and open app I get no initial notification response for iOS.  I'm using React Navigation and calling the `useLastNotificationResponseAsync` in the "getInitialURL" linkingConfig func like so: https://docs.expo.dev/versions/latest/sdk/notifications/#handle-push-notifications-with-navigation

`const response = await ExpoNotifications.getLastNotificationResponseAsync();
		console.log('--- expo initial app open notif response', response);
		if (response && response.actionIdentifier) {
			Alert.alert('You chose:', `${response.actionIdentifier}`);
		}`

On iOS that just keeps returning `null`.

**Comment by PrajTS** [comment]
Facing the same issue in expo-50 as well

**Comment by jetaggart** [comment]
I'm also hitting this on expo-50 only on android. @PrajTS did you find a solution?

**Comment by PrajTS** [comment]
No, I'm using @react-native-firebase/messaging to listen to notifications and using expo-notification to trigger local notification in foreground as @react-native-firebase/messaging does not show any notification on foreground.

**Comment by Goowwy** [comment]
> Facing the same issue in expo-50 as well. `addNotificationResponseReceivedListener` and `useLastNotificationResponse` only work when the app is in foreground.

I have same problem, works only. on foreground

**Comment by Kraktoos** [comment]
Is this solved? I just want to redirect the user when he clicks the app, which doesn't feel very niche... Is there any other way to do what I want? Thanks

**Comment by OrionPro** [comment]
Facing the same issue in expo-50 as well. addNotificationResponseReceivedListener and useLastNotificationResponse only work when the app is in foreground.

**Comment by collinahn** [comment]
same here. expo 50. only on android, using expo-notifications. addNotificationReceivedListener works fine with correct payload
the others fail

**Comment by MurrayMeller** [comment]
Please re-open this issue

**Comment by iway1** [comment]
`useLastNotificationResponse` only works when the app is killed on android. makes no sense

**Comment by billyjacoby** [comment]
I'm having this issue as well - only on Android and for both dev and production builds. Any ideas?

**Comment by Goowwy** [comment]
> I'm having this issue as well - only on Android and for both dev and production builds. Any ideas?

Is that working in ios? can you share code please?

**Comment by PrajTS** [comment]
This is working on expo 51 on android (both release and debug). Will test on iOS and update

**Comment by MGasowski** [comment]
Same issue

**Comment by emilnilimaa** [comment]
Having the same problem, expo 51.0.31

Tapping a notification when the app is in background opens the app. But no events are triggered for  Notifications.addNotificationResponseReceivedListener

And using the hook 
const lastNotificationResponse = Notifications.useLastNotificationResponse();
always return undefined (Undefined Message)
