### ISSUE TITLE
Can't read QR Code with BarCodeScanner/Camera on web build.

### ISSUE THREAD

**Issue by luizgomesdev** [expo/expo#12926]
### Summary

When building the web project. It is not possible to read QR Codes in browsers.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

41.0.1

### Environment

```
Expo CLI 4.4.6 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.11.0 - ~/.nvm/versions/node/v15.11.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.11.0/bin/yarn
      npm: 7.6.0 - ~/.nvm/versions/node/v15.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.5/12E5244e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.6
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

```
import React, { useState, useEffect, useContext } from 'react';
import { useNavigation } from '@react-navigation/core';
import { TouchableOpacity, Dimensions } from 'react-native';
import Icon from 'react-native-vector-icons/Feather';
import Toast from 'react-native-toast-message';

import { BarCodeScanningResult, Camera } from 'expo-camera';
import { BarCodeScanner } from 'expo-barcode-scanner';

import { Loading } from '@views/components/Loading';
import { Text } from '@views/components/Text';

import { QRCodeType } from '@domain/entities/scanner.entity';
import { QRCodeAdapter } from '@data/adapters/qrCode.adapter';
import { VinculateEstablishment } from '@data/usecases/vinculateEstablishment.usecase';

import { ThemeContext } from 'styled-components/native';
import { Container, CameraContent } from './styles';
import { Alert } from 'react-native';

export const Scanner = (): JSX.Element => {
    const navigation = useNavigation();
    const { colors } = useContext(ThemeContext);
    const [loading, setLoading] = useState(true);
    const [hasPermission, setHasPermission] = useState(false);

    useEffect(() => {
        (async () => {
            const { status } = await Camera.requestPermissionsAsync();
            if (status === 'granted') setHasPermission(true); setLoading(false);
        })();
    }, []);

    const handleCodeScanned = async ({ data }: BarCodeScanningResult) => {
    
    // It doesn't arrive here in the browser
        setLoading(true);
        Toast.show({
            type: "error",
            text1: 'Ops!',
        });

        // const { type, url } = QRCodeAdapter(JSON.parse(data));

        // if (type === QRCodeType.VALIDATE) navigation.navigate('ConfirmPin', { url, type })
        // if (type === QRCodeType.VINCULATE) {
        //     await VinculateEstablishment(url);
        //     navigation.reset({ index: 0, routes: [{ name: 'Home' }] });
        // }
        // if (type === QRCodeType.WITHDRAW) navigation.navigate('ConfirmPin', { url, type })

    };

    if (loading) return <Loading />;
    if (!hasPermission) return <Text fontSize={16} color={colors.light} >Sem acesso a câmera</Text>;

    return (
        <Container>
            <Camera
                autoFocus={Camera.Constants.AutoFocus.on}
                style={{ flex: 1 }}
                type={Camera.Constants.Type.back}
                ratio="16:9"
                onBarCodeScanned={(scanningResult: BarCodeScanningResult) => handleCodeScanned(scanningResult)}
                barCodeScannerSettings={{ barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr] }}
            >
                <CameraContent>
                    <Text fontSize={24} color={colors.light} fontWeight="bold">Leia o QR Code</Text>
                    <Icon name="maximize" size={Dimensions.get('window').width / 1.1} color={colors.primary} />
                    <TouchableOpacity onPress={() => navigation.navigate('Home')} style={{ padding: 16 }} >
                        <Text fontSize={16} color={colors.light}> Cancelar </Text>
                    </TouchableOpacity>
                </CameraContent>
            </Camera>
        </Container>
    );
};

```

**Comment by byCedric** [comment]
Hi @luizgomesdev, thanks for the issue report. Could you create a snack as reproducible example? It looks like your code snippet includes a lot of project-specific modules, where we don't have access to.

**Comment by exzos28** [comment]
Is there some kind of solution?

**Comment by exzos28** [comment]
Problem with `@koale/useworker` package being used in `src/expo-camera/src/useWebQRScanner.ts`. For a quick fix, you can install `@koale/useworker": "^4.0.2"` into your project. This should fix the problem.

**Comment by uoyniXnaH** [comment]
Sorry for bothering. Similiar problem here. I do not know if it's proper to create a new issue, so I reply on this one.
I am running a react-native web app using react-native-web, and try using expo-camera to read qrcode.
The camera works perfectly, but does not scan any qrcode.
I have tried putting a qrcode or a barcode before the camera though, it seems that the onBarCodeScanned is not activated.

Packages versions:
react: ^17.0.1
react-native: sdk-42.0.0
react-native-web: ^0.17.1
expo: ~42.0.1
expo-camera: ~11.2.2
expo-barcode-scanner: ~10.2.2
[at]koale/useworker: ^4.0.2

Any advice would be appreciated.

**Comment by AlissonEnz** [comment]
I just updated to expo 43 and it's still not working on web here 😢 even with koale/useworker on version 4.0.2

"expo": "^43.0.0",
"expo-barcode-scanner": "~11.1.2",
"expo-camera": "~12.0.3",
"react": "17.0.1",

```
<Camera
  onBarCodeScanned={handleBarCodeScanned}
  type={cameraType}
  style={styles.camera}
  barCodeScannerSettings={{
    barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr],
  }}
/>
```
Appreciate any help.
Thanks in advance 🙏🏼

**Comment by uoyniXnaH** [comment]
Hello @AlissonEnz 

Have you checked your expo-camera source files? Sometimes even you set koale/useworker to 4.0.x manually, the expo-camera still uses the old version.

I am using the following codes in package.json to force koale/useworker to be 4.0.x
```
  "scripts": {
    "preinstall": "npx npm-force-resolutions",
    ...
  },
  "resolutions": {
    "@koale/useworker": "^4.0.2"
  },```

**Comment by AlissonEnz** [comment]
Hi @uoyniXnaH 

Thanks for your help, I changed my package.json as you said and checked the expo-camera code and it's using `@koale/useworker` 4.0.2 but it's still not working here :/

**Comment by uoyniXnaH** [comment]
Hello @AlissonEnz 

Which part in expo-camera was not working?

I mean, was the camera working (sth is displayed in the web) but qrcode-scanner not working,
or was the camera not working (nothing is displayed)?

For the former one, I am not sure what is going wrong, perhaps you could try using Expo app to run it on different platform, to check if your codes are correct.
For the latter one, maybe the permission was not granted correctly. For some Android's device, this may happen. I am using Expo-permissions to make sure it works (though Expo-permissions is deprecated).

**Comment by AlissonEnz** [comment]
Hey @uoyniXnaH,

The camera is working fine on the web, the problem is that it's not reading the QRCode. I run on my iOS and everything is working fine (the camera and it's reading the QRCode).
