### ISSUE TITLE
[Android] [expo-analytics-segment] ExponentSegment: Method addObserver must be called on the main thread

### ISSUE THREAD

**Issue by DCKT** [expo/expo#13128]
### Summary

Hello,

When I try to initialize Segment, I receive this error : 

> [Unhandled promise rejection: Error: Encountered an exception while calling native method: Exception occurred while executing exported method initialize on module ExponentSegment: Method addObserver must be called on the main thread]

This has been tested with Expo Go on Android device.

Cheers 😄 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41.0.1

### Environment

  Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /var/folders/k6/cqlnsz8x0756r83kbyb0s2700000gp/T/fnm-shell-5389680/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - /var/folders/k6/cqlnsz8x0756r83kbyb0s2700000gp/T/fnm-shell-5389680/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/colisweb/.rvm/gems/jruby-9.2.13.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

[Here is a minimalistic repo](https://github.com/DCKT/expo-segment-bug/tree/main)

**Comment by eaclarich** [comment]
Got exactly the same problem on Android. Here's a question I posted to the forum about a week ago on this very same issue: 
[](https://forums.expo.io/t/android-11-segment-initialize-fails-with-unhandled-promise-rejection/52879)https://forums.expo.io/t/android-11-segment-initialize-fails-with-unhandled-promise-rejection/52879

It might be related to this workaround in segmentio/analytics-reac-native: 
[](https://github.com/segmentio/analytics-react-native/pull/256)https://github.com/segmentio/analytics-react-native/pull/256

My expo diagnostics:
  Expo CLI 4.4.8 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.8
    Expo Workflow: managed

**Comment by viktor992** [comment]
Same here. For some reason, our app started showing this warning on Android a week ago. There are no recent events on Segment since then. I tried with older versions of our app but the warning is still there.

This works fine in iOS though.

```
  Expo CLI 4.5.2 environment info:
    System:
      OS: Linux 5.4 Linux Mint 20 (Ulyana)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/bin/yarn
      npm: 7.16.0 - /usr/local/bin/npm
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed
```

**Comment by jarredt** [comment]
Same here for bare workflow, but only when we're using Expo Go client -- seems to initialize fine on a fully ejected build.

**Comment by rvieceli** [comment]
Also here, after upgrade to SDK41, only iOS events.

```
Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28
        Build Tools: 30.0.2
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.12.63 => 0.12.76 
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed
```

**Comment by hochungwong** [comment]
I still got the exact same error after upgrading to `expo-analytics-segment@10.2.0`.

**Comment by doutatsu** [comment]
Any updates on this? Observing the same issue on android, no Segment events are being registered as a result

**Comment by mfds** [comment]
Hi! Any chances to get this working on Expo 41? I believe that it has been fixed here https://github.com/expo/expo/pull/13263

**Comment by ajsmth** [comment]
This should be available in Expo 42 - the beta is out now! https://blog.expo.io/expo-sdk-42-beta-is-now-available-e505770389e7

**Comment by snowshiva** [comment]
Any update here?  I have successfully upgraded to Expo 42 beta and I'm still not getting any events in Segment.

**Comment by ajsmth** [comment]
@snowshiva hey there - are you getting this same warning?:

[Unhandled promise rejection: Error: Encountered an exception while calling native method: Exception occurred while executing exported method initialize on module ExponentSegment: Method addObserver must be called on the main thread]

**Comment by snowshiva** [comment]
Yes I have that exact error.  I desperately need to solve this problem, my client is not very happy with me right now as I predicted this would be an easy task and assured them segment would be the way to go.

**Comment by snowshiva** [comment]
`expo diagnostics`

`Expo CLI 4.7.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.2.0 - ~/.asdf/installs/nodejs/14.2.0/bin/node
      Yarn: 1.22.10 - ~/.asdf/installs/nodejs/14.2.0/.npm/bin/yarn
      npm: 6.14.4 - ~/.asdf/installs/nodejs/14.2.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0-beta.1 => 42.0.0-beta.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.1
    Expo Workflow: managed`

**Comment by ajsmth** [comment]
Looks like this issue is related to proguard -- if you have a bare workflow you should be able to update your proguard config to work around this issue for now:

https://github.com/expo/expo/pull/13425/files

**Comment by snowshiva** [comment]
So if we have a managed expo project, segment will not work with android at all for the time being.  Is that correct?

**Comment by ajsmth** [comment]
Yes that's right - this should make it into the next SDK 42 beta release and you can use it then

**Comment by snowshiva** [comment]
Thank you much for the update.  Now that I've already updated to SDK 42 beta I'll go figure out where to watch and see when it is updated.  Appreciate your responses

**Comment by mfds** [comment]
@ajsmth is the next beta release going to be mentioned on the Expo blog?

**Comment by ajsmth** [comment]
The beta was just updated so you should be able to install the new Expo Go client (`expo client:install:android`) - I just tested and verified its working now

In the future we'll be documenting updates to the beta during testing, so you'll have better visibility on when changes are available for use!

**Comment by snowshiva** [comment]
Installed and I can confirm it is working!  Thank you so much for your work @ajsmth.

**Comment by snowshiva** [comment]
@ajsmth I spoke too soon - while data is flowing into segment now, all calls from android are failing because my destination in segment requires userId for `trackWithProperties`, and for some reason that is automatically being passed for my iOS source but not my Android source.  I'm testing now if I can manually include `userId` to fix in the short run but seems like something is still wrong there.

**Comment by MWaqasHussain-dev** [comment]
@snowshiva can you share your code ? it would be helpful for me because stuck in the same issue

and where are you seeing you events that are being triggered?

**Comment by ajsmth** [comment]
@snowshiva are you using the identify call? https://docs.expo.io/versions/latest/sdk/segment/#segmentidentifyuserid

**Comment by snowshiva** [comment]
Yes I am using the identify call - and all events with and without properties work as expected for iOS, but for android any `track` event that I send to segment works fine, but `trackWithProperties` hit segment, but then segment does not send them on to my destination (customer.io) because is says it requires `userId`.   I can see all the failed calls and their payload in the destination Event Delivery tab.  I sure wish we could jump on a google meet to discuss or something, I feel like exchanging messages this way is a difficult way to explain and troubleshoot.  I spent about 4 hours yesterday experimenting including userId as a property, and then as an option since I saw userId in the list of common fields.  I'm basically stabbing blindly but I think something might be wrong when events land from my iOS source they all work properly, but when they hit segment from my android source the behaviour is different.

**Comment by snowshiva** [comment]
An example of a failed call payload:

`{
  "anonymousId": "308c9dfe-5369-4042-96e9-6d65c63793c9",
  "channel": "server",
  "context": {
    "app": {
      "build": "152",
      "name": "Expo Go",
      "namespace": "host.exp.exponent",
      "version": "2.21.2"
    },
    "device": {
      "id": "dbf50a9d2b617b20",
      "manufacturer": "samsung",
      "model": "SM-N960U",
      "name": "crownqltesq",
      "type": "android"
    },
    "ip": "173.195.183.120",
    "library": {
      "name": "analytics-android",
      "version": "4.9.4"
    },
    "locale": "en-US",
    "network": {
      "bluetooth": false,
      "carrier": "Verizon",
      "cellular": false,
      "wifi": true
    },
    "os": {
      "name": "Android",
      "version": "10"
    },
    "screen": {
      "density": 2.625,
      "height": 2094,
      "width": 1080
    },
    "timezone": "America/Los_Angeles",
    "traits": {
      "anonymousId": "308c9dfe-5369-4042-96e9-6d65c63793c9"
    },
    "userAgent": "Dalvik/2.1.0 (Linux; U; Android 10; SM-N960U Build/QP1A.190711.020)"
  },
  "event": "tree - registration",
  "integrations": {},
  "messageId": "e6536ff0-f8d7-42fe-a1a2-fc90a874fb69",
  "originalTimestamp": "2021-06-30T17:19:34.218Z",
  "projectId": "c9wWbBaJpbaQdLg2UBmjg6",
  "properties": {
    "# trees created": 1,
    "type": "tree",
    "userId": "dc4ee655-2679-48ef-628d-d8442cd7df10"
  },
  "receivedAt": "2021-06-30T17:20:04.937Z",
  "sentAt": "2021-06-30T17:20:04.484Z",
  "timestamp": "2021-06-30T17:19:34.671Z",
  "type": "track",
  "version": 2,
  "writeKey": "Hactts0xLZfE9kBmUUlOLuYXS8AFZST0"
}`

**Comment by snowshiva** [comment]
Failed call payload:
```
{
  "anonymousId": "308c9dfe-5369-4042-96e9-6d65c63793c9",
  "channel": "server",
  "context": {
    "app": {
      "build": "152",
      "name": "Expo Go",
      "namespace": "host.exp.exponent",
      "version": "2.21.2"
    },
    "device": {
      "id": "dbf50a9d2b617b20",
      "manufacturer": "samsung",
      "model": "SM-N960U",
      "name": "crownqltesq",
      "type": "android"
    },
    "ip": "173.195.183.120",
    "library": {
      "name": "analytics-android",
      "version": "4.9.4"
    },
    "locale": "en-US",
    "network": {
      "bluetooth": false,
      "carrier": "Verizon",
      "cellular": false,
      "wifi": true
    },
    "os": {
      "name": "Android",
      "version": "10"
    },
    "screen": {
      "density": 2.625,
      "height": 2094,
      "width": 1080
    },
    "timezone": "America/Los_Angeles",
    "traits": {
      "anonymousId": "308c9dfe-5369-4042-96e9-6d65c63793c9"
    },
    "userAgent": "Dalvik/2.1.0 (Linux; U; Android 10; SM-N960U Build/QP1A.190711.020)"
  },
  "event": "tree - registration",
  "integrations": {},
  "messageId": "e6536ff0-f8d7-42fe-a1a2-fc90a874fb69",
  "originalTimestamp": "2021-06-30T17:19:34.218Z",
  "projectId": "c9wWbBaJpbaQdLg2UBmjg6",
  "properties": {
    "# trees created": 1,
    "type": "tree",
    "userId": "dc4ee655-2679-48ef-628d-d8442cd7df10"
  },
  "receivedAt": "2021-06-30T17:20:04.937Z",
  "sentAt": "2021-06-30T17:20:04.484Z",
  "timestamp": "2021-06-30T17:19:34.671Z",
  "type": "track",
  "version": 2,
  "writeKey": "Hactts0xLZfE9kBmUUlOLuYXS8AFZST0"
}

**Comment by snowshiva** [comment]
in the example above I have tried to add userId as a property, but that doesn't seem to work either.

**Comment by rvieceli** [comment]
To track userId need to use `identifyWithTraits`

**Comment by snowshiva** [comment]
Yes, at user creation I use `identifyWithTraits` for every user:

```
useEffect(() => {
  (async () => {
    if (registerResponse) {
      const { userId, accessToken } = registerResponse.register.apiToken;
      await AsyncStorage.setItem(ACCESS_TOKEN, accessToken);
      await AsyncStorage.setItem('USER_ID', userId);

      client.writeQuery({
        query: USER_ID,
        data: { getCurrentUserId: userId },
      });
      const { firstName, lastName, zip } = route.params;
      const displayName = `${firstName} ${lastName.charAt(0).toUpperCase()}`;
      createUserSettings({ variables: { userId, zip, displayName } });

      Segment.identifyWithTraits(userId,{
        first_name: firstName,
        last_name: lastName,
        email: email,
      })
    }
  })();
}, [registerResponse]);

**Comment by snowshiva** [comment]
And for iOS all my events (both track and trackWIthProperties) work as expected for all users.  From my android source however, all events hit segment, but then fail to be sent on to my destination because Segment says userId is required and not present.  In the destination Event Delivery tab I find this error for all trackWithProperties events:

```
userId Required
Our Customer.io destination requires a userId in all your event payloads before Segment will attempt to send events to Customer.io.

**Comment by snowshiva** [comment]
This issue is closed, should I create a new one?  I'm honestly a little green when it comes to protocol for communicating about issues in github.  I've not really done it before, thank you for your patience.  I need help, and hopefully if anyone else is having issues it can help them too.

**Comment by ajsmth** [comment]
@snowshiva can you create a new issue with a minimal reproduction? (e.g an example app with the most basic implementation that shows what you are describing above)

**Comment by snowshiva** [comment]
@ajsmth I will try, that said I am new to expo and inherited this existing application so I'm not sure when I will get that done.  Also, with the external dependencies of a segment account and customer.io account I'm honestly feeling a little overwhelmed figuring out how to set that all up in a minimal app, I will try however.

**Comment by ajsmth** [comment]
okay great - I would do the following: 
- init a new expo project: `expo init`: https://docs.expo.io/workflow/expo-cli/#expo-init
- upgrade to sdk 42: `EXPO_BETA=1 expo upgrade`
- install segment: `expo install expo-analytics-segment`: https://docs.expo.io/versions/latest/sdk/segment/
- reproduce the issue you are having with the `userId` above

**Comment by mattmiranda** [comment]
> Failed call payload:
> 
> ```
> {
>   "anonymousId": "308c9dfe-5369-4042-96e9-6d65c63793c9",
>   "channel": "server",
>   "context": {
>     "app": {
>       "build": "152",
>       "name": "Expo Go",
>       "namespace": "host.exp.exponent",
>       "version": "2.21.2"
>     },
>     "device": {
>       "id": "dbf50a9d2b617b20",
>       "manufacturer": "samsung",
>       "model": "SM-N960U",
>       "name": "crownqltesq",
>       "type": "android"
>     },
>     "ip": "173.195.183.120",
>     "library": {
>       "name": "analytics-android",
>       "version": "4.9.4"
>     },
>     "locale": "en-US",
>     "network": {
>       "bluetooth": false,
>       "carrier": "Verizon",
>       "cellular": false,
>       "wifi": true
>     },
>     "os": {
>       "name": "Android",
>       "version": "10"
>     },
>     "screen": {
>       "density": 2.625,
>       "height": 2094,
>       "width": 1080
>     },
>     "timezone": "America/Los_Angeles",
>     "traits": {
>       "anonymousId": "308c9dfe-5369-4042-96e9-6d65c63793c9"
>     },
>     "userAgent": "Dalvik/2.1.0 (Linux; U; Android 10; SM-N960U Build/QP1A.190711.020)"
>   },
>   "event": "tree - registration",
>   "integrations": {},
>   "messageId": "e6536ff0-f8d7-42fe-a1a2-fc90a874fb69",
>   "originalTimestamp": "2021-06-30T17:19:34.218Z",
>   "projectId": "c9wWbBaJpbaQdLg2UBmjg6",
>   "properties": {
>     "# trees created": 1,
>     "type": "tree",
>     "userId": "dc4ee655-2679-48ef-628d-d8442cd7df10"
>   },
>   "receivedAt": "2021-06-30T17:20:04.937Z",
>   "sentAt": "2021-06-30T17:20:04.484Z",
>   "timestamp": "2021-06-30T17:19:34.671Z",
>   "type": "track",
>   "version": 2,
>   "writeKey": "Hactts0xLZfE9kBmUUlOLuYX00000000"
> }
> ```

@snowshiva I was having the same issue a couple of days ago and I fixed my bug today. I was somehow calling Segment.identify() before Segment.initialize(). I fixed my flow and now every Segment.track() call contains the userId as expected. 
I hope this helps.
