### ISSUE TITLE
Jest transform failure after upgrade to SDK v25

### ISSUE THREAD

**Issue by giautm** [expo/expo#1317]
I got bellow error after upgraded, but the app still working fine.  Did I miss something?
```sh
 FAIL  __test__/App.test.js
  ● Test suite failed to run

    /Users/admin/Devel/xxxx/node_modules/@expo/vector-icons/fonts/Ionicons.ttf:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){


    SyntaxError: Invalid or unexpected token

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:318:17)
      at Object.<anonymous> (node_modules/@expo/vector-icons/Ionicons.js:4:59)
      at Object.get Ionicons [as Ionicons] (node_modules/@expo/vector-icons/index.js:18:8)
```

This is `App.test.js`
```javascript
import React from 'react';
import 'react-native';
import renderer from 'react-test-renderer';

import App from './../App/index';

test('renders without crashing', () => {
  const rendered = renderer.create(<App/>).toJSON();
  expect(rendered).toMatchSnapshot();
});
```

**Comment by cmwall** [comment]
I'm also getting this error. Seems like the error is with trying to render an icon from Ionicons.

**Comment by ide** [comment]
We probably won't be able to get around to looking into this for awhile so help digging into the core of jest / jest-expo / babel would be a help. There's a chance the fix is difficult to find but simple to understand and it has to do with how Babel configs are resolved.

**Comment by brentvatne** [comment]
@cmwall @giautm - can you install `jest-expo@25.1.0-beta.0` and let me know if that resolves the issue? thanks!

**Comment by giautm** [comment]
@brentvatne : Yes, I confirm issue was fixed. Tks Brent. <3

**Comment by ide** [comment]
@brentvatne is a hero -- sounds like this is fixed so we'll publish 25.1.0 tomorrow. Closing this out and please feel free to open a new issue if this problem arises in a future SDK version.

**Comment by wcandillon** [comment]
I'd like to confirm the fix and @brentvatne heroism ;-)

**Comment by Dome-GER** [comment]
Unfortunately, the upgrade to version `25.1.0` does not solve my problem. I have the following configuration:
```
  "devDependencies": {
    "babel-eslint": "7.2.3",
    "babel-jest": "^22.2.2",
    "eslint": "4.6.1",
    "eslint-plugin-flowtype": "^2.40.1",
    "eslint-plugin-react": "^7.5.1",
    "husky": "0.14.3",
    "jest": "^22.3.0",
    "jest-expo": "^25.1.0",
    "remotedev-rn-debugger": "^0.8.3",
    "rimraf": "^2.6.1",
    "ts-jest": "^22.0.4",
    "tslint": "^5.6.0"
  },
```
```
"dependencies": {
    "@expo/vector-icons": "^6.2.2",
    "@types/jest": "^22.1.2",
    "@types/react": "^16.0.38",
    "@types/react-native": "^0.52.10",
    "buffer": "^5.0.8",
    "concurrently": "^3.5.0",
    "expo": "^25.0.0",
    "js-base64": "^2.4.3",
    "lodash": "4.13.1",
    "native-base": "^2.3.8",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-auth0": "^1.2.2",
    "react-native-elements": "^0.19.0",
    "react-native-scalable-image": "^0.2.2",
    "react-native-scripts": "1.11.1",
    "react-navigation": "^1.0.0-beta.27",
    "react-navigation-is-focused-hoc": "1.0.0",
    "react-redux": "5.0.5",
    "react-test-renderer": "16.2.0",
    "redux": "3.7.2",
    "redux-form": "7.2.0",
    "redux-persist": "5.4.0",
    "redux-thunk": "2.2.0",
    "remote-redux-devtools": "0.5.0",
    "typescript": "^2.6.2"
  }
```
`node_modules/.bin/jest` results in
```
Test suite failed to run

    .../node_modules/@expo/vector-icons/fonts/Ionicons.ttf:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){
                                                                                             
    SyntaxError: Invalid or unexpected token
```

**Comment by seyaobey** [comment]
Any progress on this issue? I have tried every possible solution found out there: stackoverflow, github...I still get the above error.


![error](https://user-images.githubusercontent.com/2738569/38030142-b7248ade-328f-11e8-94fd-2fa9b1436870.png)

This is my package.json content:

```
{
  "name": "__app_name",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@types/jest": "^22.0.0",
    "@types/react": "^16.0.38",
    "@types/react-native": "^0.52.0",
    "@types/react-native-loading-spinner-overlay": "^0.5.0",
    "@types/react-native-vector-icons": "^4.3.1",
    "@types/react-navigation": "^1.0.19",
    "@types/react-test-renderer": "^16.0.0",
    "babel-jest": "^22.4.3",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "jest-expo": "^25.1.0-beta.0",
    "react-native-scripts-ts": "1.11.4",
    "react-native-typescript-transformer": "^1.2.3",
    "react-test-renderer": "16.2.0",
    "ts-jest": "^22.0.4",
    "tslib": "^1.7.1",
    "typescript": "^2.7.0"
  },
  "main": "./node_modules/react-native-scripts-ts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts-ts start",
    "eject": "react-native-scripts-ts eject",
    "android": "react-native-scripts-ts android",
    "ios": "react-native-scripts-ts ios",
    "test": "node node_modules/jest/bin/jest.js --no-cache"
  },
  "jest": {
    "globals": {
      "ts-jest": {
        "useBabelrc": true
      }
    },
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "preset": "jest-expo",
    "testMatch": [
      "**/__tests__/**/*.[tj]s?(x)",
      "**/?(*.)(spec|test).[tj]s?(x)"
    ],
    "transform": {
      "^.+\\.tsx?$": "ts-jest"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!(react-native|lottie-react-native|expo|mobx-react|react-native-maps|react-native-svg|react-native-branch|native-base-shoutem-theme|react-native-easy-grid|react-native-drawer|react-native-vector-icons|react-native-keyboard-aware-scroll-view|react-navigation|native-base|@expo|react-native-scrollable-tab-view)/)"
    ]
  },
  "dependencies": {
    "backendless": "^4.3.5",
    "expo": "^25.0.0",
    "lodash": "4.17.4",
    "mobx": "3.4.1",
    "mobx-react": "4.3.5",
    "native-base": "2.3.5",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-confirmation-code-input": "^1.0.4",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-pin-code": "^0.4.1",
    "react-native-status-bar-height": "^2.0.0",
    "react-native-typography": "^1.3.0",
    "react-navigation": "1.0.0-beta.21"
  }
}
```

This is my .babelrc:

```
{
  "presets": ["babel-preset-expo", "es2015", "stage-0"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    },
    "test": {      
      "plugins": ["transform-es2015-modules-commonjs"]
    }
  }
}

```
