### ISSUE TITLE
Notifications DeviceNotRegistered for every token but mine?

### ISSUE THREAD

**Issue by paddylb** [expo/expo#1330]
Hello

Expo notifications were working perfectly from the Expo client, but any notification I send to users of my standalone iOS app comes back with

```
"data": {
        "status": "error",
        "message": "The recipient \"ExponentPushToken[xxx]\" isn't associated with any device",
        "details": {
            "error": "DeviceNotRegistered"
        }
    }
```

These users have allowed notifications for my App in settings (I've checked personally) and I can see the new tokens in firebase, but all of the tokens seem to be inactive? I can send notifications to my device and it works just fine, but not to anyone else.

Here is the register for notifications code:

```
export async function registerForPushNotificationsAsync(user) {
  const { existingStatus } = await Permissions.getAsync(Permissions.REMOTE_NOTIFICATIONS);
  let finalStatus = existingStatus;


  if (existingStatus !== 'granted') {
    const { status } = await Permissions.askAsync(Permissions.REMOTE_NOTIFICATIONS);
    finalStatus = status;
  }

  // Stop here if the user did not grant permissions
  if (finalStatus !== 'granted') {
    return;
  }

  // Get the token that uniquely identifies this device
  let token = await Notifications.getExpoPushTokenAsync();
  
  // Add token to firebase
  firebase.database().ref('/tokens/'+user).set({'token':token})

}
```

**Comment by Tyldar** [comment]
Same probleme here

**Comment by ide** [comment]
Sorry about this -- we're looking into this issue, which currently appears to be occurring with newly built standalone apps. We'll post here when we have an update.

**Comment by ide** [comment]
We’ve deployed an update to the iOS standalone app builders that fixes this issue.

This incident affected only IPAs built with exp build:ios between 2018-01-22 4:30pm to 2018-01-27 10:05pm (Pacific time). This incident did not affect any previously built IPAs, including IPAs that developers may have published to the App Store.

New standalone apps whose builds started after 2018-01-27 at 10:05pm Pacific time will include the new code that correctly registers for push notifications. Developers who have created builds affected by this incident will need to create new IPAs.

You can get a new standalone app IPA by running exp build:ios. Make sure to bump your IPA’s version number so that you can submit the new build to TestFlight (ios → buildNumber in app.json might help: https://docs.expo.io/versions/latest/guides/configuration.html#buildnumber).

Please feel free to open a new issue if you start a new standalone app build and encounter these same symptoms (and are sure your app is asking for the REMOTE_NOTIFICATIONS permission -- without this, you may see the same symptom).

**Comment by azaabudeen** [comment]
I am still getting this error...on android
{
    "data": {
        "status": "error",
        "message": "SNS failed to send the notification (reason: EndpointDisabled, status code: 400).",
        "details": {
            "error": "DeviceNotRegistered",
            "sns": {
                "statusCode": 400,
                "reason": "EndpointDisabled",
                "__message": "Endpoint is disabled"
            }
        }
    }
}

Notifications seems to work only for me, that too when i am using expo ...when standalone...it wont work

**Comment by AlexanderPPetrov** [comment]
+1 Same issue

**Comment by ide** [comment]
If you are getting DeviceNotRegistered on Android, this most likely means that (a) the user has blocked notifications or hasn’t granted permission for them, (b) the user has uninstalled the app or (c) Google/AWS has blocked delivery to the device for their own reasons.

**Comment by onezerobinary** [comment]
I’m testing with some apps using IOS and Android and I’ve seen that in Android devices the issue is still present even if tha application have all the right settings. Seams that the generated tokens are not valid.

**Comment by AlexanderPPetrov** [comment]
I've just installed on a new device and still getting DeviceNotRegistered. The generated token is a new one and still not working. On iOS everything is working fine.
Can it be connected to a recent slug name changes within the app.json causing issues on Android device?

**Comment by rodrigoHime** [comment]
+1 Same issue on Android.
{
    "data": {
        "status": "error",
        "message": "SNS failed to send the notification (reason: EndpointDisabled, status code: 400).",
         "details": {
             "error": "DeviceNotRegistered",
             "sns": {
                 "statusCode": 400,
                 "reason": "EndpointDisabled",
                 "__message": "Endpoint is disabled"
             }
        }
    }
}

**Comment by Jozsef86** [comment]
+1 same same, Android Standalone

**Comment by fweffort** [comment]
+1 same same, Android Standalone

It seems that google have been targeting expo android standalone apps and disabling the pushtokens really quickly.

https://forums.expo.io/t/bug-error-with-expo-push-notifications-on-android/8179

**Comment by ide** [comment]
Hi everyone - if you are experiencing issues with high rates of DeviceNotRegistered with Android push notifications, we believe this is due to a change that either Google or AWS made. The official workaround is to upgrade to FCM, for which we've written a guide here: https://docs.expo.io/versions/latest/guides/using-fcm.

You can now create a Firebase project, add its credentials to your Expo project (explained in the guide, be careful to follow the steps precisely), and create a new APK. Expo will use your Firebase credentials for sending FCM notifications to all devices that have the new APK installed, and your push notification delivery rate on Android should noticeably improve.
