### ISSUE TITLE
[expo] [android] Navigation Bar not hidden in production build

### ISSUE THREAD

**Issue by oanacioara** [expo/expo#13524]
### Summary

Hi! I have my `app.json` configured to hide the navigation bar on android. https://docs.expo.io/versions/latest/config/app/#androidnavigationbar

This works fine in development mode, using expo, but when I build for production it no longer works.  The navigation bar is not hidden.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41.0.0

### Environment

Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

- generate a new project
- configure app.json to hide the android navigation bar
`"androidNavigationBar": {
      "visible": "sticky-immersive"
    },
`
- build for production `npx eas-cli build --platform all --profile prod --non-interactive`

**Comment by brentvatne** [comment]
hi there! update to sdk 42 and this is resolved :)

**Comment by damianbeles** [comment]
Did update to sdk 42. The issue still persists, the navigation bar is not hidden in prod, only in dev.
