### ISSUE TITLE
iOS: expo-av audio cannot override silent switch unless autoplayed.

### ISSUE THREAD

**Issue by stuckj** [expo/expo#13617]
### Summary

Per the [docs](https://docs.expo.io/versions/latest/sdk/audio/#audiosetaudiomodeasyncmode), you can set the audio for expo-av to override the ringer / silent switch on an iOS device. However, this is not working unless the video is autoplayed. Specifically, if the `shouldPlay` prop is not set or set to false on the video, the video will not have audio on iOS if the silent switch is set to silent when the user presses play on the video. It WILL properly override the silent switch if the video autoplays by having the `shouldPlay` prop set to true (but, this forces you to use autoplay without some hacks).

Here is a simple snack that reproduces the problem: https://snack.expo.io/@stuckj/expo-av-video-silentmode-bug. In the snack, the `shouldPlay={true}` prop is commented out so the audio will not play on an iOS device when you press play on the video if the silent switch if set to silent. If you uncomment that code the audio will work.

NOTE: The audio will continue to work for all videos in the app after autoplaying one unless you reload the app. So, if you comment out the code again it WILL play audio, but if you reload the app it won't play audio anymore.

The snack is based on this [closed issue](https://github.com/expo/expo/issues/7485) where @sethgw was still having problems even after the explanation. Autoplay appears to be the culprit.

UPDATE: This bug is SPECIFICALLY only when the video is started from the thumbnail image produced by the player. If you have `shouldPlay={false}` and programmatically start the video with `video.current.playAsync()` then audio will work properly.

~UPDATE2: This is worse in SDK45. It now won't play with the ringer silent switch with `autoPlay` set to `true` or if you do `video.current.playAsync`. This breaks the only workaround we found making this a more serious issue before we can update to SDK 45.~

UPDATE3: SDK 45 is no worse. You just have to make sure to switch to using the `InterruptionModeIOS` and `InterruptionModeAndroid` enumerations when you update to SDK 45.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42 - 45.

~In SDK 45 this bug is much worse (won't play audio with the ringer silent switch even if `autoPlay` is set to `true` or if programmatically started).~

### Environment

It's in a snack...so, I'm not sure how to run expo diagnostics on it.

### Reproducible demo or steps to reproduce from a blank project

As mentioned in the summary, this snack replicates it: https://snack.expo.io/@stuckj/expo-av-video-silentmode-bug. See the summary for the caveat about reloading after playing audio successfully.

**Comment by stuckj** [comment]
Just an update on this. I updated the snack to SDK 43 and this issue still exists.

**Comment by MaximeCrp** [comment]
What I have on my project is it overrides silent switch but not if user triggers it while being in the app

**Comment by stuckj** [comment]
Yeah, that's what I said in the report up above in the `UPDATE`:
> UPDATE: This bug is SPECIFICALLY only when the video is started from the thumbnail image produced by the player. If you have shouldPlay={false} and programmatically start the video with video.current.playAsync() then audio will work properly.

The problem is only if you don't have autoplay on and playing is started from a user clicking on the video thumbnail. If you programmatically start it it will work as well.

**Comment by stuckj** [comment]
Still seems broken on the latest. Perhaps it'll finally be fixed in SDK 44?

**Comment by thevinter** [comment]
Can confirm the issue still exists

**Comment by TheRealMikeD** [comment]
Issue still exists as of April 30, 2022.
RN 0.64.3
expo 44
expo-av 10.2.0

**Comment by stuckj** [comment]
NOTE: This bug is much worse from what I can see (in the snack) on expo SDK 45. It now doesn't play audio with the ringer silent switch even if you set `autoPlay` to `true` or if you programmatically start the video. This effectively makes the ringer silent switch a mute switch for video.

I updated the snack to SDK 45 to demonstrate the behavior.

**Comment by stevehs17** [comment]
@stuckj I am also seeing this.

**Comment by zgordon02** [comment]
Any updates on this? The `playsInSilentModeIOS` prop is useless with no workarounds

**Comment by stuckj** [comment]
@brentvatne, any idea if this is on expo's radar? I'm concerned that in SDK 45 the problem appears worse and there may be no workaround. We're still using SDK 44 for our project right now, but at some point we'll need to upgrade and this will cause problems for all videos in our apps. People definitely use the ringer / silent switch on iOS. We can build custom controls, but I kinda hope this gets fixed instead.

**Comment by brentvatne** [comment]
this was not on our radar, sorry. if someone wants to open a pr to resolve this it would be welcome. we may be able to revisit in the sdk 47 cycle

**Comment by stuckj** [comment]
Thanks, glad to hear it's accepted now at least. Given that it might not be until SDK 47 I can try looking into the root cause before we update to SDK 45 since it will likely be a blocker for us.

**Comment by stuckj** [comment]
UPDATE! I was wrong about SDK 45 being worse. The constants for configuring ducking just changed to an enumeration and I hadn't updated the snack (or our app's real code). After updating in both the original workaround I've been using since SDK 42 continues to work (play programmatically). Ideally, it would still be fixed when using the play button on the player when `shouldPlay` is set to `false`.

**Comment by stuckj** [comment]
There's a workaround still, but this is still broken.

**Comment by megantaylor** [comment]
issue still exists :(

**Comment by adamtsai1** [comment]
Issue still exists on SDK 48

**Comment by anhkieet** [comment]
This issue still exists on Expo 49

**Comment by anhkieet** [comment]
```
diff --git a/node_modules/expo-av/ios/EXAV/EXAVPlayerData.m b/node_modules/expo-av/ios/EXAV/EXAVPlayerData.m
index 5650c95..0164931 100644
--- a/node_modules/expo-av/ios/EXAV/EXAVPlayerData.m
+++ b/node_modules/expo-av/ios/EXAV/EXAVPlayerData.m
@@ -198,8 +198,8 @@ NSString *const EXAVPlayerDataObserverMetadataKeyPath = @"timedMetadata";
 
 - (NSError *)_tryPlayPlayerWithRateAndMuteIfNecessary
 {
-  if (_player && [self _shouldPlayerPlay]) {
     NSError *error = [_exAV promoteAudioSessionIfNecessary];
+  if (_player && [self _shouldPlayerPlay]) {
     if (!error) {
       _player.muted = _isMuted;
       _player.rate = [_rate floatValue];
@@ -1002,7 +1002,7 @@ void EXTapProcess(MTAudioProcessingTapRef tap, CMItemCount numberFrames, MTAudio
   if (_player && ([self _isPlayerPlaying] || [self _shouldPlayerPlay])) {
     return _isMuted ? EXAVAudioSessionModeActiveMuted : EXAVAudioSessionModeActive;
   }
-  return EXAVAudioSessionModeInactive;
+  return EXAVAudioSessionModeActive;
 }
 
 - (void)appDidForeground

```

I solved this issue by applying this patch

**Comment by guilhermeguidetti** [comment]
issue still exists on Expo 50
"expo-av": "~13.10.5"

**Comment by Adriano2108** [comment]
Still broken. Workaround for me is to use state shouldPlay initially as true, and then once video has loaded set it to false. It works.

 `             
  const handlePlaybackStatusUpdate = playbackStatus => {
    if (playbackStatus.isLoaded && shouldPlay) {
      setShouldPlay(false);
    }
  };

              <Video
                source={{ uri }}
                style={styles.file}
                resizeMode="cover"
                useNativeControls={true}
                autoPlay={true}
                playsInSilentModeIOS={true}
                isMuted={false}
                shouldPlay={shouldPlay}
                onPlaybackStatusUpdate={handlePlaybackStatusUpdate}
              />
`

**Comment by WayneKim92** [comment]
```
await Audio.setAudioModeAsync({ playsInSilentModeIOS: true });
```

**Comment by zgordon02** [comment]
This thread mentions up to SDK 45, but @WayneKim92 's solution of 
`Audio.setAudioModeAsync({ playsInSilentModeIOS: true })` works great in SDK 51. I think that is the correct solution

**Comment by atgctg** [comment]
For `expo-audio`:

```ts
import { AudioModule } from 'expo-audio'

AudioModule.setAudioModeAsync({
  playsInSilentMode: true,
})
```

**Comment by ngdbao** [comment]
```ts
AudioModule.setAudioModeAsync({
  allowsRecording: false,
  playsInSilentMode: true
})
```

It fixes "low-volume" issue for iOS with expo-audio too.
