### ISSUE TITLE
[expo-splash-screen] Showing an alert prevents splash screen from hiding on iOS

### ISSUE THREAD

**Issue by srmagura** [expo/expo#14099]
### Summary

If an alert is displayed while the splash screen is open, the splash screen never goes away. This is only an issue on iOS. The problem does not occur in vanilla React Native projects created using `react-native init`.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed and bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.6.2 - /opt/homebrew/bin/node
      Yarn: 1.22.11 - /opt/homebrew/bin/yarn
      npm: 7.20.3 - /opt/homebrew/bin/npm
      Watchman: 2021.08.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

# Reproducible demos
Minimal repros in both the managed and bare workflows: https://github.com/srmagura/ExpoSplashScreenRepro. The repository's README contains instructions for running each project.

# Why does this matter?
I'm sure this seems like an inconsequential issue, but it makes the `react-native-background-location` package unusable in production apps. If location permission is denied, `react-native-background-location` shows an alert guiding the user to enable the location permission when the app starts up. The alert prevents the splash screen from going away. See https://github.com/transistorsoft/react-native-background-geolocation/issues/1373.

It's debatable whether this is a problem with Expo or `react-native-background-location`, but I'm leaning towards it being an Expo problem.

# Error messages

## ExpoManagedSplashScreenRepro
```
[Unhandled promise rejection: Error: No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.]
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:50 in promiseMethodWrapper
at node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-splash-screen/build/SplashScreen.js:19:7 in hideAsync
at node_modules/expo-splash-screen/build/SplashScreen.js:19:7 in hideAsync
at App.tsx:43:12 in useCallback$argument_0
at App.tsx:36:39 in useCallback$argument_0
```

## ExpoBareSplashScreenRepro
```
No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.
```

# Related issue
https://github.com/expo/expo/issues/7689. The discussion got pretty scattered and the issue was eventually closed, but it does seem related. A user named marcusmc [commented](https://github.com/expo/expo/issues/7689#issuecomment-899049672) that he also experienced the splash screen never disappearing when an alert was shown at startup.

**Comment by srmagura** [comment]
**Workaround**: Create a new React Native project (not using `expo init`), copy your code into it, and use `react-native-bootsplash` instead of `expo-splash-screen`.

**Comment by Kudo** [comment]
@srmagura thanks for reporting this issue with a great minimal reproducible example. #14208 should fix this issue. will let you know once we landed the fix.

**Comment by Kudo** [comment]
@srmagura `expo-splash-screen@0.11.4` published with the fixes. please upgrade expo-splash-screen and take a look. let us know if you still encounter problems. thanks for reporting this issue. your minimal reproducible example is really helpful 👍

**Comment by amberv0** [comment]
The issue is still present, for me it happens when i show the modal (from react-native) BEFORE hiding the splash screen.

**Comment by AmigoDeluxe** [comment]
> The issue is still present, for me it happens when i show the modal (from react-native) BEFORE hiding the splash screen.

Man, you said the magic word (Modal) and that got me thinking. After some testing, it appears that the modal was the issue for me as well so here is what I did (I know it is low-tech but any better solutions are welcome):

```
  useEffect(() => {
    mounted = true;
    setTimeout(() => {
      firstRunCheck();
    }, 1000);

    return function cleanup() {
      mounted = false;
    };
  }, []);
```

This is my implementation of the "First run check" so as you can see, I am using useEffect to run the check when the app launches and then I use a setTimeout in it to wait for 1 second before running the function which triggers the modal. 

I hope this helps.

**Comment by steviec** [comment]
I'm encountering the same issue. If a modal shows before the splash screen hiding is called, the splash screen never hides, even after closing the modal. It's like the call to close it just gets swallowed.

**Comment by worxadmin** [comment]
We're also encountering this issue on expo 47.0.13. We're using redux and have the default state display a loading modal right away. When loading is updated to false, the modal disappears but the app stays on the splash screen.

**Comment by benjaminhera** [comment]
I don't use custom components, I use a library called [react-native-ble-plx](https://github.com/dotintent/react-native-ble-plx), that has an expo-plugin. The problem arises from the fact that the ble package instantly tries to ask the user for bluetooth permissions on the first run, which the splash screen package doesn't like... I'm thinking of migrating to another splash screen solution until I can explicitly ask the user for the permission, and no modal is showing automatically...

**Comment by federicogomezlara** [comment]
This issue still occurs, why is this closed? I'm using Overlay from React Native Elements and when I show my Overlay before the Splash Screen hides, it gets stuck there

**Comment by LeCiel** [comment]
Still getting the issue, with expo 51 & expo-splash-screen 0.27.6.

**Comment by a-zen** [comment]
Same here on expo 51 & expo-splash-screen 0.27.6, also only on ios
