### ISSUE TITLE
RN 0.65.1 crashes while invoking "addProxiedListener"

### ISSUE THREAD

**Issue by Isaacmeedinaa** [expo/expo#14297]
### Summary

I have successfully implemented Expo notifications into a bare React Native application. Works both for Android and iOS. The only issue is that when it calls to get the device push token on a `useEffect`, the app shows an error. 

![WhatsApp Image 2021-09-06 at 12 20 54 AM](https://user-images.githubusercontent.com/29049237/132165305-b79c96cf-6f70-497b-84f8-5d190c7cd9cb.jpeg)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.19.1 - /usr/local/bin/npm
      Watchman: 2021.08.30.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2 => 17.0.2 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ^0.65.1 => 0.65.1 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

```
const registerForPushNotificationsAsync = async () => {
    let experienceId = undefined;

    if (!Constants.manifest) {
      experienceId = "@isaac_dopshop/dopshop";
    }

    const { status: existingStatus } =
      await Notifications.getPermissionsAsync();

    console.log(existingStatus);

    let finalStatus = existingStatus;

    if (existingStatus !== "granted") {
      const { status } = await Notifications.requestPermissionsAsync();
      finalStatus = status;
    }

    if (finalStatus !== "granted") {
      console.log("Failed to get push token for push notification!");
      return;
    }

    const token = (
      await Notifications.getExpoPushTokenAsync({ experienceId: experienceId })
    ).data;
    setToken(token);
  };
```

**Comment by Yonom** [comment]
Duplicate of https://github.com/expo/expo/issues/14186

@Isaacmeedinaa can you install react-native-unimodules@0.14.8 and check your yarn.lock to ensure that @unimodules/core@7.1.2 and @unimodules/react-native-adapter@6.3.7 are installed?

See https://github.com/expo/expo/issues/14186#issuecomment-915371870

**Comment by cruzach** [comment]
Fixed by the above

**Comment by HarshavardhanRai** [comment]
I tried to install react-native-unimodules@0.14.8 but it gives error as No matching verions found for react-native-unimodules@0.14.8
Im still getting the error unrecognised selector instance error.
Can any one please help me to solve the problem.

Thanks
