### ISSUE TITLE
Expo-AV Sound.playAsync() doesn't work with expo-av 9.2.3 and Expo 42.0.3

### ISSUE THREAD

**Issue by Madhav-Malhotra** [expo/expo#14291]
### Summary

I'm initialising a **stock app with Managed workflow and trying to play an mp3 file** using `expo-av (9.2.3)`. I saw [another issue](https://github.com/expo/expo/issues/13623) where no sound was playing on Moto G5, Android 8. For me, **sound doesn't play for Moto G6 Android 9, iPhone SE iOS 14.6, OR on the web.** `App.json` and `package.json` attached.

![app json](https://user-images.githubusercontent.com/47190635/132108706-fe4d14d0-e680-4051-8527-fee992d8826e.png) 
![package json](https://user-images.githubusercontent.com/47190635/132108742-01e7718d-114b-4430-ae75-44a8c887b150.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, Web

### SDK Version (managed workflow only)

42.0.3

### Environment

Expo CLI 4.9.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Run `expo init my-app`
2. Run `expo install expo-av`
3. Add some mp3 file to the root directory. I'm using [this one](https://sndup.net/2bjt).
4. Copy this code into `app.js`
```
import { StatusBar } from 'expo-status-bar';
import React, { useEffect } from 'react';
import { Audio } from 'expo-av';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  useEffect(() => {
    playSound()
  }, []);

  async function playSound() {
    const sound = new Audio.Sound();
    try {
      await sound.loadAsync(require('./sound.mp3'));
      await sound.playAsync();
      await sound.unloadAsync();
    } catch (error) {
      console.error(error)
    }
  }

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
5. Run `expo start`
6. Preview on Expo Go app on Moto G6 Android 9.0, iPhone SE iOS 14.6. Or open on web by entering `w` with terminal.

**Comment by vgrocha** [comment]
I believe I ran into this. Did you try `sound.replayAsync()`, or setting the position before the play? I.e.
```
await sound.loadAsync(require('./sound.mp3'));
await sound.setPositionAsync(0);
await sound.playAsync();
```

**Comment by Madhav-Malhotra** [comment]
@vgrocha Thank you for the suggestion! I hadn't heard of those. When I just tried these, the sound still didn't work unfortunately :/
```
await sound.loadAsync(require('./sound.mp3'));
await sound.setPositionAsync(0);
await sound.playAsync();
```
```
await sound.loadAsync(require('./sound.mp3'));
await sound.replayAsync();
```

**Comment by filipecatraia** [comment]
Hey, I just wanted to let you know I've reproduced the issue successfully, after noticing the last Expo upgrade made sound stop working in our app. Your basic example showcases the issue perfectly.

**Comment by Madhav-Malhotra** [comment]
> Hey, I just wanted to let you know I've reproduced the issue successfully, after noticing the last Expo upgrade made sound stop working in our app. Your basic example showcases the issue perfectly.

Happy to hear it @filipecatraia :-) If there's another version of Expo and Expo-AV that works, I'd love to know!

**Comment by pcnudde** [comment]
Hi, I'm also facing this issue. Are there any updates on this?

**Comment by gsevla** [comment]
This problem is already solved?

I'm facing an similar issue with an Moto G7 (Android 10). Already tested on Galaxy M30 (Android 10) and couldn't reproduce.

I'm using replaySound and sometimes it plays and others don't.

But I'm using expo modules SDK 44 (project was created with rn cli).

**Comment by gsevla** [comment]
> Any updates? Similar issue. expo@42.0.1, expo-av@9.2.3, bare workflow. Very often short sounds (for click responds, successful/unsuccessful actions) are not playing for the first time during class component lifecycle. I've made listener for these sounds. During unsuccessful play "setOnPlaybackStatusUpdate" called 2 times and 5 times on successful.
> 
> ```
> const {sound: incorrectSound} = await Audio.Sound.createAsync(require('./../../sounds/incorrect.mp3'));
> this.incorrectSound = incorrectSound;
> this.incorrectSound.setOnPlaybackStatusUpdate(async(r)=>{
>             console.log(r);
> });
> ```
> 
> Play without sound:
> 
> ```
>  LOG  {"androidImplementation": "SimpleExoPlayer", "didJustFinish": false, "durationMillis": 313, "isBuffering": false, "isLoaded": true, "isLooping": false, "isMuted": false, "isPlaying": true, "playableDurationMillis": 0, "positionMillis": 0, "progressUpdateIntervalMillis": 500, "rate": 1, "shouldCorrectPitch": false, "shouldPlay": true, "uri": "/assets/sounds/incorrect.mp3", "volume": 1}
>  LOG  {"androidImplementation": "SimpleExoPlayer", "didJustFinish": true, "durationMillis": 313, "isBuffering": false, "isLoaded": true, "isLooping": false, "isMuted": false, "isPlaying": false, "playableDurationMillis": 313, "positionMillis": 313, "progressUpdateIntervalMillis": 500, "rate": 1, "shouldCorrectPitch": false, "shouldPlay": true, "uri": "/assets/sounds/incorrect.mp3", "volume": 1}
> ```
> 
> Successfull play:
> 
> ```
>  LOG  {"androidImplementation": "SimpleExoPlayer", "didJustFinish": false, "durationMillis": 313, "isBuffering": false, "isLoaded": true, "isLooping": false, "isMuted": false, "isPlaying": false, "playableDurationMillis": 0, "positionMillis": 0, "progressUpdateIntervalMillis": 500, "rate": 1, "shouldCorrectPitch": false, "shouldPlay": true, "uri": "/assets/sounds/incorrect.mp3", "volume": 1}
>  LOG  {"androidImplementation": "SimpleExoPlayer", "didJustFinish": false, "durationMillis": 313, "isBuffering": true, "isLoaded": true, "isLooping": false, "isMuted": false, "isPlaying": false, "playableDurationMillis": 0, "positionMillis": 0, "progressUpdateIntervalMillis": 500, "rate": 1, "shouldCorrectPitch": false, "shouldPlay": true, "uri": "/assets/sounds/incorrect.mp3", "volume": 1}
>  LOG  {"androidImplementation": "SimpleExoPlayer", "didJustFinish": false, "durationMillis": 313, "isBuffering": false, "isLoaded": true, "isLooping": false, "isMuted": false, "isPlaying": true, "playableDurationMillis": 313, "positionMillis": 0, "progressUpdateIntervalMillis": 500, "rate": 1, "shouldCorrectPitch": false, "shouldPlay": true, "uri": "/assets/sounds/incorrect.mp3", "volume": 1}
>  LOG  {"androidImplementation": "SimpleExoPlayer", "didJustFinish": false, "durationMillis": 313, "isBuffering": false, "isLoaded": true, "isLooping": false, "isMuted": false, "isPlaying": true, "playableDurationMillis": 313, "positionMillis": 124, "progressUpdateIntervalMillis": 500, "rate": 1, "shouldCorrectPitch": false, "shouldPlay": true, "uri": "/assets/sounds/incorrect.mp3", "volume": 1}
>  LOG  {"androidImplementation": "SimpleExoPlayer", "didJustFinish": true, "durationMillis": 313, "isBuffering": false, "isLoaded": true, "isLooping": false, "isMuted": false, "isPlaying": false, "playableDurationMillis": 313, "positionMillis": 313, "progressUpdateIntervalMillis": 500, "rate": 1, "shouldCorrectPitch": false, "shouldPlay": true, "uri": "/assets/sounds/incorrect.mp3", "volume": 1}
> ```

Already passed through this.

Check if on top of your component that playSound you have an ScrollView or any other VirtualList. I have and remove the prop keyboardShouldPersistTaps="handled". And into your pressable that plays the sound, handle with bubble effect using the prop onStartShouldSetResponderCapture={(evt) => true}.

**Comment by Brenndoerfer** [comment]
Still not able to play a sound following the example here https://docs.expo.dev/versions/latest/sdk/audio/

```json
"expo": "~44.0.0",
    "expo-asset": "~8.4.6",
    "expo-av": "~10.2.0",
    "expo-constants": "~13.0.0",
    "expo-font": "~10.0.4",
    "expo-linking": "~3.0.0",
    "expo-splash-screen": "~0.14.0",
    "expo-status-bar": "~1.2.0",
    "expo-web-browser": "~10.1.0",
```

**Comment by TheFloatingString** [comment]
I had a similar issue, and solved it by specifying `shouldPlay: true`:

```JavaScript
const _sound = new Audio.Sound();
await _sound.loadAsync(require("./assets/sounds/theme_01.mp3"), {shouldPlay: true});
await _sound.setPositionAsync(0);
await _sound.playAsync();
```

Source: https://stackoverflow.com/questions/65736456/expo-av-audio-not-playing-on-ios-iphone

**Comment by psnet** [comment]
> Very often short sounds (for click responds, successful/unsuccessful actions) are not playing for the first time during class component lifecycle.

This is due to buffering, [docs ](https://docs.expo.dev/versions/v45.0.0/sdk/av/)says about that:

> playbackObject.playAsync()
This is equivalent to playbackObject.setStatusAsync({ shouldPlay: true }).
**Playback may not start immediately after calling this function for reasons such as buffering**. Make sure to update your UI based on the isPlaying and isBuffering properties of the AVPlaybackStatus

**Comment by Madhav-Malhotra** [comment]
@TheFloatingString I'll try to modify my code with those changes

**Comment by Madhav-Malhotra** [comment]
@TheFloatingString the code you provided worked for me! 

That said, since time has passed, I couldn't use the old Expo SDK anymore. I upgraded to `"expo": "^45.0.8"` and `"expo-av": "~11.2.3"`. With my old code (see initial post), the new SDK still didn't function. 

But after changing my function code AND the Expo SDK, it works! Though I'm unsure if it'd work with the original Expo SDK I used 😕 
```
async function playSound() {
    const sound = new Audio.Sound();
    try {
      await sound.loadAsync(require('./sound.mp3'), {shouldPlay: true});
      await sound.setPositionAsync(0);
      await sound.playAsync();
    } catch (error) {
      console.error(error)
    }
  }
```
