### ISSUE TITLE
Ask async for Camera roll permission does not seem to give the right permission

### ISSUE THREAD

**Issue by verzil** [expo/expo#1435]
When asking async for camera roll permission, upon granting the permission, the promise resolve with a status of denied, But when ask again using getAsync it says granted

1. const { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL)

### Expected Behavior

resolve to be granted

### Current Behavior
resolve to denied,
use Permissions.getAsync(Permissions.CAMERA_ROLL)
resolve to granted

**Comment by terribleben** [comment]
Thanks! We [pushed a fix for this](https://github.com/expo/expo-sdk/commit/bc04716dfc0305e0df807b0d9acc8abc02edc61f) which should be available in the next version of our SDK.

**Comment by ro1414** [comment]
Will this also fix the issue on iOS where the CAMERA_ROLL permission comes back as "granted" both when it hasn't been granted **yet** (should be "undetermined") and even **after** it has been denied?

[Snack here](https://snack.expo.io/@robrien14/camera-roll-permissions-test)

**Comment by yehudahkay** [comment]
+1 confirming that CAMERA_ROLL and CAMERA permissions come back as granted on ios before being determined and also after being denied

**Comment by FreakTheMighty** [comment]
I'm seeing the same issue on 25 when asking for location permission. It responds `denied` despite being granted. This worked on 25 at some point.

**Comment by nikki93** [comment]
@FreakTheMighty which platform (iOS / Android -- Simulator / Device) are you having this on?

**Comment by FreakTheMighty** [comment]
iOS/Simulator

**Comment by nikki93** [comment]
@FreakTheMighty is it different on device?

**Comment by alizahid** [comment]
Seeing this with `29.0.0`, too.

**Comment by aewaldman** [comment]
Seeing this with 29.0.0 as well.  I've seen the simulator permissions work for CAMERA_ROLL, but it never works on an IOS device and I'm not able to get CAMERA permissions to work on a physical device. Have not tried Android.

**Comment by BenBrostoff** [comment]
Hey all - I'm seeing this on `29.0.0` for a detached iOS app.

**Comment by alizahid** [comment]
Fixed in `30.0.1`.

**Comment by nickjuntilla** [comment]
Still broken in 31.0.0 Permissions.getAsync(Permissions.CAMERA_ROLL) is undefined in Android 8.1

**Comment by pencilcheck** [comment]
I'm on SDK 30.0.0, calling `await Permissions.getAsync(Permissions.CAMERA_ROLL)` gives me an error about `getAsync is not defined on null`, to my knowledge, Permissions exists, but the ReactNative Proxy Permissions inside the Permissions (somehow they used the same name which adds more confusion, is somehow not defined....

**Comment by esamelson** [comment]
Hi, the issue here has been long since resolved. If you're experiencing a similar issue please open a new ticket and fill out the template there fully, including a clear repro case. Thanks!
