### ISSUE TITLE
Expo Dev Client not showing in full height

### ISSUE THREAD

**Issue by crissanchez8** [expo/expo#15104]
### Summary

I've recently switched from Expo Go to a custom dev client with EAS Build. The problem that I'm facing is that, on my iOS Simulator, my app is not showing at full height. There is a big chunk of black space at the top and bottom of the screen. I expect that my app looks like when it's launched via Expo Go, without empty space.

Current behavior
<img width="267" alt="Captura de Pantalla 2021-11-08 a la(s) 19 32 07" src="https://user-images.githubusercontent.com/16993520/140828657-85519dfd-787b-424e-892c-030a1cf8d75a.png">

Expected behavior
<img width="226" alt="Captura de Pantalla 2021-11-08 a la(s) 19 32 23" src="https://user-images.githubusercontent.com/16993520/140828683-7d4fbff3-d4b8-4062-9f3f-ba840c48814d.png">

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Package versions

expo-dev-client: "^0.5.1"

### Environment

Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.4.1 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.18.1 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.2 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I couldn't reproduce this error yet.

I started a blank project with basic configuration and the development client displayed at full height on the iOS simulator. So the problem should be around my project but not sure what may be triggering this issue.

Blanck project result
<img width="336" alt="Captura de Pantalla 2021-11-08 a la(s) 20 13 51" src="https://user-images.githubusercontent.com/16993520/140833032-ffe54f3d-99ba-4a57-8e18-517b418e0212.png">

To get this result I took the following steps:
1. Run expo init test-app
2. Run eas build:configure
3. Edit eas.json file (same configuration of my project)

```
{
  "build": {
    "release": {},
    "preview": {
      "ios": {
        "developmentClient": true,
        "simulator": true
      },
      "android": {
        "developmentClient": true,
        "buildType": "apk"
      }
    },
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    }
  },
  "submit": {
    "release": {}
  }
}
```

4. Run eas build --platform ios --profile preview
5. Download and install the build in iOS Simulator (Iphone 12 Pro Max - iOS 14.4)
6. Run expo start --dev-client

**Comment by brentvatne** [comment]
the latest expo-dev-client is 0.6.3, you should use that version :)

**Comment by crissanchez8** [comment]
Hi @brentvatne ! I've just updated my expo-dev-client version to 0.6.3 and the issue persists.

I've tested the custom dev client on the Android simulator and it's all right there, so it seems that this issue is only related to the iOS simulator.

**Comment by brentvatne** [comment]
can you update expo-cli to the latest version?

**Comment by brentvatne** [comment]
actually it seems that you have a managed app so that may not be the issue. i'd recommend upgrading your app to sdk 43, or if you can, please provide a reproducible example. it's a bit too difficult to tell what might be going in your case without being able to reproduce.

**Comment by crissanchez8** [comment]
Hey @brentvatne , I've updated my app to sdk 43 and now the issue is fixed :D

So i guess it was something related with the version of the project dependencies.

Thanks for all your support

**Comment by gabekutner** [comment]
My SDK was up to date and this exact thing still happened. Looked through my Info.plist and found it was missing this:
```
<key>UILaunchStoryboardName</key>
<string>LaunchScreen</string>
```
