### ISSUE TITLE
Getting expo-constants warning about Constants.platform.ios.model even though I'm not using it

### ISSUE THREAD

**Issue by rafmrs** [expo/expo#15110]
### Summary

This is the warning I get: 

```
Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45.
```

<img src="https://user-images.githubusercontent.com/44644902/140895154-354051a5-8159-4bd0-8c06-333eb8859585.png" width="320px" />

I searched my app and it seems like I'm not using expo-constants package at all, so it must be imported and used in the SDK right?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

SDK 43. (43.0.2)

### Environment

Expo CLI 4.12.12 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 24, 25, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.2 => 43.0.2 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.12
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Too big of a project

**Comment by Kudo** [comment]
hi there! can you check your `expo-constants` version by `yarn why expo-constants`?  we fixed a related issue in `expo-constants@12.1.3`, not sure if that help for your case.

**Comment by rafmrs** [comment]
Hi, this is the result:

```
expo-constants@12.1.3
node_modules/expo-constants
  expo-constants@"~12.1.3" from expo@43.0.2
  node_modules/expo
    expo@"^43.0.2" from the root project

expo-constants@12.1.3
node_modules/expo-linking/node_modules/expo-constants
  expo-constants@"~12.1.1" from expo-linking@2.4.2
  node_modules/expo-linking
    expo-linking@"~2.4.2" from the root project

expo-constants@12.1.3
node_modules/expo-notifications/node_modules/expo-constants
  expo-constants@"~12.1.2" from expo-notifications@0.13.3
  node_modules/expo-notifications
    expo-notifications@"~0.13.3" from the root project

expo-constants@12.0.0
node_modules/react-native-unimodules/node_modules/expo-constants
  expo-constants@"~12.0.0" from react-native-unimodules@0.15.0
  node_modules/react-native-unimodules
    react-native-unimodules@"^0.15.0" from the root project

expo-constants@12.1.3
node_modules/react-native-unimodules/node_modules/expo/node_modules/expo-constants
  expo-constants@"~12.1.3" from expo@43.0.1
  node_modules/react-native-unimodules/node_modules/expo
    expo@"~43.0.0-beta.0" from react-native-unimodules@0.15.0
    node_modules/react-native-unimodules
      react-native-unimodules@"^0.15.0" from the root project
 ```
 
 Seems like `react-native-unimodules` is requesting 12.0.0

**Comment by rafmrs** [comment]
You're right I forgot about that, thanks.

In the meantime I removed the package, but still getting the same warning. The result of `npm why expo-constants` now is the following:

```
expo-constants@12.1.3
node_modules/expo-constants
  expo-constants@"~12.1.3" from expo@43.0.2
  node_modules/expo
    expo@"^43.0.2" from the root project

expo-constants@12.1.3
node_modules/expo-linking/node_modules/expo-constants
  expo-constants@"~12.1.1" from expo-linking@2.4.2
  node_modules/expo-linking
    expo-linking@"~2.4.2" from the root project

expo-constants@12.1.3
node_modules/expo-notifications/node_modules/expo-constants
  expo-constants@"~12.1.2" from expo-notifications@0.13.3
  node_modules/expo-notifications
    expo-notifications@"~0.13.3" from the root project
 ```

**Comment by Kudo** [comment]
can you share the yellow box warning screenshot after removed `react-native-unimodules`? additionally, what's your `babel-preset-expo` version (`npm why babel-preset-expo`) ?

**Comment by rafmrs** [comment]
Screenshot:
<img src="https://user-images.githubusercontent.com/44644902/141139526-0e74989f-7b46-418a-9229-64267ef6f5d3.png" width="320" />

`npm why babel-preset-expo`:

```
babel-preset-expo@8.5.1
node_modules/babel-preset-expo
  dev babel-preset-expo@"8.5.1" from the root project
  babel-preset-expo@"~8.5.1" from expo@43.0.2
  node_modules/expo
    expo@"^43.0.2" from the root project
```

**Comment by Kudo** [comment]
thank you @rafmrs. alright, i don't come any idea in my mind. can you share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? it's hard for us to troubleshoot a problem we cannot reproduce in house.

**Comment by Kudo** [comment]
i'm glad to hear you solved the problem 🎉    thank you @rafmrs!

**Comment by terrierscript** [comment]
I got same issue.
some modules has this issues?

```
expo-constants@12.1.3
node_modules/expo-constants
  expo-constants@"~12.1.3" from the root project
  expo-constants@"~12.1.3" from expo@43.0.3
  node_modules/expo
    expo@"^43.0.3" from the root project
  peer expo-constants@"*" from sentry-expo@4.0.3
  node_modules/sentry-expo
    sentry-expo@"^4.0.0" from the root project

expo-constants@12.1.2
node_modules/expo-notifications/node_modules/expo-constants
  expo-constants@"~12.1.2" from expo-notifications@0.13.3
  node_modules/expo-notifications
    expo-notifications@"~0.13.3" from the root project

expo-constants@12.1.2
node_modules/expo-firebase-core/node_modules/expo-constants
  expo-constants@"~12.1.1" from expo-firebase-core@4.0.3
  node_modules/expo-firebase-core
    expo-firebase-core@"~4.0.3" from the root project
    expo-firebase-core@"~4.0.3" from expo-firebase-analytics@5.0.3
    node_modules/expo-firebase-analytics
      expo-firebase-analytics@"~5.0.3" from the root project

expo-constants@12.1.2
node_modules/expo-linking/node_modules/expo-constants
  expo-constants@"~12.1.1" from expo-linking@2.4.2
  node_modules/expo-linking
    expo-linking@"~2.4.2" from the root project
```

**Comment by Kudo** [comment]
@terrierscript hi there! it looks like you have the old expo-constants inside other expo modules. could you try to remove both node_modules and the lockfile (yarn.lock or package-lock.json) and install again?

**Comment by dqii** [comment]
```
Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45.
```

```
yarn why expo-constants
yarn why v1.22.17
[1/4] 🤔  Why do we have the module "expo-constants"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "expo-constants@13.0.2"
info Has been hoisted to "expo-constants"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "296KB"
info Disk size with unique dependencies: "1.06MB"
info Disk size with transitive dependencies: "10.46MB"
info Number of shared dependencies: 61
=> Found "expo#expo-constants@13.0.0"
info This module exists because "expo" depends on it.
info Disk size without dependencies: "296KB"
info Disk size with unique dependencies: "1.06MB"
info Disk size with transitive dependencies: "10.46MB"
info Number of shared dependencies: 61
=> Found "expo-notifications#expo-constants@13.0.0"
info This module exists because "expo-notifications" depends on it.
info Disk size without dependencies: "296KB"
info Disk size with unique dependencies: "1.06MB"
info Disk size with transitive dependencies: "10.46MB"
info Number of shared dependencies: 61
=> Found "expo-firebase-core#expo-constants@13.0.0"
info This module exists because "expo-firebase-recaptcha#expo-firebase-core" depends on it.
info Disk size without dependencies: "296KB"
info Disk size with unique dependencies: "1.06MB"
info Disk size with transitive dependencies: "10.46MB"
info Number of shared dependencies: 61
✨  Done in 0.91s.
```

I get the same error even though I don't have expo-constants v12 installed anywhere. What else could be causing this? I tried running `expo start -c` as well but that didn't fix it.

**Comment by pwfcurry** [comment]
I think this is caused by multiple versions of `expo-constants` (@dqii you have both 13.0.0 & 13.0.2 present) - de-duplicating fixed this for us.

You can add an entry to package json "resolutions" (would not recommend), or run airbnb's `yarn-deduplicate` script, or manually tweak yarn.lock to remove the duplicates (likely easiest way to do this is just to remove both entries & run `yarn`) -- the last being the least intrusive solution.

**Comment by adgogo** [comment]
i had the same issue, i was working with expo-constants along with expo-notifications .
i fixed the issue by running this command : `expo doctor --fix-dependencies`

**Comment by grean** [comment]
Running into this warning just after installing `"expo-constants": "^13.0.2",` and only on `ios` side.
+ Didn't touch my yarn.lock
+ Replaced my node_modules did'nt helped
+ expo doctor --fix-dependencies -> `🎉 Didn't find any issues with the project!`

My warning here
```bash
Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45.
at node_modules/expo/node_modules/expo-constants/build/Constants.js:129:16 in Object.defineProperty$argument_2.get
at node_modules/expo-constants/build/Constants.js:125:26 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at node_modules/expo-asset/build/PlatformUtils.js:2:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at node_modules/expo-asset/build/AssetSources.js:6:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at node_modules/expo-asset/build/Asset.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at node_modules/expo-asset/build/Asset.fx.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at node_modules/expo-asset/build/index.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at node_modules/expo/build/Expo.fx.js:6:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at node_modules/expo/build/launch/registerRootComponent.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:35 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at node_modules/expo/AppEntry.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:201:44 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:23 in metroRequire
at http://192.168.153.118:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:389131:3 in global
```

**Comment by samjusaitis** [comment]
> Running into this warning just after installing `"expo-constants": "^13.0.2",` and only on `ios` side.

Also happened to me after upgrading to `expo` 44.0.6 which uses `expo-constants` 13.0.2. I also had an `expo-constants` 13.0.1 version dependency from the latest `expo-linking`. Solved by de-duplicating versions as per @pwfcurry [comment](https://github.com/expo/expo/issues/15110#issuecomment-1063214853) above

**Comment by djmarcosban** [comment]
I fixed this problem updating expo, after i have fixed all dependencies using expo doctor `--fix-dependencies` and after removed node_modules path. After all this, I executed `npm install` and start my project using `expo start -c`

**Comment by dan-doyon-endear** [comment]
expo install of expo-linking seems to have done the trick

**Comment by jeremykes** [comment]
@pwfcurry suggestion worked for me. I tried `expo doctor`, deleting `node_modules`/`yarn.lock didn't work. I checked in my yarn.lock and sure enough expo was using two versions of `expo-constants, 13.2.4 and 14.0.0. I removed 13.2.4 (updated all references) and then ran yarn install and that fixed it for me.

**Comment by barimehdi77** [comment]
@jeremykes can you tell me how to remove the `13.2.4` version? cuz I removed it and when I re run `yarn` the same dependency showed up again

**Comment by feRpicoral** [comment]
> @jeremykes can you tell me how to remove the `13.2.4` version? cuz I removed it and when I re run `yarn` the same dependency showed up again

For me, what fixed it was first deleting `yarn.lock` and `node_modules`, then running `yarn`, then updating all dependencies with `npx expo install ...`

**Comment by jeremykes** [comment]
> What I did was directly edit the `yarn.lock` file. There were 2 references to `expo-constants`. That didn't make sense to me so I assume using only the latest one should be sufficient (someone can correct me if I'm wrong). I only referenced the latest `expo-constants` and removed the older version in the file. Thats how I got rid of my warning message.

**Comment by WayneKeenan** [comment]
purging didn't work for me... 


If you’re happy to upgrade the SDK to 47  (e.g. your own RN dependancies will work and iOS 13 as a min) I found this out:


After running:  `npm why expo-constants`

I saw the v13 dependancy in expo v46  (expo-asset has v14 dev):

```
expo-constants@13.2.4
node_modules/expo/node_modules/expo-constants
  expo-constants@"~13.2.4" from expo@46.0.17
```

So decided to update the Expo SDK to v47 by running:

```
expo upgrade 47  
```

When trying to run `pod install` I received this error:

So edited:   ios/Podfile

```
platform :ios, podfile_properties['ios.deploymentTarget'] || '14'
```

Then deleted `Podfile.lock` and  re-ran `pod install`.

Note: I never tested iOS13 in the pod file, but I had to set it to iOS 13 in Xcode when building.


Now the app builds and there is no deprecation warning.

**Comment by hodacthanhminh** [comment]
> @jeremykes can you tell me how to remove the `13.2.4` version? cuz I removed it and when I re run `yarn` the same dependency showed up again
> 
> For me, what fixed it was first deleting `yarn.lock` and `node_modules`, then running `yarn`, then updating all dependencies with `npx expo install ...`

I have try but it not work :( 
![image](https://user-images.githubusercontent.com/81793802/204197894-2adca046-2750-430f-bda1-8b5c572f8292.png)

I have found that in my latest package `expo-constants@14.0.2` still have this line. So any help to remove those warning?

![image](https://user-images.githubusercontent.com/81793802/204197277-f18ecb11-bdf4-45b5-8ab3-6575867e0b6f.png)

**Comment by onerdark** [comment]
@hodacthanhminh 
Try to update the SDK to 47
```sh 
expo-cli upgrade
```

**Comment by hassanad94** [comment]
> npx expo install



> @pwfcurry suggestion worked for me. I tried `expo doctor`, deleting `node_modules`/`yarn.lock` didn't work. I checked in my `yarn.lock` and sure enough expo was using two versions of `expo-constants`; 13.2.4 and 14.0.0. I removed `13.2.4`, updated all references, ran `yarn install` and that fixed it for me.

I have deleted node_modules,
 - delete yarn.lock 
 - than yarn install
 - deduplicate the expo-constants@~13.2.4:
 - npx expo install -> which has fixed my dependencies

And ready to Goooo 😁😁.

**Comment by codyhenry** [comment]
> * deduplicate the expo-constants@~13.2.4:

What do you mean by this?

**Comment by hassanad94** [comment]
> > * deduplicate the expo-constants@~13.2.4:
> 
> What do you mean by this?

When you open the yarn lock file. I suggest to search “expo-constants”.

you will find 2 big block of declaration.

one of them is start 13.x.x
The other one is start 14.x.x

you will recognize them. 

Delete the 13.x.x.

You will find mani places where some dependencies use 13.2.4 Ignore them.  Simply delete the declaration. :)

**Comment by SlideeScherz** [comment]
My solution: 

```ts
/** @file App.tsx */
import { LogBox } from 'react-native';

LogBox.ignoreLogs([
  `Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45.`,
]);
```

**Comment by abepuentes** [comment]
@SlideeScherz thanks, I just did the same

**Comment by mr-tiwari-ji** [comment]
i am facing same issue - 
 WARN  Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45.

**Comment by l1h2** [comment]
I have the same problem. I create a new blank project and everytime I open it in Expo Go (Iphone) I get this warning. When testing in emulated android device however, it doesn't happen.

**Comment by 85223** [comment]
I refer to the solution here to solve my problem
https://github.com/expo/expo/issues/22543

I found out that the problem was due to the expo-asset:8.9.2 dependency on expo-constants conflicting with the Expo SDK version 48 I was using.

The new version of expo-asset depends on expo-constants:~14.3.0, which is different from the expo-constants:~14.2.0 normally used by SDK 48.
This conflict caused me to have two versions of expo-constants in my project, causing problems.

I was able to resolve this conflict by specifying expo-asset version 8.9.1 (compatible with SDK 48) in the 'resolutions' section of my package.json.

I added the following content in package.json, like this
```
  "resolutions": {
     "expo/expo-asset": "8.9.1"
   },
```

Modify package.json, I delete node_modules, reinstall package
`yarn or npm install`

**Comment by mhmeroglu** [comment]
expo-cli upgrade
just run this.

**Comment by isaque-cwb** [comment]
> expo-cli upgrade 
isso resolveu pra mim.... top

**Comment by filipe-siqueira-oliveira** [comment]
> `expo-cli upgrade` just run this.

this works for me... thanks bro <3

**Comment by TRETYAKweb** [comment]
This command helped me:
- "expo upgrade"

**Comment by dammy-key** [comment]
Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45. WARN Possible Unhandled Promise Rejection (id: 0): TypeError: Network request failed TypeError: Network request failed


while i have done some possible solution i got from here like removed node_module | removed lockfile and re-installed with yarn install and start with yarn expo start -c but i'm still getting the same problem... please help me out

**Comment by oguzalpcakmak** [comment]
> > @pwfcurry suggestion worked for me. I tried `expo doctor`, deleting `node_modules`/`yarn.lock` didn't work. I checked in my `yarn.lock` and sure enough expo was using two versions of `expo-constants`; 13.2.4 and 14.0.0. I removed `13.2.4`, updated all references, ran `yarn install` and that fixed it for me.
> 
> My Steps after reading all of the comments.
> 
> * delete node_modules,
> * delete yarn.lock
> * than yarn install
> * deduplicate the expo-constants@~13.2.4:
> * npx expo install -> which has fixed my dependencies
> * npx expo start -c -> start with clear Cache
> 
> And ready to Goooo 😁😁.

It didn't fix mine's.
Also expo upgrade ridiculously doesn't work :)

![Ekran görüntüsü 2023-07-16 141958](https://github.com/expo/expo/assets/69851645/2f3618d1-2b78-4643-abfe-abcb75b73945)

**Comment by FischeritDE** [comment]
> > > @pwfcurry suggestion worked for me. I tried `expo doctor`, deleting `node_modules`/`yarn.lock` didn't work. I checked in my `yarn.lock` and sure enough expo was using two versions of `expo-constants`; 13.2.4 and 14.0.0. I removed `13.2.4`, updated all references, ran `yarn install` and that fixed it for me.
> > 
> > 
> > My Steps after reading all of the comments.
> > 
> > * delete node_modules,
> > * delete yarn.lock
> > * than yarn install
> > * deduplicate the expo-constants@~13.2.4:
> > * npx expo install -> which has fixed my dependencies
> > * npx expo start -c -> start with clear Cache
> > 
> > And ready to Goooo 😁😁.
> 
> It didn't fix mine's. Also expo upgrade ridiculously doesn't work :)
> 
> ![Ekran görüntüsü 2023-07-16 141958](https://user-images.githubusercontent.com/69851645/253801075-2f3618d1-2b78-4643-abfe-abcb75b73945.png)

the solution worked fine on my mac.
Try:
npm audit fix --force

**Comment by DenisOleksiuk** [comment]
> I refer to the solution here to solve my problem #22543
> 
> I found out that the problem was due to the expo-asset:8.9.2 dependency on expo-constants conflicting with the Expo SDK version 48 I was using.
> 
> The new version of expo-asset depends on expo-constants:~14.3.0, which is different from the expo-constants:~14.2.0 normally used by SDK 48. This conflict caused me to have two versions of expo-constants in my project, causing problems.
> 
> I was able to resolve this conflict by specifying expo-asset version 8.9.1 (compatible with SDK 48) in the 'resolutions' section of my package.json.
> 
> I added the following content in package.json, like this
> 
> ```
>   "resolutions": {
>      "expo/expo-asset": "8.9.1"
>    },
> ```
> 
> Modify package.json, I delete node_modules, reinstall package `yarn or npm install`

it works for me

**Comment by nficca** [comment]
I am also experiencing this issue and none of the solutions seem to be working for me.

I'm using SDK 48. I've tried removing node modules, reinstalling, and restarting expo with a fresh cache: no dice. I've also tried the same with and without the resolutions section described in [an earlier comment](https://github.com/expo/expo/issues/15110#issuecomment-1625077724). Not sure what I else to do.

**Comment by Novizh** [comment]
> I refer to the solution here to solve my problem #22543
> 
> I found out that the problem was due to the expo-asset:8.9.2 dependency on expo-constants conflicting with the Expo SDK version 48 I was using.
> 
> The new version of expo-asset depends on expo-constants:~14.3.0, which is different from the expo-constants:~14.2.0 normally used by SDK 48. This conflict caused me to have two versions of expo-constants in my project, causing problems.
> 
> I was able to resolve this conflict by specifying expo-asset version 8.9.1 (compatible with SDK 48) in the 'resolutions' section of my package.json.
> 
> I added the following content in package.json, like this
> 
> ```
>   "resolutions": {
>      "expo/expo-asset": "8.9.1"
>    },
> ```
> 
> Modify package.json, I delete node_modules, reinstall package `yarn or npm install`

This solution works for me, thanks mate!
