### ISSUE TITLE
Audio setOnPlaybackStatusUpdate is not working on ios platform

### ISSUE THREAD

**Issue by MuongKimhong** [expo/expo#15224]
### Summary

Audio setOnPlaybackStatusUpdate is not being called on IOS.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42.0.4

### Environment

  Expo CLI 4.12.1 environment info:
    System:
      OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.18.1 - /usr/bin/node
      npm: 6.14.15 - /usr/bin/npm
    npmPackages:
      expo: ^42.0.4 => 42.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I'm building an application for both android & ios paltforms and I got problem with Expo Audio setOnPlaybackStatusUpdate.

I want to detect when the sound is finished by using this code below
```javascript
const soundObject = new Audio.Sound();

await Audio.setAudioModeAsync({
  allowsRecordingIOS: false,
  playsInSilentModeIOS: true,
  interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
  shouldDuckAndroid: true,
  interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
  playThroughEarpieceAndroid: false
});

await soundObject.playAsync()

soundObject.setOnPlaybackStatusUpdate(async (PlayStatus) => {
  if (PlayStatus.didJustFinish === true) {
    // sound has finished I want to do something here
    await soundObject.unloadAsync()
  }
})
```

The code above work perfectly fine on android plaform but on ios `setOnPlaybackStatusUpdate` never get called.

How can i fix this issue? I have been googling for almost 2 hours now but still can't find the solution.

Thanks you

**Comment by ffosb22** [comment]
Were you able to figure out this issue? I'm having the same problem.

**Comment by MuongKimhong** [comment]
Noo! I'm still finding the answer.

**Comment by pnadj** [comment]
Same issue

**Comment by tomas-teston** [comment]
The same issue :(

**Comment by givenm** [comment]
same issue on ios simulator

**Comment by tomas-teston** [comment]
But is this fixed in any SDK?

**Comment by harrigee** [comment]
I guess it is not fixed because I am still experiencing this in Expo 46.

**Comment by robgraeber** [comment]
I had a similar issue where `setOnPlaybackStatusUpdate` was never called with `didJustFinish = true` on iOS. In my case, it was because I was loading the sounds in npm module separate from the main app. When I moved the sound loading with the exact same code into the main app then it worked appropriately. No idea why that would be the case.

**Comment by atif7865** [comment]
What is the point of opening these issues if the Expo team does not respond to these? I am starting to think choosing react native and Expo was a bad decision!

**Comment by robgraeber** [comment]
Looking at the OP's problem, looks like `setOnPlaybackStatusUpdate` was being called after playAsync() so maybe it was a race condition.

**Comment by OneHatRepo** [comment]
Happening to me on SDK46. Status updates never happen on iOS, unless the sound is manually played or paused, and this includes the event marking the end of the file having been reached.

Looks like the ticket was auto-closed on Jun 19, and my guess is the team no longer looks at closed issues.

**Comment by robgraeber** [comment]
Please make a new ticket with a full replication repo, if it's not easy to reproduce no one looks at these.

**Comment by OneHatRepo** [comment]
Added [new ticket](https://github.com/expo/expo/issues/19022) with repro.

**Comment by davichoso** [comment]
setOnPlaybackStatusUpdate does not work on ios

**Comment by stevehs17** [comment]
Still broken as of today with expo 46 and expo-av 12.
