### ISSUE TITLE
Push notifications for Standalone Android do not work

### ISSUE THREAD

**Issue by Jozsef86** [expo/expo#1568]
### Environment

Environment:
  OS: Linux 3.16
  Node: 9.8.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^23.0.0 => 23.0.1
  react: 16.0.0 => 16.0.0
  react-native: https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz => 0.50.3

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/jozsef-b2629d43-26e8-4f22-baf2-dd8a97831e72.tar.gz

Standalone running on Samsung Galaxy s8
### Steps to Reproduce

When the applications starts, the user is asked to log in. An expo push token is created and sent to backend. To rule out any backend issues, I grab the token and call the expo server directly via Postman to send a notification. 

### Expected Behavior

The android device should get a notification

### Actual Behavior

The device is not receiving any notifications. 
Expo server first responds with 200 OK, then after a few tries it responds:
```json
{
    "data": [
        {
            "status": "error",
            "message": "SNS failed to send the notification (reason: EndpointDisabled, status code: 400).",
            "details": {
                "error": "DeviceNotRegistered",
                "sns": {
                    "statusCode": 400,
                    "reason": "EndpointDisabled",
                    "__message": "Endpoint is disabled"
                }
            }
        }
    ]
}
```

The app is granted permissions otherwise the code would not have generated the push token. The app does however not prompt for permission, as if a grant from a previous installation is still being in use. 

I have tried: 

- clearing expo data
- reinstalling expo
- reinstalling standalone app
- rebuilt the standalone app with different package names, and different slug
- rebuilt the standalone app with declared permissions in the app.json:

```json
      "permissions": [
        "CAMERA",
        "ACCESS_FINE_LOCATION",
        "com.google.android.c2dm.permission.RECEIVE",
        "READ_EXTERNAL_STORAGE",
        "READ_INTERNAL_STORAGE"
      ]
```

Everything works well running in Expo, as soon as i build the standalone apk it no longer works.

snack:
https://snack.expo.io/HJFH2l95f

**Comment by fweffort** [comment]
Same here:
https://forums.expo.io/t/bug-error-with-expo-push-notifications-on-android/8179/2
and here:
https://github.com/expo/expo/issues/1330

**Comment by jentzon** [comment]
+1 on this issue
https://forums.expo.io/t/notifications-troubles-after-building-and-running-natively/8121

**Comment by fweffort** [comment]
Sorry to botter guys, but this is really crucial.
My app is running on clients and the app relies on push notifications.

Do we have any update on how to fix this??

**Comment by AdamJNavarro** [comment]
Hey guys,

We're aware of this issue and are sorry for the inconveniences it has caused. Unfortunately, with SDK26 being released this week our resources and time are limited and sharply focused on the release. In may be a couple of days before we're able to dig in and resolve this issue.

Adam

**Comment by nicknovitski** [comment]
I can say that we have been able to sporadically reproduce the problem and we are investigating it further.

**Comment by jentzon** [comment]
Minor fix to @Jozsef86 's snack. To show revieved notification.
https://snack.expo.io/BynH9xc5f

**Comment by toxox** [comment]
For what it's worth, I am getting the same issue on OnePlus 2 (Android 6.0.1), but not on Xiaomi mi5s, which runs Android 7.x

**Comment by earle** [comment]
I have the same issue, running in the Expo Client.  Works fine for iOS.  Android users get a token (using the example code, works under iOS), but when trying to send a message,  receives the same error as seen above.

**Comment by jesseruder** [comment]
Hi! Sorry about this issue. We've been working hard on a fix but it unfortunately required a lot of changes on our end. We just put up a guide on using FCM for push notifications which should fix the problem: https://docs.expo.io/versions/latest/guides/using-fcm. Please let us know if you run into problems with the new system and sorry for the trouble.

**Comment by jentzon** [comment]
The FCM solutions works. Followed your guide to set it up and tried it out on Android stand alone (on a very old Samsung S3, but still) and it runs smoothly now. Haven't been able to try stand alone on iOS but guess that still works. Works fine when running through Expo Client. Thank you @jesseruder for this solution!

**Comment by raulsi** [comment]
@jesseruder  I followed the document of using-fcm but still not getting when the standalone app is close state. in the Logcat I am getting this  "W/GCM-DMM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000" so the device is getting but the notification is not showing up in the tray.. while when app in foreground I am getting notification and in logcat is like this "D/NotificationListener: onNotificationRemoved# hash: 169916896 sbn: StatusBarNotification(pkg=com.r....."

**Comment by fweffort** [comment]
@jesseruder hi.
I have tried to follow your fmc guide,
but when trying to build android, I am getting a fail:
`Parsing json file: /src/exponent/android-shell-app/app/google-services.json
:app:processProdReleaseGoogleServices FAILED
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:processProdReleaseGoogleServices'.
[stderr] > com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED`

build: 9580c12d-4217-434a-9158-7d9292e75239

I have no clue how to fix it

**Comment by jesseruder** [comment]
@fweffort please make sure you're using the most recent version of `exp`.

@raulsi interesting, that case is working for me. What type of device do you have?

**Comment by earle** [comment]
@jesseruder What is the plan to fix this properly with the Expo push notifications, so it works reliably under the Expo client in Android?  The  Expo FCM documentation explicitly says it wont work with Android Expo client: https://docs.expo.io/versions/latest/guides/using-fcm

Is there a fix being made for the standard Expo Push Notification library for Android devices running the Expo client?  I'd hate to have to eject at this point since I've come this far I'd prefer to stay with Expo, but not having Android notifications is a definitely a show-stopper

**Comment by jesseruder** [comment]
Hi @earle. FCM works in standalone apps but not in the Android Expo client. You need to build a standalone app to use FCM but you do not need to detach.

**Comment by earle** [comment]
@jesseruder Thanks for the quick response.  What about the normal Expo PushNotification system?  It work well for iOS, but Android using the Expo Client (or the Expo Push Notificaiton Tool) still produces the same above error.  Is this going to be fixed?   I'd prefer not to have an additional dependency...

**Comment by raulsi** [comment]
@jesseruder  I have OnePlus 5T and I found out that if i remove battery optimisation from my app in my phone then It start to work like one in Xaomi phones need to do AppStart, so it's My device problem, it's working on other devices but not on these devices,  didn't found any workaround only user have to do it manually .

**Comment by muniperez** [comment]
Hello guys!

I'm facing the same problem: notifications arrive on standalone iOS app but they never show up on standalone Android app.

Any update on a fix for this?

Thanks!

**Comment by davidsneos** [comment]
Hello Everyone!

I used the FCM Guide that @jesseruder mention and it now it works like a charm on Standalone Android. Also is super fast and easy as @muniperez said.

Happy Coding.

**Comment by muniperez** [comment]
If anyone is having problems with their tunnel going down after setting up FCM, just put the full path for the ```google-services.json``` file on your ```app.json```.

See issue #1675 .

**Comment by carsonwah** [comment]
Wiil it be related to some constraint to Android that Expo wasn't aware of?

[Related OneSignal Documentation](https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown#section-the-app-is-force-stopped)

Hope the issue can be resolved soon.

**Comment by DoWhileGeek** [comment]
Sunk about a half hour following the fcm guide, and got this resp out of the dashboard push tool `An unknown error occured.`

**Comment by vojdan** [comment]
@DoWhileGeek I had the same problem, you probably didn't send you FCM key to Expo. Follow the guide to the end.

**Comment by anp** [comment]
Hi everyone! Looks like the issues reported in this thread have been addressed by using FCM for push notifs. Please open new issues if you're still having problems. Thanks!

**Comment by karanmartian** [comment]
Hi, so do we have to use FCM now instead of the Expo Push notification service. Push notifications sent through Expo Server are now only being received in the Expo App and not in standalone apps on Android or iOS. Will this be fixed so that we don't have to migrate to FCM. Also FCM does not work for iOS Expo or standalone Apps correct?

**Comment by fweffort** [comment]
you should setup fcm and use expo push endpoint.
Working on iOS and Android standalone.
It’s easier. Shouldn’t take too long to migrate.

Em qua, 6 de jun de 2018 às 09:37, Karan Kamdar <notifications@github.com>
escreveu:

**Comment by karanmartian** [comment]
Oh ok, that's what I am thinking of doing now. I was just curious if the following configuration had anything to do with the push notification failure:

We built the app using the latest Expo SDK 27.0.2

"expo": "^27.0.2",
"react": "16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-27.0.2.tar.gz"
Latest exp version - 54.0.1
