### ISSUE TITLE
[SDK 44] Android Crash / Attempt to invoke interface method 'expo.modules.interfaces.facedetector.FaceDetectorInterface' on a null object reference

### ISSUE THREAD

**Issue by yonitou** [expo/expo#15768]
### Summary

Hello, 

When using the app on SDK 44 on an Android smartphone, we got a full app crash when we land to a screen using `expo-camera` package. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

```

  Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /Users/yonitouboul/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1 
      expo: ^44.0.0 => 44.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.42.4
      expo-cli: 5.0.1
    Expo Workflow: managed
```

### Reproducible demo

Launch an app using `expo-camera` on a physical Android smartphone. 

The app will crash. 

Here's the log : 

```
NullPointerException: Attempt to invoke interface method 'expo.modules.interfaces.facedetector.FaceDetectorInterface expo.modules.interfaces.facedetector.FaceDetectorProviderInterface.createFaceDetectorWithContext(android.content.Context)' on a null object reference
```

**Comment by paulocappa** [comment]
Up! I'm facing same issue here.

I'm not using `expo-face-detector` or `expo-barcode-scanner` and when I try to record a video it crashes with the above error. Also occurs when getting an image from `expo-image-picker`(launchImageLibraryAsync)

I have a single page that only renders the camera.

**Comment by Yonom** [comment]
Duplicate of https://github.com/expo/expo/issues/15547

**Comment by brentvatne** [comment]
fix deployed in expo-camera@12.1.2

**Comment by yonitou** [comment]
Hi @brentvatne 

Thanks for the PR ! However, I just installed expo-camera@12.1.2 on my app (running on expo 44) and I'm still having the same issue : when sending the app from background to foreground with a screen using camera, it will crash on Android. 

Do you have any more infos ?

**Comment by brentvatne** [comment]
@yonitou - can you share the exact error logs?

**Comment by yonitou** [comment]
Everything is here : https://github.com/expo/expo/issues/15547#issuecomment-1024332726

Steps : 
- Install expo-camera@12.1.2 
- Create a screen using expo-camera 
- Launch the app with an Android phone
- Put the app in background 
- Wait 3 secs 
- Put the app back foreground 
- The error in the link above will appear.

**Comment by brentvatne** [comment]
@yonitou - please give me a project that i can clone

**Comment by yonitou** [comment]
Here you are : https://github.com/yonitou/test

It should work if you follow the steps I sent you above

**Comment by mchjohn** [comment]
> Everything is here : [#15547 (comment)](https://github.com/expo/expo/issues/15547#issuecomment-1024332726)
> 
> Steps :
> 
>     * Install expo-camera@12.1.2
> 
>     * Create a screen using expo-camera
> 
>     * Launch the app with an Android phone (I'm using a Pixel 3 FYI but the error triggers on every Android)
> 
>     * Put the app in background
> 
>     * Wait 3 secs
> 
>     * Put the app back foreground
> 
>     * The error in the link above will appear.

I'm also getting this error. Any updates ?
