### ISSUE TITLE
[expo-camera] barcode scanned only once on Android

### ISSUE THREAD

**Issue by Swiftwork** [expo/expo#16126]
### Summary

Version 44 of `expo` caused a regression for `expo-camera`; barcodes will only trigger the `onBarCodeScanned` method once for Android. A similar issue was recently fixed for the `expo-barcode-scanner` package, but the implementations of the two packages are separate. Last known working versions:

```json
{
    "expo": "~43.0.0",
    "expo-camera": "~12.0.3",
    "expo-barcode-scanner": "~11.1.2"
}
```

Broken versions:
```json
{
    "expo": "~44.0.0",
    "expo-camera": "~12.1.0",
    "expo-barcode-scanner": "~11.2.0"
}
```

Related issues regarding package `expo-barcode-scanner` not `expo-camera`:
https://github.com/expo/expo/issues/15145
https://github.com/expo/expo/pull/15393
https://github.com/expo/expo/issues/14906

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

```
  Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20210110.135312.0 - C:\Projects\Tools\watchman\watchman.EXE
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      @expo/metro-config: ^0.3.9 => 0.3.9
      @expo/webpack-config: ~0.16.2 => 0.16.16
      expo: ^44.0.4 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed
```

### Reproducible demo

https://staging.snack.expo.dev/@swiftwork/ean13-scanner-v44

**Comment by Fabzien** [comment]
Is it similar to https://github.com/expo/expo/issues/15733 ?

**Comment by Swiftwork** [comment]
@Fabzien I can't rule it out, but this issue is referring to the `expo-camera` package and not `expo-barcode-scanner` so there might not be any overlap. BTW you can use the https://staging.snack.expo.dev/ to try out v44 of expo.

**Comment by Swiftwork** [comment]
@byCedric I suggest you add the label `Camera` as well as it's the primary package this issue pertains to oddly enough 😄.
```jsx
<Camera
  style={styles.camera}
  type={Camera.Constants.Type.back}
  barCodeScannerSettings={{
    barCodeTypes: [BarCodeScanner.Constants.BarCodeType.ean13],
  }}
  onBarCodeScanned={handleBarCodeScanned}
/>
```

**Comment by pingumen96** [comment]
Good morning, it happens to me too.

**Comment by Swiftwork** [comment]
Worth noting is that this issue does not occur in the `expo-barcode-scanner`:
https://staging.snack.expo.dev/@swiftwork/ean13-scanner-v44-updated

Is there any consensus yet on which package we should use for barcode scanning? Both packages have a lot of overlap, but many features still differ. Bounds for scanned events only exists in `expo-barcode-scanner` while aspect ratio, flash, etc... only exists in `expo-camera`.

**Comment by gcourtemanche** [comment]
I'm having the same issue, I'm on the latest versions
`expo`: 44.0.6
`expo-camera`: 12.1.2
`expo-barcode-scanner`: 11.2.1

**Comment by ireneprins1** [comment]
Same problem here

**Comment by TrustyTechSG** [comment]
Just upgraded to SDK44 and Im facing the same issue now

"expo": "^44.0.0",
"expo-barcode-scanner": "^11.2.1",
"expo-camera": "~12.1.2",

**Comment by Wiiktor22** [comment]
I'm having exactly the same issue on Android after updating from expo 43 to 44. As it is mentioned above on Android, barcode only triggers the onBarCodeScanned method once, so after scanning one barcode you won't be able to scan more. I have tried few different configuration for instance (with autoFocus turned on and off), but it doesn't have any impact for it I guess. 

On iOS it doesn't matter which version of expo is installed, it's working as expected on both.

I have tested this on Samsung Galaxy XCover 4S with Android 11.

**Comment by benmajor** [comment]
+1 for this using the `Camera` component. This was working fine before v44, so a fix would be good.

**Comment by benmajor** [comment]
Do we have any update on this at all? Even a temporary workaround would be good for now.

Thanks,
Ben.

**Comment by Wiiktor22** [comment]
I have not figured it out. For my app barcode scanner within Camera component is working perfectly fine in previous expo version (SDK 43), so I just helf off on updating expo 😞

**Comment by AEgan** [comment]
We've implemented a temporary workaround described here: https://github.com/expo/expo/issues/15733#issuecomment-1034785385

it just causes the camera to re-render when it scans a barcode to work around the issue of it only being able to scan one barcode. Not the greatest experience but easier than downgrading and submitting a new build to the app store.

another option is to try using [expo-barcode-scanner](https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/). There are some slight differences between expo-camera and expo-barcode-scanner and we had to stick to expo-camera, but it appears this issue used to happen there as well but was fixed: https://github.com/expo/expo/pull/15393

hopefully if it's something similar this can be fixed soon as well

**Comment by benmajor** [comment]
Thanks for the tip, @AEgan. Unfortunately, we can't use the `expo-barcode-scanner` as it's missing some of the features we've implemented (such as flash mode), but forcing the re-render of the `Camera` component seems to be about the best solution we have at the moment. 

Hopefully we will get some kind of update from the Expo in the coming days about this, but I appreciate your assistance with it.

**Comment by c-mcdonald** [comment]
Unfortunately we've encountered the same issue after upgrading from SDK43 -> 44. We can't use expo-barcode-scanner as we need the flash in expo-camera.

**Comment by Langsdorf** [comment]
Same issue on
```json
    "expo": "^44.0.1",
    "expo-barcode-scanner": "~11.2.0",
    "expo-camera": "~12.1.2",
  ```

**Comment by Swiftwork** [comment]
@ImJakeDev

> I am having the same issue on:
> 
> ```
> "expo": "43.0.1",
> "expo-barcode-scanner": "~11.1.2",
> ```

This issue is pertaining to the `expo-camera` package and not the `expo-barcode-scanner` package. Which is already fixed the single scan in version `> 11.2.0` https://github.com/expo/expo/pull/15393.

**Comment by bagraercan** [comment]
I use expo-barcode-scanner. It scans as much as you want till you do not change your navigation. When I go to another page and come back to the scan page, it does not work.

SOLUTION for me is unmount the page during navigation. 
Adding **unmountOnBlur:true** to the options of the scan page.

**Navigation.js**
`        <NavigationContainer>
            <Tab.Navigator
                screenOptions={iconOptions}
            >
                <Tab.Screen name="Scan" options={{title:"Scan", unmountOnBlur:true}} component={Scan} />
                <Tab.Screen name="Settings" component={SettingsScreen} />
            </Tab.Navigator>
        </NavigationContainer>`

**Scan.js**
`        <Center flex={1}>
            <BarCodeScanner
                onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
                style={StyleSheet.absoluteFillObject}
            />
            {scanned && <Button title={'Tap to Scan Again'} onPress={() => setScanned(false)} />}
        </Center>`

**Comment by chagriani** [comment]
+1 I'm using expo-barcode-scanner at the moment, until they solve the problem

**Comment by kchangch** [comment]
Is there any update regarding to this? Because im using expo-barcode-scanner 11.2.0, expo 44.0.1, it seems to be working fine for iOS but android doesnt work. It only scan once. Any work around?

**Comment by benmajor** [comment]
> Is there any update regarding to this? Because im using expo-barcode-scanner 11.2.0, expo 44.0.1, it seems to be working fine for iOS but android doesnt work. It only scan once. Any work around?

Yes, update the expo-barcode-scanner component, the issue being discussed here has already been fixed in versions `> 11.2.0` of `expo-barcode-scanner` (see https://github.com/expo/expo/pull/15393).

**Comment by kchangch** [comment]
> 

What version is it on now? I tried updating but it still shows 11.2.0

**Comment by benmajor** [comment]
> What version is it on now? I tried updating but it still shows 11.2.1

11.2.1, according to NPM and Yarn. Is your package locked to the minor version? What if you try installing the PR commit?

**Comment by kchangch** [comment]
Im quiet new with react native. How can I install te PR commit?

**Comment by benmajor** [comment]
I would only ever do that as a last resort. The package has been updated in both NPM and Yarn, so you should just be able to pull down the latest from there. How did you try to install the patch update to 11.2.1?

**Comment by kchangch** [comment]
I changed my package.json version to 11.2.1 and ran yarn install

**Comment by chancesmith** [comment]
changing to the Camera component works...suggested here: https://github.com/expo/expo/issues/14906#issuecomment-968338776

snack
https://snack.expo.dev/@sodiumhalogen/working-barcode-scanner

this thread relates to #15733

**Comment by f-g-p** [comment]
Same problem here

**Comment by ireneprins1** [comment]
Any progress?

**Comment by Fabzien** [comment]
Any news? I tried multiple workaround and still no results

**Comment by TrustyTechSG** [comment]
SDK 45 still have this issue. it is really a big issue for us, as only work once = total not working.

"expo": "^45.0.0",
"expo-camera": "~12.2.0",
"expo-barcode-scanner": "~11.3.0",

**Comment by jthemenace** [comment]
I had a recent build of our project on SDK 42 that Apple rejected due to what version of xcode 'expo build:ios' was using.  I found in a different github issue where the fix for that was to upgrade to SDK 43, which I did.  Now I'm running into this Android barcode scan issue.   The barcode scanner is a key part of our app, won't be able to push an update until it's fully working.  Any fix or workarounds would be much appreciated.

"expo": "^43.0.0",
"expo-barcode-scanner": "~11.1.2",

**Comment by Swiftwork** [comment]
@jthemenace If you read the issue thread you can see that this as been answered before:

> @ImJakeDev
> 
> > I am having the same issue on:
> > ```
> > "expo": "43.0.1",
> > "expo-barcode-scanner": "~11.1.2",
> > ```
> 
> This issue is pertaining to the `expo-camera` package and not the `expo-barcode-scanner` package. Which is already fixed the single scan in version `> 11.2.0` #15393.

So your options are either to use expo `v43` and the `expo-camera` package which hasn't introduced the single scan issue or upgrade expo to `v44` and use the `expo-barcode-scanner` which has fixed the single scan issue. This issue pertains only to the regression of functionality that expo `v44` brought to the `expo-camera` package.

**Comment by jthemenace** [comment]
@Swiftwork Thank you for giving a clear concise explanation of which SDK version works with which camera/barcode-scanner package.

I ended up changing our app to use expo-camera on v43 and it seems to be working fine so far, best I can tell.

I did read this entire issue thread multiple times before I left my comment.  So many different things were said by so many different people, it's hard to know who is right, etc.  Before your reply, the exact working options currently available were clear as mud.

**Comment by witheroux** [comment]
I'm not super familiar with Kotlin so maybe I misunderstand the quick code check I made, but it seems to me that the issue stems for the Kotlin rewrite(#14717) that was made to the `expo-camera` package. [These lines](https://github.com/expo/expo/blob/d374f5503fcd45af4599d384833709a0957029dc/packages/expo-camera/android/src/main/java/expo/modules/camera/tasks/BarCodeScannerAsyncTask.kt#L22) seem to be the culprit : 
```kt
    result?.let {
      delegate.onBarCodeScanned(result)
    } ?: delegate.onBarCodeScanningTaskCompleted()
```

`delegate.onBarCodeScanningTaskCompleted()` is responsible for releasing the scanning lock and allowing more scans to go through. At the moment, it is only called when the result?.let fails the null check, whereas the [previous code](https://github.com/expo/expo/blob/30432ba8105098f3dc4d2644bddcae94824758bd/packages/expo-camera/android/src/main/java/expo/modules/camera/tasks/BarCodeScannerAsyncTask.java#L45) would always release the lock, no matter if the scanning result is valid or not.
```java
    if (result != null) {
      mDelegate.onBarCodeScanned(result);
    }
    mDelegate.onBarCodeScanningTaskCompleted();
```

Hopefully someone who's more familiar with developing with Kotlin and contributing to expo can validate my hunch and help get this potential fix released ASAP.

**Comment by lucassouza16** [comment]
> Não estou super familiarizado com Kotlin, então talvez eu tenha entendido mal a verificação rápida de código que fiz, mas parece-me que o problema decorre da reescrita do Kotlin ( [# 14717](https://github.com/expo/expo/pull/14717) ) que foi feita no `expo-camera`pacote. [Estas linhas](https://github.com/expo/expo/blob/d374f5503fcd45af4599d384833709a0957029dc/packages/expo-camera/android/src/main/java/expo/modules/camera/tasks/BarCodeScannerAsyncTask.kt#L22) parecem ser o culpado:
> 
> ```kotlin
>     result?.let {
>       delegate.onBarCodeScanned(result)
>     } ?: delegate.onBarCodeScanningTaskCompleted()
> ```
> 
> `delegate.onBarCodeScanningTaskCompleted()`é responsável por liberar o bloqueio de varredura e permitir que mais varreduras passem. No momento, ele só é chamado quando o resultado?.let falha na verificação de nulo, enquanto o [código anterior](https://github.com/expo/expo/blob/30432ba8105098f3dc4d2644bddcae94824758bd/packages/expo-camera/android/src/main/java/expo/modules/camera/tasks/BarCodeScannerAsyncTask.java#L45) sempre liberaria o bloqueio, não importando se o resultado da varredura é válido ou não.
> 
> ```java
>     if (result != null) {
>       mDelegate.onBarCodeScanned(result);
>     }
>     mDelegate.onBarCodeScanningTaskCompleted();
> ```
> 
> Espero que alguém que esteja mais familiarizado com o desenvolvimento com Kotlin e contribuindo para a expo possa validar meu palpite e ajudar a lançar essa possível correção o mais rápido possível.

Your solution worked great for me, thanks!

**Comment by maxenceg** [comment]
@witheroux Is there anything else I need to do after applying the patch in my `node_modules/expo-camera` folder?

**Comment by Swiftwork** [comment]
@barthap do you have any idea when we could see the #17655 fix released? It's been a month since it was merged. Is it due to the builds failing or does expo have a release cadence for fixes as well?

**Comment by barthap** [comment]
We usually publish packages when a new SDK is released, so this will be published with SDK 46 (in about a month)
