### ISSUE TITLE
Face Detection not working on Android

### ISSUE THREAD

**Issue by naor10** [expo/expo#16233]
### Summary

Hi,

When the property "onFacesDetected" is set on camera component, the app crashes.

**In package.json:**
"expo-face-detector": "~11.0.3",

**Exception:**

java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.*****. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@19.0.0:180)
        at com.google.firebase.ml.vision.FirebaseVision.getInstance(com.google.firebase:firebase-ml-vision@@24.0.1:1)
        at expo.modules.facedetector.ExpoFaceDetector.createFaceDetector(ExpoFaceDetector.java:237)
        at expo.modules.facedetector.ExpoFaceDetector.detectFaces(ExpoFaceDetector.java:96)
        at expo.modules.camera.tasks.FaceDetectorTask.execute(FaceDetectorTask.java:40)
        at expo.modules.camera.ExpoCameraView$1.onFramePreview(ExpoCameraView.java:142)
        at com.google.android.cameraview.CameraView$CallbackBridge.onFramePreview(CameraView.java:604)
        at com.google.android.cameraview.Camera1.onPreviewFrame(Camera1.java:766)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1251)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7179)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.12.1 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\*******\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Reproducible demo

<Camera ref={ref => { this.camera = ref; }} style={{ flex: 1 }} type={this.state.type} onFacesDetected={this.handleFacesDetected}
            faceDetectorSettings={{
              mode: FaceDetector.FaceDetectorMode.fast,
              detectLandmarks: FaceDetector.FaceDetectorLandmarks.none,
              runClassifications: FaceDetector.FaceDetectorClassifications.none,
              minDetectionInterval: 100,
              tracking: true,
            }}>
{....}
          </Camera>

**Comment by brentvatne** [comment]
hi there! please update to sdk44 where this is resolved

**Comment by smoove** [comment]
@brentvatne This still happens for me on eas builds, even with current SDK and expo-camera versions.

```

  Expo CLI 5.1.2 environment info:
    System:
      OS: Linux 5.16 Arch Linux
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.17 - /usr/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
      Watchman: 20220130.171601.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3, 32.1.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: AI-211.7628.21.2111.8139111
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.16
      expo: ^44.0.6 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.1.2
    Expo Workflow: managed
```

`` "expo-camera": "~12.1.2",``

**Comment by rusakovic** [comment]
confirm the issue:

```
2022-03-13 19:12:55.545 23610-23610/com.camera E/libc: Access denied finding property "vendor.camera.hal1.packagelist"
2022-03-13 19:12:55.954 23610-23610/com.camera E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.camera, PID: 23610
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.camera. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@19.0.0:180)
        at com.google.firebase.ml.vision.FirebaseVision.getInstance(com.google.firebase:firebase-ml-vision@@24.0.1:1)
        at expo.modules.facedetector.ExpoFaceDetector.createFaceDetector(ExpoFaceDetector.kt:185)
        at expo.modules.facedetector.ExpoFaceDetector.detectFaces(ExpoFaceDetector.kt:99)
        at expo.modules.camera.tasks.FaceDetectorTask.execute(FaceDetectorTask.kt:17)
        at expo.modules.camera.ExpoCameraView$1.onFramePreview(ExpoCameraView.kt:324)
        at com.google.android.cameraview.CameraView$CallbackBridge.onFramePreview(CameraView.java:604)
        at com.google.android.cameraview.Camera1.onPreviewFrame(Camera1.java:766)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1321)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8019)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
