### ISSUE TITLE
Linking.getInitialURL in standalone in iOS fails to pass additional data in the URL

### ISSUE THREAD

**Issue by matb33** [expo/expo#1673]
When using `Linking.getInitialURL` to retrieve the URL (in a standalone iOS app with a custom scheme) when the app is first loaded (not when foregrounded), only the prefix is returned.

For example, attempting to open the app using custom scheme `test` with `test://something`, the URL retrieved with `Linking.getInitialURL` will return only the prefix `test://`.

### Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.0
  Yarn: 0.22.0
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/gradealabs-903bc80d-7584-4adb-b9cc-a451803284e8.tar.gz

### Steps to Reproduce

In order to make this as easy as possible, I've written a bash script to create a `test` project, build it for simulator, download it, and install it in the iOS simulator automatically.

1. Create this script and run it in a scratch folder of your choosing. A `test` project will be created within:
```
#!/bin/bash

set -e

exp init test --template blank
cd test

cat > App.js <<- EOM
import React from 'react';
import { StyleSheet, Text, View, Linking } from 'react-native';

export default class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = { url: '' }
  }
  componentDidMount() {
    Linking.getInitialURL().then(url => this.setState({ url }))
  }
  render() {
    return (
      <View style={styles.container}>
        <Text>URL: {this.state.url}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
EOM

cat > app.json <<- EOM
{
  "expo": {
    "name": "test",
    "description": "This project is really great.",
    "slug": "test",
    "scheme": "test",
    "privacy": "public",
    "sdkVersion": "26.0.0",
    "platforms": ["ios", "android"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.test.test"
    }
  }
}
EOM

rm -f /tmp/ios-app.tar.gz
exp build:ios --type simulator | grep -Eo "Successfully built standalone app: (.+)" | cut -d: -f2,3 | xargs curl -o /tmp/ios-app.tar.gz
rm -rf /tmp/test.app
tar -xvzf /tmp/ios-app.tar.gz -C /tmp

open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app
while : ; do
  count=$(xcrun simctl list | grep Booted | wc -l | sed -e 's/ //g')
  [ $count -lt 1 ] || break
  sleep 1
done

xcrun simctl install booted /tmp/test.app
```
2. Make sure the app is not currently running in the simulator, as we are not concerned with the behavior when the app is foregrounded

3. Launch the app in the simulator via Safari, such as `test://thisshouldwork`

4. Look for the URL being displayed in the app

### Expected Behavior

The app should display: `URL: test://thisshouldwork`

### Actual Behavior

The app displays: `URL: test://`

![getinitialurl](https://user-images.githubusercontent.com/1038466/39077316-fe997fea-44ce-11e8-8273-4d71814ace3d.gif)

### Reproducible Demo

See above installation script and demo video.

EDIT: changed `wget` to `curl` in the script

**Comment by axelnormand** [comment]
I too am seeing this exact thing. Magic authentication links and deep linking are quite crucial for the app i'm developing. 
Expo SDK 26
Any ideas without ejecting?

Thanks

ps thank you for that script @matb33 very useful to automate install standalone app to simulator!

**Comment by axelnormand** [comment]
I've also tried addListener('url') but that is not being triggered

**Comment by matb33** [comment]
@axelnormand that's strange -- I had `Linking.addEventListener` working in my production app. But now that I try to repro it in this miminal project, it doesn't work as expected anymore.
But because I do have that working in my prod app, I should be able to find the differences that lead it to break here (hopefully!)

**Comment by axelnormand** [comment]
Thank you for the reply and good to know.
Love to know the differences.

**Comment by terribleben** [comment]
We have a bunch of Linking changes forthcoming in SDK 27 which may affect this. cc @esamelson in case you know more about this particular case.

**Comment by esamelson** [comment]
I'm fairly certain that this should be fixed in SDK 27, which will be out shortly. Please let us know if this behavior continues to occur after upgrading.

**Comment by azurechen** [comment]
it still return prefix only in SDK 27.

**Comment by terribleben** [comment]
There are no standalone SDK 27 apps yet, so it hasn't been possible to test this yet.

**Comment by terribleben** [comment]
Hey there - we updated our standalone app builder to support SDK 27 a couple hours ago, so it should be possible to test this now.

**Comment by azurechen** [comment]
Thanks @terribleben, I just tried to change the sdkVersion to 27.0.0 and built again. I didn't know it was not released yet.
But now I really upgrade to 27.0.0 and the deep link works perfect!
Thank you for fixing the issue!

**Comment by terribleben** [comment]
Great! Really glad your issue is resolved. I will close this.

**Comment by matb33** [comment]
Confirming that this is indeed resolved with SDK 27. 👍

**Comment by yirui94** [comment]
Anyone still encountering this issue but when opening an App from a notification deep link?
