### ISSUE TITLE
AuthSession fails to redirect back to Android Standalone app

### ISSUE THREAD

**Issue by nikoootine** [expo/expo#1683]
Doing an auth session on an android standalone app does not redirect back to the app. I have defined my scheme in app.json. On an iOS standalone auth session works perfectly fine. 

It is also worth noting that I've tried detaching but then I encountered this exact same issue: https://github.com/expo/expo/issues/880. This issue might be related to that but I'm creating this issue in case this is a different one.

I'm hoping you could add this fix for SDK 27 as this auth session is an important aspect of our app! 

### Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 6.11.0
  Yarn: Not Found
  npm: 3.10.10
  Watchman: 4.7.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/nupixo-122d8e85-2632-435a-a67b-1638914677ab.tar.gz

### Steps to Reproduce

1. Fork this repo: https://github.com/expo/auth0-example
2. Make sure you have Auth0 client set up
3. Make sure you define a scheme in app.json
4. Change the redirect url to the defined scheme in app.json
5.  exp build:android
6. Once installed, open the app
7. Login with Auth0, a browser should open and an auth session should initiate
8. Sign in with valid credentials

### Expected Behavior

User gets successfully authenticated. AuthSession browser window will get closed and redirect back to the app.

### Actual Behavior

Browser window does not get closed and does not redirect back to the app.

### Reproducible Demo

A good reproducible demo is expo's own example: https://github.com/expo/auth0-example but try building an android standalone apk

**Comment by brentvatne** [comment]
@esamelson - this sounds like a bug with Linking

**Comment by esamelson** [comment]
Hi @nikoootine - i just confirmed this is fixed in SDK 27. Please watch our blog - it will be out very soon!

**Comment by nikoootine** [comment]
Thanks @esamelson !!

**Comment by nikoootine** [comment]
Hi @esamelson @brentvatne seems like this is still not fixed. I tried this with the same steps above but still it doesn't redirect back successfully. Can this issue be re-opened please thanks!

**Comment by felipefs93** [comment]
Hi @nikoootine I'm facing the same erro. Did you solve it?

**Comment by adammalevski** [comment]
Same issue here. SDK 27.0.0.
AuthSession in apk doesn't work.

**Comment by nikoootine** [comment]
@felipefs93 The work around that I did was to just implement the WebBrowser redirect manually. Pretty much the same thing here: 
https://github.com/expo/examples/blob/master/with-webbrowser-redirect/app/App.js

But the last time I checked this AuthSession issue I have was never resolved. Not sure for others
