### ISSUE TITLE
Manifest string is not a valid JSONObject or JSONArray Error, after running `eas build`

### ISSUE THREAD

**Issue by rodbs** [expo/expo#17695]
### Summary

After running `eas build  -p android --profile development`  and not getting it work because of this issue  [https://github.com/react-native-async-storage/async-storage/issues/768](url), now  I cannot run the Expo Go either because of  `Manifest string is not a valid JSONObject or JSONArray Error,`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
      Shell: 5.0.16 - /bin/bash
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 3.2.0 - /mnt/c/Users/rodri/AppData/Roaming/npm/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Expo Workflow: managed

### Reproducible demo

https://github.com/rodbs/test-issue

laun eas build

```
cd expo 
yarn eas login
cd ..
yarn build:expo
```   

run expo start
```
cd expo
yarn eas logout
cd ..
yarn native 
```

**Comment by HamzaAitOumghar** [comment]
same here

**Comment by alexislefebvre** [comment]
We have the same issue. Do we have any idea of the call that trigger the “Manifest string is not a valid JSONObject or JSONArray Error” error?

**Comment by alexislefebvre** [comment]
We fixed our issue by moving a plugin from `development` to `plugins` in the file `.babelrc`.

**Comment by brentvatne** [comment]
not clear to me that this is related to expo. if you can repro without the many additional libraries please let us know. i'd recommend trying to bisect the bug source by removing things until it doesn't repro

**Comment by stephenson080** [comment]
i am having the same issue. Even when i create a new expo app  with the demo code only and build with eas it still throws same error.
I am expo 46 SDK

**Comment by Monnus** [comment]
I have the same problem on platform android...I performed "eas build --profile development --platform android" on a project, then on a blank expo templet project  both give the same error
[Manifest string is not a valid JSONObject or JSONArray Error, after running eas build]
I also tried  with the both "expo global cli" & "npx expo local"
Expo 47 SDK
node -v16.18.0

**Comment by Alex88xl** [comment]
Same here using eas

SDK 47
Platform Android
node v.16.16.0

**Comment by adamtsai1** [comment]
Same here using EAS and SDK 47. Android only.

**Comment by hackingharold** [comment]
It seems like Expo on Android tries to serve the app from a local development server, like when developing with the CLI. But since we have a bundled .apk, the manifest file is not available.

For me, it helped to copy the URL of the apk (by doing a long-press on the download button) and paste it into the `Enter URL manually` field in the Expo Go app.
Then, the default installation process started. After confirming to install from an unknown source a couple of times, the app was added to my home screen and I was able to run it. 

![CleanShot 2022-12-20 at 16 33 38](https://user-images.githubusercontent.com/86829799/208705354-002089d6-d629-4fed-a439-659c85881105.png)

**Comment by GregPetropoulos** [comment]
> It seems like Expo on Android tries to serve the app from a local development server, like when developing with the CLI. But since we have a bundled .apk, the manifest file is not available.
> 
> For me, it helped to open the URL of the apk in a new tab (by doing a long-press on the download button). Then, the default installation process started. After confirming to install from an unknown source a couple of times, the app was added to my home screen and I was able to run it.
> 
> ![CleanShot 2022-12-20 at 16 33 38](https://user-images.githubusercontent.com/86829799/208705354-002089d6-d629-4fed-a439-659c85881105.png)

I logged in on two different  android devices and the long press  as described was the fix,  [hackingharold](https://github.com/hackingharold) you a genius and saved me hours.
