### ISSUE TITLE
exp build iOS enterprise app error: PKCS#12 MAC could not be verified. Invalid password?

### ISSUE THREAD

**Issue by zhaozhiming** [expo/expo#1771]
Hi, I use expo build the iOS enterprise app and it report the `Invalid password` error. But I have regenerate the p12 file and reset the password and it still error. 

#### The build error:
```sh
checking if teamID is present in keychain and that certificate is valid...
[stderr] [00:57:26] 'ios:build-and-sign-ipa' errored after 366 ms
[stderr] [00:57:26] Error: PKCS#12 MAC could not be verified. Invalid password?
[stderr]     at Object.p12.pkcs12FromAsn1 (/usr/local/turtle-agent/tools-public/node_modules/node-forge/lib/pkcs12.js:475:13)
[stderr]     at genCertFingerprint (/xdl@49.2.0/src/detach/IosUtils.js:32:28)
[stderr]     at Object.<anonymous> (/xdl@49.2.0/src/detach/IosUtils.js:12:23)
[stderr]     at Generator.next (<anonymous>)
[stderr]     at step (/usr/local/turtle-agent/tools-public/node_modules/xdl/build/detach/IosUtils.js:204:191)
[stderr]     at /usr/local/turtle-agent/tools-public/node_modules/xdl/build/detach/IosUtils.js:204:361
[stderr]     at <anonymous>
```

I have verify the p12 file password locally and it is correct.

```sh
# verify the distribution p12 password
openssl pkcs12 -nocerts -out PushKey.pem -in distribution.p12 -nodes -password pass:mypassword
MAC verified OK
# verify the push notification p12 password
openssl pkcs12 -nocerts -out PushKey.pem -in push.p12 -nodes -password pass:mypassword
MAC verified OK
```
I can publish the iOS app using the same password last week. But it failed today. Is something broken? Thanks.

```
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.0
  Yarn: 1.5.1
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.1
  react: 16.2.0 => 16.2.0
  react-native: ~0.55.2 => 0.55.4
```

**Comment by esamelson** [comment]
Hi @zhaozhiming - what an odd error 😕  A quick google search suggests that sometimes setting an empty password or a password with non-ASCII characters could potentially cause this issue. Could you try setting a different password for your p12 file (maybe a simple, but non-empty, one) and let us know if that works?

**Comment by zhaozhiming** [comment]
My password is very simple. First time I set the password to `123`, second time I set to `111`, but they both failed.

**Comment by esamelson** [comment]
@zhaozhiming -- okay, thanks for the info. It looks like we've recently changed how we run the signing code on our servers. I'll ping someone internally and see if we can get this figured out for you.

**Comment by zhaozhiming** [comment]
@esamelson Thanks. Waiting for your good news.

**Comment by jonatanrinckus** [comment]
Same problem, very simple password

**Comment by dsokal** [comment]
@zhaozhiming @jonatanrinckus 
I found the issue in our code. The problem occurs only for passwords which have only digits. I'll add support for them (i'll fix the bug) soon, but until now you can change your passwords to something that have at least one letter. Please let me know if it resolves the problem for you. Thanks!

**Comment by jonatanrinckus** [comment]
Great, it works. Thanks

**Comment by zhaozhiming** [comment]
@dsokal It works! Thanks, bro.

**Comment by dsokal** [comment]
@jonatanrinckus @zhaozhiming 
The fix has been deployed to production, you can already use numeric passwords if you would like to.

**Comment by igorrmotta** [comment]
It looks like the problem still happening... 

I did get the error many times, once changed the password to contain letters & numbers the problem went away...
