### ISSUE TITLE
App rotation leaves blank space. It is fine on Expo Go, but not when it runs on expo-dev-client.

### ISSUE THREAD

**Issue by Wei102193** [expo/expo#17724]
### Summary

After upgrading to SDK 45. It seems like the app dose not adjust its width and height automatically when its orientation changes. It leaves blank space when it changes orientation. It only happens on expo-dev-client. It has no problem on Expo Go
![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-06-02 at 10 51 24](https://user-images.githubusercontent.com/27971322/171657466-dcc6b923-781c-4869-9d4c-f16f01d64077.png)

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Package versions

"expo-dev-client": "~0.9.6",
"expo-updates": "~0.13.1"

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.6
    Expo Workflow: bare

### Reproducible demo

upgrading to SDK 45 and runs on dev client

**Comment by umbertoghio** [comment]
Same problem, it's easy to reproduce: unlock screen rotation and have a red  absolute View top/bottm/left/right at 0

Fine in portrait, when rotating to landscape I have the half right side of the screen black.

Will test a production build

**Comment by theJustinCase** [comment]
I have the same issue with my projects after upgrading from SDK44 to SDK45.  I was able to replicate it in a brand new project.  Running `expo start` and using Expo Go works fine.  Running `expo start --dev-client` and using an EAS build replicates the issue.

**Replication steps:**

1. New project with `expo init`
2. Set `orientation` in `app.json` to `default` to allow landscape
3. Run `expo start` and test in the Expo Go app.  Device orientation changes work as expected.
4. Install `expo-dev-client` with `expo install expo-dev-client`
5. Add `import 'expo-dev-client';` to the top of `App.js`
6. Create `eas.json` config with `eas build:configure`
7. Create an EAS build with `eas build --profile development`
8. Test on device.

**Results:**

Portrait orientation works as expected.  Rotating to landscape appears to keep the exact same dimensions as portrait instead of resizing to the updated orientation.
![IMG_3661](https://user-images.githubusercontent.com/1832182/172017269-04e8d2e8-c717-4d61-ad96-3e38635da999.PNG)
![IMG_3662](https://user-images.githubusercontent.com/1832182/172017273-daabd513-943f-4986-834b-149993c30a8e.PNG)

**Comment by vallezw** [comment]
Having the same issue

**Comment by fencer-yd** [comment]
I also encountered the same problem, but this problem seems to only happen in ios dev environment, and it does not reproduce in android and production environment.

**Comment by fencer-yd** [comment]
I also encountered the same problem, but this problem seems to only happen in ios dev environment, and it does not reproduce in android and production environment.

**Comment by nn1900** [comment]
diff --git a/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m b/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m
index a6493c6..619ff28 100644
--- a/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m
+++ b/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m
@@ -16,6 +16,15 @@
 
 @end
 
+#if DEBUG
+void __swap(CGFloat *p, CGFloat *q) {
+  if (p == NULL || q == NULL) return;
+  CGFloat tmp = *p;
+  *p = *q;
+  *q = tmp;
+}
+#endif
+
 @implementation EXScreenOrientationRegistry
 
 EX_REGISTER_SINGLETON_MODULE(ScreenOrientationRegistry)
@@ -227,6 +236,40 @@ EX_REGISTER_SINGLETON_MODULE(ScreenOrientationRegistry)
   for (id module in [_notificationListeners allObjects]) {
     [module screenOrientationDidChange:newScreenOrientation];
   }
+  
+#if DEBUG
+  if (![EXScreenOrientationUtilities isIPad]) {
+    return;
+  }
+  
+  // on iPad: try to force layout the root view when screen orientation changes.
+  UIWindow *window = [[[UIApplication sharedApplication] delegate] window];
+  UIView *rootView = [window rootViewController].view;
+  
+  CGFloat width = window.frame.size.width;
+  CGFloat height = window.frame.size.height;
+  
+  // default to portrait orientation
+  if (width > height) {
+    __swap(&width, &height);
+  }
+  
+  if (newScreenOrientation == UIInterfaceOrientationLandscapeLeft ||
+      newScreenOrientation == UIInterfaceOrientationLandscapeRight
+  ) {
+    // manually switch to landscape orientation when changed.
+    __swap(&width, &height);
+  }
+  
+  if (rootView.frame.size.width != width ||
+      rootView.frame.size.height != height
+  ) {
+    rootView.frame = CGRectMake(0, 0, width, height);
+    NSLog(@"HACK!!! Updated RCTRootView::frame to %@", NSStringFromCGRect(rootView.frame));
+  }
+  
+  [rootView layoutIfNeeded];
+#endif
 }
 
 #pragma mark - lifecycle
diff --git a/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationViewController.m b/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationViewController.m
index 8508789..fed05a8 100644
--- a/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationViewController.m
+++ b/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationViewController.m
@@ -6,6 +6,10 @@
 #import <EXScreenOrientation/EXScreenOrientationRegistry.h>
 #import <EXScreenOrientation/NSString+UIInterfaceOrientationMask.h>
 
+#if DEBUG
+#import "EXScreenOrientationUtilities.h"
+#endif
+
 NSString *const EXDefaultScreenOrientationMask = @"EXDefaultScreenOrientationMask";
 
 // copy of RNScreens protocol
@@ -62,6 +66,12 @@ NSString *const EXDefaultScreenOrientationMask = @"EXDefaultScreenOrientationMas
     return [screenOrientationRegistry requiredOrientationMask];
   }
   
+#if DEBUG
+  if ([EXScreenOrientationUtilities isIPad]) {
+    return UIInterfaceOrientationMaskAll;
+  }
+#endif
+  
   return _defaultOrientationMask;
 }

**Comment by nn1900** [comment]
I made a local patch to work around this issue temporarily. 
```diff
diff --git a/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m b/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m
index a6493c6..619ff28 100644
--- a/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m
+++ b/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m
@@ -16,6 +16,15 @@
 
 @end
 
+#if DEBUG
+void __swap(CGFloat *p, CGFloat *q) {
+  if (p == NULL || q == NULL) return;
+  CGFloat tmp = *p;
+  *p = *q;
+  *q = tmp;
+}
+#endif
+
 @implementation EXScreenOrientationRegistry
 
 EX_REGISTER_SINGLETON_MODULE(ScreenOrientationRegistry)
@@ -227,6 +236,40 @@ EX_REGISTER_SINGLETON_MODULE(ScreenOrientationRegistry)
   for (id module in [_notificationListeners allObjects]) {
     [module screenOrientationDidChange:newScreenOrientation];
   }
+  
+#if DEBUG
+  if (![EXScreenOrientationUtilities isIPad]) {
+    return;
+  }
+  
+  // on iPad: try to force layout the root view when screen orientation changes.
+  UIWindow *window = [[[UIApplication sharedApplication] delegate] window];
+  UIView *rootView = [window rootViewController].view;
+  
+  CGFloat width = window.frame.size.width;
+  CGFloat height = window.frame.size.height;
+  
+  // default to portrait orientation
+  if (width > height) {
+    __swap(&width, &height);
+  }
+  
+  if (newScreenOrientation == UIInterfaceOrientationLandscapeLeft ||
+      newScreenOrientation == UIInterfaceOrientationLandscapeRight
+  ) {
+    // manually switch to landscape orientation when changed.
+    __swap(&width, &height);
+  }
+  
+  if (rootView.frame.size.width != width ||
+      rootView.frame.size.height != height
+  ) {
+    rootView.frame = CGRectMake(0, 0, width, height);
+    NSLog(@"HACK!!! Updated RCTRootView::frame to %@", NSStringFromCGRect(rootView.frame));
+  }
+  
+  [rootView layoutIfNeeded];
+#endif
 }
 
 #pragma mark - lifecycle
diff --git a/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationViewController.m b/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationViewController.m
index 8508789..fed05a8 100644
--- a/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationViewController.m
+++ b/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationViewController.m
@@ -6,6 +6,10 @@
 #import <EXScreenOrientation/EXScreenOrientationRegistry.h>
 #import <EXScreenOrientation/NSString+UIInterfaceOrientationMask.h>
 
+#if DEBUG
+#import "EXScreenOrientationUtilities.h"
+#endif
+
 NSString *const EXDefaultScreenOrientationMask = @"EXDefaultScreenOrientationMask";
 
 // copy of RNScreens protocol
@@ -62,6 +66,12 @@ NSString *const EXDefaultScreenOrientationMask = @"EXDefaultScreenOrientationMas
     return [screenOrientationRegistry requiredOrientationMask];
   }
   
+#if DEBUG
+  if ([EXScreenOrientationUtilities isIPad]) {
+    return UIInterfaceOrientationMaskAll;
+  }
+#endif
+  
   return _defaultOrientationMask;
 }
 

```

**Comment by fencer-yd** [comment]
> I made a local patch to work around this issue temporarily.
> 
> ```diff
> diff --git a/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m b/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m
> index a6493c6..619ff28 100644
> --- a/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m
> +++ b/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m
> @@ -16,6 +16,15 @@
>  
>  @end
>  
> +#if DEBUG
> +void __swap(CGFloat *p, CGFloat *q) {
> +  if (p == NULL || q == NULL) return;
> +  CGFloat tmp = *p;
> +  *p = *q;
> +  *q = tmp;
> +}
> +#endif
> +
>  @implementation EXScreenOrientationRegistry
>  
>  EX_REGISTER_SINGLETON_MODULE(ScreenOrientationRegistry)
> @@ -227,6 +236,40 @@ EX_REGISTER_SINGLETON_MODULE(ScreenOrientationRegistry)
>    for (id module in [_notificationListeners allObjects]) {
>      [module screenOrientationDidChange:newScreenOrientation];
>    }
> +  
> +#if DEBUG
> +  if (![EXScreenOrientationUtilities isIPad]) {
> +    return;
> +  }
> +  
> +  // on iPad: try to force layout the root view when screen orientation changes.
> +  UIWindow *window = [[[UIApplication sharedApplication] delegate] window];
> +  UIView *rootView = [window rootViewController].view;
> +  
> +  CGFloat width = window.frame.size.width;
> +  CGFloat height = window.frame.size.height;
> +  
> +  // default to portrait orientation
> +  if (width > height) {
> +    __swap(&width, &height);
> +  }
> +  
> +  if (newScreenOrientation == UIInterfaceOrientationLandscapeLeft ||
> +      newScreenOrientation == UIInterfaceOrientationLandscapeRight
> +  ) {
> +    // manually switch to landscape orientation when changed.
> +    __swap(&width, &height);
> +  }
> +  
> +  if (rootView.frame.size.width != width ||
> +      rootView.frame.size.height != height
> +  ) {
> +    rootView.frame = CGRectMake(0, 0, width, height);
> +    NSLog(@"HACK!!! Updated RCTRootView::frame to %@", NSStringFromCGRect(rootView.frame));
> +  }
> +  
> +  [rootView layoutIfNeeded];
> +#endif
>  }
>  
>  #pragma mark - lifecycle
> diff --git a/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationViewController.m b/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationViewController.m
> index 8508789..fed05a8 100644
> --- a/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationViewController.m
> +++ b/node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationViewController.m
> @@ -6,6 +6,10 @@
>  #import <EXScreenOrientation/EXScreenOrientationRegistry.h>
>  #import <EXScreenOrientation/NSString+UIInterfaceOrientationMask.h>
>  
> +#if DEBUG
> +#import "EXScreenOrientationUtilities.h"
> +#endif
> +
>  NSString *const EXDefaultScreenOrientationMask = @"EXDefaultScreenOrientationMask";
>  
>  // copy of RNScreens protocol
> @@ -62,6 +66,12 @@ NSString *const EXDefaultScreenOrientationMask = @"EXDefaultScreenOrientationMas
>      return [screenOrientationRegistry requiredOrientationMask];
>    }
>    
> +#if DEBUG
> +  if ([EXScreenOrientationUtilities isIPad]) {
> +    return UIInterfaceOrientationMaskAll;
> +  }
> +#endif
> +  
>    return _defaultOrientationMask;
>  }
>  
> ```

I added this patch to my project, but it still doesn't seem to work.

**Comment by chris24elias** [comment]
happening to me too, expo-dev-client is breaking screen rotation on ios. expo please fix this

**Comment by fencer-yd** [comment]
> happening to me too, expo-dev-client is breaking screen rotation on ios. expo please fix this

Take advantage of @nn1900  solution, removing the judgment of isPad can temporarily solve your problem.

**Comment by chris24e** [comment]
> > happening to me too, expo-dev-client is breaking screen rotation on ios. expo please fix this
> 
> Take advantage of @nn1900 solution, removing the judgment of isPad can temporarily solve your problem.

This worked for me, thanks!

**Comment by derekstavis** [comment]
Also experiencing this issue on dev client after upgrading from 44 to 46.

**`App.tsx` code:**

<img width="733" alt="image" src="https://user-images.githubusercontent.com/1611639/184559594-a71f3d23-803a-4631-842b-828e52a52e81.png">

| Landscape | Portrait |
|--|--|
| ![IMG_5423](https://user-images.githubusercontent.com/1611639/184559538-90c4000c-1abb-4697-92b2-217dba0adc20.PNG) | ![IMG_5424](https://user-images.githubusercontent.com/1611639/184559543-1e2698c0-2de7-46bf-87c8-aa16fda5118e.PNG) |

**Dev client version**
<img src="https://user-images.githubusercontent.com/1611639/184559653-5ca87e9c-081b-4757-bb8d-1f2d7adc4a0f.PNG"  height="1024" />

**Comment by keith-kurak** [comment]
This is fixed in https://github.com/expo/expo/pull/18509 and is available in SDK 46/ `expo-dev-client` 1.2.1

**Comment by derekstavis** [comment]
Hey @keith-kurak -- this is still broken for me running `expo-dev-client@1.2.1`. Now I see that the status bar rotates, but the app content isn't rotating.

https://user-images.githubusercontent.com/1611639/187788854-037bebb2-19da-4042-b549-553a2bc6235b.mov

**Comment by ajsmth** [comment]
@derekstavis Is it possible you are setting the orientation of the app to be portrait only in your `app.json`? I've just tried to replicate with a fresh project with dev client installed and removed the `orientation` key in `app.json` and it works as expected. 

Another possibility might be if you are using `expo-screen-orientation` that is overriding the default behaviour when rotating the device - are you using this package in your project?

**Comment by derekstavis** [comment]
It was the latter. I followed https://github.com/expo/expo/issues/15009#issuecomment-1163071921 and it worked for me. I think the confusion for me stemmed from the fact that I thought that to support screen rotation I needed the `expo-screen-orientation` package, and I was not using it's config plugin. Adding the config plugin (or removing `expo-screen-orientation` solved the problem. I chose adding the config plugin as such:

```
  ...
  plugins: [
    [
      "expo-screen-orientation",
      {
        initialOrientation: "ALL",
      },
    ],
  ],
...
```

**Comment by tslater** [comment]
It is pretty hard to develop with this bug. This is not working for me:
```
  ...
  plugins: [
    [
      "expo-screen-orientation",
      {
        initialOrientation: "ALL",
      },
    ],
  ],
...
```

**Comment by tslater** [comment]
> expo-dev-client

### can confirm  that I'm still seeing this in SDK 46/ expo-dev-client 1.3.1

**Comment by abdymm** [comment]
> > happening to me too, expo-dev-client is breaking screen rotation on ios. expo please fix this
> 
> Take advantage of @nn1900 solution, removing the judgment of isPad can temporarily solve your problem.

hi @chris24elias @fencer-yd can you guys share your patch file for this `expo-screen-rotation` here? thankyou 🙏

**Comment by nn1900** [comment]
For the guys who experienced this issue before, now you can try to add the following value to your `Info.plist` file: 
```xml
<key>EXDefaultScreenOrientationMask</key>
<string>UIInterfaceOrientationMaskAllButUpsideDown</string>
```

The previous patch is no longer needed and does not work either. 
Check https://www.npmjs.com/package/expo-screen-orientation for more information. 

I tested on Expo 48, and everything works like a charm.

**Comment by tslater** [comment]
Still a problem for me with dev-client `~2.1.6` @keith-kurak  can we reopen?
