### ISSUE TITLE
Getting an error when trying to submit the app to app-store: ITMS-90338: Non-public API usage 

### ISSUE THREAD

**Issue by ornakash** [expo/expo#17768]
### Summary

I created a new application and I'm trying to submit it to App Store. but I keep getting an the following error message:
```ITMS-90338: Non-public API usage - The app references non-public selectors in app```

The full error message from apple is:

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "בדיקת תו נכה לרכב" 1.0.5 (1.0.5). Please correct the following issues, then upload again.
> 
> ITMS-90338: Non-public API usage - The app references non-public selectors in app: callWithArguments:, frameInfo, initWithFrame:configuration:, isMainFrame, navigationType, onSuccess:, setNavigationDelegate:, setProcessPool:, toDouble, userContentController, viewManager. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
> 
> Best regards,
> 
> The App Store Team
> 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Reproducible demo

I'll just post my package.json as this happens only in iOS and the code is fine

{
  "name": "tavneche",
  "version": "1.0.5",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "expo": "~45.0.0",
    "expo-ads-admob": "~13.0.0",
    "expo-status-bar": "~1.3.0",
    "expo-tracking-transparency": "~2.2.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-web": "0.17.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.66.13",
    "typescript": "~4.3.5"
  },
  "private": true
}

**Comment by GasparAdragna** [comment]
Same, getting almost the exact error.

**Comment by dericksa** [comment]
It seems this is happening with all flutter and react-native apps. 
There a lot of reports on this error here: https://developer.apple.com/forums/thread/127678?page=2

**Comment by mllngtn** [comment]
Just noting that's it's happening here, too

**Comment by tidusjar** [comment]
Happened to me yesterday, after changing almost nothing on the app from the previous update

**Comment by mitchobrian** [comment]
I think this is not an expo issue. It is related to Apple which checks some internal URIs and flag them as "not public" eg as insecure. hope they will change/fix this check soon!

**Comment by barthap** [comment]
Looks like this is fixed:

https://github.com/facebook/react-native/issues/33789#issuecomment-1148216533

**Comment by paulocoutinhox** [comment]
Hi,

Message from Apple: "The issue has been resolved on the app validation backend. Please try resubmitting. Sorry for the trouble."

Thanks.

**Comment by abazudosen** [comment]
> Hi,
> 
> Message from Apple: "The issue has been resolved on the app validation backend. Please try resubmitting. Sorry for the trouble."
> 
> Thanks.

still getting the same error.

**Comment by MattiaDiChiara** [comment]
still getting this error:
TMS-90338: Non-public API usage - The app references non-public selectors in APP_NAME: _isKeyDown, _modifiedInput, _modifierFlags.

**Comment by abumalick** [comment]
It happens when you try to submit a dev client build to testflight

**Comment by jbaxleyiii** [comment]
@abumalick @MattiaDiChiara did you end up finding a solution to submit dev client builds to testflight?

**Comment by abumalick** [comment]
No, I would love to have one

**Comment by sanoofrahiman960** [comment]
> Hi,
> 
> Message from Apple: "The issue has been resolved on the app validation backend. Please try resubmitting. Sorry for the trouble."
> 
> Thanks




 
--
 
. Please correct the following issues, then upload again.ITMS-90338: Non-public API usage - The app references non-public selectors in app_name: _isKeyDown, _modifiedInput, _modifierFlags. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions
 get response from apple connect how to solve this


 
--
 
Dear Developer,We identified one or more issues with a recent delivery for your app, "MilmaPMS" 1.0 (8). Please correct the following issues, then upload again.ITMS-90338: Non-public API usage - The app references non-public selectors in donamstechlabs.milmapms: _isKeyDown, _modifiedInput, _modifierFlags. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions
