### ISSUE TITLE
Standalone app serves cached js bundle

### ISSUE THREAD

**Issue by andyhbg** [expo/expo#1815]
As the title says. We are experiencing the same issue with cached js bundle as #1719 and [here](https://forums.expo.io/t/standalone-ios-app-update-doesnt-immediately-update-js/6164). The embedded JS bundle in the new version (uploaded to Itunes) is shown first after a restart of app. On first start a cached version is shown.

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.1 Build version 9B37
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^27.0.0 => 27.0.2
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/andy_hbg-707ec1ad-efbc-44ac-8981-71e066921a46.tar.gz

### Steps to Reproduce

1. Install version 1.3.3 (SDK 25) from App Store
2. Open it, showing version 1.3.3 (screen shot 1)
3. Update app with version 1.4.0 (SDK 27) via TestFlight
4. Open it, still showing version 1.3.3 and serves old js bundle but retrieves buildNumber 1.4.4 (from app.json) which belongs to version 1.4.0  (screen shot 2)
5. Close app, reopen, showing version 1.4.0 with buildNumber 1.4.4 (screen shot 3)

Not downloaded remotely because I have set "checkAutomatically": "ON_ERROR_RECOVERY"
This happens only IOS

### Expected Behavior
Embedded JS bundle should be served the first time.

### Actual Behavior
Cached JS bundle is served the first time and the new embedded JS bundle only after restart.

### Screen shots
1.
![img_1015](https://user-images.githubusercontent.com/8157298/40743787-c3ba6a26-6452-11e8-8913-e1a37ea8df76.png)

2.
![img_1016](https://user-images.githubusercontent.com/8157298/40743789-c3fa1d92-6452-11e8-8472-7bc0c381ca50.png)

3.
![img_1017](https://user-images.githubusercontent.com/8157298/40743788-c3db6884-6452-11e8-8143-ab3883d8ff8a.png)

**Comment by esamelson** [comment]
Hi @andyhbg - could you try making a new IPA build with `exp build:ios`? We deployed a fix for this issue to our build servers a week or two ago.

**Comment by andyhbg** [comment]
Hi @esamelson!

I have tried three new IPA today with same version 1.4.0 but different build numbers. All with the same result. Running the following command

`exp build:ios --release-channel prod-1.4.0`

**Comment by esamelson** [comment]
Hi @andyhbg -- sorry for the confusion. It appears the fix actually has not been deployed yet and will instead go out early next week. Apologies for the inconvenience!!

**Comment by andyhbg** [comment]
@esamelson Thanks for quick reply. Looking forward to the release.

**Comment by andyhbg** [comment]
We still have the same problem, using version 55.0.1
Has the fix been released?

**Comment by esamelson** [comment]
Hi @andyhbg - the fix has just been deployed earlier today. If you make a new IPA with `exp build:ios` it should have the expected behavior.

**Comment by terribleben** [comment]
Marking as pending so we can follow up here - as Eric mentioned, the fix has been deployed, so please go ahead and rebuild.

**Comment by andyhbg** [comment]
@esamelson, @terribleben Still the same problem 
Have tried several times, latest release 1.4.0-r.Bq9g1MD9Jk

**Comment by freinbichler** [comment]
We still experience this problem in our app. I made a new iOS build today and after submitting it to Testflight and updating from my old installed build to the new Testflight build, which even has a *different release channel*, the old JS bundle (from a different release channel) was loaded until I quit the app and restarted.

iOS 11.4
Expo SDK 28

Update from a Build with SDK 27 on release channel "default" to a build with SDK 28 on release channel "prod-v1". The cached JS bundle from the default release channel was loaded after updating.

Update Config:
```
    "updates": {
      "enabled": true,
      "checkAutomatically": "ON_LOAD",
      "fallbackToCacheTimeout": 0
    },
```

Let me know if you need more information. This issue is pretty big and should be a priority! Thank you for having a look.

**Comment by andyhbg** [comment]
Have also tried a new build today and still the same problem for us as well.
Two weeks ago since we released for Android, so hope for a solution soon.

**Comment by esamelson** [comment]
Hi @andyhbg @freinbichler - I am not able to repro this at all with the currently deployed iOS builders. It's possible, however, that the "base" IPA (the old version being installed over) has to be a version built with this fix (i.e. built since SDK 28 was released), as well as the "new" IPA (the one being newly installed). Are you both testing by installing over older IPAs that were built before this fix was released?

If so, unfortunately you may need to deal with this for one more upgrade cycle 😕 You can confirm it's fixed from now on by doing the following workflow (which is what I've been testing and has worked for me even with changing release channels and app.json settings):
1. Publish JS and build a "base" IPA
2. Install "base" IPA
3. Publish new JS
4. Reload installed app so that it's showing new JS
5. Publish another new JS, but _don't load it in the installed app_
6. Build a "new" IPA
7. Install new IPA over base, then correctly see newest JS

If this is not the case, and you are seeing different behavior when following this workflow ^ from step 1, would you be willing to share your build IDs?

**Comment by andyhbg** [comment]
@esamelson I can confirm that the above workflow works as expected if my "base" IPA is built with SDK 28. The problem is still that the app in App Store is built with SDK 25, I guess the only solution is to ask customers to restart the app after update. Thanks for the help
