### ISSUE TITLE
[expo-keep-awake][ios] Constant crashes / EXC_BAD_ACCESS / NSInvalidArgumentException

### ISSUE THREAD

**Issue by hirbod** [expo/expo#18292]
### Summary

expo-keep-awake is flooding my Sentry crash reports. Of course, I can't reproduce it, I don't know why it happens but I have a single use of expo-keep-awake, which I tried to replicate in a Snack

expo-dev-client

Here are the two sentry crash logs:

![Bildschirmfoto_2022-07-15_um_11 49 57](https://user-images.githubusercontent.com/504909/179730403-ee21cf49-7819-4217-993d-48166530b0c8.png)

![Bildschirmfoto_2022-07-15_um_14 23 01](https://user-images.githubusercontent.com/504909/179730411-cc2c0695-46ea-499a-91fc-2f28fd983ba2.png)

The only thing I am doing is to call `activateKeepAwake` and `deactivateKeepAwake` on focus/blur.
Thats it. It did not crash for me but for my users. I think it happens when the app was backgrounded for a while and when the user returns.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

```
  expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 3.2.0 - ~/.nvm/versions/node/v16.15.1/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2022.02.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 5.5.1
    Expo Workflow: bare
```

### Reproducible demo

https://snack.expo.dev/CD5WDZrXf

**Comment by axeldelafosse** [comment]
Can repro in the Showtime app too. Always on top of all the issues @hirbod haha -- thank you!

**Comment by daveslutzkin** [comment]
Yes, we're seeing this too. Seems to happen for us when the component calling useKeepAwake is being unmounted (and the stack trace is completely unhelpful unfortunately).

**Comment by barthap** [comment]
The most cryptic part is that both stacktraces point to lines that are typical [Swift Set](https://developer.apple.com/documentation/swift/set) operations:
1.
https://github.com/expo/expo/blob/40c4a73859a5e1676a9a3fd502d25b2a378b521a/packages/expo-keep-awake/ios/KeepAwakeModule.swift#L28

2.
https://github.com/expo/expo/blob/40c4a73859a5e1676a9a3fd502d25b2a378b521a/packages/expo-keep-awake/ios/KeepAwakeModule.swift#L31

The `activeTags` is just a normal module property:
https://github.com/expo/expo/blob/40c4a73859a5e1676a9a3fd502d25b2a378b521a/packages/expo-keep-awake/ios/KeepAwakeModule.swift#L5-L6

A memory leak? Wrong thread access? 🤔

**Comment by daveslutzkin** [comment]
@barthap ours was "unrecognised selector sent to instance" if that helps, but presumably that's not actually a useful thing.

**Comment by ajsmth** [comment]
@axeldelafosse @hirbod can we get clearer steps for a reproduction? Seems like a lot of people are seeing this!

**Comment by hirbod** [comment]
I wish I had more infos @ajsmth. I just made the example how I am using this module on my app - beside of that I don't know why it happens - I am just seeing a lot of these crashes in Sentry - I did not encounter them myself so far

**Comment by daveslutzkin** [comment]
Unfortunately it was intermittent for us. Because it happens when the component is unmounted, the reproduction was to click back and forward a lot of times in the nav and about 1 in 10 or 20 it would fail.

We've disabled keep awake until it's fixed so can't reproduce at this point.

**Comment by daveslutzkin** [comment]
Probably also worth noting that we only saw this after updating to expo 45 so my uninformed opinion is that it's probably related to this https://github.com/expo/expo/commit/02b61e24659a7cc448c788b7930003e299e2a29b

**Comment by barthap** [comment]
In SDK 46 beta, Swift modules are loading differently than in SDK 45 so the crash could be fixed, might be worth trying.

**Comment by daveslutzkin** [comment]
@barthap Hah yes, but as always updating a big dependency like Expo can cause more problems than it fixes (as we see with the 45 bump here creating this issue for us), so we don't really have the appetite for it right now - especially given it's an unpredictable and intermittent bug which has very negative user implications.

**Comment by barthap** [comment]
I'm sorry, I didn't make myself clear - I didn't mean to suggest updating production apps to 46 😅

**Comment by axeldelafosse** [comment]
Hey Andy and Bartłomiej! Our repo is open-source now so it might be really easy for you to reproduce. You can uncomment this code to reproduce the crash (happening at launch): https://github.com/showtime-xyz/showtime-frontend/commit/c46bfa85496e034fee3c89b4197feabf7f825c90. Let me know if you want to jump on a call to set up the app.

**Comment by ajsmth** [comment]
@axeldelafosse yes that would be great -- i'm having trouble reproducing, a call might help clarify some things!

**Comment by timlangeSystl** [comment]
Any news on this? Seeing this aswell.
Updated to Version 10.2.0. Im not able to reproduce but getting a lot crash reports.

**Comment by daveslutzkin** [comment]
@timlangeSystl

No idea as I'm not core team but the workaround is to remove the keep awake functionality (if you can), or to switch to https://github.com/sayem314/react-native-keep-awake (which would require a custom dev client if you're in managed).

**Comment by axeldelafosse** [comment]
@ajsmth you can book a time here: https://cal.com/axel

**Comment by barthap** [comment]
It's just my blind guess, but these crashes might be caused by some Swift closure stuff. You can try applying these changes using e.g. patch-package:

```diff
--- a/node_modules/expo-keep-awake/ios/KeepAwakeModule.swift
+++ b/node_modules/expo-keep-awake/ios/KeepAwakeModule.swift
@@ -8,9 +8,17 @@ public final class KeepAwakeModule: Module {
   public func definition() -> ModuleDefinition {
     Name("ExpoKeepAwake")
 
-    AsyncFunction("activate", activate)
-    AsyncFunction("deactivate", deactivate)
-    AsyncFunction("isActivated", isActivated)
+    AsyncFunction("activate") { (tag: String) -> Bool in
+      return activate(tag)
+    }
+
+    AsyncFunction("deactivate") { (tag: String) -> Bool in
+      return deactivate(tag)
+    }
+    
+    AsyncFunction("isActivated") { () -> Bool in
+      return isActivated()
+    }
 
     OnAppEntersForeground {
       if !self.activeTags.isEmpty {
```

Force downgrading `expo-keep-awake` to `10.0.2` might also do the job (not sure), but it could break Android.

Btw. Axel - I tried to run your project (I'm mostly familiar with the monorepo structure, I have an app based on your starter), but it failed on runtime when trying to load some custom fonts. Jumping on call doesn't really fit me this week.

**Comment by dorthwein** [comment]
We're running into this and trying this patch + some fixes for deprecation warnings.  Little different than above - tbd if it fixes.

```
diff --git a/node_modules/expo-keep-awake/.DS_Store b/node_modules/expo-keep-awake/.DS_Store
new file mode 100644
index 0000000..36d39ae
Binary files /dev/null and b/node_modules/expo-keep-awake/.DS_Store differ
diff --git a/node_modules/expo-keep-awake/ios/KeepAwakeModule.swift b/node_modules/expo-keep-awake/ios/KeepAwakeModule.swift
index 00cffbd..d67f177 100644
--- a/node_modules/expo-keep-awake/ios/KeepAwakeModule.swift
+++ b/node_modules/expo-keep-awake/ios/KeepAwakeModule.swift
@@ -6,18 +6,30 @@ public final class KeepAwakeModule: Module {
   private var activeTags = Set<String>()
 
   public func definition() -> ModuleDefinition {
-    name("ExpoKeepAwake")
+    Name("ExpoKeepAwake")
+
+    // function("activate", activate)
+    // function("deactivate", deactivate)
+    // function("isActivated", isActivated)
+    AsyncFunction("activate") { (tag: String) -> Bool in
+      return self.activate(tag: tag)
+    }
+
+    AsyncFunction("deactivate") { (tag: String) -> Bool in
+      return self.deactivate(tag: tag)
+    }
+    
+    AsyncFunction("isActivated") { () -> Bool in
+      return isActivated()
+    }
 
-    function("activate", activate)
-    function("deactivate", deactivate)
-    function("isActivated", isActivated)
 
-    onAppEntersForeground {
+    OnAppEntersForeground {
       if !self.activeTags.isEmpty {
         setActivated(true)
       }
     }
-    onAppEntersBackground {
+    OnAppEntersBackground {
       if !self.activeTags.isEmpty {
         setActivated(false)
       }
```

**Comment by trajano** [comment]
Eventually saw this after I did my [own digging](https://forums.expo.dev/t/how-would-i-diagnose-a-sigsegv-error-that-appears-to-only-occur-on-testflight-builds-on-keep-awake-module/65550/2).

Anyway is there a solution for managed yet?

**Comment by trajano** [comment]
Doing the downgrade to expo keep awake prevents it from building on Android EAS

**Comment by hirbod** [comment]
For now - until resolved - I would recommend using https://github.com/sayem314/react-native-keep-awake @trajano 
Works fine.

**Comment by barthap** [comment]
Ok people. If nobody is able to provide a reliable way to reproduce (I know it might be difficult) or check if the patch I provided fixed the crashes, we won't be able to fix it.

**Comment by hirbod** [comment]
I would love to test the patch @barthap, the issue is that I can't reproduce it. Testing it would force me to release a patch to the user base, which is a gamble for me. I don't have any A/B release plan/path.

**Comment by daveslutzkin** [comment]
Frustrating if it can't be fixed but that means the only responsible thing to do is remove expo-keep-awake in favour of react-native-keep-awake - otherwise people adopting expo are going to get random crashes that they can't diagnose or do anything about.

**Comment by brentvatne** [comment]
@daveslutzkin - this seems like a good workaround for now. I pinged a couple people about this internally and we'll follow up early next week. if you want to try @barthap's patch that would be very helpful as well.

**Comment by hirbod** [comment]
@brentvatne @barthap I've figured that even uninstalling expo-keep-awake, it will still be autolinked with expo. 

So following the link from @brentvatne I added an exclusion to package.json. 

```
  "expo": {
    "autolinking": {
      "exclude": [
        "expo-keep-awake"
      ]
    }
  },
```

After doing so, I get the following warning:
<img width="1415" alt="Bildschirmfoto 2022-08-07 um 13 22 58" src="https://user-images.githubusercontent.com/504909/183288230-f91ead9a-d925-408e-892c-c34fd5326dd6.png">

I think one Expo package does still call this internally? Like dev client or something?

**Comment by hirbod** [comment]
Looks like it was added by @Kudo 
https://github.com/expo/expo/commit/3bbd6603335f880da318c4260898875d84be39b8#diff-30274671a7eb1987c7142f8c163acdc733016fb7ba319478262b239afa779ff7

**Comment by trajano** [comment]
> For now - until resolved - I would recommend using https://github.com/sayem314/react-native-keep-awake @trajano Works fine.

Thanks @hirbod this appeared to have worked on an EAS build

**Comment by hirbod** [comment]
I'll release an app update including the change this week. Might take 10 days for further feedback.

**Comment by tsapeta** [comment]
As the @expo-bot said above, I've just published a potential fixes for these crashes in version `10.2.1`. Please keep in mind that we were not able to reproduce the issue and so we couldn't test if it really fixes the issue. Volunteers are welcome 😄 
`10.2.x` versions are generally intended to be used with SDK46, but this one should also be compatible with SDK45.

Even though I hope it solves the problem, I'm reopening it until I get a confirmation that it works and doesn't cause any more crashes.

**Comment by hirbod** [comment]
So far, no more crashes with our current version and 10.2.1. Let's give it a couple more days but it looks promising.

**Comment by wilcoxky** [comment]
I had this crash with 10.2.1 on bareworkflow.

**Comment by hirbod** [comment]
@tsapeta I can once confirm, that I haver never seen this issue again after your potential fix. I think this issue is fixed.

**Comment by robertontiu** [comment]
Hi - we can still see this issue on iOS after v10.2.1 upgrade and with expo 46. Any news or ways to fix it? The crash is quite frequent as well. (think we have at least 20 users who have encountered this at least once in the past week)

<img width="1939" alt="image" src="https://user-images.githubusercontent.com/9152337/233285028-ad8bbe79-d4cf-4a09-9a62-b5078fbf93f0.png">

**Comment by summer-wu** [comment]
I don't think someone in this thread really find the root cause, I think the root cause is thread-unsafety of Set. You can only access a Set via only one thread, if you access the Set via global_queue, you are in danger. The simplest bugfix is to wrap all the accesses in `DispatchQueue.main.async {}`.

You can test the thread-unsafety of Set using below code(just create a Command Line project, then paste): 
```
import Foundation

var greeting = "Hello, playground"
print("a=\(greeting)");
var awakeFlags = Set<String>()

let semaphore = DispatchSemaphore(value: 0);
class Producer:Thread{
    override func main() {
        print("Producer: this is producer");
        
        for i in 1...1000 {
            let milliseconds = Int.random(in: 1...5)
            usleep(useconds_t(milliseconds * 1000));
            DispatchQueue.global().asyncAndWait(execute: DispatchWorkItem(block: {
                awakeFlags.insert("EXPO_FLAG");
            }))
            
            
            print("Producer: \(i) awakeFlags.count: ",awakeFlags.count);
        }
        
        semaphore.signal();
    }
}


class Consumer:Thread{
    override func main() {
        print("Consumer: this is Consumer")
        
        for i in 1...1000 {
            let milliseconds = Int.random(in: 1...5)
            usleep(useconds_t(milliseconds * 1000));
            DispatchQueue.global().asyncAndWait(execute: DispatchWorkItem(block: {
                if !awakeFlags.isEmpty{
                    awakeFlags.remove("EXPO_FLAG");
                }
            }))
            
            print("Consumer: \(i) awakeFlags.count: ",awakeFlags.count);
        }
        
        semaphore.signal();
    }
}



let p = Producer()
p.name = "Producer"
let c = Consumer()
c.name="Consumer"
p.start()
c.start()
semaphore.wait()
semaphore.wait()
print("will exit")
exit(0)
```
