### ISSUE TITLE
Using PROVIDER_GOOGLE with react-native-maps crashes iOS Simulator in latest Expo Go

### ISSUE THREAD

**Issue by iM-GeeKy** [expo/expo#18530]
### Summary

Using the `provider={PROVIDER_GOOGLE}` with a valid Google Maps API key in the `MapView` component causes the iOS simulator to crash. Running the code on a physical device however, does in fact render the map properly.

Issue opened on `react-native-maps` as well https://github.com/react-native-maps/react-native-maps/issues/4379

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

46.0.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.2 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.3 => 0.69.3 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.57.0
      expo-cli: 6.0.1
    Expo Workflow: managed

### Reproducible demo

This was created using `npx create-expo-app my-app`.

https://github.com/iM-GeeKy/my-app/tree/master

**Comment by H4ck3r-x0** [comment]
Same here, after upgrading expo SDK to 46 google maps crashed. But when I change the MapView provider prop to use apple's map issue solved.


```

<MapView
                region={region}
                scrollEnabled={true}
                pitchEnabled={true}
                // provider={PROVIDER_GOOGLE} issue 
                maxZoomLevel={10}
                style={styles.map}>

                {/* {pickupCords && <Marker coordinate={pickupCords} />}
                {dropOffCords && <Marker coordinate={dropOffCords} />} */}
            </MapView>
```

**Comment by Rudiney** [comment]
> 

Had the exact same situation here.

**Comment by Cleversou1983** [comment]
I'm facing the same problem here...

**Comment by SohelIslamImran** [comment]
I'm facing the same problem here...

**Comment by SohelIslamImran** [comment]
And Google Map not visible on android

**Comment by itrcz** [comment]
Same story, apple maps works okay, google is crashing. Android got just blank view.

**Comment by hlthi** [comment]
It is not SDK 46 problem! 

With SDK 45, Expo Go 2.25.1 grey block on android, crash on ios.
With SDK 46, Expo GO 2.25.1 grey block on android, crash on ios.

But,
With SDK 45, Expo Go 2.24.3 work.

How to downgrade Expo 45 with Expo Go 2.24.3.

- Delete Expo Go app from Simulator and Real Device.
1. expo upgrade 45
 - Downgrade to sdk 45, because  Expo Go 2.24.3  doesn't support Expo SDK 46.
3. expo start
  - Expo , automatically install expo go 2.24.3.
  - 
Now you can wait for fix Expo Go problem :)

**Comment by H4ck3r-x0** [comment]
Waiting for the fix, so I can publish.

**Comment by byCedric** [comment]
This should be resolved in the latest Expo Go version! (`2.25.2`)

**Comment by Rudiney** [comment]
thats really awesome! thanks folks! ❤️

**Comment by dhmoon91** [comment]
Anyone still facing the issue?

Using Expo-sdk 46, Expo-go; 2.25.3.101

**Comment by carlashawol** [comment]
I'm still facing this issue in the latest version of expo (sdk 46)

**Comment by marianif** [comment]
Hi Guys! I was having the same issue running an IOS Simulator build (SDK 46).

in app.json ios.infoPlist I changed the former permission NSLocationUsageDescription with the new one NSLocationWhenInUseUsageDescription (in my case this solved the issue cause i was foreground tracking the user position).

Now it works properly.

Hope it helps someone with my same test scenario

**Comment by stuartrapop** [comment]
[marianif](https://github.com/marianif), It seems to me that NSLocationUsageDescription is still valid for MacOS and that it is NSLocationAlwaysUsageDescription which has been deprecated.

**Comment by marianif** [comment]
@stuartrapop this issue is about IOS not macOs,  as you can see [Here in the Offical Docs](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationusagedescription) the permission is deprecated for iOS 6.0–8.0 infact in my case changing the permission name to **NSLocationWhenInUseUsageDescription** solved my issue. NSLocationWhenInUseUsageDescription
it's not deprecated at all for IOS, just read the docs

**Comment by dhanasekarancm** [comment]
I have referenced the example app and modified the API key as follows in `AppDelegate.mm`

`[GMSServices provideAPIKey:[[NSBundle mainBundle] objectForInfoDictionaryKey:@"MAPS_API_KEY"]];`

However, it only functions correctly when added as indicated in the documentation:

`[GMSServices provideAPIKey:@"MAPS_API_KEY"];`
