### ISSUE TITLE
Iphone X crashes on FaceID scan on Expo.Fingerprint.authenticateAsync func

### ISSUE THREAD

**Issue by Jose2x** [expo/expo#1901]
hi,

I am creating an app that scans for fingerprint or FaceID on Iphone X.
The app works great on all devices android and IOS except Iphone X  with FaceID.
My code is based on this snack:
https://snack.expo.io/@adamjnav/fingerprint-example

await Expo.Fingerprint.hasHardwareAsync()); // return TRUE
await Expo.Fingerprint.isEnrolledAsync()); // returns TRUE when face enrolled
await Expo.Fingerprint.authenticateAsync('Login'); // CRASH black screen no logs

advice please.

thanks!

**Comment by lucas1richard** [comment]
We are having the same problem. It's only crashing on expo, not on the TestFlight build. Fingerprint still works fine on expo with an iPhone 6.

**Comment by JEGardner** [comment]
We are also experiencing this. We have tested on 2 iPhone X's while the app is in production mode in TestFlight, and the app crashes as soon as authenticateAsync is called on iPhone X. Works perfectly on other devices.

For us it works in development within the Expo app, but crashes in a production standalone build through TestFlight.

**Comment by yarrumretep** [comment]
I have this same problem - call to authenticateAsync crashes.  NOTE: this was working before - and there could be two changes since last-known-good (a) new Expo Client version (new icon) and (b) new iPhone X (previous one died)

**Comment by yarrumretep** [comment]
Is this a possible relevant change: https://github.com/expo/expo/commit/5cfcab59016fdd6fd4aafed143558749b844cccf#diff-f50881d13a41dc11fc1ebc61091421a9

Would this April 27th commit have only been recently pushed to production Expo Client?

**Comment by esamelson** [comment]
Hi all - we'll look into this as soon as we can. Thanks for the report.

**Comment by Stefanama** [comment]
@esamelson @barthec I appreciate you guys are working on it, meanwhile do you reckon there is a way to "hack it" into working? 

@lucas1richard has the opposite issue, it works on testflight but crashes on the expo client whilst for us it works on the expo client but crashes (SDK 26)/fallback on Passcode(SDK 28) on Testflight.

Thank you very much for your help :)

**Comment by Stefanama** [comment]
these guys seem to have a similar issue on their react-native-touch-id, maybe their solution can apply on Expo as well? 
https://github.com/naoufal/react-native-touch-id/issues/111

**Comment by Stefanama** [comment]
@esamelson @barthec I can confirm that adding 
```
"ios" : {
      "bundleIdentifier": "com.coolbeans",
      "infoPlist": {
        "NSFaceIDUsageDescription": "This app will optionally use Face ID or Touch ID to save login"
      }
    },
```

solved the crashing issue

**Comment by terribleben** [comment]
Thanks for digging into this, we can improve our documentation to mention adding this key when using FaceID.

**Comment by ziyoshams** [comment]
Didn't work for me.
```"ios" : {
      "bundleIdentifier": "com.coolbeans",
      "infoPlist": {
        "NSFaceIDUsageDescription": "This app will optionally use Face ID or Touch ID to save login"
      }
    },```

**Comment by lucas1richard** [comment]
@esamelson @barthec @Stefanama We've had the infoPlist `NSFaceIDUsageDescription` since before the issue came up.

**Comment by yarrumretep** [comment]
For what it's worth, the addition of the infoPlist entry for NSFaceIDUsageDescription as described above did not change the behavior for us.  authenticateAsync() does not do face-id, just prompts directly for the numeric passcode.

```

**Comment by terribleben** [comment]
Acknowledging the last few comments, sounds like the info.plist config is not the solution. Will update my previous comment.

**Comment by bravetarget** [comment]
using react-native `NativeModules.ExponentFingerprint.authenticateAsync(...)` directly when FaceID is detected seems to be an easy temporary workaround while the Expo module gets smoothed out.

**Comment by ranyehushua** [comment]
@bravetarget that suggestion did not work for me unfortunately.

**Comment by bravetarget** [comment]
@ranyehushua possibly use in tandem with the app.json infoPlist entry?  using both solutions made FaceID operational for us.

**Comment by ranyehushua** [comment]
@bravetarget unfortunately the combination of the 2 is also not working for us. One thing that is interesting is that under the iPhone X faceID settings, the Expo app is not listed under apps that have requested use of FaceID. Does Expo appear in that application list for you?

**Comment by ranyehushua** [comment]
@bravetarget, or does this only fix your issue when deployed as a standalone app (not using the Expo app to view)?

**Comment by bravetarget** [comment]
@ranyehushua If you're running it from the Expo Client on the device then it won't list as a separate app in the system settings.  If you install a standalone app, then it should appear there.

**Comment by ranyehushua** [comment]
@bravetarget, understood. So with your solution in place are you able to run your app through Expo (not as a standalone) with the faceID functioning?

**Comment by tsapeta** [comment]
We fixed this issue in the latest release (SDK 29). Unfortunately, FaceID authorization **will not** work in Expo Client, but will work if you add `NSFaceIDUsageDescription` to your `app.json` (as described above) and then build your app with `exp build`. Sorry for the limitation.

**Comment by ranleung** [comment]
@tsapeta I am still having the same problem even with updated SDK 29 release.

It is still crashing on`await Expo.Fingerprint.authenticateAsync('Login')` // CRASH

```
"expo": "^29.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz",
```

Instead of a blank screen I am getting:
![95442](https://user-images.githubusercontent.com/5177175/43423304-e9f24cb2-9400-11e8-974d-5428df2580c0.jpg)

Thanks

**Comment by allankikkas** [comment]
Could you create a fallback options to not get instant fatal error in development mode if faceID is used (for example custom error message as a callback instead of redscreen).  And also add information about this issue to docs.

**Comment by tsapeta** [comment]
Hi @allankikkas, sure, thanks for your suggestion! I'll add this to our docs.
Sorry for this fatal error, I guess it could just fallback to passcode authentication or so in that case. We will try to improve this behavior.

**Comment by tsapeta** [comment]
@JackHowa The fallback to device passcode will be included in the next release (SDK 30) that we're going to roll out pretty soon!

**Comment by tsapeta** [comment]
Hi @valmotor2,
So far, it's not possible using `LocalAuthentication` API (`Fingerprint` has been renamed in SDK30), but I can imagine it might be useful to have some kind of `authenticationType` which could be `TouchID` or `FaceID`. I'm adding this feature to our stack, thanks 😄 
Until then, you can try using [Expo.Constants.deviceName](https://docs.expo.io/versions/v30.0.0/sdk/constants#expoconstantsdevicename) and just compare if it's iPhone X or newer.

**Comment by JackHowa** [comment]
Thanks @tsapeta, the fallback works in SDK 30
