### ISSUE TITLE
IOS Picker results in type 'image' for both videos and photos

### ISSUE THREAD

**Issue by allonahmed** [expo/expo#19883]
### Summary

Currently using React Native v0.70.4 and the new expo 47. When selecting a media file using the `launchImageAsync` method, we get an object that looks something like: 
`results Object {
  "assets": Array [
    Object {
      "assetId": "67FF08DD-5757-HGH3/L0/001",
      "base64": null,
      "duration": 53540,
      "exif": null,
      "fileName": "IMG_5233.MOV",
      "fileSize": 334231851,
      "height": 2160,
      "type": "image",
      "uri": "file://path/location/Library/Caches/ImagePicker/BE37B007-E9B3-4E48-AD18-90400A00D11D.mov",
      "width": 3840,
    },
  ],
  "canceled": false,
  "cancelled": false,
}`
The 'type' key returns 'image' for MOV files on IOS

### What platform(s) does this occur on?

iOS

### SDK Version

14

### Environment

    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.4.0 => 0.4.0 
      @expo/webpack-config: ^0.17.2 => 0.17.3 
      expo: ~47.0.1 => 47.0.1 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.4 => 0.70.4 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      expo-cli: 6.0.2
    Expo Workflow: bare

### Minimal reproducible example

`export const UploadMedia = async (
  setMedia: React.Dispatch<React.SetStateAction<string>>, mediaTypes: 'Images' | 'Videos' | 'All' , multi = false ) => {
  // No permissions request is necessary for launching the image library
  const result = await Picker.launchImageLibraryAsync({
    mediaTypes: Picker.MediaTypeOptions[mediaTypes],
    allowsEditing: true,
    aspect: [4, 3],
    quality: 1,
    allowsMultipleSelection: multi
  });

  if (!result.canceled) {
    console.log('results', result);
    setMedia(result.assets[0].uri);
  }
};`

**Comment by vbylen** [comment]
can confirm, I am also experiencing this

**Comment by tsapeta** [comment]
I've just published `expo-image-picker@14.0.1` that includes a fix for this 😉
You can upgrade it right away if you're not using Expo Go which should get this update in a few days.

**Comment by osztenkurden** [comment]
Issue still persists, at least for me on Expo 47 and expo-image-picker@14.0.2

**Comment by udokaokoye** [comment]
Here is a fix;
make sure your expo-image-picker is running on version @14.01
then update the expo go app to the latest version. 

14.0.1 seems to be the only version that works as of now

**Comment by chirag-codealchemy** [comment]
i try version 14.0.1, 14.0.2, 14.0.3 
all are not working for me (only in ios) (work well in android )
it's gives file type image but it's video
