### ISSUE TITLE
Expo 47 react-native-svg update to 13.4.0 can crash Android - fixed in 13.5.0+  

### ISSUE THREAD

**Issue by Codelica** [expo/expo#20396]
### Summary

Expo 47 takes react-native-svg from 12.3.0 to 13.4.0.  However 13.4.0 has an incompatibility with UI Kitten (and other libs that may pass null for color) which is solved in 13.5.0+.  Using 13.4.0 results in a native Android crash detailed at https://github.com/software-mansion/react-native-svg/issues/1899

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.10 => 46.0.13 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    npmGlobalPackages:
      eas-cli: 2.7.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

Triggered when using Kitten UI lib which uses tintColor property.   

Basic reproducible best detailed on this post: https://github.com/software-mansion/react-native-svg/issues/1899.)#issuecomment-1304644745

**Comment by iM-GeeKy** [comment]
I'm using [patch-package](https://www.npmjs.com/package/patch-package) to apply this patch  https://github.com/software-mansion/react-native-svg/commit/8cf406888034c6a468e652558fea8236a01a75c9#diff-73bfcd6b9672fc9694913b10a232038470557fd02a8d688932f64cdc4dc26fbfR111 while we wait for the upgrade to `13.5.0` to officially resolve the issue.

**Comment by gloredo** [comment]
Same issue here, using `react-native-svg 13.0.5` as a workaround.

**Comment by thedoublejay** [comment]
Same here

**Comment by iegik** [comment]
Do not use svg's in react-native as workaround.

**Comment by javier-zabala-lenio** [comment]
I've also encountered this issue

**Comment by borstelmannl** [comment]
> Same issue here, using `react-native-svg 13.0.5` as a workaround.

There is no version 13.0.5 for me? Can you recheck which version u use as workaround currently?

**Comment by geosotirlis** [comment]
I am having the same issue here and while using ui kitten eva icons and expo. What is the appropriate workaround on that in order to make that work with managed workflow build?

**Comment by borstelmannl** [comment]
> I am having the same issue here and while using ui kitten eva icons and expo. What is the appropriate workaround on that in order to make that work with managed workflow build?

i am running sdk47 with react-native-svg set to 13.2.0 set in package.json, and it seems to work for now.

**Comment by siarheipashkevich** [comment]
@gloredo @borstelmannl what about warning from `expo doctor` because this versions incompatible with expo sdk 47?

**Comment by borstelmannl** [comment]
@siarheipashkevich no problems in production so far. But i saw that expo managed to update to react-native-svg 13.4 so the problem should be fixed now with ui-kitten.

**Comment by mkhib** [comment]
I still have this issue
Expo version ~47.0.12
react-native-svg version 13.4.0
@ui-kitten/eva-icons version 5.1.2

**Comment by borstelmannl** [comment]
@mkhib you are right my bad. It is fixed in 13.5+ so 13.4 is still an issue with ui-kitten.
You can use version 13.2 of react-native-svg for now.

**Comment by Codelica** [comment]
I waited out 47 due to this, but it looks like 48 has the same issue. :(  Surprised this didn't get any attention considering it was a big jump for the SVG package in 47 and should be a simple fix.  Will try rolling back to 13.2.0 for now, but hope this gets some attention.

**Comment by Codelica** [comment]
Well Expo 48 seems to make things more "interesting"...

iOS builds with react-native-svg @ 13.2.0 (the workaround version) fail for me with:

`[!] Unable to find a specification for 'React-RCTFabric' depended upon by 'RNSVG'`

However they do build for Android using 13.2.0

Using react-native-svg @ 13.4.0 will build for iOS and Android, but then we hit the Android issue here.

Using react-native-svg @ 13.5.0 will build for iOS and Android, but development using Expo Go will only work for iOS as presumably it's compiled using react-native-svg @ 13.4.0 so the exception hits. 

So as far as I see the only way to avoid this dependency mess with Expo 48 between iOS, Android, and development using Expo Go would be to make a custom dev client.  Which seems like a little much just for this. 👎  Hopefully I'm wrong.

**Comment by iM-GeeKy** [comment]
> Well Expo 48 seems to make things more "interesting"...
> 
> iOS builds with react-native-svg @ 13.2.0 (the workaround version) fail for me with:
> 
> `[!] Unable to find a specification for 'React-RCTFabric' depended upon by 'RNSVG'`
> 
> However they do build for Android using 13.2.0
> 
> Using react-native-svg @ 13.4.0 will build for iOS and Android, but then we hit the Android issue here.
> 
> Using react-native-svg @ 13.5.0 will build for iOS and Android, but development using Expo Go will only work for iOS as presumably it's compiled using react-native-svg @ 13.4.0 so the exception hits.
> 
> So as far as I see the only way to avoid this dependency mess with Expo 48 between iOS, Android, and development using Expo Go would be to make a custom dev client. Which seems like a little much just for this. 👎 Hopefully I'm wrong.

Hey @Codelica, I've had some success getting my Expo Go app running and deployable on iOS and Android using Expo 48. I'm on react-native-svg `13.4.0` and have been using the patch I [mentioned above](https://github.com/expo/expo/issues/20396#issuecomment-1345341876) since Expo 47. Hopefully that will help get you working, until at least react-native-svg `13.5.0` is supported.

**Comment by Codelica** [comment]
@iM-GeeKy thanks for the info and sorry I missed it.  I'll be sure to try it out tomorrow.  👍

**Comment by Codelica** [comment]
@iM-GeeKy so are you literally using Expo Go with SDK 48 and react-native-svg 13.4.0 (under Android) successfully?  I can see how the Java patch could work for builds (and custom dev build), but am assuming Go is beyond help since it's presumably compiled with unpatched 13.4.0 already.

**Comment by iM-GeeKy** [comment]
> @iM-GeeKy so are you literally using Expo Go with SDK 48 and react-native-svg 13.4.0 (under Android) successfully? I can see how the Java patch could work for builds (and custom dev build), but am assuming Go is beyond help since it's presumably compiled with unpatched 13.4.0 already.

That's correct. My app works on Expo Go on both platforms and standalone builds are working as well under react-native-svg 13.4.0 using the applied patch.

**Comment by Codelica** [comment]
@iM-GeeKy but the [patch](https://github.com/software-mansion/react-native-svg/commit/8cf406888034c6a468e652558fea8236a01a75c9#diff-73bfcd6b9672fc9694913b10a232038470557fd02a8d688932f64cdc4dc26fbfR111) linked is for the native Android Java code which Go already has compiled and unpatched.  I can see how it would fix new builds, but considering Go just takes the JS runtime code I can't see how that would work unless I'm missing something.  Any chance you're not affected by this any more, like the component triggering it was updated to include length or was removed?

**Comment by flexbox** [comment]
My 2 cents on this issue

I encountered this issue after upgrading to Expo SDK 48
```
NullPointerException com.horcrux.svg.SvgView in setTintColor
Unhandled
Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
```
here is my sentry stack trace
![image](https://user-images.githubusercontent.com/360936/225572998-a58a781f-95b6-443d-a01d-d89241d39844.png)

...because I forgot I [fixed the problem in January](https://github.com/akveo/react-native-ui-kitten/issues/1705) 😂 


**Solution**
bump `react-native-svg` fixed my problem

```diff
"expo": "^48.0.6",
--    "react-native-svg": "13.4.0",
++    "react-native-svg": "^13.8.0",
```


If you run `npx expo-doctor`, just ignore the warning 🙈 
```
Issues:
  Some dependencies are incompatible with the installed expo version:
    react-native-svg@13.8.0 - expected version: 13.4.0
  Your project may not work correctly until you install the correct versions of the packages.
  Install individual packages by running npx expo install react-native-svg@13.4.0
  Found outdated dependencies
```

**Comment by Codelica** [comment]
@flexbox using 13.5.0+ will work for builds (warning aside), but what are you doing for development -- custom dev build?  Since Go is compiled with 13.4.0 it will throw an render error re: RNSVGSvgViewAndroid which doesn't exist.

**Comment by flexbox** [comment]
@Codelica It's weird I got other issues today (not )

No problem on Android 8
Crash on Android 12 (but not raising on Sentry 🤯)
```
Invariant Violation: requireNativeComponent: "RNSVGSvgViewAndroid" was not found in the UIManager.
```

here is [what I have done to make it work](https://github.com/akveo/react-native-ui-kitten/issues/1705#issuecomment-1472644846)

**Comment by Codelica** [comment]
I'm using Kitten's `IconRegistry` to register `EvaIconsPack` as well as several sets from `@expo/vector-icons`.   I was already processing `tintColor` and deleting it before passing in the remaining `style` with the Expo icons I was registering (as it's my code). However `EvaIconsPack` does not do this and was the source of my trouble.   For anyone looking to sanitize `EvaIconsPack` manually *for now*, just use the following to import `{EvaIconsPack}` rather than from `@ui-kitten/eva-icons` and Eva icons will work with 13.4.0 and Android, both builds and Go.

```js
import React from 'react';
import { StyleSheet } from 'react-native';
import { IconProvider, IconPack } from '@ui-kitten/components';
import { SvgProps } from 'react-native-svg';
import { findIconByName } from 'react-native-eva-icons/icons';

type IconElement = React.ReactElement<SvgProps>;
type IconComponent = React.ComponentType<SvgProps>;

class EvaIcon implements IconProvider<SvgProps> {

  constructor(private content: IconComponent) {
  }

  public toReactElement(props: SvgProps): IconElement {
    const Icon: IconComponent = this.content;

    const { style, ...svgProps } = props;
    // @ts-ignore - UI Kitten components pass here `tintColor`
    const fillColor: string = StyleSheet.flatten(style || {}).tintColor;

    // TODO: Get rid of tintColor for react-native-svg 13.4.0
    // Remove this file and revert back to native UI Kitten EvaIconsPack once resolved
    let cleanStyle = StyleSheet.flatten(style || {});
    // @ts-ignore - UI Kitten components pass here `tintColor`
    delete cleanStyle.tintColor;

    return (
      <Icon
        style={cleanStyle}
        fill={fillColor}
        {...svgProps}
      />
    );
  }
}

export const createIconsMap = (): { [key: string]: IconProvider<SvgProps> } => {
  return new Proxy({}, {
    get(target, name: string): IconProvider<SvgProps> {
      return new EvaIcon(findIconByName(name));
    },
  });
};

export const EvaIconsPack: IconPack<SvgProps> = {
  name: 'eva',
  icons: createIconsMap(),
};
```

**Comment by brentvatne** [comment]
we still use react-native-svg@13.4.0 in sdk-48, but you can update to 13.5.0 or another more recent version - it just won't work in expo go, but works fine with [development builds](https://docs.expo.dev/develop/development-builds/use-development-builds/) and release builds, as @flexbox pointed out. you can ignore the warning about not using the suggested version because you are doing that intentionally. in sdk 49, we're going to make it possible to opt out of these dependency warnings because they are more recommendations than requirements in any context outside of expo go.

**Comment by Codelica** [comment]
@brentvatne any chance of moving to 13.5.0+ in sdk-49 ?   Development builds work, but was hoping to avoid the additional work that comes with (maintaining and distributing dev clients) for this issue alone.  Thanks!

**Comment by Codelica** [comment]
@brentvatne sorry to ping again, but please consider moving to react-native-svg 13.5.0+ in SDK 49. 🙏  I'm still patching random 3rd party SVG components which have `tintColor` in their `style` which makes Android blow up in the current 13.4.0 which Go uses.  With a small dev team (just me ;) ) I'm hoping to avoid custom dev clients just for this issue, which react-native-svg patched for good reason.  Thanks... 👍

**Comment by brentvatne** [comment]
@Codelica https://github.com/expo/expo/pull/22934

**Comment by ricardopacheco** [comment]
> @Codelica #22934

The problem persists, even using this version and with the recent expo 49 version.
