### ISSUE TITLE
ExpoKit v29 - Detached Android Build won't load after splashscreen

### ISSUE THREAD

**Issue by ejimenez93** [expo/expo#2059]
### Environment
```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 9.2.0
  Yarn: 1.3.2
  npm: 6.1.0
  Watchman: Not Found
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: 29.0.0 => 29.0.0
  react: 16.4.1 => 16.4.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4
```

Only occurs in Latest ExpoKit Android: https://docs.expo.io/versions/v29.0.0/expokit/expokit#android
iOS works just fine

**Note: ** Relates to **Issue #2038**

**Comment by wjielim** [comment]
Same case here on Windows 10

**Comment by N1ghtly** [comment]
Running into this issue as well. Anyone got a solution?

**Comment by Daadler6** [comment]
Getting the same issue. @N1ghtly @ejimenez93 - any update on what the solution was?

**Comment by ljubomir-digihey** [comment]
Same problem on SDK 30,
anyone had any luck figuring this out?

**Comment by ljuborados** [comment]
Same issue on SDK 30,
anyone had any luck fixing this?

**Comment by Daadler6** [comment]
@ljuborados I fixed it using the following solution:

https://github.com/expo/expo/issues/2486

**Comment by ljuborados** [comment]
@Daadler6 that worked for me as well, thanks!

**Comment by sy92th** [comment]
Still not working in V31 ( I directly detach from version 31 )
  ```
Expo CLI 2.6.14 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - /usr/local/opt/node@8/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.0.9 
    npmGlobalPackages:
      expo-cli: 2.6.14
```
It working in ios but not in Android ( in release version)

**Comment by tmjordan** [comment]
Same still not working in V31 and V32. Only on android

**Comment by tmjordan** [comment]
@Daadler6, hi, i already had those lines in my proguard-rules file after ejecting my expo app. But the problem persists, still stuck on the blank screen after splashscreen

**Comment by juanjoslopezv** [comment]
Having the same issue with SDK 32 on Android with not Ejected App
  Expo CLI 2.11.7 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.11.7

**Comment by tsapeta** [comment]
SDK29 and ExpoKit are no longer supported so I'm closing this issue.
