### ISSUE TITLE
Branch links not working when app is first opened

### ISSUE THREAD

**Issue by AdamPD** [expo/expo#2085]
### Environment

Environment:
  OS: Windows 10
  Node: 8.4.0
  Yarn: 1.9.2
  npm: 5.3.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  1.2.0.0 AI-141.1980579

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/tonicapp-95d0cd78-484d-4714-9bc2-e4a3454b8aec.tar.gz

iOS Standalone

### Steps to Reproduce

1. Setup Branch following the guide in the docs
2. `Branch.subscribe` in `componentDidMount` of the root component
3. Kill the standalone app completely (close it in iOS)
4. Tap a branch deep link that's been created (e.g. https://my-app.test-app.link/123456)

### Expected Behavior

The app should start and `branch.subscribe` should be called correctly with the `params` from the link tapped.

### Actual Behavior

`branch.subscribe` is never called on app start.

### Reproducible Demo

Unfortunately, Branch is only supported in standalone apps and we can't get a reproducible demo.

### More Information

I've debugged this issue as far as I can without getting into the native code.  Basically `RNBranch.redeemInitSessionResult` is called on first `subscribe` but it returns `null`.  This suggests there is a bug in the initialization code of Branch.  Expo appears to customise this considerably, so it may be a bug on the Expo side, or it may be a bug on the Branch iOS or Branch react-native side.

Either way, it renders the feature basically useless.

**Comment by AdamPD** [comment]
Just a follow up.  It looks like this is worse than originally anticipated.  It appears the library still thinks it's initialising and therefore no events are pushed through to Branch.  They get queued and not delivered until the app fully restarts.

**Comment by AdamJNavarro** [comment]
Thanks for the report, @AdamPD. I brought this to the attention of the dev who works closely with our Branch API.

Cheers,

Adam

**Comment by AdamPD** [comment]
I detached from Expo to try to debug this, but it works in a detached app.  Frustrating!

**Comment by miljantekic** [comment]
@AdamJNavarro Not sure how much of a similar issue it is but we have also had issues with Android standalone apps and Branch links opening the app.

If the Branch link is clicked when the application is closed only the initial link gets registered and called and all further links clicks are not registered by the `subscribe` function. But if the application wasn't opened by a Branch link then the subscribe function works normally and gets called every time.

Strangely this happens only on Android, on iOS everything works as expected.

I was able to create a reproducible test app using CRNA. When built via Expo it will only register the initial link with which the app was opened but all other link clicks will not call the subscribe function.
Here is the repo:
https://github.com/CelsiusNetwork/branch-test

**Comment by superyarik** [comment]
also face this problem.

**Comment by AdamPD** [comment]
We really need a way to create an Xcode runnable version of the standalone app.  There are clearly some differences between this and a detached app.  My guess is the fact there is an instance of Branch for every SDK bundled with a standalone app and some of the notifications are hitting the wrong Branch instance.  This, to me, seems to be the only difference between the standalone and a detached app.

Is there any guidance on how to debug standalone apps?

**Comment by AdamPD** [comment]
@miljantekic - I can reproduce your issue too.  Probably should be raised as a separate issue.

Real pity there are so many issues with the Branch integration.

**Comment by AdamPD** [comment]
I've found the bug.  I managed to build the standalone app from source and could only reproduce consistently when building in Release.  The following lines are the issue:

https://github.com/expo/expo/blob/master/ios/Exponent/Kernel/Services/EXBranchManager.m#L108

`nativeModuleForAppManager` returns nil when the app starts up from a Branch link.  It appears the bridge hasn't been initialised yet.  Looking at the call stack, it makes sense that `branchModuleDidInit` is called *during* initialisation and then the callback is called synchronously, thus the module is never fully registered.

To fix it, I simply removed the `nativeModuleForAppManager` call and used the `versionedBranchModule` argument that's passed to `branchModuleDidInit`.  My only apprehension here would be referencing that in the callback, but considering this should all be happening very quickly, I can't see any issue with it.

@janicduplessis - is there any issue with the above fix?  If not, I'd be happy to post a PR for it.

**Comment by AdamPD** [comment]
@terribleben - looks like you were the one who wrote these specific lines.  Thought you might have some thoughts.

**Comment by ide** [comment]
Closing this since the linked PR has been merged. Thanks for diving in and figuring this out @AdamPD .

**Comment by ide** [comment]
As mentioned in https://github.com/expo/expo/pull/2158 the fix was deployed for SDK 30. Make sure you're using the latest SDK version to get the fix.

**Comment by rodriguezmanu** [comment]
I am using expo 31 detached, I can see the fix from @AdamPD on EXBranchManager file, but the issue still there, only works on ios when the app is closed not opened. Any updates? Thanks

**Comment by AdamPD** [comment]
@rodriguezmanu - I'm using SDK 31 (albeit not detached) and the builds are working as expected for iOS.  Not sure if there is something unique about being detached with regards to this issue.

**Comment by sin2** [comment]
Also experiencing the same issue as @rodriguezmanu 
I have a detached expo project using expokit 32.0.7
