### ISSUE TITLE
DocumentPicker promise never resolves on M1 Mac (built for iOS)

### ISSUE THREAD

**Issue by psquizzle** [expo/expo#21064]
### Summary

[DocumentPicker.getDocumentAsync]

Running on m1
- Pick a document, the window closes and nothing happens
- Press the button again and the Yellow box warning (Different document picking in progress. Await other document picking first.
- works on iOS of course

### What platform(s) does this occur on?

iOS

### Environment

@latest 
M1 Mac, MacOS, Ventura 13.1

### Minimal reproducible example

https://snack.expo.dev/@ritam/document-picker

**Comment by jzhangdev** [comment]
I recently encountered a similar issue that can throw this exception if you open a modal type component at the same time.

**Comment by hochdyl** [comment]
Same here, when I try to reopen the DocumentPicker I closed with the BackButton of my phone, I get this error: Possible Unhandled Promise Rejection (id: 0): Error: Call to function 'ExpoDocumentPicker.getDocumentAsync' has been rejected.

I used Sentry to get a little more detail about the error. See the following screen.
![image](https://user-images.githubusercontent.com/55688853/223171079-f17c631d-3b08-4dce-ae0b-edbd216f50af.png)

**Comment by hochdyl** [comment]
Same issue as : https://github.com/expo/expo/issues/21578

It's fixed with the last commit.

**Comment by bberos** [comment]
Same error here, anyone know when this fix will be released?

**Comment by psquizzle** [comment]
Tested with the latest "expo-document-picker": "~11.2.2", the issue still persists.

**Comment by NCS** [comment]
In my app, the issue occurred on Android and now it is solved but I didn't test it with iOS. Thank you for your support.
