### ISSUE TITLE
SDK ~48.0.1 100 lines of "react-navigation failed to find sourcemap" issue

### ISSUE THREAD

**Issue by peterpme** [expo/expo#21276]
### Minimal reproducible example

https://github.com/peterpme/expo-react-navigation-sourcemap-issue

### Summary

By including a Tab Navigator, I am faced with 100 lines of source map errors (excerpt below).

Reproduction Steps:

- `yarn create expo-app --template blank@beta sourcemap-issue
`
- upgrade react-native to 0.71.3 (as instructed by expo error)
- Install react-navigation and its requirements like react-native-screens, react-native-safe-area-context
- install web-required modules
- use react-navigation TabNavigator
  - happens with StackNavigator as well
- run `yarn web`

```
WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/Header.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/peter/Projects/sourcemap-issue/node_modules/@react-navigation/elements/lib/src/Header.tsx' file: Error: ENOENT: no such file or directory, open '/Users/peter/Projects/sourcemap-issue/node_modules/@react-navigation/elements/lib/src/Header.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/HeaderBackButton.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/peter/Projects/sourcemap-issue/node_modules/@react-navigation/elements/lib/src/HeaderBackButton.tsx' file: Error: ENOENT: no such file or directory, open '/Users/peter/Projects/sourcemap-issue/node_modules/@react-navigation/elements/lib/src/HeaderBackButton.tsx'
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.9 - /opt/homebrew/bin/zsh
    Binaries:
      Node: 16.18.0 - ~/Library/Caches/fnm_multishells/88374_1676670625658/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.2 - ~/Library/Caches/fnm_multishells/88374_1676670625658/bin/npm
      Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.1
      expo: ~48.0.1 => 48.0.1
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
      react-native-web: ~0.18.10 => 0.18.12
    Expo Workflow: managed

**Comment by elitenas** [comment]
Getting the same issue

**Comment by frankcalise** [comment]
Also experiencing the same

**Comment by brentvatne** [comment]
cc @EvanBacon @satya164

**Comment by younes0** [comment]
@peterpme after reading [this](https://github.com/expo/expo-cli/issues/1498#issuecomment-1407573019), I used the [metro bundler for web](https://docs.expo.dev/guides/customizing-metro/#adding-web-support-to-metro) and ditched webpack. 
For fast refresh support, I didn't see documentation out there yet, but these are the steps I did and it works flawlessly (and so much faster):
- add package `@expo/metro-runtime` 
- put `import "@expo/metro-runtime";` in your App.tsx (as seen [here](https://github.com/expo/router/blob/f366b1b66e499887d86e3beeb4179de626c3889b/packages/expo-router/src/fork/expo/registerRootComponent.tsx))

**Comment by elitenas** [comment]
One bug to be aware of:

`expo-constants` don't work with metro yet

**Comment by EvanBacon** [comment]
Fast Refresh, LogBox errors, and Expo Constants are all enabled by default in Expo Router (where Metro web is developed).

We should still figure out what's going on with Webpack/React Navigation as Metro web is very early in development.

**Comment by carlosa54** [comment]
I think I found out why we're getting the warnings, the previous `webpack.config.js` was using `stats: 'none'` and now it uses `stats: EXPO_DEBUG ? 'detailed' : 'errors-warnings',`

Before:
https://github.com/expo/expo-cli/blob/7f7242bd93d19aaf1238d856f2f4187675953a98/packages/webpack-config/src/webpack.config.ts#L327-L328

After:
https://github.com/expo/expo-cli/blob/b5161c374039f1c9105f7a9582ab719d9ce7fa1e/packages/webpack-config/src/webpack.config.ts#L267-L268

**Comment by elitenas** [comment]
@EvanBacon i had to switch back to webpack because `Constants.manifest` returns an empty {} in expo 48.

It works fine in webpack so I know my configurations are correct

**Comment by carlosa54** [comment]
fwiw I can confirm that overriding the `stats` hides the warnings. I confirmed that the functionality of my app is not affected so this could be a workaround in the meantime to get rid of the warnings.

- `npx expo customize webpack.config.js`
- Modify file:
```js
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);

  // Disable warnings
  config.stats = 'none'

  // Customize the config before returning it.
  return config;
};

```

**Comment by satya164** [comment]
There seems to be an issue with the path to the source file in our compiled code. I'll take a look.

**Comment by satya164** [comment]
This should be fixed if you upgrade to latest versions of `@react-navigation` packages.

**Comment by elitenas** [comment]
@satya164 this fixed a most of the warnings. I am still getting some warnings for  `@react-navigation/bottom-tabs` and `@react-navigation/stack`

**Comment by satya164** [comment]
@elitenas can you post the warnings?

**Comment by elitenas** [comment]
```
WARNING in ./node_modules/@react-navigation/bottom-tabs/lib/module/navigators/createBottomTabNavigator.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/createBottomTabNavigator.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/createBottomTabNavigator.tsx'

WARNING in ./node_modules/@react-navigation/bottom-tabs/lib/module/utils/BottomTabBarHeightCallbackContext.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/BottomTabBarHeightCallbackContext.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/BottomTabBarHeightCallbackContext.tsx'

WARNING in ./node_modules/@react-navigation/bottom-tabs/lib/module/utils/BottomTabBarHeightContext.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/BottomTabBarHeightContext.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/BottomTabBarHeightContext.tsx'

WARNING in ./node_modules/@react-navigation/bottom-tabs/lib/module/utils/useBottomTabBarHeight.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/useBottomTabBarHeight.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/useBottomTabBarHeight.tsx'

WARNING in ./node_modules/@react-navigation/bottom-tabs/lib/module/utils/useIsKeyboardShown.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/useIsKeyboardShown.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/useIsKeyboardShown.tsx'

WARNING in ./node_modules/@react-navigation/bottom-tabs/lib/module/views/Badge.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/Badge.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/Badge.tsx'

WARNING in ./node_modules/@react-navigation/bottom-tabs/lib/module/views/BottomTabBar.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/BottomTabBar.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/BottomTabBar.tsx'

WARNING in ./node_modules/@react-navigation/bottom-tabs/lib/module/views/BottomTabItem.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/BottomTabItem.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/BottomTabItem.tsx'

WARNING in ./node_modules/@react-navigation/bottom-tabs/lib/module/views/BottomTabView.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/BottomTabView.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/BottomTabView.tsx'

WARNING in ./node_modules/@react-navigation/bottom-tabs/lib/module/views/ScreenFallback.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/ScreenFallback.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/ScreenFallback.tsx'

WARNING in ./node_modules/@react-navigation/bottom-tabs/lib/module/views/TabBarIcon.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/TabBarIcon.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/bottom-tabs/lib/src/TabBarIcon.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/Header.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/Header.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/Header.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/HeaderBackButton.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/HeaderBackButton.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/HeaderBackButton.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/HeaderBackContext.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/HeaderBackContext.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/HeaderBackContext.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/HeaderBackground.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/HeaderBackground.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/HeaderBackground.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/HeaderHeightContext.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/HeaderHeightContext.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/HeaderHeightContext.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/HeaderShownContext.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/HeaderShownContext.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/HeaderShownContext.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/HeaderTitle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/HeaderTitle.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/HeaderTitle.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/getDefaultHeaderHeight.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/getDefaultHeaderHeight.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/getDefaultHeaderHeight.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/getHeaderTitle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/getHeaderTitle.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/getHeaderTitle.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/useHeaderHeight.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/useHeaderHeight.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/elements/lib/src/useHeaderHeight.tsx'

WARNING in ./node_modules/@react-navigation/native-stack/lib/module/navigators/createNativeStackNavigator.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/native-stack/lib/src/createNativeStackNavigator.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/native-stack/lib/src/createNativeStackNavigator.tsx'

WARNING in ./node_modules/@react-navigation/native-stack/lib/module/views/NativeStackView.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/native-stack/lib/src/NativeStackView.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/native-stack/lib/src/NativeStackView.tsx'

WARNING in ./node_modules/@react-navigation/native/lib/module/theming/DarkTheme.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/native/lib/src/DarkTheme.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/native/lib/src/DarkTheme.tsx'

WARNING in ./node_modules/@react-navigation/native/lib/module/theming/DefaultTheme.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/native/lib/src/DefaultTheme.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/native/lib/src/DefaultTheme.tsx'

WARNING in ./node_modules/@react-navigation/native/lib/module/theming/ThemeContext.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/native/lib/src/ThemeContext.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/native/lib/src/ThemeContext.tsx'

WARNING in ./node_modules/@react-navigation/native/lib/module/theming/ThemeProvider.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/native/lib/src/ThemeProvider.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/native/lib/src/ThemeProvider.tsx'

WARNING in ./node_modules/@react-navigation/native/lib/module/theming/useTheme.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/native/lib/src/useTheme.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/native/lib/src/useTheme.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/TransitionConfigs/CardStyleInterpolators.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/CardStyleInterpolators.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/CardStyleInterpolators.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/TransitionConfigs/HeaderStyleInterpolators.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/HeaderStyleInterpolators.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/HeaderStyleInterpolators.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/TransitionConfigs/TransitionPresets.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/TransitionPresets.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/TransitionPresets.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/TransitionConfigs/TransitionSpecs.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/TransitionSpecs.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/TransitionSpecs.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/navigators/createStackNavigator.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/createStackNavigator.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/createStackNavigator.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/utils/CardAnimationContext.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/CardAnimationContext.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/CardAnimationContext.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/utils/GestureHandlerRefContext.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/GestureHandlerRefContext.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/GestureHandlerRefContext.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/utils/ModalPresentationContext.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/ModalPresentationContext.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/ModalPresentationContext.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/utils/conditional.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/conditional.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/conditional.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/utils/debounce.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/debounce.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/debounce.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/utils/findLastIndex.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/findLastIndex.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/findLastIndex.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/utils/getDistanceForDirection.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/getDistanceForDirection.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/getDistanceForDirection.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/utils/getInvertedMultiplier.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/getInvertedMultiplier.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/getInvertedMultiplier.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/utils/memoize.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/memoize.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/memoize.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/utils/useCardAnimation.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/useCardAnimation.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/useCardAnimation.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/utils/useGestureHandlerRef.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/useGestureHandlerRef.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/useGestureHandlerRef.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/utils/useKeyboardManager.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/useKeyboardManager.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/useKeyboardManager.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/views/GestureHandler.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/GestureHandler.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/GestureHandler.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/views/Header/Header.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/Header.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/Header.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/views/Header/HeaderContainer.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/HeaderContainer.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/HeaderContainer.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/views/Header/HeaderSegment.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/HeaderSegment.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/HeaderSegment.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/views/ModalStatusBarManager.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/ModalStatusBarManager.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/ModalStatusBarManager.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/views/Screens.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/Screens.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/src/Screens.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/views/Stack/Card.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/Card.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/Card.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/views/Stack/CardContainer.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/CardContainer.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/CardContainer.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/views/Stack/CardSheet.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/CardSheet.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/CardSheet.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/views/Stack/CardStack.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/CardStack.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/CardStack.tsx'

WARNING in ./node_modules/@react-navigation/stack/lib/module/views/Stack/StackView.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/StackView.tsx' file: Error: ENOENT: no such file or directory, open '/Users/Anas/Downloads/myapp/node_modules/@react-navigation/stack/lib/module/src/StackView.tsx'
```

**Comment by satya164** [comment]
@elitenas what are the versions numbers of your `@react-navigation` packages?

**Comment by elitenas** [comment]
These are the versions I have:

```
"@react-navigation/bottom-tabs": "^6.5.7",
  "@react-navigation/native": "^6.1.6",
  "@react-navigation/native-stack": "^6.9.11",
  "@react-navigation/stack": "^6.3.16"
```

**Comment by elitenas** [comment]
Ignore that.. i was looking at older logs on my console. This is fixed

**Comment by frankcalise** [comment]
This fixed my react-navigation warnings, however I still receive this one:

```
WARNING in ./node_modules/expo-asset/build/ReactNativeCompatibleAssetsRegistry.js:7:13
Module not found: Can't resolve '@react-native/assets-registry/registry'
   5 | let registry: any | null = null;
   6 | try {
>  7 |   registry = require('@react-native/assets-registry/registry');
     |             ^
   8 | } catch {}
   9 | if (!registry) {
  10 |   try {
```

**Comment by elitenas** [comment]
@frankcalise i do get the same log as well

**Comment by djaffer** [comment]
I am also getting this error.

**Comment by kreshnikalidema** [comment]
@satya164 the same problem is also with `react-native-paper`.

**Comment by satya164** [comment]
> @satya164 the same problem is also with `react-native-paper`.

Please open an issue in Paper repo
