### ISSUE TITLE
New SDK 30 ExpoKit projects fail on `pod install`

### ISSUE THREAD

**Issue by esamelson** [expo/expo#2200]
New SDK 30 ExpoKit projects currently encounter this error when trying to `pod install`:

```
[!] No podspec found for `EXImageLoaderInterface` in `../node_modules/expo-image-loader-interface/ios
```

This is because no modules have a declared dependency on `expo-image-loader-interface`, even though three of them (`expo-barcode-scanner`, `expo-camera`, and `expo-react-native-interface`) depend on its native functionality.

While we work on a fix, quick workaround for anyone encountering this issue is to just add `expo-image-loader-interface@1.0.0` as a dependency in your package.json.

**Comment by lwinkyawmyat** [comment]
`pod install` worked after `expo-image-loader-interface` added in `package.json`.
But `build failed` in `ejected` project with follow error message:

```
clang: error: no such file or directory: '/Users/XXX/XXX/node_modules/expo-image-loader-interface/ios/EXImageLoaderInterface/EXImageLoaderInterface.m'
clang: error: no input files
```

**Comment by SimoneLSK** [comment]
other than add `expo-image-loader-interface@1.0.0 `

Guess we need to add other two dependencies and add follow line in pod 

```
   pod 'EXImageLoaderInterface', 
  :path => "../node_modules/expo-image-loader-interface/ios",
  :inhibit_warnings => true

  pod 'EXBarCodeScannerInterface', 
  :path => "../node_modules/expo-barcode-scanner-interface/ios",
  :inhibit_warnings => true

  pod 'EXFontInterface', 
  :path => "../node_modules/expo-font-interface/ios",
  :inhibit_warnings => true
```

**Comment by tsapeta** [comment]
Hey guys, sorry for the inconvenience, I've just published a patch for `expo-react-native-adapter` to version `1.1.1` that is now including `expo-image-loader-interface` in its dependencies. 
If you get an update, then you need to run `pod update EXReactNativeAdapter --no-repo-update` if you've already tried doing `pod install` with the previous version.

Closing this issue but feel free to continue discussion if it is still happening for you 😉

**Comment by nsipplswezey** [comment]
This issue persisted for me even after updating `expo-react-native-adapter` to 1.1.1.

@SimoneLSK fix was necessary for me to get through a `pod install`

> other than add `expo-image-loader-interface@1.0.0`
> 
> Guess we need to add other two dependencies and add follow line in pod
> 
> ```
>    pod 'EXImageLoaderInterface', 
>   :path => "../node_modules/expo-image-loader-interface/ios",
>   :inhibit_warnings => true
> 
>   pod 'EXBarCodeScannerInterface', 
>   :path => "../node_modules/expo-barcode-scanner-interface/ios",
>   :inhibit_warnings => true
> 
>   pod 'EXFontInterface', 
>   :path => "../node_modules/expo-font-interface/ios",
>   :inhibit_warnings => true
> ```

After pod install, however, building ejected Expo App in XCode throws the following error.

`No visible @interface for 'EXModuleRegistryProvider' declares the selector 'initWithSingletonModuleClasses:'`

**Comment by tsapeta** [comment]
@nsipplswezey what's the version of `expo-cli` you're using (`expo --version`)? Can you show me your Podfile?

**Comment by nsipplswezey** [comment]
```
Macintosh-7:expo-issues nsipplswezey$ expo --version
2.1.2
```

Here are steps to recreate this particular case

```
npm install -g expo-cli
git clone https://github.com/expo/playlist-example
cd playlist-example
npm install
expo eject (select ExpoKit: I'll create or log in with an Expo account to use React Native and the Expo SDK.)
expo start
open playlist-example/ios/playlist.xcworkspace/
cd ios/
pod install
```

Throws error
```
Macintosh-7:playlist-example nsipplswezey$ cd ios/
Macintosh-7:ios nsipplswezey$ pod install
Ignoring executable-hooks-1.4.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.4.2
Ignoring fast-stemmer-1.0.2 because its extensions are not built.  Try: gem pristine fast-stemmer --version 1.0.2
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring gem-wrappers-1.3.2 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.3.2
Ignoring nokogiri-1.6.7.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.7.2
Ignoring posix-spawn-0.3.11 because its extensions are not built.  Try: gem pristine posix-spawn --version 0.3.11
Ignoring redcarpet-3.3.4 because its extensions are not built.  Try: gem pristine redcarpet --version 3.3.4
Ignoring yajl-ruby-1.2.1 because its extensions are not built.  Try: gem pristine yajl-ruby --version 1.2.1
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `EXCamera` from `../node_modules/expo-camera/ios`
Fetching podspec for `EXCameraInterface` from `../node_modules/expo-camera-interface/ios`
Fetching podspec for `EXConstants` from `../node_modules/expo-constants/ios`
Fetching podspec for `EXConstantsInterface` from `../node_modules/expo-constants-interface/ios`
Fetching podspec for `EXCore` from `../node_modules/expo-core/ios`
Fetching podspec for `EXFaceDetectorInterface` from `../node_modules/expo-face-detector-interface/ios`
Fetching podspec for `EXFileSystem` from `../node_modules/expo-file-system/ios`
Fetching podspec for `EXFileSystemInterface` from `../node_modules/expo-file-system-interface/ios`
Fetching podspec for `EXGL` from `../node_modules/expo-gl/ios`
Fetching podspec for `EXGL-CPP` from `../node_modules/expo-gl-cpp/cpp`
Fetching podspec for `EXPermissions` from `../node_modules/expo-permissions/ios`
Fetching podspec for `EXPermissionsInterface` from `../node_modules/expo-permissions-interface/ios`
Fetching podspec for `EXReactNativeAdapter` from `../node_modules/expo-react-native-adapter/ios`
Fetching podspec for `EXSMS` from `../node_modules/expo-sms/ios`
Fetching podspec for `EXSensors` from `../node_modules/expo-sensors/ios`
Fetching podspec for `EXSensorsInterface` from `../node_modules/expo-sensors-interface/ios`
Pre-downloading: `ExpoKit` from `http://github.com/expo/expo.git`, tag `ios/2.7.8`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
[!] Unable to find a specification for `EXImageLoaderInterface` depended upon by `EXCamera`
```


Podfile looks like this
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'playlist' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.7.8",
    :subspecs => [
      "Core"
    ],
    :inhibit_warnings => true
  pod 'EXCamera',
    :path => "../node_modules/expo-camera/ios"
  pod 'EXCameraInterface',
    :path => "../node_modules/expo-camera-interface/ios"
  pod 'EXConstants',
    :path => "../node_modules/expo-constants/ios"
  pod 'EXConstantsInterface',
    :path => "../node_modules/expo-constants-interface/ios"
  pod 'EXCore',
    :path => "../node_modules/expo-core/ios"
  pod 'EXFaceDetectorInterface',
    :path => "../node_modules/expo-face-detector-interface/ios"
  pod 'EXFileSystem',
    :path => "../node_modules/expo-file-system/ios"
  pod 'EXFileSystemInterface',
    :path => "../node_modules/expo-file-system-interface/ios"
  pod 'EXGL',
    :path => "../node_modules/expo-gl/ios"
  pod 'EXGL-CPP',
    :path => "../node_modules/expo-gl-cpp/cpp"
  pod 'EXPermissions',
    :path => "../node_modules/expo-permissions/ios"
  pod 'EXPermissionsInterface',
    :path => "../node_modules/expo-permissions-interface/ios"
  pod 'EXReactNativeAdapter',
    :path => "../node_modules/expo-react-native-adapter/ios"
  pod 'EXSensors',
    :path => "../node_modules/expo-sensors/ios"
  pod 'EXSensorsInterface',
    :path => "../node_modules/expo-sensors-interface/ios"
  pod 'EXSMS',
    :path => "../node_modules/expo-sms/ios"

  pod 'React',
    :path => "../node_modules/react-native",
    :inhibit_warnings => true,
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true


  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|

    if target.pod_name == 'ExpoKit'
      target.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'
        
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end


    if ['Amplitude-iOS','Analytics','AppAuth','Branch','CocoaLumberjack','FBSDKCoreKit','FBSDKLoginKit','FBSDKShareKit','GPUImage','JKBigInteger2'].include? target.pod_name
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
    # Can't specify this in the React podspec because we need
    # to use those podspecs for detached projects which don't reference ExponentCPP.
    if target.pod_name.start_with?('React')
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
      end
    end
    # Build React Native with RCT_DEV enabled
    next unless target.pod_name == 'React'
    target.native_target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
    end

    end
  end
end
```

**Comment by tsapeta** [comment]
@nsipplswezey 
Looks like you're using wrong version of ExpoKit which doesn't support SDK30. `2.7.8` is the last version for SDK29.
In other words, if you want to use SDK30, you need to change `:tag => "ios/2.7.8",` to `:tag => "ios/2.8.2",` in your Podfile 🙂 Also, you don't have pods that were added in SDK30, so I've prepared a gist with an example Podfile for SDK30: https://gist.github.com/tsapeta/82c19c15f6b53f0c9f12e6bcff480fd2

Let me know if you want to use SDK29 instead of 30, then the workaround would be a bit different 😉

**Comment by nsipplswezey** [comment]
@tsapeta 
Thanks! Updated ExpoKit by using the example podfile provided for SDK30.
`pod install` works without issue. Building for iOS runs as well, with a couple warnings. 

I've got a couple potentially useful followups.
1. The expo app I was attempting to eject was https://github.com/expo/playlist-example. I'm wondering if there's a pull request to be made updating the podfile that `expo eject` generates –which didn't work initially– with the changes included in the Podfile for SDK30 that you provided. As it stands now, I believe the `playlist-example` which has been updated to SDK30 fails after ejecting, and updating the Podfile with the on you provided fixed it.
2. It looks like there are a couple warnings in the ejected `playlist-example` app that might be worth looking into. Screenshot attached.
![img_4044](https://user-images.githubusercontent.com/7946707/45842469-ab202f00-bcd1-11e8-900a-d43f420b9aae.PNG)

Looks like I'm unblocked for now. Thanks again!

**Comment by blackberry4311** [comment]
> @nsipplswezey
> Looks like you're using wrong version of ExpoKit which doesn't support SDK30. `2.7.8` is the last version for SDK29.
> In other words, if you want to use SDK30, you need to change `:tag => "ios/2.7.8",` to `:tag => "ios/2.8.2",` in your Podfile 🙂 Also, you don't have pods that were added in SDK30, so I've prepared a gist with an example Podfile for SDK30: https://gist.github.com/tsapeta/82c19c15f6b53f0c9f12e6bcff480fd2
> 
> Let me know if you want to use SDK29 instead of 30, then the workaround would be a bit different 😉

Currently I use sdk29 with which face the issue: No visible @interface for 'EXModuleRegistryProvider' declares the selector 'initWithSingletonModuleClasses:'
my pod file as below:

`source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

EXPO_CPP_HEADER_DIR = 'ExpoKit'

target 'test' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.8.0",
    :subspecs => [
      "Core"
    ],
    :inhibit_warnings => true
  pod 'EXCamera',
    :path => "../node_modules/expo-camera/ios"
  pod 'EXCameraInterface',
    :path => "../node_modules/expo-camera-interface/ios"
  pod 'EXConstants',
    :path => "../node_modules/expo-constants/ios"
  pod 'EXConstantsInterface',
    :path => "../node_modules/expo-constants-interface/ios"
  pod 'EXCore',
    :path => "../node_modules/expo-core/ios"
  pod 'EXFaceDetectorInterface',
    :path => "../node_modules/expo-face-detector-interface/ios"
  pod 'EXFileSystem',
    :path => "../node_modules/expo-file-system/ios"
  pod 'EXFileSystemInterface',
    :path => "../node_modules/expo-file-system-interface/ios"
  pod 'EXGL',
    :path => "../node_modules/expo-gl/ios"
  pod 'EXGL-CPP',
    :path => "../node_modules/expo-gl-cpp/cpp"
  pod 'EXPermissions',
    :path => "../node_modules/expo-permissions/ios"
  pod 'EXPermissionsInterface',
    :path => "../node_modules/expo-permissions-interface/ios"
  pod 'EXReactNativeAdapter',
    :path => "../node_modules/expo-react-native-adapter/ios"
  pod 'EXSensors',
    :path => "../node_modules/expo-sensors/ios"
  pod 'EXSensorsInterface',
    :path => "../node_modules/expo-sensors-interface/ios"
  pod 'EXSMS',
    :path => "../node_modules/expo-sms/ios"

  pod 'React',
    :path => "../node_modules/react-native",
    :inhibit_warnings => true,
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge",
      "RCTPushNotification"
    ]
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true


  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'


  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|

    if target.pod_name == 'ExpoKit'
      target.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'
        
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end


    if ['Amplitude-iOS','Analytics','AppAuth','Branch','CocoaLumberjack','FBSDKCoreKit','FBSDKLoginKit','FBSDKShareKit','GPUImage','JKBigInteger2'].include? target.pod_name
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
    if target.pod_name == "#{EXPO_CPP_HEADER_DIR}"
      target.native_target.build_configurations.each do |config|
        config.build_settings['CLANG_WARN_COMMA'] = false
        config.build_settings['CLANG_WARN_UNGUARDED_AVAILABILITY'] = false
      end
    end
    # Can't specify this in the React podspec because we need
    # to use those podspecs for detached projects which don't reference ExponentCPP.
    if target.pod_name.start_with?('React')
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        config.build_settings['HEADER_SEARCH_PATHS'] << "${PODS_ROOT}/Headers/Public/#{EXPO_CPP_HEADER_DIR}"
      end
    end
    # Build React Native with RCT_DEV enabled
    next unless target.pod_name == 'React'
    target.native_target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
    end

    end
  end
end
`

I updated this expo pod when detached from sdk27, any help ?

**Comment by tsapeta** [comment]
Hey @blackberry4311,
The ExpoKit version you're using is for SDK30. You need to use `:tag => "ios/2.7.8",` which is the most recent version that includes SDK29.

**Comment by blackberry4311** [comment]
Hi @tsapeta ,
sr my mistake, I post wrong version of pod file, I meant my pod file is same as above but the version of expokit is :tag => "ios/2.7.8"(tag of expokit above just my trying to workaroud the issue).
expokit with tag 2.7.8 face the issue as above :(

**Comment by tsapeta** [comment]
Can you also share your `package.json` file? This error above probably means that you have incorrect version of `expo-core` dependency that doesn't play well with ExpoKit v2.7.8

**Comment by blackberry4311** [comment]
here is my package.json file
`{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "^29.0.0",
    "react-native-scripts": "1.13.2",
    "react-test-renderer": "16.3.0-alpha.1",
    "redux-persist": "^5.10.0",
    "validator": "^10.3.0"
  },
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "exp start -c",
    "start:test": "exp start -c --lan",
    "publish:test": "exp publish --release-channel develop",
    "reset": "rm -rf node_modules && npm cache clean --force && npm i",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "azstack-react-native": "^1.2.1",
    "deep-freeze": "^0.0.1",
    "expo": "^29.0.0",
    "expokit": "1.5.0",
    "fetch-ponyfill": "^6.0.2",
    "jsencrypt": "^3.0.0-beta.1",
    "moment": "^2.22.2",
    "native-base": "^2.4.2",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz",
    "react-native-easy-grid": "^0.1.17",
    "react-native-fcm": "16.2.0",
    "react-native-htmlview": "^0.12.1",
    "react-native-modalbox": "^1.4.2",
    "react-native-star-rating": "^1.0.9",
    "react-native-webrtc": "1.63.0",
    "react-navigation": "^2.9.3",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-actions": "^2.3.0",
    "redux-form": "^7.3.0",
    "redux-logger": "^3.0.6",
    "redux-saga": "^0.16.0",
    "socket.io-client": "^2.1.1",
    "uuid": "^3.3.2"
  }
}
`

**Comment by tsapeta** [comment]
hmm it looks fine 🤔 can you check version of `expo-core` that got installed in your project? `npm ls --depth=1 expo-core`

**Comment by blackberry4311** [comment]
I use yarn for package manager
here is my yarn output:

> yarn list --depth=1 expo-core
yarn list v1.10.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ expo-core@1.1.0
└─ expo@29.0.1
   └─ expo-core@1.0.1

**Comment by tsapeta** [comment]
So `expo-core` in `node_modules/expo-core` is in v1.1.0 which is not compatible with ExpoKit v2.7.8.
Can you try `yarn add expo-core@1.0.1`?

**Comment by blackberry4311** [comment]
thanks @tsapeta ,it work like a charm. Will buy u a cup of coffee if can^^

**Comment by blackberry4311** [comment]
No, I sure buy u a cup of coffee, u save my day, just tell me the method 💃

**Comment by tsapeta** [comment]
Haha, thanks 😄 I'm glad it works 😉
But if you really want to buy me a coffee, we can meet at [App.js conf](https://appjs.co) 🤩

**Comment by gianpaj** [comment]
Is there a tutorial or documentation page on how to add Expo kit/core or, whatever is the right name is, to a plain react native app (`react-native init`) now, in late 2019?

I'm just trying to add a camera component.

I've started with iOS, but every time I run `pod install` it says one package is dependent on another, and another, and another.
I don't see the point of having all these separate Cocoapod packages if they're are coupled together, unless I'm missing something obvious.

**Comment by bscaspar** [comment]
I ran into this issue after updating from sdk27 to 28. Turns out my expo-core was v1.1.0 as well, and changing it back to 1.0.1 resolved the issue. Not sure how it was updated to 1.1.0 in the first place.
