### ISSUE TITLE
[expo-image-picker] Inverted dimensions when selecting vertical images without editting on Android

### ISSUE THREAD

**Issue by JacobJaffe** [expo/expo#22097]
### Minimal reproducible example

https://github.com/JacobJaffe/expo-image-picker-android-dimension-bug-reproduction

### Summary

When an image is selected via `ImagePicker.launchImageLibraryAsync`, on Android, the `height` and `width` are inverted for images that are supposed to be vertical. **This only occurs without editing (`allowsEditing: false`)** 

For example, if I select an image that's supposed to be 2000px tall, by 1000px wide, it'll return `{ height: 1000, width: 2000 }`.

Notably, the rotation of the image is *not* wrong -- it just has the wrong dimensions, resulting in a really bad crop.

I'm facing this issue on `expo: 48` and `expo-image-picker: 14.1.1`.
I did NOT have this issue when on Expo 47 / expo-image-picker 13.3.1. 

This bug also occurs with `allowsMultipleSelection`, and in those cases, since `allowsEditting` isn't supported, **This bug is unavoidable for mulit-selection**

I've included a minimum reproduction of this as a repo, since snack doesn't have expo 48 support. The reproduction steps are simple selecting a vertical image, and seeing that it is displayed with the wrong dimensions. This issue is occurring across multiple physical devices I've tested this on. 

I really hope I'm just missing something about correct usage of `ImagePicker` in the latest major change... and not that it just doesn't work on Android for half of photos now.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
      Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.10 => 48.0.10
      react: 18.2.0 => 18.2.0
      react-native: 0.71.6 => 0.71.6
    npmGlobalPackages:
      eas-cli: 3.6.1
    Expo Workflow: manage

**Comment by hamzawii** [comment]
Same problem for me, Is there any updates for this bug ?

**Comment by behenate** [comment]
@hamzawii This should already be fixed for quite a while. Which version of image-picker are you using?

**Comment by gaearon** [comment]
This is still a problem with EXIF tags 5 and 7 (easy to verify with https://github.com/recurser/exif-orientation-examples/). I'm chatting to @lukmccall and he's working on a fix — but wanted to mention for people finding this via search.

**Comment by ffMathy** [comment]
Interesting @gaearon, any way to track the progress? Is there an issue open or a way to be notified when it's fixed?

**Comment by hamzawii** [comment]
I recently updated to Expo 52 and expo-image-picker 16.0.3. I'm still encountering an issue where selected videos on Android have inverted width and height. This works correctly on iOS. Any idea ?

**Comment by gaearon** [comment]
I’ve only looked at images. I’m not sure which codepaths affect video and whether there’s a problem there too.
