### ISSUE TITLE
BarCodeScanner does not trigger `onBarCodeScanned`

### ISSUE THREAD

**Issue by ZebGirouard** [expo/expo#2239]
### Environment

^^FYI this should say `expo diagnostics` now, this can be really confusing for people filing their first GH issue in this repo.

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.9.0
  Yarn: Not Found
  npm: 6.2.0
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.1
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.0 => 0.55.4

**Target**:
- iOS
- iPhone 5C and iPhoneX
- Link sent by pressing `s` in `npm start` for CRNA
- Link opens in Expo iOS app

### Steps to Reproduce

(Write your steps here:)

1. Send Expo link to iPhone (have reproduced on iPhone X and 5C)
2. Open link, navigate to a page with component with `BarCodeScanner` inside it
3. Try to scan several different bar code formats, including QR code

### Expected Behavior

`BarCodeScanner` appears and getting a QR code in frame triggers `onBarCodeScanned`.

### Actual Behavior

`BarCodeScanner` appears but getting a QR code in frame does **not** trigger `onBarCodeScanned`.

### Reproducible Demo

https://snack.expo.io/SJDdXKzY7

I mean...that's really just the docs for the BarCodeScanner component, but it can't be reproduced without a real phone.  Let me know if there's anything else I can provide.

**Comment by Aasfga** [comment]
Hi @ZebGirouard. BarCodeScanner has changed since SDK 28. We extracted it to unimodule and rewritten. Try to use latest SDK, this bug is fixed there

**Comment by ZebGirouard** [comment]
@Aasfga , could I get a little more information on this?  I tried updating to `"expo": "^28.0.0",` in my `package.json` but still could not scan a QR code.  Then I tried updating to `"expo": "^29.0.0",` and I see this error:

`The Expo SDK requires Expo to run. It appears...`

Do I also need to change the way `BarCodeScanner` is imported now?  I'm not exactly sure what "unimodule" means in the context of `npm`--does that mean I need to install a `BarCodeScanner` package now, too?

I wish I could give you more information, but unfortunately the function just doesn't fire so I'm left to wonder if I'm scanning wrong, have wrong packages, am calling it wrong, or if there really is a bug.

**Comment by ZebGirouard** [comment]
Confirmed that upgrading to `"expo": "^30.0.0",` also shows the `Expo SDK requires Expo...` error.  Rolling back to v28, no error, but still does not scan QR Code.  Tried several code samples with different sizes and angles and nothing's happening :(

**Comment by esamelson** [comment]
@ZebGirouard please follow the instructions at the bottom of this post to fully upgrade to SDK 30. https://blog.expo.io/expo-sdk-30-0-0-is-now-available-e64d8b1db2a7

**Comment by ZebGirouard** [comment]
Thank you @esamelson , that worked perfectly.  `onBarCodeScanned` fired after following all update steps!
