### ISSUE TITLE
AV Recording IOS durationMillis bug

### ISSUE THREAD

**Issue by ameenfarook8** [expo/expo#22972]
### Minimal reproducible example

https://snack.expo.dev/@ameenfarook8/expo-av-bug

### Summary

In this snack, we can see 2 buttons, mount and unmount, if we click mount, it mounts recorder component and starts recording, and we can pause or stop or unmount. the issue here is with ios. follow these steps to produce the error.

1. click mount
2. after recording started we can see milliseconds running
3. click pause
4. the unmount and notice the milliseconds
5. now again mount then milliseconds restart from previous state.

this is not the case with android. in android it works fine.

### Environment

just run the snack, and run in ios device or simulator

**Comment by mojavad** [comment]
It's in another issue as well. Definitely a bug. 

Put up a PR to fix: https://github.com/expo/expo/pull/23816

**Comment by tsapeta** [comment]
Probably it's been fixed in https://github.com/expo/expo/pull/23816
I'll release a new version of expo-av for SDK 49 in a few days

**Comment by rohankm** [comment]
im still facing the same issue im on     "expo-av": "~13.4.1",
