### ISSUE TITLE
[SDK 49 beta] [Android] expo-blur causes decreased performance and looks weird 

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#23239]
### Minimal reproducible example

https://github.com/RRaideRR/expo-blur-sdk-49

### Summary

I noticed in my Android app some performance degradation when I tried out the new SDK 49. I tracked it down to expo-blur view. As hyped as I am for the new blurred view on the Android side, I cannot use it in my app because it causes the application to become significantly slower on low end and medium Android devices.  Plus: you will see that if I'm navigating away from a view, the blur view changes its colours in a strange way.

In my repro, I added also a 49SDK build APK and a 48SDK build APK so you can try it out faster by yourself :-). 

PS - on a side node: I noticed that the build size between these two builds differs (48 SDK build: 24.98 MB ; 49 SDK build: 28.22 MB --> so its gotten nearly 13% worse 😢)

SDK 49 build:
https://github.com/expo/expo/assets/3411292/31cab6ff-00f3-42a5-99aa-99b906f6b15c

SDK 48 build:
https://github.com/expo/expo/assets/3411292/ffaa8c1b-31c2-4c7f-bb19-56b528579e60

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.0-beta.1 => 49.0.0-beta.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.0 => 0.72.0 
    npmGlobalPackages:
      eas-cli: 3.14.0
      expo-cli: 6.3.9
    Expo Workflow: managed

**Comment by behenate** [comment]
Sorry but most likely we won't be able to resolve this issue quickly. The issue is caused by `react-native-screens` enabling hardware acceleration on the layer containing the blur views.
The Blur library we are using for the blurring effect uses a non-hardware accelerated canvas for view snapshotting https://github.com/Dimezis/BlurView/issues/185#issuecomment-1271611622 and it's stops working correctly after `react-native-screens` enables hardware acceleration. You can try disabling the transition animation when navigating between screens although it might not fix the issue completely. 

If you *_Really_* need the flickering to disappear and you are running on a bare workflow you can edit the [`Screens.kt`](https://github.com/software-mansion/react-native-screens/blob/4e7048577ad7fd59c4dba75a8d28d07ed12ff5a2/android/src/main/java/com/swmansion/rnscreens/Screen.kt#L104) file from `react-native-screens`  and replace `LAYER_TYPE_HARDWARE` with `LAYER_TYPE_NONE`. I don't recommend this approach for anything other than testing as it will most likely have unwanted side effects and reduce performance of the transitions between other screens.

When it comes to performance we are currently being limited by the library we are using and native Android support for blurring. The blur calculation is pretty expensive. In general on Android you should limit the number of blur views to a minimum (example you provided will never work smoothly on Android).

**Comment by RRaideRR** [comment]
Hey @behenate,

thanks a lot for your thoughtful response - appreciate it a lot mate. 

I see the point that enabling the blur effect on Android comes with costs. It took me a couple of hours to investigate why my app is running so bad on SDK49. So maybe we can (1) either adjust the expo-blur documentation or (2) putting a note in the release document of SDK49 to tell the users that enabling blur on Android is pretty expensive. What do you think?

**Comment by crstnmac** [comment]
I get this 
` ERROR  Invariant Violation: requireNativeComponent: "ViewManagerAdapter_ExpoBlurView" was not found in the UIManager.`
in Android when I use BlurView

**Comment by behenate** [comment]
@crstnmac  Thanks for spotting the issue! It's fixed in here https://github.com/expo/expo/pull/23369 the change should be published in around a week

**Comment by scottsoif** [comment]
@behenate 

I am running 12.6.0 and still get the ERROR: Invariant Violation: requireNativeComponent: "ViewManagerAdapter_ExpoBlurView" was not found in the UIManager.

When will this patch be released?

**Comment by axtgr** [comment]
> @behenate, thanks for working on this issue
> 
> I am running 12.6.0 and still get the ERROR: Invariant Violation: requireNativeComponent: "ViewManagerAdapter_ExpoBlurView" was not found in the UIManager.
> 
> When will this patch be released?

If you are still experiencing this error, try updating expo, then updating Expo Go or rebuilding the dev client if you use it.

**Comment by behenate** [comment]
@jkadamczyk Hi, after we found out that the issues would be really hard to fix that's exactly what we did 😉 
https://github.com/expo/expo/pull/24709
The changes are available in `expo-blur@next` 
https://www.npmjs.com/package/expo-blur?activeTab=versions

**Comment by jkadamczyk** [comment]
@behenate Music to my ears!
No worries!
I'm not 100% sure whether my code is correct, but if anyone finds this issue and wants a quick wrapper that brings the old behavior, help yourself with the below typescript snippet

```typescript
import type { BlurViewProps } from "expo-blur";
import { BlurView } from "expo-blur";
import getBackgroundColor from "expo-blur/build/getBackgroundColor";
import * as React from "react";
import { Platform, View } from "react-native";

class LegacyAndroidBlurView extends React.Component<BlurViewProps> {
  render() {
    const { tint = "default", intensity = 50, style, ...props } = this.props;
    const backgroundColor = getBackgroundColor(intensity, tint);
    return <View {...props} style={[style, { backgroundColor }]} />;
  }
}

export const PBlurView: React.FC<BlurViewProps> | typeof LegacyAndroidBlurView =
  Platform.OS === "ios" ? BlurView : LegacyAndroidBlurView;
```

**Comment by hugobayoud** [comment]
I've got this exact same error on Expo SDK 50, I simply run `npx expo prebuild` and relaunch my app on `ios` simulator `npx expo run:ios`

**Comment by elisabeth0bangoura** [comment]
I'm getting this error now on Expo SDK51
