### ISSUE TITLE
[SDK 49 beta] Path aliases don't work in EAS Build

### ISSUE THREAD

**Issue by bndkt** [expo/expo#23265]
### Minimal reproducible example

https://github.com/bndkt/expo-mre

### Summary

I enabled path aliases in an Expo SDK 49 beta project via

```
{
  "expo": {
    "experiments": {
      "tsconfigPaths": true
    }
  }
}
```

in app.json and

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    }
}
}
```

in tsconfig.json.

Building a development build via EAS Build works and when running the dev server locally and opening via the dev client, everything works as well. But when building a production build, I get the following error:

```
Metro encountered an error:
Unable to resolve module @/components/HelloWorld from /private/var/folders/3d/k28gwz5n7tlfzq3pbdtnm0z40000gn/T/eas-build-local-nodejs/f3465575-aec9-4a4b-bbff-edf3aa48e4ca/build/app/index.tsx: @/components/HelloWorld could not be found within the project or in these directories:
  node_modules
  2 | import { StyleSheet, Text, View } from "react-native";
  3 |
> 4 | import { HelloWorld } from "@/components/HelloWorld";
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.3.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.7 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.0-beta.4 => 49.0.0-beta.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.0 => 0.72.0 
      react-native-web: ~0.19.6 => 0.19.6 
    Expo Workflow: managed

**Comment by bndkt** [comment]
Potentially addressed by https://github.com/expo/expo/pull/23276, FYI @EvanBacon

**Comment by bndkt** [comment]
This was resolved with beta 5 🎉 FYI @Kudo @EvanBacon

**Comment by corasan** [comment]
I am still having this issue using expo SDK 49.0.4, it works locally but eas build complains.


![image](https://github.com/expo/expo/assets/5108929/77e3d2bf-1e43-42d5-be5a-7a1ff68b777e)

**Comment by switz** [comment]
Seeing this on 49.0.6:

```
+ /Users/expo/.nvm/versions/node/v16.18.1/bin/node /Users/expo/workingdir/build/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/expo/Library/Developer/Xcode/DerivedData/Relisten-emnzyaajjixqozcqtivndfrlkxzm/Build/Intermediates.noindex/ArchiveIntermediates/Relisten/BuildProductsPath/Release-iphoneos/main.jsbundle --assets-dest /Users/expo/Library/Developer/Xcode/DerivedData/Relisten-emnzyaajjixqozcqtivndfrlkxzm/Build/Intermediates.noindex/ArchiveIntermediates/Relisten/BuildProductsPath/Release-iphoneos/Relisten.app --minify false
warn From React Native 0.72, your metro.config.js file should extend'@react-native/metro-config'. Please see the React Native 0.72 changelog, or copy the template at:
https://github.com/facebook/react-native/blob/main/packages/react-native/template/metro.config.js
warn Falling back to internal defaults.
warning: the transform cache was reset.
                Welcome to Metro v0.76.7
              Fast - Scalable - Integrated


error Unable to resolve module @/relisten/components/PlaybackBar from /Users/expo/workingdir/build/app/(tabs)/(relisten)/index.tsx: @/relisten/components/PlaybackBar could not be found within the project or in these directories:
  node_modules
[0m [90m 1 |[39m [36mimport[39m { [33mSafeAreaView[39m } [36mfrom[39m [32m'react-native-safe-area-context'[39m[33m;[39m[0m
[0m [90m 2 |[39m[0m
[0m[31m[1m>[22m[39m[90m 3 |[39m [36mimport[39m { usePlaybackState } [36mfrom[39m [32m'@/relisten/components/PlaybackBar'[39m[33m;[39m[0m
[0m [90m   |[39m                                   [31m[1m^[22m[39m[0m
[0m [90m 4 |[39m [36mimport[39m { [33mRelistenText[39m } [36mfrom[39m [32m'@/relisten/components/relisten_text'[39m[33m;[39m[0m
[0m [90m 5 |[39m[0m
[0m [90m 6 |[39m [36mexport[39m [36mdefault[39m [36mfunction[39m [33mPage[39m() {[0m.
Error: Unable to resolve module @/relisten/components/PlaybackBar from /Users/expo/workingdir/build/app/(tabs)/(relisten)/index.tsx: @/relisten/components/PlaybackBar could not be found within the project or in these directories:
  node_modules
[0m [90m 1 |[39m [36mimport[39m { [33mSafeAreaView[39m } [36mfrom[39m [32m'react-native-safe-area-context'[39m[33m;[39m[0m
[0m [90m 2 |[39m[0m
[0m[31m[1m>[22m[39m[90m 3 |[39m [36mimport[39m { usePlaybackState } [36mfrom[39m [32m'@/relisten/components/PlaybackBar'[39m[33m;[39m[0m
[0m [90m   |[39m                                   [31m[1m^[22m[39m[0m
[0m [90m 4 |[39m [36mimport[39m { [33mRelistenText[39m } [36mfrom[39m [32m'@/relisten/components/relisten_text'[39m[33m;[39m[0m
[0m [90m 5 |[39m[0m
[0m [90m 6 |[39m [36mexport[39m [36mdefault[39m [36mfunction[39m [33mPage[39m() {[0m
    at ModuleResolver.resolveDependency (/Users/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)
    at DependencyGraph.resolveDependency (/Users/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve (/Users/expo/workingdir/build/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/expo/workingdir/build/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/expo/workingdir/build/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at async Graph._addDependency (/Users/expo/workingdir/build/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 1)
    at async Graph._processModule (/Users/expo/workingdir/build/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
```

**Comment by avanrish** [comment]
In 49.0.6 I still have this issue with path aliases (I use the same configuration as OP). I looked into bare-workflow-setup guide, but I don't have access to the files mentioned there as I rely on expo and eas to run `prebuild` script.
```
[stderr] Error: Unable to resolve module @/hooks/useProtectedScreen from /home/expo/workingdir/build/app/index.tsx: @/hooks/useProtectedScreen could not be found within the project or in these directories:
[stderr] node_modules
```

**Comment by brendobrendo** [comment]
@switz Did you ever get this resolved? I'm experiencing this issue too.

**Comment by Drish-xD** [comment]
Having the same issue!!!
did anyone got the solution??

**Comment by LucasBourgeois** [comment]
any news ?

**Comment by steve-rodri** [comment]
Still having issue in ~49.0.16

**Comment by LucasBourgeois** [comment]
Im on a track : 

But why the heck nothing is written in documentation except : "use tsconfigPaths: true and it will works :)"
Nothing about EAS, nothing about adding configuration in babel, nothing about metro.config.js using expo/metro-config getDefaultConfig() not handling path aliases...

It seems that we still need to use module resolver in babel.config.js:
https://github.com/tleunen/babel-plugin-module-resolver

```
[
    'module-resolver',
    {
	    alias: {
		    '@': './',
		    '@assets': './src/assets',
		    '@classes': './src/classes',
		    '@components': './src/components',
		    '@contexts': './src/contexts',
		    '@core': './src/core',
		    '@features': './src/features',
		    '@hooks': './src/hooks',
		    '@services': './src/services',
		    '@stacks': './src/stacks',
		    '@style': './src/style',
		    '@utils': './src/utils'
	    }
    }
]
```

Im still facing some issue in EAS:
Path seems to be correct but fr_FR.js files doesnt seems to be found..

```
Error: Unable to resolve module ../assets/translations/fr_FR from /home/expo/workingdir/build/src/core/i18n.ts: 

None of these files exist:

  * src/assets/translations/fr_FR(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.svg|.native.svg|.svg|.android.mjs|.native.mjs|.mjs)

  * src/assets/translations/fr_FR/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.svg|.native.svg|.svg|.android.mjs|.native.mjs|.mjs)

> 1 | import i18next from 'i18next';
```

Ill let you know if i finally find a solution.

**Comment by LucasBourgeois** [comment]
https://docs.expo.dev/build-reference/troubleshooting/#build-errors:

Is .gitignore should prevent eas to be able to find files ??????

I was reading this and check this out: 
![image](https://github.com/expo/expo/assets/18696528/2f1931bb-883b-46de-b847-fd3f929fd3eb)

**Comment by LucasBourgeois** [comment]
Ok I finally managed to use path aliases with eas, after many attempts and tests, here is what you must check: 

---
The crazy thing !! 
---
**If any directory or a file is added in .gitignore, EAS will not find it !!**
My trad files come from a server so they're indeed gitignored and my webpack bundle is indeed also gitignored.
You can use in package.json a script `postinstall` that will trigger and produce whatever you want.

Also, EAS use a cache for idk what, but the `--clear-cache` flag seems to improve things and allowed me to finally have working build pipeline.

---

In metro.config.js
Check that you require/import `expo/metro-config`
`const { getDefaultConfig } = require('expo/metro-config');`
If you use webpack or a any bundler that is output a `.mjs`, you need to add `'mjs'` in `config.resolver.sourceExts`

---

In babel.config.js, no module-resolver plugin is needed

---

In babel.config.js, no module-resolver plugin is needed

---

In tsconfig.json, you can define your aliases and base url as you like.


I hope that it will help smh some ppl ! 
What a shame that this thing of ignored files isnt written in documentation.
With a stepback, it seems logical as the build is runned by a mounted machine, but anyone would assume that the sourcecode used by eas is the project that you have locally and not git related...

@steve-rodri (for the notification 👍)
