### ISSUE TITLE
Error: Cannot find native module 'ExpoImage'

### ISSUE THREAD

**Issue by MoreeZ** [expo/expo#23304]
### Minimal reproducible example

Created expo app using `npx create-expo-app my-app`  https://docs.expo.dev/tutorial/create-your-first-app/  Installed expo-image into my React Native Expo application. 

### Summary

When I try to use expo-image I keep getting the same error. `Error: Cannot find native module 'ExpoImage'`

Here are screenshots of the errors:

![WhatsApp Image 2023-07-05 at 13 17 19 (2)](https://github.com/expo/expo/assets/47431553/7a2a6e4c-6df8-47f4-be38-412eba7b24e2)
![WhatsApp Image 2023-07-05 at 13 17 19 (1)](https://github.com/expo/expo/assets/47431553/3ca1cec7-d2eb-46e1-abb7-23281898c3be)
![WhatsApp Image 2023-07-05 at 13 17 19](https://github.com/expo/expo/assets/47431553/04465dbc-c12a-4051-876b-e4e8ea0939c9)

__I have tried to remove node-modules, android, .expo folders as well as yarn.lock file.__ Reinstalled everything and still not working. In the process of trying to fix the issue I updated most the packages I have used.

Here are some other dependencies that might be relevant.

Dependencies:

```json
    "@expo/webpack-config": "18.0.4",
    "@fortawesome/react-native-fontawesome": "^0.3.0",
    "@react-native-async-storage/async-storage": "1.19.0",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "expo": "~48.0.18",
    "expo-dev-client": "~2.2.1",
    "expo-file-system": "~15.2.2",
    "expo-font": "~11.1.1",
    "expo-image": "^1.3.1",
    "react": "18.2.0",
    "react-device-detect": "^2.2.3",
    "react-dom": "~18.2.0",
    "react-native": "0.71.8",
    "react-native-asset": "^2.1.0",
    "react-native-safe-area-context": "~4.5.0",
    "react-native-screens": "~3.22.0",
    "react-native-size-matters": "^0.4.0",
    "react-native-svg": "~13.4.0",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-web": "~0.18.9",
    "yarn": "^1.22.19"
```

The `app.json` file:
```json
{
  "expo": {
    "name": "#####",
    "slug": "#####",
    "version": "1.0.0",
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./src/assets/#####.png",
        "backgroundColor": "#ef7a38"
      },
      "package": "#####"
    },
    "extra": {
      "eas": {
        "projectId": "#####"
      }
    }
  }
}
```

The react code: 
```js
import { Image } from "expo-image";
export default function GridMenu({myImage}) {
  return <Image
      source={myImage}
      style={styles.thumbnailImage}
      contentFit="contain"
    />
}
```

The react code is irrelevant as the app breaks regardless of there I import the image.

### Environment

expo-env-info 1.0.5 environment info:
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\Desktop\LDL\mao-app\node_modules\.bin\yarn.CMD   
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: AI-221.6008.13.2211.9514443
  npmPackages:
    @expo/webpack-config: 18.0.4 => 18.0.4
    expo: ~48.0.18 => 48.0.19
    react: 18.2.0 => 18.2.0
    react-dom: ~18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-web: ~0.18.9 => 0.18.12
  Expo Workflow: bare

**Comment by brentvatne** [comment]
> Expo Workflow: bare

you likely need to recompile the native app

if the issues persists for you, try starting from scratch and reproducing it in a minimal example and share it in a new issue. thanks!

**Comment by brayanobisto** [comment]
> ### Minimal reproducible example
> Created expo app using `npx create-expo-app my-app` [docs.expo.dev/tutorial/create-your-first-app](https://docs.expo.dev/tutorial/create-your-first-app/) Installed expo-image into my React Native Expo application.
> 
> ### Summary
> When I try to use expo-image I keep getting the same error. `Error: Cannot find native module 'ExpoImage'`
> 
> Here are screenshots of the errors:
> 
> ![WhatsApp Image 2023-07-05 at 13 17 19 (2)](https://user-images.githubusercontent.com/47431553/251147252-7a2a6e4c-6df8-47f4-be38-412eba7b24e2.jpeg) ![WhatsApp Image 2023-07-05 at 13 17 19 (1)](https://user-images.githubusercontent.com/47431553/251147258-3ca1cec7-d2eb-46e1-abb7-23281898c3be.jpeg) ![WhatsApp Image 2023-07-05 at 13 17 19](https://user-images.githubusercontent.com/47431553/251147260-04465dbc-c12a-4051-876b-e4e8ea0939c9.jpeg)
> 
> **I have tried to remove node-modules, android, .expo folders as well as yarn.lock file.** Reinstalled everything and still not working. In the process of trying to fix the issue I updated most the packages I have used.
> 
> Here are some other dependencies that might be relevant.
> 
> Dependencies:
> 
> ```json
>     "@expo/webpack-config": "18.0.4",
>     "@fortawesome/react-native-fontawesome": "^0.3.0",
>     "@react-native-async-storage/async-storage": "1.19.0",
>     "@react-navigation/native": "^6.1.6",
>     "@react-navigation/native-stack": "^6.9.12",
>     "expo": "~48.0.18",
>     "expo-dev-client": "~2.2.1",
>     "expo-file-system": "~15.2.2",
>     "expo-font": "~11.1.1",
>     "expo-image": "^1.3.1",
>     "react": "18.2.0",
>     "react-device-detect": "^2.2.3",
>     "react-dom": "~18.2.0",
>     "react-native": "0.71.8",
>     "react-native-asset": "^2.1.0",
>     "react-native-safe-area-context": "~4.5.0",
>     "react-native-screens": "~3.22.0",
>     "react-native-size-matters": "^0.4.0",
>     "react-native-svg": "~13.4.0",
>     "react-native-url-polyfill": "^1.3.0",
>     "react-native-web": "~0.18.9",
>     "yarn": "^1.22.19"
> ```
> 
> The `app.json` file:
> 
> ```json
> {
>   "expo": {
>     "name": "#####",
>     "slug": "#####",
>     "version": "1.0.0",
>     "updates": {
>       "fallbackToCacheTimeout": 0
>     },
>     "assetBundlePatterns": [
>       "**/*"
>     ],
>     "ios": {
>       "supportsTablet": true
>     },
>     "android": {
>       "adaptiveIcon": {
>         "foregroundImage": "./src/assets/#####.png",
>         "backgroundColor": "#ef7a38"
>       },
>       "package": "#####"
>     },
>     "extra": {
>       "eas": {
>         "projectId": "#####"
>       }
>     }
>   }
> }
> ```
> 
> The react code:
> 
> ```js
> import { Image } from "expo-image";
> export default function GridMenu({myImage}) {
>   return <Image
>       source={myImage}
>       style={styles.thumbnailImage}
>       contentFit="contain"
>     />
> }
> ```
> 
> The react code is irrelevant as the app breaks regardless of there I import the image.
> 
> ### Environment
> expo-env-info 1.0.5 environment info: System: OS: Windows 10 10.0.19045 Binaries: Node: 16.16.0 - C:\Program Files\nodejs\node.EXE Yarn: 1.22.19 - ~\Desktop\LDL\mao-app\node_modules.bin\yarn.CMD npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD IDEs: Android Studio: AI-221.6008.13.2211.9514443 npmPackages: @expo/webpack-config: 18.0.4 => 18.0.4 expo: ~48.0.18 => 48.0.19 react: 18.2.0 => 18.2.0 react-dom: ~18.2.0 => 18.2.0 react-native: 0.71.8 => 0.71.8 react-native-web: ~0.18.9 => 0.18.12 Expo Workflow: bare

Can you solve this?

**Comment by brayanobisto** [comment]
> ### Minimal reproducible example
> Created expo app using `npx create-expo-app my-app` [docs.expo.dev/tutorial/create-your-first-app](https://docs.expo.dev/tutorial/create-your-first-app/) Installed expo-image into my React Native Expo application.
> 
> ### Summary
> When I try to use expo-image I keep getting the same error. `Error: Cannot find native module 'ExpoImage'`
> 
> Here are screenshots of the errors:
> 
> ![WhatsApp Image 2023-07-05 at 13 17 19 (2)](https://user-images.githubusercontent.com/47431553/251147252-7a2a6e4c-6df8-47f4-be38-412eba7b24e2.jpeg) ![WhatsApp Image 2023-07-05 at 13 17 19 (1)](https://user-images.githubusercontent.com/47431553/251147258-3ca1cec7-d2eb-46e1-abb7-23281898c3be.jpeg) ![WhatsApp Image 2023-07-05 at 13 17 19](https://user-images.githubusercontent.com/47431553/251147260-04465dbc-c12a-4051-876b-e4e8ea0939c9.jpeg)
> 
> **I have tried to remove node-modules, android, .expo folders as well as yarn.lock file.** Reinstalled everything and still not working. In the process of trying to fix the issue I updated most the packages I have used.
> 
> Here are some other dependencies that might be relevant.
> 
> Dependencies:
> 
> ```json
>     "@expo/webpack-config": "18.0.4",
>     "@fortawesome/react-native-fontawesome": "^0.3.0",
>     "@react-native-async-storage/async-storage": "1.19.0",
>     "@react-navigation/native": "^6.1.6",
>     "@react-navigation/native-stack": "^6.9.12",
>     "expo": "~48.0.18",
>     "expo-dev-client": "~2.2.1",
>     "expo-file-system": "~15.2.2",
>     "expo-font": "~11.1.1",
>     "expo-image": "^1.3.1",
>     "react": "18.2.0",
>     "react-device-detect": "^2.2.3",
>     "react-dom": "~18.2.0",
>     "react-native": "0.71.8",
>     "react-native-asset": "^2.1.0",
>     "react-native-safe-area-context": "~4.5.0",
>     "react-native-screens": "~3.22.0",
>     "react-native-size-matters": "^0.4.0",
>     "react-native-svg": "~13.4.0",
>     "react-native-url-polyfill": "^1.3.0",
>     "react-native-web": "~0.18.9",
>     "yarn": "^1.22.19"
> ```
> 
> The `app.json` file:
> 
> ```json
> {
>   "expo": {
>     "name": "#####",
>     "slug": "#####",
>     "version": "1.0.0",
>     "updates": {
>       "fallbackToCacheTimeout": 0
>     },
>     "assetBundlePatterns": [
>       "**/*"
>     ],
>     "ios": {
>       "supportsTablet": true
>     },
>     "android": {
>       "adaptiveIcon": {
>         "foregroundImage": "./src/assets/#####.png",
>         "backgroundColor": "#ef7a38"
>       },
>       "package": "#####"
>     },
>     "extra": {
>       "eas": {
>         "projectId": "#####"
>       }
>     }
>   }
> }
> ```
> 
> The react code:
> 
> ```js
> import { Image } from "expo-image";
> export default function GridMenu({myImage}) {
>   return <Image
>       source={myImage}
>       style={styles.thumbnailImage}
>       contentFit="contain"
>     />
> }
> ```
> 
> The react code is irrelevant as the app breaks regardless of there I import the image.
> 
> ### Environment
> expo-env-info 1.0.5 environment info: System: OS: Windows 10 10.0.19045 Binaries: Node: 16.16.0 - C:\Program Files\nodejs\node.EXE Yarn: 1.22.19 - ~\Desktop\LDL\mao-app\node_modules.bin\yarn.CMD npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD IDEs: Android Studio: AI-221.6008.13.2211.9514443 npmPackages: @expo/webpack-config: 18.0.4 => 18.0.4 expo: ~48.0.18 => 48.0.19 react: 18.2.0 => 18.2.0 react-dom: ~18.2.0 => 18.2.0 react-native: 0.71.8 => 0.71.8 react-native-web: ~0.18.9 => 0.18.12 Expo Workflow: bare
Were you able to solve the problem?

**Comment by brayanobisto** [comment]
> ### Minimal reproducible example
> Created expo app using `npx create-expo-app my-app` [docs.expo.dev/tutorial/create-your-first-app](https://docs.expo.dev/tutorial/create-your-first-app/) Installed expo-image into my React Native Expo application.
> 
> ### Summary
> When I try to use expo-image I keep getting the same error. `Error: Cannot find native module 'ExpoImage'`
> 
> Here are screenshots of the errors:
> 
> ![WhatsApp Image 2023-07-05 at 13 17 19 (2)](https://user-images.githubusercontent.com/47431553/251147252-7a2a6e4c-6df8-47f4-be38-412eba7b24e2.jpeg) ![WhatsApp Image 2023-07-05 at 13 17 19 (1)](https://user-images.githubusercontent.com/47431553/251147258-3ca1cec7-d2eb-46e1-abb7-23281898c3be.jpeg) ![WhatsApp Image 2023-07-05 at 13 17 19](https://user-images.githubusercontent.com/47431553/251147260-04465dbc-c12a-4051-876b-e4e8ea0939c9.jpeg)
> 
> **I have tried to remove node-modules, android, .expo folders as well as yarn.lock file.** Reinstalled everything and still not working. In the process of trying to fix the issue I updated most the packages I have used.
> 
> Here are some other dependencies that might be relevant.
> 
> Dependencies:
> 
> ```json
>     "@expo/webpack-config": "18.0.4",
>     "@fortawesome/react-native-fontawesome": "^0.3.0",
>     "@react-native-async-storage/async-storage": "1.19.0",
>     "@react-navigation/native": "^6.1.6",
>     "@react-navigation/native-stack": "^6.9.12",
>     "expo": "~48.0.18",
>     "expo-dev-client": "~2.2.1",
>     "expo-file-system": "~15.2.2",
>     "expo-font": "~11.1.1",
>     "expo-image": "^1.3.1",
>     "react": "18.2.0",
>     "react-device-detect": "^2.2.3",
>     "react-dom": "~18.2.0",
>     "react-native": "0.71.8",
>     "react-native-asset": "^2.1.0",
>     "react-native-safe-area-context": "~4.5.0",
>     "react-native-screens": "~3.22.0",
>     "react-native-size-matters": "^0.4.0",
>     "react-native-svg": "~13.4.0",
>     "react-native-url-polyfill": "^1.3.0",
>     "react-native-web": "~0.18.9",
>     "yarn": "^1.22.19"
> ```
> 
> The `app.json` file:
> 
> ```json
> {
>   "expo": {
>     "name": "#####",
>     "slug": "#####",
>     "version": "1.0.0",
>     "updates": {
>       "fallbackToCacheTimeout": 0
>     },
>     "assetBundlePatterns": [
>       "**/*"
>     ],
>     "ios": {
>       "supportsTablet": true
>     },
>     "android": {
>       "adaptiveIcon": {
>         "foregroundImage": "./src/assets/#####.png",
>         "backgroundColor": "#ef7a38"
>       },
>       "package": "#####"
>     },
>     "extra": {
>       "eas": {
>         "projectId": "#####"
>       }
>     }
>   }
> }
> ```
> 
> The react code:
> 
> ```js
> import { Image } from "expo-image";
> export default function GridMenu({myImage}) {
>   return <Image
>       source={myImage}
>       style={styles.thumbnailImage}
>       contentFit="contain"
>     />
> }
> ```
> 
> The react code is irrelevant as the app breaks regardless of there I import the image.
> 
> ### Environment
> expo-env-info 1.0.5 environment info: System: OS: Windows 10 10.0.19045 Binaries: Node: 16.16.0 - C:\Program Files\nodejs\node.EXE Yarn: 1.22.19 - ~\Desktop\LDL\mao-app\node_modules.bin\yarn.CMD npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD IDEs: Android Studio: AI-221.6008.13.2211.9514443 npmPackages: @expo/webpack-config: 18.0.4 => 18.0.4 expo: ~48.0.18 => 48.0.19 react: 18.2.0 => 18.2.0 react-dom: ~18.2.0 => 18.2.0 react-native: 0.71.8 => 0.71.8 react-native-web: ~0.18.9 => 0.18.12 Expo Workflow: bare

Were you able to solve the problem?

**Comment by MoreeZ** [comment]
> Were you able to solve the problem?

Yeah, not 100% sure what caused it but I ended up rebuilding my whole project from ground up on every device and it solved itself.
At one point the problem was present on my personal android device but it worked fine on the emulator. I fixed that issue by deleting my eas build and rebuilding and redownloading the project.

**Comment by stesvis** [comment]
> > Were you able to solve the problem?
> 
> Yeah, not 100% sure what caused it but I ended up rebuilding my whole project from ground up on every device and it solved itself. At one point the problem was present on my personal android device but it worked fine on the emulator. I fixed that issue by deleting my eas build and rebuilding and redownloading the project.

What commands did you run? I am having the same problem and I deleted the `node_modules` folder, reinstalled everything, restarted after clearing the cache, and I still get it.

>  ERROR  Error: Cannot find native module 'ExpoImage'
>  ERROR  Invariant Violation: "main" has not been registered. This can happen if:
> * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
> * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

**Comment by papipranay** [comment]
facing similar issue in debug and crashlytics is report crash in production https://github.com/expo/expo/issues/23899

**Comment by MoreeZ** [comment]
Make sure to uninstall the old dev build on your android device before installing the new one.

**Comment by papipranay** [comment]
@MoreeZ can you please also take a look into this issue i am seeing in iOS https://github.com/expo/expo/issues/23899

**Comment by harrymelka** [comment]
To fix that I increase the version of deploymentTarget until in app.json it works. I just had to increase from 13 to 14 in my case and it worked again.

```json
"plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 31,
            "targetSdkVersion": 31,
            "kotlinVersion": "1.7.10"
          },
          "ios": {
            "deploymentTarget": "14.0"
          }
        }
      ],
]
```

**Comment by juliolemosdf** [comment]
npx react-native run-ios
npx react-native run-android

**Comment by olearykieran** [comment]
Deleting the app from my simulator then running npx expo rin:ios solved this error for me

**Comment by valentin-fngr** [comment]
> Make sure to uninstall the old dev build on your android device before installing the new one.

You saved my day, literally. You are a true hero.

**Comment by abdwebus** [comment]
I had to delete the app on my ios device and then ran `npx expo run:ios --device` again for it to work.

**Comment by tfrank11** [comment]
I had to also delete the `ios` folder
