### ISSUE TITLE
[SDK 49] Cannot find native module 'ExpoDevMenu', js engine: hermes

### ISSUE THREAD

**Issue by thespacemanatee** [expo/expo#23401]
### Minimal reproducible example

https://github.com/thespacemanatee/expo-dev-menu-repro

### Summary

#23219 has broken iOS Release builds that import `expo-dev-menu`. A simple `import "expo-dev-client";` will cause a crash at launch with the following stacktrace:

```
[CoreFoundation] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Error: Cannot find native module 'ExpoDevMenu', js engine: hermes', reason: 'Unhandled JS Exception: Error: Cannot find native module 'ExpoDevMenu', js engine: hermes, stack:
requireNativeModule@53668:21
anonymous@58299:58
loadModuleImplementation@205:13
guardedLoadModule@136:37
metroRequire@64:91
anonymous@58246:55
loadModuleImplementation@205:13
guardedLoadModule@136:37
metroRequire@64:91
anonymous@58131:51
loadModuleImplementation@205:13
guardedLoadModule@136:37
metroRequire@64:91
anonymous@58101:13
loadModuleImplementation@205:13
guardedLoadModule@136:37
metroRequire@64:91
anonymous@878:47
loadModuleImplementation@205:13
guardedLoadModule@128:46
metroRequire@64:91
global@58537:3
```

At the very least, the docs here should be updated to say that the imports should be conditional to the build environment: https://docs.expo.dev/bare/install-dev-builds-in-bare/#optional-configuration

I believe this could have been avoided if it was tested on Release builds before releasing it to the public.

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.asdf/installs/nodejs/16.15.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/16.15.0/bin/yarn
      npm: 8.5.5 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.06.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/thespacemanatee/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 23, 26, 29, 30, 31, 33
        Build Tools: 26.0.3, 29.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.2, 34.0.0
        System Images: android-24 | Google APIs ARM 64 v8a, android-26 | Google APIs ARM 64 v8a, android-26 | Google APIs Intel x86_64 Atom, android-26 | Google Play Intel x86 Atom, android-29 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.0 => 49.0.0 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
    npmGlobalPackages:
      eas-cli: 3.15.0
    Expo Workflow: bare
```

**Comment by bj97301** [comment]
I am also experiencing this issue.

**Comment by fobos531** [comment]
Same - I'm not sure what changed internally to cause this - but if it could be modified so
it works fine on Release builds (like it used to), that would be great.

**Comment by ornakash** [comment]
Same here.

**Comment by ldevLucasl** [comment]
Just remove the 'expo-dev-client' import from your main file

**Comment by thespacemanatee** [comment]
@ldevLucasl the docs still should be fixed at least. I'm also using some methods from `expo-dev-menu` to customize the dev menu. Seems like a fix is already underway.

**Comment by bj97301** [comment]
> Just remove the 'expo-dev-client' import from your main file

Oh didn't realize it was caused by that. I thought it was in a random package somewhere. I must be experiencing another issue cuz my app still crashes immediately when on iOS non dev build(main and prod builds).

**Comment by rafavalerio** [comment]
> > Just remove the 'expo-dev-client' import from your main file
> 
> Oh didn't realize it was caused by that. I thought it was in a random package somewhere. I must be experiencing another issue cuz my app still crashes immediately when on iOS non dev build(main and prod builds). This was the only error log I could find in senty though.

There is currently an issue with SDK49 for prod builds if you use `expo-updates` or have any packages that import it.

For now, I guess the best course is to roll back to SDK48 until a fix is released.

More info: https://github.com/expo/expo/pull/23385

**Comment by bj97301** [comment]
> > > Just remove the 'expo-dev-client' import from your main file
> 
> > 
> 
> > Oh didn't realize it was caused by that. I thought it was in a random package somewhere. I must be experiencing another issue cuz my app still crashes immediately when on iOS non dev build(main and prod builds). This was the only error log I could find in senty though.
> 
> 
> 
> There is currently an issue with SDK49 for prod builds if you use `expo-updates` or have any packages that import it.
> 
> 
> 
> For now, I guess the best course is to roll back to SDK48 until a fix is released.
> 
> 
> 
> More info: https://github.com/expo/expo/pull/23385


Ahhh didn't realize that. I do use updates. I removed the update code deny my app but still insta crashed. The kicker is it's nearly impossible for me to track down. No logs or errors anywhere. Thank you for the info I'll be sure to check out and follow that bug. Would love to be on 49 and get the orientation bug fixed 😊
