### ISSUE TITLE
Expo web does not run on SDK 49

### ISSUE THREAD

**Issue by hyochan** [expo/expo#23412]
### Minimal reproducible example

https://github.com/dooboolab-community/expo-router-starter/tree/migration/expo-49

### Summary

![Screenshot 2023-07-09 at 10 37 20 PM](https://github.com/expo/expo/assets/27461460/5e978ef3-7920-47f0-af9c-3b7de346e2e1)

I am not sure if this are issues with other packages but my boilerplate project started to fail running on web environment.

It started failing in [branch migration/expo-49](https://github.com/dooboolab-community/expo-router-starter/tree/migration/expo-49) while it works perfectly in [main branch](https://github.com/dooboolab-community/expo-router-starter).

<details>
  <summary>Logs here</summary>

```sh
"textShadow*" style props are deprecated. Use "textShadow".
warnOnce @ index.js:26
preprocess @ preprocess.js:126
compileAndInsertAtomic @ index.js:58
(anonymous) @ index.js:101
create @ index.js:89
(anonymous) @ ErrorToast.js:87
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ ErrorToastContainer.web.js:41
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ index.js:11
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ error-overlay.js:1
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ registerRootComponent.tsx:11
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ renderRootComponent.tsx:5
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ entry.js:1
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ index.js:1
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ index.tsx:26
index.js:1 "transform" style array value is deprecated. Use space-separated string functions, e.g., "scaleX(2) rotateX(15deg)".
warnOnce @ index.js:26
preprocess @ preprocess.js:161
compileAndInsertAtomic @ index.js:58
(anonymous) @ index.js:101
create @ index.js:89
(anonymous) @ HeaderBackButton.js:123
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ index.js:7
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ NativeStackView.js:2
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ createNativeStackNavigator.js:4
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ index.js:9
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ Stack.tsx:8
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ index.tsx:3
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ _app.tsx:8
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ entry.js:2
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ index.js:1
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ index.tsx:26
getRoutes.ts:298 Error loading route "./_layout.tsx" TypeError: (0 , _stylis.middleware) is not a function
    at createCache (emotion-cache.browser.esm.js:542:24)
    at emotion-element-c39617d8.browser.esm.js:22:11
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at emotion-react.browser.esm.js:4:1
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at ThemeProvider.tsx:12:1
(anonymous) @ getRoutes.ts:298
contextModuleToFileNodes @ getRoutes.ts:274
contextModuleToTree @ getRoutes.ts:419
getExactRoutes @ getRoutes.ts:408
getRoutes @ getRoutes.ts:363
initialize @ router-store.tsx:70
(anonymous) @ router-store.tsx:254
mountMemo @ react-dom.development.js:17227
useMemo @ react-dom.development.js:17672
useMemo @ react.development.js:1652
useInitializeExpoRouter @ router-store.tsx:252
ContextNavigator @ ExpoRoot.tsx:90
renderWithHooks @ react-dom.development.js:16307
mountIndeterminateComponent @ react-dom.development.js:20076
beginWork @ react-dom.development.js:21590
beginWork$1 @ react-dom.development.js:27428
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
performConcurrentWorkOnRoot @ react-dom.development.js:25741
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
getRoutes.ts:298 Error loading route "./details.tsx" TypeError: (0 , _stylis.middleware) is not a function
    at createCache (emotion-cache.browser.esm.js:542:24)
    at emotion-element-c39617d8.browser.esm.js:22:11
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at emotion-react.browser.esm.js:4:1
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at ThemeProvider.tsx:12:1
(anonymous) @ getRoutes.ts:298
contextModuleToFileNodes @ getRoutes.ts:274
contextModuleToTree @ getRoutes.ts:419
getExactRoutes @ getRoutes.ts:408
getRoutes @ getRoutes.ts:363
initialize @ router-store.tsx:70
(anonymous) @ router-store.tsx:254
mountMemo @ react-dom.development.js:17227
useMemo @ react-dom.development.js:17672
useMemo @ react.development.js:1652
useInitializeExpoRouter @ router-store.tsx:252
ContextNavigator @ ExpoRoot.tsx:90
renderWithHooks @ react-dom.development.js:16307
mountIndeterminateComponent @ react-dom.development.js:20076
beginWork @ react-dom.development.js:21590
beginWork$1 @ react-dom.development.js:27428
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
performConcurrentWorkOnRoot @ react-dom.development.js:25741
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
getRoutes.ts:298 Error loading route "./index.tsx" TypeError: (0 , _stylis.middleware) is not a function
    at createCache (emotion-cache.browser.esm.js:542:24)
    at emotion-element-c39617d8.browser.esm.js:22:11
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at emotion-react.browser.esm.js:4:1
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at ThemeProvider.tsx:12:1
(anonymous) @ getRoutes.ts:298
contextModuleToFileNodes @ getRoutes.ts:274
contextModuleToTree @ getRoutes.ts:419
getExactRoutes @ getRoutes.ts:408
getRoutes @ getRoutes.ts:363
initialize @ router-store.tsx:70
(anonymous) @ router-store.tsx:254
mountMemo @ react-dom.development.js:17227
useMemo @ react-dom.development.js:17672
useMemo @ react.development.js:1652
useInitializeExpoRouter @ router-store.tsx:252
ContextNavigator @ ExpoRoot.tsx:90
renderWithHooks @ react-dom.development.js:16307
mountIndeterminateComponent @ react-dom.development.js:20076
beginWork @ react-dom.development.js:21590
beginWork$1 @ react-dom.development.js:27428
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
performConcurrentWorkOnRoot @ react-dom.development.js:25741
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
SafeAreaContext.js:74 Uncaught Error: No safe area value available. Make sure you are rendering `<SafeAreaProvider>` at the top of your app.
    at useSafeAreaInsets (SafeAreaContext.js:74:10)
    at SafeAreaView.web.js:28:116
    at renderWithHooks (react-dom.development.js:16307:7)
    at updateForwardRef (react-dom.development.js:19229:10)
    at beginWork (react-dom.development.js:21639:10)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4166:9)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4216:16)
    at invokeGuardedCallback (react-dom.development.js:4279:1)
    at beginWork$1 (react-dom.development.js:27453:29)
    at performUnitOfWork (react-dom.development.js:26559:10)
useSafeAreaInsets @ SafeAreaContext.js:74
(anonymous) @ SafeAreaView.web.js:28
renderWithHooks @ react-dom.development.js:16307
updateForwardRef @ react-dom.development.js:19229
beginWork @ react-dom.development.js:21639
callCallback @ react-dom.development.js:4166
invokeGuardedCallbackDev @ react-dom.development.js:4216
invokeGuardedCallback @ react-dom.development.js:4279
beginWork$1 @ react-dom.development.js:27453
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
performConcurrentWorkOnRoot @ react-dom.development.js:25741
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
getRoutes.ts:298 Error loading route "./_layout.tsx" TypeError: (0 , _stylis.middleware) is not a function
    at createCache (emotion-cache.browser.esm.js:542:24)
    at emotion-element-c39617d8.browser.esm.js:22:11
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at emotion-react.browser.esm.js:4:1
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at ThemeProvider.tsx:12:1
(anonymous) @ getRoutes.ts:298
contextModuleToFileNodes @ getRoutes.ts:274
contextModuleToTree @ getRoutes.ts:419
getExactRoutes @ getRoutes.ts:408
getRoutes @ getRoutes.ts:363
initialize @ router-store.tsx:70
(anonymous) @ router-store.tsx:254
mountMemo @ react-dom.development.js:17227
useMemo @ react-dom.development.js:17672
useMemo @ react.development.js:1652
useInitializeExpoRouter @ router-store.tsx:252
ContextNavigator @ ExpoRoot.tsx:90
renderWithHooks @ react-dom.development.js:16307
mountIndeterminateComponent @ react-dom.development.js:20076
beginWork @ react-dom.development.js:21590
beginWork$1 @ react-dom.development.js:27428
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
recoverFromConcurrentError @ react-dom.development.js:25853
performConcurrentWorkOnRoot @ react-dom.development.js:25752
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
getRoutes.ts:298 Error loading route "./details.tsx" TypeError: (0 , _stylis.middleware) is not a function
    at createCache (emotion-cache.browser.esm.js:542:24)
    at emotion-element-c39617d8.browser.esm.js:22:11
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at emotion-react.browser.esm.js:4:1
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at ThemeProvider.tsx:12:1
(anonymous) @ getRoutes.ts:298
contextModuleToFileNodes @ getRoutes.ts:274
contextModuleToTree @ getRoutes.ts:419
getExactRoutes @ getRoutes.ts:408
getRoutes @ getRoutes.ts:363
initialize @ router-store.tsx:70
(anonymous) @ router-store.tsx:254
mountMemo @ react-dom.development.js:17227
useMemo @ react-dom.development.js:17672
useMemo @ react.development.js:1652
useInitializeExpoRouter @ router-store.tsx:252
ContextNavigator @ ExpoRoot.tsx:90
renderWithHooks @ react-dom.development.js:16307
mountIndeterminateComponent @ react-dom.development.js:20076
beginWork @ react-dom.development.js:21590
beginWork$1 @ react-dom.development.js:27428
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
recoverFromConcurrentError @ react-dom.development.js:25853
performConcurrentWorkOnRoot @ react-dom.development.js:25752
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
getRoutes.ts:298 Error loading route "./index.tsx" TypeError: (0 , _stylis.middleware) is not a function
    at createCache (emotion-cache.browser.esm.js:542:24)
    at emotion-element-c39617d8.browser.esm.js:22:11
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at emotion-react.browser.esm.js:4:1
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at ThemeProvider.tsx:12:1
(anonymous) @ getRoutes.ts:298
contextModuleToFileNodes @ getRoutes.ts:274
contextModuleToTree @ getRoutes.ts:419
getExactRoutes @ getRoutes.ts:408
getRoutes @ getRoutes.ts:363
initialize @ router-store.tsx:70
(anonymous) @ router-store.tsx:254
mountMemo @ react-dom.development.js:17227
useMemo @ react-dom.development.js:17672
useMemo @ react.development.js:1652
useInitializeExpoRouter @ router-store.tsx:252
ContextNavigator @ ExpoRoot.tsx:90
renderWithHooks @ react-dom.development.js:16307
mountIndeterminateComponent @ react-dom.development.js:20076
beginWork @ react-dom.development.js:21590
beginWork$1 @ react-dom.development.js:27428
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
recoverFromConcurrentError @ react-dom.development.js:25853
performConcurrentWorkOnRoot @ react-dom.development.js:25752
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
SafeAreaContext.js:74 Uncaught Error: No safe area value available. Make sure you are rendering `<SafeAreaProvider>` at the top of your app.
    at useSafeAreaInsets (SafeAreaContext.js:74:10)
    at SafeAreaView.web.js:28:116
    at renderWithHooks (react-dom.development.js:16307:7)
    at updateForwardRef (react-dom.development.js:19229:10)
    at beginWork (react-dom.development.js:21639:10)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4166:9)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4216:16)
    at invokeGuardedCallback (react-dom.development.js:4279:1)
    at beginWork$1 (react-dom.development.js:27453:29)
    at performUnitOfWork (react-dom.development.js:26559:10)
useSafeAreaInsets @ SafeAreaContext.js:74
(anonymous) @ SafeAreaView.web.js:28
renderWithHooks @ react-dom.development.js:16307
updateForwardRef @ react-dom.development.js:19229
beginWork @ react-dom.development.js:21639
callCallback @ react-dom.development.js:4166
invokeGuardedCallbackDev @ react-dom.development.js:4216
invokeGuardedCallback @ react-dom.development.js:4279
beginWork$1 @ react-dom.development.js:27453
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
recoverFromConcurrentError @ react-dom.development.js:25853
performConcurrentWorkOnRoot @ react-dom.development.js:25752
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
LogBox.web.js:99 The above error occurred in the <ForwardRef> component:

    at http://localhost:8081/index.bundle//&platform=web&dev=true&hot=false&lazy=true:86978:27
    at div
    at http://localhost:8081/index.bundle//&platform=web&dev=true&hot=false&lazy=true:45925:27
    at View (http://localhost:8081/index.bundle//&platform=web&dev=true&hot=false&lazy=true:68715:17)
    at createPsuedoClassView (http://localhost:8081/index.bundle//&platform=web&dev=true&hot=false&lazy=true:68460:22)
    at Tutorial (http://localhost:8081/index.bundle//&platform=web&dev=true&hot=false&lazy=true:133584:20)
    at ContextNavigator (http://localhost:8081/index.bundle//&platform=web&dev=true&hot=false&lazy=true:97351:25)
    at ExpoRoot (http://localhost:8081/index.bundle//&platform=web&dev=true&hot=false&lazy=true:97322:31)
    at r (http://localhost:8081/index.bundle//&platform=web&dev=true&hot=false&lazy=true:134471:23)
    at App
    at withDevTools(App)
    at LogBoxStateSubscription (http://localhost:8081/index.bundle//&platform=web&dev=true&hot=false&lazy=true:68032:9)
    at ErrorOverlay

React will try to recreate this component tree from scratch using the error boundary you provided, LogBoxStateSubscription.
registerError @ LogBox.web.js:99
console.error @ LogBox.web.js:38
logCapturedError @ react-dom.development.js:18689
callback @ react-dom.development.js:18757
callCallback @ react-dom.development.js:13926
commitUpdateQueue @ react-dom.development.js:13946
commitLayoutEffectOnFiber @ react-dom.development.js:23367
commitLayoutMountEffects_complete @ react-dom.development.js:24690
commitLayoutEffects_begin @ react-dom.development.js:24676
commitLayoutEffects @ react-dom.development.js:24614
commitRootImpl @ react-dom.development.js:26825
commitRoot @ react-dom.development.js:26684
finishConcurrentRender @ react-dom.development.js:25894
performConcurrentWorkOnRoot @ react-dom.development.js:25811
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
index.js:26 "shadow*" style props are deprecated. Use "boxShadow".
warnOnce @ index.js:26
preprocess @ preprocess.js:115
compileAndInsertAtomic @ index.js:58
(anonymous) @ index.js:101
create @ index.js:89
(anonymous) @ LogBoxInspectorFooter.js:89
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ ErrorOverlay.js:43
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
show @ index.js:16
(anonymous) @ LogBoxData.js:235
setTimeout (async)
setSelectedLog @ LogBoxData.js:231
addPendingLog @ LogBoxData.js:125
(anonymous) @ LogBoxData.js:140
flushCallbacks @ LogBoxLog.js:91
updateStatus @ LogBoxLog.js:180
(anonymous) @ LogBoxLog.js:145
Promise.then (async)
handleSymbolicate @ LogBoxLog.js:144
_symbolicate @ LogBoxLog.js:124
symbolicate @ LogBoxLog.js:107
appendNewLog @ LogBoxData.js:138
(anonymous) @ LogBoxData.js:186
setTimeout (async)
global.setImmediate @ index.js:15
addException @ LogBoxData.js:182
addException @ LogBox.web.js:77
handleException @ index.js:73
reportLogBoxError @ LogBoxData.js:64
componentDidCatch @ LogBoxData.js:359
callback @ react-dom.development.js:18770
callCallback @ react-dom.development.js:13926
commitUpdateQueue @ react-dom.development.js:13946
commitLayoutEffectOnFiber @ react-dom.development.js:23367
commitLayoutMountEffects_complete @ react-dom.development.js:24690
commitLayoutEffects_begin @ react-dom.development.js:24676
commitLayoutEffects @ react-dom.development.js:24614
commitRootImpl @ react-dom.development.js:26825
commitRoot @ react-dom.development.js:26684
finishConcurrentRender @ react-dom.development.js:25894
performConcurrentWorkOnRoot @ react-dom.development.js:25811
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
3index.js:121 StyleSheet.compose(a, b) is deprecated; use array syntax, i.e., [a,b].
compose @ index.js:121
LogBoxButton @ LogBoxButton.js:50
renderWithHooks @ react-dom.development.js:16307
mountIndeterminateComponent @ react-dom.development.js:20076
beginWork @ react-dom.development.js:21590
beginWork$1 @ react-dom.development.js:27428
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
performSyncWorkOnRoot @ react-dom.development.js:26088
flushSyncCallbacks @ react-dom.development.js:12044
commitRootImpl @ react-dom.development.js:26961
commitRoot @ react-dom.development.js:26684
finishConcurrentRender @ react-dom.development.js:25983
performConcurrentWorkOnRoot @ react-dom.development.js:25811
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
index.js:26 TouchableWithoutFeedback is deprecated. Please use Pressable.
warnOnce @ index.js:26
TouchableWithoutFeedback @ index.js:39
renderWithHooks @ react-dom.development.js:16307
updateForwardRef @ react-dom.development.js:19229
beginWork @ react-dom.development.js:21639
beginWork$1 @ react-dom.development.js:27428
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
performSyncWorkOnRoot @ react-dom.development.js:26088
flushSyncCallbacks @ react-dom.development.js:12044
commitRootImpl @ react-dom.development.js:26961
commitRoot @ react-dom.development.js:26684
finishConcurrentRender @ react-dom.development.js:25983
performConcurrentWorkOnRoot @ react-dom.development.js:25811
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
index.js:26 focusable is deprecated.
warnOnce @ index.js:26
createDOMProps @ index.js:506
createElement @ index.js:22
(anonymous) @ index.js:111
renderWithHooks @ react-dom.development.js:16307
updateForwardRef @ react-dom.development.js:19229
beginWork @ react-dom.development.js:21639
beginWork$1 @ react-dom.development.js:27428
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
performSyncWorkOnRoot @ react-dom.development.js:26088
flushSyncCallbacks @ react-dom.development.js:12044
commitRootImpl @ react-dom.development.js:26961
commitRoot @ react-dom.development.js:26684
finishConcurrentRender @ react-dom.development.js:25983
performConcurrentWorkOnRoot @ react-dom.development.js:25811
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
index.js:26 selectable prop is deprecated. Use styles.userSelect.
warnOnce @ index.js:26
(anonymous) @ index.js:59
renderWithHooks @ react-dom.development.js:16307
updateForwardRef @ react-dom.development.js:19229
beginWork @ react-dom.development.js:21639
beginWork$1 @ react-dom.development.js:27428
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
performSyncWorkOnRoot @ react-dom.development.js:26088
flushSyncCallbacks @ react-dom.development.js:12044
commitRootImpl @ react-dom.development.js:26961
commitRoot @ react-dom.development.js:26684
finishConcurrentRender @ react-dom.development.js:25983
performConcurrentWorkOnRoot @ react-dom.development.js:25811
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
12index.js:121 StyleSheet.compose(a, b) is deprecated; use array syntax, i.e., [a,b].
compose @ index.js:121
LogBoxButton @ LogBoxButton.js:50
renderWithHooks @ react-dom.development.js:16307
mountIndeterminateComponent @ react-dom.development.js:20076
beginWork @ react-dom.development.js:21590
beginWork$1 @ react-dom.development.js:27428
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
performSyncWorkOnRoot @ react-dom.development.js:26088
flushSyncCallbacks @ react-dom.development.js:12044
commitRootImpl @ react-dom.development.js:26961
commitRoot @ react-dom.development.js:26684
finishConcurrentRender @ react-dom.development.js:25983
performConcurrentWorkOnRoot @ react-dom.development.js:25811
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
15index.js:121 StyleSheet.compose(a, b) is deprecated; use array syntax, i.e., [a,b].
compose @ index.js:121
LogBoxButton @ LogBoxButton.js:50
renderWithHooks @ react-dom.development.js:16307
updateFunctionComponent @ react-dom.development.js:19591
beginWork @ react-dom.development.js:21604
beginWork$1 @ react-dom.development.js:27428
performUnitOfWork @ react-dom.development.js:26559
workLoopSync @ react-dom.development.js:26468
renderRootSync @ react-dom.development.js:26436
performConcurrentWorkOnRoot @ react-dom.development.js:25741
workLoop @ scheduler.development.js:269
flushWork @ scheduler.development.js:241
performWorkUntilDeadline @ scheduler.development.js:535
Show 13 more frames
HMRClient.js:227 Disconnected from Metro (1006: "").

To reconnect:
- Ensure that Metro is running and available on the same network
- Reload this app (will trigger further help if Metro cannot be connected to)
```

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 3.6.0 - ~/.nvm/versions/node/v18.15.0/bin/yarn
      npm: 9.7.2 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.04.03.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.1.0 => 18.1.0 
      expo: ^49.0.0 => 49.0.1 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
      react-native-web: ~0.19.6 => 0.19.6 
    npmGlobalPackages:
      eas-cli: 3.15.0
    Expo Workflow: managed
```

</details>

**Comment by hyochan** [comment]
[This](https://github.com/thysultan/stylis/issues/254) might be related. I've tried adding below in `webpack.config.js` but no luck.

```js
config.module.rules.push({test: /\.mjs$/, type: 'javascript/auto'});
```

**Comment by devoren** [comment]
Do you use [metro bundler](https://docs.expo.dev/routing/installation/#modify-project-configuration)?

**Comment by hyochan** [comment]
> Do you use [metro bundler](https://docs.expo.dev/routing/installation/#modify-project-configuration)?

Yes. It is set in https://github.com/dooboolab-community/expo-router-starter/blob/982636241ff0302babd45c502751cf518e17fd4c/app.config.ts#L110 and https://github.com/dooboolab-community/expo-router-starter/blob/982636241ff0302babd45c502751cf518e17fd4c/babel.config.js#L6

**Comment by devoren** [comment]
import type {ReactElement, ReactNode} from 'react';
import {SplashScreen, Stack} from 'expo-router';

SplashScreen.preventAutoHideAsync();

function Layout(): ReactElement | null {
  return <Stack />;
}

export default function RootLayout(): ReactNode {
  return <Layout />;
}

![code](https://github.com/expo/expo/assets/99968085/2686bf61-7d36-414b-b491-6cc8013f4034)

After removing all libraries: 
<img width="374" alt="image" src="https://github.com/expo/expo/assets/99968085/17ec79ab-3a26-4cee-abe3-82f476271df7">
 
I think you should try removing each import to find which library or file has the error

**Comment by hyochan** [comment]
I think I need to know why it is not working from in SDK49 and why it only happens in web?

**Comment by devoren** [comment]
Yes you should try, if some code works on native and not in web then you can use .web.js / .native.js extension

**Comment by devoren** [comment]
Yes, maybe, but when I import any dooboo files, the error also occurs

**Comment by hyochan** [comment]
> Yes, maybe, but when I import any dooboo files, the error also occurs

Yes because it depends on emotion

**Comment by devoren** [comment]
Why doesn’t it work, maybe something was changed, added or removed during the last update? :(

**Comment by marklawlor** [comment]
We are investigating, the issue appears to be a module resolution conflict between Metro and stylis (a dependency of emotion)

**Comment by BoavistaLudwig** [comment]
I also have multiple issues with SDK49 on the web:

1. Web Bundling failed 3108ms
Unable to resolve "@fortawesome/free-solid-svg-icons" from "app/(var)/start.tsx"

2. Web Bundling failed 7704ms
Unable to resolve "@koale/useworker" from "node_modules/expo-camera/build/useWebQRScanner.js"

pretty annoying ... I have no issues with SDK48

**Comment by andreiascendia** [comment]
> 2. Web Bundling failed 7704ms
>    Unable to resolve "@koale/useworker" from "node_modules/expo-camera/build/useWebQRScanner.js"

> pretty annoying ... I have no issues with SDK48

I bump into the same thing

**Comment by rozsival** [comment]
It appears to be connected with this issue: https://github.com/facebook/metro/issues/535.

For me, adding the following to the `metro.config.js` config worked:

```js
const { getDefaultConfig } = require('@expo/metro-config');

const config = getDefaultConfig(__dirname);
config.resolver.sourceExts.push('cjs', 'mjs');

module.exports = config;
```

A little warning for TS users, `sourceExts` property is typed as `ReadonlyArray` 😌, so you might need to add `@ts-expect-error` on top of the line to allow `push`.

Also, I'm currently in the middle of migrating my project to SDK 49, there might be other issues to deal with while bundling for the web, but this could help others to move forward too.

**Comment by hyochan** [comment]
> ```js
> const { getDefaultConfig } = require('@expo/metro-config');
> 
> const config = getDefaultConfig(__dirname);
> config.resolver.sourceExts.push('cjs', 'mjs');
> 
> module.exports = config;
> ```

Actually, I already tried above before I posted the issue and I faced another error like below. Therefore I just felt that this is not a solution 🤔

```
WARNING in ./node_modules/i18n-js/dist/require/MissingTranslation.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/MissingTranslation.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/MissingTranslation.ts'

WARNING in ./node_modules/i18n-js/dist/require/Pluralization.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/Pluralization.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/Pluralization.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/camelCaseKeys.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/camelCaseKeys.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/camelCaseKeys.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/createTranslationOptions.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/createTranslationOptions.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/createTranslationOptions.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/expandRoundMode.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/expandRoundMode.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/expandRoundMode.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/formatNumber.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/formatNumber.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/formatNumber.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/getFullScope.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/getFullScope.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/getFullScope.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/index.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/inferType.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/inferType.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/inferType.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/interpolate.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/interpolate.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/interpolate.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/isSet.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/isSet.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/isSet.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/lookup.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/lookup.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/lookup.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/numberToDelimited.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/numberToDelimited.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/numberToDelimited.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/numberToHuman.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/numberToHuman.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/numberToHuman.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/numberToHumanSize.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/numberToHumanSize.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/numberToHumanSize.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/parseDate.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/parseDate.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/parseDate.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/pluralize.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/pluralize.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/pluralize.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/propertyFlatList.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/propertyFlatList.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/propertyFlatList.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/roundNumber.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/roundNumber.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/roundNumber.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/strftime.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/strftime.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/strftime.ts'

WARNING in ./node_modules/i18n-js/dist/require/helpers/timeAgoInWords.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/timeAgoInWords.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/helpers/timeAgoInWords.ts'

WARNING in ./node_modules/i18n-js/dist/require/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/index.ts'

WARNING in ./node_modules/i18n-js/dist/require/typing.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/typing.ts' file: Error: ENOENT: no such file or directory, open '/Users/hyo/Github/dooboolab/dooboo-expo/node_modules/i18n-js/src/typing.ts'

ERROR in ./node_modules/@expo/metro-runtime/build/error-overlay/Data/parseLogBoxLog.js:10
Module not found: Can't resolve 'react-native/Libraries/UTFSequence'
   8 |
   9 | // @ts-expect-error
> 10 | import UTFSequence from "react-native/Libraries/UTFSequence";
  11 |
  12 | import parseErrorStack from "../modules/parseErrorStack";
  13 | import stringifySafe from "../modules/stringifySafe";

ERROR in ./node_modules/@expo/metro-runtime/build/error-overlay/modules/parseErrorStack/parseHermesStack.js:1
Module not found: Can't resolve 'react-native/Libraries/Core/Devtools/parseErrorStack'
> 1 | import parseErrorStack from "react-native/Libraries/Core/Devtools/parseErrorStack";
  2 |
  3 | export { parseErrorStack };
  4 |

ERROR in ./node_modules/expo-asset/build/Asset.js:2
Module not found: Can't resolve 'react-native/Libraries/Image/AssetRegistry'
  1 | import { Platform } from 'expo-modules-core';
> 2 | import { getAssetByID } from 'react-native/Libraries/Image/AssetRegistry';
  3 |
  4 | import { AssetMetadata, selectAssetSource } from './AssetSources';
  5 | import * as AssetUris from './AssetUris';

ERROR in ./node_modules/expo-asset/build/resolveAssetSource.web.js:1
Module not found: Can't resolve 'react-native/Libraries/Image/AssetRegistry'
> 1 | import { getAssetByID } from 'react-native/Libraries/Image/AssetRegistry';
  2 |
  3 | import AssetSourceResolver, { ResolvedAssetSource } from './AssetSourceResolver';
  4 |

ERROR in ./node_modules/expo-image/build/utils/resolveAssetSource.web.js:1
Module not found: Can't resolve 'react-native/Libraries/Image/AssetRegistry'
> 1 | import { getAssetByID } from 'react-native/Libraries/Image/AssetRegistry';
  2 |
  3 | import AssetSourceResolver, { ResolvedAssetSource } from './AssetSourceResolver.web';
```

**Comment by rozsival** [comment]
@hyochan Have you tried adding `web.js` to the list of extensions?

**Comment by rozsival** [comment]
@hyochan Turns out `cjs` extension is already included in the `@expo/metro-config`, to only `mjs` should be added.

About your error, that's really strange. It almost seems like in your case `metro` is not able to resolve `web.js` modules, which it actually should by default. I tried it and it works for my project without any issues. 

Not sure about the source maps parsing though. If I am able to reproduce the error, I'll try to find some solution.

**Comment by rozsival** [comment]
@marklawlor In my case only `mjs` modules cause the problem. I suppose `mjs` extension could be added here: https://github.com/expo/expo/blob/919bdd2921b64eb9399e35377d98d4ed6e07836f/packages/%40expo/metro-config/src/ExpoMetroConfig.ts#L96

**Comment by hyochan** [comment]
> @hyochan Turns out `cjs` extension is already included in the `@expo/metro-config`, only `mjs` needs to be added.
> 
> About your error, that's really strange. It almost seems like in your case `metro` is not able to resolve `web.js` modules, which it actually should by default. I tried it and it works for my project without any issues.
> 
> Not sure about the source maps parsing though. If I am able to reproduce the error, I'll try to find some solution.

@rozsival I am really sorry!! I temporarily removed `metro` because of the issue in #23480. The real issue I faced was below which @EvanBacon is working on following https://twitter.com/Baconbrix/status/1679323911316545542 which is really thankful and impressive.

```
Web Bundling failed 15090ms
Unable to resolve "../Utilities/Platform" from "node_modules/react-native/Libraries/ReactPrivate/ReactNativePrivateInterface.js"
```

**Comment by BoavistaLudwig** [comment]
> It appears to be connected with this issue: [facebook/metro#535](https://github.com/facebook/metro/issues/535).
> 
> For me, adding the following to the `metro.config.js` config worked:
> 
> ```js
> const { getDefaultConfig } = require('@expo/metro-config');
> 
> const config = getDefaultConfig(__dirname);
> config.resolver.sourceExts.push('cjs', 'mjs');
> 
> module.exports = config;
> ```
> 
> A little warning for TS users, `sourceExts` property is typed as `ReadonlyArray` 😌, so you might need to add `@ts-expect-error` on top of the line to allow `push`.
> 
> Also, I'm currently in the middle of migrating my project to SDK 49, there might be other issues to deal with while bundling for the web, but this could help others to move forward too.

This worked for me as well 🥳

**Comment by hyochan** [comment]
I am seeing below after applying #23551

```tsx
Web Bundling failed 6794ms
Unable to resolve "../Utilities/Platform" from "node_modules/react-native/Libraries/ReactPrivate/ReactNativePrivateInterface.js"

Import stack:
 node_modules/react-native/Libraries/ReactPrivate/ReactNativePrivateInterface.js
 | import "../Utilities/Platform"

 node_modules/react-native/Libraries/Renderer/shims/ReactFabric.js
 | import "react-native/Libraries/ReactPrivate/ReactNativePrivateInterface"

 node_modules/react-native/Libraries/ReactNative/RendererImplementation.js
 | import "../Renderer/shims/ReactFabric"

 node_modules/react-native/Libraries/ReactNative/RendererProxy.js
 | import "./RendererImplementation"

 node_modules/react-native/Libraries/Utilities/codegenNativeCommands.js
 | import "../ReactNative/RendererProxy"

 node_modules/react-native-maps/lib/MapMarkerNativeComponent.js
 | import "react-native/Libraries/Utilities/codegenNativeCommands"
          Importing react-native internals is not supported on web.

 node_modules/react-native-maps/lib/MapMarker.js
 | import "./MapMarkerNativeComponent"

 node_modules/react-native-maps/lib/index.js
 | import "./MapMarker"

  app/view/map.tsx
 | import "react-native-maps"

  app (require.context)
  src/Details/Home/index.tsx
 | import "react-native-maps"

  app/mission/[missionId]/index.tsx
 | import "../../../src/Details/Home"

  app (require.context)
```

**Comment by hyochan** [comment]
I believe this matter encompasses two key challenges. Given the intertwined nature of the discussions on this issue, I find it necessary to offer a concise summary for clearer understanding.

1. Conflict between Metro and stylis
2. Metro bundling issue

**Comment by jstdk** [comment]
My Expo app worked perfectly in SDK48 and is totally broken in SDK49. Besides this Backhandler issue, many Unmatched Routes errors (simple Link from page A to B), now stuck with the following error

![image](https://github.com/necolas/react-native-web/assets/115603308/ee6b26f4-ce81-4f14-af5e-5302d1b73a51)

**Comment by EvanBacon** [comment]
Original issue is fixed in expo-router@2.0.1

**Comment by hyochan** [comment]
@EvanBacon I just tried updating the packages and ran in https://github.com/dooboolab-community/expo-router-starter/tree/migration/expo-49

However, I am still seeing below.

![Screenshot 2023-07-26 at 12 02 19 PM](https://github.com/expo/expo/assets/27461460/48b9c780-3951-40f2-a53b-87693f894157.

I am not seeing the blank page now but I am seeing "Welcome to Expo page" although I have the `app/index.tsx`. Also, the console shown in the browser is bit different but looks similar 🤔
The only difference is that I am not seeing error in`SafeProvider`.

**Comment by hyochan** [comment]
> Contributor

@EvanBacon @marklawlor I don't thin issue with `stylis` is resolve yet 🤔

**Comment by rozsival** [comment]
@EvanBacon Can I track some other issue for the support of `mjs` modules?

**Comment by marklawlor** [comment]
If you still having issues can you either create a new issue or reply with a repo that reproduces the issue for us. Screenshots provide very little value in helping us troubleshoot issues

**Comment by rozsival** [comment]
@marklawlor I'm sorry, but I'm really confused now. 

There was another [issue](https://github.com/expo/router/issues/786) where others were mentioning troubles with importing `mjs` modules for web. But you closed that issue as duplicate of this one. Now, this issue is closed while `mjs` modules are still not supported.

I can, of course, create a new issue or send a PR. It really is just a tiny change in `@expo/metro-config` (as suggested in one of my previous [comments](https://github.com/expo/expo/issues/23412#issuecomment-1635466168)).

**Comment by awilson9** [comment]
I don't understand if google is just serving me completely irrelevant links or someones answer changed but I received an exact webpage hit based on my query of 

```
"transform" style array value is deprecated. use space-separated string functions, e.g., "scalex(2) rotatex(15deg)".
```

I created a minimum reproducible example over at https://github.com/awilson9/shady-pines-radio-mobile/pull/1

**Comment by marklawlor** [comment]
@awilson9 Are you concerned about

`warning: "transform" style array value is deprecated.`

 It is simply a warning that will only occur in development and will resolved in time. React Native Web deprecated a number of APIs with no announcement and it will take time for the ecosystem to adjust.
or

`Error loading route "./(sidebar)/_layout.tsx" ReferenceError: requestAnimationFrame is not defined`

The error will be resolved by https://github.com/software-mansion/react-native-reanimated/pull/4665

**Comment by nanyaDev** [comment]
> If you still having issues can you either create a new issue or reply with a repo that reproduces the issue for us. Screenshots provide very little value in helping us troubleshoot issues

@marklawlor I've created a minimal [repo](https://github.com/nanyaDev/bug-repro) that reproduces the error:


The exact commands I ran to set up the repro can be seen in the commit messages. The linked repo fails on `npm run web` with the following error:

```
Web Bundling failed 1005ms
Unable to resolve "@fortawesome/fontawesome-svg-core" from "node_modules/@fortawesome/react-native-fontawesome/dist/components/FontAwesomeIcon.js"
```

I confirmed that the issue resolves itself when downgrading to SDK 48. I was also able to fix the issue by creating a `metro.config.js` with the following contents:

```javascript
const { getDefaultConfig } = require('@expo/metro-config');

const config = getDefaultConfig(__dirname);
config.resolver.sourceExts.push('cjs', 'mjs');

module.exports = config;
```

(taken from [this](https://github.com/expo/expo/issues/23412#issuecomment-1634916708) comment by @rozsival)

As [previously mentioned](https://github.com/expo/expo/issues/23412#issuecomment-1653179239) by @rozsival, both issues relating to this error have been closed. Now that a minimal repro exists, could one of the issues be re-opened? (alternatively I can file a new issue)

**Comment by alielhusseini** [comment]
@jstdk by any chance did you upgrade to expo 49, since I am having the same BackHandler issue

**Comment by Akronae** [comment]
Just creating a new blank expo router project gives me these warnings
```
npx create-expo-app@latest --template tabs@49
```
<img width="418" alt="image" src="https://github.com/expo/expo/assets/17302866/3336280e-1c1a-498e-ae8f-f41f0f9d6f86">

**Comment by devoren** [comment]
@Akronae these warnings from react-native-web https://github.com/necolas/react-native-web/releases/tag/0.19.0

**Comment by Akronae** [comment]
@devoren shouldn't expo come with an appropriate RNWeb version? How should I get rid of those? 🤔

**Comment by devoren** [comment]
@Akronae I dont know :( try to change each deprecated styles, but some libraries use deprecated styles so just ignore for now?!

**Comment by events-jonas-chrisw** [comment]
they have deprecated loads of stuff which makes it impossible to move to expo 49. They are warnings for now but imagine they will get removed.
I'm going to have to bin it or patch it.

**Comment by Manas-Nagelia** [comment]
So currently is there no fix for this?

**Comment by francisleigh** [comment]
expo SDK 49 with create-expo-app (typescript template) running `dev --web` yields the below.

I updated expo-router to `2.0.1` but no 🎲 

```shell
Static Rendering Error (Node.js)
Unexpected token < in JSON at position 0
Source
 
 122 |
let
 data
;
 
 123 |
try
 {
>
 124 |
    data 
=
 
JSON
.
parse(txt)
;
 
     |
                
^
 
 125 |
} 
catch
 (error) {
 
 126 |
    _log
.
Log
.
error(
"Failed to generate resources with Metro, the Metro config may not be using the correct serializer. Ensure the metro.config.js is extending the expo/metro-config and is not overriding the serializer."
)
;
 
 127 |
    debug(txt)
;
Call Stack
JSON.parse
<anonymous>
MetroBundlerDevServer.getStaticResourcesAsync
node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js:124:25
async MetroBundlerDevServer.getStaticPageAsync
node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js:179:41
async
node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js:291:46
See 1 more frame
```

**Comment by moza88** [comment]
> ```
> import type {ReactElement, ReactNode} from 'react';
> import {SplashScreen, Stack} from 'expo-router';
> 
> SplashScreen.preventAutoHideAsync();
> 
> function Layout(): ReactElement | null {
>   return <Stack />;
> }
> 
> export default function RootLayout(): ReactNode {
>   return <Layout />;
> }
> ```
> 
> ![code](https://private-user-images.githubusercontent.com/99968085/252165960-2686bf61-7d36-414b-b491-6cc8013f4034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MzQ0MzksIm5iZiI6MTcxNTczNDEzOSwicGF0aCI6Ii85OTk2ODA4NS8yNTIxNjU5NjAtMjY4NmJmNjEtN2QzNi00MTRiLWI0OTEtNmNjODAxM2Y0MDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAwNDg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYzVmZDI2NzM0OWQyNjRkODQ3MTc4NmM1MTM3Yjk1MzgwNTZkMTI0YzAyZTZlZDMwZDAzYmMyNzAxZGUyZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gMpYskcqkeCBVaLxznX9ryW_cULja40teZZpXWnAGK0)
> 
> After removing all libraries: <img alt="image" width="374" src="https://private-user-images.githubusercontent.com/99968085/252166048-17ec79ab-3a26-4cee-abe3-82f476271df7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MzQ0MzksIm5iZiI6MTcxNTczNDEzOSwicGF0aCI6Ii85OTk2ODA4NS8yNTIxNjYwNDgtMTdlYzc5YWItM2EyNi00Y2VlLWFiZTMtODJmNDc2MjcxZGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAwNDg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ODZjNDU5MGEyOWM5YTE4OTA0OTM5MjhhZDNiMDFiNDc4OTFkNmM4ODVlNDZiM2MyYTkwZTVhMGZhYjBhNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V-1-5-lQ2iIMC5PdGT3LW7RlU2V7AtVY3gKkkV77DGQ">
> 
> I think you should try removing each import to find which library or file has the error

I noticed it came from react native paper for my project.
