### ISSUE TITLE
Expo splash screen is not working after publishing update

### ISSUE THREAD

**Issue by burhanyilmaz** [expo/expo#23815]
### Minimal reproducible example

https://github.com/burhanyilmaz/expo-splash-screen-eas-update

### Summary

There is no bug in development mode. App shows splash screen correctly. After publish with eas update. After opening released update, app shows white screen instead splash screen.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.7.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.0 - /opt/homebrew/bin/npm
      Watchman: 2023.04.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /Users/burhanyilmaz/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.5 => 49.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      eas-cli: 3.15.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by pganster** [comment]
I'm experiencing the same issue after upgrading from expo 47.0.12 => 49.0.5 (expo-splash-screen from 0.17.5 => 0.20.5).

**Comment by burhanyilmaz** [comment]
> I'm experiencing the same issue after upgrading from expo 47.0.12 => 49.0.5 (expo-splash-screen from 0.17.5 => 0.20.5).

I upgraded it too. The same issue still exists. 
I know the issue but I don't know how to fix it.

When running `eas update`, I saw this log `Uploading assets skipped - no new assets found`. This means the expo not exporting assets.

**Comment by pganster** [comment]
To clarify, with expo@47.0.12 (and expo-splash-screen@0.17.5) it worked, but after the upgrade it broke.

**Comment by jeokeefe** [comment]
issue started with 49.03 for me. both iOS and Android. only happens with version published to store.

**Comment by jeokeefe** [comment]
UPDATE - I moved the SplashScreen.preventAutoHideAsync(); to below the imports and problem went away. I had it in the App() main component since Expo 47 and had no problems. Starting with 49.03 it caused an issue.

**Comment by burhanyilmaz** [comment]
not make sense to downgrade the expo. it should be fixed with 49.x.x 🚀

**Comment by Kudo** [comment]
hi there! this issue looks like duplicated to #23363 and `expo@49.0.6` should resolve the issue. could you try the version again?

**Comment by pganster** [comment]
Hi, I upgraded to `expo@49.0.6` and `expo-splash-screen@0.20.5` but for me, the same issue still occurs. Do I also need to set `EX_UPDATES_ANDROID_DELAY_LOAD_APP` to `false`, as indicated in the linked issue?

**Comment by burhanyilmaz** [comment]
the issue still exists. @Kudo  @pganster

**Comment by JoshBot-Debug** [comment]
```ts
import { SplashScreen } from "expo-router";
```

In **expo@^49.0.5** you should import **SplashScreen** from **"expo-router"**. Also, call **preventAutoHideAsync()** outside the component, call it as early as possible.
```ts
SplashScreen.preventAutoHideAsync()

function App() {
....
}
```

**Comment by burhanyilmaz** [comment]
@JoshBot-Debug  it is not working :/
Thank you for the comment

**Comment by JoshBot-Debug** [comment]
No problem, just trying to help :)

Okay, are you using **"expo-router"**? If not, try using it and inside **package.json**, change the entry point to **"expo-router/entry"**

[https://docs.expo.dev/routing/installation/#setup-entry-point](url)

To use expo-router, refer this [https://docs.expo.dev/routing/introduction/](url)

I'm using expo-router 2.0.0, I think it's really good, definitely the way to go from sdk 49.0.0 onwards.

I haven't tried building the example you posted, if this doesn't work, I'll check it out

```
{
  "name": "splash-screen-bug",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",  <-- remove this
  "main": "expo-router/entry",              <-- add this
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~49.0.5",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-updates": "~0.18.11",
    "react": "18.2.0",
    "react-native": "0.72.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "typescript": "^5.1.3"
  },
  "private": true
}
```

**Comment by pganster** [comment]
I've identified the issue on my side. The Expo splash screen was never the issue.

In addition to the Expo splash screen I'm also using Expo push notifications. I've wrapped pulling the push token via `Notifications.getExpoPushTokenAsync` within a hook where I hide the splash screen as soon as the token has been retrieved (similar to [this example](https://docs.expo.dev/versions/latest/sdk/splash-screen/#usage)). 

Since Expo v49, it seems that providing the `projectId` to `getExpoPushTokenAsync` is mandatory, which wasn't mentioned in [the changelog](https://github.com/expo/expo/blob/main/CHANGELOG.md#4900--2023-06-27). Now that I've added that field, the token is now being retrieved and the splash screen finally hides.

It would be good to either include this breaking change in the changelog or produce a proper warning if it isn't provided.

**Comment by JoshBot-Debug** [comment]
It isn't mandatory, when setting up your project, you need to set the eas id by executing this command. You may need to install eas-cli.
```
npm install --global eas-cli && \
eas init --id <my-project-id>
```

This will setup you app.json

```json
{
  "expo": {
    "name": "MyApp",
    "slug": "myapp",
    "extra": {
      "eas": {
        "projectId": "<my-project-id>" <-- this is the expo project id
      }
    },
}
```

However, calling getExpoPushTokenAsync without specifying a projectId is deprecated in SDK 49+. So yes, please pass projectId when calling getExpoPushTokenAsync()

```js
import * as Notifications from 'expo-notifications';

await Notifications.getExpoPushTokenAsync({ projectId: "<my-project-id>" })
```

**Comment by burhanyilmaz** [comment]
Hey guys, there is no expo notification lib on my app. @pganster @JoshBot-Debug 
Did you try my app? https://github.com/burhanyilmaz/expo-splash-screen-eas-update

**Comment by pganster** [comment]
> However, calling getExpoPushTokenAsync without specifying a projectId is deprecated in SDK 49+.
What we have observed is that the call doesn't work (i.e. nothing is returned or an exception is thrown, I don't know the specifics anymore) without passing a `projectId`.

**Comment by derekt38** [comment]
> No problem, just trying to help :)
> 
> I read that upgrading to 49.0.6 fixes this issue, maybe try that?
> 
> ```
> yarn add expo@49.0.6
> npx expo install --fix
> ```
> 
> Otherwise, are you using **"expo-router"**? If not, try using it, inside **package.json**, change the entry point to **"expo-router/entry"**
> 
> https://docs.expo.dev/routing/installation/#setup-entry-point
> 
> To use expo-router, refer this https://docs.expo.dev/routing/introduction/
> 
> I'm using expo-router 2.0.0, I think it's really good, definitely the way to go from sdk 49.0.0 onwards.
> 
> I haven't tried building the example you posted, if this doesn't work, I'll check it out
> 
> ```
> {
>   "name": "splash-screen-bug",
>   "version": "1.0.0",
>   "main": "node_modules/expo/AppEntry.js",  <-- remove this
>   "main": "expo-router/entry",              <-- add this
>   "scripts": {
>     "start": "expo start",
>     "android": "expo start --android",
>     "ios": "expo start --ios",
>     "web": "expo start --web"
>   },
>   "dependencies": {
>     "expo": "~49.0.5",
>     "expo-splash-screen": "~0.20.5",
>     "expo-status-bar": "~1.6.0",
>     "expo-updates": "~0.18.11",
>     "react": "18.2.0",
>     "react-native": "0.72.3"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.20.0",
>     "@types/react": "~18.2.14",
>     "typescript": "^5.1.3"
>   },
>   "private": true
> }
> ```

still have this issue how could i fix it ? i could able to see the splash screen in ios simulator but i could not see it after eas build in the real device in ios

**Comment by AnhTP-Corize** [comment]
Does it work on real devices guys? I'm a bit worried about this...

**Comment by burhanyilmaz** [comment]
> Does it work on real devices guys? I'm a bit worried about this...

After building, it is working. 
But it is not working on Expo Go, after `eas update`

**Comment by baeez** [comment]
> It isn't mandatory, when setting up your project, you need to set the eas id by executing this command. You may need to install eas-cli. This still works in SDK 49.
> 
> ```
> npm install --global eas-cli && \
> eas init --id <my-project-id>
> ```
> 
> This will setup you app.json
> 
> ```json
> {
>   "expo": {
>     "name": "MyApp",
>     "slug": "myapp",
>     "extra": {
>       "eas": {
>         "projectId": "<my-project-id>" <-- this is the expo project id
>       }
>     },
> }
> ```
> 
> However, calling getExpoPushTokenAsync without specifying a projectId is deprecated in SDK 49+. So yes, please pass projectId when calling getExpoPushTokenAsync()
> 
> ```js
> import * as Notifications from 'expo-notifications';
> 
> await Notifications.getExpoPushTokenAsync({ projectId: "<my-project-id>" })
> ```

Thanks! for you solution!! :)

**Comment by baeez** [comment]
I share my solution that I did to obtain the project ID:

`import { expo } from "../app.json"`


In my code:

`token = (await Notifications.getExpoPushTokenAsync({ projectId: expo.extra.eas.projectId })).data;`

**Comment by sleekLancelot** [comment]
> UPDATE - I moved the SplashScreen.preventAutoHideAsync(); to below the imports and problem went away. I had it in the App() main component since Expo 47 and had no problems. Starting with 49.03 it caused an issue.

What do you mean by '...below the imports'?
