### ISSUE TITLE
Expo web not replacing process.env variables

### ISSUE THREAD

**Issue by mat-certn** [expo/expo#23812]
### Minimal reproducible example

https://snack.expo.dev/@mat-certn/expo-web-vars

### Summary

I've recently migrated my app to use process.env.EXPO_PUBLIC_DOMAIN etc - i was previously using dotenv.

This works great in Android and iOS - the process.env.EXPO_PUBLIC etc is replaced with the variable and is working as expected and as the docs indicate https://docs.expo.dev/guides/environment-variables/

This is not working when I run the app as a web app, nor is it working in snacks.

### Environment

basic expo app with:

expo start --web

**Comment by TJTorola** [comment]
Can confirm. Ran into this issue when running `expo start` then pressing `w`. No env vars, but env vars work properly when running through Expo go.

**Comment by febLey** [comment]
Can confirm as well, I've created a brand new app via `npx create-expo-app --template` and my env variables are `undefined`

**Comment by bananemo** [comment]
I also encountered the same issue

**Comment by techninja1008** [comment]
(hacky) Workaround:

1. Use dynamic app config
2. Add the following:
   
   ```js
   const filteredEnv = Object.fromEntries(Object.entries(process.env)
     .filter(([key, val]) => key.indexOf("EXPO_PUBLIC_") === 0))
   // ...
   // Include this in the exported config:
     extra: { env: filteredEnv },
   // ...
   ```
3. Replace instances of `process.env` with `Constants.expoConfig.extra.env`, remembering to add `import Constants from 'expo-constants';` to the file

**Comment by techninja1008** [comment]
(hacky) Workaround:

1. Use dynamic app config
2. Add the following:
   
   ```js
   const filteredEnv = Object.fromEntries(Object.entries(process.env)
     .filter(([key, val]) => key.indexOf("EXPO_PUBLIC_") === 0))
   // ...
   // Include this in the exported config:
     extra: { env: filteredEnv },
   // ...
   ```
3. Replace instances of `process.env` with `Constants.expoConfig.extra.env`, remembering to add `import Constants from 'expo-constants';` to the file

**Comment by vine77** [comment]
Thanks @techninja1008! That worked for me. I added this to `app.config.ts`:

```ts
const env = Object.fromEntries(
  Object.entries(process.env).filter(([key]) => key.startsWith('EXPO_PUBLIC_')),
);

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  // ...
  extra: { env },
});
```

And then also added this to some app-level setup code to allow usage of `process.env.EXPO_PUBLIC_KEY` keys at runtime for `npx expo start --web --clear`:

```ts
import Constants from 'expo-constants';

Object.entries(Constants.expoConfig?.extra?.env).forEach(([key, value]) => {
  if (!key.startsWith('EXPO_PUBLIC_') || process.env[key]) return;
  process.env[key] = `${value}`;
});
```

**Comment by robbporto** [comment]
Confirmed. ENV variables don't work for web. I'm using Expo 49.

**Comment by reinoudxyz** [comment]
Yep, not working on web.

**Comment by raienko** [comment]
+1

**Comment by MateuszBukowski93** [comment]
+ 1

**Comment by finnmerlett** [comment]
If anyone wants to fix this by manually adding the `EXPO_PUBLIC_<...>` env variables in to the `process.env` substitution carried out by the config from `createExpoWebpackConfigAsync` (since it doesn't appear to happen automatically at this point with Expo 49), here's how to patch them into the webpack.config.js:

```javascript
const createExpoWebpackConfigAsync = require("@expo/webpack-config");
const { DefinePlugin } = require("webpack");
const get = require("lodash/get");

// Expo CLI will await this method so you can optionally return a promise.
module.exports = async function configureWebpack(
  /** @type {import("@expo/webpack-config/webpack/types").InputEnvironment} */ env,
  /** @type {import("@expo/webpack-config/webpack/types").Arguments} */ argv,
) {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
  const config = await createExpoWebpackConfigAsync(env, argv);

  // Add in missing process.env.EXPO_PUBLIC_<...> variables to the DefinePlugin
  const expoPublicEnvVars = Object.fromEntries(
    Object.entries(process.env)
      .filter(([key]) => key.startsWith("EXPO_PUBLIC_"))
      .map(([key, value]) => [key, JSON.stringify(value)]),
  );
  const configDefinePlugin = config.plugins?.[4];
  if (!(configDefinePlugin instanceof DefinePlugin)) {
    throw new Error("unexpected config plugins array order");
  }
  const configDefinePluginEnv = /** @type {{}} */ (
    // NOTE: the last key is actually the string "process.env", so to access directly you
    // would need to do configDefinePlugin.definitions["process.env"]
    get(configDefinePlugin.definitions, ["process.env"])
  );
  Object.assign(configDefinePluginEnv, expoPublicEnvVars);

  // Finally return the new config for the CLI to use.
  return config;
};

```

You can swap out the lodash.get for something simpler and less type-safe if you aren't trying to play nice with a ts type-checker. Also you may need to drop a breakpoint in to check which array item the existing DefinePlugin is occupying. For me it was index 4, it may be different for you.

**Comment by Kevin5025** [comment]
Hey all, I was able to get the environment variables to work in web. 

1) Use metro bundler because it works closer to the way Android and iOS work: 
https://docs.expo.dev/guides/customizing-metro/#adding-web-support-to-metro

2) install expo-router 
https://github.com/expo/expo/issues/23819

3) add `config.resolver.sourceExts.push("mjs");` to your metro.config.js
https://github.com/facebook/metro/issues/1003

**Comment by jennyckaplan** [comment]
+1

**Comment by brianGammon** [comment]
> Hey all, I was able to get the environment variables to work in web.
> 
> 1. Use metro bundler because it works closer to the way Android and iOS work:
>    https://docs.expo.dev/guides/customizing-metro/#adding-web-support-to-metro
> 2. install expo-router, e.g. `npm install expo-router`
>    [SDK 49 - Constants.expoConfig is an empty object in Web  #23819](https://github.com/expo/expo/issues/23819)
> 3. If you now get an error like `Web Bundling failed Unable to resolve ... from ...,` then add `config.resolver.sourceExts.push("mjs");` to your metro.config.js
>    [Unable to resolve modules on latest Expo with Metro web facebook/metro#1003](https://github.com/facebook/metro/issues/1003)

Using metro bundler for web solved this for me, thank you!

**Comment by Shelrothman** [comment]
> Hey all, I was able to get the environment variables to work in web.
> 
> 1. Use metro bundler because it works closer to the way Android and iOS work:
>    https://docs.expo.dev/guides/customizing-metro/#adding-web-support-to-metro
> 2. install expo-router, e.g. `npm install expo-router`
>    [SDK 49 - Constants.expoConfig is an empty object in Web  #23819](https://github.com/expo/expo/issues/23819)
> 3. If you now get an error like `Web Bundling failed Unable to resolve ... from ...,` then add `config.resolver.sourceExts.push("mjs");` to your metro.config.js
>    [Unable to resolve modules on latest Expo with Metro web facebook/metro#1003](https://github.com/facebook/metro/issues/1003)

This solved it for me too, thank you!

**Comment by greynewell** [comment]
Came here to remark that I've experienced this same issue on android and ios after polyfilling both Browser and NodeJS core APIs. Approach shared by @vine77 and @techninja1008 worked for these environments as well.

**Comment by lpolito** [comment]
I am having the same issue, except for local ios release builds.

If I specify a `NODE_ENV={env}`, the `EXPO_PUBLIC_*` env vars specified in the given `.env.{env}` do not get populated. This works just fine in regular builds.

The fact there's no documentation about maintaining env vars for a local release build is very frustrating. There is [documentation for EAS](https://docs.expo.dev/guides/environment-variables/#environment-variables-in-expo-application-services), but I do not want to rely on EAS to do my builds and want to do everything locally. 

Luckily the above [trick](https://github.com/expo/expo/issues/23812#issuecomment-1697998466) works well, but this should not be necessary.

**Comment by lpolito** [comment]
After spinning my wheels on this, I just went ahead and went back to `react-native-dotenv` which works flawlessly in all styles of build

**Comment by maks-io** [comment]
I am currently experiencing a similar problem, whenever running a web build via `npx expo export -p web` the `process.env.EXPO_PUBLIC_[MY_VAR]` variables are not getting populated accordingly. If the corresponding bundle js then runs in the client's browser it of course cannot retrieve anything but `undefined`.

**Comment by seeden** [comment]
Temp solution
export -p web -c

**Comment by ssarnot** [comment]
> Temp solution export -p web -c

It works! Thank you Zlatko! 🚀

**Comment by ydrea** [comment]
it's present in the current version (SDK 51) too...

**Comment by pa3ick-code** [comment]
Refer to this [expo doc page](https://docs.expo.dev/guides/environment-variables/) to read more about Environment variables in Expo .
This issue should be closed by now

**Comment by ydrea** [comment]
done reading.
still don't understand the following paragraph:

Accessing secrets in EAS Build
After creating a secret, you can read it on subsequent EAS Build jobs with
process.env.VARIABLE_NAME from Node.js or in shell scripts as
$VARIABLE_NAME.

:(

**Comment by pa3ick-code** [comment]
I'm unable to find the paragraph you are talking about.
 Please confirm if you have installed the 'react-native-dotenv' package. If not, please run the command 'npm i react-native-dotenv' in your terminal. Additionally, in your .env file, make sure to precede the variable name with 'EXPO_PUBLIC' (e.g. 'EXPO_PUBLIC_API_URL') to access the environment variables in your React Native app.

**Comment by pa3ick-code** [comment]
I'm unable to find the paragraph you are talking about.
Please confirm if you have installed the 'react-native-dotenv' package. If not, please run the command 'npm i react-native-dotenv' in your terminal. Additionally, in your .env file, make sure to precede the variable name with 'EXPO_PUBLIC' (e.g. 'EXPO_PUBLIC_API_URL') to access the environment variables in your React Native app.

**Comment by ydrea** [comment]
it's on the next page: https://docs.expo.dev/build-reference/variables/
what is the point in using env variables at all, if you can't keep'em
secret?

**Comment by diegohmac** [comment]
I'm also experiencing that, when I run the `eas update` command, if I don't manually export the `.env` variables they won't be available on the update 🤔

**Comment by pa3ick-code** [comment]
To make environment variables unavailable to the public in an Expo project, you can use the expo-secure-store library to store sensitive data securely. Here's how:

1**. Install expo-secure-store:** expo install expo-secure-store

2**. Store sensitive data:** Instead of storing sensitive data in .env files, use expo-secure-store to store them securely:
**import * as SecureStore from 'expo-secure-store';
_// Store a value_
await SecureStore.setItemAsync('API_KEY', 'your_api_key_here');
_// Get a value_
const apiKey = await SecureStore.getItemAsync('API_KEY');**

3**.Use environment variables for non-sensitive data:** For non-sensitive data, you can still use .env files. Expo will automatically exclude these files from the published bundle.

4**.Exclude sensitive files from the bundle:** In your expo.json file, add the following configuration to exclude sensitive files from the published bundle:
JSON
**{
  "expo": {
    ...
    "assetBundlePatterns": ["**/*"],
    "excludeFromBundle": ["./secure.env", "./sensitive-data.json"]
  }
}**

By following these steps, you can keep sensitive environment variables secure and unavailable to the public in your Expo project.

**Comment by SwhiteMHC** [comment]
react-native-dotenv is not an option for me. There is an open issue concerning the incompatability between react-native-dotenv and expo-router, which I am making use of.

Issue: https://github.com/goatandsheep/react-native-dotenv/issues/501

**Comment by skaramicke** [comment]
I came here thinking I had the same problem but I just forgot the PUBLIC part of the constant name.
It seems to work perfectly fine with `expo@~51.0.28` and `expo-constants@16.0.2`

**Comment by devsheva** [comment]
this is still an issue, im using expo 49

**Comment by tjg37** [comment]
I'm also experiencing this issue with expo 51.

**Comment by okwast** [comment]
We've also experienced that. The env variables didn't get updated. The first values set on a machine got used even though those were changed in the env file later on.

For us we could "solve" it by BOTH deleting the dist folder AND doing the web export with the clean flag like `npx expo export --platform web -c`. That way the env variables were updated in the dist folder.

Hope that is helpful to anyone.

**Comment by Jackman3005** [comment]
@okwast We also ran into this today. Finding out that we needed to run with `--clear` or `-c` to get it to pick up the changed environment variables from the `.env` file. We are on Expo Version `52.0.28`.

**Comment by nolife08021** [comment]
I get an empty value when trying to use process.env.EXPO_PUBLIC_VERSION in. It works in debug mode but happens in prod/release mode, I also tried using Constants.expoConfig, but it returns an empty object as well. Is anyone else facing the same issue?

> ENV: Web
> "react-native": "^0.75.2"
> "expo": "^51.0.0"
> "expo-constants": "~16.0.2"


.env
```
EXPO_PUBLIC_VERSION=1.0
```


app.config.js
```
export default {
  expo: {
    extra: {
      buildVersionW: process.env.EXPO_PUBLIC_VERSION || "not set",
    },
    web: {
      config: {
        buildVersionW: process.env.EXPO_PUBLIC_VERSION || "no set", 
      },
      favicon: "./public/favicon.png",
      meta: {
        viewport:
          "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no",
      },
    },
  },
};
```

package.json
```
{
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "npx expo start -c",
    "build": "cat .env && npx expo export -p web --clear",
    "test": "jest",
    "lint": "eslint .",
    "lint:fix": "npm run lint -- --fix",
    "validate": "npm run prettier -- --list-different && npm run lint",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@expo/metro-runtime": "~3.2.3",
    "@react-navigation/bottom-tabs": "6.4.0",
    "@react-navigation/native": "6.0.13",
    "@react-navigation/stack": "6.3.2",
    "babel-eslint": "^10.1.0",
    "deprecated-react-native-listview": "0.0.8",
    "deprecated-react-native-prop-types": "^2.2.0",
    "expo": "^51.0.0",
    "expo-av": "~14.0.7",
    "expo-camera": "~15.0.16",
    "expo-constants": "~16.0.2",
    "expo-dev-client": "~4.0.28",
    "expo-linear-gradient": "~13.0.2",
    "expo-updates": "~0.25.27",
    "expo-video": "^1.2.7",
    "lint-staged": "9.2.1",
    "moment": "2.29.4",
    "patch-package": "^8.0.0",
    "react": "18.3.1",
    "react-dom": "18.2.0",
    "react-native": "^0.75.2",
    "react-native-gesture-handler": "^2.17.1",
    "react-native-reanimated": "^3.1.0",
    "react-native-safe-area-context": "^4.11.0",
    "react-native-screens": "^3.22.0",
    "react-native-svg": "^15.6.0",
    "react-native-vector-icons": "^10.2.0",
    "react-native-web": "~0.19.10",
    "react-navigation-props-mapper": "3.1.0",
  },
}
```

DEBUG mode
> console.log('Version" + process.env.EXPO_PUBLIC_VERSION) 
> Version 1.0


console.log("Version" + process.env.EXPO_PUBLIC_VERSION) in RELEASE/ PROD 
> Version

**Comment by nguyenhai0527** [comment]
+ 1

**Comment by dbertolini** [comment]
For the web deploy, in my case I was running this command to generate the web deploy:

npx expo export --platform web --output-dir web

And also had the same issue as you by not updating the .env values in the deploy. I just added --clean and worked. Resulting this command:

npx expo export --platform web --output-dir web --clear

Maybe this could help someone.

**Comment by SyahmiRafsan** [comment]
> For the web deploy, in my case I was running this command to generate the web deploy:
> 
> npx expo export --platform web --output-dir web
> 
> And also had the same issue as you by not updating the .env values in the deploy. I just added --clean and worked. Resulting this command:
> 
> npx expo export --platform web --output-dir web --clear
> 
> Maybe this could help someone.

Can confirm adding `--clear` fixed it for me. Thanks buddy.

In my case, the latest envs are not being bundled when running expo export -p web.

It always used the old envs when bundling even after I have updated the .env file.

But I think adding `--clear` removes the bundler cache or something?

Because I can definitely feel the process is slower with that flag.

**Comment by ukch** [comment]
Not stale

**Comment by cammil** [comment]
The --clear flag seemed to work for one moment. Until then it seemed my previous envvars were just persistent. However, after building with clear, then running `eas deploy` (which worked fine), and then running `eas deploy --prod` prod still has the old envvars!

What's going on?

**Comment by kitten** [comment]
Unlikely to still be an issue in recent SDKs. I'm assuming this has since collected unrelated problems/issues, but should be resolved/obsolete. `--clear` is indeed sometimes needed here for production builds, depending on when/how files were transpiled, and is expected behaviour for the time being.

@cammil: That's unrelated. Your production deployment likely is cached and needed a moment to switch over to the new alias. Checking the "direct URL" for a given deployment will always give you the deployment directly and reflect recent changes immediately.

Happy to reopen if the original issue is still relevant.

**Comment by omniboyOK** [comment]
Still doesn't work.

**Comment by markanthonyuy** [comment]
Reopen this issue because it's still not working when you export to web. It's ignoring variables in .env or .env.local

**Comment by kitten** [comment]
Locking since new issues aren't related to this issue or any releases/bugs/fixes pre-2025. Open a new issue with a new reproduction please if you encounter any issues, even if they vaguely sound similar
