### ISSUE TITLE
 Sdk 30 Notifications.getExpoPushTokenAsync() not working on standalone Android

### ISSUE THREAD

**Issue by magnusros** [expo/expo#2381]
Hi, 
This problem was solved for sdk 29 in client code. But with sdk 30 the problem  is back. Exact same behavior as issue: https://github.com/expo/expo/issues/1881
@esamelson solved this for sdk 29.

**Comment by Heimathandel** [comment]
@magnusros I had to figure out that there is no fallback or exception for not providing a google-services.json in project root.

I did solve the issue by adding fcm, downloading the google-services.json, linking as described in expo documentation to expo servers and using the "old" way of async call with.then(token)..catch(error)
I hope that helps.

**Comment by Niades** [comment]
Hi, I have the same issue as well. Works fine when I use Expo client. When running a standalone app, it silently hangs on `Notifications.getExpoPushTokenAsync`.

**Comment by safarigps** [comment]
I have same issue -.-

**Comment by mblodorn** [comment]
same issue here

**Comment by BrettS89** [comment]
I'm having this issue as well.

**Comment by Niades** [comment]
@Heimathandel Which SDK version are you on? I tried SDK 30.0, then 29.0, also tried enabling FCM as you suggested. Unfortunately I did not get any results.

**Comment by safarigps** [comment]
any news?

**Comment by safarigps** [comment]
@esamelson can you fix this too please?

**Comment by shashankintelzee** [comment]
guys I am experiencing  same issue ..... getExpoPushTokenAsync()  not generating token in android standalone app. It was working few days back with new build it stopped working. I am using expo 29 .

Anyone able to resolve this issue ?

**Comment by alialaa** [comment]
I have the same issue, I tried using sdk 29 and 30. It works on the expo client app but on standalone apps it works on some phones but doesn't resolve at all on other phones.

**Comment by shashankintelzee** [comment]
@alialaa : I was able to resolve it by integrating FCM on version 30. After integrating started getting expo pushtoken and was able to get notification on android standalone app.
Follow this link https://docs.expo.io/versions/latest/guides/using-fcm
should work

**Comment by shashankintelzee** [comment]
@alialaa Glad worked for you

**Comment by mblodorn** [comment]
After integrating FCM the problem is solved here too.

Version: 30

**Comment by meksiabdou** [comment]
i can't get token from getExpoPushTokenAsync in real device android

**Comment by Heimathandel** [comment]
@Niades I use version 30

**Comment by BrettS89** [comment]
@shashankintelzee Thank you so much for this fix!

**Comment by outaTiME** [comment]
Hi guys, same here 😢 

Suddenly stopped working im using FCM with SDK 30, apparently it is for devices on which the push token was never obtained.

Here a few related links:

https://github.com/expo/expo/issues/2555
https://forums.expo.io/t/android-standalone-app-doesnt-get-expo-push-notification/15260

**Comment by esamelson** [comment]
Hi all -- apologies for the silence here. We're going to look into this as soon as we can.

**Comment by meksiabdou** [comment]
A problem has been resolved after integrating FCM. Thanks @shashankintelzee

**Comment by JonatanSouza04** [comment]
The error also occurs in SDK 31.0.1
I added the FCM, and it did not work.

@esamelson  thanks

**Comment by emrahtoy** [comment]
@esamelson seems like problem occurs only over version 6 (6<) at android side.
Tested with : https://snack.expo.io/@emrahtoy/expo-push-notification-example
Samsung C5 ( Android 7 ) - Permission granted but promise stuck
Huawei P20 lite ( Android 7 ) - Permission granted but promise stuck
LG G4 ( Android 6 ) - working properly
Turkcell Tablet ( Android 5 ) - working properly
4 oter friends using android 6 and below - working properly
3 other friends using android 7 and above - Permission granted but promise stuck

**Comment by arunxampr** [comment]
Issue persists with SDK 31 as well...
while debugging with Expo app it is working but after expo build: android ... it is not working

**Comment by arunxampr** [comment]
@esamelson Issue persist with sdk 31 as well...
after build it's not working

**Comment by arunxampr** [comment]
> @esamelson seems like problem occurs only over version 6 (6<) at android side.
> Tested with : https://snack.expo.io/@emrahtoy/expo-push-notification-example
> Samsung C5 ( Android 7 ) - Permission granted but promise stuck
> Huawei P20 lite ( Android 7 ) - Permission granted but promise stuck
> LG G4 ( Android 6 ) - working properly
> Turkcell Tablet ( Android 5 ) - working properly
> 4 oter friends using android 6 and below - working properly
> 3 other friends using android 7 and above - Permission granted but promise stuck
> 
> Note : All tests done by expo android app

what's the solution?

**Comment by emrahtoy** [comment]
@esamelson this is affecting production and development phases in a really bad way.. is there a solution path or any idea for work around ( except FCM ) ?

**Comment by esamelson** [comment]
Hey all, if you're experiencing this issue in the Expo client app for Android, could you try updating to version 2.9.1? (If you don't see it in the Play Store yet, wait a few hours -- sometimes it takes a while for updates to propagate.) That should fix your issue.

If you're having this issue with FCM in a standalone issue, hold tight -- we're looking into it.

**Comment by hnlinzhi19** [comment]
my device is android 7.0 and client 2.9.1 still not geted pushToken,

**Comment by whusterj** [comment]
I was experiencing this issue in development for the past few days using the Expo client app. Updating to Expo 2.9.1 just now resolved it for me.

**Comment by esamelson** [comment]
Everyone who is using FCM and is affected by this problem on a standalone app -- hang tight, we have landed a fix and expect it to be deployed in the next day or so!

Note that if you have not yet set up FCM, it is now required in order to use Expo push notifications on a standalone Android app. (Google is deprecating GCM and is expiring tokens very quickly.) See this guide for how to set up FCM for your app: https://docs.expo.io/versions/v31.0.0/guides/using-fcm

**Comment by arunxampr** [comment]
> Everyone who is using FCM and is affected by this problem on a standalone app -- hang tight, we have landed a fix and expect it to be deployed in the next day or so!
> 
> Note that if you have not yet set up FCM, it is now required in order to use Expo push notifications on a standalone Android app. (Google is deprecating GCM and is expiring tokens very quickly.) See this guide for how to set up FCM for your app: https://docs.expo.io/versions/v31.0.0/guides/using-fcm

what about the issue "After build it's not working".. but working on expo client

**Comment by esamelson** [comment]
The fix for this issue has now been deployed to our Android build servers for SDK 31. You can run `expo build:android` to rebuild your SDK 31 app with this fix.

All cases that have been reported by this issue should now be covered:
- issue in Expo client has been resolved in v2.9.1 and above
- issue with FCM-enabled standalone apps has been fixed on SDK 31 builders
- for GCM standalone apps, you need to enable FCM

I'm going to go ahead and close this. Apologies for the trouble -- things should work more consistently going forward from here.

**Comment by JB-CHAUVIN** [comment]
@esamelson I am still getting the issue.

SDK : 31
Latest expo CLI
Samsung Galaxy S8 in Genymotion

I think I added the FCM support to my project...

So I don't get why it's not working ?

**Comment by gerardo15** [comment]
The documentation clearly states that notifications do not work on emulators.

**Comment by JPeer264** [comment]
@gerardo15 Notifications do not work, that is correct. But still, it should resolve the promise

**Comment by jSkrills** [comment]
Anyone who finds themselves here and is still seeing the undesired behavior -like I was... @arunxampr @emrahtoy and @esamelson were right on the money with pointing out that it's only certain android versions. The fix for me was that I had not configured my notifications for notification channels which starting in android oreo all local and push notifications needed to be configured with a channel. The [docs](https://docs.expo.io/versions/v31.0.0/guides/notification-channels/) say that it will give you a default channel for your stuff to go through but I am assuming something is messed up with that bc as soon as I implemented the channels the way those docs show I was able to reliably get all my notifications.
