### ISSUE TITLE
expo-updates break gradlew build on Expo 49

### ISSUE THREAD

**Issue by yepMad** [expo/expo#23930]
### Minimal reproducible example

https://github.com/yepMad/expo-updates-break-gradlew-build

### Summary

I recently upgraded my Expo 48 application to version 49. I use managed with the prebuild system. My OS is Windows 11.

After the upgrade I am unable to do a build via `gradlew assembleRelease`. I get an error on the :app:createReleaseExpoManifest step.

When I uninstall the "expo-updates" package I am able to build through gradlew again. There seems to be some problem with "expo-updates" on Windows - as I can build the same expo-updates project through EAS Local Build in WSL and EAS Cloud Build.

I made a demo project: https://github.com/yepMad/expo-updates-break-gradlew-build

> Task :app:createReleaseExpoManifest FAILED
'[node' is not recognized as an internal command

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      expo: ^49.0.7 => 49.0.7 
      react: ^18.2.0 => 18.2.0 
      react-native: ^0.72.3 => 0.72.3 
    Expo Workflow: bare

**Comment by JClackett** [comment]
Yep was about to post the exact same issue, iOS works fine but android just started failing

**Comment by brentvatne** [comment]
@JClackett - look at the full xcode logs. usually this will point you to a more detailed error, likely what you are encountering is some missing import or something along those lines.

https://docs.expo.dev/build-reference/troubleshooting/

**Comment by Kudo** [comment]
published in `expo-updates@0.18.12`

**Comment by Kaosc** [comment]
This issue still exist in 
`"expo-updates": "^0.18.14"` with `expo@49.0.13`

```bash
Task :app:createReleaseExpoManifest FAILED
'[node' is not recognized as an internal or external command,
operable program or batch file.

> Task :expo-updates:compileReleaseKotlin
```

**Comment by Kudo** [comment]
@Kaosc published a fix on `expo-updates@0.18.15`. could you upgrade the version and try again by chance? thanks!

**Comment by Kaosc** [comment]
It's has been fixed now. Thanks @Kudo .

**Comment by Goowwy** [comment]
i had problem with 0.18.18 
[RUN_GRADLEW] * Where:
[RUN_GRADLEW] Build file '/private/var/folders/d8/zscc3kp50cgbg83093976d3r0000gn/T/eas-build-local-nodejs/426d2abf-5145-4934-8bb6-a4567011796d/build/node_modules/expo-updates-interface/android/build.gradle' line: 40
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] A problem occurred evaluating project ':expo-updates-interface'.
[RUN_GRADLEW] > Could not set unknown property 'classifier' for task ':expo-updates-interface:androidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan
[RUN_GRADLEW] to get full insights.

**Comment by toni1703** [comment]
Hello, i think the issue is still there in expo 50.0.6 and expo updates "expo-updates": "~0.24.10". I am in an expo managed react-native app. this is from trying to build app on expo and the same error is if i try to build locally:
![Screenshot 2024-02-09 at 14 47 56](https://github.com/expo/expo/assets/23199856/2f594cee-03c4-4a94-9ca4-e016399a0abb)

**Comment by toni1703** [comment]
Hello, 
the problem still exist!
I am on MacOS, and having the same issue. I tried to build both locally and on eas servers but it is giving me the same error:
Execution failed for task ':app:createReleaseExpoManifest'. that happens for expo updates 0.24.9 and expo 0.24.10

**Comment by AmmarKhan21** [comment]
Hello i am  getting same issue with expo SDk  ^50.0.14 and "expo-updates": "~0.24.12
while building apk with es build i am  getting this error
> Task :app:createReleaseExpoManifest
FAILED
node:internal/modules/cjs/loader:1080
throw err;
^
Error: Cannot find module '@expo/cli/build/src/export/embed/exportEmbedAsync'
Require stack:
- /home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
at Module._load (node:internal/modules/cjs/loader:922:27)
at Module.require (node:internal/modules/cjs/loader:1143:19)
at require (node:internal/modules/cjs/helpers:119:18)
at Object.<anonymous> (/home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js:4:5)
at Module._compile (node:internal/modules/cjs/loader:1256:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
at Module.load (node:internal/modules/cjs/loader:1119:32)
at Module._load (node:internal/modules/cjs/loader:960:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js'
]
}
Node.js v18.18.0
> Task :app:processReleaseResources
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:createReleaseExpoManifest'.
> Process 'command 'node'' finished with non-zero exit value 1
* Try:

**Comment by AmmarKhan21** [comment]
> Hello i am getting same issue with expo SDk ^50.0.14 and "expo-updates": "~0.24.12 while building apk with es build i am getting this error
> 
> > Task :app:createReleaseExpoManifest
> > FAILED
> > node:internal/modules/cjs/loader:1080
> > throw err;
> > ^
> > Error: Cannot find module '@expo/cli/build/src/export/embed/exportEmbedAsync'
> > Require stack:
> 
> * /home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js
>   at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
>   at Module._load (node:internal/modules/cjs/loader:922:27)
>   at Module.require (node:internal/modules/cjs/loader:1143:19)
>   at require (node:internal/modules/cjs/helpers:119:18)
>   at Object. (/home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js:4:5)
>   at Module._compile (node:internal/modules/cjs/loader:1256:14)
>   at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>   at Module.load (node:internal/modules/cjs/loader:1119:32)
>   at Module._load (node:internal/modules/cjs/loader:960:12)
>   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js'
>   ]
>   }
>   Node.js v18.18.0
> 
> > Task :app:processReleaseResources
> > FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:createReleaseExpoManifest'.
> 
> > Process 'command 'node'' finished with non-zero exit value 1
> 
> * Try:

@Kudo can you please help ?

**Comment by BartoszDadok** [comment]
The issue still exists. I have the same problem. Is there any solution?

**Comment by toni1703** [comment]
I think i found the problem. just update "@expo/cli".

**Comment by samixp02** [comment]
> Hello i am getting same issue with expo SDk ^50.0.14 and "expo-updates": "~0.24.12 while building apk with es build i am getting this error
> 
> > Task :app:createReleaseExpoManifest
> > FAILED
> > node:internal/modules/cjs/loader:1080
> > throw err;
> > ^
> > Error: Cannot find module '@expo/cli/build/src/export/embed/exportEmbedAsync'
> > Require stack:
> 
> * /home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js
>   at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
>   at Module._load (node:internal/modules/cjs/loader:922:27)
>   at Module.require (node:internal/modules/cjs/loader:1143:19)
>   at require (node:internal/modules/cjs/helpers:119:18)
>   at Object. (/home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js:4:5)
>   at Module._compile (node:internal/modules/cjs/loader:1256:14)
>   at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>   at Module.load (node:internal/modules/cjs/loader:1119:32)
>   at Module._load (node:internal/modules/cjs/loader:960:12)
>   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js'
>   ]
>   }
>   Node.js v18.18.0
> 
> > Task :app:processReleaseResources
> > FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:createReleaseExpoManifest'.
> 
> > Process 'command 'node'' finished with non-zero exit value 1
> 
> * Try:

so easy in package.json remove "@expo/cli" and we are done
