### ISSUE TITLE
Suspense: throw promise is not working in expo-router.

### ISSUE THREAD

**Issue by smontlouis** [expo/expo#24422]
### Minimal reproducible example

https://github.com/smontlouis/jotai-async

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I thought this was related to [jotai async atoms](https://github.com/pmndrs/jotai/issues/2131), but looks like it's an issue with expo-router.
In the repro, you can change the package main to switch between expo-router and classic to notice the issue.

```jsx
const promise = new Promise((r) => setTimeout(r, 3000))
let resolved = false
promise.then(() => {
  console.log('RESOLVED')
  resolved = true
})

const usePromise = () => {
  if (!resolved) {
    throw promise
  }
}

export const Component = () => {
  usePromise()
  return <Text>Component {count}</Text>
}
```

The following code is failing with expo-router but working in classic expo.

### Environment

System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.10 => 49.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 5.1.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by mluiten** [comment]
I'm new to expo and been trying for hours why my `<Suspense>` in combination with `useRecoilValue` was not updating using expo router... but apparently it's critical that useRecoilValue throws promises to support updates of the view. Hope this can be fixed.

**Comment by smontlouis** [comment]
@marklawlor any news about this ? Not being able to use Suspense in expo-router looks critical.
Am I missing something ? Is there a simpler way of doing it ?

**Comment by marklawlor** [comment]
No updates yet, but It is on the roadmap

**Comment by EvanBacon** [comment]
This will require some re-architecture to support. We didn't account for throwing anything besides errors when writing the internal optimization patterns. We will be rebuilding a number of core features in 2024 to support server components, but unclear if throwing extraneous promises (outside of `use` hook / `Suspense`) will be directly supported.

**Comment by smontlouis** [comment]
Thanks @EvanBacon.

To be clear, it means I'm not able as of now to use jotai async atoms ?
Because it's throwing a promise **inside** Suspense.
https://github.com/pmndrs/jotai/issues/2131

**Comment by jbrumwell** [comment]
@EvanBacon Is this fixed in v3? Currently on 2.0.14 and my recoil state is updated but the suspense is not updated and stays suspended.

**Comment by marklawlor** [comment]
This is not fixed yet. We will update this issue when we have more information available

**Comment by jbrumwell** [comment]
@marklawlor thanks for the update, is the react use hook (https://react.dev/reference/react/use) supported in v3? If not what is the recommended library that will work with suspense?  Right now with recoil the state updates but we are stuck in the suspense.

**Comment by marklawlor** [comment]
Expo Router doesn't change how React works, so you can still use suspense within a route, just not for the route component (as the OP is requesting).

While the suspense APIs have been stable for a while, the React Native ecosystem has been slow to adopt them. Its not as simple as "just fix Expo Router", we have to make upstream changes dependencies. We would like to support React Server Components, which require both Suspense and new features to be added to Metro. Right now we're working on Metro, as it has a larger impact on improving Expo Router projects.

**Comment by mluiten** [comment]
I was rewriting my expo app from recoil to jotai yesterday, and I noticed that, using Expo 50.0.8 / expo-router 3.4.7, the atoms (and thus throwing of promises) actually worked very nicely out of the box. I'm not sure if this was deliberate or not, but I think that #25627 changed the `getLoadable` in `useScreens` in such as way that it always wraps the route in a Suspense, and waits for it to resolve?

@jbrumwell maybe you can retest using the latest expo-router?

**Comment by jbrumwell** [comment]
Thanks @mluiten I'll give it a try!!

**Comment by marklawlor** [comment]
As per the comments above, we are in the process of re-architecturing Expo Router to better support suspense. This is a gradual work-in-progress. You may find that some features work, while others do not. 

We will have a proper announcement (and most likely a version bump) when this feature is stable. You're welcome to try these features, but please hold off on issues until the full announcement.

**Comment by danielpqb** [comment]
I made a Context that works like a middleware for expo-router, it can do the job of rendering a spinner while the components are rendering.

```
import {
  Dispatch,
  FC,
  ReactNode,
  SetStateAction,
  createContext,
  useContext,
  useEffect,
  useState,
} from "react";
import { useAppContext } from "./AppContext";
import { router } from "expo-router";

type TContext = {
  sideMenu: {
    isOpen: boolean;
    open: () => void;
    close: () => void;
    toggle: () => void;
    selectedHref: string;
    setSelectedHref: Dispatch<SetStateAction<string>>;
  };
  router: {
    push: (href: string) => void;
    replace: (href: string) => void;
    back: () => void;
    setParams: () => void;
  };
};
const Context = createContext<TContext>({} as TContext);

type TProps = {
  children: ReactNode;
};
const NavigationContext: FC<TProps> = ({ children }) => {
  const { setIsLoading } = useAppContext();

  const [action, setAction] = useState<() => Promise<void>>();
  //Only act on next render
  useEffect(() => {
    if (typeof action === "function") {
      action();
      setAction(undefined);
    } else {
      setIsLoading(false);
    }
  }, [action]);

  const [isSideMenuOpen, setIsSideMenuOpen] = useState(false);
  const [selectedHref, setSelectedHref] = useState("");

  const sideMenu = {
    isOpen: isSideMenuOpen,
    open: () => setIsSideMenuOpen(true),
    close: () => setIsSideMenuOpen(false),
    toggle: () => setIsSideMenuOpen(!isSideMenuOpen),
    selectedHref: selectedHref,
    setSelectedHref: setSelectedHref,
  };

  const navRouter = {
    push: (href: string) => {
      setIsLoading(true);
      setAction(async () => {
        router.push(href);
      });
    },
    replace: (href: string) => {
      setIsLoading(true);
      setAction(async () => {
        router.replace(href);
      });
    },
    back: () => {
      setIsLoading(true);
      setAction(async () => {
        router.back();
      });
    },
    setParams: () => {
      setIsLoading(true);
      setAction(async () => {
        router.setParams();
      });
    },
  };

  return (
    <Context.Provider value={{ sideMenu, router: navRouter }}>
      {children}
    </Context.Provider>
  );
};

export default NavigationContext;
export function useNavigationContext() {
  return useContext(Context);
}
```

You just have to use the 'useNavigationContext' hook to navigate, and put this LoadingLayout component on your root '_layout.tsx'.

```
import { useAppContext } from "@/contexts/AppContext";
import { gSC } from "@/styles/global";
import { Slot } from "expo-router";
import { ReactNode, useEffect } from "react";
import { ActivityIndicator, Dimensions, View } from "react-native";

type TProps = {
  children?: ReactNode;
};
const LoadingLayout: React.FC<TProps> = ({ children }) => {
  const { isLoading, setIsLoading } = useAppContext();
  const screenWidth = Dimensions.get("screen").width;

  useEffect(() => {
    setIsLoading(false);
  }, []);

  return (
    <>
      {isLoading ? (
        <View
          style={{
            flex: 1,
            width: "100%",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          {children || (
            <ActivityIndicator
              size={screenWidth / 8}
              color={gSC("white")}
            />
          )}
        </View>
      ) : (
        <Slot />
      )}
    </>
  );
};

export default LoadingLayout;
```
It's not super performatic but can enhance the user experience with a feedback while this issue isn't solved.
I hope it can help.

**Comment by smontlouis** [comment]
On Expo 50 everything is working great 👍
