### ISSUE TITLE
[ios] MediaLibrary.getAssetInfoAsync does not return localUri for mediaType "video" 

### ISSUE THREAD

**Issue by afenrir** [expo/expo#2448]
Environment:
  OS: macOS 10.14
  Node: 10.10.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Calling MediaLibrary.getAssetInfoAsync for a media library asset of type "video" does not return a localUri. The documentation does not give any indication that this method should return a different object shape to type 'photo', so I assume it is a bug.

I can't get Snack to play nicely with this for whatever reason, but here is code to reproduce the error:

```javascript
'use strict';
import React, { Component } from 'react';
import { Button } from 'react-native';
import { MediaLibrary, Permissions, Camera } from 'expo';

class CameraScreen extends Component {
    state = { recording: false };

    componentDidMount() {
        Permissions.askAsync(
            Permissions.CAMERA,
            Permissions.CAMERA_ROLL,
            Permissions.AUDIO_RECORDING
        );
    }

    takeVideo = async () => {
        if (this.camera && !this.state.recording) {
            this.setState({ recording: true });
            this.video = this.camera.recordAsync();
        } else if (this.camera && this.state.recording) {
            this.setState({ recording: false });
            this.camera.stopRecording();
            const { uri } = await this.video;
            const asset = await MediaLibrary.createAssetAsync(uri);
            const assetInfo = await MediaLibrary.getAssetInfoAsync(asset);
            console.log(assetInfo);
        }
    };

    render() {
        return (
            <Camera
                ref={ref => (this.camera = ref)}
                style={{ flex: 1, justifyContent: 'center' }}
            >
                <Button
                    onPress={this.takeVideo}
                    title={
                        this.state.recording ? 'Stop recording' : 'Start recording'
                    }
                />
            </Camera>
        );
    }
}

export default CameraScreen;
```

Here is what the above will log. As you can see, there is no localUri:

```javascript
Object {
  "creationTime": 1539848674000,
  "duration": 2.868333333333333,
  "filename": "IMG_1566.MOV",
  "height": 1920,
  "id": "B4AEEE95-32F2-4968-94B7-BFB1B68E694C/L0/001",
  "isFavorite": false,
  "isHidden": false,
  "location": null,
  "mediaSubtypes": Array [],
  "mediaType": "video",
  "modificationTime": 1539848677094,
  "orientation": 0,
  "uri": "assets-library://asset/asset.MOV?id=B4AEEE95-32F2-4968-94B7-BFB1B68E694C&ext=MOV",
  "width": 1080,
}
```

**Comment by peter-axomic** [comment]
This problem still exists on expo 33 with all the videos I've tested. This is seen in simulator, expo app and binary releases for app store.

I can't find any way to get the ```localUri``` through other means, and therefore can't use fetch or XMLHttpRequest to upload a video as the file transferred if you just use the ```uri``` isn't the original, but a file with different EXIF and other properties

Relates to problems around ```localUri``` and https://github.com/expo/expo/issues/3177

**Comment by peter-axomic** [comment]
This problem is also described in https://forums.expo.io/t/upload-file-from-medialibrary/22043

**Comment by peter-axomic** [comment]
Here is a snack that demonstrates the bug. You will need to run it on a device that has at least one photo and one video in the cameral roll.

https://snack.expo.io/@peter-axomic/366ed9

![IMG_7946](https://user-images.githubusercontent.com/1798388/62455535-7e043000-b76e-11e9-94e2-e45de5dda1e1.png)

**Comment by rxhivzero** [comment]
exist expo 34

**Comment by Abdelrahman-Nabil** [comment]
Still having this issue too, anyone has a workaround ?

**Comment by Psiiirus** [comment]
I'm new to expo and using it with a bare RN project...can anyone give me a hint how i can use this fix? Is it enough to just add a dep. yarn add expo-media-library@latest ?

**Comment by lukmccall** [comment]
@Psiiirus, Unfortunately, it won't be easy. We don't publish a new version of our packages after every fix. Most likely for the new version, you need to wait to the next SDK update.

If you need this change now, you can download `expo-media-library` and copy fixed from PR. Next, you can link it locally. I know, it's pretty ugly but it will do the job.

**Comment by Lele** [comment]
Could you tell me whether the fix for this bug is already scheduled?

**Comment by tsapeta** [comment]
@Lele Yes, this bug has been fixed a while ago and will be a part of SDK36 which should be available publicly next week if everything goes well 😉

**Comment by Psiiirus** [comment]
@tsapeta can you tell me which packages i need if i use the react-native-unimodules ?

**Comment by lukmccall** [comment]
I think it's fixed in [media-library 8.0.0](https://www.npmjs.com/package/expo-media-library/v/8.0.0).

**Comment by naliferov** [comment]
iOS Supported SDKs 39, 40,41, 42.
Still the same
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_files$_i.filename')]

**Comment by naliferov** [comment]
try to use await FileSystem.getInfoAsync and got same error 
```
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_files$_i.filename')]
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```
