### ISSUE TITLE
"Attempted to navigate before mounting the Root Layout component." when setting up authenticated routes

### ISSUE THREAD

**Issue by alaughlin** [expo/expo#24734]
### Minimal reproducible example

https://github.com/alaughlin/expo-testing

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I am attempting to follow the directions [here](https://docs.expo.dev/router/reference/authentication/#navigating-without-navigation) in order to enable routing to different pages based on authentication status. However, I am receiving this error:
```
ERROR  Error: Attempted to navigate before mounting the Root Layout component. Ensure the Root Layout component is rendering a Slot, or other navigator on the first render.

This error is located at:
    in AppLayout
    in Unknown (created by Route((app)))
    in Route (created by Route((app)))
    in Route((app)) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by QualifiedSlot)
    in QualifiedSlot (created by Slot)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by QualifiedNavigator)
    in QualifiedNavigator (created by Navigator)
    in Navigator (created by Slot)
    in Slot (created by RootLayout)
    in RootLayout
    in Unknown (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App) (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
```

If I remove the `router.replace()` from my AppLayout, the error goes away, but then the desired redirect will not happen. What am I missing?

### Environment

```expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.13 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
    npmGlobalPackages:
      eas-cli: 5.3.0
    Expo Workflow: managed
```

**Comment by pdcribeiro** [comment]
Happening for me too. @alaughlin, did you find a solution?

**Comment by dhatGuy** [comment]
I added an `index.tsx` and redirect from there. The only issue is I get a blank screen for about 1 - 2 seconds before it redirects

**Comment by eybel** [comment]
I am still having this issue, any updates?

**Comment by mishenThakshana** [comment]
If you using fonts do like this if not loaded just return,

**React.useEffect(() => {
    if (!loaded) return;

    const inTabsGroup = segments[0] === "(tabs)";

    if (isSignedIn && !inTabsGroup) {
      router.replace("/(tabs)/chats");
    } else if (!isSignedIn && inTabsGroup) {
      router.replace("/");
    }
  }, [isSignedIn]);**

**Comment by amloelxer** [comment]
@felippewick @eybel 

Instead of programmatically using the router to navigate, if I return the redirect component it seems to fix the issue for me

In my app/(app)/_layout.tsx file

```
const AppLayout = () => {
    const currentUser = contextObject?.currentUser;
    if (isLoading) {
      return <LoadingScreen />;
    }
  
    if(!currentUser) {
      // BAD  
      // router.replace('/SignIn')
  
      // Fixes the issue
      return <Redirect href="/SignIn" />;
    }
}
```

**Comment by felippewick** [comment]
Yes, this works, but Redirect doesn't give you a replace, unfortunately (navigation without stack animation).

**Comment by xushnud123** [comment]
import { useFonts } from "expo-font";
import { ClerkProvider, ClerkLoaded, useAuth } from "@clerk/clerk-expo";
import * as SecureStore from "expo-secure-store";
import { Link, Redirect, router, Slot, Stack, useSegments } from "expo-router";
import * as SplashScreen from "expo-splash-screen";
import { useEffect, useState } from "react";
import "react-native-reanimated";
import { StatusBar } from "expo-status-bar";
import Toast from "react-native-toast-message";

import "./global.css";
import { ActivityIndicator, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";

SplashScreen.preventAutoHideAsync();

const tokenCache = {
  async getToken(key: string) {
    try {
      const item = await SecureStore.getItemAsync(key);
      if (item) {
        console.log(`${key} was used 🔐 \n`);
      } else {
        console.log("No values stored under key: " + key);
      }
      return item;
    } catch (error) {
      console.error("SecureStore get item error: ", error);
      await SecureStore.deleteItemAsync(key);
      return null;
    }
  },
  async saveToken(key: string, value: string) {
    try {
      return SecureStore.setItemAsync(key, value);
    } catch (err) {
      return;
    }
  },
};

const InitialLayout = () => {
  const { isLoaded, isSignedIn } = useAuth();
  const [isMounted, setIsMounted] = useState(false);
  const segments = useSegments();
  const [loaded] = useFonts({
    SpaceMono: require("../assets/fonts/SpaceMono-Regular.ttf"),
  });

  useEffect(() => {
    if (loaded) {
      SplashScreen.hideAsync();
    }
  }, [loaded]);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  useEffect(() => {
    if (!isMounted || !isLoaded) return;

    const inAuthGroup = segments[0] === "(authenticated)";

    if (isSignedIn && !inAuthGroup) {
      router.replace("/(authenticated)/(tabs)/");
    } else if (!isSignedIn) {
      router.replace("/");
    }
  }, [isSignedIn, isMounted, segments]);

  if (!loaded || !isLoaded) {
    return (
      <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
        <ActivityIndicator size='large' />
      </View>
    );
  }

  return (
    <>
      {
        <Stack>
          <Stack.Screen name='index' options={{ headerShown: false }} />
          <Stack.Screen
            name='login'
            options={{
              title: "",
              headerBackTitle: "",
              headerShadowVisible: false,
              headerStyle: {
                backgroundColor: "#F5F5F5",
              },
              headerLeft: () => (
                <TouchableOpacity
                  style={{ marginLeft: -10 }}
                  onPress={() => router.back()}
                >
                  <Ionicons name='arrow-back' size={34} className='text-dark' />
                </TouchableOpacity>
              ),
              headerRight: () => (
                <Link href='/help' asChild>
                  <TouchableOpacity style={{ marginRight: -10 }}>
                    <Ionicons
                      name='help-circle-outline'
                      size={34}
                      className='text-dark'
                    />
                  </TouchableOpacity>
                </Link>
              ),
            }}
          />
          <Stack.Screen
            name='sign-up'
            options={{
              title: "",
              headerBackTitle: "",
              headerShadowVisible: false,
              headerStyle: {
                backgroundColor: "#F5F5F5",
              },
              headerLeft: () => (
                <TouchableOpacity
                  style={{ marginLeft: -10 }}
                  onPress={() => router.back()}
                >
                  <Ionicons name='arrow-back' size={34} className='text-dark' />
                </TouchableOpacity>
              ),
            }}
          />
          <Stack.Screen
            name='help'
            options={{ title: "Help", presentation: "modal" }}
          />
          <Stack.Screen
            name='verify/[email]'
            options={{
              title: "",
              headerBackTitle: "",
              headerShadowVisible: false,
              headerStyle: {
                backgroundColor: "#F5F5F5",
              },
              headerLeft: () => (
                <TouchableOpacity
                  style={{ marginLeft: -10 }}
                  onPress={() => router.back()}
                >
                  <Ionicons name='arrow-back' size={34} className='text-dark' />
                </TouchableOpacity>
              ),
            }}
          />
        </Stack>
      }
    </>
  );
};

const RootLayout = () => {
  const publishableKey = process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY!;

  if (!publishableKey) {
    throw new Error("Add EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY to your .env file");
  }

  return (
    <ClerkProvider publishableKey={publishableKey!} tokenCache={tokenCache}>
      <ClerkLoaded>
        <StatusBar style='light' />
        <InitialLayout />
        <Toast />
      </ClerkLoaded>
    </ClerkProvider>
  );
};

export default RootLayout;
i am also getting initialized before navigation error here how can i initialize after navigation

**Comment by xushnud123** [comment]
`import { useFonts } from "expo-font";
import { ClerkProvider, ClerkLoaded, useAuth } from "@clerk/clerk-expo";
import * as SecureStore from "expo-secure-store";
import { Link, Redirect, router, Slot, Stack, useSegments } from "expo-router";
import * as SplashScreen from "expo-splash-screen";
import { useEffect, useState } from "react";
import "react-native-reanimated";
import { StatusBar } from "expo-status-bar";
import Toast from "react-native-toast-message";

import "./global.css";
import { ActivityIndicator, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";

SplashScreen.preventAutoHideAsync();

const tokenCache = {
  async getToken(key: string) {
    try {
      const item = await SecureStore.getItemAsync(key);
      if (item) {
        console.log(`${key} was used 🔐 \n`);
      } else {
        console.log("No values stored under key: " + key);
      }
      return item;
    } catch (error) {
      console.error("SecureStore get item error: ", error);
      await SecureStore.deleteItemAsync(key);
      return null;
    }
  },
  async saveToken(key: string, value: string) {
    try {
      return SecureStore.setItemAsync(key, value);
    } catch (err) {
      return;
    }
  },
};

const InitialLayout = () => {
  const { isLoaded, isSignedIn } = useAuth();
  const [isMounted, setIsMounted] = useState(false);
  const segments = useSegments();
  const [loaded] = useFonts({
    SpaceMono: require("../assets/fonts/SpaceMono-Regular.ttf"),
  });

  useEffect(() => {
    if (loaded) {
      SplashScreen.hideAsync();
    }
  }, [loaded]);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  useEffect(() => {
    if (!isMounted || !isLoaded) return;

    const inAuthGroup = segments[0] === "(authenticated)";

    if (isSignedIn && !inAuthGroup) {
      router.replace("/(authenticated)/(tabs)/");
    } else if (!isSignedIn) {
      router.replace("/");
    }
  }, [isSignedIn, isMounted, segments]);

  if (!loaded || !isLoaded) {
    return (
      <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
        <ActivityIndicator size='large' />
      </View>
    );
  }

  return (
    <>
      {
        <Stack>
          <Stack.Screen name='index' options={{ headerShown: false }} />
          <Stack.Screen
            name='login'
            options={{
              title: "",
              headerBackTitle: "",
              headerShadowVisible: false,
              headerStyle: {
                backgroundColor: "#F5F5F5",
              },
              headerLeft: () => (
                <TouchableOpacity
                  style={{ marginLeft: -10 }}
                  onPress={() => router.back()}
                >
                  <Ionicons name='arrow-back' size={34} className='text-dark' />
                </TouchableOpacity>
              ),
              headerRight: () => (
                <Link href='/help' asChild>
                  <TouchableOpacity style={{ marginRight: -10 }}>
                    <Ionicons
                      name='help-circle-outline'
                      size={34}
                      className='text-dark'
                    />
                  </TouchableOpacity>
                </Link>
              ),
            }}
          />
          <Stack.Screen
            name='sign-up'
            options={{
              title: "",
              headerBackTitle: "",
              headerShadowVisible: false,
              headerStyle: {
                backgroundColor: "#F5F5F5",
              },
              headerLeft: () => (
                <TouchableOpacity
                  style={{ marginLeft: -10 }}
                  onPress={() => router.back()}
                >
                  <Ionicons name='arrow-back' size={34} className='text-dark' />
                </TouchableOpacity>
              ),
            }}
          />
          <Stack.Screen
            name='help'
            options={{ title: "Help", presentation: "modal" }}
          />
          <Stack.Screen
            name='verify/[email]'
            options={{
              title: "",
              headerBackTitle: "",
              headerShadowVisible: false,
              headerStyle: {
                backgroundColor: "#F5F5F5",
              },
              headerLeft: () => (
                <TouchableOpacity
                  style={{ marginLeft: -10 }}
                  onPress={() => router.back()}
                >
                  <Ionicons name='arrow-back' size={34} className='text-dark' />
                </TouchableOpacity>
              ),
            }}
          />
        </Stack>
      }
    </>
  );
};

const RootLayout = () => {
  const publishableKey = process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY!;

  if (!publishableKey) {
    throw new Error("Add EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY to your .env file");
  }

  return (
    <ClerkProvider publishableKey={publishableKey!} tokenCache={tokenCache}>
      <ClerkLoaded>
        <StatusBar style='light' />
        <InitialLayout />
        <Toast />
      </ClerkLoaded>
    </ClerkProvider>
  );
};

export default RootLayout;
`

**Comment by xushnud123** [comment]
i am also getting initialized before navigation error here how can i initialize after navigation

**Comment by EvanBacon** [comment]
In Expo Router v5 we mount a virtual navigator at the root to prevent this error from occurring.

**Comment by pcmaffey** [comment]
Im hitting this error now with `prefetch` on a Link, and async routes disabled.

**Comment by DanielKorsa** [comment]
> In Expo Router v5 we mount a virtual navigator at the root to prevent this error from occurring.

Could you elaborate on it?
Im also stuck with this issue....

**Comment by onyedikachi23** [comment]
> Im hitting this error now with `prefetch` on a Link, and async routes disabled.

I'm using `expo-router@5.1.5` and in the root `index.tsx` I'm simply prefetching some routes that their usage is based on a state:

```tsx
const router = useRouter();
	React.useEffect(() => {
		router.prefetch("/(auth)/login");
		router.prefetch("/(tabs)");
	}, [router]);
	const { isAuthenticated } = useAuth();
	if (hasCompletedOnboarding) {
		return (
			<Redirect href={isAuthenticated ? "/(tabs)" : "/(auth)/login"} />
		);
	}
```

When user completes onboarding, the earlier `router.prefetch("/(tabs)")` helps make sure the next route is ready for redirect. So, I don't understand why I'm getting this error @EvanBacon ?

**Comment by onyedikachi23** [comment]
I fixed mine by using a callback ref to defer the navigation till the root view of my screen is mounted:

```tsx

// ✅ This pattern will work
export default function OnboardingScreen() {
	return <View
				className="flex-1"
				ref={(view) => {
					if (view) {
						router.prefetch("/(auth)/login");
						router.prefetch("/(tabs)");
					}
				}}></View>
}

// ❌ This pattern will not work
export default function OnboardingScreen() {
	React.useEffect(() => {
		router.prefetch("/(auth)/login");
		router.prefetch("/(tabs)");
	}, [router]);
}

// ❌ This pattern will not work
export default AppLayout () {
    const currentUser = contextObject?.currentUser;
  
    if(!currentUser) {
      router.replace('/SignIn')
    }
}

**Comment by tannerbaum** [comment]
@EvanBacon I'm on Router 5.1.4 and I will still get this error sometimes even though you would think with the update of having a virtual navigator at the root it wouldn't be possible. I regrettably don't have a reproduction but it happens on quick user action on foregrounding the app, and oddly even after a successful navigation. 

Take these breadcrumbs from Sentry. Touching "Person" is the profile tab in our tab navigator bar at the bottom, which takes you to the profile page. Then the gear icon press is a `Link` wrapping a `Pressable` to the settings page, triggering the error. This is all within the span ~6 seconds. 

<img width="583" height="853" alt="Image" src="https://github.com/user-attachments/assets/7d5cb223-b32f-4c4e-9dea-393938da2ea0" />

And here is a snippet of our root layout with any parts that seem relevant

```jsx
  const [hasOpenedApp] = useMMKVBoolean(STORAGE_KEYS.HAS_OPENED_APP); //first-ever launch
  const [loaded, error] = useFonts({
    // ... 
  });

  useEffect(() => {
    if (loaded || error) {
      SplashScreen.hide();
    }
  }, [loaded, error]);


  if (!loaded && !error) {
    return null;
  }

  return (
    <>
      <AuthContextProvider>
        <GestureHandlerRootView className="flex h-full flex-1 flex-col">
          <Stack screenOptions={{
            headerShown: false,
          }}
          >
            <Stack.Protected guard={!!hasOpenedApp}>
              <Stack.Screen name="(tabs)" />
              <Stack.Screen
                name="modal/login"
                options={{
                  presentation: "transparentModal",
                }}
              />
            </Stack.Protected>
            <Stack.Protected guard={!hasOpenedApp}>
              <Stack.Screen name="onboarding" />
            </Stack.Protected>
            <Stack.Screen name="+not-found" />
          </Stack>
        </GestureHandlerRootView>
      </AuthContextProvider>
    </>
  );
```

Does this suggest anything? Could this be something remedied by the new v6?

**Comment by VariabileAleatoria** [comment]
Still facing the same issue on `expo-router@6.0.13` literally copying the code from [the docs](https://docs.expo.dev/router/advanced/authentication-rewrites/#navigating-without-navigation)

```
import { Slot } from 'expo-router';

export default function RootLayout() {

  return (
    <Slot />
  );
}
```
```
export default function InnerLayout() {
  React.useEffect(() => {
    router.push('/sign-in');
  }, []);

  // It is OK to defer rendering this nested layout's content. We couldn't
  // defer rendering the root layout's content since a navigation event (the
  // redirect) would have been triggered before the root layout's content had
  // been mounted.
  if (true) {
    return <Text>Loading...</Text>;
  }

}
```


`[Error: Attempted to navigate before mounting the Root Layout component. Ensure the Root Layout component is rendering a Slot, or other navigator on the first render.]`
