### ISSUE TITLE
Detached project,  apk "unable to load script from assets 'index.android.bundle'" - android

### ISSUE THREAD

**Issue by BlazJurisic** [expo/expo#2499]
### Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.1.0
  Yarn: 1.9.2
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

### Steps to Reproduce

1. ejected
2. added native modules
3. created signed apk
4. adb install <signed-apk>.apk

### Expected Behavior

Build works as expected, loads splash and rest of the app 

(Write what you thought would happen.)

### Actual Behavior

blue screen shows up saying: 

Something went wrong.
Sorry about that. Press the reload button to try again

Error says: unable to load script from assets 'index.android.bundle

after pressing reload everything loads normally.

### Reproducible Demo
- cant reproduce

**Comment by ide** [comment]
If this happened about a week ago, it could have been related to a bug fixed here https://github.com/expo/expo/commit/d36a750a75817aa7d49f31720d53493754ed0b6f

**Comment by BlazJurisic** [comment]
I think this is the same issue like here -> #2111
Fixes proposed there didn't solve the problem.

**Comment by heyaj19** [comment]
Having the same issue @ide @BlazJurisic  plus app wont hot reload. This happened after I published my apk now on dev nothing works as before. Any idea whats happening?I am on expo 30 detached

**Comment by sjchmiela** [comment]
Could you try publishing your app before creating a signed APK?

**Comment by BlazJurisic** [comment]
@sjchmiela I did that, issue is still present

**Comment by sjchmiela** [comment]
Then, could you see the `expo.android.publishManifestPath` and `expo.android.publishBundlePath` and see their values and confirm if the files exist under these paths? In `android/app/src/main/assets` there should also be files `kernel.android.bundle` and `kernel-manifest.json`.

**Comment by BlazJurisic** [comment]
kernel.android.bundle and kernel-manifest.json exist in android/app/src/main/assets

where can I find expo.android.publishManifestPath and expo.android.publishBundlePath?

**Comment by BlazJurisic** [comment]
they are missing from app.json

**Comment by BlazJurisic** [comment]
<img width="435" alt="screenshot 2018-11-05 at 16 19 52" src="https://user-images.githubusercontent.com/12563346/48006869-aba44600-e116-11e8-9dd6-6dc7a2405c41.png">

this is extracted release.apk

**Comment by heyaj19** [comment]
Can you try clearing the cache that helped me

**Comment by sjchmiela** [comment]
Have you managed to solve this issue? Was it maybe fixed by clearing the cache? (Both the packager one and the Android Studio one?) 🙂

**Comment by nandhakishorenk** [comment]
> Then, could you see the `expo.android.publishManifestPath` and `expo.android.publishBundlePath` and see their values and confirm if the files exist under these paths? In `android/app/src/main/assets` there should also be files `kernel.android.bundle` and `kernel-manifest.json`.

kernel.android.bundle is not found in my assets folder

**Comment by sjchmiela** [comment]
I'll close this issue tentatively, it was reported on a (now) old, unsupported SDK version. I believe upgrading to latest SDK would fix this issue. 🙂
