### ISSUE TITLE
Prevent require cycle warnings in SDK31

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#2538]
Lots of spam, not a lot of value

**Comment by ide** [comment]
Fixed in https://github.com/expo/expo/commit/22a3479a91012dad70c97ed4ae9c9be305071b83

**Comment by WouterFlorijn** [comment]
@ide @brentvatne This is still an issue, and these warnings should be disabled entirely. With SDK 30 they never showed up, but with 31 they keep spamming my console, causing lag and making it impossible to debug actual issues.

Require 'cycles' are unavoidable in many projects, including the one I'm working on. In my project for example, I group all my UI components in the file `src/components/index.js`, which is aliased as `'~/components'`. This file looks something like this:

```js
export * from './subfolder-with-components'
export * from './another-subfolder'
export { default as Component1 } from './Component1'
export { default as Component2 } from './Component2'
export { default as Component3 } from './Component3'
```

This way I can import components using `import { Component1, Component2 } from '~/components'`, which is very useful.

However, if say `Component3` imports `Component1`, I get a require cycle warning, even though you could hardly call this a cycle. It just happens to go through the same file (`src/components/index.js`).

This happens in a few instances, causing tons of require cycle warnings with zero value. This makes it impossible for me and my team to use SDK 31 at the moment.

**Comment by davidwadge** [comment]
This is also a major problem for me, fix appreciated...

**Comment by ide** [comment]
To customize the behavior of this warning, you can override `console.warn` (monkeypatch it) before your other code gets required. This warning is coming from Metro or React Native so opening an issue there is more actionable.

Regarding the umbrella components module -- cycles are unavoidable if you opt to use that pattern and disabling the warning is right if you want to go down that path.

**Comment by JulianKingman** [comment]
@ide can you share how? I've tried monkeypatching console.warn and it doesn't work for me...

```javascript
// App.js, at the top
// Things I tried:
const ignoredWarnings = [
  '<InputAccessoryView> is not supported on Android yet.',
  'Class EX',
  'Require cycles are allowed',
];

// doesn't remove from console
YellowBox.ignoreWarnings(ignoredWarnings);

// does nothing; I believe I also tried putting this in a timeout. I made sure the regex works, but no luck; the function never runs
console.warn = msg => {
  if (!msg.match(new RegExp(`${ignoredWarnings.join('.*|')}.*`), 'g')) {
    console.log('not ignored', ignoredWarnings);
    console.warn(msg);
  }
};

// does nothing to console
setTimeout(() => (console.disableYellowBox = true), 100);

**Comment by ide** [comment]
That code needs to run before any imports that cause the warning - make sure you're actually importing (import statements get hoisted) your cyclic modules after the monkeypatch.

**Comment by lc3t35** [comment]
Same here, can't get rid of this crap .... 
````
Expo CLI 2.6.14 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: 31.0.2 => 31.0.2 
      react: 16.3.1 => 16.3.1 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: 2.18.2 => 2.18.2 
    npmGlobalPackages:
      expo-cli: 2.6.14
````

**Comment by JulianKingman** [comment]
OK, with a little help from this package: https://github.com/sindresorhus/filter-console
I made some progress.... Putting this at the top, above imports, ignores many console warnings, but still doesn't ignore the require cycle messages. Ideas?
```javascript
const ignoredWarnings = [
  '<InputAccessoryView> is not supported on Android yet.',
  'Class EX',
  'Require cycle:',
];
// Don't forget to import this
YellowBox.ignoreWarnings(ignoredWarnings);
const originalConsoleWarn = console.warn;
console.warn = (...args) => {
  const msg = args[0];
  if (msg.match(new RegExp(`${ignoredWarnings.join('.*|')}.*`), 'g')) {
    return;
  }
  originalConsoleWarn(...args);
};
```

**Comment by SDxBacon** [comment]
I do also run into this problem as well with expo v32.0.0. That is so weird that I have tried comment out line 109 in `node_modules/metro/src/lib/polyfills/require.js`. So, the require.js may looks like:
```javascript
function metroRequire(moduleId) {
  ...
  cycle.push(cycle[0]);
  // console.warn('Require cycle: ' + cycle.join(' -> ') + '\n\n' + 'Require cycles are allowed, but can result in uninitialized values. ' + 'Consider refactoring to remove the need for a cycle.');

}
```

The require cycle warning error is still there ! I also tried to debug `node_modules/expo/build/environment/loggin.js` with following changes:
```javascript
// NOTE(2018-10-29): temporarily filter out cyclic dependency warnings here since they are noisy and
// each warning symbolicates a stack trace, which is slow when there are many warnings
const originalWarn = console.warn;
console.warn = function warn(...args) {

    /* Add a small log function to print out the result of comparison.
        The comparison does return with value `true` */
    console.log(args.length > 0 &&
        typeof args[0] === 'string' &&
        /^Require cycle: .*node_modules/.test(args[0]));

    if (args.length > 0 &&
        typeof args[0] === 'string' &&
        /^Require cycle: .*node_modules/.test(args[0])) {
        return;
    }
    originalWarn.apply(console, args);
};
```

But the crap is still there! I don't get it, I can't find any code starting with `console.warn('Require cycle: .... ')` havn't been commented. This is so weird.

**Comment by JulianKingman** [comment]
This comment worked for me for require cycles: https://github.com/facebook/metro/issues/287#issuecomment-470026886
