### ISSUE TITLE
MapView not working on Android (provider: google)

### ISSUE THREAD

**Issue by n-lavrenko** [expo/expo#2580]
Hi guys! 👋
First of all, thank you for your work! This project is awesome!

**Problem:** (that you can easy reproduce)
![image](https://user-images.githubusercontent.com/7901225/47956879-425cef80-dfbd-11e8-8593-5cce74bdb860.png)
**Platforms**: Android, Android emulator.
My OS: MacOs Mojave 10.14
expo-cli: 2.2.5

Just a month ago the same code was working, but today I spent the whole day to solve this problem that you can see on the screen above.  I've created a new project with the newest expo (v31), react-native and react-native-maps (v21), but... no results. 

On the iOS emulator, everything is good. 
Maybe this problem is related to package `react-native-maps` but in the installation guide of this lib contains information about including some API keys and builders inside .xml. files of the Android project, like this:
![image](https://user-images.githubusercontent.com/7901225/47957059-4b9b8b80-dfc0-11e8-9d75-f685d99fa257.png)
![image](https://user-images.githubusercontent.com/7901225/47957051-39b9e880-dfc0-11e8-8b49-3855f8ed64a8.png)

In this case, an expo.io project doesn't contain the folder `android`, that's why I decided to create an issue in this repository.  Also, the problem also may be in the google. I don't know. 

Best regards, 
Nikita

**Comment by danikane** [comment]
Same here, in development mode.
Map shows the Google logo, but there is no content.
Maybe something is wrong with Expo API keys.

  Expo CLI 2.2.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/danikane-a9919a86-ba78-4d98-8f27-c582be8d4d84.tar.gz

**Comment by arnaudncy** [comment]
Same problem here with sdk 31. Everything worked fine with sdk 24. Since I have updated my dependencies, iOS still works but blank map for android.
Did you found some fix?

**Comment by danikane** [comment]
I think there is nothing WE can fix at the moment. 😃 

It would be great if for development we can use our own API key we set in app.json as well, if an API key cannot be found then to fallback to Expo's default API key.

**Comment by conerstone111** [comment]
I am experiencing the same problem, any solution?

**Comment by oliverdolgener** [comment]
Same problem here. It works on published apps but not in development mode. I did not even upgrade to SDK 31. I can't debug my app. Please do something!

**Comment by IdanDavidi** [comment]
Same problem here, SDK 31, any solution?

**Comment by n-lavrenko** [comment]
For today we have just three solutions:
1. Developing without `expo`
2. Downgrade `expo SDK` (I didn't check what is the latest version of the working ViewMap), maybe 29. But not sure that it works fine. 
3. Wait for the bugfix from expo.

**Comment by danikane** [comment]
At the moment with expo 31.0.3 markers are visible, basemaps are not.
I believe you can continue with your development until there full fix is announced, unless having a gray background really bothers you.

**Comment by dsokal** [comment]
Hello guys,
we just pushed a fix to the production, so if you're experiencing this issue in the standalone apps, please rebuild them with `expo build:android`.
Sorry for the inconvenience!

**Comment by mnemotiv** [comment]
@dsokal a fix to where? we're experiencing the issue only while using expo dev mode, not on standalone apps

**Comment by oliverdolgener** [comment]
@dsokal Yes, I'm sorry, but the problem still remains. No map in expo dev mode...

**Comment by dsokal** [comment]
@mnemotiv @oliverdolgener what does "expo dev mode" mean for you guys?
I ran this snack on my phone and it works fine - https://snack.expo.io/@dsokal/disrespectful-yogurt 
I also created a new project (with `expo init`) and then ran `expo start`, scanned the QR code and the app works as well.

Could you please provide the steps to reproduce the issue? What SDK version are you using?

**Comment by mnemotiv** [comment]
![screenshot_20181105-170918](https://user-images.githubusercontent.com/3081042/48006098-ba422b80-e11d-11e8-84f4-0dedc3ed1637.png)
@dsokal this is what I see on that expo snack. expo dev mode - using expo new cli and expo app

**Comment by oliverdolgener** [comment]
@dsokal For me it means: I have created my app with crna and since then I always upgraded to the latest expo version. Currently I'm on SDK 30. In my standalone app (signed android apk) everythings works fine. I can see the map etc like before. But when I want to develop new features using `expo start` and the Expo Client App for Android the map is only grey/beige depending on the mapType. Upgrading to SDK 31 won't make a difference for me.

**Comment by oliverdolgener** [comment]
I thought it would be a problem with my Google Maps API Key but this would also affect my standalone app. Somehow it's only the dev mode app

**Comment by danikane** [comment]
@dsokal First of all thank you for trying to resolve the issue.
Issue occurs on **Android**.
Issue occurs locally (local project created with Expo CLI) or in Snack.
Issue has been reported for SDK31 but people reported it occuring on lower versions too.
Even the Snack you posted proves there is an issue. 😄 

It occurs in "development" and "production" modes, it affects published apps too.
Standalone apps are unaffected, because they use the provided API key we set in app.json and there is no problem.

**Comment by oliverdolgener** [comment]
@danikane I didn't know that the local projects don't use the API key. But that would explain the problems we're having since the standalone apps are working.

**Comment by outaTiME** [comment]
Same here 😢

**Comment by n-lavrenko** [comment]
Good news for `react-native-maps`: I've tested `react-native-maps` on the project based on `react-native-cli` (without expo).
And maps on Android emulator is working. So the problem just in `expo`. I hope for the quick bugfix and I want to return into `expo`. 
![image](https://user-images.githubusercontent.com/7901225/48020884-2174d580-e148-11e8-8776-8b181978988b.png)

**Comment by conerstone111** [comment]
Hi Guys I am experiencing the same issue here , please help

**Comment by esamelson** [comment]
Hi all -- apologies for the inconvenience caused by this issue! 😞  We just released version 2.9.1 of the Expo client to the Play Store which should fix this. Please upgrade and let us know if it's still broken. (If you don't see the update yet, give it a few hours -- sometimes updates take a little while to propagate.)

**Comment by IdanDavidi** [comment]
@esamelson Just updated Expo app and it works fine, thank you!

**Comment by egeucak** [comment]
this solved the problem, thanks a lot

**Comment by n-lavrenko** [comment]
Fixed. Thanks, guys!

**Comment by Billmike** [comment]
Hi @esamelson I am currently on expo client version `2.9.2` and I am experiencing the same grey screen. It works perfectly on iOS simulator but shows a grey screen on Android.
<img width="837" alt="screenshot 2018-11-19 at 10 37 55 am" src="https://user-images.githubusercontent.com/24798364/48698480-78b68380-ebe7-11e8-8884-693d987ce130.png">

**Comment by danikane** [comment]
This has been fixed 2 weeks ago, somewhere some component of yours is old (expo, expo app or something else).

**Comment by Billmike** [comment]
@danikane Started this project four days ago. Expo SDK version is `31.0.0`, expo-cli version is `2.4.0`, expo client version is `2.9.2`. expo version in `package.json` is `31.0.0` Could you tell me what else might be outdated so as to fix it? 🙂 It works perfectly on iOS, just doesn't display properly on Android.

**Comment by danikane** [comment]
Same here, old project with expo 31.0.5, expo-cli 2.4.0 etc ...
My suspect would be the emulator.
Did you try it on a real device and did you try a Snack?

**Comment by danikane** [comment]
Delete the Expo app on your Android emulator and then "Run on Android device/emulator again".
Just in case clear your cache at least. 😃 I would rm -rf node_modules/ as well but oh well ... maybe that's not necessary.

**Comment by Billmike** [comment]
Already did that, without clearing the cache though. Would try that and leave an update on whether or not that works.

**Comment by Billmike** [comment]
Nope! Same thing

**Comment by madmax124** [comment]
The issue is still there and none of the mentioned solutions work :(

**Comment by joshuakaluba** [comment]
For my project, the map works fine in the expo app, but once published to the store I get a blank screen. Everything works great on iOS tho.

**Comment by cngodles** [comment]
I have the same issue as @joshuakaluba . Works just fine in the emulator, however the published app however shows a blank map screen.

```{
    "@expo/vector-icons": "^9.0.0",
    "babel-preset-react-native": "^2.1.0",
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-elements": "^0.19.1",
    "react-native-vector-icons": "^5.0.0"

**Comment by cngodles** [comment]
That was it for me. Once I added the Google Play console SHA-1 certificate fingerprint to the API key and the OAuth 2.0 client ID under the Google Cloud Console API for the project, things started working. At first, my sign-in did not work, and second my maps would not show.

When you are deploying to Google Play (and you are a first timer like me), they ask you if they can sign the app for you. I chose yes, but I did not know that meant I had to apply those keys to the Google Cloud Console for them to be accepted. It makes perfect sense now, but it was very confusing when it happened.

**Comment by lemonjp** [comment]
For me, when I add "Google Maps Android API" then it's works fine as expect on android.
[Deploying to a standalone app on Android](https://docs.expo.io/versions/latest/sdk/map-view/#deploying-to-a-standalone-app-on-android)

**Comment by logesssh** [comment]
enable the api map will load

**Comment by gogogous88** [comment]
guys, I solved the problem with following steps

Describe what was my problem:

expo client in Genymotion - Google Map working!
expo build:android - manually download(not from play store) and install in any android device - working!

HOWEVER, app download from playstore - google map - blank screen.......(not working)

Here is how I solved my problem:

there is a mistake of expo fetch:android:hashes, it give me a WRONG SHA-1 Fingerprint....

Do use adb logcat(https://developer.android.com/studio/command-line/logcat) 

open the playstore downloaded app and debugging your app and by going into the map -it will show you the correct SHA-1 Fingerprint.... as following:

`2019-05-27 12:33:18.736 30552-30801/? E/Google Maps Android API: Authorization failure. Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map. 2019-05-27 12:33:18.737 30552-30801/? E/Google Maps Android API: In the Google Developer Console (https://console.developers.google.com) Ensure that the "Google Maps Android API v2" is enabled. Ensure that the following Android Key exists: API Key: AIzaSyA4FDPR8y6yAPhF30kyff_B3VK0mxxxeeSU Android Application (<cert_fingerprint>;<package_name>): 13:2B:AA:09:E1:xx:xx:41:B8:59:C3:A4:xx:xx:23:63:C0:B9:D7;com.<yourbundle>.<name>`

******* 13:2B:AA:09:E1:xx:xx:41:B8:59:C3:A4:xx:xx:23:63:C0:B9:D7 **** instead of the fetch:android:hashes give me is the right Sha1 Fingerprint....Please do log the reason why it not work~
--
