### ISSUE TITLE
Expo-AV - App Crashes with useNativeControls after iOS Update to Version 17.2

### ISSUE THREAD

**Issue by joaolenosi** [expo/expo#25938]
### Summary

Hello Expo team,

I would like to report an issue that occurred after updating iOS to version 17.2. When using the Expo-AV library and enabling the useNativeControls command in a Video component, the application crashes when trying to navigate to any screen. Removing useNativeControls resolves the problem.

Here is a code snippet illustrating the issue:

`<Video
    ref={post_url_video}
    style={{ width: '100%', height: heightScreen-350, minHeight: heightScreen-350, maxHeight:  heightScreen-350 }}
    source={{ uri: data?.post_url_video }}
    useNativeControls // This command causes the crash
    resizeMode={ResizeMode.COVER}
    shouldPlay={false}
    isMuted={false}
    isLooping
    onPlaybackStatusUpdate={(status) => setStatus(() => status)} 
/>
`

This problem was not present in previous iOS versions.

Additional information:

    iOS Version: 17.2
    Expo-AV Version: ~13.4.1

I appreciate it if you could investigate and provide a solution.

Best regards,

### What platform(s) does this occur on?

iOS

### SDK Version

49.0.9

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22631
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8815526
    npmPackages:
      expo: ^49.0.9 => 49.0.9
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: managed

### Minimal reproducible example

`<Video
    ref={post_url_video}
    style={{ width: '100%', height: heightScreen-350, minHeight: heightScreen-350, maxHeight:  heightScreen-350 }}
    source={{ uri: data?.post_url_video }}
    useNativeControls // This command causes the crash
    resizeMode={ResizeMode.COVER}
    shouldPlay={false}
    isMuted={false}
    isLooping
    onPlaybackStatusUpdate={(status) => setStatus(() => status)} 
/>
`

**Comment by alanjhughes** [comment]
Hi - can you provide a minimal project that demonstrates the issue you are seeing? An example using the component it not enough. You say this happens on navigating? Are you using react navigation or expo router? Answering these questions is best done through a small demo.

Also, I have tested this. iOS 17, expo router, using your example component usage and I cannot reproduce.

**Comment by erxclau** [comment]
@alanjhughes I filed the same issue in #25713 with a repro

**Comment by veljkoph** [comment]
same here, app crashes without any error message after screen change, without useNativeControls, everything works

**Comment by sethgw** [comment]
this is happening to me too.

**Comment by Elue-dev** [comment]
happening to me too

**Comment by alanjhughes** [comment]
Hi

This was an issue in react-native-screens. It was fixed [here](https://github.com/software-mansion/react-native-screens/pull/1969) and will be included in expo go when SDK 50 comes out of beta. Until then, you can build a dev client and install react-native-screens 3.28.0 or above to resolve the issue.

**Comment by Elue-dev** [comment]
> Hi
> 
> 
> 
> This was an issue in react-native-screens. It was fixed [here](https://github.com/software-mansion/react-native-screens/pull/1969) and will be included in expo go when SDK 50 comes out of beta. Until then, you can build a dev client and install react-native-screens 3.28.0 or above to resolve the issue.

i did that earlier, i upgraded react-native-.screens package it did not solve my issue tho...

**Comment by alanjhughes** [comment]
@Elue-dev are you using expo go?

**Comment by Elue-dev** [comment]
> @Elue-dev are you using expo go?
> 
> 

yes but it also happens on test flight

**Comment by alanjhughes** [comment]
Expo go is a playground app, for prototyping, testing and learning, not for building your project. For that, we recommend creating a dev client. If you are using `react-native-screens` 3.28.0 or 3.29.0 and still have the issue, then you will need to report the issue to them https://github.com/software-mansion/react-native-screens

**Comment by alanjhughes** [comment]
@Elue-dev - I would suggest creating a dev client, updating to the latest react-native-screens, and if you can still reproduce the issue, report it to them
