### ISSUE TITLE
expo-router: Drawer opens by itself on first load of app

### ISSUE THREAD

**Issue by JorensM** [expo/expo#26415]
### Minimal reproducible example

https://gist.github.com/JorensM/9d68d069353aec1bb66f93776c8941d2

### Summary

When I use the `Drawer` component from `expo-router/drawer`, the drawer opens up automatically on its own upon the first load of the app and then immediately closes.

Below is a video demonstrating the issue:

https://github.com/expo/expo/assets/17122123/26c6f40c-17ad-45ae-98ca-eedccc2489a3

This happens both on Android and web. Haven't tested for iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.8.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 30, 31, 33
        Build Tools: 30.0.2, 30.0.3
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      expo: ~49.0.15 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

**Comment by jleem99** [comment]
I was having the same problem, but it was resolved once I upgraded to SDK 50.
Perhaps it was fixed in Expo Router v3.

**Comment by marklawlor** [comment]
There's a couple of reasons for this issue with the most typical one being incorrect SafeAreaContext. Can you please try upgrading to SDK 50 and fix your still having the issue reply with a full reproduction. A single file does not provide us enough information to assist you

**Comment by nathanbedford** [comment]
I just reproduced this myself with a brand new project based off an official Expo template from the Expo docs. Hopefully this helps narrow the issue down.

## Minimal reproducible example ##
https://github.com/nathanbedford/expo-drawer-test

This repro example is as simple as I could make it. I followed these steps:

1.  Create a new project using the template [here](https://docs.expo.dev/router/installation/) by running `npx create-expo-app@latest --template tabs@50`
2. Install the Drawer library by following the [instructions here](https://docs.expo.dev/router/advanced/drawer/): `npx expo install @react-navigation/drawer react-native-gesture-handler react-native-reanimated`
3. Simplify the screens in the demo app - remove nested routes and just make the root a Drawer.

## What platform(s) does this occur on? ##
Web

## Did you reproduce this issue in a development build? ##
No - web-only

## Summary ##
As you can see in the video, the drawer starts in the 'open' position as soon as the app first loads and then retracts quickly, every time, regardless of route.

This only happens on Web, not iOS or Android.

https://share.cleanshot.com/G8Jbh8Xr

## Environment ##

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.15
      expo-router: ~3.4.8 => 3.4.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed
```

## Expo Doctor Diagnostrics ##
```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by nathanbedford** [comment]
@marklawlor let me know if you need any other info from me 😁 Appreciate the help!
