### ISSUE TITLE
Location.watchPositionAsync never refreshes

### ISSUE THREAD

**Issue by Xerus2000** [expo/expo#2682]
### Environment

```
[16:38:36] Generating diagnostics report...
[16:38:36] You can join our slack here: https://slack.expo.io/.

  Expo CLI 2.2.5 environment info:
    System:
      OS: Linux 4.14 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.12.1 - /usr/bin/yarn
      npm: 3.5.2 - /usr/bin/npm
    npmPackages:
      expo: ^31.0.2 => 31.0.4 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.2 
    npmGlobalPackages:
      expo-cli: 2.2.5

  Diagnostics report:
|[16:38:43] Request failed with status code 500
[16:38:43] Set EXPO_DEBUG=true in your env to view the stack trace.
```

Target: Android

### Steps to Reproduce

`Location.watchPositionAsync` only reports the position only once, while repeatedly calling `Location.getCurrentPositionAsync` will update the location.

1. Clone https://github.com/Xerus2000/react-native-test
2. Enable High Accuracy GPS on your android phone
3. Run `npm start` and start the app using Expo

### Expected Behavior

location-watch and location-get stay roughly in sync

### Actual Behavior

location-watch never changes while location-get does

### Reproducible Demo

https://github.com/Xerus2000/react-native-test

**Comment by Xerus2000** [comment]
bump

**Comment by DanNoQuarter** [comment]
Am getting same behaviour. Using `distanceInterval` regularly calls handler as expected, but using `timeInterval` only calls once but does not continue.

**Comment by nicgordon** [comment]
Note to others stumbling across this. Even after that fix was merged I still had to pass values to `timeInterval` and `distanceInterval` to get this to work.

**Comment by kokno** [comment]
Hi, For me it's still not working, here is my code : 

`await Location.watchPositionAsync({ accuracy: Location.Accuracy.Balanced, timeInterval: 300, distanceInterval: 1 }, loc => console.log(loc.coords));`

Logging only once and nothing after ...

**Comment by hugomejia** [comment]
@kokno Your code is working for me but only after setting distanceInterval to zero, like this `await Location.watchPositionAsync({ accuracy: Location.Accuracy.Balanced, timeInterval: 300, distanceInterval: 0 }, loc => console.log(loc.coords));` , give it a try!

**Comment by Pat-Gekoski** [comment]
It doesn't matter what time interval I assign, the callback is run one right after the other. For example:
```
try {
            await requestPermissionsAsync();
            await watchPositionAsync({
                accuracy: Accuracy.BestForNavigation,
                timeInterval: 10000000,
                distanceInterval: 20
            }, (location) => {
                console.log(location);
            })
        } catch (e) {
            setErr(e)
        }
```
ran continuously without pause. I had to comment out timeInterval.

**Comment by fender** [comment]
Same here. `timeInterval` doesn't seem to do anything.
