### ISSUE TITLE
[expo-updates] Migrating to `@sentry/react-native` warns about using multiple versions of the "promise" package

### ISSUE THREAD

**Issue by newfylox** [expo/expo#26949]
### Minimal reproducible example

none

### Summary

When migrating from `expo-sentry` to `@sentry/react-native`, Sentry warns this message
```
 WARN  Sentry Logger [warn]: You appear to have multiple versions of the "promise" package installed.
This may cause unexpected behavior like undefined `Promise.allSettled`. Please install the `promise`
package manually using the exact version as the React Native package.
See https://docs.sentry.io/platforms/react-native/troubleshooting/ for more details.
```
Looking my `promise` package installed, it appears that `expo-updates` uses an outdated one
```
my-app@1.0.0 /home/user/my-app
├─┬ expo-updates@0.24.10
│ └─┬ fbemitter@3.0.0
│   └─┬ fbjs@3.0.4
│     └── promise@7.3.1
└─┬ react-native@0.73.2
  └── promise@8.3.0
```
The culprit is here
https://github.com/facebook/fbjs/blob/c47b64a43f307bb8e56bc44215982ab74fd9d150/packages/fbjs/package.json#L70

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Linux Mint 21.3 (Virginia)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      npm: 10.4.0 - ~/.nvm/versions/node/v20.11.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 31, 33, 34
        Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    npmPackages:
      expo: ~50.0.5 => 50.0.5 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    npmGlobalPackages:
      eas-cli: 7.1.2
    Expo Workflow: managed
```

**Comment by pavattt** [comment]
Also experiencing this issue, would be great to hear back from someone.

**Comment by Roilan** [comment]
+1 also experiencing this issue

**Comment by warm--tape** [comment]
+1 also experiencing this issue

**Comment by Trashpants** [comment]
```
myapp@0.0.1 /Users/me/Developer/myapp
├─┬ react-native-web@0.19.10
│ └─┬ fbjs@3.0.5
│   └── promise@7.3.1
└─┬ react-native@0.73.4
  └── promise@8.3.0
  ```
  
Same underlying package but from react-native-web for me,
Tried adding in a resolution as per [sentry docs](https://docs.sentry.io/platforms/react-native/troubleshooting/) 

  ```
   "resolutions": {
    "promise": "^8.3.0"
  },
  ```
  but its made no difference for me (even after removing node_modules and doing a clean npm install)

**Comment by Thaigun** [comment]
Same here, started happening after migrating to Expo 50 and `@sentry/react-native` as per the documentation.

**Comment by sigaits** [comment]
Expo team, do you have any update on this issue?

I contacted Sentry support, and they referred me to this issue. They have a solution for this on their troubleshooting documents, but it won't work. They also suggest manually forcing "package resolution," but that's unacceptable. We have a few apps ready to deploy and are awaiting a solution to this issue.

**Comment by 7kylor** [comment]
Same here. I'm having same issue and tried to solve it using sentry docs [https://docs.sentry.io/platforms/react-native/troubleshooting/#auto-patching-default-behavior](url) **but still persists**

**Comment by anasalaqeel** [comment]
`npm install promise` solved the problem to me

**Comment by 7kylor** [comment]
> This steps solved the problem for me 1 - `npm uninstall promise` 2 - `npm install promise`

Didn't work for me.

**Comment by curtis-ia** [comment]
> This steps solved the problem for me 1 - `npm uninstall promise` 2 - `npm install promise`

This worked for me.

**Comment by sato-daiki** [comment]
I didn't have the 'promise' package installed, but when I used the command below, the bug was fixed.

yarn add promise

**Comment by cha0sg0d** [comment]
> This steps solved the problem for me 1 - `npm uninstall promise` 2 - `npm install promise`

Still having this problem

**Comment by anasalaqeel** [comment]
@cha0sg0d ok then the next step should fix it:- 
1 - npm uninstall promise
2- npx expo install @sentry/react-native@5.20.0 

Note: the second step will update the sentry to the latest version they have fixed this problem, but Expo still has not included this version as expo compatible package and you will have a warning from expo when you install this version but I just install it and ignored the expo warning because it just works without any issue.

**Comment by cha0sg0d** [comment]
> @cha0sg0d ok then the next step should fix it:- 1 - `npm uninstall promise` 2- `npx expo install @sentry/react-native@5.20.0 `
> 
> Note: the second step will update the sentry to the latest version they have fixed this problem, but Expo still has not included this version as expo compatible package and you will have a warning from expo when you install this version but I just install it and ignored the expo warning because it just works fine without any issue.

Thanks for the response! I did these steps and re-built my development build and am still getting the warning :(

**Comment by anasalaqeel** [comment]
@cha0sg0d try to clear the cache and remove the node_modules folder and .expo folder and package-lock.json and re-run npm install

**Comment by Naveen-g09** [comment]
anything works?
am getting?
![image](https://github.com/expo/expo/assets/76151123/eb9672da-1652-428b-b988-d6fa8b8e4849)

**Comment by Naveen-g09** [comment]
guys remove expo-permissions, it is deprecated and add
```yarn add promise```
it fixed for me

**Comment by ggchicote-awg** [comment]
> This steps solved the problem for me 1 - `npm uninstall promise` 2 - `npm install promise`

This solve the problem in my case! Thanks!

**Comment by sibermaindev** [comment]
Still getting this error. How do i solve this? this is Expo SDK 51 with all required packages up to date


$ npm ls promise
plm_mobile@1.6.6 C:\Users\devel\Documents\CODE\plm_mobile\plm_mobile
├─┬ expo-updates@0.25.11
│ └─┬ fbemitter@3.0.0
│   └─┬ fbjs@3.0.5
│     └── promise@7.3.1
└─┬ react-native@0.74.1
  └── promise@8.3.0

**Comment by bocarw121** [comment]
> This steps solved the problem for me 1 - `npm uninstall promise` 2 - `npm install promise`

This worked for me, Thank you!

**Comment by iatanasov37** [comment]
I'm bumping this issue as recently we've found out that the "[fbemitter](https://github.com/facebookarchive/emitter)" package is likely archived by Meta. The package has a custom license too, which may be outdated.

A long-term solution would be to replace the "fbemitter" with the emitter that react-native exposes in `react-native/Libraries/vendor/emitter/EventEmitter`, which has an MIT license.
