### ISSUE TITLE
[expo-screen-orientation][expo 50] Cutting the screen in half sometimes

### ISSUE THREAD

**Issue by Kubessandra** [expo/expo#27228]
### Minimal reproducible example

Did not manage to reproduce it each time.

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Only on iOS
Version: expo50
yarn install --check, reporting no issue

I'm having a hard time reproducing the bug, but sometimes when I switch from LANDSCAPE_LEFT to PORTRAIT_UP or the other way around, the screen is cut in half and I need to rotate the phone or background/foreground.
Looking like the size of the screen is not correct.

Same bug (They are on older version)
https://github.com/expo/expo/issues/17724
https://github.com/expo/expo/issues/17700

## Hook used:
```ts
import { trackError } from "@Helpers/trackError";
import * as ScreenOrientation from "expo-screen-orientation";
import { useCallback, useEffect } from "react";

interface UseScrnOrientationProps {
  pathname: string;
}

const landscapeScreens = ["/live", "/recap"];

export const useScreenOrientation = (props: UseScrnOrientationProps): void => {
  const { pathname } = props;

  const changeScreenOrientation = useCallback(async (): Promise<void> => {
    await ScreenOrientation.unlockAsync();
    if (landscapeScreens.some((name) => pathname.includes(name)))
      await ScreenOrientation.lockAsync(
        ScreenOrientation.OrientationLock.LANDSCAPE
      );
    else
      await ScreenOrientation.lockAsync(
        ScreenOrientation.OrientationLock.PORTRAIT_UP
      );
  }, [pathname]);

  useEffect(() => {
    changeScreenOrientation().catch((e) => trackError(e));
  }, [changeScreenOrientation]);
};
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 4.0.1 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 10.4.0 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.7 => 50.0.7
      expo-router: ~3.4.7 => 3.4.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.9
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by brentvatne** [comment]
can you provide a video recording that demonstrates the issue?

**Comment by Kubessandra** [comment]
Updated the repo with example

**Comment by nicolaslair** [comment]
Any news on this? Thks in advance

**Comment by Kubessandra** [comment]
@brentvatne can we reopen the issue now that we have more information and a reproduction please.

**Comment by Kubessandra** [comment]
We found a workaround by adding a timeout of 100 before doing the rotation.

**Comment by dziekan30** [comment]
> We found a workaround by adding a timeout of 100 before doing the rotation.

Yep that works for me, it's not breaking anymore.

**Comment by dani-mp** [comment]
@brentvatne I'm experiencing this as well, there are a bunch of related issues open in different repositories.
- https://github.com/react-navigation/react-navigation/issues/10966
- https://github.com/software-mansion/react-native-screens/issues/1738
- https://github.com/software-mansion/react-native-screens/issues/1341

It seems there's a PR fixing it, but it's not moving forward: https://github.com/software-mansion/react-native-screens/pull/1970.

**Comment by dani-mp** [comment]
In case folks are fighting with this, I could have a non-buggy and consistent behavior using stacks with different orientations (some landscape, some portrait) using React Navigation's `orientation` screen prop. I'm developing a game and some stacks must be always in landscape, and the rest (login, onboarding, settings, and so on) are always portrait. When I tried implementing this with `expo-screen-orientation`, it was buggy.

**Comment by JacobJaffe** [comment]
@dani-mp could you share your structure for making this work with using the `orientation` setting? 

I'm using a native-stack, and am seeing this behavior when using the navigation option to control `orientation: "portrait"` + `orientation: "landscape"` on screens.

**Comment by dani-mp** [comment]
I'm using expo router with nested layouts.

The app/_layout has a native stack with orientation landscape, and one of the routes of that stack (which is another stack) has orientation portrait.

Showing the portrait stack from the home screen works kind of well, but when the portrait stack is dismissed, it does like a double rendering/animation, super ugly. The first time you can see the screen cut in half and then it _corrects itself_ with a second pass and the end result is good.

I still have to put time into trying to solve the double animation issue because it's super ugly, but at least our users never end up with a cut screen right now.

**Comment by JustJoostNL** [comment]
I still experience this bug, like half of the time when I rotate my screen to landscape, the right half of the screen is just cut off. Experiencing this on iOS.

Any things I can try?

**Comment by karaoku** [comment]
Yes, same problem

**Comment by aliceni81** [comment]
I'm facing the same problem. Any fix will come?

**Comment by Kubessandra** [comment]
Why did we close the issue can we reopen it please ?

**Comment by karaoku** [comment]
When I removed the use of ScreenOrientation.getOrientationAsync() the problem was solved.

**Comment by JustJoostNL** [comment]
@aliceni81 which version of expo and expo screen orientation are you using now, and where you using before? I am on the latest version and the problem still occurs for me.

**Comment by aliceni81** [comment]
@JustJoostNL "expo": "^52.0.25",
    "expo-screen-orientation": "^8.0.4",

**Comment by JustJoostNL** [comment]
I use:
`"expo-screen-orientation": "~8.0.4",`
`"expo": "^52.0.27",`

When I turn my screen, it is still cut in half.

**Comment by aliceni81** [comment]
@JustJoostNL https://github.com/expo/expo/blob/sdk-52/packages/expo-screen-orientation/CHANGELOG.md
8.0.3 — 2025-01-08
🐛 Bug fixes
[iOS] Fixed ScreenOrientation.addOrientationChangeListener() Freezes iOS Devices in Expo SDK 52, issue 33853 (https://github.com/expo/expo/pull/33867 by [@pjdemers](https://github.com/pjdemers)

**Comment by JustJoostNL** [comment]
That issue was that the app would freeze. I also experienced that, and that is indeed solved now. But that freezing issue is different from the screen cutting in half, which still happens for me.

**Comment by aliceni81** [comment]
My case is the screen cuts in half and then extends to the full screen very quickly. Are you experiencing this?

**Comment by JustJoostNL** [comment]
No, the screen cuts in half and it stays like that.

**Comment by aliceni81** [comment]
I don't have the same issue as yours. I'm using bare react native 0.76.6.

**Comment by ameesme** [comment]
We've had reports of users experiencing the same thing on iOS 17.6.1, but not on versions beyond 18. We are using Expo version 51.0.14 (will soon upgrade to 52).
