### ISSUE TITLE
SSE aka. Server Sent Events are blocked by Expo CdpInterceptor

### ISSUE THREAD

**Issue by MartinHarkins** [expo/expo#27526]
### Minimal reproducible example

https://github.com/MartinHarkins/expo-sse-patch

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

[Server Sent Events (whatwg)](https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events) / SSE / EventSource are not getting through while app is in **debug** variant.

After investigating, that is due to two issues.
1. expo-modules-core's [ExpoRequestCdpInterceptor.kt](https://github.com/expo/expo/blob/5bd5d1695f932b8448950bb5d927a06bca27547c/packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/devtools/ExpoRequestCdpInterceptor.kt#L57)
2. react-native's flipper integration within MainApplication => https://github.com/facebook/react-native/issues/28835

This bug report isn't about #2, but it's important to take note of it in order for you to reproduce the problem within the expo codebase.

## The problem
[ExpoRequestCdpInterceptor.kt](https://github.com/expo/expo/blob/5bd5d1695f932b8448950bb5d927a06bca27547c/packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/devtools/ExpoRequestCdpInterceptor.kt#L57)
 tries to read the response body using `response.peekBody(MAX_BODY_SIZE)` , however, in the case of an SSE stream, the body is of type Stream, and therefore cannot be peeked that way.

I've linked to a reproduce repo (https://github.com/MartinHarkins/expo-sse-patch), which hopefully allows for clear steps in reproducing the problem.

## The solution
SSE expects the content type `text/event-stream` coming from the server.

The code should check the content type before trying to pull out the body information to send to the Chrome Dev Tools.

Essentially a most basic patch could consist of (which is what I did):
```diff
- if (response.peekBody(ExpoNetworkInspectOkHttpNetworkInterceptor.MAX_BODY_SIZE + 1).contentLength() <= ExpoNetworkInspectOkHttpNetworkInterceptor.MAX_BODY_SIZE) {
+ if (response.body?.contentType()?.type == "text" && response.body?.contentType()?.subtype == "event-stream") {
+      // do nothing for now
+ } else if (response.peekBody(ExpoNetworkInspectOkHttpNetworkInterceptor.MAX_BODY_SIZE + 1).contentLength() <= ExpoNetworkInspectOkHttpNetworkInterceptor.MAX_BODY_SIZE) {
     val params2 = ExpoReceivedResponseBodyParams(now, requestId, request, response)
     dispatchEvent(Event("Expo(Network.receivedResponseBody)", params2))
  }
```

Note that okhttp's implementation for SSE, is more brazen with reading the body (https://github.com/square/okhttp/blob/master/okhttp-sse/src/main/kotlin/okhttp3/sse/internal/RealEventSource.kt):

```kotlin
val body = response.body

      if (!body.isEventStream()) {
        listener.onFailure(
          this,
          IllegalStateException("Invalid content-type: ${body.contentType()}"),
          response,
        )
        return
      }

// with isEventStream being declared like that:
private fun ResponseBody.isEventStream(): Boolean {
    val contentType = contentType() ?: return false
    return contentType.type == "text" && contentType.subtype == "event-stream"
  }
```

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      npm: 10.5.0 - ~/.nvm/versions/node/v20.10.0/bin/npm
    npmPackages:
      expo: ~50.0.11 => 50.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.2.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by maurobalbi** [comment]
Can confirm, this fixes the problem!

**Comment by sli-rbi** [comment]
can confirm it worked! Thank you so much [MartinHarkins](https://github.com/MartinHarkins)

**Comment by chvanlennep** [comment]
Also I can confirm this was an issue for our android debug builds, and this patch fixes the issue. Thank you @MartinHarkins!

**Comment by etler** [comment]
This bug is fixed on the recently released [Expo 51](https://expo.dev/changelog/2024/05-07-sdk-51)!

We've been dealing with this bug for a while now and I was recently trying to debug it in depth, so I also created a repro project. After finding your issue I was able to fix it on my repro project as well, but I was confused why the flipper patch was needed as I saw that [flipper was removed from expo](https://github.com/expo/expo/pull/26581) in my research. After looking a bit closer, I realized that it was actually merged slightly after [Expo 50](https://expo.dev/changelog/2024/01-18-sdk-50) came out (Expo 50 came out Jan 18th 2024, the PR was merged Jan 22nd 2024), so I figured I'd need to upgrade everything.

Turns out that not only does Expo 51 fix the need for the Flipper patch, it also fixes the expo issue as well, so no modifications are needed anymore. You can check it out in on the [Expo 51 upgrade branch on my reproduction project](https://github.com/etler/expo-dev-fetch-delay-repro/tree/expo-51).

Ironically I initialized my reproduction project the day before Expo 51 so I narowly missed it simply being fixed when I started the new project.

**Comment by thomasdierickx** [comment]
Both solutions did not work for me.. The first one worked only for production and the second for neither. I am working with an Android Emulator and this topic is the only thing i find regarding the problem. When using `Expo 48` both environments worked but as soon as i upgraded to `Expo 50`, playtime was over and development environment started to fail at connecting. 

### Environment

-     "expo": "^50.0.17",
-     "react": "18.2.0",
-     "react-dom": "18.2.0",
-     "react-native-event-source": "1.1.0",
-     OS: MacOS Ventura 13.5

I hope someone can help me! Thanks in advance!

**Comment by DeTrinh** [comment]
Hi @etler I upgraded expo to Expo 51 but still have this problem. Are you sure this bug was fixed in Expo 51? Correct me if I'm missing anything

**Comment by etler** [comment]
@DeTrinh I tried again and it looks like it's only half fixed. When I was testing it, I was using the same command to start an expo dev build as the one in @MartinHarkins repo, which is `expo run:android`. I did that in both my repo and Martin's repo on Expo 50 and it did not work, and after upgrading to Expo 51 it worked on both my emulator and on my phone. I figured it didn't work on 50, and it worked on 51, problem solved.

Turns out it's not completely solved. I tried again but this time also did a build file using eas as well. When using a build from `eas build` it didn't work and reverted to the old behavior.

On both our repro repos we were building dev builds without eas and when I ran `eas build` for the first time, it required me to add `"expo-dev-client": "~4.0.15"`. The build with that dependency failed, and also, when I re-ran `expo run:android` it now also failed, and continued to fail until I removed the `expo-dev-client` dependency.

Running `expo run:android` without the `expo-dev-client` dependency still provides development functionality like hot reloading, but upon closer inspection, it's providing dev features with the standard react native dev mode. With `expo-dev-client` installed, it overrides the standard dev mode and adds some features like the expo server select menu, the fancier dev menu, and hot reload over the network with the expo server as opposed to needing to be connected over usb. But, `expo-dev-client` breaks streaming while the react native core dev mode does not.

Previously both dev modes broke streaming, meaning the underlying issue was fixed in the core expo dev mode, and broke in `expo-dev-client`. I'm trying to figure out what exactly the discrepancy is at this point. As @MartinHarkins pointed out, react native's flipper integration was causing the same issue in the core react native dev mode. [Expo has since removed flipper from its usage of the core react native dev tools](https://github.com/expo/expo/pull/27234), which I think was likely the change that fixed streaming in `expo run:android` and that change was released in Expo 51.

Martin also pointed out that there was a second problem causing the same issue in `expo-modules-core`. [Looking at the updated code as of the publish of `expo-dev-client@4.0.15`](https://github.com/expo/expo/blob/82b5a4a7ada98ca26cd99d097400b01240cbcf99/packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/devtools/ExpoRequestCdpInterceptor.kt), it no longer has the `peekBody` call, so it appears that that should also be fixed now as that's specifically what Martin's patch corrected. So it appears, that the 2 underlying issues that Martin pointed out and provided patches for are both fixed in Expo 51, but now there's a new bug somewhere else that's not in the expo core modules package and is instead specifically relegated to `expo-dev-client`!

To narrow it down, I went back and tried @MartinHarkins repro again on Expo 50, and this time I tried it with and without `expo-dev-client` and it worked in both cases. That must mean that somewhere between `expo-dev-client@3.3.12` for Expo 50 and `expo-dev-client@4.0.0` for Expo 51, something was added that broke streaming.

So what seems to be going on is that the 2 issues @MartinHarkins identified in expo core in this issue were fixed, but a new regression got added to `expo-dev-client` that broke it again! The expo team needs to be aware of this issue on dev, and add tests for this to their CI platform, otherwise we'll be playing whack-a-mole trying to fix dev streaming when it can randomly regress and resurface in a new part of the codebase from one version of Expo to the next.

**Comment by etler** [comment]
I dug a little deeper and found a new fix for Expo 51! If you just want a new fix, you can check out [my fork branch here](https://github.com/etler/expo-sse-patch/tree/expo-51-fix). If you want a very deep dive into the issue, read on.

The `peekBody` call that was causing issues before was specifically removed in [this commit that removed it to add gzip support to CDP](https://github.com/expo/expo/commit/f4416ebd6e6b10581c6a51c484df2f81cde3d65f). It was removed from `ExpoRequestCdpInterceptor` to leave the body untouched for the gzip decompression. A peek was added at the same time to `ExpoNetworkInspectOkHttpNetworkInterceptor` to check the body size and short circuit if it is too large.

In the old version [`response.peekBody()`](https://square.github.io/okhttp/5.x/okhttp/okhttp3/-response/index.html#1341446055%2FFunctions%2F1481842020) was being called on the `Response` object on [this line](https://github.com/expo/expo/commit/f4416ebd6e6b10581c6a51c484df2f81cde3d65f#diff-70eb71b289084ba6c28430a4840325367e45875b4fb1bc30caedf7448b5c7281L57). Because `peekBody` is a syncronous function and takes `byteCount` it waits and blocks the thread until the number of bytes is reached and returns a `ResponseBody` preventing any other networking code on that stream from running while it's waiting. Since it it was peeking for `MAX_BODY_SIZE` bytes which was a megabyte, that meant if you were not expecting a large amount of data, it would block onto the entire stream until 1mb was transfered.

In the new version, instead of `peekBody`, [`response.body.source().peek()`](https://square.github.io/okio/3.x/okio/okio/okio/-buffered-source/index.html#244038234%2FFunctions%2F-1473893935) is being called [here](https://github.com/expo/expo/commit/f4416ebd6e6b10581c6a51c484df2f81cde3d65f#diff-e7c9344e26708470892af8b39408ec4c0cea722708cf8459f152a4732b0c94fbR103-R104). This is an improvement because `peek` is not a blocking call because the return value is a new stream that receives copied data from the `body.source` so it is returned immediately. The problem is that right after that new source stream is created, [`peeked.request()`](https://square.github.io/okio/3.x/okio/okio/okio/-buffered-source/index.html#325498883%2FFunctions%2F-1473893935) is called on [this line](https://github.com/expo/expo/commit/f4416ebd6e6b10581c6a51c484df2f81cde3d65f#diff-e7c9344e26708470892af8b39408ec4c0cea722708cf8459f152a4732b0c94fbR106) right after and that function *is* blocking. That function returns a boolean when `byteCount` is reached, meaning that in order to return that boolean, it must wait until the full amount of bytes are reached, which again, is 1mb.

As a quick test fix, I branched off @MartinHarkins reproduction repo again, and [simply changed `if (peeked.request(byteCount + 1)` to `if (true)`](https://github.com/etler/expo-sse-patch/blob/expo-51-fix/plugins/withAndroidExpoSSEPatch.ts#L55) to fully short circuit it to remove any syncronously blocking code, and that worked.

So now we know why it broke in Expo 51, but the next question is why did it only break when `expo-dev-client` was installed? Well one clue is that [`ExpoNetworkInspectOkHttpNetworkInterceptor` has `@Suppress("unused")` above it](https://github.com/expo/expo/blob/main/packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/devtools/ExpoNetworkInspectOkHttpInterceptors.kt#L23) meaning it's not being used within `expo-modules-core`. [When I search for it across the code base](https://github.com/search?q=repo%3Aexpo%2Fexpo%20ExpoNetworkInspectOkHttpNetworkInterceptor&type=code), I found references to it in [`expo-dev-launcher`](https://github.com/expo/expo/blob/c957207a30e6abb43f28ec8d09e63b47e9e563eb/packages/expo-dev-launcher/expo-dev-launcher-gradle-plugin/src/main/kotlin/expo/modules/devlauncher/DevLauncherPlugin.kt#L95), [ `expo-network-addons`](https://github.com/expo/expo/blob/c957207a30e6abb43f28ec8d09e63b47e9e563eb/packages/expo-network-addons/expo-network-addons-gradle-plugin/src/main/kotlin/expo/modules/networkaddons/NetworkAddonsPlugin.kt#L114), and [`expo-go`](https://github.com/expo/expo/blob/c957207a30e6abb43f28ec8d09e63b47e9e563eb/apps/expo-go/android/expoview/src/main/java/host/exp/exponent/kernel/KernelNetworkInterceptor.kt#L33).

The main culprit is `expo-dev-launcher`, which is a dependency of `expo-dev-client`. Since `ExpoNetworkInspectOkHttpNetworkInterceptor` is required there, it inherits the bug. The [`expo-network-addons`](https://www.npmjs.com/package/expo-network-addons) module is hardly used and only has 22 weekly downloads so we can ignore it. `expo-go` also requires it, so to confirm the relation, I tested again on expo go, but without `expo-dev-client` installed, and sure enough, it was broken again. I don't really understand how the `MethodVisitor` build code works, but the connection seems to confirm that `ExpoNetworkInspectOkHttpNetworkInterceptor` is only being used in those specific modules.

As for `ExpoRequestCdpInterceptor` where the `peekBody` used to be, [it does not seem to be directly required in the codebase anymore](https://github.com/search?q=repo%3Aexpo%2Fexpo%20ExpoRequestCdpInterceptor&type=code) outside of expo go and `ExpoNetworkInspectOkHttpInterceptors`, so when `expo-dev-client` isn't installed it or expo go isn't being used, it doesn't get run anymore. When looking at the old code, it's imported in [`android/expoview`'s `ExpoNetworkInterceptor.kt`](https://github.com/expo/expo/blob/3142a086578deffd8704a8f1b6f0f661527d836c/android/expoview/src/main/java/versioned/host/exp/exponent/ExpoNetworkInterceptor.kt#L10). I'm not sure how that folder was being used back then, so I'm not sure if that's for sure the requirement from core, but it looks like it.

The solution to all these issues is simply to stop putting blocking calls on network streams! Network streams should never be blocked otherwise you're going to break its consumption, so it needs to be changed to run asyncronously. I need to refresh my memory on how to intercept a stream without blocking in Java but I believe a thread would need to be used in place of or within `peekResponseBody`. If a stream feature is going to break the consumption of a stream, then I think it's worse than not having that feature at all.

**Comment by angelopedroso** [comment]
> I dug a little deeper and found a new fix for Expo 51! If you just want a new fix, you can check out [my fork branch here](https://github.com/etler/expo-sse-patch/tree/expo-51-fix). If you want a very deep dive into the issue, read on.
> 
> The `peekBody` call that was causing issues before was specifically removed in [this commit that removed it to add gzip support to CDP](https://github.com/expo/expo/commit/f4416ebd6e6b10581c6a51c484df2f81cde3d65f). It was removed from `ExpoRequestCdpInterceptor` to leave the body untouched for the gzip decompression. A peek was added at the same time to `ExpoNetworkInspectOkHttpNetworkInterceptor` to check the body size and short circuit if it is too large.
> 
> In the old version [`response.peekBody()`](https://square.github.io/okhttp/5.x/okhttp/okhttp3/-response/index.html#1341446055%2FFunctions%2F1481842020) was being called on the `Response` object on [this line](https://github.com/expo/expo/commit/f4416ebd6e6b10581c6a51c484df2f81cde3d65f#diff-70eb71b289084ba6c28430a4840325367e45875b4fb1bc30caedf7448b5c7281L57). Because `peekBody` is a syncronous function and takes `byteCount` it waits and blocks the thread until the number of bytes is reached and returns a `ResponseBody` preventing any other networking code on that stream from running while it's waiting. Since it it was peeking for `MAX_BODY_SIZE` bytes which was a megabyte, that meant if you were not expecting a large amount of data, it would block onto the entire stream until 1mb was transfered.
> 
> In the new version, instead of `peekBody`, [`response.body.source().peek()`](https://square.github.io/okio/3.x/okio/okio/okio/-buffered-source/index.html#244038234%2FFunctions%2F-1473893935) is being called [here](https://github.com/expo/expo/commit/f4416ebd6e6b10581c6a51c484df2f81cde3d65f#diff-e7c9344e26708470892af8b39408ec4c0cea722708cf8459f152a4732b0c94fbR103-R104). This is an improvement because `peek` is not a blocking call because the return value is a new stream that receives copied data from the `body.source` so it is returned immediately. The problem is that right after that new source stream is created, [`peeked.request()`](https://square.github.io/okio/3.x/okio/okio/okio/-buffered-source/index.html#325498883%2FFunctions%2F-1473893935) is called on [this line](https://github.com/expo/expo/commit/f4416ebd6e6b10581c6a51c484df2f81cde3d65f#diff-e7c9344e26708470892af8b39408ec4c0cea722708cf8459f152a4732b0c94fbR106) right after and that function _is_ blocking. That function returns a boolean when `byteCount` is reached, meaning that in order to return that boolean, it must wait until the full amount of bytes are reached, which again, is 1mb.
> 
> As a quick test fix, I branched off @MartinHarkins reproduction repo again, and [simply changed `if (peeked.request(byteCount + 1)` to `if (true)`](https://github.com/etler/expo-sse-patch/blob/expo-51-fix/plugins/withAndroidExpoSSEPatch.ts#L55) to fully short circuit it to remove any syncronously blocking code, and that worked.
> 
> So now we know why it broke in Expo 51, but the next question is why did it only break when `expo-dev-client` was installed? Well one clue is that [`ExpoNetworkInspectOkHttpNetworkInterceptor` has `@Suppress("unused")` above it](https://github.com/expo/expo/blob/main/packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/devtools/ExpoNetworkInspectOkHttpInterceptors.kt#L23) meaning it's not being used within `expo-modules-core`. [When I search for it across the code base](https://github.com/search?q=repo%3Aexpo%2Fexpo%20ExpoNetworkInspectOkHttpNetworkInterceptor&type=code), I found references to it in [`expo-dev-launcher`](https://github.com/expo/expo/blob/c957207a30e6abb43f28ec8d09e63b47e9e563eb/packages/expo-dev-launcher/expo-dev-launcher-gradle-plugin/src/main/kotlin/expo/modules/devlauncher/DevLauncherPlugin.kt#L95), [ `expo-network-addons`](https://github.com/expo/expo/blob/c957207a30e6abb43f28ec8d09e63b47e9e563eb/packages/expo-network-addons/expo-network-addons-gradle-plugin/src/main/kotlin/expo/modules/networkaddons/NetworkAddonsPlugin.kt#L114), and [`expo-go`](https://github.com/expo/expo/blob/c957207a30e6abb43f28ec8d09e63b47e9e563eb/apps/expo-go/android/expoview/src/main/java/host/exp/exponent/kernel/KernelNetworkInterceptor.kt#L33).
> 
> The main culprit is `expo-dev-launcher`, which is a dependency of `expo-dev-client`. Since `ExpoNetworkInspectOkHttpNetworkInterceptor` is required there, it inherits the bug. The [`expo-network-addons`](https://www.npmjs.com/package/expo-network-addons) module is hardly used and only has 22 weekly downloads so we can ignore it. `expo-go` also requires it, so to confirm the relation, I tested again on expo go, but without `expo-dev-client` installed, and sure enough, it was broken again. I don't really understand how the `MethodVisitor` build code works, but the connection seems to confirm that `ExpoNetworkInspectOkHttpNetworkInterceptor` is only being used in those specific modules.
> 
> As for `ExpoRequestCdpInterceptor` where the `peekBody` used to be, [it does not seem to be directly required in the codebase anymore](https://github.com/search?q=repo%3Aexpo%2Fexpo%20ExpoRequestCdpInterceptor&type=code) outside of expo go and `ExpoNetworkInspectOkHttpInterceptors`, so when `expo-dev-client` isn't installed it or expo go isn't being used, it doesn't get run anymore. When looking at the old code, it's imported in [`android/expoview`'s `ExpoNetworkInterceptor.kt`](https://github.com/expo/expo/blob/3142a086578deffd8704a8f1b6f0f661527d836c/android/expoview/src/main/java/versioned/host/exp/exponent/ExpoNetworkInterceptor.kt#L10). I'm not sure how that folder was being used back then, so I'm not sure if that's for sure the requirement from core, but it looks like it.
> 
> The solution to all these issues is simply to stop putting blocking calls on network streams! Network streams should never be blocked otherwise you're going to break its consumption, so it needs to be changed to run asyncronously. I need to refresh my memory on how to intercept a stream without blocking in Java but I believe a thread would need to be used in place of or within `peekResponseBody`. If a stream feature is going to break the consumption of a stream, then I think it's worse than not having that feature at all.

I clonned your merge, but it doesn't work

**Comment by etler** [comment]
@angelopedroso Do you have more details on the specific steps you followed?

**Comment by MartinHarkins** [comment]
Thanks a bunch @etler, you've saved me tons of time, your patch worked flawlessly for me.

I've updated my repro repo for SDK 51: https://github.com/MartinHarkins/expo-sse-patch, there is still the patch for SDK 50 on branch expo-50

My version of the fix is a bit narrower and hasn't caused me issues:
```diff
// in {projectRoot}/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/devtools/ExpoNetworkInspectOkHttpInterceptors.kt#peekResponseBody

- if (peeked.request(byteCount + 1)) {
+ if (body.contentType()?.type == "text" && body.contentType()?.subtype == "event-stream" || peeked.request(byteCount + 1)) {  
  // When the request() returns true,  
  // it means the source have more available bytes then [byteCount].  
  return null
}
```

It would be great if the SSE use case could be taken into account. Here's the spec: https://html.spec.whatwg.org/multipage/server-sent-events.html, it's actually very light.
@Kudo sorry to bug you, but since you've actually worked on this code in https://github.com/expo/expo/pull/28486, perhaps you might pitch in or bring this up when it's convenient for you guys ?

**Comment by etler** [comment]
@MartinHarkins glad to hear it works on other machines too! Your narrower fix should work for the event stream use case, but it still leaves other requests unstreamed and delayed. SSE is one of the most common ways to stream data over http, but in the case of my company, we actually use streaming line delimited json which is why I just disabled it entirely for our use case as a quick fix for people who do not need the chrome dev tools events.

A proper fix would fix the underlying concurrency problem and provide a fix for all files. On top of the streaming use case it also prevents headers from being received (if I'm remembering correctly from my tests), and it's also pretty common to begin doing work as soon as a header is received before receiving or completing the body.

I believe I know why needs to be done to fix the concurrency issue with a thread or co-routine, but I will need to get the project running locally first and ensure it works with a from scratch build and pass tests to be able to open a PR. In the meanwhile if someone on the expo team could fix this that would be amazing.

**Comment by arthur-fontaine** [comment]
I'm not using my own development build, but Expo Go, and I guess that `ExpoNetworkInspectOkHttpInterceptors` is built into the Expo Go client since it is a native code? So I am stuck until the Expo team fixes the issue?

**Comment by arthur-fontaine** [comment]
Hello, is it possible that there is the same bug on iOS? I didn't manage to receive SSE on iOS, but the same code works on web (not React Native). I don't know Swift, but it seems that the logic implemented in the code linked below is the same that the Kotlin version before the PR #30062. https://github.com/expo/expo/blob/8eece1964f1620841130a5e6806162dde318b5a3/packages/expo-modules-core/ios/DevTools/ExpoRequestInterceptorProtocol.swift#L103

**Comment by brycnguyen** [comment]
> Is it possible that there is the same bug on iOS?
> 
> I didn't manage to receive SSE on iOS, but the same code works on web (not React Native). I don't know Swift, but it seems that the logic implemented in the code linked below is the same that the Kotlin version before the PR #30062.
> 
> https://github.com/expo/expo/blob/8eece1964f1620841130a5e6806162dde318b5a3/packages/expo-modules-core/ios/DevTools/ExpoRequestInterceptorProtocol.swift#L103

I have the same issue on iOS

**Comment by codesmax** [comment]
@arthur-fontaine @brycnguyen In case this helps, I was able to receive SSE on iOS by using the [react-native-sse](https://www.npmjs.com/package/react-native-sse) package. The issue on Android, as documented above, still remains though. I'm using Expo @ 51.0.31, React Native @ 0.74.5, and expo-dev-client @ 4.0.25.

**Comment by gopidon** [comment]
Still doesn't work on iOS Simulator (Expo Go). I am on expo@51.0.37. The message event handler is never called. It's able to open an SSE connection.I can see that in the open message handler. But after that, nothing! Is the fix expected in expo@52? @Kudo

**Comment by arthur-fontaine** [comment]
@gopidon with expo@52, you will be able to use `expo/fetch`. See https://github.com/expo/expo/discussions/21710#discussioncomment-11036387

**Comment by mocon** [comment]
Hello, we are encountering this issue in Expo 51.0.39. Does anyone have a solution for iOS and Android, short of upgrading to Expo 52?

**Comment by arthur-fontaine** [comment]
Hi @mocon , I think you can use xhr as a workaround.

You might want to take a look at the Agrume client (SSE-dependent) we made with my team.

https://github.com/arthur-fontaine/yvees/blob/main/apps%2Fmobile%2Fsrc%2Fshared%2Futils%2Fagrume-sse-client-for-rn.ts#L128-L160

**Comment by mocon** [comment]
Thanks @arthur-fontaine! We are taking a look.
