### ISSUE TITLE
Expo Install Check recommends incompatible version of @react-native-community/datetimepicker

### ISSUE THREAD

**Issue by dnelsonlivecurrence** [expo/expo#27743]
### Summary

Expo Install Check expects version: 7.6.1  of @react-native-community/datetimepicker, however while building on iOS with that version the following error causes the build to fail:

```
❌  (node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m:8:41)

   6 | {
   7 |   if (self = [super init]) {
>  8 |     YGNodeSetMeasureFunc(self.yogaNode, RNDateTimePickerShadowViewMeasure);
     |                                         ^ incompatible function pointer types passing 'YGSize ' (aka 'struct YGSize (struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') to parameter of type 'YGMeasureFunc' (aka 'struct YGSize (*)(const struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') [-Wincompatible-function-pointer-types]
   9 |   }
  10 |   return self;
  11 | }
```

To resolve, please change the expected version of @react-native-community/datetimepicker to 7.6.3

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.5.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.0 - /opt/homebrew/bin/npm
      Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/dannelson/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.13 => 50.0.13 
      react: ^18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.73.5 => 0.73.5 
    npmGlobalPackages:
      eas-cli: 7.1.1
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/dnelsonlivecurrence/my-app-cli-bug

**Comment by byCedric** [comment]
Hi @dnelsonlivecurrence! Thanks for the report. It seems that this is actually an incompatibility with Xcode 15.3, not Expo or React Native: ([issue](https://github.com/react-native-datetimepicker/datetimepicker/issues/866)).

I'll check internally if we can upgrade to this version for SDK 50.

**Comment by dnelsonlivecurrence** [comment]
@byCedric Yes, but that issue was already fixed with @react-native-community/datetimepicker 7.6.3, so Expo Check should be set to expect that version, so Xcode 15.3 can be supported.

**Comment by obayit** [comment]
I am still facing this issue, how can I apply the fix?
My expo version is 50.0.17, but datetimepicker is still 7.6.1

I did `npm upgrade expo` then `pod install` but it did not upgrade the datetime package/pod.

**Comment by AnthonyP128** [comment]
Same Issue here does anyone gave a proper fix

**Comment by raysarebest** [comment]
For me, after manually upgrading `@react-native-community/datetimepicker` to `^7.6.3` in my `package.json` and `npm install`ing, running `npx expo-doctor` flags it as an incompatible version (it had actually resolved to 7.7.0), which suggests I run `npx expo install --check`, and that downgrades me back to 7.6.1. I'm on Expo 50.0.17

**Comment by dnelsonlivecurrence** [comment]
@alanjhughes This issue was closed as fixed, but there have been a few releases since and it's still an issue. Can we get this reopened?

**Comment by MorganDavid** [comment]
same here, upgrading to `7.7.0` and ignoring expo doctor fixes it.

**Comment by ahmadadejumo** [comment]
Same issue here for me has it not being fixed yet ?

**Comment by devalnor** [comment]
+1

**Comment by callmekimbo** [comment]
This issue shouldn't be closed, it's still affecting users who want to build out iOS apps via expo with RNDateTimePicker

**Comment by anand-elumalai-GNBTech** [comment]
we are still facing the issue .

**Comment by callmekimbo** [comment]
Change YGNodeRef to YGNodeConstRef, or via the package.json bump RNDateTimePicker version to 7.6.3 and then run your build.

From: anand-elumalai-GNBTech ***@***.***>
Date: Wednesday, May 15, 2024 at 3:22 AM
To: expo/expo ***@***.***>
Cc: Robert Harry ***@***.***>, Comment ***@***.***>
Subject: Re: [expo/expo] Expo Install Check recommends incompatible version of @react-native-community/datetimepicker (Issue #27743)

we are still facing the issue .

**Comment by the-kamol** [comment]
> @byCedric Yes, but that issue was already fixed with @react-native-community/datetimepicker 7.6.3, so Expo Check should be set to expect that version, so Xcode 15.3 can be supported.

That helped, thank you, man!

**Comment by dnelsonlivecurrence** [comment]
@byCedric @alanjhughes @tsapeta Lots of other people facing this issue still, including myself, can we get this re-opened?

**Comment by alanjhughes** [comment]
@dnelsonlivecurrence  This was fixed yesterday and just needs to be published. You are free to install whatever version of datetimepicker you like. You can ignore the expo doctor warnings

**Comment by obayit** [comment]
Just add a patch to fix the issue "permanently" until you get the fix from expo itself.
I have this patch file:
```
diff --git a/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m b/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m
index c139440..4ff3362 100644
--- a/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m
+++ b/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m
@@ -41,7 +41,7 @@ - (void)setTimeZoneName:(NSString *)timeZoneName {
   YGNodeMarkDirty(self.yogaNode);
 }
 
-static YGSize RNDateTimePickerShadowViewMeasure(YGNodeRef node, float width, YGMeasureMode widthMode, float height, YGMeasureMode heightMode)
+static YGSize RNDateTimePickerShadowViewMeasure(YGNodeConstRef node, float width, YGMeasureMode widthMode, float height, YGMeasureMode heightMode)
 {
   RNDateTimePickerShadowView *shadowPickerView = (__bridge RNDateTimePickerShadowView *)YGNodeGetContext(node);
```

`patch-package` it is a package you can add to your project to apply fix like this automatically. You also have to add this line in `package.json` inside `scripts`:
```
    "postinstall": "patch-package"
```

**Comment by jesseblom** [comment]
Issues still there, please propose a right fix. It's been taking too long.

**Comment by pablaber** [comment]
Having the same issue, but i was able to work around it by upgrading `@react-native-community/datetimepicker` to `7.7.0` and adding the following block to my `package.json` file:

```json
  "expo": {
    "install": {
      "exclude": ["@react-native-community/datetimepicker"]
    }
  },
```

After adding that, running `expo-doctor` no longer complains about `@react-native-community/datetimepicker`

(expo docs for that block found here: https://docs.expo.dev/more/expo-cli/#configuring-dependency-validation)
