### ISSUE TITLE
[@expo/fingerprint] Non-deterministic output (expoAutolinkingAndroid:config)

### ISSUE THREAD

**Issue by ColinHmrl** [expo/expo#27839]
### Minimal reproducible example

no need

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Hello Expo team, 
I've found out about 2 issues around the fingerprint generation.

## Issue 1: Inconsistancy during local devClient build

when building a local devClient using eas build --local, the fingerPrint is never the same, how could i save the fingerprint detail generated during the resolve process at build time ?

``` log
[CONFIGURE_EXPO_UPDATES] Runtime version from the app config evaluated on your local machine (a813b709509cd8a79f43dae7414cb3144a90a832) does not match the one resolved here (51c3ff46c8233b6e3bb1459612df4b0c928a6728). 
```
51c3ff46c8233b6e3bb1459612df4b0c928a6728 is never the same

## Issue 2: Fingerprint is different between env (local and github action).

When using fingerprint as runtimeVersion i got this difference between local and github action. 

``` json
 {
    "type": "contents",
    "id": "expoAutolinkingConfig:android",
    "contents": {"extraDependencies":{"androidMavenRepos":[],"iosPods":{}},"modules":[{"packageName":"expo","packageVersion":"50.0.14","projects":[{"name":"expo","sourceDir":"node_modules/expo/android"}],"modules":[]},{"packageName":"expo-application","packageVersion":"5.8.3","projects":[{"name":"expo-application","sourceDir":"node_modules/expo-application/android"}],"modules":["expo.modules.application.ApplicationModule"]},{"packageName":"expo-constants","packageVersion":"15.4.5","projects":[{"name":"expo-constants","sourceDir":"node_modules/expo-constants/android"}],"modules":["expo.modules.constants.ConstantsModule"]},{"packageName":"expo-dev-client","packageVersion":"3.3.11","projects":[{"name":"expo-dev-client","sourceDir":"node_modules/expo-dev-client/android"}],"modules":[]},{"packageName":"expo-dev-launcher","packageVersion":"3.6.9","projects":[{"name":"expo-dev-launcher","sourceDir":"node_modules/expo-dev-launcher/android"}],"plugins":[{"id":"expo-dev-launcher-gradle-plugin","group":"expo.modules","so ... 
    reasons: [ 'expoAutolinkingAndroid' ],
    hash: '631600f8f9511ff67b32b909d1573fbf9978b66d'
  }
```

difference is in expoAutolinkingConfig:android content within the following properties (sourceDir):
```json
{
    "extraDependencies": {
        "androidMavenRepos": [
        ],
        "iosPods": {
        }
    },
    "modules": [
        {
//...

            "modules": [
            ],
            "packageName": "expo-dev-launcher",
            "packageVersion": "3.6.9",
            "plugins": [
                {
                    "group": "expo.modules",
                    "id": "expo-dev-launcher-gradle-plugin",
                    "sourceDir": "/home/node/workspace/node_modules/expo-dev-launcher/expo-dev-launcher-gradle-plugin" <-- sourceDir shouldn't be an absolute path
                }
            ],
            "projects": [
                {
                    "name": "expo-dev-launcher",
                    "sourceDir": "node_modules/expo-dev-launcher/android"
                }
            ]
        },
//...
        {
            "modules": [
                "expo.modules.updates.UpdatesModule"
            ],
            "packageName": "expo-updates",
            "packageVersion": "0.24.12",
            "plugins": [
                {
                    "group": "expo.modules",
                    "id": "expo-updates-gradle-plugin",
                    "sourceDir": "/home/node/workspace/node_modules/expo-updates/expo-updates-gradle-plugin" <-- same here
                }
            ],
            "projects": [
                {
                    "name": "expo-updates",
                    "sourceDir": "node_modules/expo-updates/android"
                }
            ]
        },
``` 

as  we can see, the sourceDir is an absolute path and when executed in different machine/environment, this leads to a different hash because of the difference in wokring space. 

Colin

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 20.11.1 - /usr/local/bin/node
      Yarn: 4.1.0 - /usr/local/bin/yarn
      npm: 10.5.0 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 33.0.1, 34.0.0
    npmPackages:
      expo: ^50.0.14 => 50.0.14 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.3.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by ColinHmrl** [comment]
Hi @wschurman, expo-bot just closed it, do you really need a reproducible example ?

Also, can you give me hint for the issue 1 about logging the fingerprint detail during build time ? 

Colin

**Comment by wschurman** [comment]
Thanks for the report! No need for a repro.

**Comment by wschurman** [comment]
https://github.com/expo/expo/commit/b9b5352042b00b4528ec188488447841076bdec5 should fix this, and it will be released with SDK 51. It can be tested earlier with canaries but stability of canary releases is not guaranteed.

**Comment by vonkanehoffen** [comment]
So this solves the issue for me when generating fingerprints locally in different dirs @wschurman , but I'm still seeing mismatches between fingerprints in [my EAS builds](https://expo.dev/accounts/liftshare/projects/mobilityways-app/builds/8a5da39e-4697-4e6d-9d79-3c12925b2e34) when I set
```
    "runtimeVersion": {
      "policy": "fingerprint"
    },
```
This is with `"@expo/fingerprint": "^0.9.0",`

Could EAS be using the old version of the package internally or something?

**Comment by giorgiofellipe** [comment]
@wschurman I'm still facing it, running build build locally is always generating different hashes.

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.2.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.7.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 26, 29, 30, 31, 32, 33, 34
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^11.0.8 => 11.0.8 
      expo: ~51.0.17 => 51.0.17 
      expo-router: ^3.5.15 => 3.5.15 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.6 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.2.0
    Expo Workflow: managed
```

```
    "@expo/fingerprint": "^0.10.0",
    "expo-updates": "~0.25.18",
```

Am I missing something?
Thanks in advance.
