### ISSUE TITLE
Custom Sound for Expo Push Notifications Only Works in Foreground

### ISSUE THREAD

**Issue by waelbenmustapha** [expo/expo#27978]
### Minimal reproducible example

https://github.com/waelbenmustapha/pushNotifIssue

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I'm developing an app with Expo and facing an issue with push notifications where the custom sound only plays when the app is in the foreground. When the app is backgrounded or closed, the notifications default to the system sound instead of the custom sound I've specified also it uses miscellaneous channelId. I can't understand why it's different in the background than in the foreground , the version im testing is an apk production build. I'm using Expo's managed workflow and sending notifications through their backend (expo-server-sdk). Here's how I configure the notification channel on the frontend:

```
await Notifications.setNotificationChannelAsync("ltsChannel", {
  name: "ltsChannel",
  sound: "sound.wav", // Custom sound file
  importance: Notifications.AndroidImportance.MAX,
  audioAttributes: {
    usage: Notifications.AndroidAudioUsage.ALARM,
    contentType: Notifications.AndroidAudioContentType.SONIFICATION,
  },
});
```
And this is how I send notifications from the backend:

```
const messages = [];
messages.push({
  to: pushToken,
  sound: 'default',
  title: 'Test Title',
  body: 'Test Body',
  channelId: "ltsChannel",
});
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10811636
    npmPackages:
      expo: ~50.0.14 => 50.0.14
      react: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions 
for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by douglowder** [comment]
@waelbenmustapha I have forked your test repo, and built the Android app. Do you have working credentials so I can log in? Otherwise, we would need a more minimal repo that does not have a dependency on your service.

**Comment by collinahn** [comment]
i have the same experience, in my case it seems the problem is caused by absence of channelId when app is background or killed.
I have faced this issue in expo 50 and expo 51 and not sure it is related to FCMv1.(started building app only using FCMv1.)

even though I managed to send correct channelId with expo notification sdk, the installed app doesn't seem to work with correct channelId when app is foreground. Tested with multiple devices and it works fine when app is foreground. so i guess it is not server's fault

when entered notification setting of the app, i encountered "기타" channel which means other or etc, can't tell the exact name since it kept showing that however i tried to change language setting to english.
on foreground push message received, it goes to "default" channel that i have setup on start, otherwise it goes to "기타" channel

**Comment by Mirthis** [comment]
Having a possible related problem here.
If I send a push notification when my app is in foreground the channel is respected and the corresponding settings are used.
If the app is in the background or closed the notification ends up in a newly created "Miscellaneous" channel (id: fcm_fallback_notification_channel) resulting also in the notification not showing my app icon.
I'm using expo 50.

**Comment by Krucial92** [comment]
@Mirthis having exactly the same issue, just wasted hours trying to figure out what's going on. I have correctly configured a channel and whenever I send to this channel (even via the online expo push notification tool: https://expo.dev/notifications) it still goes to the miscellaneous channel. I've seen other recent threads popping up online, seems like there is a bug/regression here which needs to be looked into cc @douglowder

**Comment by Krucial92** [comment]
Update on this, I have just found that it goes into my "general" channel whenever I send a push notification and the app is OPEN, however if the app is closed, in foreground, or phone is locked then the same push notification I am sending ends up in the miscellaneous channel. Any reason why this happens?

**Comment by ericlyoung** [comment]
Hitting this wall too.

**Comment by douglowder** [comment]
Tracking in ENG-12780

**Comment by waelbenmustapha** [comment]
hey another question related to notifications , i sometimes don't receive push notifications , while other people do receive them , it's like maybe 10% of the times a notifications goes missing , is it normal ? i have the priority set to HIGH

**Comment by fgauna12** [comment]
@waelbenmustapha - Should you be sending notifications from the backend like this?

i.e. specifying the sound and not choosing `default`?

```
const messages = [];
messages.push({
  to: pushToken,
  sound: "sound.wav", // Custom sound file
  title: 'Test Title',
  body: 'Test Body',
  channelId: "ltsChannel",
});
```

**Comment by mhuggins** [comment]
> @waelbenmustapha - Should you be sending notifications from the backend like this?
> 
> i.e. specifying the sound and not choosing `default`?
> 
> ```
>   sound: "sound.wav", // Custom sound file
> ```

The push notification request fails if the `sound` string is anything other than "default".

**Comment by mhuggins** [comment]
I can't even get the custom sound to work at all when sending from the back-end, regardless of the app being in the foreground, background, or killed.

**Comment by pedroayres** [comment]
We’re facing the same issue here. Any update?

**Comment by vonovak** [comment]
Hello and thanks for reporting.
Custom sounds are controlled by channels, and channel information was incorrectly handled by our push backend service. That issue is now resolved and does not require updating the expo-notifications package.

That means you should not be seeing this problem as of now. If you do, please open a new issue and follow the issue template.

Thank you

**Comment by SiddigHope** [comment]
@vonovak 
how about custom sound for iOS, it's still not working on managed apps using EAS Build.
the documentation makes it like it works with both Android and iOS , it works perfectly fine on Android, but not on iOS

**Comment by vonovak** [comment]
hello @SiddigHope 
Please open a new issue for your problem and follow the issue template. It's especially important that you include:

1. runnable reproduction
2. what behavior you're seeing (with steps to reproduce) and what you expect to see instead.
3. For push notifications: the request you're sending to the push service in order to send the notification (especially the request body is important)
4. Add the "Notifications" label to the Github Issue - this helps with visibility.

Thank you!

**Comment by sulemantech** [comment]
After reviewing the messages in this thread, I initially assumed that Expo notification sounds wouldn’t work while the app is in the background or terminated. However, after cross-checking with the Expo documentation and running my own tests, I can confirm that they do work in those states. I’ve verified this using "_expo": "~53.0.22". 

Here is the code snippet of the test I tried 

```

const PRAYER_CHANNEL_ID = 'prayer_notifications';

// Set the notification handler
Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowBanner: true,
    shouldShowList: true,
    shouldPlaySound: true,
    shouldSetBadge: false,
  }),
});

/**
 * Setup notification channel
 */
async function setupNotificationChannel(): Promise<boolean> {
  try {
    // Delete any existing channel
    try {
      await Notifications.deleteNotificationChannelAsync(PRAYER_CHANNEL_ID);
      console.log('Deleted existing prayer channel');
    } catch (error) {
      console.log('No existing channel to delete', error);
    }

    // Create channel with custom sound
    await Notifications.setNotificationChannelAsync(PRAYER_CHANNEL_ID, {
      name: 'Prayer Notifications',
      importance: Notifications.AndroidImportance.HIGH,
      sound: 'adhan.wav',
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
      lockscreenVisibility: Notifications.AndroidNotificationVisibility.PUBLIC,
      showBadge: true,
      enableLights: true,
      enableVibrate: true,
    });

    console.log('Prayer notification channel created with custom sound');
    return true;
  } catch (error) {
    console.error('Failed to create notification channel:', error);
    return false;
  }
}

/**
 * Request notification permissions
 */
export async function requestNotificationPermissions(): Promise<boolean> {
  try {
    // Setup notification channel first
    const channelSetup = await setupNotificationChannel();
    if (!channelSetup) {
      console.error('Channel setup failed');
      return false;
    }

    const { status: existingStatus } = await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;

    if (existingStatus !== 'granted') {
      const { status } = await Notifications.requestPermissionsAsync();
      finalStatus = status;
    }

    if (finalStatus !== 'granted') {
      console.error('Notification permission not granted');
      return false;
    }

    return true;
  } catch (error) {
    console.error('Error in requestNotificationPermissions:', error);
    return false;
  }
}

/**
 * Schedule notification
 */
async function scheduleNotification(content: any, trigger: any): Promise<boolean> {
  try {
    await Notifications.scheduleNotificationAsync({
      content: {
        ...content,
        sound: 'adhan.wav',
        channelId: PRAYER_CHANNEL_ID,
      },
      trigger,
    });
    console.log('Notification scheduled successfully');
    return true;
  } catch (error) {
    console.error('Failed to schedule notification:', error);
    return false;
  }
}

/**
 * Schedules daily notifications for each prayer time
 */
export async function schedulePrayerNotifications(prayers: { name: string, time: Date }[]): Promise<boolean> {
  const isPermissionGranted = await requestNotificationPermissions();
  if (!isPermissionGranted) {
    console.log("Permission to receive notifications not granted.");
    return false;
  }

  await Notifications.cancelAllScheduledNotificationsAsync();
  console.log("Scheduling daily prayer notifications...");

  for (const prayer of prayers) {
    let trigger: Notifications.CalendarTriggerInput = {
      channelId: PRAYER_CHANNEL_ID,
      type: Notifications.SchedulableTriggerInputTypes.CALENDAR,
      hour: prayer.time.getHours(),
      minute: prayer.time.getMinutes(),
      repeats: true,
    };

    const notificationContent = {
      title: `🕌 Time for ${prayer.name} – Answer Allah’s call!`,
      body: `Purify your soul and draw closer to Allah with ${prayer.name}.`,
      data: { prayer: prayer.name },
    };

    // If prayer time is in the past, schedule for tomorrow
    if (prayer.time.getTime() < new Date().getTime()) {
      console.log(`Skipping ${prayer.name} as it is in the past, will be scheduled for tomorrow.`);
      const tomorrow = new Date(prayer.time);
      tomorrow.setDate(tomorrow.getDate() + 1);
      trigger.hour = tomorrow.getHours();
      trigger.minute = tomorrow.getMinutes();
    }

    try {
      await scheduleNotification(notificationContent, trigger);
      console.log(`Scheduled notification for ${prayer.name}`);
    } catch (error) {
      console.error(`Failed to schedule notification for ${prayer.name}:`, error);
    }
  }
  return true;
}

```

**Comment by Aloneking789** [comment]
notification works in both background and foreground but I tried adding custom sound but it never works please help
what does the app. json and notification code snippets looks like if anyone could help

**Comment by lotsoGuy** [comment]
> notification works in both background and foreground but I tried adding custom sound but it never works please help what does the app. json and notification code snippets looks like if anyone could help

Mine on android comes with no sound at all.

**Comment by SiddigHope** [comment]
@lotsoGuy 

Make sure you include the notification sound in your app.json, and rebuild with eas if you're using eas builds.

```
plugins: [
       [
          "expo-notifications",
          {
            sounds: ["./assets/audio/notification.wav"]
          }
        ]
]
```
And make sure you use the exact name of the sound file (in this case ```notification``` without .wav extention) in your api call  if you're using push url
