### ISSUE TITLE
RN: CommandError: Can't determine id of Simulator

### ISSUE THREAD

**Issue by JuanRdBO** [expo/expo#28345]
### Summary

Hey guys, 

I ran a bunch of yarn add/ yarn remove commands and all of a sudden I got this error `CommandError: Can't determine id of Simulator app; the Simulator is most likely not installed on this machine. Run `sudo xcode-select -s /Applications/Xcode.app`` when starting the dev server with `npx expo start` and then pressing `i`.

After some digging and verifying that the simulators, xcode and osascript all work properly (I can execute `osascript -e 'id of app "Simulator"'` properly) I looked into the source code of the cli [here](https://github.com/expo/expo/blob/739f16d607cadb8c00924b01a9711277ebfa164c/packages/%40expo/cli/src/start/doctor/apple/SimulatorAppPrerequisite.ts#L11) and added an error message to the try/catch block and saw this:

`TypeError: (0 , _osascript).execAsync is not a function`

Upgrading to the latest @expo/cli (0.18.1) yields a similar error: `TypeError: (0 , _osascript(...).execAsync) is not a function`

It seems that when running the command to start the expo cli, it can't find the import and crashes. 

I found that forcing @expo/osascript version to be the previous one (2.1.0) fixes it for me, so there must be something wrong with 2.1.1

### What platform(s) does this occur on?

iOS

### SDK Version

50.0.17

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      Yarn: 4.1.1 - ~/.nvm/versions/node/v18.18.2/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
      Watchman: 2024.04.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 25, 28, 29, 30, 31, 32, 33, 34
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-28 | Google APIs ARM 64 v8a, android-28 | Google ARM64-V8a Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-Tiramisu | Google Play ARM 64 v8a, android-TiramisuPrivacySandbox | Google Play ARM 64 v8a, android-UpsideDownCake-ext5 | Google APIs ARM 64 v8a, android-UpsideDownCake-ext5 | Google Play ARM 64 v8a, android-UpsideDownCakePrivacySandbox | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.17 => 50.0.17
      expo-router: ~3.4.8 => 3.4.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
    npmGlobalPackages:
      eas-cli: 7.8.2
      expo-cli: 6.3.10
    Expo Workflow: bare

### Minimal reproducible example

This happens in the latest version of expo-cli

**Comment by cem2ran** [comment]
I've also run into this issue since yesterday.

**Comment by Mohamed-kassim** [comment]
having the same issue here

**Comment by Kudo** [comment]
we've published `@expo/osascript@2.1.2` with fixes. by updating latest `expo@next` then you should include the newer osascript version. thanks for having the issue reporting!

**Comment by Mohamed-kassim** [comment]
they are not in my dependencies,  Expo 50.0.17 is pulling 2.1.1, I tried downgrading but didn't fix the issue, removing all node modules and lock files, but it's still pulling 2.1.0
actually this issue mentioned SDK 50.0.17, not expo next @JuanRdBO can confirm
**Update:**  after cleaning the project now and reinstalling, it pulls 2.1.2, issue resolved

**Comment by nmassey** [comment]
Resolved for me, as well. ✅ Thanks, team! 🙌

My procedure to get the newer dependency:
1. remove `expo` from `package.json` (for my Expo project running locally)
2. run `yarn`
3. re-add `expo` to `package.json`
4. run `yarn`

**Comment by Kudo** [comment]
oh i see. it's a caret version: https://github.com/expo/expo/blob/000600c9e4223acc316ecc9a988257fcc965575a/packages/%40expo/cli/package.json#L49

sorry the current solution is to pull the expo version again or regenerate the npm lock file. if there are any difficulty in regenerating the lock file. let us know and i'll think some alternatives.

i'm closing the issue. and thanks everyone for having the feedback.
