### ISSUE TITLE
Typed routes not working in Expo 51 and Expo router

### ISSUE THREAD

**Issue by alfjesus** [expo/expo#28680]
### Minimal reproducible example

https://github.com/alfjesus/typed-routes

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

Creating a new project with `yarn create expo-app` (Expo 51) seems to have broken the typed routes for expo router. When I downgraded to Expo 50 (and `npx expo install --check`), typed routes started to working again. I guess there's something wrong with the generation of the types when the development server starts 🤔

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - /usr/local/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.3 - /usr/local/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /Users/anders/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.0 => 51.0.0 
      expo-router: ~3.5.10 => 3.5.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 7.8.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by alfjesus** [comment]
> Having the same issue after upgrading an expo project from SDK50 to 51.
> 
> Also, in a fresh new project using SDK 51, switching between tabs closes Expo Go

The crash issue you are referring to @pedrohamarques, has already been mentioned in the release notes for Expo 51 together with a workaround. https://github.com/expo/expo/issues/28618

**Comment by pedrohamarques** [comment]
Thank you @alfjesus , I remember reading about that issue but I totally forgot about the workaround , my bad.

**Comment by Brahim-djiddi** [comment]
@alfjesus I had the same issue when I installed SDK 51. The **Expo Go** app just closes when touching the screen, simultaneously.

**Comment by vitaliinnest** [comment]
I can relate. Typed routes are turned off even though `app.json` contains `"experiments": { "typedRoutes": true }`

**Comment by marklawlor** [comment]
Fixed in `3.5.11`

**Comment by vitaliinnest** [comment]
The issue still persists, I have `"expo-router": "~3.5.11",` installed

**Comment by alfjesus** [comment]
Yes, I can also confirm that the issue still exist in 3.5.11

**Comment by ljukas** [comment]
Confirm this exists for me aswell

**Comment by alfjesus** [comment]
> Confirm this exists for me as well, issue for me seems to be that it does not use the generated types but instead the base types from the expo router library. So it is missing all the project specific route types

Yes exactly. Looks like there's something with the typescript namespace, which is defined both in the expo router lib and in the generated `.expo/types/router.d.ts`.

```typescript
export namespace ExpoRouter
```

**Comment by AdamTyler** [comment]
Also having this issue... we were previously using `import type { AllRoutes } from 'expo-router';`

As @alfjesus mentioned, SDK 51/expo-router update made a change to the generated types to be:

`export namespace ExpoRouter {`

instead of 

`declare module "expo-router" {` that it has in SDK 50

**Comment by riebel** [comment]
The same for me in all 3.5.x (including 3.5.11) versions. I get the "Welcome to Expo" default screen. None of my routes work.

**Comment by asmachkirida** [comment]
I'm having the same problem too!! After upgrading to expo 51
Did any of yall find a solution?

**Comment by George-Acquah** [comment]
I just got the same problem after upgrading to **expo 51**
I get the **Welcome to Expo** screen and nothing seems to be working
Is there any workaround without downgrading my expo-router @marklawlor

**Comment by alfjesus** [comment]
> I just got the same problem after upgrading to **expo 51** I get the **Welcome to Expo** screen and nothing seems to be working Is there any workaround without downgrading my expo-router @marklawlor

@George-Acquah This issue is about typed routes in Expo Router not working. Navigation calls to defined routes is working as before with no issues. However, these routes are not typed and therefore I don't get auto completion of available routes for the `href` prop or a typescript error if I put in a route that is not defined.

But you are saying nothing seems to be working? Are you experiencing more issue than typed routes? If so I think a new issue should be filed to keep these separated.

**Comment by gorbypark** [comment]
I can also confirm typed routes are not working (as far as the href prop on Link and router.navigate() from useRouter() goes).  They will both accept any string.  I tried deleting the .expo folder and restarting metro with --clear to ensure new types were being generated, but it still doesn't work.

```json
    "expo-router": "~3.5.12",
    "expo": "~51.0.4",
```

**Comment by tjadolfo004** [comment]
Fixed in expo ~51.0.5 expo router: ~3.5.12....if build has an error delete node_modules folder and run npm install again.

**Comment by gorbypark** [comment]
> Fixed in expo ~51.0.5 expo router: ~3.5.12....if build has an error delete node_modules folder and run npm install again.

This does not seem to work for me.  I'm on 51.0.5 and router 3.5.12, I nuked node_modules, deleted .expo and did a full reinstall and still no typed routes.

**Comment by fredericogomesaeguana** [comment]
Not sure if it's related but seems I can't find screens inside my (tabs) group on a production build only. Development ones works just fine with expo sdk 51.

**Comment by ekramteyeb** [comment]
same here not working for me as well :)

**Comment by oliviercperrier** [comment]
Same here

**Comment by jokubauskas** [comment]
Can confirm, yesterday I have bootstrapped a new Expo project with Expo Router, and typed routes are not working for me.

**Comment by jonasdhein** [comment]
Any news?

**Comment by TimoVie** [comment]
Still same issue

**Comment by ljukas** [comment]
The problems is because there are imports in the declaration file that is generated, which turns it into a local module instead of a global module. This can be solved by using something that was introduced in typescript 2.1 i think, which is using the `import()` api.

Solution:

These two files at the top needs to be removed:
```
import type { ReactNode } from 'react';
import type { GestureResponderEvent, TextProps } from 'react-native';
```

And the usages of these types needs to be changed like the following:

```
  export declare const Redirect: (props: React.PropsWithChildren<{ href: Href }>) => ReactNode;
```
```
  export declare const Redirect: (props: React.PropsWithChildren<{ href: Href }>) => import('react').ReactNode;
```

When this is done for all the three imports the types works again.

**Comment by shiftytab** [comment]
Same here....

**Comment by awvremusic** [comment]
> @alfjesus I dont know if i should downgrade, once i downgrade too it becomes difficult to use expo go on my mobile

Just hit this same issue today after upgrading to Expo SDK 51

**Comment by WKampel** [comment]
+1

**Comment by akarm13** [comment]
+1

**Comment by harivgts** [comment]
+1

**Comment by family2806** [comment]
+1

**Comment by idudinov** [comment]
hi there, instead of another useless `+1` (sorry folks) I'd share more details of issue that particularly hits me (looks like it hasn't been mentioned above).

```typescript
type StaticRoutes = `/` | `/(app)` | `/(tabs)` | `/_sitemap` | `/apps` | `/auth` | `/confirm-email` | `/editProfile` // ...
```

that's how routes are generated for my app, and main problem here is that they **do not include folder path** which makes it totally useless for non-root routes (which I have mostly all).

And yeah, just confirming another pain point that now it's not clear how to import `Href` or other route types. For now I'm importing like that:

```ts
import { ExpoRouter } from 'expo-router/types/expo-router';

const route: ExpoRouter.AbsoluteRoute = 'any-wrong-path-which-ts-doesnt-care-about';
```

so it looks awful, and doesn't include any actual route typings.

Checked on `"expo-router": "~3.5.14"`, `"expo": "~51.0.8"`.

Hopefully this could be fixed soon.
Thanks

**Comment by JohnGeorgiadis** [comment]
Same here.
I am using `"expo": "^51.0.8"` and `"expo-router": "~3.5.14"`.

`expo-router` exposes the `index.d.ts` from `expo-router` file instead of the `router.d.ts` from `.expo/types.router.d.ts`

I have an import like this `import { Route, router, usePathname } from 'expo-router';` and there is no more `Route` type being exposed by the package.

I hope this will be helpful,
amazing job and congrats for the great release.
Thanks

**Comment by kpoelhekke** [comment]
It looks like the `.expo/types.router.d.ts` file isn't properly generated because of this line: https://github.com/expo/expo/blame/6da4825c8af13f3f5480d88723a6683fd9ff39ca/packages/expo-router/src/typed-routes/generate.ts#L36

It should also do a ```.replace('export namespace ExpoRouter {', declare module "expo-router" {`)``` In that case you can import `Route` again from `expo-router`

**Comment by riebel** [comment]
> The same for me in all 3.5.x (including 3.5.11) versions. I get the "Welcome to Expo" default screen. None of my routes work. If I "touch" to create an index.js, the file gets created (app/index.tsx), but also does not load on refresh. Version 3.4.10 is working fine.

For clarification: My problem with the "Welcome to Expo" default screen and no routes working after upgrading `expo-router` was not related to this issue. It was a problem with `react-native-dotenv`.

Nevertheless my generated route types also do not work.

**Comment by jmacbhc** [comment]
Same problem here.

**Comment by fediru-gloat** [comment]
@marklawlor @EvanBacon Seems this is a blocker issue for upgrading to Expo SDK 51 / Expo Router 3.5. Could you please take a look and possibly advise temporary workaround while it's being fixed?

**Comment by joonshakya** [comment]
A temporary workaround I've been using is just by installing expo-router@3.4

**Comment by jake-stewart** [comment]
same problem

**Comment by jokinol** [comment]
@joonshakya Unfortunately expo-router 3.4 & Expo 51 breaks Android build at least for me.

**Comment by joonshakya** [comment]
@jokinol Hmm maybe you could try using expo-router@3.4 during development and use the typed routes and then during build time upgrade the expo-router to 3.5

**Comment by fediru-gloat** [comment]
```diff
diff --git a/build/typed-routes/generate.js b/build/typed-routes/generate.js
index 1e621830d26f90b3105d326ae31690c1e51730d1..01cce851540fd8d8882181ede0ec8fb2b3f22c38 100644
--- a/build/typed-routes/generate.js
+++ b/build/typed-routes/generate.js
@@ -26,7 +26,7 @@ function getTypedRoutesDeclarationFile(ctx) {
     return (node_fs_1.default
         .readFileSync(path_1.default.join(__dirname, '../../types/expo-router.d.ts'), 'utf-8')
         // Swap from being a namespace to a module
-        .replace('declare namespace ExpoRouter {', `declare module "expo-router" {`)
+        .replace('export namespace ExpoRouter {', `declare module "expo-router" {`)
         // Add the route values
         .replace('type StaticRoutes = string;', `type StaticRoutes = ${setToUnionType(staticRoutes)};`)
         .replace('type DynamicRoutes<T extends string> = string;', `type DynamicRoutes<T extends string> = ${setToUnionType(dynamicRoutes)};`)
``` 

This is the workaround until it will be merged properly by the team. Just create file `patches/expo-router@3.5.14.patch` and use it by `patch-package` or `pnpm patch`

**Comment by gorbypark** [comment]
> ```diff
> diff --git a/build/typed-routes/generate.js b/build/typed-routes/generate.js
> index 1e621830d26f90b3105d326ae31690c1e51730d1..01cce851540fd8d8882181ede0ec8fb2b3f22c38 100644
> --- a/build/typed-routes/generate.js
> +++ b/build/typed-routes/generate.js
> @@ -26,7 +26,7 @@ function getTypedRoutesDeclarationFile(ctx) {
>      return (node_fs_1.default
>          .readFileSync(path_1.default.join(__dirname, '../../types/expo-router.d.ts'), 'utf-8')
>          // Swap from being a namespace to a module
> -        .replace('declare namespace ExpoRouter {', `declare module "expo-router" {`)
> +        .replace('export namespace ExpoRouter {', `declare module "expo-router" {`)
>          // Add the route values
>          .replace('type StaticRoutes = string;', `type StaticRoutes = ${setToUnionType(staticRoutes)};`)
>          .replace('type DynamicRoutes<T extends string> = string;', `type DynamicRoutes<T extends string> = ${setToUnionType(dynamicRoutes)};`)
> ```
> 
> This is the workaround until it will be merged properly by the team. Just create file `patches/expo-router@3.5.14.patch` and use it by `patch-package` or `pnpm patch`

I tried this out when @kpoelhekke posted above and it does allow you to import the Route type again but it doesn't fix the typed routes issue (ie: no type safety or autocomplete on `<Link href='/home'>` or on `router.navigate('/home')` for example)

**Comment by ega65** [comment]
> blocke

It took me 12 hours to find out about this damned "env"...

**Comment by nicolasssosa** [comment]
Still same here

**Comment by trentcharlie** [comment]
What is the point of `.replace('declare namespace ExpoRouter {', `declare module "expo-router" {`)` cause if I change `export namespace ExpoRouter {` to  `declare module "expo-router" {` manually, all the typing issues go away

**Comment by trentcharlie** [comment]
Just came across more bugs with the types now that I can actually type check.
I have a route `/auth/sign-up` and in the generated types I only see `/sign-up`. And this is inconsistent too cause another route `settings/account` is generated so it isn't like nested routes are not working.
<img width="287" alt="Screenshot 2024-06-03 at 11 42 10" src="https://github.com/expo/expo/assets/127359753/6716cc95-303d-4b50-b64c-a857e646dcaa">

I guess release notes of Expo 51 should've said:
> We've broken the "typed" in `expo-router` we've been talking about so much and aren't gonna do something about it for weeks or maybe months so screw everyone who relied on those types for anything.

**Comment by dannyhw** [comment]
the fix in https://github.com/expo/expo/issues/28680#issuecomment-2134632877

seems to partially work but also I found that some of the routes are missing, seems to be nested routes that are missing in the generated type. I.e /onboarding is there but nothing like /onboarding/about-you etc

**Comment by V1RE** [comment]
Building upon the patch by @fediru-gloat, I think I got it working correctly!

```patch
diff --git a/build/typed-routes/generate.js b/build/typed-routes/generate.js
index 1e621830d26f90b3105d326ae31690c1e51730d1..a42ca3886501c1636640e75e83a87eff3bcc3ce4 100644
--- a/build/typed-routes/generate.js
+++ b/build/typed-routes/generate.js
@@ -26,7 +26,12 @@ function getTypedRoutesDeclarationFile(ctx) {
     return (node_fs_1.default
         .readFileSync(path_1.default.join(__dirname, '../../types/expo-router.d.ts'), 'utf-8')
         // Swap from being a namespace to a module
-        .replace('declare namespace ExpoRouter {', `declare module "expo-router" {`)
+        .replace(`import type { ReactNode } from 'react';
+import type { TextProps, GestureResponderEvent } from 'react-native';
+
+export namespace ExpoRouter {`,
+          `declare module "expo-router" {\n  import type { ReactNode } from 'react';\n  import type { TextProps, GestureResponderEvent } from 'react-native';\n  export * from "expo-router/build";`
+        )
         // Add the route values
         .replace('type StaticRoutes = string;', `type StaticRoutes = ${setToUnionType(staticRoutes)};`)
         .replace('type DynamicRoutes<T extends string> = string;', `type DynamicRoutes<T extends string> = ${setToUnionType(dynamicRoutes)};`)
```

**Comment by ianfelix** [comment]
I am with the same issue, I am using `"expo": "^51.0.11"` e `"expo-router": "~3.5.15"`

**Comment by hichemfantar** [comment]
I'm having this issue as well navigating to `/(tabs)` doesn't load the first screen by default and causes a 404

**Comment by pinki-palacios** [comment]
Same here.

I tried the shared patches but as someone already mentioned that only works partially. You can see the types being generated at the module level and see things like StaticRoutes being properly defined. But those types are not being propagated to the rest of the package (router, redirect and link components, etc are not tied to the generated types). So other than getting a type for your static routes there's not much else from that fix...

As a workaround I ended up rolling back to a previous expo router version for now while keeping the latest-ish. expo version
Everything seems to be working so far and got typed routes behaving as expected.


```
    "expo-router": "~3.4.10",
     "expo": "~51.0.10",
```

Once this issue is resolved it should be a matter of updading to the latest expo-router again.

**Comment by alfjesus** [comment]
Looks like a fix is coming soon in PR #29612 👀

**Comment by Poison159** [comment]
Lol waiting for a merge while our apps don't work

**Comment by akarm13** [comment]
@Poison159 The apps work just fine. Typed routes are an experimental development only feature. It is bound to break from time to time. Disable it for now and work as usual.

**Comment by Siyabonga-TitanSecure** [comment]
@akarm13 Well maybe I'm confused by something. I could route to my pages just fine with <Link href={{ pathname: "LocationsScreen", params: { vibe, distance }}} asChild>
using expo router on SDK 49 and now on SDK 51 all those pages give a Unmatched route on my expo go. I would say that constitutes an app not working.![Screenshot 2024-06-12 at 11 45 43](https://github.com/expo/expo/assets/163743783/677cccf0-509f-47e7-ac51-ad79961c5c0a)

**Comment by giovannilondero** [comment]
@Poison159 / @Siyabonga-TitanSecure how does that have anything to do with types? Your issue is different than the OP. Also if you update from SDK 49 to 51 (2 majors) you can't expect everything to work perfectly fine.
If you think the error is not on your side, you can open a specific ticket with a reproducible example

As @akarm13 said, apps work just fine.

**Comment by akarm13** [comment]
@Siyabonga-TitanSecure 

That's another issue. Typed Routes are enabled in your config under the `experimental` flag. It provides route suggestions based on the routes you've defined, based on the file system and also based on the routes you've defined in your `_layout` files. I've disabled mine for now because I know the structure of my routes and I know what params they take. It was a nice addition, but since it is experimental I tend to not care much when it breaks, I simply just disable it. You can learn more from [here](https://docs.expo.dev/router/reference/typed-routes/)


As for your issue, since you are using Expo, you can customize your Expo Menu when you press `M` in your terminal or shake it. So as a start to see what is going on, I suggest you to create this hook:

```ts
import { useRouter } from "expo-router";
import { useEffect } from "react";
import { registerDevMenuItems } from "expo-dev-menu";

export const useDevRoutes = () => {
  const router = useRouter();

  useEffect(() => {
    const devMenuItems = [
      {
        name: `Go to Sitemap`,
        callback: () => router.push("/_sitemap"),
      },
    ];

    registerDevMenuItems(devMenuItems);
  }, [router]);
};
```

Put it in your root `_layout` file and run it like usual.

Now when you press `M` to open up the dev menu, You will see a new a menu item called `Go to Sitemap` and when you press it, it shows all the registered routes there. And try to see what your `LocationScreen` component is registered as. Let me know if you found the problem and if it is related to typed routes at all. Have a good day.

**Comment by Siyabonga-TitanSecure** [comment]
@akarm13 Thanks for the above.

I've checked the sitemap and see that some components show up while others don't(files are on the same dir level).
I've also checked if there are any major diffs between the ones that show up vs the ones that don't and i can't seem to see a significant diff. 
I can of course navigate to the ones that show up but would you know why the others don't show up ?

I've been looking online all day but no joy so far
![Screenshot 2024-06-12 at 14 31 11](https://github.com/expo/expo/assets/163743783/d2046bd5-4ab1-4072-8dc1-b6c521d21af7)
![Screenshot 2024-06-12 at 14 31 28](https://github.com/expo/expo/assets/163743783/cbbcc877-cbc4-497c-8612-5c195bfc78b1)
![Screenshot 2024-06-12 at 14 33 36](https://github.com/expo/expo/assets/163743783/724ca308-762c-4a66-b22e-5f9067a85038)
![Screenshot 2024-06-12 at 14 34 09](https://github.com/expo/expo/assets/163743783/77c5d919-24d1-4f13-b847-31f3ef8e8ab2)

**Comment by akarm13** [comment]
@Siyabonga-TitanSecure 

The way you structured your screens is very unconventional. Usually in the file-system routers they expect you to structure your files and folders like how you'd structure URLs.

As for Expo Router, it should be in the `app` directory, and by convention you should use kebab-case (lower-case file and folder names and separate them by dashes).

I highly suggest you to look at the docs [here](https://docs.expo.dev/router/create-pages/).


Things I would check for if I were you:
1. Making sure I've `export default`(ed) the screens I want to use.
2. If it still doesn't show up, making sure to define the screens in the `_layout` file with their paths in case Expo Router doesn't recognize your convention.
3. If you have time, maybe try to restructure your folder structure to match the convention everyone uses.

**Comment by MartinHarkins** [comment]
In the mean time I just did the declaration merge on my end:

```ts
// src/@types/expo-router.d.ts

import { ExpoRouter } from 'expo-router'

// TODO check this again if date > 18 june 2024
// temp while https://github.com/expo/expo/issues/28680 is open
// and while https://github.com/expo/expo/pull/29612/files is not merge
// simply remove this file and run type checking to verify
declare module 'expo-router' {
  export type Href = ExpoRouter.Href
  export type Router = ExpoRouter.Router
}
```

I'm glad I did, the route typings are a lot better now

**Comment by bradleyayers** [comment]
I think I'm experiencing another issue with this when you have nested layouts and static routes. I was seeing the prefix of the route being dropped and I needed to apply this patch.

https://github.com/bradleyayers/haohao.how/blob/149781fae327c14dd0a06d57b7144af31424d71d/.yarn/patches/expo-router-patch-c2c9a30c9c.patch

```
/_layout.tsx
/index.tsx
/foo/
/foo/_layout.tsx
/foo/bar.tsx
```

The route for `/foo/bar` was being output as `/bar` because when crawling the filesystem the route nodes `node.route` is made relative to the layout:

- https://github.com/expo/expo/blob/cbb5828481fe05d423d6f248fc8aa20fa167c140/packages/expo-router/src/getRoutesCore.ts#L45
- https://github.com/expo/expo/blob/cbb5828481fe05d423d6f248fc8aa20fa167c140/packages/expo-router/src/getRoutesCore.ts#L296

But in the typed routes generator the layout route is not put back:

- https://github.com/expo/expo/blob/cbb5828481fe05d423d6f248fc8aa20fa167c140/packages/expo-router/src/typed-routes/generate.ts#L67

**Comment by bradleyayers** [comment]
> how did you fix it? i'm having the same exact issue after upgrading to Expo SDK 51

You can have a look at the patches I use to fix it here https://github.com/bradleyayers/haohao.how/tree/main/.yarn/patches

**Comment by anthlasserre** [comment]
I'm under Expo 51 as well. `expo@51.0.14` and `expo-router@3.5.16` and I'm facing this typing issue.

I took inspiration from @V1RE's [patch](https://github.com/expo/expo/issues/28680#issuecomment-2148084616.) and it's all working now.

```Diff
diff --git a/node_modules/expo-router/build/typed-routes/generate.js b/node_modules/expo-router/build/typed-routes/generate.js
index 1e62183..6e66bf6 100644
--- a/node_modules/expo-router/build/typed-routes/generate.js
+++ b/node_modules/expo-router/build/typed-routes/generate.js
@@ -26,7 +26,7 @@ function getTypedRoutesDeclarationFile(ctx) {
     return (node_fs_1.default
         .readFileSync(path_1.default.join(__dirname, '../../types/expo-router.d.ts'), 'utf-8')
         // Swap from being a namespace to a module
-        .replace('declare namespace ExpoRouter {', `declare module "expo-router" {`)
+        .replace(`import type { ReactNode } from 'react';\nimport type { TextProps, GestureResponderEvent } from 'react-native';\n\nexport namespace ExpoRouter {`, `declare module "expo-router" {\n  import type { ReactNode } from 'react';\n  import type { TextProps, GestureResponderEvent } from 'react-native';\n  export * from "expo-router/build";\n`)
         // Add the route values
         .replace('type StaticRoutes = string;', `type StaticRoutes = ${setToUnionType(staticRoutes)};`)
         .replace('type DynamicRoutes<T extends string> = string;', `type DynamicRoutes<T extends string> = ${setToUnionType(dynamicRoutes)};`)
```
**Before** `.expo/types/router.d.ts`
```typescript
import type { ReactNode } from 'react';
import type { TextProps, GestureResponderEvent } from 'react-native';

export namespace ExpoRouter {
  type StaticRoutes = `/` | `/(latest)` | `/(tabs)` | `/_sitemap` | `/article` | `/category` | `/debug` | `/language` | `/matches` | `/menu` | `/modal` | `/profile` | `/settings` | `/shop` | `/storybook` | `/teams` | `/update` | `/videos`;
  type DynamicRoutes<T extends string> = `/${CatchAllRoutePart<T>}` | `/${SingleRoutePart<T>}` | `/content-page/${SingleRoutePart<T>}` | `/navigation-screen/${SingleRoutePart<T>}`;
  type DynamicRouteTemplate = `/[...unmatched]` | `/[id]` | `/content-page/[id]` | `/navigation-screen/[id]`;
```

**After** `.expo/types/router.d.ts`
```typescript
/* eslint-disable */
declare module "expo-router" {
  import type { ReactNode } from 'react';
  import type { TextProps, GestureResponderEvent } from 'react-native';
  export * from "expo-router/build";

  type StaticRoutes = `/` | `/(latest)` | `/(tabs)` | `/_sitemap` | `/article` | `/category` | `/debug` | `/language` | `/matches` | `/menu` | `/modal` | `/profile` | `/settings` | `/shop` | `/storybook` | `/teams` | `/update` | `/videos`;
  type DynamicRoutes<T extends string> = `/${CatchAllRoutePart<T>}` | `/${SingleRoutePart<T>}` | `/content-page/${SingleRoutePart<T>}` | `/navigation-screen/${SingleRoutePart<T>}`;
  type DynamicRouteTemplate = `/[...unmatched]` | `/[id]` | `/content-page/[id]` | `/navigation-screen/[id]`;
```

**Comment by SKempin** [comment]
Same issue here, have downgraded back to `3.4.6`

**Comment by leggomuhgreggo** [comment]
Noticing similar issues, even with the patch, in a monorepo context — eg where the project-root is different the the workspace- / node_modules-root

Here's a [repro](https://github.com/leggomuhgreggo/nx-expo-router-repro-2024-05-25/tree/repro/typed-routes-monorepo-issue).

**Comment by anthlasserre** [comment]
@leggomuhgreggo Mine is only working if you use the Href object.

`pathname` is typed only. I haven't hard the to look at the Href string.

**Comment by bradleyayers** [comment]
> Noticing similar issues, even with the patch, in a monorepo context — eg where the project-root is different the the workspace- / node_modules-root
> 
> Here's a [repro](https://github.com/leggomuhgreggo/nx-expo-router-repro-2024-05-25/tree/repro/typed-routes-monorepo-issue).

I think the issue here is probably that your patch isn't being applied. In your repo you have `patch-package` only being run in the root package.json, but you have the `@nx/expo` fixer scripts that copy the dependencies and devDependencies into the app package.json, but you didn't copy the post-install script that actually runs `patch-package`.

So I think in your case the issue is with your Nx stuff. BTW I'm using yarn workspaces too and don't need to do any workarounds, I just run `yarn` in the root before doing `eas build` or `eas update`, you can have a look here https://github.com/haohao-how/haohao.how/blob/95011bda5549777a88ec6c3eed3abbb5713757d6/.github/workflows/expo-eas-build.yml#L39

**Comment by Akuma-U1** [comment]
Also experiencing these issues, but seems like everyone that has updated to expo 51 will experience it, based on what the underlying issue is. Had a look a PR https://github.com/expo/expo/pull/29612 like mentioned in https://github.com/expo/expo/issues/28680#issuecomment-2160521644. It seems like there is still active ongoing development on the PR, but hopefully fix is shipped soon. 🙏

**Comment by arijitcodes** [comment]
> I'm under Expo 51 as well. `expo@51.0.14` and `expo-router@3.5.16` and I'm facing this typing issue.
> 
> I have built my patch with a combo from @V1RE's [patch](https://github.com/expo/expo/issues/28680#issuecomment-2148084616.) and @bradleyayers's [patch](https://github.com/expo/expo/issues/28680#issuecomment-2184758149). It's all working now.
> 
> ```diff
> diff --git a/node_modules/expo-router/build/typed-routes/generate.js b/node_modules/expo-router/build/typed-routes/generate.js
> index 1e62183..b2b18e5 100644
> --- a/node_modules/expo-router/build/typed-routes/generate.js
> +++ b/node_modules/expo-router/build/typed-routes/generate.js
> @@ -26,7 +26,7 @@ function getTypedRoutesDeclarationFile(ctx) {
>      return (node_fs_1.default
>          .readFileSync(path_1.default.join(__dirname, '../../types/expo-router.d.ts'), 'utf-8')
>          // Swap from being a namespace to a module
> -        .replace('declare namespace ExpoRouter {', `declare module "expo-router" {`)
> +        .replace(`import type { ReactNode } from 'react';\nimport type { TextProps, GestureResponderEvent } from 'react-native';\n\nexport namespace ExpoRouter {`, `declare module "expo-router" {\n  import type { ReactNode } from 'react';\n  import type { TextProps, GestureResponderEvent } from 'react-native';\n  export * from "expo-router/build";\n`)
>          // Add the route values
>          .replace('type StaticRoutes = string;', `type StaticRoutes = ${setToUnionType(staticRoutes)};`)
>          .replace('type DynamicRoutes<T extends string> = string;', `type DynamicRoutes<T extends string> = ${setToUnionType(dynamicRoutes)};`)
> @@ -41,7 +41,8 @@ function walkRouteNode(routeNode, staticRoutes, dynamicRoutes, dynamicRouteConte
>          return;
>      addRouteNode(routeNode, staticRoutes, dynamicRoutes, dynamicRouteContextKeys);
>      for (const child of routeNode.children) {
> -        walkRouteNode(child, staticRoutes, dynamicRoutes, dynamicRouteContextKeys);
> +        const childWithPrefixedRoute = { ...child, route: `${routeNode.route}/${child.route}` };
> +        walkRouteNode(childWithPrefixedRoute, staticRoutes, dynamicRoutes, dynamicRouteContextKeys);
>      }
>  }
>  /**
> ```
> 
> **Before** `.expo/types/router.d.ts`
> 
> ```ts
> import type { ReactNode } from 'react';
> import type { TextProps, GestureResponderEvent } from 'react-native';
> 
> export namespace ExpoRouter {
>   type StaticRoutes = `/` | `/(latest)` | `/(tabs)` | `/_sitemap` | `/article` | `/category` | `/debug`;
>   type DynamicRoutes<T extends string> = `/${CatchAllRoutePart<T>}` | `/${SingleRoutePart<T>}`;
>   type DynamicRouteTemplate = `/[...unmatched]` | `/[id]`;
> ```
> 
> **After** `.expo/types/router.d.ts`
> 
> ```ts
> /* eslint-disable */
> declare module "expo-router" {
>   import type { ReactNode } from 'react';
>   import type { TextProps, GestureResponderEvent } from 'react-native';
>   export * from "expo-router/build";
> 
>   type StaticRoutes = `/` | `/(latest)` | `/(tabs)` | `/_sitemap` | `/article` | `/category` | `/debug`;
>   type DynamicRoutes<T extends string> = `/${CatchAllRoutePart<T>}` | `/${SingleRoutePart<T>}`;
>   type DynamicRouteTemplate = `/[...unmatched]` | `/[id]`;
> ```

The solution worked pretty well for me. Thanks a lot mate 🙏🏻

**Comment by igoro00** [comment]
> I'm under Expo 51 as well. `expo@51.0.14` and `expo-router@3.5.16` and I'm facing this typing issue.
> 
> I have built my patch with a combo from @V1RE's [patch](https://github.com/expo/expo/issues/28680#issuecomment-2148084616.) and @bradleyayers's [patch](https://github.com/expo/expo/issues/28680#issuecomment-2184758149). It's all working now.
> 
> ```diff
> diff --git a/node_modules/expo-router/build/typed-routes/generate.js b/node_modules/expo-router/build/typed-routes/generate.js
> index 1e62183..b2b18e5 100644
> --- a/node_modules/expo-router/build/typed-routes/generate.js
> +++ b/node_modules/expo-router/build/typed-routes/generate.js
> @@ -26,7 +26,7 @@ function getTypedRoutesDeclarationFile(ctx) {
>      return (node_fs_1.default
>          .readFileSync(path_1.default.join(__dirname, '../../types/expo-router.d.ts'), 'utf-8')
>          // Swap from being a namespace to a module
> -        .replace('declare namespace ExpoRouter {', `declare module "expo-router" {`)
> +        .replace(`import type { ReactNode } from 'react';\nimport type { TextProps, GestureResponderEvent } from 'react-native';\n\nexport namespace ExpoRouter {`, `declare module "expo-router" {\n  import type { ReactNode } from 'react';\n  import type { TextProps, GestureResponderEvent } from 'react-native';\n  export * from "expo-router/build";\n`)
>          // Add the route values
>          .replace('type StaticRoutes = string;', `type StaticRoutes = ${setToUnionType(staticRoutes)};`)
>          .replace('type DynamicRoutes<T extends string> = string;', `type DynamicRoutes<T extends string> = ${setToUnionType(dynamicRoutes)};`)
> @@ -41,7 +41,8 @@ function walkRouteNode(routeNode, staticRoutes, dynamicRoutes, dynamicRouteConte
>          return;
>      addRouteNode(routeNode, staticRoutes, dynamicRoutes, dynamicRouteContextKeys);
>      for (const child of routeNode.children) {
> -        walkRouteNode(child, staticRoutes, dynamicRoutes, dynamicRouteContextKeys);
> +        const childWithPrefixedRoute = { ...child, route: `${routeNode.route}/${child.route}` };
> +        walkRouteNode(childWithPrefixedRoute, staticRoutes, dynamicRoutes, dynamicRouteContextKeys);
>      }
>  }
>  /**
> ```
> 
> **Before** `.expo/types/router.d.ts`
> 
> ```ts
> import type { ReactNode } from 'react';
> import type { TextProps, GestureResponderEvent } from 'react-native';
> 
> export namespace ExpoRouter {
>   type StaticRoutes = `/` | `/(latest)` | `/(tabs)` | `/_sitemap` | `/article` | `/category` | `/debug`;
>   type DynamicRoutes<T extends string> = `/${CatchAllRoutePart<T>}` | `/${SingleRoutePart<T>}`;
>   type DynamicRouteTemplate = `/[...unmatched]` | `/[id]`;
> ```
> 
> **After** `.expo/types/router.d.ts`
> 
> ```ts
> /* eslint-disable */
> declare module "expo-router" {
>   import type { ReactNode } from 'react';
>   import type { TextProps, GestureResponderEvent } from 'react-native';
>   export * from "expo-router/build";
> 
>   type StaticRoutes = `/` | `/(latest)` | `/(tabs)` | `/_sitemap` | `/article` | `/category` | `/debug`;
>   type DynamicRoutes<T extends string> = `/${CatchAllRoutePart<T>}` | `/${SingleRoutePart<T>}`;
>   type DynamicRouteTemplate = `/[...unmatched]` | `/[id]`;
> ```

and if you wanna patch it with `bun patch` (pnpm is probably the same) you have to patch this patch (lol) by removing all instances of `node_modules/expo-router/`. Otherwise it complains that the file .../generate.js doesn't exist. This patch was probably made for git patch.

**Comment by zowebs** [comment]
The PR [#29612](https://github.com/expo/expo/pull/29612) has been merged. Hopefully new release will contain the fix.

**Comment by alfjesus** [comment]
> The PR [#29612](https://github.com/expo/expo/pull/29612) has been merged. Hopefully new release will contain the fix.

@zowebs Yes, I noticed the same. Hopefully a new release will come very soon.

**Comment by jokinol** [comment]
Maybe worth to mention here, but I was able to fix this issue by migrating from `react-native-dotenv` to Expo environment variables. 

Related issue: https://github.com/goatandsheep/react-native-dotenv/issues/501

**Comment by GabrielDierks** [comment]
@marklawlor @EvanBacon Any ETA when and with which version [#29612](https://github.com/expo/expo/pull/29612) will be released?

**Comment by yourjhay** [comment]
> > I just got the same problem after upgrading to **expo 51** I get the **Welcome to Expo** screen and nothing seems to be working Is there any workaround without downgrading my expo-router @marklawlor
> 
> @George-Acquah This issue is about typed routes in Expo Router not working. Navigation calls to defined routes is working as before with no issues. However, these routes are not typed and therefore I don't get auto completion of available routes for the `href` prop or a typescript error if I put in a route that is not defined.
> 
> But you are saying nothing seems to be working? Are you experiencing more issue than typed routes? If so I think a new issue should be filed to keep these separated.

I can confirm this. expo-router is working fine, how ever it is not typed & I don't get auto completion.
using expo `"expo-router": "~3.5.18",` & `"expo-router": "~3.5.18",`

**Comment by Code-Victor** [comment]
> I'm under Expo 51 as well. `expo@51.0.14` and `expo-router@3.5.16` and I'm facing this typing issue.
> 
> I have built my patch with a combo from @V1RE's [patch](https://github.com/expo/expo/issues/28680#issuecomment-2148084616.) and @bradleyayers's [patch](https://github.com/expo/expo/issues/28680#issuecomment-2184758149). It's all working now.
> 
> ```diff
> diff --git a/node_modules/expo-router/build/typed-routes/generate.js b/node_modules/expo-router/build/typed-routes/generate.js
> index 1e62183..b2b18e5 100644
> --- a/node_modules/expo-router/build/typed-routes/generate.js
> +++ b/node_modules/expo-router/build/typed-routes/generate.js
> @@ -26,7 +26,7 @@ function getTypedRoutesDeclarationFile(ctx) {
>      return (node_fs_1.default
>          .readFileSync(path_1.default.join(__dirname, '../../types/expo-router.d.ts'), 'utf-8')
>          // Swap from being a namespace to a module
> -        .replace('declare namespace ExpoRouter {', `declare module "expo-router" {`)
> +        .replace(`import type { ReactNode } from 'react';\nimport type { TextProps, GestureResponderEvent } from 'react-native';\n\nexport namespace ExpoRouter {`, `declare module "expo-router" {\n  import type { ReactNode } from 'react';\n  import type { TextProps, GestureResponderEvent } from 'react-native';\n  export * from "expo-router/build";\n`)
>          // Add the route values
>          .replace('type StaticRoutes = string;', `type StaticRoutes = ${setToUnionType(staticRoutes)};`)
>          .replace('type DynamicRoutes<T extends string> = string;', `type DynamicRoutes<T extends string> = ${setToUnionType(dynamicRoutes)};`)
> @@ -41,7 +41,8 @@ function walkRouteNode(routeNode, staticRoutes, dynamicRoutes, dynamicRouteConte
>          return;
>      addRouteNode(routeNode, staticRoutes, dynamicRoutes, dynamicRouteContextKeys);
>      for (const child of routeNode.children) {
> -        walkRouteNode(child, staticRoutes, dynamicRoutes, dynamicRouteContextKeys);
> +        const childWithPrefixedRoute = { ...child, route: `${routeNode.route}/${child.route}` };
> +        walkRouteNode(childWithPrefixedRoute, staticRoutes, dynamicRoutes, dynamicRouteContextKeys);
>      }
>  }
>  /**
> ```
> 
> **Before** `.expo/types/router.d.ts`
> 
> ```ts
> import type { ReactNode } from 'react';
> import type { TextProps, GestureResponderEvent } from 'react-native';
> 
> export namespace ExpoRouter {
>   type StaticRoutes = `/` | `/(latest)` | `/(tabs)` | `/_sitemap` | `/article` | `/category` | `/debug`;
>   type DynamicRoutes<T extends string> = `/${CatchAllRoutePart<T>}` | `/${SingleRoutePart<T>}`;
>   type DynamicRouteTemplate = `/[...unmatched]` | `/[id]`;
> ```
> 
> **After** `.expo/types/router.d.ts`
> 
> ```ts
> /* eslint-disable */
> declare module "expo-router" {
>   import type { ReactNode } from 'react';
>   import type { TextProps, GestureResponderEvent } from 'react-native';
>   export * from "expo-router/build";
> 
>   type StaticRoutes = `/` | `/(latest)` | `/(tabs)` | `/_sitemap` | `/article` | `/category` | `/debug`;
>   type DynamicRoutes<T extends string> = `/${CatchAllRoutePart<T>}` | `/${SingleRoutePart<T>}`;
>   type DynamicRouteTemplate = `/[...unmatched]` | `/[id]`;
> ```

This worked for me thanks

**Comment by Jiyr0119** [comment]
> The same for me in all 3.5.x (including 3.5.11) versions. I get the "Welcome to Expo" default screen. None of my routes work. If I "touch" to create an index.js, the file gets created (app/index.tsx), but also does not load on refresh. Version 3.4.10 is working fine.

work for me thanks bro

**Comment by AyoCodess** [comment]
> I'm under Expo 51 as well. `expo@51.0.14` and `expo-router@3.5.16` and I'm facing this typing issue.
> 
> I have built my patch with a combo from @V1RE's [patch](https://github.com/expo/expo/issues/28680#issuecomment-2148084616.) and @bradleyayers's [patch](https://github.com/expo/expo/issues/28680#issuecomment-2184758149). It's all working now.
> 
> ```diff
> diff --git a/node_modules/expo-router/build/typed-routes/generate.js b/node_modules/expo-router/build/typed-routes/generate.js
> index 1e62183..b2b18e5 100644
> --- a/node_modules/expo-router/build/typed-routes/generate.js
> +++ b/node_modules/expo-router/build/typed-routes/generate.js
> @@ -26,7 +26,7 @@ function getTypedRoutesDeclarationFile(ctx) {
>      return (node_fs_1.default
>          .readFileSync(path_1.default.join(__dirname, '../../types/expo-router.d.ts'), 'utf-8')
>          // Swap from being a namespace to a module
> -        .replace('declare namespace ExpoRouter {', `declare module "expo-router" {`)
> +        .replace(`import type { ReactNode } from 'react';\nimport type { TextProps, GestureResponderEvent } from 'react-native';\n\nexport namespace ExpoRouter {`, `declare module "expo-router" {\n  import type { ReactNode } from 'react';\n  import type { TextProps, GestureResponderEvent } from 'react-native';\n  export * from "expo-router/build";\n`)
>          // Add the route values
>          .replace('type StaticRoutes = string;', `type StaticRoutes = ${setToUnionType(staticRoutes)};`)
>          .replace('type DynamicRoutes<T extends string> = string;', `type DynamicRoutes<T extends string> = ${setToUnionType(dynamicRoutes)};`)
> @@ -41,7 +41,8 @@ function walkRouteNode(routeNode, staticRoutes, dynamicRoutes, dynamicRouteConte
>          return;
>      addRouteNode(routeNode, staticRoutes, dynamicRoutes, dynamicRouteContextKeys);
>      for (const child of routeNode.children) {
> -        walkRouteNode(child, staticRoutes, dynamicRoutes, dynamicRouteContextKeys);
> +        const childWithPrefixedRoute = { ...child, route: `${routeNode.route}/${child.route}` };
> +        walkRouteNode(childWithPrefixedRoute, staticRoutes, dynamicRoutes, dynamicRouteContextKeys);
>      }
>  }
>  /**
> ```
> 
> **Before** `.expo/types/router.d.ts`
> 
> ```ts
> import type { ReactNode } from 'react';
> import type { TextProps, GestureResponderEvent } from 'react-native';
> 
> export namespace ExpoRouter {
>   type StaticRoutes = `/` | `/(latest)` | `/(tabs)` | `/_sitemap` | `/article` | `/category` | `/debug`;
>   type DynamicRoutes<T extends string> = `/${CatchAllRoutePart<T>}` | `/${SingleRoutePart<T>}`;
>   type DynamicRouteTemplate = `/[...unmatched]` | `/[id]`;
> ```
> 
> **After** `.expo/types/router.d.ts`
> 
> ```ts
> /* eslint-disable */
> declare module "expo-router" {
>   import type { ReactNode } from 'react';
>   import type { TextProps, GestureResponderEvent } from 'react-native';
>   export * from "expo-router/build";
> 
>   type StaticRoutes = `/` | `/(latest)` | `/(tabs)` | `/_sitemap` | `/article` | `/category` | `/debug`;
>   type DynamicRoutes<T extends string> = `/${CatchAllRoutePart<T>}` | `/${SingleRoutePart<T>}`;
>   type DynamicRouteTemplate = `/[...unmatched]` | `/[id]`;
> ```

any ideas on this?


``patch-package 8.0.0
Applying patches...
Unrecognized patch file in patches directory expo-router@3.5.16.patch``

**Comment by nerixim** [comment]
@AyoCodess 
I believe the filename in your case should be `expo-router+3.5.16.patch`.

**Comment by AyoCodess** [comment]
Thankyou this worked perfectly. When will this PR get merged.

**Comment by alfjesus** [comment]
Expo router v3.5.19 is now released and after updating I can confirm that the typed routes are working again. Thank you @marklawlor ! Closing this issue.

**Comment by RyadOucherif** [comment]
v3.5.19 and not working with nested routes with multipliable layouts
Ex: 
`router.push(`/homes/${item.home.id}`);`

My folder structure:
<img width="196" alt="Capture d’écran 2024-07-30 à 10 14 18" src="https://github.com/user-attachments/assets/ab14a7e3-0aa2-489e-be64-8369a7f40964">

**Comment by jonmcwest** [comment]
v3.5.19 & Still not generating types correctly...

<img width="346" alt="image" src="https://github.com/user-attachments/assets/7dc05fe4-357a-4422-8188-c247ee2e7325">

<img width="986" alt="image" src="https://github.com/user-attachments/assets/9bad8b59-998f-4841-a427-fc9806ab94bf">

**Comment by jonmcwest** [comment]
Type generation is still broken. We are getting routes generated for top level routes but not for their nested navigation stack screens.

**Comment by hanyufoodles** [comment]
I confirm that with expo-router 3.5.19 routes inside nested navigator are not included in generated typed routes.

**Comment by alfjesus** [comment]
Okay.. I can also confirm that nested stack routes doesn't work. Maybe this should be in a new issue?

**Comment by jonmcwest** [comment]
@alfjesus might get it's prioritisation nerfed because it's a new issue.. perhaps bump this one because technically your original statement is still true - "Typed routes not working in Expo 51 and Expo router"

**Comment by alfjesus** [comment]
> @alfjesus might get it's prioritisation nerfed because it's a new issue (not sure how the team prioritises though).. perhaps bump this one because technically your original statement is still true - "Typed routes not working in Expo 51 and Expo router"

I think I create a new issue with title "Typed routes for nested navigators not working in Expo router"

**Comment by alfjesus** [comment]
I'm confused 🤔. After clearing node_modules, .expo folder and run a new clean prebuild the type generation for nested paths seems to be generated correctly again. However, I don't know exactly what I did before it started to work again. At this point I can't replicate the issue with nested navigators and type routes, hence I will not create a new issue right now.

**Comment by Akuma-U1** [comment]
@alfjesus RIP closing issue too soon. 😢 
Is there a way to reopen?

I'm having an issue with any nested navigators as well. Typing seems to be broken. Works for top level files, but anything within groups aka routes in a folder that have `(routeName)` as the folder's name is broken as well.

**Comment by alfjesus** [comment]
@Akuma-U1 I hear you. I will reopen this issue.

**Comment by saulamsal** [comment]
Literally everyone using typed and shared routes is stuck with Expo 49/50.

**Comment by piscis** [comment]
using expo 51 + expo router 3.5.20 I have the same problem having a route to **/foo/bar** will generate the type **"/bar"** when looking into **".expo/types/router.de.ts"** the parent directory **"foo"** is missing. Having a route like "(root)/barz" will generate typings **"/(root)/barz"** and **"/barz"**

The only workaround I found to be able to ship is disable typedRoutes by switching it of in app.json

```json
"experiments": {
   "typedRoutes": false
},
```

I also tried to regenerate the project with expo prebuild --clean / expo run:ios but this did nothing

**Comment by iamdanajr** [comment]
Same for me

**Comment by sobrinho** [comment]
Same here

**Comment by DanielAdari** [comment]
Same here

**Comment by belkocik** [comment]
Error with  3.5.20 `expo-router`
```js
Type '"/(auth)/(tabs)/explore"' is not assignable to type 'Href<string | object>'.ts(2322)
Link.d.ts(55, 5): The expected type comes from property 'href' which is declared here on type 'IntrinsicAttributes & LinkProps<string | object> & { children?: ReactNode; }'
⚠ Error (TS2322)  | 
Type 
 is not assignable to type 
 .
(property) LinkProps<string | object>.href: Href<string | object>
```

**Comment by sobrinho** [comment]
Fixed for me as well, thanks! ❤️

**Comment by austinm911** [comment]
I'm still getting this issue on 3.5.21 @marklawlor 

Is it perhaps because my dir structure is 
./src/mobile/app/(tabs) and so forth?

**Comment by tventura-africell** [comment]
> Fixed in expo ~51.0.5 expo router: ~3.5.12....if build has an error delete node_modules folder and run npm install again.

worked for me

**Comment by andflett** [comment]
Fixed me for, had to delete `.expo` directory first though.

**Comment by mercyaj** [comment]
Type checks seem to fail when passing search parameters using expo 51.0.26 and expo router 3.5.21:

``/folder1/folder2/${item.id}`` passes fine, but ``/folder1/folder2/${item.id}?name=${item.name}`` gives the error:
``` 
Argument of type '`/folder1/folder2/${item.id}?name=${item.name}`' is not assignable to parameter of type 'Href<`/folder1/folder2/${item.id}?name=${item.name}`>'`
```

I've deleted the .expo directory and node_modules and npm installed.

**Comment by piscis** [comment]
@mercyaj  I had the same problem and I noticed that it should possible to do it with a  dynamic route object config.

instead of using a string like: `/folder1/folder2/${item.id}?name=${item.name}`>'` 

I do the following:

```ts
router.navigate({
  pathname: "/folder1/folder2/[id]",
  params: {
    id: item.id, // gets passed as a route parameter
    name: item.name // gets passed as a query parameter
  }
})
...

const { name } = useLocalSearchParam();

```
I'm also not sure if it should be possible to pass query params in a string looking at the type definitions for `Href` I see a `SearchOrHash` type so could be a bug? Would be awesome if it would work with strings too

**Comment by mercyaj** [comment]
Thanks @piscis - I can confirm that works :)

The docs seem to suggest that passing search params directly in the string should work:

[https://docs.expo.dev/router/reference/url-parameters/#statically-typed-url-parameters](https://docs.expo.dev/router/reference/url-parameters/#statically-typed-url-parameters)
___
<img width="663" alt="Screenshot 2024-08-10 at 16 53 12" src="https://github.com/user-attachments/assets/7f5b4641-5adc-404e-9416-139319e01c72">


___
<img width="662" alt="Screenshot 2024-08-10 at 16 51 28" src="https://github.com/user-attachments/assets/ef65e54e-4fb6-4e6a-b132-411c801f8f44">

**Comment by RyadOucherif** [comment]
Passing params for nested routes directly as string is still not working. 

This is working: 
`
 router.push({
    pathname: "/users/[id]/reviews",
    params: { id: data.id },
  })
`

and not this code:
`
router.push(`/users/${data.id}/reviews`)
`

**Comment by paolotremadio** [comment]
Expo router `3.5.21` fixed most of the issues for me but I still get an error:

```log
 error TS2345: Argument of type '{ pathname: Routes; params: { id: string; }; }' is not assignable to parameter of type 'Href<string | object>'.
  Type '{ pathname: Routes; params: { id: string; }; }' is not assignable to type '{ pathname: "/"; params?: RouteParamInput<"/"> | undefined; } | { pathname: "/(main)"; params?: RouteParamInput<"/(main)"> | undefined; } | { pathname: "/(main)/(overlays)/standard/automation-mode"; params?: RouteParamInput<...> | undefined; } | ... 72 more ... | { ...; }'.
    Type '{ pathname: Routes; params: { id: string; }; }' is not assignable to type '{ pathname: `${string}:${string}`; params?: RouteParamInput<`${string}:${string}`> | undefined; }'.
      Types of property 'pathname' are incompatible.
        Type 'Routes' is not assignable to type '`${string}:${string}`'.

93     router.navigate({ pathname: getViewUrlByType('custom_v1'), params: { id: viewId } });
```

Caller code (causing the error):
```typescript
import { Routes, useRouter } from 'expo-router';

export const getViewUrlByType = (viewType: string): Routes => {
  return '/'; // This is a valid route, I actually have a switch statement in there but I'm simplifying 
}

const router = useRouter();
router.navigate({ pathname: getViewUrlByType('custom_v1'), params: { id: viewId } });
```


router.d.ts:
```typescript
/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string = string> extends Record<string, unknown> {
      StaticRoutes: `/` | `/(main)` | `/(main)/(overlays)/standard/automation-mode` | `/(main)/(overlays)/standard/climate` | `/(main)/(overlays)/standard/custom-v1` | `/(main)/(overlays)/standard/generic-appliance` | `/(main)/(overlays)/standard/light` | `/(main)/(overlays)/standard/ventilation` | `/(main)/(overlays)/standard/window-covering` | `/(main)/floorplan` | `/(main)/player/compact-player-modal` | `/(main)/player/extended-player-modal` | `/(main)/settings` | `/(main)/settings/` | `/(main)/settings/app-update` | `/(main)/settings/batteries` | `/(main)/settings/faulty` | `/(main)/settings/site-membership` | `/(main)/settings/site-membership/` | `/(main)/settings/site-membership/helpers` | `/(main)/settings/site-membership/invitation` | `/(main)/settings/site-membership/profile` | `/(main)/settings/system-info` | `/(main)/standard/automation-mode` | `/(main)/standard/climate` | `/(main)/standard/custom-v1` | `/(main)/standard/generic-appliance` | `/(main)/standard/light` | `/(main)/standard/ventilation` | `/(main)/standard/window-covering` | `/(overlays)/standard/automation-mode` | `/(overlays)/standard/climate` | `/(overlays)/standard/custom-v1` | `/(overlays)/standard/generic-appliance` | `/(overlays)/standard/light` | `/(overlays)/standard/ventilation` | `/(overlays)/standard/window-covering` | `/_sitemap` | `/floorplan` | `/onboarding` | `/onboarding/done` | `/onboarding/invitation` | `/onboarding/legacy-code` | `/onboarding/legacy-failed-wrong-code` | `/onboarding/legacy-verify-code` | `/onboarding/open-link-prompt` | `/onboarding/permission-bluetooth` | `/onboarding/permission-components` | `/onboarding/permission-location-background` | `/onboarding/permission-location-foreground` | `/onboarding/permission-notifications` | `/player/compact-player-modal` | `/player/extended-player-modal` | `/settings` | `/settings/` | `/settings/app-update` | `/settings/batteries` | `/settings/faulty` | `/settings/site-membership` | `/settings/site-membership/` | `/settings/site-membership/helpers` | `/settings/site-membership/invitation` | `/settings/site-membership/profile` | `/settings/system-info` | `/standard/automation-mode` | `/standard/climate` | `/standard/custom-v1` | `/standard/generic-appliance` | `/standard/light` | `/standard/ventilation` | `/standard/window-covering` | `/v1`;
      DynamicRoutes: never;
      DynamicRouteTemplate: never;
    }
  }
}

```

**Comment by kimdanielarthur-cowlabs** [comment]
Also experiencing the issue related to expecting a pathname to be an `ExternalPathString` aka `${string}:${string}` when passing an object { pathname:"/", params: {key:value}}, it seems the types.d.ts for expo router has
```/**
 * Converts a static route to a Href object
 */
type StaticRouteToHrefObject<T extends string = string> = T extends any ? {
    pathname: T;
    params?: RouteParamInput<T> | never;
} : never;```

should the pathname type also be including StaticRoutes somehow?

**Comment by AWill-EEC** [comment]
Using

```
"expo": "^51.0.26",
"expo-router": "~3.5.21",
```

And the following code does not function as expected - 

`router.replace('/')`

![image](https://github.com/user-attachments/assets/7eee3bd5-ac8d-40ac-a9e3-7f49df435edd)

Also tried using 

`router.navigate('/')` w/ the same behavior

**Comment by sobrinho** [comment]
eas update is not working with typed routes:

```
Run eas update --auto --non-interactive
- Exporting...
[expo-cli] Starting Metro Bundler
[expo-cli] 
[expo-cli] iOS Bundling failed 78926ms node_modules/expo-router/entry.js (1815 modules)
[expo-cli] TypeError: (0 , sourceMapString_1.default) is not a function
[expo-cli] TypeError: (0 , sourceMapString_1.default) is not a function
[expo-cli]     at Chunk.serializeToAssetsAsync (/home/runner/work/myapp-mobile/myapp-mobile/node_modules/@expo/metro-config/src/serializer/serializeChunks.ts:455:24)
[expo-cli]     at /home/runner/work/myapp-mobile/myapp-mobile/node_modules/@expo/metro-config/src/serializer/serializeChunks.ts:621:25
[expo-cli]     at Array.map (<anonymous>)
[expo-cli]     at serializeChunksAsync (/home/runner/work/myapp-mobile/myapp-mobile/node_modules/@expo/metro-config/src/serializer/serializeChunks.ts:619:17)
[expo-cli]     at graphToSerialAssetsAsync (/home/runner/work/myapp-mobile/myapp-mobile/node_modules/@expo/metro-config/src/serializer/serializeChunks.ts:150:26)
[expo-cli]     at /home/runner/work/myapp-mobile/myapp-mobile/node_modules/@expo/metro-config/src/serializer/withExpoSerializers.ts:263:50
[expo-cli]     at serializer (/home/runner/work/myapp-mobile/myapp-mobile/node_modules/@expo/metro-config/src/serializer/withExpoSerializers.ts:296:12)
[expo-cli]     at MetroBundlerDevServer._bundleDirectAsync (/home/runner/work/myapp-mobile/myapp-mobile/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:1026:28)
[expo-cli]     at MetroBundlerDevServer.metroLoadModuleContents (/home/runner/work/myapp-mobile/myapp-mobile/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:442:21)
[expo-cli]     at MetroBundlerDevServer.legacySinglePageExportBundleAsync (/home/runner/work/myapp-mobile/myapp-mobile/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:553:20)
[expo-cli]     at /home/runner/work/myapp-mobile/myapp-mobile/node_modules/@expo/cli/src/export/exportApp.ts:137:26
[expo-cli]     at async Promise.all (index 0)
[expo-cli]     at exportAppAsync (/home/runner/work/myapp-mobile/myapp-mobile/node_modules/@expo/cli/src/export/exportApp.ts:127:7)
[expo-cli]     at exportAsync (/home/runner/work/myapp-mobile/myapp-mobile/node_modules/@expo/cli/src/export/exportAsync.ts:19:3)
✖ Export failed
/home/runner/work/myapp-mobile/myapp-mobile/node_modules/expo/bin/cli exited with non-zero code: 1
    Error: update command failed.
Error: Process completed with exit code 1.

**Comment by gorbypark** [comment]
> Type checks seem to fail when passing search parameters using expo 51.0.26 and expo router 3.5.21:
> 
> `/folder1/folder2/${item.id}` passes fine, but `/folder1/folder2/${item.id}?name=${item.name}` gives the error:
> 
> ```
> Argument of type '`/folder1/folder2/${item.id}?name=${item.name}`' is not assignable to parameter of type 'Href<`/folder1/folder2/${item.id}?name=${item.name}`>'`
> ```
> 
> I've deleted the .expo directory and node_modules and npm installed.

Try using the object syntax and passing the params that way.  For example:
```ts
      <Link
        href={{
          pathname: "/folder1/folder2/[id]",
          params: {
            id: item.id,
            name: item.name
          },
        }}
      >
        Hello
      </Link>
 ```

**Comment by AlexMachin1997** [comment]
Glad to see this issue closed 😄 

I've just given this a whirl looks like whatever changes were made resolved the issue, awesome work guys 😉

**Comment by sobrinho** [comment]
eas update is still not working with typed routes 🥹

**Comment by Rajrup-TransEV** [comment]
still not working for fresh projects

**Comment by KazutoMartin** [comment]
I'm following along with expo website tutorial
Im having the same problem

**Comment by trajano** [comment]
removing .expo folder helps

**Comment by Rajrup-TransEV** [comment]
removed and re tried - did not worked @trajano

**Comment by trajano** [comment]
@Rajrup-TransEV  did you check if the `.expo/types/router.d.ts` looks correct?  It should be recreated with the routes that are present when you do a `npx expo start -c`
