### ISSUE TITLE
React Native Gesture Handler not detecting gestures in conjunction with CameraView starting in SDK 51

### ISSUE THREAD

**Issue by rbrki07** [expo/expo#28966]
### Minimal reproducible example

https://github.com/rbrki07/react-native-gesture-handler-test

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

I would like to have a React Native Gesture Handler on top of `CameraView` of `expo-camera` to detect certain gestures like long press or double tap. This was possible in SDK 50 using `Camera` of `expo-camera/legacy`, but it is no longer possible in SDK 51 and `CameraView` of `expo-camera`. 

This is only a problem on iOS. If you run the example on Android, the gestures will be recognized.

I guess this is more related to `CameraView` and less to the way React Native Gesture Handler is used in the example. If you run the example, you can try to open the Expo developer menu using the iOS specific 3 finger tab gesture, and it won't work.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - /usr/local/bin/node
      npm: 10.3.0 - /usr/local/bin/npm
      Watchman: 2024.01.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 9.0.7
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by pablobarreraf** [comment]
Yes this is happening to me too, I had to add a toggle above my camera view trigger which changes the state of the cameraMode before capturing a picture or a video if I try to change the cameraMode on the fly on the event of a longPress is not working.

**Comment by rbrki07** [comment]
Hey @brentvatne 👋,
could you please have a look at this issue? This issue is stale for 16 days and I wonder, if there is something missing here?

**Comment by brentvatne** [comment]
hey @rbrki07! we will investigate. apologies for the delay, a lot of the team was busy for the last couple weeks with various conferences.

**Comment by rbrki07** [comment]
Thanks for your response! Yes, it's the time of the year with React Native Conf and App.js Conf 😅 I've seen some cool new stuff!

**Comment by alanjhughes** [comment]
Hi @rbrki07 this was resolved by #28829. I've tested it against repro and it is working now

**Comment by rbrki07** [comment]
Hi @alanjhughes,
I updated the minimal reproducible example (https://github.com/rbrki07/react-native-gesture-handler-test) and did a test on iOS. Unfortunately, the problem still exists: Gestures like long press or double tap are not detected on top of `CameraView` of `expo-camera`. If you run the example, you can try to open the Expo developer menu using the iOS specific 3 finger tab gesture, and you should see it won't work.

**Comment by alanjhughes** [comment]
Hi @rbrki07 - I have addressed this in #30338. Thanks for following up!

**Comment by alanjhughes** [comment]
@MarianAlexandruAlecu - no, because the simulator will never render the camera view. You'll just see a black view where it would be

**Comment by rbrki07** [comment]
Hi @alanjhughes,
was #30338 shipped with expo-camera 15.0.14? I can still reproduce the error in expo-camera 15.0.14.
