### ISSUE TITLE
Expo 51 Crashes when Using Google Font: Inter_600SemiBold (iOS Only)

### ISSUE THREAD

**Issue by yachtwave** [expo/expo#29030]
### Minimal reproducible example

https://github.com/xpario/expo.51.sdk-error

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Starting with Expo 51 - not sure when it began, just upgraded from Expo 50 to 51.08. In the iOS Expo Go crashes hard (simulator and on the phone) if you attempt to use Google Font 'Inter_600SemiBold' in your Text style. There is no problem with the Android simulator. All of the other Inter fonts are fine. For the Minimal Example, I downloaded Inter from Google fonts fresh from Google to eliminate any chance of corrupt files. We have been using this font since Expo 46 with no issues.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.13.1 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.8.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.8 => 51.0.8
      react: 18.2.0 => 18.2.0
      react-native: ^0.74.1 => 0.74.1
    npmGlobalPackages:
      eas-cli: 9.0.7
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by raajnadar** [comment]
The main issue is there are no logs it is a hard crash on Expo Go, and it happens with that specific font type only

**Comment by raajnadar** [comment]
Please add your log in a spoiler it is so long

Check this issue, maybe this also solves your problem of crashing - https://github.com/expo/expo/issues/29018

**Comment by ptupi** [comment]
Hey everyone. I had to remove Inter_200ExtraLight, Inter_600SemiBold and Inter_800ExtraBold everywhere. I've replaced them.

**Comment by SenadAlagic** [comment]
> Hey everyone. I had to remove Inter_200ExtraLight, Inter_600SemiBold and Inter_800ExtraBold everywhere. I've replaced them.

What do you mean by remove and replace? I have the exact same issue as you so the fix would be welcome 😅.

**Comment by ptupi** [comment]
> > Hey everyone. I had to remove Inter_200ExtraLight, Inter_600SemiBold and Inter_800ExtraBold everywhere. I've replaced them.
> 
> What do you mean by remove and replace? I have the exact same issue as you so the fix would be welcome 😅.

:D, sorry, my bad.
I've removed them from the "InterFonts" imports and declarations.

_________________________________________________________________________________________________

import {
  Inter_100Thin,
  Inter_300Light,
  Inter_400Regular,
  Inter_500Medium,
  Inter_700Bold,
  Inter_900Black,
} from '@expo-google-fonts/inter';

export const InterFonts = {
  Inter_100Thin,
  Inter_300Light,
  Inter_400Regular,
  Inter_500Medium,
  Inter_700Bold,
  Inter_900Black,
};

const [fontsLoaded] = useFonts(InterFonts);

_________________________________________________________________________________________________

And I've replaced "ExtraLight" with "Light", and "SemiBold" and "ExtraBold" with "Bold". Nothing too crazy.

**Comment by akkilaa** [comment]
I'm confirming this also, I was using Inter_600SemiBold and my IOS app was crashing right when the Text was called with that font. The Interesting fact is that it was happening only first time when the app was opened, on the second time it was working and app wasn't crashing.

**Comment by akkilaa** [comment]
I just swapped "Inter_600SemiBold" with "Inter_500Medium" and it's not crashing anymore.

**Comment by raajnadar** [comment]
@akkilaa that is not a solution, If just tested by following the app.json configuration the crash is gone on iOS but on android I am unable to use the fonts (Tested on expo go both android & ios)

https://docs.expo.dev/develop/user-interface/fonts/#with-config-plugin

**Comment by stanleyugwu** [comment]
Just fyi this still happens on `expo 51.0.9` and `expo-font 12.0.6` which are the latest versions

**Comment by Gnative** [comment]
https://github.com/expo/google-fonts/issues/109

**Comment by antoniogoulao** [comment]
> Just fyi this still happens on `expo 51.0.9` and `expo-font 12.0.6` which are the latest versions

Same for `expo 51.0.10`

**Comment by RodriguesCosta** [comment]
Same errors here with fonts:  Poppins_700Bold, Poppins_600SemiBold, Poppins_400Regular

**Comment by raajnadar** [comment]
We can close the issue the problem is addressed and published https://github.com/expo/expo/pull/29502

**Comment by lukmccall** [comment]
Closed by https://github.com/expo/expo/pull/29502

**Comment by Hamza-readyOn** [comment]
For IOS I am still getting this issue in Expo go with the latest versions.
"expo": "^51.0.11",
"expo-font": "12.0.7",

I also confirmed the latest changes in my node_modules. (node_modules/expo-font/ios/FontLoaderModule.swifft)


  if let postScriptName = font.postScriptName as? String {
        FontFamilyAliasManager.setAlias(fontFamilyAlias, forFamilyName: postScriptName)
      }

**Comment by hamzaayub402** [comment]
For IOS I am still getting this issue in Expo go with the latest versions.
"expo": "^51.0.11",
"expo-font": "12.0.7",

I also confirmed the latest changes in my node_modules. (node_modules/expo-font/ios/FontLoaderModule.swifft)

if let postScriptName = font.postScriptName as? String {
        FontFamilyAliasManager.setAlias(fontFamilyAlias, forFamilyName: postScriptName)
      }

**Comment by zagazat** [comment]
You need to install the Inter fonts on your Mac, then probably your "Inter-400", "Inter-600", etc. variants are combined into one "Inter" family. So you can use general `fontFamily: "Inter"`, and just use `fontWeight: '400'`. 

```
const [fontsLoaded, fontError] = useFonts({
    'Inter-400': require('./assets/fonts/Inter/static/Inter-Regular.ttf'),
    'Inter-500': require('./assets/fonts/Inter/static/Inter-Medium.ttf'),
    'Inter-600': require('./assets/fonts/Inter/static/Inter-SemiBold.ttf'),
    'Inter-700': require('./assets/fonts/Inter/static/Inter-Bold.ttf'),
});

const styles = StyleSheet.createStyle({
   app: {
       fontFamily: 'Inter',
   }
})
```

https://codewithchris.com/common-mistakes-with-adding-custom-fonts-to-your-ios-app/

**Comment by jcachuryb** [comment]
Hi, this is still happening with 
expo@51.0.28
expo-font@12.0.9

It happens after I use expo-camera, then close it, then try to open an ActionSheet that has a text with the fontFamily attribute: 
fontFamily={"Roboto_500Medium"}

Thread 20 Crashed::  Dispatch queue: com.facebook.react.ShadowQueue

3   Expo Go                       	       0x100968e88 weightOfFont(UIFont*) + 212
RCTFont updateFont:withFamily:size:weight:style:variant:scaleMultiplier

**Comment by nabilfreeman** [comment]
We are still getting this intermittently in production. Here is a screenshot of the stack trace from Sentry:

<img width="1156" alt="Screenshot 2024-08-21 at 14 52 17" src="https://github.com/user-attachments/assets/eb780a00-d696-4b2f-8d13-eb1fd6301423">

**Comment by vinrei** [comment]
I am still experiencing intermittently in production (iOS only) with
expo@51.0.31
expo-font@12.0.9

I don't actually specify a different font from the lib defaults in my app.

<img width="641" alt="Screenshot 2024-09-02 at 9 11 22 AM" src="https://github.com/user-attachments/assets/69078c21-f859-40eb-9ef5-58e674292e37">

**Comment by vinrei** [comment]
@lukmccall @raajnadar do you guys have any insight into this iOS intermittent fontNames error? For me I'm not specifying a specific font and the error only occurs on certain larger iPhones: mainly 15 pro max, 12 pro max.
 It's hitting 1% of my users. No luck yet reproducing it on my simulator. I'm using latest versions of expo & expo-font.
<img width="824" alt="image" src="https://github.com/user-attachments/assets/e35f801c-44ea-4cad-91c9-f6a0a76ef530">

**Comment by lukmccall** [comment]
@vinrei could you create a new issue and describe your problem there?

**Comment by events-jonas-chrisw** [comment]
> @lukmccall @raajnadar do you guys have any insight into this iOS intermittent fontNames error? For me I'm not specifying a specific font and the error only occurs on certain larger iPhones: mainly 15 pro max, 12 pro max. It's hitting 1% of my users. No luck yet reproducing it on my simulator. I'm using latest versions of expo & expo-font. <img alt="image" width="824" src="https://private-user-images.githubusercontent.com/38410447/367558139-e35f801c-44ea-4cad-91c9-f6a0a76ef530.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzYxMDYsIm5iZiI6MTcyNjQ3NTgwNiwicGF0aCI6Ii8zODQxMDQ0Ny8zNjc1NTgxMzktZTM1ZjgwMWMtNDRlYS00Y2FkLTkxYzktZjZhMGE3NmVmNTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA4MzY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYWZjZGE2NjFlNjVkNjZjYjZmNzI4N2IwOGQ1MzdiNjZhZjFiODVjMmQ0YzUzNGY3N2ZkZjQ4ZjNmMGJkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lPZDaVJmTidOjYJ0Gv9QYFU7m-trxyjIF9CTY4YHJ70">

ame problem here - weird thing is, it only seems to happen once per user

**Comment by emilje-cap** [comment]
Same problem as @vinrei . Unable to reproduce the crash, but a huge amount of users are affected on ios with the 
"Dictionary.subscript.getter (FontFamilyAliasManager.swift)" crash. Has a new thread been created?

**Comment by lukmccall** [comment]
@emilje-cap Could you create a new issue? It will be easier to track.
