### ISSUE TITLE
[iOS][expo-file-system][SDK51] Asset is not readable on iPhone XS Max and older in standalone build.

### ISSUE THREAD

**Issue by NikitaDudin** [expo/expo#29759]
### Minimal reproducible example

https://github.com/NikitaDudin/ios-assets-standalone

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (only happens in a standalone build)

### Summary

Embedded assets not loaded in production build on iPhone XS Max and older versions.
Tested on iPhone XS Max, iPhone 8 and iPhone 7.

```TS
import { Asset } from 'expo-asset';

const [asset] = await Asset.loadAsync(require('../image.png'));

await readAsStringAsync(asset.localURI, { encoding: 'base64' });
/* 
error in standalone app: Calling the 'readAsStringAsync' function has failed -> 
Caused by: File '/var/mobile/Containers/Data/Application/0973AB0F-35AB-4061-9CE5-101B2C674F81/Library/Application%20Support/.expo-internal/deaf581986ecc87e8742fcbf07daf94f.png' 
is not readable.
*/
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.14.0/bin/yarn
      npm: 10.8.1 - ~/.nvm/versions/node/v20.14.0/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/lib/ruby/gems/3.3.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 30, 31, 33, 34, 34, 34
        Build Tools: 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 35.0.0
        System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
        Android NDK: 26.1.10909125
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      react: ~18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.74.2 => 0.74.2 
    npmGlobalPackages:
      eas-cli: 9.2.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by NikitaDudin** [comment]
Receives localUri has next form: `file:///var/mobile/Containers/Data/Application/${APP_HASH}/Library/Application%20Support/.expo-internal/${ASSET_HASH}.${ASSET_TYPE}`;
This path unreadable on iPhone XS Max and older.

But it works after modifying localUri to next form: `${cacheDirectory}ExponentAssets-${ASSET_HASH}.${ASSET_TYPE}` -> `file:///var/mobile/Containers/Data/Application/${APP_HASH}/Library/Caches/ExponentAssets-${ASSET_HASH}.${ASSET_TYPE}`


```TS
import { Asset } from 'expo-asset';
import { cacheDirectory, readAsStringAsync } from 'expo-file-system';

const [asset] = await Asset.loadAsync(require('../image.png'));
const fixedFileURI = `${cacheDirectory}ExponentAsset-${asset.hash}.${asset.type}`;
await readAsStringAsync(fixedFileURI, { encoding: 'base64' }); // file load succesfully.
```

**Comment by NikitaDudin** [comment]
Seems like an error in [filesystem path permission func](https://github.com/expo/expo/blob/d185e11df0e6adee8ba8b6fcbc1f3bfbeda9b74f/packages/expo-file-system/ios/FileSystemHelpers.swift#L66).

**Comment by NikitaDudin** [comment]
In development mode, the correct function for the local asset is called: [getInternalPathPermissions](https://github.com/expo/expo/blob/d185e11df0e6adee8ba8b6fcbc1f3bfbeda9b74f/packages/expo-modules-core/ios/FileSystemUtilities/FileSystemLegacyUtilities.swift#L89).
But in production mode on iPhone XS and older the permission request function is terminated at this [point](https://github.com/expo/expo/blob/d185e11df0e6adee8ba8b6fcbc1f3bfbeda9b74f/packages/expo-modules-core/ios/FileSystemUtilities/FileSystemLegacyUtilities.swift#L87). Always returns an empty array

**Comment by kamil6311** [comment]
Hey I have the exact same problem

**Comment by Kudo** [comment]
hi there! since you are reading the icon asset, please try to use base64 encoding instead:

```diff
--- a/App.js
+++ b/App.js
@@ -7,9 +7,9 @@ import { StyleSheet, Text, View } from 'react-native';
 export default function App() {
   useEffect(() => {
     (async () => {
-      const [asset] = Asset.loadAsync(require('./assets/icon.png'));
+      const [asset] = await Asset.loadAsync(require('./assets/icon.png'));

-      await readAsStringAsync(asset.localUri); // error in iOS standalone app in iPhone XS and older versions.
+      await readAsStringAsync(asset.localUri, { encoding: 'base64' }); // error in iOS standalone app in iPhone XS and older versions.
     })();
   }, []);

```

**Comment by NikitaDudin** [comment]
@Kudo thanks! I updated example, but in first message wrote code sample with base64 encoding and it not working on iPhone XS and older.

**Comment by Kudo** [comment]
@NikitaDudin sorry i missed the original code in the issue. did you know whether this issue is only happened on iphone xs and older. how about newer iphone?

**Comment by NikitaDudin** [comment]
@Kudo Also I tested on iphone 11, iphone 14 and it works fine.

**Comment by Kudo** [comment]
good to know. well, now the problem is that we have to find an old iphone 🤔

**Comment by NikitaDudin** [comment]
@Kudo Seems like issue with path or URL creating in this [guard](https://github.com/expo/expo/blob/d185e11df0e6adee8ba8b6fcbc1f3bfbeda9b74f/packages/expo-modules-core/ios/FileSystemUtilities/FileSystemLegacyUtilities.swift#L86-L88).

**Comment by Kudo** [comment]
i tested on iphone 7 plus / ios 15.8.2 / expo go upon your [latest commit](https://github.com/NikitaDudin/ios-assets-standalone/commit/a2bb5678b8055af9a71e60cbf034bf07503a30b1). it works for me though

**Comment by NikitaDudin** [comment]
I have problems in standalone production build only.

**Comment by NikitaDudin** [comment]
1. Build archive in xcode, install and run on device.
2. Build and submit to tesflight via EAS, insatll and run on device.

**Comment by Kudo** [comment]
it's hard for me to test it on testflight, but installing through xcode works for me through.

if you can run through xcode, could you try to help adding breakpoints and debug the stacktrace on these two places?
- https://github.com/expo/expo/blob/25b4f6fd1f34e99fee375cfbae0bbbc9efea1cd5/packages/expo-file-system/ios/FileSystemHelpers.swift#L67
- https://github.com/expo/expo/blob/25b4f6fd1f34e99fee375cfbae0bbbc9efea1cd5/packages/expo-file-system/ios/FileSystemModule.swift#L59

**Comment by NikitaDudin** [comment]
@Kudo, I'll check tomorrow. I don't have the necessary devices right now.
@kamil6311 could you please provide the iOS version for your iPhone X?

**Comment by NikitaDudin** [comment]
@Kudo Checked on iphone 8 / ios 16.7.2:

Error occur at this step:
https://github.com/expo/expo/blob/25b4f6fd1f34e99fee375cfbae0bbbc9efea1cd5/packages/expo-file-system/ios/FileSystemHelpers.swift#L67 

Error appears after adding expo-updates to project and set "updates.url".
I updated [sample](https://github.com/NikitaDudin/ios-assets-standalone) project.

**Comment by kamil6311** [comment]
> @Kudo, I'll check tomorrow. I don't have the necessary devices right now. @kamil6311 could you please provide the iOS version for your iPhone X?

It's an iPhone X with iOS 16.7.2

**Comment by kamil6311** [comment]
Tested Today with an xcode build and an iphone x (iOS 16.7.2): 

`await FileSystem.readAsStringAsync(DATA_PATH);`

ERROR LOG:
[Error: Calling the 'readAsStringAsync' function has failed
→ Caused by: File '/var/mobile/Containers/Data/Application/261E9B9D-E465-4BD5-BF1F-CF1FAB712971/Library/Application Support/com.xxx.xxxx/RCTAsyncLocalStorage_V1/appintent.json' is not readable]

**Comment by NilsBaumgartner1994** [comment]
Yes, problem still exists here too

**Comment by Kudo** [comment]
before delivering the fix, could someone help to apply #29958 locally and check whether the fix works?

**Comment by NikitaDudin** [comment]
@Kudo checked on iphone 8 / ios 16.7.2. Seems to be working fine.

**Comment by NikitaDudin** [comment]
Fixed in expo@51.0.16, expo-modules-core@1.12.17.
@Kudo Thank you!

**Comment by denissb** [comment]
The error still happens for me on:
- expo-modules-core@npm:1.12.18
- expo@51.0.18

**Comment by lichmac** [comment]
I got the error

yarn why expo-modules-core
└─ expo@npm:51.0.22
   └─ expo-modules-core@npm:1.12.19 (via npm:1.12.19)
