### ISSUE TITLE
[expo-router] test-library/index.js in npm distribution contains unmerged content

### ISSUE THREAD

**Issue by hanyufoodles** [expo/expo#30717]
### Minimal reproducible example

N/A

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

The content of `expo-router/build/testing-library/index.js` contains following unmerged content:
https://github.com/expo/expo/blob/36a88d090e5a39949e193f9ee91d94807e59057e/packages/expo-router/build/testing-library/index.js#L45-L53
The file is not valid javascript and is causing tests to fail.

### Environment

expo-router: 3.5.19

**Comment by brentvatne** [comment]
thanks for the report, this is fixed in expo-router@~3.5.20

**Comment by mlukasik-dev** [comment]
After updating expo-router to version 3.5.19, I encountered the following error:
```
../../node_modules/expo-router/build/qualified-entry.js: _getAssignmentIdentifiers is not a function
```
This error is breaking the development build. I have already tried clearing the cache, but the issue persists.
Unfortunately, updating to version 3.5.20 did not resolve the issue as I had hoped.

Does anyone know what might be causing this problem?

**Comment by marklawlor** [comment]
@mlukasik-dev Can you please create a new issue with a full reproduction. `_getAssignmentIdentifiers` is not a function in Expo Router, it is part of the Babel package `babel-traverse` and originates from `@babel/types` ([source](https://github.com/babel/babel/blob/992c6e062efba7e1ef27a0bb02c66ae8800f3e24/packages/babel-traverse/src/path/family.ts#L6))

Therefor to reproduce this issue will we need you to create a reproduction repo as its most likely a conflict with the babel transform / expo packages
