### ISSUE TITLE
Expo SDK51 crash in real android device (only debug app)

### ISSUE THREAD

**Issue by benomzn** [expo/expo#30764]
### Minimal reproducible example

https://github.com/benomzn/test-android-app-crash-sdk51-min-repro

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Hello, I'm testing an app (in debug mode) on a real android device, and it's giving me this error:

![image](https://github.com/user-attachments/assets/443189eb-9010-4bc1-b721-5251d6d8c079)

**The exception stack trace:**
{
  "appName": "test-app-android",
  "timestamp": 1722531018970,
  "message": "No virtual method setSystemGestureExclusionRects(Ljava/util/List;)V in class Lexpo/modules/devmenu/DevMenuReactRootViewContainer; or its super classes (declaration of 'expo.modules.devmenu.DevMenuReactRootViewContainer' appears in /data/app/com.anonymous.testappandroid-EfODu1NoTA9EYK14NNDClw==/base.apk!classes2.dex)",
  "runtimeVersion": "",
  "sdkVersion": "",
  "appVersion": "1.0.0",
  "stack": "java.lang.Throwable: No virtual method setSystemGestureExclusionRects(Ljava/util/List;)V in class Lexpo/modules/devmenu/DevMenuReactRootViewContainer; or its super classes (declaration of 'expo.modules.devmenu.DevMenuReactRootViewContainer' appears in /data/app/com.anonymous.testappandroid-EfODu1NoTA9EYK14NNDClw==/base.apk!classes2.dex)\n\tat expo.modules.devmenu.DevMenuReactRootViewContainer$updateSystemGestureExclusionRects$1.invoke(DevMenuReactRootViewContainer.kt:35)\n\tat expo.modules.devmenu.DevMenuReactRootViewContainer$updateSystemGestureExclusionRects$1.invoke(DevMenuReactRootViewContainer.kt:22)\n\tat expo.modules.devmenu.DevMenuReactRootViewContainer.onLayout(DevMenuReactRootViewContainer.kt:53)\n\tat android.view.View.layout(View.java:22419)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6584)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat android.view.View.layout(View.java:22419)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6584)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1565)\n\tat android.view.View.layout(View.java:22419)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6584)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat android.view.View.layout(View.java:22419)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6584)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1565)\n\tat android.view.View.layout(View.java:22419)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6584)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat com.android.internal.policy.DecorView.onLayout(DecorView.java:1041)\n\tat android.view.View.layout(View.java:22419)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6584)\n\tat android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3375)\n\tat android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2839)\n\tat android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1885)\n\tat android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8508)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)\n\tat android.view.Choreographer.doCallbacks(Choreographer.java:761)\n\tat android.view.Choreographer.doFrame(Choreographer.java:696)\n\tat android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)\n\tat android.os.Handler.handleCallback(Handler.java:873)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loop(Looper.java:214)\n\tat android.app.ActivityThread.main(ActivityThread.java:7050)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)\n"
}

I created a new app using sdk51, and it continues to give the same error on the real device. The application crashes when you try to open it. In release mode, it works well.

I cleaned cache, prebuild directories, I restarted the device and the laptop where expo server is running. I tried another device, and it worked, it's only on this one (maybe the api level version idk). Maybe I can test in emulator with API LEVEL 27.

To confirm if is the device or expo, I created a project in sdk 50, and I executed the app in the same real device and it works. This is the device software info (samsung galaxy s8+):

![image](https://github.com/user-attachments/assets/5d128f72-2807-4b0f-9d0b-e8c7c6388edf)

![image](https://github.com/user-attachments/assets/a2162bf0-f982-4007-bb59-09deebec3d45)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v20.12.1/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.24 => 51.0.24
      expo-router: ~3.5.20 => 3.5.20
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by KarlaSaenz** [comment]
I tested on the same Samsung S8 device with Android 9, and the development build does not work; the application closes when you try to open it. On another device with Android 14, the same build works.

After these changes in package.json, it does not work.
![Captura de pantalla 2024-08-01 a la(s) 21 31 09](https://github.com/user-attachments/assets/5a90b1ea-1904-490a-8342-8124f848a43c)

**Comment by anton-chikunov** [comment]
@KarlaSaenz @benomzn 
I had same issue yesterday, looks like this crash caused by  `expo-dev-client`, I've downgraded  to `4.0.20` and it starts working again

**Comment by benomzn** [comment]
> @KarlaSaenz @benomzn I had same issue yesterday, looks like this crash caused by `expo-dev-client`, I've downgraded to `4.0.20` and it starts working again

Yes, it is related to expo-dev-client, because it works in release mode. I mentioned this error on discord and they sent me here, hopefully they can fix it

**Comment by Aleks86** [comment]
I can confirm, I get same error on Expo 51 and `expo-dev-client` `4.0.21`.
Setting in `package.json`:
`"expo-dev-client": "4.0.20"` fixes issue. 

Careful, do not use `~`, as it this will not work: 
`"expo-dev-client": "~4.0.20"` - it will resolve to 4.0.21

**Comment by ari633** [comment]
> 4.0.20

it work

**Comment by jczekalski** [comment]
Ran into the same error today on a Samsung Galaxy A10 with Android 9 after upgrading to SDK 51. I can also confirm that downgrading to `"expo-dev-client": "4.0.20"` resolved the issue.

**Comment by jczekalski** [comment]
This is still an issue after upgrading to the latest patch version: `"expo-dev-client": "4.0.22"`

**Comment by fdesjardins** [comment]
I hit the same issue on Samsung Galaxy S8 with Android 9, downgrading to `"expo-dev-client": "4.0.20"` also resolved the issue for me.

**Comment by Aleks86** [comment]
Anyone tried if `4.0.23` is working?

**Comment by andrejpavlovic** [comment]
> Anyone tried if `4.0.23` is working?
`4.0.23` doesn't work either

**Comment by RohovDmytro** [comment]
> Anyone tried if 4.0.23 is working?

I've tried, no luck.

**Comment by AtGbemiga** [comment]
In addition to @anton-chikunov . This ensures you install the exact version you want `npm install expo-dev-client@4.0.20 --save-exact` otherwise you may get the caret version which may be a different version with minor patch.

**Comment by tkrafael** [comment]
Is there anything we can do to help solve issue?

**Comment by Abhishekjohri1998** [comment]
I had the same issue yesterday, it looks like this crash caused by expo-dev-client, I've downgraded to 4.0.20 and it starts working fine now 
thanks

**Comment by RohovDmytro** [comment]
Downgrading to lower expo-dev-client leads to kotlin-related crash in my case, I've tried playing around kotlin version via expo-build-properties, but with no luck.

**Comment by RohovDmytro** [comment]
`expo-dev-client@4.0.24` is not working for me either.

**Comment by larrybwosi** [comment]
I have downgraded to "expo-dev-client": "4.0.20" but the build fails  with this error  FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':expo-dev-menu:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> Compilation error. See log for more details

**Comment by RohovDmytro** [comment]
"expo-dev-client": "4.0.25"

All good.

**Comment by alanjhughes** [comment]
Fixed by #31114

**Comment by martin-ecatch** [comment]
This is still happening on Android 9. "expo-dev-client": "~4.0.28",
