### ISSUE TITLE
Upstream Expo changes cause flaky build errors like "Plugin [id: 'com.facebook.react.settings'] was not found in any of the following sources"

### ISSUE THREAD

**Issue by nigel-sr** [expo/expo#31005]
### Summary

Starting today, running `expo run:android` my build would very quickly fail with
```
FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/username/path/to/app/android/settings.gradle' line: 4

* What went wrong:
Plugin [id: 'com.facebook.react.settings'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (No included builds contain this plugin)
- Plugin Repositories (plugin dependency must include a version number for this source)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

The relevant line (settings.gradle line 4: `plugins { id("com.facebook.react.settings") }`) was recently added to the `expo-template-bare-minimum` package, which the CLI pulls remotely and therefore cannot be versioned by our app.

The new plugin (`com.facebook.react.settings`) was apparently introduced in react-native 0.75.0, and then stubbed in 0.74.4 in order to allow Expo to support both 0.74 and 0.75 with Expo 51 (https://github.com/facebook/react-native/pull/45720)

I have fixed the problem by updating from react-native 0.74.3 to 0.74.5 (the current recommended version for Expo 51).

### What platform(s) does this occur on?

Android

### SDK Version

51

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - /opt/homebrew/opt/node@18/bin/node
      npm: 10.2.4 - /opt/homebrew/opt/node@18/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 31, 33, 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 33.0.2, 34.0.0
        System Images: android-32 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.26 => 51.0.27
      expo-router: ~3.5.21 => 3.5.21
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: bare

### Minimal reproducible example

`npx create-expo-app@latest`
Change react-native version in package.json to 0.74.3

`expo prebuild --clean && expo run:android` will fail because "com.facebook.react.settings" does not exist yet.

**Comment by nigel-sr** [comment]
I made this issue mostly so that other people who run into the bug with "com.facebook.react.settings" will be able to easily find the solution (upgrading to at least react-native 0.74.3).

Also, this seems like a breaking change. Is there a test case missing for the `expo-template-bare-minimum` team to make sure that their templates work with Expo 51's minimum react native version? Our project depended on 0.74.3 because that was current when we updated Expo last month. It was very unexpected that it would stop working due to behind-the-scenes changes.

**Comment by ljmzbigsmart** [comment]
Oh god I was going crazy thinking I was the only one with this issue. Just started today.
Doing a prebuild of the android folder, we can see the line mentioned in the error:
```
pluginManagement {
  includeBuild(new File(["node", "--print", "require.resolve('@react-native/gradle-plugin/package.json')"].execute(null, rootDir).text.trim()).getParentFile().toString())
}
plugins { id("com.facebook.react.settings") }

def getRNMinorVersion() {
  def version = providers.exec {
    commandLine("node", "-e", "console.log(require('react-native/package.json').version);")
  }.standardOutput.asText.get().trim()

  def coreVersion = version.split("-")[0]
  def (major, minor, patch) = coreVersion.tokenize('.').collect { it.toInteger() }

  return minor
}
```

**Comment by jludwiggreenaction** [comment]
We're trying to create a new build without upgrading all of our packages right now, is there a workaround we can take to allow this? We use the managed workflow so we don't have a lot of visibility in the prebuild process.

**Comment by gabrieldonadel** [comment]
Hi, sorry for the inconvenience.

As described by [nigel-sr](https://github.com/nigel-sr), this error is caused by an outdated React Native version in your project.

To fix that, upgrade to `react-native@^0.74.5` by running: **`npx expo install --fix`** and then run your build again.

**Comment by jludwiggreenaction** [comment]
> Hi, sorry for the inconvenience.
> 
> As described by [nigel-sr](https://github.com/nigel-sr), this error is caused by an outdated React Native version in your project.
> 
> To fix that, upgrade to `react-native@^0.74.5` by running: **`npx expo install --fix`** and then run your build again.

There's no way to have builds be successful with older react native versions? For our use case, we don't want to upgrade our packages right now since we have to go through a much larger testing phase for all of our apps.

**Comment by gabrieldonadel** [comment]
> > Hi, sorry for the inconvenience.
> > As described by [nigel-sr](https://github.com/nigel-sr), this error is caused by an outdated React Native version in your project.
> > To fix that, upgrade to `react-native@^0.74.5` by running: **`npx expo install --fix`** and then run your build again.
> 
> @gabrieldonadel There's no way to have builds be successful with older react native versions (e.g. different build image)? For our use case, we don't want to upgrade our packages right now since we have to go through a much larger testing phase for all of our apps.

React-native 0.74.4 is just a patch release including a few bug fixes, it shouldn't require any other libraries to be updated

**Comment by jludwiggreenaction** [comment]
> > > Hi, sorry for the inconvenience.
> > > As described by [nigel-sr](https://github.com/nigel-sr), this error is caused by an outdated React Native version in your project.
> > > To fix that, upgrade to `react-native@^0.74.5` by running: **`npx expo install --fix`** and then run your build again.
> > 
> > 
> > @gabrieldonadel There's no way to have builds be successful with older react native versions (e.g. different build image)? For our use case, we don't want to upgrade our packages right now since we have to go through a much larger testing phase for all of our apps.
> 
> React-native 0.74.4 is just a patch release including a few bug fixes, it shouldn't require any other libraries to be updated

Thanks for you input.

Our problem is we have multiple apps sharing the same native code. So even minor updates to native code would require publishing multiple new apps. We were just hoping to push a splash screen change for one of our apps when we encountered this problem.

I guess we're out of luck though, since it seems the problem is during the prebuild phase.

**Comment by gabrieldonadel** [comment]
> Thanks for you input.
> 
> Our problem is we have multiple apps sharing the same native code. So even minor updates to native code would require publishing multiple new apps. We were just hoping to push a splash screen change for one of our apps when we encountered this problem.
> 
> I guess we're out of luck though, since it seems the problem is during the prebuild phase.

Oh, I understand @jludwiggreenaction, one simple fix that you can apply is to remove line 4 from [android/settings.gradle ](https://github.com/expo/expo/blob/36d307eff0b598d3582c3a05e5135f5d59622b7d/templates/expo-template-bare-minimum/android/settings.gradle#L4) (`plugins { id("com.facebook.react.settings") }`), this will allow you to build normally again without having to upgrade react-native

**Comment by jludwiggreenaction** [comment]
> Oh, I understand @jludwiggreenaction, one simple fix that you can apply is to remove line 4 from [android/settings.gradle ](https://github.com/expo/expo/blob/36d307eff0b598d3582c3a05e5135f5d59622b7d/templates/expo-template-bare-minimum/android/settings.gradle#L4) (`plugins { id("com.facebook.react.settings") }`), this will allow you to build normally again without having to upgrade react-native

Thanks a lot for the info. Currently we use eas-build for everything so we never actually see the gradle file. Is it possible to do this without building locally?

**Comment by brentvatne** [comment]
@jludwiggreenaction - another option is to override the template that is used, we default to using the latest one for the SDK version you use. you can use [`prebuildCommand`](https://docs.expo.dev/eas/json/#prebuildcommand) to do this, eg:

```
"prebuildCommand": "prebuild --template expo-template-bare-minimum@51.0.50"
```

this will use the latest version for SDK 51 prior to the changes that required react-native@0.74.5

**Comment by nigel-sr** [comment]
Oh! I might steal that `--template` option for my scripts, too. It will be nice to have a way to pin the template version so we can revert changes when necessary!

**Comment by lindboe** [comment]
After upgrading from 0.74.3 to 0.74.5, I'm seeing an issue I'm a little baffled by. Prebuild works, but then when loading the JS for iOS or Android I see

```
iOS Bundling failed 3255ms node_modules/expo/AppEntry.js (1892 modules)
Unable to resolve "react-native/Libraries/Utilities/DevLoadingView" from "node_modules/@expo/metro-runtime/build/LoadingView.native.js"
```

Since we're on RN 74, that file path is still `react-native/Libraries/Utilities/LoadingView`, without `Dev`, and that is present in my node_modules. The file from `@expo/metro-runtime` also looks like it should be trying the old file first and then the next, but there's some sort of issue I haven't figured out yet:

```
  3 let LoadingView;
  4 try {
  5     LoadingView = require('react-native/Libraries/Utilities/LoadingView');
  6 }
  7 catch {
  8     // In react-native 0.75.0 LoadingView was renamed to DevLoadingView
  9     LoadingView = require('react-native/Libraries/Utilities/DevLoadingView');
 10 }
```

The workaround: if I just delete the `DevLoadingView` require entirely the app loads just fine.

Anyone else running into this?

**Comment by Darren120** [comment]
> @jludwiggreenaction - another option is to override the template that is used, we default to using the latest one for the SDK version you use. you can use [`prebuildCommand`](https://docs.expo.dev/eas/json/#prebuildcommand) to do this, eg:
> 
> ```
> "prebuildCommand": "prebuild --template expo-template-bare-minimum@51.0.50"
> ```
> 
> this will use the latest version for SDK 51 prior to the changes that required react-native@0.74.5

how to pipe this into eas build ?

**Comment by nigel-sr** [comment]
@Darren120 There is a "prebuildCommand" config option in `eas.json`, if you use that. https://docs.expo.dev/eas/json/

**Comment by brentvatne** [comment]
@lindboe - can you create a new issue and share a minimal reproducible example there? thank you!

**Comment by Darren120** [comment]
> @Darren120 There is a "prebuildCommand" config option in `eas.json`, if you use that. https://docs.expo.dev/eas/json/

how do i pipe eas build -p android ? it throws

**Comment by Darren120** [comment]
> I made this issue mostly so that other people who run into the bug with "com.facebook.react.settings" will be able to easily find the solution (upgrading to at least react-native 0.74.4).
> 
> Also, this seems like a breaking change. Is there a test case missing for the `expo-template-bare-minimum` team to make sure that their templates work with Expo 51's minimum react native version? Our project depended on 0.74.3 because that was current when we updated Expo last month. It was very unexpected that it would stop working due to behind-the-scenes changes.

the latest version of expo fix is 0.74.5 which wont build, but 0.74.4 builds for android

**Comment by brentvatne** [comment]
> > @Darren120 There is a "prebuildCommand" config option in `eas.json`, if you use that. https://docs.expo.dev/eas/json/
> 
> how do i pipe eas build -p android ? it throws

put it on your build profile, similar to other properties that you would put on a build profile such as `"channel"`

**Comment by statico** [comment]
> @jludwiggreenaction - another option is to override the template that is used, we default to using the latest one for the SDK version you use. you can use [`prebuildCommand`](https://docs.expo.dev/eas/json/#prebuildcommand) to do this, eg:
> 
> ```
> "prebuildCommand": "prebuild --template expo-template-bare-minimum@51.0.50"
> ```
> 
> this will use the latest version for SDK 51 prior to the changes that required react-native@0.74.5

Thanks for this. Is there some trick to using it? When I add...

```json
// eas.json
{
  "build": {
    "base": {
      "prebuildCommand": "prebuild --template expo-template-bare-minimum@51.0.50"
    },
```

The prebuild step fails on Expo with:

```
AssertionError [ERR_ASSERTION]: template file does not exist: /home/expo/workingdir/build/packages/mobile/expo-template-bare-minimum@51.0.50
pnpm expo prebuild --template expo-template-bare-minimum@51.0.50 --platform android exited with non-zero code: 1
```

**Comment by brentvatne** [comment]
we decided to roll back the changes, so the default template is compatible with 0.74.3 and below again. we'll figure out a better way to roll out react-native@0.75 compatibility without requiring 0.74.4 and higher

if you encountered this issue, please try your build again. apologies for the trouble, this is our first attempt at supporting multiple react-native versions in a single SDK and we didn't anticipate the possible side effects correctly.

**Comment by gabrielcantarin2** [comment]
> Oh! I might steal that `--template` option for my scripts, too. It will be nice to have a way to pin the template version so we can revert changes when necessary!

`npx expo install --fix`

This worked for me!! Thanks @brentvatne

**Comment by gabrieldonadel** [comment]
Quick follow-up here, we just updated our templates again, this time with a fix that supports all versions of react-native 0.74 and 0.75. 

As of now you no longer need to use a custom `prebuildCommand` nor edit your Android files manually, everything should work out of the box after running `npx expo prebuild -p android --clean`

Apologies for the issues caused yesterday

**Comment by timothydillan** [comment]
> > @jludwiggreenaction - another option is to override the template that is used, we default to using the latest one for the SDK version you use. you can use [`prebuildCommand`](https://docs.expo.dev/eas/json/#prebuildcommand) to do this, eg:
> > ```
> > "prebuildCommand": "prebuild --template expo-template-bare-minimum@51.0.50"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this will use the latest version for SDK 51 prior to the changes that required react-native@0.74.5
> 
> Thanks for this. Is there some trick to using it? When I add...
> 
> ```json
> // eas.json
> {
>   "build": {
>     "base": {
>       "prebuildCommand": "prebuild --template expo-template-bare-minimum@51.0.50"
>     },
> ```
> 
> The prebuild step fails on Expo with:
> 
> ```
> AssertionError [ERR_ASSERTION]: template file does not exist: /home/expo/workingdir/build/packages/mobile/expo-template-bare-minimum@51.0.50
> pnpm expo prebuild --template expo-template-bare-minimum@51.0.50 --platform android exited with non-zero code: 1
> ```
> 
> EDIT: Please ignore. `packages/mobile` was part of our monorepo, so my template argument was incorrect.

Hey @statico , would you mind sharing how you'd fix this issue? Currently facing the same one and have not found a solution for it..

**Comment by hiroaka** [comment]
Having this problem using 

`npx expo run:android`

**Comment by cloudberry-mk** [comment]
Same issue, expo 51.0.28… 
Tried to create a clean project - no go. Neither npx expo install --fix nor prebuild script modifications mentioned above work.
Going into android dir and running ./gradlew clean - same issue.

**Comment by gabrieldonadel** [comment]
> Having this problem using
> 
> `npx expo run:android`

Hi @hiroaka, does the error persists when you run `npx expo prebuild -p android --clean`?

**Comment by hiroaka** [comment]
> > Having this problem using
> > `npx expo run:android`
> 
> Hi @hiroaka, does the error persists when you run `npx expo prebuild -p android --clean`?
@gabrielcantarin2 
Got fixed just now by running:

`npx expo prebuild --clean
`npx expo install --fix`

This updated metro-runtime to *"@expo/metro-runtime": "~3.2.3"*

**Comment by timothydillan** [comment]
Hi guys, just wanted to update that I successfully fixed the issue for my project.
1. Run `npx expo install --fix` -> this updates all necessary packages to the required version for Expo 51.
2. Test first locally using `npx expo start` -> I got an error saying invariant violation due to "main" not being registered. This issue is caused by a library dependency (i.e. react-native-snap-carousel) that uses ViewPropTypes from react-native, which has long been deprecated. 
3. Installed patch-package and postinstall: `npx expo install patch-package postinstall`, and also downloaded the patch from here: https://github.com/meliorence/react-native-snap-carousel/files/15391324/react-native-snap-carousel%2B3.9.1.patch and moving it into a patches folder inside my project (folder should be directly in the root project folder, making it 1 level deep, tree-wise).
4. Ran `npx patch-package` to apply the package
5. Put `"postinstall": "patch-package"` inside the `scripts` object in package.json.
6. Run `npm install` just to make sure all packages are good to go, and package-lock.json is updated. 
7. Commit and push to github repo. <- this step is important, as cloud expo builds will clone from the latest commit in your repository.
8. No need for prebuild, just create a clean build `eas build --platform android --clear-cache`
9. Voila

Extra steps for iOS:
1. After doing the steps above, I still had some issues. Particularly, this error showed up when installing pods in the build process: ` CocoaPods could not find compatible versions for pod "MMKV":`
2. I had to uninstall an unused dependency called `react-native-mmkv` and `react-native-mmkv-storage` -> e.g. `npm uninstall react-native-mmkv` and `npm uninstall react-native-mmkv-storage`
3. Reran `npm install`
4. Create a clean build `eas build --platform ios --clear-cache`
5. Build now works :)

Hope this helps anyone else facing the same issue.

**Comment by dpuckett** [comment]
Also getting this error when building locally. Please re-open this issue.

**Comment by lishaan** [comment]
> I'm still getting the "Plugin [id: 'com.facebook.react.settings'] was not found in any of the following sources" error in EAS Build, even after:
> 
> * `npx expo install --fix`
> * `yarn install`
> * `npx expo prebuild --clean`
> * `npx eas-cli build --platform=android --profile=development`
> 
> I have the following in my package.json:
> 
> * "expo": "~51.0.28",
> * "react-native": "^0.74.5",
> 
> So it appears that this issue persists even with the latest package versions for some apps, for some reason. Any thoughts welcome.

same issue here. we noticed our android builds stopped working a few days back.

**Comment by brentvatne** [comment]
@lishaan - would you be able to share a reproducible example & links to your build page urls please?

**Comment by srosato** [comment]
Not sure what I am doing wrong as well, but I suddenly had the `Plugin [id: 'com.facebook.react.settings'] was not found in any of the following sources` error as well. When I switched from pnpm back to yarn (and clearing node_modules) it started to work again. 

I tried removing node_modules and re-install with pnpm, but I would still get the error.

**Comment by upnorth** [comment]
> I'm still getting the "Plugin [id: 'com.facebook.react.settings'] was not found in any of the following sources" error in EAS Build, even after:
> 
> * `npx expo install --fix`
> * `yarn install`
> * `npx expo prebuild --clean`
> * `npx eas-cli build --platform=android --profile=development`
> 
> I have the following in my package.json:
> 
> * "expo": "~51.0.28",
> * "react-native": "^0.74.5",
> 
> So it appears that this issue persists even with the latest package versions for some apps, for some reason. Any thoughts welcome.

Same here... tried nuking node_modules and reinstalling everything as well.

**Comment by brentvatne** [comment]
@srosato @upnorth - ensure you're using the latest version of the expo pkg, 51.0.31

**Comment by upnorth** [comment]
> * npx expo prebuild --clean

Updated to that from 28 now, no difference. Is there a fool-proof routine that is officially supported to sort of "reset" a project with the correct dependencies. I'm new to npx and eas build, I might be doing something wrong.

I'm doing a local android build with this profile to get the apk right away:

`    "apk": {
      "distribution": "internal",
      "env": { "NODE_ENV": "development" },
      "android": {
        "buildType": "apk"
      }
    },`

**Comment by srosato** [comment]
> ensure you're using the latest version of the expo pkg, 51.0.31

Yes this happened while on `~51.0.31`.

**Comment by upnorth** [comment]
This is the full error I get, just to confirm:

```
[RUN_GRADLEW] Running 'gradlew :app:assembleRelease' in /var/folders/3d/4382wrb15qg1x2ytrl1d40700000gn/T/eas-build-local-nodejs/13175212-3ca5-40ef-b10e-8d49faae411e/build/android
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * Where:
[RUN_GRADLEW] Settings file '/private/var/folders/3d/4382wrb15qg1x2ytrl1d40700000gn/T/eas-build-local-nodejs/13175212-3ca5-40ef-b10e-8d49faae411e/build/android/settings.gradle' line: 13
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Plugin [id: 'com.facebook.react.settings'] was not found in any of the following sources:
[RUN_GRADLEW] - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
[RUN_GRADLEW] - Included Builds (No included builds contain this plugin)
[RUN_GRADLEW] - Plugin Repositories (plugin dependency must include a version number for this source)
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] >
[RUN_GRADLEW] Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org.
```

Just upgraded to the recommended `eas-cli@10.2.4` for good measure and have `"expo": "^51.0.31"` in package.json

**Comment by srosato** [comment]
Steps to reproduce:

```bash
npx create-expo-app@latest // I chose `expo-react-settings-bug` as a name (not sure its a bug though, just trying out)
rm package-lock.json
rm -rf node_modules/
pnpm i
pnpm expo prebuild --clean
eas build --platform android --local --profile preview
```

Using eas-cli/10.2.1

I get

```
[PREBUILD] Skipped running "expo prebuild" because the "android" directory already exists. Learn more about the build process: https://docs.expo.dev/build-reference/android-builds/
[PREPARE_CREDENTIALS] Writing secrets to the project's directory
[PREPARE_CREDENTIALS] Injecting signing config into build.gradle
[RUN_GRADLEW] Running 'gradlew :app:assembleRelease' in /tmp/srosato/eas-build-local-nodejs/4c1ffe61-f8af-4b70-812d-a552bd570e02/build/android
[RUN_GRADLEW] Starting a Gradle Daemon (subsequent builds will be faster)
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * Where:
[RUN_GRADLEW] Settings file '/tmp/srosato/eas-build-local-nodejs/4c1ffe61-f8af-4b70-812d-a552bd570e02/build/android/settings.gradle' line: 13
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Error resolving plugin [id: 'com.facebook.react.settings']
[RUN_GRADLEW] > Included build '/tmp/srosato/eas-build-local-nodejs/4c1ffe61-f8af-4b70-812d-a552bd570e02/build/android/null' does not exist.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org.
[RUN_GRADLEW] BUILD FAILED in 1s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```

If I run

```bash
rm -rf node_modules pnpm-lock.yaml
yarn
yarn expo prebuild --clean
eas build --platform android --local --profile preview
```

It works

**Comment by upnorth** [comment]
Nuking `package-lock.json` in addition to `node_modules` seems to have done it for me, thanks @srosato !

Ran into this after but locking the version as suggested worked right away: https://github.com/nativewind/nativewind/issues/498

`Build successful`

I finally get to test my push notifications this weekend haha!

**Comment by lishaan** [comment]
> Steps to reproduce:
> 
> ```shell
> npx create-expo-app@latest // I chose `expo-react-settings-bug` as a name (not sure its a bug though, just trying out)
> cd expo-react-settings-bug
> rm package-lock.json
> rm -rf node_modules/
> pnpm i
> pnpm expo prebuild --clean
> eas build --platform android --local --profile preview
> ```
> 
> Using eas-cli/10.2.1
> 
> I get
> 
> ```
> [PREBUILD] Skipped running "expo prebuild" because the "android" directory already exists. Learn more about the build process: https://docs.expo.dev/build-reference/android-builds/
> [PREPARE_CREDENTIALS] Writing secrets to the project's directory
> [PREPARE_CREDENTIALS] Injecting signing config into build.gradle
> [RUN_GRADLEW] Running 'gradlew :app:assembleRelease' in /tmp/srosato/eas-build-local-nodejs/4c1ffe61-f8af-4b70-812d-a552bd570e02/build/android
> [RUN_GRADLEW] Starting a Gradle Daemon (subsequent builds will be faster)
> [RUN_GRADLEW] FAILURE: Build failed with an exception.
> [RUN_GRADLEW] * Where:
> [RUN_GRADLEW] Settings file '/tmp/srosato/eas-build-local-nodejs/4c1ffe61-f8af-4b70-812d-a552bd570e02/build/android/settings.gradle' line: 13
> [RUN_GRADLEW] * What went wrong:
> [RUN_GRADLEW] Error resolving plugin [id: 'com.facebook.react.settings']
> [RUN_GRADLEW] > Included build '/tmp/srosato/eas-build-local-nodejs/4c1ffe61-f8af-4b70-812d-a552bd570e02/build/android/null' does not exist.
> [RUN_GRADLEW] * Try:
> [RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
> [RUN_GRADLEW] > Run with --info or --debug option to get more log output.
> [RUN_GRADLEW] > Run with --scan to get full insights.
> [RUN_GRADLEW] > Get more help at https://help.gradle.org.
> [RUN_GRADLEW] BUILD FAILED in 1s
> [RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
> ```
> 
> If I run
> 
> ```shell
> rm -rf node_modules pnpm-lock.yaml
> yarn
> yarn expo prebuild --clean
> eas build --platform android --local --profile preview
> ```
> 
> It works
> 
> Note: expo latest has 51.0.28, I upgraded to 51.0.31, still same problem.

can confirm that this works! simply had to switch from pnpm@8.15.6 to yarn@1.22.22

**Comment by brentvatne** [comment]
hi there @upnorth @lishaan! are you using the node modules linker for pnpm? it seems like no. this is required to use pnpm currently: https://docs.expo.dev/more/create-expo/#pnpm - you can try creating a project with `pnpm create expo-app` and it will configure that for you

**Comment by lishaan** [comment]
> hi there @upnorth @lishaan! are you using the node modules linker for pnpm? it seems like no. this is required to use pnpm currently: https://docs.expo.dev/more/create-expo/#pnpm - you can try creating a project with `pnpm create expo-app` and it will configure that for you

I don't think that's the issue, my .npmrc has these two lines:

node-linker=hoisted
auto-install-peers=true

**Comment by brentvatne** [comment]
@lishaan - are you able to repro the issue if you use `pnpm create expo-app`?

**Comment by brentvatne** [comment]
@lishaan - i did the following and it succeeded:

```
pnpm create expo-app lishaan
cd lishaan
eas build -p android
```

**Comment by lishaan** [comment]
> @lishaan - are you able to repro the issue if you use `pnpm create expo-app`?

since our project is a bit complicated and has a bunch of native modules, I'm not able to properly make a repro. 

however, we had it working last week. same error occurs if I try to make a build that succeeded even two months back. all boils down to pnpm now since switching to yarn or npm fixes it. 

I also tried on bun and I couldn't get it to work. at the moment its only working on npm and yarn.

**Comment by lishaan** [comment]
> I'm still getting the error after updating to expo@51.0.31 (and still react-native@0.74.5). I'm running Yarn 4 in a monorepo, but with "nodeLinker: node-modules" in my .yarnrc.yml, so I do have a node_modules. I tried:
> 
> * `rm -rf node_modules/`
> * `yarn install`
>   But the issue persists.
> 
> It seems like modern package management tools is perhaps a commonality among those of us who are still experiencing the issue. Is there something else I need to be doing in a monorepo / Yarn >1 to be compatible with whatever change was made?

does it work on yarn@1.22.22?

**Comment by AlirezaHadjar** [comment]
In my case, I was using `react-native-gradle-plugin` v0.74 in my `yarn.lock` file. by upgrading it to v0.75, the issue was resolved.

**Comment by Hakanlsk** [comment]
> > Steps to reproduce:
> > ```shell
> > npx create-expo-app@latest // I chose `expo-react-settings-bug` as a name (not sure its a bug though, just trying out)
> > cd expo-react-settings-bug
> > rm package-lock.json
> > rm -rf node_modules/
> > pnpm i
> > pnpm expo prebuild --clean
> > eas build --platform android --local --profile preview
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Using eas-cli/10.2.1
> > I get
> > ```
> > [PREBUILD] Skipped running "expo prebuild" because the "android" directory already exists. Learn more about the build process: https://docs.expo.dev/build-reference/android-builds/
> > [PREPARE_CREDENTIALS] Writing secrets to the project's directory
> > [PREPARE_CREDENTIALS] Injecting signing config into build.gradle
> > [RUN_GRADLEW] Running 'gradlew :app:assembleRelease' in /tmp/srosato/eas-build-local-nodejs/4c1ffe61-f8af-4b70-812d-a552bd570e02/build/android
> > [RUN_GRADLEW] Starting a Gradle Daemon (subsequent builds will be faster)
> > [RUN_GRADLEW] FAILURE: Build failed with an exception.
> > [RUN_GRADLEW] * Where:
> > [RUN_GRADLEW] Settings file '/tmp/srosato/eas-build-local-nodejs/4c1ffe61-f8af-4b70-812d-a552bd570e02/build/android/settings.gradle' line: 13
> > [RUN_GRADLEW] * What went wrong:
> > [RUN_GRADLEW] Error resolving plugin [id: 'com.facebook.react.settings']
> > [RUN_GRADLEW] > Included build '/tmp/srosato/eas-build-local-nodejs/4c1ffe61-f8af-4b70-812d-a552bd570e02/build/android/null' does not exist.
> > [RUN_GRADLEW] * Try:
> > [RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
> > [RUN_GRADLEW] > Run with --info or --debug option to get more log output.
> > [RUN_GRADLEW] > Run with --scan to get full insights.
> > [RUN_GRADLEW] > Get more help at https://help.gradle.org.
> > [RUN_GRADLEW] BUILD FAILED in 1s
> > [RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If I run
> > ```shell
> > rm -rf node_modules pnpm-lock.yaml
> > yarn
> > yarn expo prebuild --clean
> > eas build --platform android --local --profile preview
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It works
> > Note: expo latest has 51.0.28, I upgraded to 51.0.31, still same problem.
> 
> can confirm that this works! simply had to switch from pnpm@8.15.6 to yarn@1.22.22
> 
> edit: tested on pnpm@9.8.0 as well. same issue

"react-native": "0.74.5",
"expo": "^51.0.31",

I followed all the steps but I still get an error

* Where:
Settings file 'C:\Users\hakan\OneDrive\Masa³st³\archai-fix\android\settings.gradle' line: 13

* What went wrong:
Error resolving plugin [id: 'com.facebook.react.settings']
> Included build 'C:\Users\hakan\OneDrive\Masa³st³\archai-fix\android\null' does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

-npx expo run:android    Error :

BU¦LD FAILED in 1s
Error: C:\Users\hakan\OneDrive\Masaüstü\PROJECT_FOLDER\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=x86 exited with non-zero code: 1

eas build --platform android    Error:

Build failed: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

**Comment by brentvatne** [comment]
@Hakanlsk - can you share a minimal reproducible example? it seems like perhaps there is some version locking/resolution that is giving you incorrect dependencies. you may have an outdated version of `@react-native/gradle-plugin` - try checking what version are in your repo (eg: `npm why @react-native/gradle-plugin`) and sharing those here. the version of `@react-native/gradle-plugin` in your repo should exactly match your `react-native` version

**Comment by Hakanlsk** [comment]
@brentvatne `npm why @react-native/gradle-plugin` after running 

to match project root version with gradle version I changed @react-native/gradle-plugin@0.75.2 to 0.74.87, deleted and reinstalled my node_modules and package-lock.json files but it was not enough. What should I do?

@react-native/gradle-plugin@0.75.2
node_modules/@react-native/gradle-plugin
  @react-native/gradle-plugin@"^0.75.2" from the root project

@react-native/gradle-plugin@0.74.87
node_modules/react-native/node_modules/@react-native/gradle-plugin
  @react-native/gradle-plugin@"0.74.87" from react-native@0.74.5
  node_modules/react-native
    react-native@"0.74.5" from the root project
    peer react-native@"*" from @react-native-firebase/app@20.4.0
    node_modules/@react-native-firebase/app
      @react-native-firebase/app@"^20.4.0" from the root project
      peer @react-native-firebase/app@"20.4.0" from @react-native-firebase/analytics@20.4.0
      node_modules/@react-native-firebase/analytics
        peer @react-native-firebase/analytics@"20.4.0" from @react-native-firebase/remote-config@20.4.0
        node_modules/@react-native-firebase/remote-config
          @react-native-firebase/remote-config@"^20.4.0" from the root project
      peer @react-native-firebase/app@"20.4.0" from @react-native-firebase/messaging@20.4.0
      node_modules/@react-native-firebase/messaging
        @react-native-firebase/messaging@"^20.4.0" from the root project
      peer @react-native-firebase/app@"20.4.0" from @react-native-firebase/remote-config@20.4.0
      node_modules/@react-native-firebase/remote-config
        @react-native-firebase/remote-config@"^20.4.0" from the root project
    peer react-native@"*" from @react-native/virtualized-lists@0.74.87
    node_modules/@react-native/virtualized-lists
      @react-native/virtualized-lists@"0.74.87" from react-native@0.74.5
    peer react-native@"*" from @react-navigation/bottom-tabs@6.6.1
    node_modules/@react-navigation/bottom-tabs
      @react-navigation/bottom-tabs@"^6.6.1" from the root project
    peer react-native@"*" from @react-navigation/elements@1.3.31
    node_modules/@react-navigation/elements
      @react-navigation/elements@"^1.3.31" from @react-navigation/bottom-tabs@6.6.1
      node_modules/@react-navigation/bottom-tabs
        @react-navigation/bottom-tabs@"^6.6.1" from the root project
      @react-navigation/elements@"^1.3.31" from @react-navigation/native-stack@6.11.0
      node_modules/@react-navigation/native-stack
        @react-navigation/native-stack@"^6.11.0" from the root project
    peer react-native@"*" from @react-navigation/native@6.1.18
    node_modules/@react-navigation/native
      @react-navigation/native@"^6.1.18" from the root project
      peer @react-navigation/native@"^6.0.0" from @react-navigation/bottom-tabs@6.6.1
      node_modules/@react-navigation/bottom-tabs
        @react-navigation/bottom-tabs@"^6.6.1" from the root project
      peer @react-navigation/native@"^6.0.0" from @react-navigation/elements@1.3.31
      node_modules/@react-navigation/elements
        @react-navigation/elements@"^1.3.31" from @react-navigation/bottom-tabs@6.6.1
        node_modules/@react-navigation/bottom-tabs
          @react-navigation/bottom-tabs@"^6.6.1" from the root project
        @react-navigation/elements@"^1.3.31" from @react-navigation/native-stack@6.11.0
        node_modules/@react-navigation/native-stack
          @react-navigation/native-stack@"^6.11.0" from the root project
      peer @react-navigation/native@"^6.0.0" from @react-navigation/native-stack@6.11.0
      node_modules/@react-navigation/native-stack
        @react-navigation/native-stack@"^6.11.0" from the root project
    peer react-native@"*" from @react-navigation/native-stack@6.11.0
    node_modules/@react-navigation/native-stack
      @react-navigation/native-stack@"^6.11.0" from the root project
    peer react-native@"*" from react-native-purchases@8.1.0
    node_modules/react-native-purchases
      react-native-purchases@"^8.0.1" from the root project
    peer react-native@"*" from react-native-reanimated@3.10.1
    node_modules/react-native-reanimated
      react-native-reanimated@"~3.10.1" from the root project
      peer react-native-reanimated@"*" from moti@0.29.0
      node_modules/moti
        moti@"^0.29.0" from the root project
    peer react-native@"*" from react-native-safe-area-context@4.10.5
    node_modules/react-native-safe-area-context
      react-native-safe-area-context@"4.10.5" from the root project
      peer react-native-safe-area-context@">= 3.0.0" from @react-navigation/bottom-tabs@6.6.1
      node_modules/@react-navigation/bottom-tabs
        @react-navigation/bottom-tabs@"^6.6.1" from the root project
      peer react-native-safe-area-context@">= 3.0.0" from @react-navigation/elements@1.3.31
      node_modules/@react-navigation/elements
        @react-navigation/elements@"^1.3.31" from @react-navigation/bottom-tabs@6.6.1
        node_modules/@react-navigation/bottom-tabs
          @react-navigation/bottom-tabs@"^6.6.1" from the root project
        @react-navigation/elements@"^1.3.31" from @react-navigation/native-stack@6.11.0
        node_modules/@react-navigation/native-stack
          @react-navigation/native-stack@"^6.11.0" from the root project
      peer react-native-safe-area-context@">= 3.0.0" from @react-navigation/native-stack@6.11.0
      node_modules/@react-navigation/native-stack
        @react-navigation/native-stack@"^6.11.0" from the root project
    peer react-native@"*" from react-native-screens@3.31.1
    node_modules/react-native-screens
      react-native-screens@"3.31.1" from the root project
      peer react-native-screens@">= 3.0.0" from @react-navigation/bottom-tabs@6.6.1
      node_modules/@react-navigation/bottom-tabs
        @react-navigation/bottom-tabs@"^6.6.1" from the root project
      peer react-native-screens@">= 3.0.0" from @react-navigation/native-stack@6.11.0
      node_modules/@react-navigation/native-stack
        @react-navigation/native-stack@"^6.11.0" from the root project

**Comment by brentvatne** [comment]
> to match project root version with gradle version I changed @react-native/gradle-plugin@0.75.2 to 0.74.87, deleted and reinstalled my node_modules and package-lock.json files but it was not enough. What should I do?

can you elaborate on what you mean here? it looks like you have @react-native/gradle-plugin@0.75.2 installed in the root of your project

**Comment by Hakanlsk** [comment]
> > to match project root version with gradle version I changed @react-native/gradle-plugin@0.75.2 to 0.74.87, deleted and reinstalled my node_modules and package-lock.json files but it was not enough. What should I do?
> 
> can you elaborate on what you mean here? it looks like you have @react-native/gradle-plugin@0.75.2 installed in the root of your project

I understood that my gradle package version must be the same as my react native package version in order for the packages listed above to work and build smoothly, but I guess I misunderstood? I installed @react-native/gradle-plugin in the current project and I still get the same error during build. I don't understand what the 'npm why @react-native/gradle-plugin' command does, sorry for taking your time. The current package.json is like this:

{
  "name": "archai",
  "version": "3",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@apollo/client": "^3.11.4",
    "@expo/react-native-action-sheet": "^4.1.0",
    "@react-native-firebase/app": "^20.4.0",
    "@react-native-firebase/messaging": "^20.4.0",
    "@react-native-firebase/remote-config": "^20.4.0",
    "@react-native/gradle-plugin": "^0.75.2",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "@types/react": "~18.2.79",
    "apollo-upload-client": "^18.0.1",
    "expo": "^51.0.31",
    "expo-av": "~14.0.7",
    "expo-build-properties": "~0.12.5",
    "expo-camera": "^15.0.15",
    "expo-dev-client": "~4.0.25",
    "expo-file-system": "~17.0.1",
    "expo-image-picker": "~15.0.7",
    "expo-linear-gradient": "~13.0.2",
    "expo-media-library": "~16.0.4",
    "expo-sharing": "~12.0.1",
    "expo-status-bar": "~1.12.1",
    "expo-store-review": "~7.0.2",
    "expo-system-ui": "~3.0.7",
    "expo-video": "^1.2.5",
    "expo-web-browser": "~13.0.3",
    "graphql": "^15.8.0",
    "moti": "^0.29.0",
    "react": "18.2.0",
    "react-native": "0.74.5",
    "react-native-purchases": "^8.0.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "typescript": "~5.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

**Comment by Hakanlsk** [comment]
My problem was that there were characters other than English characters in the file path of the project. Solved the problem by changing the file path

**Comment by MilanBarande** [comment]
> > Steps to reproduce:
> > ```shell
> > npx create-expo-app@latest // I chose `expo-react-settings-bug` as a name (not sure its a bug though, just trying out)
> > cd expo-react-settings-bug
> > rm package-lock.json
> > rm -rf node_modules/
> > pnpm i
> > pnpm expo prebuild --clean
> > eas build --platform android --local --profile preview
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Using eas-cli/10.2.1
> > I get
> > ```
> > [PREBUILD] Skipped running "expo prebuild" because the "android" directory already exists. Learn more about the build process: https://docs.expo.dev/build-reference/android-builds/
> > [PREPARE_CREDENTIALS] Writing secrets to the project's directory
> > [PREPARE_CREDENTIALS] Injecting signing config into build.gradle
> > [RUN_GRADLEW] Running 'gradlew :app:assembleRelease' in /tmp/srosato/eas-build-local-nodejs/4c1ffe61-f8af-4b70-812d-a552bd570e02/build/android
> > [RUN_GRADLEW] Starting a Gradle Daemon (subsequent builds will be faster)
> > [RUN_GRADLEW] FAILURE: Build failed with an exception.
> > [RUN_GRADLEW] * Where:
> > [RUN_GRADLEW] Settings file '/tmp/srosato/eas-build-local-nodejs/4c1ffe61-f8af-4b70-812d-a552bd570e02/build/android/settings.gradle' line: 13
> > [RUN_GRADLEW] * What went wrong:
> > [RUN_GRADLEW] Error resolving plugin [id: 'com.facebook.react.settings']
> > [RUN_GRADLEW] > Included build '/tmp/srosato/eas-build-local-nodejs/4c1ffe61-f8af-4b70-812d-a552bd570e02/build/android/null' does not exist.
> > [RUN_GRADLEW] * Try:
> > [RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
> > [RUN_GRADLEW] > Run with --info or --debug option to get more log output.
> > [RUN_GRADLEW] > Run with --scan to get full insights.
> > [RUN_GRADLEW] > Get more help at https://help.gradle.org.
> > [RUN_GRADLEW] BUILD FAILED in 1s
> > [RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If I run
> > ```shell
> > rm -rf node_modules pnpm-lock.yaml
> > yarn
> > yarn expo prebuild --clean
> > eas build --platform android --local --profile preview
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It works
> > Note: expo latest has 51.0.28, I upgraded to 51.0.31, still same problem.
> 
> can confirm that this works! simply had to switch from pnpm@8.15.6 to yarn@1.22.22
> 
> edit: tested on pnpm@9.8.0 as well. same issue

This solved it for me, thanks! I was using pnpm@9.9. I switched to yarn (I had 1.9.2 installed), it didn't work. Using yarn 1.22.22 solved the error on the android build.
Is there any pnpm known version where the issue doesn't happen?

**Comment by srosato** [comment]
> hi there @upnorth @lishaan! are you using the node modules linker for pnpm? it seems like no. this is required to use pnpm currently: https://docs.expo.dev/more/create-expo/#pnpm - you can try creating a project with `pnpm create expo-app` and it will configure that for you

Ok that was my bad as well, I did not read documentation correctly. I was able to build my project with `pnpm` as soon as I added this to `.npmrc` and confirms it also works with `npx create-expo-app@latest` if you add the hoist setting as well.

`.npmrc`

```
node-linker=hoisted
```

**Comment by MilanBarande** [comment]
> > hi there @upnorth @lishaan! are you using the node modules linker for pnpm? it seems like no. this is required to use pnpm currently: https://docs.expo.dev/more/create-expo/#pnpm - you can try creating a project with `pnpm create expo-app` and it will configure that for you
> 
> Ok that was my bad as well, I did not read documentation correctly. I was able to build my project with `pnpm` as soon as I added this to `.npmrc` and confirms it also works with `npx create-expo-app@latest` if you add the hoist setting as well.
> 
> `.npmrc`
> 
> ```
> node-linker=hoisted
> ```

This lets me use pnpm's latest version and still have my build passing. Thanks

**Comment by cpetzel** [comment]
I also faced this issue with our NX monorepo using `pnpm` version 8.15, expo version 51.0.37

The settings.gradle file is [conditionally including the build](https://github.com/expo/expo/blob/6d9bdd622822a721ee69d4e39faf35c47fc425db/docs/public/static/diffs/template-bare-minimum/raw/50..51.diff#L336-L338) for the `react-settings-plugin`, and then [always referencing it ](https://github.com/expo/expo/blob/6d9bdd622822a721ee69d4e39faf35c47fc425db/docs/public/static/diffs/template-bare-minimum/raw/50..51.diff#L341)no matter what version of react native you have. 

Also, it seems there is an issue with the path for determining the gradle-plugin... 
at the bottom of the settings.gradle file, you will see this...

```groovy
includeBuild(new File(["node", "--print", "require.resolve('@react-native/gradle-plugin/package.json', { paths: [require.resolve('react-native/package.json')] })"].execute(null, rootDir).text.trim()).getParentFile())

```
(notice the `paths` parameter to require.resolve)

However, in the `pluginManagement` block at the top of the file, we are NOT using this `paths` property, so it failes to resolve that project. 

```groovy
includeBuild(new File(["node", "--print", "require.resolve('@react-native/gradle-plugin/package.json')"].execute(null, rootDir).text.trim()).getParentFile().toString())
```

## Fix
I fixed my setup by introducing a custom plugin that uses the same module resolution technique as it does in the bottom of the file. It also always requires the `react-settings-plugin` project.

in my `app.config.ts` file...

```typescript
import { ConfigContext, ExpoConfig } from 'expo/config';
import { withSettingsGradle } from 'expo/config-plugins';

// Function to modify the settings.gradle content
function applySettings(gradleSettings: string) {
  const oldContent = `
pluginManagement {
  def version = providers.exec {
    commandLine("node", "-e", "console.log(require('react-native/package.json').version);")
  }.standardOutput.asText.get().trim()
  def (_, reactNativeMinor, reactNativePatch) = version.split("-")[0].tokenize('.').collect { it.toInteger() }

  includeBuild(new File(["node", "--print", "require.resolve('@react-native/gradle-plugin/package.json')"].execute(null, rootDir).text.trim()).getParentFile().toString())
  if(reactNativeMinor == 74 && reactNativePatch <= 3){
    includeBuild("react-settings-plugin")
  }
}
`;

  const newContent = `
pluginManagement {
  def version = providers.exec {
    commandLine("node", "-e", "console.log(require('react-native/package.json').version);")
  }.standardOutput.asText.get().trim()
  def (_, reactNativeMinor, reactNativePatch) = version.split("-")[0].tokenize('.').collect { it.toInteger() }

  includeBuild(new File(["node", "--print", "require.resolve('@react-native/gradle-plugin/package.json', { paths: [require.resolve('react-native/package.json')] })"].execute(null, rootDir).text.trim()).getParentFile())
  includeBuild("react-settings-plugin")
}
`;

  if (gradleSettings.includes(oldContent.trim())) {
    console.log('Replacing settings.gradle content');
    return gradleSettings.replace(oldContent.trim(), newContent.trim());
  }

  return gradleSettings;
}

// Config plugin to apply the custom changes to settings.gradle
const withAndroidSettingsFix = (config: ExpoConfig) => {
  return withSettingsGradle(config, (config) => {
    config.modResults.contents = applySettings(config.modResults.contents);
    return config;
  });
};


// config

const staticConfig: ExpoConfig = {
   ...
  plugins: [
    // TODO - remove this when upgrading to the next RN version (76+)
    withAndroidSettingsFix,
    'expo-router',
    'expo-document-picker',
  ],
  ...
};

```

**Comment by deathook007** [comment]
For me, running the following command worked:
@react-native/gradle-plugin -D

**Comment by delphinebugner** [comment]
Using pnpm here with Expo 52 / RN 0.76.5, had the error on EAS build 👋  

Because of constraints on the rest of the monorepo, I could not use `node-linker=hoisted` in npmrc

Fixed it as mentioned above by adding a direct dependency to `@react-native/gradle-plugin`, thanks for the recommandation 🙂 Not the first time I fix my non-hoistable monorepo like this, did the same for CSS interop layer on NativeWind! Starting to understand the dynamic a little better 😁

**Comment by itsbjoern** [comment]
We also run a pnpm monorepo and cannot globally enable `node-linker=hoisted`. The above seemed to work at first but our EAS build still eventually failed with
```
[stderr] import expo.core.ExpoModulesPackage;
[stderr] symbol:   class ExpoModulesPackage
[stderr] location: package expo.core
```

After wasting a bunch of time the easiest way to fix this was to just temporarily write the line into the .npmrc using the [eas-build-pre-install](https://docs.expo.dev/build-reference/npm-hooks/) hook.
Note: We tried (but did not have any luck with) a second permanent `.npmrc` in the `./packages/mobile` folder

Assuming your Expo project sits in something like `./packages/mobile` in the monorepo you can just add the following to your scripts in package.json. (so `./packages/mobile/package.json`)
```json
  "scripts": {
    "eas-build-pre-install": "echo node-linker=hoisted >> ../../.npmrc"
  }
```

This also resolved a bunch of other issues for us so we were able to remove some awkward patches that were connected to non-hoisted modules.

**Comment by meriadec** [comment]
Thanks @itsbjoern, you saved us quite some trouble :D your solution worked like a charm 🎉

**Comment by andynghiaa** [comment]
Thanks @itsbjoern a lot , it saved my day. Have a nice day!

**Comment by andynghiaa** [comment]
Thanks @itsbjoern  a lot it solved the monorepo problems with expo config, it actually saved my day. Happy coding!

**Comment by KodeKenobi** [comment]
> Hi, sorry for the inconvenience.
> 
> This error is caused by an outdated React Native version in your project.
> 
> To fix that, upgrade to `react-native@^0.74.5` by running: **`npx expo install --fix`** and then run your build again.
> 
> In order to make the SDK51 template compatible with both react-native 0.74 and 0.75 we had to enforce a minimum react-native version of 0.74.4.

This worked for

1) I ran npx expo install --fix
2) npm run android (didn't have my emulator running but tat is no issue, I needed the android folder)
3) cd android
4) ./gradlew clean
