### ISSUE TITLE
Expo 51 Android Build Fail with expo-updates and react-native 0.75.1

### ISSUE THREAD

**Issue by rnkdsh** [expo/expo#31069]
### Minimal reproducible example

-

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

![image](https://github.com/user-attachments/assets/1db6cfe2-e1db-455f-9cc9-aea22870fae7)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      npm: 10.8.2 - ~/.nvm/versions/node/v20.10.0/bin/npm
      Watchman: 2024.01.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/ronakdoshi/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 35.0.0
        System Images: android-33 | Google APIs Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom, android-VanillaIceCream | Google Play Intel x86_64 Atom
        Android NDK: 23.0.7344513-beta4
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.28 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.75.1 => 0.75.1 
    npmGlobalPackages:
      eas-cli: 10.2.4
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by Kudo** [comment]
expo-av@14.0.7 should fix this. thanks for reporting the issue.

**Comment by AyoCodess** [comment]
im still getting the same error too   ``expo-updates": "=0.25.24",``
