### ISSUE TITLE
[expo-video][android]  Video view showing as black while loading

### ISSUE THREAD

**Issue by mihailapuste** [expo/expo#31561]
### Minimal reproducible example

https://github.com/mihailapuste/ExpoVideoTest

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

When a video appears to load or buffer on android, the entire video view component shows as black. 
This isn't something I found the ability to modify or hide either. 

This behaviour isn't reproducible on iOS.

https://github.com/user-attachments/assets/da157820-7319-48a1-a373-04b78b60f64e

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.5.1 - /opt/homebrew/bin/node
      Yarn: 3.6.4 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/bin/npm
      Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.22 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
    npmGlobalPackages:
      eas-cli: 7.1.3
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```
Expected package @expo/metro-config@~0.18.11
Found invalid:
  @expo/metro-config@0.18.9
  (for more info, run: npm why @expo/metro-config)
Advice: Upgrade dependencies that are using the invalid package versions.

Error: Problem validating fields in /Users/mihailapuste/ExpoVideoTesting/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • should NOT have additional property 'displayName'.

Cocoapods version check failed. Cocoapods may not be installed or there may be an issue with your Cocoapods installation. Installing version 1.15.2 or higher is recommended.

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: plugins. 

Advice: Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

(node:846) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The following packages should be updated for best compatibility with the installed expo version:
  expo@51.0.22 - expected version: ~51.0.31
  react-native@0.74.3 - expected version: 0.74.5
  react-native-safe-area-context@4.10.8 - expected version: 4.10.5
  react-native-screens@3.32.0 - expected version: 3.31.1
  @types/react@18.3.3 - expected version: ~18.2.79
  typescript@5.0.4 - expected version: ~5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.
```

**Comment by mihailapuste** [comment]
@behenate 

Hello wonderful expo team!
Wondering if you would have any ideas or updates on the issue above.

Warmest regards!

**Comment by behenate** [comment]
@mihailapuste Hi! Sorry for the late response. Unfortunately this is the default behaviour from ExoPlayer and we can't match iOS without some major changes. Basically before getting the video what you are seeing is the `exo_shutter` view which is black and shows only when there is no data for the `videoSurfaceView` underneath. Now, we can make the `exo_shutter` transparent, but you would just see the empty videoSurfaceView, which is also black as expected. 

I came up with a workaround for now, as I will return to it when we have a bit more time to spare for lower priority bugs. You can patch this line into `VideoView.kt`

```
  override fun onAttachedToWindow() {
    (this.background as? ColorDrawable?)?.let {
      playerView.setShutterBackgroundColor(it.color)
    }
   // ...rest of the function
}
```
Now you will have to specifically set the background color for the VideoView to the background color of the container view. This is the result:

[Screen_recording_20241012_011640.webm](https://github.com/user-attachments/assets/fe9c3f02-aa15-4f71-b178-19d98356e0e1)

**Comment by mihailapuste** [comment]
> @mihailapuste Hi! Sorry for the late response. Unfortunately this is the default behaviour from ExoPlayer and we can't match iOS without some major changes. Basically before getting the video what you are seeing is the `exo_shutter` view which is black and shows only when there is no data for the `videoSurfaceView` underneath. Now, we can make the `exo_shutter` transparent, but you would just see the empty videoSurfaceView, which is also black as expected.
> 
> I came up with a workaround for now, as I will return to it when we have a bit more time to spare for lower priority bugs. You can patch this line into `VideoView.kt`
> 
> ```
>   override fun onAttachedToWindow() {
>     (this.background as? ColorDrawable?)?.let {
>       playerView.setShutterBackgroundColor(it.color)
>     }
>    // ...rest of the function
> }
> ```
> 
> Now you will have to specifically set the background color for the VideoView to the background color of the container view. This is the result:
> 
>  Screen_recording_20241012_011640.webm

Thank you @behenate 
I've added a patch and seems to work very smoothly. Wonderful ✨

**Comment by mihailapuste** [comment]
> > @mihailapuste Hi! Sorry for the late response. Unfortunately this is the default behaviour from ExoPlayer and we can't match iOS without some major changes. Basically before getting the video what you are seeing is the `exo_shutter` view which is black and shows only when there is no data for the `videoSurfaceView` underneath. Now, we can make the `exo_shutter` transparent, but you would just see the empty videoSurfaceView, which is also black as expected.
> > I came up with a workaround for now, as I will return to it when we have a bit more time to spare for lower priority bugs. You can patch this line into `VideoView.kt`
> > ```
> >   override fun onAttachedToWindow() {
> >     (this.background as? ColorDrawable?)?.let {
> >       playerView.setShutterBackgroundColor(it.color)
> >     }
> >    // ...rest of the function
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now you will have to specifically set the background color for the VideoView to the background color of the container view. This is the result:
> > Screen_recording_20241012_011640.webm
> 
> Thank you @behenate I've added a patch and seems to work very smoothly. Wonderful ✨

@behenate 

Hello!

Just following up on this issue.

Althought the above suggested patch https://github.com/expo/expo/issues/31561#issuecomment-2408264488 is a decent workaround for locally loaded videos, it still isn't ideal for when buffering is required for streamed media, as the underlying surface still remains black. Wondering if there are any other suggestions or updates on a potential timeline for this issue.

Thank you for all your hard work!

**Comment by leonardorib** [comment]
> Althought the above suggested patch [#31561 (comment)](https://github.com/expo/expo/issues/31561#issuecomment-2408264488) is a decent workaround for locally loaded videos, it still isn't ideal for when buffering is required for streamed media, as the underlying surface still remains black. Wondering if there are any other suggestions or updates on a potential timeline for this issue.

I followed the discussion and I'm in the exact same situation 😄 

If there's any suggestion it would be really helpful 🙏🏻 

Thank you!

**Comment by bobinrinder** [comment]
@behenate Any update or work around for this? 🙇 One of the last few things stopping us from trying this in production on a large scale. I appreciate the hard work and progress. ❤️

**Comment by behenate** [comment]
@bobinrinder I did some experimentation on this while working on a semi-related issue, will post a PR soon. 
We can disable the `exo_shutter` view and set the SurfaceView to be transparent until `onFirstFrame` event is emitted. The biggier problem was that I encountered this bug https://github.com/google/ExoPlayer/issues/5222
I think I managed to work around it and will be able to show the `SurfaceView` after the stretched out frame has been laid out correctly.

For now I'm planning to introduce a prop, which will allow users to disable the default `exo_shutter` behaviour and enable iOS-like behaviour instead 😄

**Comment by christophemenager** [comment]
Thanks for the update @behenate, can't wait to this fix released, great job!

**Comment by amandaoneal** [comment]
useExoShutter={false} works in most cases, but doesn't seem to work when the video is in a modal. It still shows the black background when loading on Android in this case.

**Comment by amandaoneal** [comment]
useExoShutter={false} does not work when the video is in a Modal.
