### ISSUE TITLE
Release build Android APK won't show local image assets

### ISSUE THREAD

**Issue by ykosaka-welyco** [expo/expo#3226]
### Environment

```
Expo CLI 2.6.13 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.5 - /usr/local/bin/zsh
    Binaries:
      Node: 9.11.1 - ~/.anyenv/envs/ndenv/versions/v9.11.1/bin/node
      Yarn: 1.9.4 - ~/.yarn/bin/yarn
      npm: 6.0.0 - ~/.anyenv/envs/ndenv/versions/v9.11.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.0.9
```

I'm using ExpoKit.

### Steps to Reproduce

1. Run `expo init` and choose react-navigation sample
2. Run `expo eject` and choose ExpoKit.
3. Run `expo publish`
4. Open `android` directory with Android Studio.
5. Set Signing setting for release build from `Project Structure > Signing`
6. Run app with `prodKernelRelease` build variants.

### Expected Behavior

Images should be rendered. 

![screenshot_1547590721](https://user-images.githubusercontent.com/36811303/51213697-fcc68680-195e-11e9-9d2b-c9ea52ed14d1.png)

This screenshot is taken in `devKernelDebug` mode.

### Actual Behavior

Images are not rendered. (Icons, and Image)

![screenshot_1547588926](https://user-images.githubusercontent.com/36811303/51212096-d56dba80-195a-11e9-9859-ee7a38dd11d3.png)

Images fetched through internet are properly rendered.
However if it is a local image, it won't show.
In development mode, images are rendered properly.

### Reproducible Demo

https://github.com/ykosaka-welyco/expo-signed-android-app-image-problem-reproduce

I created a demo `keystore.jks` to sign production apk file. I noted the settings to use it in README.md.

### Related issues

[0.57][ANDROID] Signed release do not show local assets images.
https://github.com/facebook/react-native/issues/21309

**Comment by sjchmiela** [comment]
Hey, sorry for taking so long to look into this. 😕

Could you please try upgrading your `expokit` NPM package to `32.0.6-rc.0` and seeing if the issue persists? 🙂

**Comment by esamelson** [comment]
This is now fixed on our build servers -- please rebuild your app with `expo build:android` or, if you're using ExpoKit, upgrade to `expokit@32.0.6` or later in order to get the fix.

**Comment by jdponomarev** [comment]
Hey guys, this is not fixed for me. I'm on freshly ejected 32 SDK and upgraded to expokit@32.0.6. I don't see assets when I analyze the bundle in Android Studio.

![image](https://user-images.githubusercontent.com/387037/52233321-ce89f600-28cf-11e9-8fd9-2ec454e129f6.png)

They're in bundledAssets after I publish the app as well as in Filesystem object when the app is loaded.

Any ideas?

**Comment by esamelson** [comment]
@jdponomarev - what you're seeing is a separate issue. The issue that was fixed last week was that the assets were properly included in the app bundle but the `FS.bundledAssets` property was undefined.

Do you have `assetBundlePatterns` set in your app.json, and have you published your app at least once after ejecting? If so, and your assets still aren't getting bundled, please open a new issue and fill out the template there fully so we can reproduce the issue. Thanks!

**Comment by jdponomarev** [comment]
@esamelson Hey, sorry, I didn't get why you think that's another issue. Could you please tell me which one you are speaking of? Because actually all the symptoms look pretty the same with this issue for me

FS.bundledAssets has all the assets, assetBundlePatterns are set and everything's fine on emulator. But when I sign a production bundle, they're not there

Thanks!

**Comment by esamelson** [comment]
@jdponomarev - apologies, looks like this is not fixed for ExpoKit projects. We're looking into it now.

**Comment by esamelson** [comment]
@jdponomarev - making [these changes](https://github.com/expo/expo/commit/227bdc3bd080179b7a12b04f285b578c73f7c102) to android/app/expo.gradle fixed the issue for me. Would you be able to give that a try on your project? If that solves the issue for you I'll go ahead and put out a new version of expokit with the changes. Thanks 🙂

**Comment by jdponomarev** [comment]
@esamelson Sure thing! It worked 👍 Thanks!

**Comment by gmaclennan** [comment]
@esamelson I reported a similar issue in https://github.com/expo/expo/issues/3480 and I applied the changes you link to to android/app/expo.gradle and it is working for me now.

**Comment by fcaride** [comment]
> @jdponomarev - making [these changes](https://github.com/expo/expo/commit/227bdc3bd080179b7a12b04f285b578c73f7c102) to android/app/expo.gradle fixed the issue for me. Would you be able to give that a try on your project? If that solves the issue for you I'll go ahead and put out a new version of expokit with the changes. Thanks

This is not working for me

**Comment by esamelson** [comment]
Hi @fcaride - please try [this commit](https://github.com/expo/expo/commit/149129d5b760f403b1e1b78d7cb6928d439387c4) instead. (I've updated it in the previous post as well.) This change has fixed the issue that was originally reported and is now included in newly created ExpoKit projects. If that doesn't fix things for you, could you open a new ticket with specific repro steps so that we can reproduce the exact issue you're seeing? Thanks 🙂 

Going to go ahead and close this now as the issue has been resolved.

**Comment by fcaride** [comment]
It worked!! Thanks!

**Comment by gerbus** [comment]
> Hi @fcaride - please try [this commit](https://github.com/expo/expo/commit/149129d5b760f403b1e1b78d7cb6928d439387c4) instead. (I've updated it in the previous post as well.) This change has fixed the issue that was originally reported and is now included in newly created ExpoKit projects. If that doesn't fix things for you, could you open a new ticket with specific repro steps so that we can reproduce the exact issue you're seeing? Thanks 🙂
> 
> Going to go ahead and close this now as the issue has been resolved.

Thanks! Worked for me too. And for the record I'm using gradle 4.10.2.

**Comment by lilosir** [comment]
@esamelson I just upgraded to 32, I checked my original expo.gradle file seems a little different than [this commit](https://github.com/expo/expo/commit/149129d5b760f403b1e1b78d7cb6928d439387c4), so I force to copied and pasted it. It could not load neither of my images and fonts. But if I use the old one from  [this commit](https://github.com/expo/expo/commit/149129d5b760f403b1e1b78d7cb6928d439387c4), I can see all the png and fonts from **Analyze APK** assets folder. When I run the apk from a device, my fonts could not load when I running on the devices, but the all the images are rendering good.
What's the reason of it, and how can I track it, thx

**Comment by esamelson** [comment]
@lilosir that probably means you're running an older version of gradle. That commit fixes expo.gradle so that it works with gradle 4.10.2, which ships with newly ejected SDK 32 projects. For projects upgraded from an older SDK version, though, you should either leave expo.gradle alone (older version) or update both it AND all the rest of the android gradle/config files to match the SDK 32 templates.

Hope that helps!

**Comment by mattdamon108** [comment]
@esamelson Thanks! It works.

**Comment by joebologna** [comment]
Thanks for posting this. I spent 3 days trying to track this down. For future reference following the links in the forum are a little confusing, so here's a synopsis:

Change the doFirst() method in android/app/expo.gradle to check if the assetsDir does not exist then make it.

```
// Create dirs if they are not there (e.g. the "clean" task just ran)
doFirst {
    if (!assetsDir.exists()) {
      assetsDir.mkdirs()
    }
}
```

I don't know much about Gradle... but it seems making the directory regardless of whether it exists or not should work. I'd never have figured this out. This is still an issue using a fresh "expo init" followed by "expo eject" using SDK33.

**Comment by ozanhonamlioglu** [comment]
Hey there

Please help. I just did everything to make it run, my assets are in right directory, they are in there but it still shows nothing!

I am using SDK 33 and why this is happening, I need to finish a project in my company but it run out of the dead line.

Please help to solve this issue, what am I doing wrong!

**Comment by raikk** [comment]
Hii
In released apk my asset images and all vector icons not showing up.
I am using expokit SDK 33.

**Comment by mlecoq** [comment]
With a newly created project (with react navigation tabs), I have the same behavior as the issue described in the first post. The described commit (which should fix the issue) is already in expo.gradle 

```
android.applicationVariants.each { variant ->
    def folderName = variant.name
    def targetName = folderName.capitalize()

    def assetsDir = file("$buildDir/intermediates/merged_assets/${folderName}/merge${targetName}Assets/out")

    // Bundle task name for variant
    def bundleExpoAssetsTaskName = "bundle${targetName}ExpoAssets"
```

**Comment by mlecoq** [comment]
I have the feeling that it is due to android studio which propose to upgrade Gradle. Since I refuse this upgrade, all is fine

**Comment by Luckygirlllll** [comment]
Same issue here, I just have updated ExpoKit from SDK 32 to SDK 33 and now in release app bundle there are no images and vector icons.

**Comment by Luckygirlllll** [comment]
@joebologna  I have tried tried your solution, but it didn't work for me

@mlecoq  I also already have this code in my expo.gradle

@mlecoq @joebologna Which version of gradle do you use now?

**Comment by amitava82** [comment]
I've updated to SDK34, now it is not showing vector icons in released app.

**Comment by Luckygirlllll** [comment]
@amitava82 I have created new expoKit project from the scratch and copied all src folder from the previous project, now I can see images/icons in the release app bundle.

**Comment by thanh90** [comment]
> I've updated to SDK34, now it is not showing vector icons in released app.

I have the same problem with SDK34 :(

**Comment by thanh90** [comment]
> @jdponomarev - making [these changes](https://github.com/expo/expo/commit/149129d5b760f403b1e1b78d7cb6928d439387c4) to android/app/expo.gradle fixed the issue for me. Would you be able to give that a try on your project? If that solves the issue for you I'll go ahead and put out a new version of expokit with the changes. Thanks 🙂



> Hi @fcaride - please try [this commit](https://github.com/expo/expo/commit/149129d5b760f403b1e1b78d7cb6928d439387c4) instead. (I've updated it in the previous post as well.) This change has fixed the issue that was originally reported and is now included in newly created ExpoKit projects. If that doesn't fix things for you, could you open a new ticket with specific repro steps so that we can reproduce the exact issue you're seeing? Thanks 🙂
> 
> Going to go ahead and close this now as the issue has been resolved.



> @jdponomarev - making [these changes](https://github.com/expo/expo/commit/149129d5b760f403b1e1b78d7cb6928d439387c4) to android/app/expo.gradle fixed the issue for me. Would you be able to give that a try on your project? If that solves the issue for you I'll go ahead and put out a new version of expokit with the changes. Thanks 🙂

This works for me :)

**Comment by SnaiNeR** [comment]
> > I've updated to SDK34, now it is not showing vector icons in released app.
> 
> I have the same problem with SDK34 :(
> gradle-4.10.2
> build:grade:3.3.2

updating gradle to ^^ versions helps me !!! (with adding this changes too [https://github.com/expo/expo/commit/149129d5b760f403b1e1b78d7cb6928d439387c4](url))

**Comment by MHauray** [comment]
Hello,

I managed to correct my image display problem by removing this line from the app.json file. If it can help others :)

Expo SDK 34

"assetBundlePatterns": [
       "** / *"
     ]

Regards,

**Comment by madida** [comment]
I had this issue Using Expo SDK 33 and Gradle 4.10.2.

The solution for me was to rewrite the **doFirst** hook in **android/app/expo.gradle** to

`      // Create dirs if they are not there (e.g. the "clean" task just ran)
      doFirst {
        if (!assetsDir.exists()) {
          assetsDir.mkdirs()
        }
      }
`

During the build process, the asset directory was being overwritten.

**Comment by felipegouveiae** [comment]
Hey  Guys. I have the same issue. I tried @madida and @MHauray and no success. Anything that could help me at all?

**Comment by felipegouveiae** [comment]
I'm my case, it was all about gradle's version. 

I created a project on expo SDK v35 and ejected the project. 

Android Studio asked me to update at some point and I silly accepted. 

For Expo v35 after rolling back Gradle version to the following solved the issue : 
        * Android Gradle Plugin Version - 3.3.2
        * Gradle Version - 4.10.2
