### ISSUE TITLE
DOM Component throws error in dev client using SDK 52.0.0 beta preview 7

### ISSUE THREAD

**Issue by StefSchalks** [expo/expo#32449]
### Minimal reproducible example

https://github.com/StefSchalks/expo-52-beta-7-dom-issues

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

I created a development build with the newest beta release to test out dom-components. 
For creating the project, I used the command:
```
npx create-expo-app --template blank@beta    
```

When opening the app, instead of displaying the dom component, I instantly am prompted with the render error:
```
 (NOBRIDGE) ERROR  Warning: Error: Exception in HostFunction: Unable to convert string to floating point value: "normal"      
```

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~52.0.0-preview.7 => 52.0.0-preview.7
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.0 => 0.76.0
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✖ Validate packages against React Native Directory package metadata
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✖ Check that packages match versions required by installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: @expo/metro-runtime
Advice:
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

The following packages should be updated for best compatibility with the installed expo version:
  @expo/metro-runtime@4.0.0-preview.0 - expected version: ~4.0.0-preview.0
  expo-dev-client@5.0.0-preview.2 - expected version: ~5.0.0-preview.2
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.
```

**Comment by gabrieldonadel** [comment]
Hi @StefSchalks, this has now been fixed in the latest release of Expo beta, please update to preview 12

**Comment by doublex** [comment]
@StefSchalks 
Same issue.
Has the problem gone away by updating?

**Comment by StefSchalks** [comment]
Nope, still happens (also in expo go and dev builds) with the stable version.

**Comment by quitran97** [comment]
> Nope, still happens (also in expo go and dev builds) with the stable version... I'll file a new issue later today.

I've got this problem in the newest Expo version, too. Do you create a new issue?

**Comment by StefSchalks** [comment]
@quitran97 Yes! I created a new issue. You can find it here #32998
