### ISSUE TITLE
Modal screen with CustomHeader and a reanimated exiting animation causes glitches on swipe down [ios]

### ISSUE THREAD

**Issue by YasinAkimura** [expo/expo#32940]
### Minimal reproducible example

https://github.com/YasinAkimura/expo-sdk-52-modal-bug-reanimated

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

While upgrading to SKD 52 I happened to catch a weird bug which only started happening on the new arch using the newest expo router.

# Affected Platform
- iOS
- Expo Go (iOS)
# Expected Behavior
I can dismiss the modal containing any basic headers configured in screenOptions and I should be able to use functionalities which are not marked as unstable or experimental like exiting animations on reanimated.

# Whats actually happening
App and Modal screen glitches completely out after swiping it down a few times.
  - Note: You don't even have to do it as fast as I did on the provided video.

I am also sure that this bug is different from https://github.com/expo/expo/issues/32874#issuecomment-2477988050 as react-native-screens does not fix that issue and the cause is precise problem.
  - Did not happen on previous SDK 
  - I think that issue is related to reanimated and expo-router eg. react-navigation.
  - What's weird is that the cause is so specific ONLY IF you use a custom header and happen to have an exiting animation on any component in that modal it glitches out so it might be connected.
 
https://github.com/user-attachments/assets/af9b2aac-b990-4751-95bb-5aac76921348

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.17.0/bin/yarn
      npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7 
      expo-router: ~4.0.5 => 4.0.5 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
this is fixed by https://github.com/software-mansion/react-native-screens/pull/2496
we'll bump the version of react-native-screens used in expo go, but you can use 4.1.0 already in development builds. we always recommend using development builds instead of the go app for any non-trivial real-world projects. there isn't a good reason really to use "go" instead of development builds beyond just getting started and quick experiments. learn more: https://expo.dev/blog/expo-go-vs-development-builds

[this doc explains how to exclude](https://docs.expo.dev/more/expo-cli/#configuring-dependency-validation) react-native-screens from validation so you can bump to 4.1.0 and then you can [create a development build with that version 
](https://docs.expo.dev/tutorial/eas/configure-development-build/)

**Comment by YasinAkimura** [comment]
# not fixed
Tried on ios simulator its still glitching and crashing
As I mentioned its very specific and seems to be different from the other bug

```
[Foundation] *** Assertion failure in -[RNSScreenStackView setModalViewControllers:](),
/Users/yasinsimsek/Projects/ExpoSDK52-Modal-issue/node_modules/react-native-screens/ios/RNSScreenStack.mm:452
[CoreFoundation] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modally presented controllers are
being reshuffled, this is not allowed'
*** First throw call stack:
(
0   CoreFoundation                      0x00000001804b757c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x000000018008eda8 objc_exception_throw + 72
2   Foundation                          0x0000000180e7a398 -[NSMutableDictionary(NSMutableDictionary) classForCoder] + 0
3   ExpoSDK52Modalissue.debug.dylib     0x0000000108e33d8c -[RNSScreenStackView setModalViewControllers:] + 1712
4   ExpoSDK52Modalissue.debug.dylib     0x0000000108e35de0 -[RNSScreenStackView updateContainer] + 1208
5   ExpoSDK52Modalissue.debug.dylib     0x0000000108e34588 __46-[RNSScreenStackView setModalViewControllers:]_block_invoke + 220
6   ExpoSDK52Modalissue.debug.dylib     0x0000000108e34e14 __46-[RNSScreenStackView setModalViewControllers:]_block_invoke_2 + 144
7   UIKit                               0x0<…>
```

**Comment by brentvatne** [comment]
@YasinAkimura - can you post an issue to react-native-screens with a minimal reproducible example outside of expo go if you are still experiencing this?

**Comment by YasinAkimura** [comment]
@brentvatne - Yes, sure I'll do that as it seems to be still related to them.

**Comment by derekvawdrey** [comment]
I am encountering similar issues on Expo 53

**Comment by colby-mchenry** [comment]
Still happening in Expo 54
