### ISSUE TITLE
<Link> does not "unwind" to the route that is already in the stack

### ISSUE THREAD

**Issue by mbackonja** [expo/expo#33014]
### Minimal reproducible example

https://github.com/mbackonja/expo-router-issue

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Documentation says:

> Expo Router uses a stack-based navigation approach. Each new route you navigate to get added to a stack. If you navigate to a route already in the stack, the stack unwinds back to that existing route.
>
>For example, when you navigate from /feed to /profile, the stack contains /feed and /profile. If you then navigate to /settings, the stack contains /feed, /profile, and /settings. If you then navigate back to /feed, the stack unwinds back to /feed.

And it was working just like that in the previous Expo SDK 51 version. After upgrading to Expo SDK 52, this feature looks broken. I included minimum reproducible code in the GitHub repo and I'm providing two screen recordings for easier understanding of what's happening...

Expo SDK 52 (broken):

[android_issue.webm](https://github.com/user-attachments/assets/0901e411-95a2-466a-b6cc-6b9fe2bbd719)

Expo SDK 51 (working):

[android_working.webm](https://github.com/user-attachments/assets/782c0d17-1406-483b-a7ee-8faa58365653)

It was tested on both Android and iOS, both in a Simulator and on real devices.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
      npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
      Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7
      expo-router: ~4.0.6 => 4.0.6
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
      react-native-web: ~0.19.13 => 0.19.13
    npmGlobalPackages:
      eas-cli: 13.2.3
    Expo Workflow: managed
```

**Comment by nchangizi** [comment]
experiencing the same issue

**Comment by marklawlor** [comment]
This is fixed in `4.0.9`. React Navigation 7 changed the behaviour of the navigate function, please use <Link dismissTo href="" />` to retain this functionality. Docs should be published later today

**Comment by nchangizi** [comment]
Can I pass props using <Link dismissTo>?

**Comment by DjellalAbdou** [comment]
its really weird, am using the 4.0.9 and am still having this issue with the dismissTo prop, my use case is as follows: 
1- I have a root page that uses a router.push to send the flow to the login page
2- the login page uses a link to send you to the sign-up page
3- sign up page has a link to send you to the login page

when I press the login link in the sign-up page, the flow is not getting back to the previous page AKA the login but its like its adding a new login page to the stack

I found out that using router.navigate in the login page fixes the issues but its still really weird
