### ISSUE TITLE
[SDK52] [expo-updates] android build failure: Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (17) and 'kspDebugKotlin' (21).

### ISSUE THREAD

**Issue by rranjan14** [expo/expo#33107]
### Minimal reproducible example

https://github.com/rranjan14/expo-update-test

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

ksp version is too old for the kotlin version being used. Happening with expo-updates.
<img width="1259" alt="Screenshot 2024-11-20 at 16 19 37" src="https://github.com/user-attachments/assets/fa69a5e7-18b9-49fb-9282-5a09ef72ba80">

JVM version I am using is 17

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 3.7.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.13.1/bin/yarn
      npm: 10.9.0 - /opt/homebrew/bin/npm
      Watchman: 2024.11.18.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 33, 34, 35
        Build Tools: 30.0.2, 30.0.3, 33.0.0, 34.0.0, 35.0.0, 35.0.0
        System Images: android-UpsideDownCakePrivacySandbox | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.8 => 52.0.8
      react: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
    npmGlobalPackages:
      eas-cli: 13.1.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by AbdulRehman960** [comment]
Same issue, any solution?

**Comment by lukmccall** [comment]
I was unable to reproduce the issue, and the repository link is broken. Could you create a minimal reproduction for us to investigate the problem further?

I've created a fresh project with:
- `expo@52.0.8`
- `expo-updates@0.26.7`

**Comment by rranjan14** [comment]
> I was unable to reproduce the issue, and the repository link is broken. Could you create a minimal reproduction for us to investigate the problem further?
> 
> I've created a fresh project with:
> 
> * `expo@52.0.8`
> * `expo-updates@0.26.7`

Hey, I made it private mistakingly. I have made it public now. I am using the same versions as mentioned by you. Also, I have removed the actual `projectId` and `updates.url`. You'll need to fill in with your values.

**Comment by gtwilliams03** [comment]
I am getting the same error also (although I suspect mine was related to moving from a 2019 MacBook Pro to a new M4 Max MacBook Pro (and I have had to reinstall several coding related packages to move from `x64` to `arm64` packages.  Android Studio, Android SDKs, Java JRE and JDK have been the problem children.

Output from my latest Android development build:

```
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':expo-updates:kspDebugKotlin'.
[RUN_GRADLEW] > Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (17) 
and 'kspDebugKotlin' (21).
[RUN_GRADLEW]   
[RUN_GRADLEW]   Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
[RUN_GRADLEW]   Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation
```

**Comment by lukmccall** [comment]
Hmm, that's weird. I was able to build it locally: 
<img width="699" alt="image" src="https://github.com/user-attachments/assets/edb87be0-f25c-434b-b15f-7111174b5b18">

**Comment by lukmccall** [comment]
Can you send me your build logs or link to the build on the EAS?

**Comment by rranjan14** [comment]
Is it possible that `kspVersion` is taken `1.8.x` due to the project kotlin version being `1.8.x` but the `expo-updates-gradle-plugin` specifically uses `1.9.24`?

<img width="643" alt="Screenshot 2024-11-20 at 21 26 37" src="https://github.com/user-attachments/assets/d74b1b2c-e1a3-4c04-a555-7dca9f544ab3">

**Comment by adi87** [comment]
For what it's worth, I'm getting the exact same error message after upgrading to SDK 52 in my own project and trying to run locally.

```
npx expo run:android
```

I was also able to replicate the same issue with the same repro example provided above in the repository expo-update-test.

### Environment
```
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.8 => 52.0.8
      react: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
    Expo Workflow: bare
```

**Comment by lukmccall** [comment]
Which version of java are you using (what is the output of `java --version`)? 
You can also try to add the following lines under the `android` block:
```
kotlin {
  jvmToolchain(17)
}
```
to the `android/build.gradle` inside of the `expo-updates` package.

**Comment by Kudo** [comment]
when building with android studio. please makes sure to use jdk 17. the new android studio uses its jdk 21 by default. 
![Screenshot 2024-11-12 at 1 10 02 AM](https://github.com/user-attachments/assets/e47b9566-2e9e-4410-b4aa-e4df6491ed9c)

**Comment by vegidio** [comment]
Same problem for me: I have Java 21 installed in my machine and my project used to build fine with Expo 51, but as soon as I upgraded to Expo 52 I started to get the error below:

```
> Task :expo-updates:kspDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-updates:kspDebugKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (17) and 'kspDebugKotlin' (21).

  Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
  Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation
```

The problem seems to be coming from `expo-updates`.

**Comment by Kudo** [comment]
> Same problem for me: I have Java 21 installed in my machine and my project used to build fine with Expo 51, but as soon as I upgraded to Expo 52 I started to get the error below

expo-updates in sdk 51 still uses kapt than ksp.
anyway, having #33148 to fix the issue anyway

**Comment by esipavicius** [comment]
Im also getting this
```
* What went wrong:
Could not determine the dependencies of task ':expo-updates:bundleLibCompileToJarDebug'.
> Could not create task ':expo-updates:kspDebugKotlin'.
   > Cannot query the value of task ':expo-updates:compileDebugKotlin' property 'moduleName' because it has no value available.
```

**Comment by Kaarelmm** [comment]
The issue was fixed with expo-updates@0.26.9 and also make sure to update expo to @52.0.11 (atleast thats the lates at this time and applyKspJvmToolchain didn't exist in @52.0.0 yet. Thank you @brentvatne for the fix!

**Comment by thyming** [comment]
I'm still experiencing this issue on eas with expo 52.0.23, expo updates 0.26.10. i am able to build with eas --local

**Comment by souyahia** [comment]
I had this issue when building my Expo app locally using `expo run:android`. I fixed it by :
- Installing [JDK 17](https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html) on my machine
- [Setting the $JAVA_HOME](https://stackoverflow.com/questions/14702702/how-to-set-java-home-in-mac-permanently) env var on my machine and making it point to the JDK 17
- Setting the Gradle JDK version to 17 in Android Studio, as shown in Kudo's screenshot above

**Comment by Monte9** [comment]
Thanks @souyahia! I was on Java v20 and downgrading to Java v17 worked for me on Expo v51. Appreciate the guidance! 🙏🏼
