### ISSUE TITLE
[SDK52] Android release variant build crashes on Windows

### ISSUE THREAD

**Issue by andrejpavlovic** [expo/expo#33151]
### Minimal reproducible example

https://github.com/allboatsrise/expo-52-test

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

I'm getting `Error: Unable to resolve module` error when trying to run `npx expo run:android --variant release`  on Windows on fresh install.

Reproduce:

```powershell
npx create-expo-app@latest my-app
cd my-app
npx expo run:android --variant release
```

Result:
```powershell
√ Created native directory
√ Updated package.json | no changes
√ Finished prebuild
› Building app...
Starting Metro Bundler
warning: Bundler cache is empty, rebuilding (this may take a minute)
Error: Unable to resolve module ./C:/Users/Andrej/my-app/node_modules/expo-router/entry.js from C:\Users\Andrej\my-app/.:

None of these files exist:
  * C:\Users\Andrej\my-app\node_modules\expo-router\entry.js(.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.mjs|.native.mjs|.mjs|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css)
  * C:\Users\Andrej\my-app\node_modules\expo-router\entry.js
Error: Unable to resolve module ./C:/Users/Andrej/my-app/node_modules/expo-router/entry.js from C:\Users\Andrej\my-app/.:

None of these files exist:
  * C:\Users\Andrej\my-app\node_modules\expo-router\entry.js(.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.mjs|.native.mjs|.mjs|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css)
  * C:\Users\Andrej\my-app\node_modules\expo-router\entry.js
    at ModuleResolver.resolveDependency (C:\Users\Andrej\my-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:112:15)
    at DependencyGraph.resolveDependency (C:\Users\Andrej\my-app\node_modules\metro\src\node-haste\DependencyGraph.js:235:43)
    at C:\Users\Andrej\my-app\node_modules\metro\src\lib\transformHelpers.js:160:21
    at Server._resolveRelativePath (C:\Users\Andrej\my-app\node_modules\metro\src\Server.js:1104:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at MetroBundlerDevServer.resolveRelativePathAsync (C:\Users\Andrej\my-app\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:1677:12)
    at MetroBundlerDevServer.metroLoadModuleContents (C:\Users\Andrej\my-app\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:506:35)
    at MetroBundlerDevServer.legacySinglePageExportBundleAsync (C:\Users\Andrej\my-app\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:809:20)
    at exportEmbedBundleAndAssetsAsync (C:\Users\Andrej\my-app\node_modules\@expo\cli\src\export\embed\exportEmbedAsync.ts:193:21)
    at exportEmbedInternalAsync (C:\Users\Andrej\my-app\node_modules\@expo\cli\src\export\embed\exportEmbedAsync.ts:125:37)
```

It looks like some sort of an issue building on Windows since the path seems to be prefixed with `./`

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20240728.093121.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
    IDEs:
      Android Studio: AI-242.21829.142.2421.12409432
    npmPackages:
      expo: ~52.0.9 => 52.0.9
      expo-router: ~4.0.7 => 4.0.7
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Validate packages against React Native Directory package metadata
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

**Comment by Kudo** [comment]
#33114 covers the `path.isAbsolute` fwiw

**Comment by rohankm** [comment]
facing same issue

**Comment by YasinAkimura** [comment]
Was this already fixed? I am able to make release variants without issues on android just pointing this out as there might be something else behind? But I am using android studio but the process should be almost the same?

**Comment by stochmalm** [comment]
I have the same issue, tried clearing caches, removing node_modules, changing "main": "expo-router/entry" in package json to "index.js" and importing router in "index.js" but nothing helps. I will try to apply patch by @andrejpavlovic .

npx expo run:android --variant release

`env: load .env
env: export EXPO_PUBLIC_API_URL EXPO_PUBLIC_API_KEY
› Building app...
Starting Metro Bundler
warning: Bundler cache is empty, rebuilding (this may take a minute)
Error: Unable to resolve module ./C:/Projekty/DentaCityConsentApp/frontend/node_modules/expo-router/entry.js from C:\Projekty\DentaCityConsentApp\frontend/.: 

None of these files exist:
  * C:\Projekty\DentaCityConsentApp\frontend\node_modules\expo-router\entry.js(.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.mjs|.native.mjs|.mjs|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css)
  * C:\Projekty\DentaCityConsentApp\frontend\node_modules\expo-router\entry.js
Error: Unable to resolve module ./C:/Projekty/DentaCityConsentApp/frontend/node_modules/expo-router/entry.js from C:\Projekty\DentaCityConsentApp\frontend/.: 

None of these files exist:
  * C:\Projekty\DentaCityConsentApp\frontend\node_modules\expo-router\entry.js(.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.mjs|.native.mjs|.mjs|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css)
  * C:\Projekty\DentaCityConsentApp\frontend\node_modules\expo-router\entry.js
    at ModuleResolver.resolveDependency (C:\Projekty\DentaCityConsentApp\frontend\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:112:15)
    at DependencyGraph.resolveDependency (C:\Projekty\DentaCityConsentApp\frontend\node_modules\metro\src\node-haste\DependencyGraph.js:235:43)
    at C:\Projekty\DentaCityConsentApp\frontend\node_modules\metro\src\lib\transformHelpers.js:160:21
    at Server._resolveRelativePath (C:\Projekty\DentaCityConsentApp\frontend\node_modules\metro\src\Server.js:1104:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at MetroBundlerDevServer.resolveRelativePathAsync (C:\Projekty\DentaCityConsentApp\frontend\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:1677:12)
    at MetroBundlerDevServer.metroLoadModuleContents (C:\Projekty\DentaCityConsentApp\frontend\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:506:35)
    at MetroBundlerDevServer.legacySinglePageExportBundleAsync (C:\Projekty\DentaCityConsentApp\frontend\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:809:20)
    at exportEmbedBundleAndAssetsAsync (C:\Projekty\DentaCityConsentApp\frontend\node_modules\@expo\cli\src\export\embed\exportEmbedAsync.ts:193:21)
    at exportEmbedInternalAsync (C:\Projekty\DentaCityConsentApp\frontend\node_modules\@expo\cli\src\export\embed\exportEmbedAsync.ts:125:37)`

**Comment by mr-tm** [comment]
@Kudo @byCedric 
https://github.com/expo/expo/pull/33114 seems to cause crash when building basic [monorepo](https://docs.expo.dev/guides/monorepos/) folder structure release version on Windows: 
`npx expo run:android --variant release`

> Task :app:createBundleReleaseJsAndAssets
  Eager key: {"bundleEncoding":"utf8","dev":false,"entryFile":"C:\\Projects\\myapp\\apps\\native\\index.js","minify":false,"platform":"android","sourcemapUseAbsolutePath":false}
Request key: {"bundleEncoding":"utf8","dev":false,"entryFile":"index.js","minify":false,"platform":"android","sourcemapOutput":"android\\app\\build\\intermediates\\sourcemaps\\react\\release\\index.android.bundle.packager.map","sourcemapUseAbsolutePath":false}     
warning: Eager bundle does not match new options, bundling again.
Starting Metro Bundler
Error: Unable to resolve module ./index.js from C:\Projects\myapp/.: 

Hardcoding
`opts.mainModuleName = './' + opts.mainModuleName;`
to
`opts.mainModuleName = "./apps/native";`
fixes the issue for me.

On dev everything works fine without changes.

**Comment by andrejpavlovic** [comment]
This is fixed as of `expo@52.0.14` (`expo-cli@0.22.0`).

**Comment by robertwt7** [comment]
uhh i'm still receiving this issue i believe. was this fixed for you on a new app? I just opened a new issue at #34602
