### ISSUE TITLE
[android][expo-video]: Error: Exception in HostFunction: java.lang.IllegalStateException: HorizontalScrollView can host only one direct child

### ISSUE THREAD

**Issue by m1st1ck** [expo/expo#33441]
### Minimal reproducible example

https://github.com/m1st1ck/expo-video-crash

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

Navigating away from screen that contains FlatList with VideoView in renderItem causes the app to crash with `Error: Exception in HostFunction: java.lang.IllegalStateException: HorizontalScrollView can host only one direct child`

Only on android, dev build and standalone.

Works fine on Expo Go and iOS

```
"@react-navigation/native": "^7.0.13",
"@react-navigation/native-stack": "^7.1.14",
"expo": "~52.0.14",
"expo-dev-client": "~5.0.5",
"expo-status-bar": "~2.0.0",
"expo-video": "~2.0.2",
"react": "18.3.1",
"react-native": "0.76.3",
"react-native-safe-area-context": "4.12.0",
"react-native-screens": "~4.1.0"
```

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.5
      Shell: 3.6.0 - /opt/homebrew/bin/fish
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.11.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.14 => 52.0.14 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
    npmGlobalPackages:
      eas-cli: 13.4.2
      expo-cli: 6.3.10
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: expo-video
Advice: 
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.
```

**Comment by doublex** [comment]
Same issue

**Comment by behenate** [comment]
Hi! It seems like this issue is related to `rn-screens` and the handling of transitions of screens with FlatLists. I'll talk with the `rn-screens` team for some more details.

**Comment by kkafar** [comment]
Hey, I'm from `react-native-screens` team here. My [fix to core](https://github.com/facebook/react-native/pull/47634) has landed just couple of days ago - we'll be able to fix this issue from react-native 0.77 forward (assuming the commit will get included). Action you can take immediately is to patch the lib ( yeah :/ ) & add your special case here: https://github.com/software-mansion/react-native-screens/blob/afd5e723dedf57ae95e5c692358aa025987a6f28/android/src/main/java/com/swmansion/rnscreens/Screen.kt#L413-L417

**Comment by behenate** [comment]
The issue should be fixed in `react-native-screens` `4.4.0`, right now `4.4.0-rc0` is available. You can use it to test if it resolves the issue. When a stable version is available an upgrade should resolve the problems 😄

**Comment by glagou** [comment]
Hey! I am currently facing the same issue as above ⬆️ I have tried installing `react-native-screens` `4.4.0` and manually patching the lib, however the issue remains unsolved (`HorizontalScrollView can host only one direct child`). Is there a chance we have more updates on this that I have missed 😭?

Thank you guys.

**Comment by behenate** [comment]
@glagou Are you using a develipment build or Expo Go? I just tested the [repro from above](https://github.com/m1st1ck/expo-video-crash) with `screens` bumped to `4.4.0` and it seems like it fixed the issue there.

**Comment by glagou** [comment]
@behenate I used a development build for it. Since you have verified it, I will give it another go and come back. Maybe I missed something in the process. Thank you :pray:

**Comment by glagou** [comment]
I must have done something wrong. I made the update and the issue seems to be resolved. Thank you @behenate! 💯

**Comment by behenate** [comment]
@glagou Awesome to hear that! 😄
