### ISSUE TITLE
crash when excluding expo-font module

### ISSUE THREAD

**Issue by fatlinesofcode** [expo/expo#33552]
### Minimal reproducible example

n/a

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a standalone app

### Summary

In our bare app, we're seeing crashes in production environment from expo-font noted in https://github.com/expo/expo/issues/31563

we're attempted exclude expo-font from the project as we dont use it.

we've added to package.json
```
"expo": {
    "autolinking": {
      "exclude": [
        "expo-font",
        "expo-keep-awake"
      ]
    }
  },
  ```

this does exclude expo-font from the build but the app crashes at runtime in release mode.

It seems its still attempting to load expo-font

```
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Error: Cannot find native module 'ExpoFontLoader', js engine: hermes', reason: 'Unhandled JS Exception: Error: Cannot find native module 'ExpoFontLoader', js engine: hermes, stack:
requireNativeModule@202056:21
anonymous@292586:86
loadModuleImplementation@157:13
guardedLoadModule@96:37
metroRequire@38:91
anonymous@292358:54
loadModuleImplementation@157:13
guardedLoadModule@96:37
metroRequire@38:91
anonymous@292268:21
loadModuleImplementation@157:13
guardedLoadModule@96:37
metroRequire@38:91
anonymous@292168:44
loadModuleImplementation@157:13
guardedLoadModule@96:37
metroRequire@38:91
anonymous@292139:53
loadModuleImplementation@157:13
guardedLoadModule@96:37
```

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - /opt/homebrew/opt/node@18/bin/node
      Yarn: 3.6.4 - /opt/homebrew/opt/node@18/bin/yarn
      npm: 10.2.4 - /opt/homebrew/opt/node@18/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/phil/.rbenv/versions/2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 34
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-33 | ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.21829.142.2421.12409432
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.39 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.75.4 => 0.75.4 
    npmGlobalPackages:
      eas-cli: 3.17.1
      expo-cli: 6.3.10
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✖ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✔ Check npm/ yarn versions
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

**Comment by chrfalch** [comment]
Hi @falcoagustin! Thanks for the issue :) 

I've added this as potentially being fixed by #33574 - although the error you report about excluding auto linking is **not** fixed by that PR - I view it as a attempt to fix the problem of the crashing font manager.

**Comment by fatlinesofcode** [comment]
thanks @chrfalch we have deployed the fix from https://github.com/expo/expo/pull/33574 as a patch in our production environment but are still seeing similar crash reports:


```
          Crashed: expo.fontfamilyaliasmanager
0   [redacted]                   0x1ac928 closure #1 in static FontFamilyAliasManager.familyName(forAlias:) + 6 (FontFamilyAliasManager.swift:6)
1   [redacted]                   0x1ae428 partial apply for closure #1 in static FontFamilyAliasManager.familyName(forAlias:) + 4377289768 (<compiler-generated>:4377289768)
2   libswiftDispatch.dylib         0x2dd4 partial apply for thunk for @callee_guaranteed () -> (@out A, @error @owned Error) + 28
3   libswiftDispatch.dylib         0x2db0 thunk for @callee_guaranteed () -> (@out A, @error @owned Error)partial apply + 16
4   libswiftDispatch.dylib         0x2d18 closure #1 in closure #1 in OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 192
5   libswiftDispatch.dylib         0x2c3c partial apply for thunk for @callee_guaranteed () -> () + 28
6   libswiftDispatch.dylib         0x2c14 thunk for @escaping @callee_guaranteed () -> () + 28
7   libdispatch.dylib              0x3fa8 _dispatch_client_callout + 20
8   libdispatch.dylib              0x13e2c _dispatch_sync_invoke_and_complete + 56
9   libswiftDispatch.dylib         0x46b0 implicit closure #2 in implicit closure #1 in OS_dispatch_queue.asyncAndWait<A>(execute:) + 192
10  libswiftDispatch.dylib         0x45e8 partial apply for implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 76
11  libswiftDispatch.dylib         0x4468 OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 404
12  libswiftDispatch.dylib         0x42a4 OS_dispatch_queue.asyncAndWait<A>(execute:) + 140
13  libswiftDispatch.dylib         0x4210 OS_dispatch_queue.sync<A>(execute:) + 64
14  [redacted]                   0x1ae340 specialized static UIFont._expo_fontNames(forFamilyName:) + 46 (FontFamilyAliasManager.swift:46)
15  [redacted]                   0x1ae1f0 @objc static UIFont._expo_fontNames(forFamilyName:) + 4377289200 (<compiler-generated>:4377289200)
16  [redacted]                   0x5a9098 fontNamesForFamilyName(NSString*) + 175 (RCTFont.mm:175)
17  [redacted]                   0x5a87a4 +[RCTFont updateFont:withFamily:size:weight:style:variant:scaleMultiplier:] + 450 (RCTFont.mm:450)
18  [redacted]                   0x4b1300 -[RCTTextAttributes effectiveFont] + 220 (RCTTextAttributes.mm:220)
19  [redacted]                   0x4b0ee0 -[RCTTextAttributes effectiveTextAttributes] + 150 (RCTTextAttributes.mm:150)
20  [redacted]                   0x4ad168 -[RCTBaseTextShadowView attributedTextWithBaseTextAttributes:] + 101 (RCTBaseTextShadowView.mm:101)
21  [redacted]                   0x4b2d10 -[RCTTextShadowView attributedTextWithMeasuredAttachmentsThatFitSize:] + 179 (RCTTextShadowView.mm:179)
22  [redacted]                   0x4b3090 -[RCTTextShadowView textStorageAndLayoutManagerThatFitsSize:exclusiveOwnership:] + 227 (RCTTextShadowView.mm:227)
23  [redacted]                   0x4b2104 RCTTextShadowViewMeasure(YGNode const*, float, YGMeasureMode, float, YGMeasureMode) + 385 (RCTTextShadowView.mm:385)
24  [redacted]                   0xa50824 facebook::yoga::Node::measure(float, facebook::yoga::MeasureMode, float, facebook::yoga::MeasureMode) + 57 (Node.cpp:57)
25  [redacted]                   0xa4b108 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 318 (CalculateLayout.cpp:318)
26  [redacted]                   0xa4c5ac facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 106 (FlexDirection.h:106)
27  [redacted]                   0xa4c5ac facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 106 (FlexDirection.h:106)
28  [redacted]                   0xa4cf60 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 49 (LayoutResults.h:49)
29  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
30  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
31  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
32  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
33  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
34  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
35  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
36  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
37  [redacted]                   0xa487b0 facebook::yoga::layoutAbsoluteChild(facebook::yoga::Node const*, facebook::yoga::Node const*, facebook::yoga::Node*, float, float, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 457 (AbsoluteLayout.cpp:457)
38  [redacted]                   0xa494ec facebook::yoga::layoutAbsoluteDescendants(facebook::yoga::Node*, facebook::yoga::Node*, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int, float, float, float, float) + 52 (Style.h:52)
39  [redacted]                   0xa4efe4 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 2099 (CalculateLayout.cpp:2099)
40  [redacted]                   0xa487b0 facebook::yoga::layoutAbsoluteChild(facebook::yoga::Node const*, facebook::yoga::Node const*, facebook::yoga::Node*, float, float, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 457 (AbsoluteLayout.cpp:457)
41  [redacted]                   0xa494ec facebook::yoga::layoutAbsoluteDescendants(facebook::yoga::Node*, facebook::yoga::Node*, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int, float, float, float, float) + 52 (Style.h:52)
42  [redacted]                   0xa4efe4 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 2099 (CalculateLayout.cpp:2099)
43  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
44  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
45  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
46  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
47  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
48  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
49  [redacted]                   0xa487b0 facebook::yoga::layoutAbsoluteChild(facebook::yoga::Node const*, facebook::yoga::Node const*, facebook::yoga::Node*, float, float, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 457 (AbsoluteLayout.cpp:457)
50  [redacted]                   0xa494ec facebook::yoga::layoutAbsoluteDescendants(facebook::yoga::Node*, facebook::yoga::Node*, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int, float, float, float, float) + 52 (Style.h:52)
51  [redacted]                   0xa4efe4 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 2099 (CalculateLayout.cpp:2099)
52  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
53  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
54  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
55  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
56  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
57  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
58  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
59  [redacted]                   0xa487b0 facebook::yoga::layoutAbsoluteChild(facebook::yoga::Node const*, facebook::yoga::Node const*, facebook::yoga::Node*, float, float, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 457 (AbsoluteLayout.cpp:457)
60  [redacted]                   0xa494ec facebook::yoga::layoutAbsoluteDescendants(facebook::yoga::Node*, facebook::yoga::Node*, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int, float, float, float, float) + 52 (Style.h:52)
61  [redacted]                   0xa4efe4 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 2099 (CalculateLayout.cpp:2099)
62  [redacted]                   0xa487b0 facebook::yoga::layoutAbsoluteChild(facebook::yoga::Node const*, facebook::yoga::Node const*, facebook::yoga::Node*, float, float, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 457 (AbsoluteLayout.cpp:457)
63  [redacted]                   0xa494ec facebook::yoga::layoutAbsoluteDescendants(facebook::yoga::Node*, facebook::yoga::Node*, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int, float, float, float, float) + 52 (Style.h:52)
64  [redacted]                   0xa4efe4 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 2099 (CalculateLayout.cpp:2099)
65  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
66  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
67  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
68  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
69  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
70  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
71  [redacted]                   0xa487b0 facebook::yoga::layoutAbsoluteChild(facebook::yoga::Node const*, facebook::yoga::Node const*, facebook::yoga::Node*, float, float, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 457 (AbsoluteLayout.cpp:457)
72  [redacted]                   0xa494ec facebook::yoga::layoutAbsoluteDescendants(facebook::yoga::Node*, facebook::yoga::Node*, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int, float, float, float, float) + 52 (Style.h:52)
73  [redacted]                   0xa4efe4 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 2099 (CalculateLayout.cpp:2099)
74  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
75  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
76  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
77  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
78  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
79  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
80  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
81  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
82  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
83  [redacted]                   0xa4de38 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 1699 (CalculateLayout.cpp:1699)
84  [redacted]                   0xa487b0 facebook::yoga::layoutAbsoluteChild(facebook::yoga::Node const*, facebook::yoga::Node const*, facebook::yoga::Node*, float, float, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 457 (AbsoluteLayout.cpp:457)
85  [redacted]                   0xa494ec facebook::yoga::layoutAbsoluteDescendants(facebook::yoga::Node*, facebook::yoga::Node*, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int, float, float, float, float) + 52 (Style.h:52)
86  [redacted]                   0xa4efe4 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 2099 (CalculateLayout.cpp:2099)
87  [redacted]                   0xa487b0 facebook::yoga::layoutAbsoluteChild(facebook::yoga::Node const*, facebook::yoga::Node const*, facebook::yoga::Node*, float, float, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 457 (AbsoluteLayout.cpp:457)
88  [redacted]                   0xa494ec facebook::yoga::layoutAbsoluteDescendants(facebook::yoga::Node*, facebook::yoga::Node*, facebook::yoga::SizingMode, facebook::yoga::Direction, facebook::yoga::LayoutData&, unsigned int, unsigned int, float, float, float, float) + 52 (Style.h:52)
89  [redacted]                   0xa4efe4 facebook::yoga::calculateLayoutInternal(facebook::yoga::Node*, float, float, facebook::yoga::Direction, facebook::yoga::SizingMode, facebook::yoga::SizingMode, float, float, bool, facebook::yoga::LayoutPassReason, facebook::yoga::LayoutData&, unsigned int, unsigned int) + 2099 (CalculateLayout.cpp:2099)
90  [redacted]                   0xa4f5f8 facebook::yoga::calculateLayout(facebook::yoga::Node*, float, float, facebook::yoga::Direction) + 2373 (CalculateLayout.cpp:2373)
91  [redacted]                   0x5c87f8 -[RCTShadowView layoutWithMinimumSize:maximumSize:layoutDirection:layoutContext:] + 280 (RCTShadowView.m:280)
92  [redacted]                   0x5bf5dc -[RCTRootShadowView layoutWithAffectedShadowViews:] + 39 (RCTRootShadowView.m:39)
93  [redacted]                   0x5d20b0 -[RCTUIManager uiBlockWithLayoutUpdateForRootView:] + 551 (RCTUIManager.m:551)
94  [redacted]                   0x527614 -[REASwizzledUIManager reanimated_uiBlockWithLayoutUpdateForRootView:] + 158 (REASwizzledUIManager.mm:158)
95  [redacted]                   0x5d54c8 -[RCTUIManager _layoutAndMount] + 1126 (RCTUIManager.m:1126)
96  [redacted]                   0x59e0e8 __32-[RCTCxxBridge batchDidComplete]_block_invoke + 1518 (RCTCxxBridge.mm:1518)
97  libdispatch.dylib              0x2248 _dispatch_call_block_and_release + 32
98  libdispatch.dylib              0x3fa8 _dispatch_client_callout + 20
99  libdispatch.dylib              0xb5cc _dispatch_lane_serial_drain + 768
100 libdispatch.dylib              0xc124 _dispatch_lane_invoke + 380
101 libdispatch.dylib              0x1738c _dispatch_root_queue_drain_deferred_wlh + 288
102 libdispatch.dylib              0x16bd8 _dispatch_workloop_worker_thread + 540
103 libsystem_pthread.dylib        0x3680 _pthread_wqthread + 288
104 libsystem_pthread.dylib        0x1474 start_wqthread + 8
        
```

**Comment by chrfalch** [comment]
Hi @fatlinesofcode - Could you provide some more info about the crash? Would it be possible to try to create a small reproducible example that we can test in production?

**Comment by mr-tm** [comment]
@chrfalch 
Having similar issue
![image](https://github.com/user-attachments/assets/7d056690-7832-4679-88d3-f3f927a82634)

Expo 52.0.18
This happens ever since I migrated from react-native CLI to EXPO. About 0.5% of users daily. I don't use expo-fonts anywhere in app. Not reproducible locally, happens randomly in production on app launch.

```
Crashed: com.facebook.react.ShadowQueue
0  App                          0x48c04 specialized static UIFont._expo_fontNames(forFamilyName:) + 6 (FontFamilyAliasManager.swift:6)
1  App                          0x48b0c @objc static UIFont._expo_fontNames(forFamilyName:) + 4367108876 (<compiler-generated>:4367108876)
2  App                          0x660b08 fontNamesForFamilyName(NSString*) + 175 (RCTFont.mm:175)
3  App                          0x660294 +[RCTFont updateFont:withFamily:size:weight:style:variant:scaleMultiplier:] + 472 (RCTFont.mm:472)
4  App                          0x54ba90 -[RCTTextAttributes effectiveFont] + 220 (RCTTextAttributes.mm:220)
5  App                          0x54b674 -[RCTTextAttributes effectiveTextAttributes] + 150 (RCTTextAttributes.mm:150)
6  App                          0x54786c -[RCTBaseTextShadowView attributedTextWithBaseTextAttributes:] + 101 (RCTBaseTextShadowView.mm:101)
7  App                          0x54d4ac -[RCTTextShadowView attributedTextWithMeasuredAttachmentsThatFitSize:] + 179 (RCTTextShadowView.mm:179)
8  App                          0x54d82c -[RCTTextShadowView textStorageAndLayoutManagerThatFitsSize:exclusiveOwnership:] + 227 (RCTTextShadowView.mm:227)
9  App                          0x54dc24 -[RCTTextShadowView layoutSubviewsWithContext:] + 265 (RCTTextShadowView.mm:265)
10 App                          0x6801f0 -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
11 App                          0x6801f0 -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
12 App                          0x6801f0 -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
13 App                          0x6801f0 -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
14 App                          0x6801f0 -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
15 App                          0x6801f0 -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
16 App                          0x6801f0 -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
17 App                          0x6801f0 -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
18 App                          0x6801f0 -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
19 App                          0x6801f0 -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
20 App                          0x67ff7c -[RCTShadowView layoutWithMinimumSize:maximumSize:layoutDirection:layoutContext:] + 294 (RCTShadowView.m:294)
21 App                          0x676cec -[RCTRootShadowView layoutWithAffectedShadowViews:] + 39 (RCTRootShadowView.m:39)
22 App                          0x5e1ad8 -[REASwizzledUIManager reanimated_uiBlockWithLayoutUpdateForRootView:] + 169 (REASwizzledUIManager.mm:169)
23 App                          0x68cbe4 -[RCTUIManager _layoutAndMount] + 1126 (RCTUIManager.m:1126)
24 App                          0x65650c __32-[RCTCxxBridge batchDidComplete]_block_invoke + 1518 (RCTCxxBridge.mm:1518)
25 libdispatch.dylib              0x2370 _dispatch_call_block_and_release + 32
26 libdispatch.dylib              0x40d0 _dispatch_client_callout + 20
27 libdispatch.dylib              0xb6d8 _dispatch_lane_serial_drain + 744
28 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 380
29 libdispatch.dylib              0x17258 _dispatch_root_queue_drain_deferred_wlh + 288
30 libdispatch.dylib              0x16aa4 _dispatch_workloop_worker_thread + 540
31 libsystem_pthread.dylib        0x4c7c _pthread_wqthread + 288
32 libsystem_pthread.dylib        0x1488 start_wqthread + 8
```

**Comment by chrfalch** [comment]
> @chrfalch Having similar issue 

The fix has not been released yet - it should hopefully be resolved here: #31563

**Comment by mr-tm** [comment]
@chrfalch Unfortunately, after updating the app to include the fix in #31563, the issue still remains.
This crash event happens in the first second of the user's session. Log:
```
Crashed: expo.fontfamilyaliasmanager
0  App                          0x4c65c closure #1 in static FontFamilyAliasManager.familyName(forAlias:) + 6 (FontFamilyAliasManager.swift:6)
1  App                          0x4d264 partial apply for closure #1 in static FontFamilyAliasManager.familyName(forAlias:) + 4377268836 (<compiler-generated>:4377268836)
2  libswiftDispatch.dylib         0x2dd4 partial apply for thunk for @callee_guaranteed () -> (@out A, @error @owned Error) + 28
3  libswiftDispatch.dylib         0x2db0 thunk for @callee_guaranteed () -> (@out A, @error @owned Error)partial apply + 16
4  libswiftDispatch.dylib         0x2d18 closure #1 in closure #1 in OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 192
5  libswiftDispatch.dylib         0x2c3c partial apply for thunk for @callee_guaranteed () -> () + 28
6  libswiftDispatch.dylib         0x2c14 thunk for @escaping @callee_guaranteed () -> () + 28
7  libdispatch.dylib              0x3fa8 _dispatch_client_callout + 20
8  libdispatch.dylib              0x13e2c _dispatch_sync_invoke_and_complete + 56
9  libswiftDispatch.dylib         0x46b0 implicit closure #2 in implicit closure #1 in OS_dispatch_queue.asyncAndWait<A>(execute:) + 192
10 libswiftDispatch.dylib         0x45e8 partial apply for implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 76
11 libswiftDispatch.dylib         0x4468 OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 404
12 libswiftDispatch.dylib         0x42a4 OS_dispatch_queue.asyncAndWait<A>(execute:) + 140
13 libswiftDispatch.dylib         0x4210 OS_dispatch_queue.sync<A>(execute:) + 64
14 App                          0x4f050 specialized static UIFont._expo_fontNames(forFamilyName:) + 46 (FontFamilyAliasManager.swift:46)
15 App                          0x4ef04 @objc static UIFont._expo_fontNames(forFamilyName:) + 4377276164 (<compiler-generated>:4377276164)
16 App                          0x654754 fontNamesForFamilyName(NSString*) + 174 (RCTFont.mm:174)
17 App                          0x654144 +[RCTFont updateFont:withFamily:size:weight:style:variant:scaleMultiplier:] + 471 (RCTFont.mm:471)
18 App                          0x573118 -[RCTTextAttributes effectiveFont] + 227 (RCTTextAttributes.mm:227)
19 App                          0x572d1c -[RCTTextAttributes effectiveTextAttributes] + 157 (RCTTextAttributes.mm:157)
20 App                          0x57054c -[RCTBaseTextShadowView attributedTextWithBaseTextAttributes:] + 101 (RCTBaseTextShadowView.mm:101)
21 App                          0x574b54 -[RCTTextShadowView attributedTextWithMeasuredAttachmentsThatFitSize:] + 179 (RCTTextShadowView.mm:179)
22 App                          0x574ed4 -[RCTTextShadowView textStorageAndLayoutManagerThatFitsSize:exclusiveOwnership:] + 227 (RCTTextShadowView.mm:227)
23 App                          0x5756ec -[RCTTextShadowView layoutSubviewsWithContext:] + 311 (RCTTextShadowView.mm:311)
24 App                          0x673e2c -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
25 App                          0x673e2c -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
26 App                          0x673e2c -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
27 App                          0x673e2c -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
28 App                          0x673e2c -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
29 App                          0x673e2c -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
30 App                          0x673e2c -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
31 App                          0x673e2c -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
32 App                          0x673e2c -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
33 App                          0x673e2c -[RCTShadowView layoutSubviewsWithContext:] + 332 (RCTShadowView.m:332)
34 App                          0x673bb8 -[RCTShadowView layoutWithMinimumSize:maximumSize:layoutDirection:layoutContext:] + 294 (RCTShadowView.m:294)
35 App                          0x66bc04 -[RCTRootShadowView layoutWithAffectedShadowViews:] + 39 (RCTRootShadowView.m:39)
36 App                          0x600bb8 -[REASwizzledUIManager reanimated_uiBlockWithLayoutUpdateForRootView:] + 169 (REASwizzledUIManager.mm:169)
37 App                          0x680460 -[RCTUIManager _layoutAndMount] + 1126 (RCTUIManager.m:1126)
38 App                          0x64ac38 __32-[RCTCxxBridge batchDidComplete]_block_invoke + 1540 (RCTCxxBridge.mm:1540)
39 libdispatch.dylib              0x2248 _dispatch_call_block_and_release + 32
40 libdispatch.dylib              0x3fa8 _dispatch_client_callout + 20
41 libdispatch.dylib              0xb5cc _dispatch_lane_serial_drain + 768
42 libdispatch.dylib              0xc124 _dispatch_lane_invoke + 380
43 libdispatch.dylib              0x1738c _dispatch_root_queue_drain_deferred_wlh + 288
44 libdispatch.dylib              0x16bd8 _dispatch_workloop_worker_thread + 540
45 libsystem_pthread.dylib        0x3680 _pthread_wqthread + 288
46 libsystem_pthread.dylib        0x1474 start_wqthread + 8
        
```

**Comment by mr-tm** [comment]
@chrfalch The crashes seems to have mostly fixed when switched from react-native-vector-icons to expo/vector-icons and using expo-font plugin:
```
[
        "expo-font",
        {
          "fonts": [
            "../../node_modules/react-native-vector-icons/Fonts/MaterialCommunityIcons.ttf"
          ]
        }
]
```
