### ISSUE TITLE
iOS App store build fails with the following error - [redundant conformance of 'CAGradientLayerType' to protocol 'CaseIterable']

### ISSUE THREAD

**Issue by himanshu1721** [expo/expo#33994]
### Build/Submit details page URL

https://expo.dev/accounts/himanshu721/projects/andernApp/builds/486978ae-c25f-4231-8ef9-93babe31ab2c

### Summary

The expected behaviour is the build gets created as it did when i first created it here - (https://expo.dev/accounts/himanshu721/projects/andernApp/builds/2722933f-e9c9-42f5-805c-fcfdfe8bdf87)

<img width="843" alt="Screenshot 2025-01-01 at 1 56 28 PM" src="https://github.com/user-attachments/assets/765662d6-a906-4235-976f-368d7bcaa69f" />
<img width="766" alt="Screenshot 2025-01-01 at 1 55 47 PM" src="https://github.com/user-attachments/assets/e4ce7834-970c-4777-a44b-de8d810c8c8e" />

Nothing has changed, as the commits are the same; only the version number and iOS build number have been updated. This error appeared after I added some code related to Reanimated, which I believe was correct. After creating a build, I encountered the error I have shared below. I then performed a backtrack, and even when I built the same commit that was previously successful, the issue still persists.

![Group 15](https://github.com/user-attachments/assets/a8f73b4a-4b55-4a01-b85f-f6db69c97682)

### Managed or bare?

Bare.

### Environment

npx expo-env-info

  expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - /usr/local/bin/node
      npm: 9.6.7 - /usr/local/bin/npm
      Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12700392
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.39 => 51.0.39 
      expo-router: ~3.5.24 => 3.5.24 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: bare

-----------------------------------------------------

npx expo-doctor
Didn't find any issues with the project!

### Reproducible demo or steps to reproduce from a blank project

The issue lies when running the following command in my project. Not sure if I will be able to provide a reproducible demo without sharing the entire project.

> eas build --platform ios

**Comment by brentvatne** [comment]
@jhmesseroux - https://github.com/dominicstop/react-native-ios-utilities/issues/14#issuecomment-2567200196

**Comment by brentvatne** [comment]
i closed this because it isn't related to anything that we work on at expo, it is an issue from react-native-ios-utilities, and it has been fixed, see that repo for more information on how to update it to get the fix

**Comment by Aycom366** [comment]
I'm still having this issue, updating to those packages didn't work, the building is still failing
I'm on expo 50

**Comment by janziemba** [comment]
It has been fixed in the react-native-ios-utilities v4.5.2: https://github.com/dominicstop/react-native-ios-utilities/issues/14#issuecomment-2567200196
