### ISSUE TITLE
[expo-router] Web URL Changes to Alphabetically First Route on Refresh in Expo Router

### ISSUE THREAD

**Issue by daeuk1011** [expo/expo#34345]
### Minimal reproducible example

https://github.com/daeuk1011/expo-router-web-url-changed-bug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

When refreshing a page in a web application using Expo Router, the current URL unexpectedly changes. Specifically, it appears to default to the first route listed alphabetically in the sitemap, regardless of the intended behavior.

This issue occurs only in production builds, such as:

After running npx expo export -p web -c

1. When serving the build locally using npx serve dist.
2. When deploying the build to AWS Amplify.

https://github.com/user-attachments/assets/96953394-415b-43da-97c6-f85314261a44

<img width="771" alt="Image" src="https://github.com/user-attachments/assets/0e421e0a-dccc-4925-8430-c6671a991a4b" />

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.4.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.9.2 - /opt/homebrew/bin/npm
      Watchman: 2024.07.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/kimdaeuk/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.26 => 52.0.27 
      expo-router: ~4.0.17 => 4.0.17
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.6 => 0.76.6 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 14.2.0
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
I believe this should be fixed by https://github.com/expo/expo/pull/34668 which will be released soon in `4.1`

**Comment by emidaniele** [comment]
> I believe this should be fixed by [#34668](https://github.com/expo/expo/pull/34668) which will be released soon in `4.1`

Hi @marklawlor! Do you know if there will be a `4.1.0` version coming out soon with this fix? Or was the fix released already? I'm on `4.0.20` and this is still happening on my end. Thanks!

**Comment by JeanDes-Code** [comment]
I’ve been running into this issue too and spent a good while scratching my head before realizing it was because `expo-router` defaults to the first route in alphabetical order.

This behavior is really throwing off our analytics. It makes it look like users are landing on pages they never actually navigated to, which breaks our funnels and makes feature usage harder to track accurately.

We’re not ready to upgrade to SDK 53 yet, so we’re really hoping this will be addressed in `4.1.0` (releasing soon, hopefully?).

Thanks for your work on this. It would make a big difference on our end.

**Comment by c0rnonthec0bb** [comment]
Using `5.1.0` and this still appears to be an issue. URL defaults to the alphabetically first route, even though the page itself is rendering what would otherwise be the correct UI

**Comment by riamon-v** [comment]
Using `5.1.3` here with a (tabs) navigator and i'm still having the issue too. I tried to explicitly set the name screen into the _layout but it changes nothing, any news on that ?

**Comment by kitten** [comment]
As @marklawlor said, this was resolved. However, this can also occur when there's no `/index` route (including groups) or when there's overlapping `/index` routes (including groups) as groups don't contribute to the route name.

As such, this issue is now ambiguous, but the original issue was resolved. Closing since it'd be unclear now whether this is resolved and the original poster hasn't validated the fix, making this a stale issue.

Happy to accept questions or new issues re. this. To clarify, if you're seeing this please check whether you have overlapping routes (e.g. `/(a)/index` and `/(b)/index`
