### ISSUE TITLE
[expo-google-sign-in][android][standalone] GoogleSignIn.signInAsync: DEVELOPER_ERROR

### ISSUE THREAD

**Issue by serhiipalash** [expo/expo#3439]
### Environment

| software         | version
| ---------------- | -------
| expo | 32.0.0
| react-native     | https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
| device    | Samsung Galaxy A8

`exp diagnostics` output

<img width="958" alt="screen shot 2019-02-06 at 6 50 57 pm" src="https://user-images.githubusercontent.com/14208343/52358173-36f7e500-2a40-11e9-811a-bc895100c70d.png">

### Steps to Reproduce

We built Google sign in flow based on @EvanBacon article https://blog.expo.io/react-native-google-sign-in-with-expo-d1707579a7ce and his example repository https://github.com/EvanBacon/expo-google-sign-in-demo and everything worked fine both on Android and iOS 3 weeks ago right after Expo v32 was released, but now it only works on iOS and on Android the code fails on this line 
```
const googleSignInResponse = await GoogleSignIn.signInAsync()
```
with error message `GoogleSignIn.signInAsync: DEVELOPER_ERROR`.

### Expected Behavior

`GoogleSignIn.signInAsync` should work on both platforms.

### Actual Behavior

On Android `GoogleSignIn.signInAsync` fails

### Reproducible Demo

Sorry, no demo. 
You can install this build on your Android device and try to login with Google
https://expo.io/builds/995e99a3-a5a2-4d7b-95bb-b322b5cc1bd5

**Comment by serhiipalash** [comment]
@EvanBacon do you have any idea what could go wrong? All I did during last 3 weeks is created an Android app in our production project Firebase Console with the same name as it was in staging.

I googled this error and tried all possible solutions, but nothing helped.
https://github.com/react-native-community/react-native-google-signin/issues/246
https://developer.android.com/studio/publish/app-signing#expdebug
https://stackoverflow.com/questions/37421518/statuscode-developer-error-in-google-login

**Comment by Samesh** [comment]
Hi @serhiipalash try taking the certificateHash key from android.config.certificateHash and adding it into your firebase configuration as the SHA 1 key mentioned here https://stackoverflow.com/questions/37273145/error-statusstatuscode-developer-error-resolution-null/39061410#39061410

It worked out for me, it might be the case.

**Comment by serhiipalash** [comment]
Hi @Samesh ! Do you have a app detached?

**Comment by serhiipalash** [comment]
@Samesh also I don't have `android.config.certificateHash` in my `app.json`. How did you generate it? Like this `keytool -list -printcert -jarfile myApk.apk`?

**Comment by Samesh** [comment]
Hi @serhiipilash, the certificate has was not required.
I managed to fix it by taking the Sha 1 key created by google play console (have app signing turned on) and adding it into your firebase configuration as the SHA 1 key mentioned here https://stackoverflow.com/questions/37273145/error-statusstatuscode-developer-error-resolution-null/39061410#39061410

**Comment by serhiipalash** [comment]
The problem is fixed. 

1. Get Android hashes from Expo
```
expo fetch:android:hashes
```
2. Copy `Google Certificate Fingerprint` and save it in your `app.json` under
```
{
    "expo": {
        "android": {
            "config": {
                "googleSignIn": {
                    "certificateHash": "<Google Certificate Fingerprint>"
                }
            }
        }
    }
}
```
3. Add the same Fingerprint in your Android app settings in Firebase console

ping @Samesh, @EvanBacon

**Comment by ohpax** [comment]
I still have this issue, my app is detached and I upgraded it from expo 31 to 32 and tried everything said in here but I had no success.

**Comment by serhiipalash** [comment]
Hi @ohpax !
As I know, detached apps are built not on Expo server, but on your local machine. And this command applies settings to Expo server
```
expo fetch:android:hashes
```
I think you should find out what it does in details and do the same for your local Turtle CLI instance, if you build your app with it, or for Android Studio utils, that you use.

**Comment by faria** [comment]
Hi @serhiipalash, in your app.json, do you still have the "googleServicesFile" key in the android object?  Are we supposed to add the config object in addition to the googleServicesFile?  
Some infos: My app is managed by expo - I run expo build:android to generate the APK.

**Comment by serhiipalash** [comment]
Hi @faria !
Yes, you need to add both. Our app.json looks like this
```
{
  "expo": {
    ...
    "ios": {
      ...
      "config": {
        "googleSignIn": {
          "reservedClientId": "<REVERSED_CLIENT_ID field from GoogleService-Info.plist file>"
        }
      }
    },
    "android": {
      ...
      "googleServicesFile": "./google-services.json",
      "config": {
        "googleSignIn": {
          "certificateHash": "<your_certificate_hash>"
        }
      }
    }
  }
}
```

**Comment by jineous27** [comment]
How I fixed the problem in my situation after uploading the app to the app store:

 1) Downloaded Dérive app from google console.
2) Run below command in command prompt.
`keytool -list -printcert -jarfile <FILE_NAME>.apk`
3) check for "SHA1" and copy

4) Goto firebase android app settings and click on "Add fingerprint" and paste SHA1 from the above step.

**Comment by raikk** [comment]
@jineous27 thanks

i had this issue in debug app

`{"framesToPop":1,"nativeStackAndroid":[],"userInfo":null,"code":"10","line":2720,"column":26,"sourceURL":"http://192.168.43.162:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false"}`

**SOLUTION:-**

my debug key was mismatch, In firebase i was putting wrong debug SH1 using this command.

`keytool -exportcert -list -v -alias androiddebugkey -keystore ~/.android/debug.keystore`

When i switch to android/app/build/outputs/apk/release/app-debug.apk and used this command

`keytool -list -printcert -jarfile app-debug.apk`

then i used generated SH1 in firebase, then it fixed my problem.
