### ISSUE TITLE
expo-image Image.loadAsync doesn't send HTTP headers

### ISSUE THREAD

**Issue by AnzeBlaBla** [expo/expo#34723]
### Minimal reproducible example

https://github.com/AnzeBlaBla/expo-image-bug-reproducible

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build

### Summary

When using `useImage`, or (what it internally uses) `Image.loadAsync` from the new 'expo-image' module, it doesn't send headers along with the request for the image, if the source is specified in the format:
```js
Image.loadAsync({
  uri: "URL_HERE",
  headers: {
    Authorization:
      "Bearer ...",
  },
});
```

It works if the headers are passed directly to the `Image` component, though.

See reproducible for a specific example that's easily testable.

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: Windows 11 10.0.26100
    Binaries:
      Node: 20.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 11.1.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 32, 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0
        System Images: android-35 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: AI-212.5712.43.2112.8815526
    npmPackages:
      expo: ^52.0.0 => 52.0.29
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.6 => 0.76.6
      react-native-web: ~0.19.6 => 0.19.13
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for issues with Metro config
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✖ Validate packages against React Native Directory package metadata
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
Untested on New Architecture: react-native-nfc-manager
Unmaintained: expo-video-player
No metadata available: @anzeblabla/react-native-markdown-editor, @expo/config-plugins, @expo/prebuild-config, @openspacelabs/react-native-zoomable-view, base-64, he, mime, punycode, react-native-multi-selectbox, react-navigation, typescript
Advice:
- Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.        
- Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.     
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

The following packages should be updated for best compatibility with the installed expo version:
  expo@52.0.29 - expected version: ~52.0.30
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```

**Comment by czipi** [comment]
Experiencing the same issue

**Comment by AnzeBlaBla** [comment]
@czipi Update the library, it is fixed now.

**Comment by czipi** [comment]
@AnzeBlaBla I did, but using your example (what i updated to 2.0.6) I can still reproduce it. Headers gets sent only if passed directly to the Image component.

**Comment by AnzeBlaBla** [comment]
@czipi Yes, this issue was only on Android.

I currently don't have the testing environment at hand, but I can for sure say that 2.0.6 fixed this in our app. Is there maybe some kind of issue with package caching on your local machine? Check if the code that was changed in this version is actually inside `node_modules`, that's the only thing I can think of.
