### ISSUE TITLE
DOM Components Not Working in Production

### ISSUE THREAD

**Issue by rishabhjain-dp** [expo/expo#35443]
### Summary

When using "use dom" components in Expo (expo@50+), they work fine in development mode but fail to render in production builds when using npx expo export --platform android. The issue seems related to Metro's bundling process, which does not properly bundle web-based dependencies like highcharts-react-official.

✅ Works in: npx expo start (development mode)
❌ Fails in: npx expo start --dev-client --no-dev --minify (production mode)

we are using highcharts to render charts in dom components:

`'use dom';
import { useEffect, useState } from 'react';
import HighchartsReact from 'highcharts-react-official';
import Highcharts from 'highcharts';

export default function ChartComponent() {
  const [options, setOptions] = useState(null);

  useEffect(() => {
    setOptions({
      chart: { type: 'pie' },
      title: { text: 'My Pie Chart' },
      series: [{ name: 'Share', data: [{ name: 'Apples', y: 40 }, { name: 'Bananas', y: 30 }, { name: 'Oranges', y: 30 }] }]
    });
  }, []);

  return options ? <HighchartsReact highcharts={Highcharts} options={options} /> : null;
}
`

the webview implementation works but use dom doesnt

`import { WebView } from 'react-native-webview';

const htmlContent = `
  <html>
    <head><script src="https://code.highcharts.com/highcharts.js"></script></head>
    <body><div id="container"></div>
      <script>
        Highcharts.chart('container', {
          chart: { type: 'pie' },
          title: { text: 'My Pie Chart' },
          series: [{ name: 'Share', data: [{ name: 'Apples', y: 40 }, { name: 'Bananas', y: 30 }, { name: 'Oranges', y: 30 }] }]
        });
      </script>
    </body>
  </html>
`;

return <WebView source={{ html: htmlContent }} style={{ flex: 1 }} />;
`

The bundle doesn't have the html and js files required for the charts to run in android and ios.

### What platform(s) does this occur on?

Android, iOS

### SDK Version

52.0.33

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.12.0 - ~/.nvm/versions/node/v22.12.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v22.12.0/bin/yarn
      npm: 11.0.0 - ~/.nvm/versions/node/v22.12.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: 52.0.33 => 52.0.33 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.7 => 0.76.7 
      react-native-web: 0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 15.0.14
    Expo Workflow: bare
```

### Minimal reproducible example

npx create-expo-app my-app
cd my-app
npx expo install @expo/metro-runtime react-dom react-native-web
npm install highcharts highcharts-react-official

create the chart component and run using npx expo start --dev-client --no-dev --minify

**Comment by brentvatne** [comment]
hi there! please update to the latest expo version. `npx expo install --fix`

we've fixed a few issues with DOM components that are likely related

**Comment by rishabhjain-dp** [comment]
Still getting same error on the latest version of expo.

<img width="427" alt="Image" src="https://github.com/user-attachments/assets/affa0801-f4bf-4610-871f-3352a18c7e8c" />

**Comment by brentvatne** [comment]
@rishabhjain-dp - sorry to hear that! if you create a new issue with a minimal reproducible example then someone can certainly help!
