### ISSUE TITLE
Background Task never Executing

### ISSUE THREAD

**Issue by nickreynolds** [expo/expo#36492]
### Minimal reproducible example

https://github.com/nickreynolds/expo-background-test

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

I'm following the instructions from here: https://docs.expo.dev/versions/latest/sdk/background-task/

the code looks like this: 

```
import * as BackgroundTask from 'expo-background-task';
import * as TaskManager from 'expo-task-manager';

const BACKGROUND_TASK_IDENTIFIER = 'background-task';

// Register and create the task so that it is available also when the background task screen
// (a React component defined later in this example) is not visible.
// Note: This needs to be called in the global scope, not in a React component.
TaskManager.defineTask(BACKGROUND_TASK_IDENTIFIER, async () => {
  try {
    const now = Date.now();
    console.log(`Got background task call at date: ${new Date(now).toISOString()}`);
  } catch (error) {
    console.error('Failed to execute the background task:', error);
    return BackgroundTask.BackgroundTaskResult.Failed;
  }
  return BackgroundTask.BackgroundTaskResult.Success;
});

// 2. Register the task at some point in your app by providing the same name
// Note: This does NOT need to be in the global scope and CAN be used in your React components!
async function registerBackgroundTaskAsync() {
  console.log('registerBackgroundTaskAsync');
  return BackgroundTask.registerTaskAsync(BACKGROUND_TASK_IDENTIFIER, {
    minimumInterval: 15,
  });
}

export default function RootLayout() {
  const colorScheme = useColorScheme();
  const [loaded] = useFonts({
    SpaceMono: require('../assets/fonts/SpaceMono-Regular.ttf'),
  });

  useEffect(() => {
    registerBackgroundTaskAsync();
  }, []);
```

When I run the app with `npx expo run:android`, I see the log for *registering* the background task, but after waiting 20+ minutes, I never see the log for the task being executed.

There are 2 errors found when running expo-doctor, but this is a brand new project creating with `create-expo-app` and then following the instructions on the expo-background-task page.

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 15.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.1 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.8.2 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2024.2 AI-242.23726.103.2422.12816248
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.46 => 52.0.46 
      expo-router: ~4.0.20 => 4.0.20 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.9 => 0.76.9 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
13/15 checks passed. 2 checks failed. Possible issues detected:
Use the --verbose flag to see more details about passed checks.

✖ Check for app config fields that may not be synced in a non-CNG project
This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, scheme, userInterfaceStyle, ios, android, plugins, androidStatusBar. 


✖ Validate packages against React Native Directory package metadata
The following issues were found when validating your dependencies against React Native Directory:
  No metadata available: expo-background-task
Advice:
Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

2 checks failed, indicating possible issues with the project.
```

**Comment by ogtfaber** [comment]
Experiencing the same issue on iOS

**Comment by chrfalch** [comment]
Hi @nickreynolds, thanks for submitting the issue, we're super happy about getting feedback on Expo BackgroundTasks. It is important that you put the app in the background for the app to run the task in the background, on iOS a task can be delayed until the next time your device is put to sleep in the background - could any of these things be the cause of the issues you are seeing?

**Comment by nickreynolds** [comment]
@chrfalch I'm putting the app into the background. On android simulator, I'm swiping up to background the app and staring at the homescreen. I'm not testing on iOS.

**Comment by chrfalch** [comment]
Hi, could you test to not swipe the app out? (read more [here](https://docs.expo.dev/versions/latest/sdk/background-task/#when-will-they-be-stopped) about why this might not be the correct thing to do)- just press the home button and see if it helps.

**Comment by nickreynolds** [comment]
@chrfalch I'm not swiping the app out of the list of running apps (and thus closing it), I'm just swiping up from the bottom of the screen while the app is running to return to the homescreen. The app is still in the list of running apps if I check that. Most android phones don't have home buttons, as gesture navigation is the default. But swiping up should be the same behavior as hitting the home button.

**Comment by chrfalch** [comment]
👍 Just wanted to check the obvious candidates first :) I'm doing some research on this now and will get back!

**Comment by Morenosebas** [comment]
I have the same issue; the tasks are defined and registered, but they never run, not even with the development trigger.

![Image](https://github.com/user-attachments/assets/b8aa1354-7349-4481-b446-02168bdc37cf)

```ts
import * as TaskManager from "expo-task-manager";
import * as BackgroundTask from "expo-background-task";
import ReportQueue from "../Realm/projects_reports/reportQueue";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { getLocation } from "../Location/Location";
import { LocationReportService } from "../Realm/locationReports/locationQueue";
import Battery from "expo-battery";

const BACKGROUND_SYNC_REPORTS = "background-sync-reports";
const BACKGROUND_SYNC_LOCATION = "background-sync-locations";
const BACKGROUND_TEST_LOG = "background-test-log";

TaskManager.defineTask(BACKGROUND_TEST_LOG, async () => {
  console.log("test");
  return BackgroundTask.BackgroundTaskResult.Success;
});

TaskManager.defineTask(BACKGROUND_SYNC_REPORTS, async () => {
  try {
    await ReportQueue.getInstance().runQueueProcessing();
    return BackgroundTask.BackgroundTaskResult.Success;
  } catch (error) {
    return BackgroundTask.BackgroundTaskResult.Failed;
  }
});

TaskManager.defineTask(BACKGROUND_SYNC_LOCATION, async () => {
  try {
    console.log("Subiendo localizacion 1");
    console.log("Subiendo localizacion 2");

    const userId = await AsyncStorage.getItem("userId");
    if (!userId) {
      console.warn("No hay userId en AsyncStorage, salto ubicación");
      return BackgroundTask.BackgroundTaskResult.Failed;
    }

    const loc = await getLocation();
    if (!loc) {
      return BackgroundTask.BackgroundTaskResult.Failed;
    }

    const batteryLevel = await Battery.getBatteryLevelAsync();

    const service = await LocationReportService.getInstance();
    await service.enqueue({
      userId,
      timestamp: loc.timestamp,
      lat: loc.coords.latitude,
      lon: loc.coords.longitude,
      battery: batteryLevel,
      accuracy: loc.coords.accuracy,
    });

    await service.syncReports();
    console.log("Subiendo localizacion 3");

    return BackgroundTask.BackgroundTaskResult.Success;
  } catch (error) {
    console.error("Error en Tarea_testing:", error);
    return BackgroundTask.BackgroundTaskResult.Failed;
  }
});

async function registerBackgroundSyncTask() {
  try {
    console.log("Registrando tareas", await TaskManager.getRegisteredTasksAsync());

    if (!(await TaskManager.isTaskRegisteredAsync(BACKGROUND_TEST_LOG))) {
      console.log("Registering background test log task");
      await BackgroundTask.registerTaskAsync(BACKGROUND_TEST_LOG, {
        minimumInterval: 60,
      });
    }

    if (!(await TaskManager.isTaskRegisteredAsync(BACKGROUND_SYNC_REPORTS))) {
      console.log("Registering background sync reports task");
      await BackgroundTask.registerTaskAsync(BACKGROUND_SYNC_REPORTS, {
        minimumInterval: 15 * 60,
      });
    }

    if (!(await TaskManager.isTaskRegisteredAsync(BACKGROUND_SYNC_LOCATION))) {
      console.log("Registering background sync location task");
      await BackgroundTask.registerTaskAsync(BACKGROUND_SYNC_LOCATION, {
        minimumInterval: 15 * 60,
      });
    }

    console.log("Tareas registradas");
  } catch (error) {
    console.error("Error al registrar la tarea:", error);
  }
}

registerBackgroundSyncTask();

**Comment by Benisy** [comment]
I have the same problem on Android. The background task is registered and even launched using the command:

`adb shell cmd jobscheduler run -f <package-name> <JOB_ID>`

but it does not execute. I have LogCat open in Android Studio during testing, and in theory I would expect to see “Run task!”, but it's not there. 

I defined the task in app/_layout.tsx (simplified):
```tsx
import { Platform } from "react-native";
import * as BackgroundTask from "expo-background-task";
import * as TaskManager from "expo-task-manager";
import * as Notifications from "expo-notifications";
import { scheduleTodayReminders, updateDailyRemindersTask } from '@/tasks/dailyReminders';
import { AppFlowProvider } from "@/context/AppFlowContext";
import { ThemeProviderCustom } from "@/context/ThemeContext";
import { ThemeProvider } from "@react-navigation/native";
import { TASK_NAME } from "@/constants/Tasks";
import { router, Stack } from "expo-router";

TaskManager.defineTask(TASK_NAME, async () => {
  console.log("Run task!");
  try {
    await scheduleTodayReminders();
  } catch (error) {
    return BackgroundTask.BackgroundTaskResult.Failed;
  }
  return BackgroundTask.BackgroundTaskResult.Success;
});

function useNotificationObserver() {
  // Basic handle
}

export default function RootLayoutWrapper() {
  if (Platform.OS !== "web") {
    useNotificationObserver();
    updateDailyRemindersTask(); // <--- Updating task registration
  }

  return (
    <AppFlowProvider>
      <ThemeProviderCustom>
        <InnerLayout />
      </ThemeProviderCustom>
    </AppFlowProvider>
  );
}

function InnerLayout() {
  return (
    <ThemeProvider>
      <Stack>
        <Stack.Screen name="(tab)" options={{ headerShown: false }} />
        <Stack.Screen name="+not-found" />
      </Stack>
    </ThemeProvider>
  );
}
```

Register task: tasks\dailyReminders.ts
```ts
export async function updateDailyRemindersTask() {
  await unregisterDailyRemindersTask();
  await registerDailyRemindersTask();
}

export async function registerDailyRemindersTask() {
  const isRegistered = await TaskManager.isTaskRegisteredAsync(TASK_NAME);
  if (!isRegistered) {
    await BackgroundTask.registerTaskAsync(TASK_NAME, {
      minimumInterval: 60 * 12,
    });
  }
}
export async function unregisterDailyRemindersTask() {
  const isRegistered = await TaskManager.isTaskRegisteredAsync(TASK_NAME);
  if (isRegistered) {
    await BackgroundTask.unregisterTaskAsync(TASK_NAME);
  }
}

```

<details>
  <summary>Environment</summary>

  ```
  expo-env-info 1.3.3 environment info:
    System:
      OS: Windows 11 10.0.26100
    Binaries:
      Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
      npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-243.25659.59.2432.13423653
    npmPackages:
      expo: 53.0.10 => 53.0.10
      expo-router: ~5.0.6 => 5.0.7
      react: 19.0.0 => 19.0.0
      react-dom: 19.0.0 => 19.0.0
      react-native: ^0.79.3 => 0.79.3
      react-native-web: ~0.20.0 => 0.20.0
    Expo Workflow: bare
  ```
</details>

**Comment by alxpez** [comment]
Are there any updates on this issue?

I just moved from using [`BackgroundFetch`](https://docs.expo.dev/versions/latest/sdk/background-fetch/) after seeing the deprecation message in the docs, which encourages a migration with certain degree of urgency; one would expect the new solution to be actually working, however `BackgroundTask`s only register but never trigger, which makes this kinda pointless.

**Comment by chrfalch** [comment]
Hi, sorry for the delay in answering - I understand the frustration! We've made som simplifications in SDK-53 that helps a bit and are also working on building better tools for testing background tasks. If you have the option to upgrade to SDK-53 - please do that.

**Comment by Minori-ty** [comment]
> Hi, sorry for the delay in answering - I understand the frustration! We've made som simplifications in SDK-53 that helps a bit and are also working on building better tools for testing background tasks. If you have the option to upgrade to SDK-53 - please do that.

It works, but instead of running tasks on a scheduled basis, the running time is uncertain. And when the app is closed, the scheduled tasks will not run anymore, even though I have allowed auto-start and disabled the battery-saving strategy.

**Comment by chrfalch** [comment]
A nice [video](https://www.youtube.com/watch?v=4lFus7TvayI) about background tasks was just recently released by @betomoedano - maybe it can shed some light on this.

**Comment by chrfalch** [comment]
> It works, but instead of running tasks on a scheduled basis, the running time is uncertain. And when the app is closed, the scheduled tasks will not run anymore, even though I have allowed auto-start and disabled the battery-saving strategy.

Yes, that is an important part of background tasks - the system decides when to run the tasks to ensure maximum battery life and resource usage, it often batches background tasks from different apps. This is part of how the system is designed.

**Comment by chrfalch** [comment]
I'll close the issue for now, but feel free to comment if you need - I'll be watching this space :)

**Comment by Minori-ty** [comment]
> > It works, but instead of running tasks on a scheduled basis, the running time is uncertain. And when the app is closed, the scheduled tasks will not run anymore, even though I have allowed auto-start and disabled the battery-saving strategy.
> 
> Yes, that is an important part of background tasks - the system decides when to run the tasks to ensure maximum battery life and resource usage, it often batches background tasks from different apps. This is part of how the system is designed.

Thank you for your reply. I will watch it carefully.

**Comment by santiagogarzon** [comment]
@chrfalch I'm facing the same issue with both OS. Task are registered and they get triggered. But they got stuck in any async action(not able to make any fetch), until the app is in active state again.

Am I expecting something odd? or is this expected?. Thanks in advance.

**Comment by cezapig** [comment]
Its not working for me after upgrade

🚀 Version Upgrades:
Expo SDK: 52.x → 53.0.22 (latest)
React: 18.3.1 → 19.0.0 (latest)
React DOM: 18.3.1 → 19.0.0 (latest)
React Native: 0.76.9 → 0.79.5 (latest compatible)
TypeScript Types: Updated to React 19
react-test-renderer: Updated to 19.0.0

 LOG  [{"options": {"minimumInterval": 15}, "taskName": "fetch-quote-task", "taskType": "expo-background-task"}]
 LOG  Resolver called
 LOG  Calling triggerTaskWorkerForTestingAsync
 LOG  null
 LOG  Background task triggered for testing

**Comment by yelnyafacee** [comment]
> Its not working for me after upgrade
> 
> 🚀 Version Upgrades: Expo SDK: 52.x → 53.0.22 (latest) React: 18.3.1 → 19.0.0 (latest) React DOM: 18.3.1 → 19.0.0 (latest) React Native: 0.76.9 → 0.79.5 (latest compatible) TypeScript Types: Updated to React 19 react-test-renderer: Updated to 19.0.0
> 
> LOG [{"options": {"minimumInterval": 15}, "taskName": "fetch-quote-task", "taskType": "expo-background-task"}] LOG Resolver called LOG Calling triggerTaskWorkerForTestingAsync LOG null LOG Background task triggered for testing

hi, did you managed to fix this?

**Comment by cezapig** [comment]
No, I couldn’t fix it. After upgrading to Expo SDK 53 and React 19 it just
stopped working — the background task registers, but it doesn’t execute
anymore.

Em qua., 3 de set. de 2025 às 04:39, yeln ***@***.***>
escreveu:

**Comment by vanstinator** [comment]
Seeing similar behavior where as soon as you `await fetch` (or await something that eventually calls `fetch`) the task hangs and nothing happens until the app is foregrounded again. But if I use `axios` network requests work as expected. It's weird and I haven't been able to get to the bottom of what is going on yet.

**Comment by chrfalch** [comment]
We've pushed a new version (1.0.8) that implements a fix on iOS for a timing issue with the registration of the task handler - see if this will help.

**Comment by moorea** [comment]
> Seeing similar behavior where as soon as you `await fetch` (or await something that eventually calls `fetch`) the task hangs and nothing happens until the app is foregrounded again. But if I use `axios` network requests work as expected. It's weird and I haven't been able to get to the bottom of what is going on yet.

Just chiming in to say that I also experienced a similar issue. Background Task would execute but would hang trying to `await fetch`

Switching to `axios` for that http call was a valid workaround for me.

**Comment by nickreynolds** [comment]
can you reopen this issue? I am still having this issue even after upgrading to Expo 54 (another difficult upgrade fighting dependency issues that took hours just to see no improvement...)

the task registers, but never executes.

I am running an Android device in the simulator ("Medium Phone API 35") and viewing the logs in Android Studio. I see the log for the registering of the background task, and have waited over an hour and do not see the logs for the executing of the task.

**Comment by nickreynolds** [comment]
a small update: I am able to force the execution of the background task with `adb shell cmd jobscheduler run -f <package name> <jobId>` but I only know that because I see a log on the server (my task calls one of my endpoints). I see no logs on the client side (nothing in the expo terminal logs or in Logcat in android studio - even though I *do* see the logs for registering the task).

more worryingly though, I am only able to trigger the task one time (subsequent triggers have no effect). To trigger it again I need to restart the app. After triggering the task, nothing about the:

```
Enqueue time: -1m10s152ms
Run time: earliest=+13m49s841ms
```

changes at all. Is that expected? I would think that after running the task, the enqueue time would be reset

**Comment by RohovDmytro** [comment]
> I'll close the issue for now, but feel free to comment if you need - I'll be watching this space :)

So sorry, buy a nice YT vid with a tutorial from documentation does not really solve the persisting issue.

> We've pushed a new version (1.0.8) that implements a fix on iOS for a timing issue with the registration of the task handler - see if this will help.

Thanks for the fix, but it does not work in my case. I am running code from expo docs.

**Comment by Benjythebee** [comment]
Relevant for me too; `triggerTaskWorkerForTestingAsync` doesn't do anything on android

yet `adb shell cmd jobscheduler run -f <package-name> <JOB_ID>` works

**Comment by martin-ecatch** [comment]
Unfortunately the issue with tasks hanging on "fetch" still exists in SDK 54. Axios seems to work, but I can't switch to Axios, because I'm using PouchDB (which uses fetch internally).

**Comment by martin-ecatch** [comment]
I found a workaround for the "fetch" issue! You need to use fetch from expo explicitely, like this:
import { fetch } from 'expo/fetch';

Then it seems to work.

**Comment by ITSJORDAN-TFA** [comment]
Same here for both IOS and Android on 54. Even the sample on the BG task documentation doesn't work, the task registers but never executes. Also the function makes notes of the "debug mode" but we just build for development

**Comment by mariuskrass** [comment]
Is there any update on that? Unfortunately, I can't get the example from the documentation to work on either Android or iOS (simulator or device).

Follow-up: I also couldn't get https://github.com/betomoedano/daily-quotes-app to work.

**Comment by NPT1601** [comment]
> Seeing similar behavior where as soon as you `await fetch` (or await something that eventually calls `fetch`) the task hangs and nothing happens until the app is foregrounded again. But if I use `axios` network requests work as expected. It's weird and I haven't been able to get to the bottom of what is going on yet.

that happen to me to and it works idk why :"D

**Comment by Episodex** [comment]
I have the same problem on SDK 54 and I see this issue is closed. So? It means it just doesn't work and won't be fixed? Is there any other way to get something done in background periodically in Expo?

**Comment by arnabJ** [comment]
@chrfalch 

I am on latest SDK 55 but still face the same issue.
The Task is being registered but doesn't gets triggered.

I am using development builds and I have tried in both Emulator (`npm start && npm run android`) and Real Device (with Release APK).

I also face the same issue as https://github.com/expo/expo/issues/39978

I tried forcing the backgriund job using:
`f com.anonymous.backgroundtasktest 11`
And I got:
`Running job [FORCED]`
But nothing happened.

**Comment by xgiovio** [comment]
Same issue here, using BackgroundTask and Expo Router. I define the task in app/_layout.tsx and register it in app/(home)/index.tsx
Task is being registered correctly and, if i try to reregister it, expos says that the task already exists so until here is ok.
If i open the macos console with the iphone connected i can see this log after calling BackgroundTask.triggerTaskWorkerForTestingAsync()

```
Simulating launch for task with identifier com.expo.modules.backgroundtask.processing
Getting pending task requests
Simulating launch for task with identifier com.expo.modules.backgroundtask.processing
Getting pending task requests
Found pending activities: (
    "bgProcessing-com.expo.modules.backgroundtask.processing:CE8FBC"
)
cancelTaskRequestWithIdentifier: com.expo.modules.backgroundtask.processing
Running task: <BGProcessingTask: com.expo.modules.backgroundtask.processing>
Starting simulated task: <BGProcessingTask: com.expo.modules.backgroundtask.processing>
Marking simulated task complete: <private>
Found pending activities: (
    "bgProcessing-com.expo.modules.backgroundtask.processing:CE8FBC"
)
cancelTaskRequestWithIdentifier: com.expo.modules.backgroundtask.processing
Running task: <BGProcessingTask: com.expo.modules.backgroundtask.processing>
Starting simulated task: <BGProcessingTask: com.expo.modules.backgroundtask.processing>
Marking simulated task complete: <private>
```

Now if i try to simulate again the log is
```
Getting pending task requests
Found pending activities: (
)
No task request with identifier com.expo.modules.backgroundtask.processing has been scheduled
Simulating launch for task with identifier com.expo.modules.backgroundtask.processing
Getting pending task requests
Found pending activities: (
)
No task request with identifier com.expo.modules.backgroundtask.processing has been scheduled
```
It seems that on second simulation the tasks are not present anymore. If i kill the app and i restart it the tasks are again in the log but in both cases i don't see any real execution of the defined function.

Any update on this situation?

**Comment by mariuskrass** [comment]
@chrfalch, are there any plans to reopen this issue?
