### ISSUE TITLE
[SDK 53] EXPO_PUBLIC env var not being set

### ISSUE THREAD

**Issue by jpaas** [expo/expo#36503]
### Minimal reproducible example

https://github.com/jpaas/expo-53-beta-env-var-bug

### What platform(s) does this occur on?

Web

### Where did you reproduce the issue?

on web

### Summary

I am trying to use an env var EXPO_PUBLIC_TEST in my app, but it is not being set.
The example repo is a new expo 53.0.3 project.
If you run `EXPO_PUBLIC_TEST=my_value yarn start` you can see that it does not get set.

This has regressed in expo 53, because we were using it in 52 and prior.

Other observations:
- You can see briefly that it is set and then gets unset
- If you provide the value via .env it always works
- If you run `expo export` it works. So it seems to only be an issue for the dev server.
- If you examine the generated bundle you can see that it knows about the variable:
```
/* HMR env vars from Expo CLI (dev-only) */ process.env=Object.defineProperties(process.env, {"EXPO_PUBLIC_TEST": { value: "foo" },"EXPO_PUBLIC_PROJECT_ROOT": { value: "/Users/jpaas/Documents/karma/expo-53-beta" }});
```
However the value in the page is replaced as `_env2.env.EXPO_PUBLIC_TEST` which is undefined

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 15.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.12.0 - ~/.proto/shims/node
      Yarn: 4.7.0 - ~/.proto/shims/yarn
      npm: 10.9.0 - ~/.proto/shims/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.4, iOS 18.4, macOS 15.4, tvOS 18.4, visionOS 2.4, watchOS 11.4
      Android SDK:
        API Levels: 31, 33, 34, 35
        Build Tools: 34.0.0, 35.0.0
        System Images: android-21 | Google APIs ARM 64 v8a, android-24 | ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-35 | Google APIs ARM 64 v8a, android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.19072.14.2412.12360217
      Xcode: 16.3/16E140 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.3 => 53.0.3 
      expo-router: ~5.0.3 => 5.0.3 
      react: 19.0.0 => 19.0.0 
      react-dom: 19.0.0 => 19.0.0 
      react-native: 0.79.1 => 0.79.1 
      react-native-web: ~0.20.0 => 0.20.0 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
NB: expo-doctor and `expo install --fix` disagree on the dependencies

✖ Check that native modules use compatible support package versions for installed Expo SDK
Expected package @expo/config-plugins@~9.1.0
Found invalid:
  @expo/config-plugins@10.0.0
  (for more info, run: npm why @expo/config-plugins)
Advice:
Upgrade dependencies that are using the invalid package versions.

1 check failed, indicating possible issues with the project.
```

**Comment by thejoaov** [comment]
+1

**Comment by a-eid** [comment]
we're also having this issue right after the upgrade.

**Comment by RohovDmytro** [comment]
+1

**Comment by brentvatne** [comment]
this is resolved in the latest version of the expo pkg. the issue was only present when using `process.env.EXPO_PUBLIC_X` without having any .env files, but now that is no longer an issue

**Comment by a-eid** [comment]
@brentvatne unfortunately the issue is still present with the latest expo `53.0.7`

```bash
EXPO_PUBLIC_CHANNEL=development expo start 
```

```ts
console.log(process.env.EXPO_PUBLIC_CHANNEL) // undefined 
```

**Comment by brentvatne** [comment]
@a-eid - to clarify, the issue is only with setting it with `EXPO_PUBLIC_CHANNEL=development expo start ` but if you set it in **.env** then it works as expected?

**Comment by a-eid** [comment]
@brentvatne correct, env variables from `.env` work just fine.

**Comment by DimitarNestorov** [comment]
Offending commit: https://github.com/expo/expo/commit/022955b16f1c7db8d74ee650b54d21b1455afee0

Patch that works for us:

```patch
diff --git a/build/inline-env-vars.js b/build/inline-env-vars.js
index caf3e9bf2bd3f6c7d3d0bb903bd2be1eff8cf242..c0595481d5c934ed5a623be5b8fc4dce30fb45e4 100644
--- a/build/inline-env-vars.js
+++ b/build/inline-env-vars.js
@@ -14,6 +14,7 @@ function expoInlineEnvVars(api) {
     return {
         name: 'expo-inline-or-reference-env-vars',
         pre(file) {
+            return
             const addNamedImportOnce = (0, common_1.createAddNamedImportOnce)(core_1.types);
             addEnvImport = () => {
                 return addNamedImportOnce(file.path, 'env', 'expo/virtual/env');
@@ -28,6 +29,8 @@ function expoInlineEnvVars(api) {
                     if (core_1.types.isStringLiteral(key) &&
                         !isFirstInAssign(path) &&
                         key.value.startsWith('EXPO_PUBLIC_')) {
+                            path.replaceWith(core_1.types.valueToNode(process.env[key.value]));
+                            return
                         const envVar = key.value;
                         debug(`${isProduction ? 'Inlining' : 'Referencing'} environment variable in %s: %s`, filename, envVar);
                         publicEnvVars.add(envVar);
@@ -42,6 +45,7 @@ function expoInlineEnvVars(api) {
             },
         },
         post(file) {
+            return
             assertExpoMetadata(file.metadata);
             file.metadata.publicEnvVars = Array.from(publicEnvVars);
         },
```

**Comment by AyoCodess** [comment]
same issue, only fails in production for me 

![Image](https://github.com/user-attachments/assets/6e239ba9-95c6-4ef3-8ef0-9a585a293a1b)

**Comment by EvanBacon** [comment]
@AyoCodess the issue linked above is in development-only as far as I can tell. The production system works the same as before and doesn't seem to have changed. Please open a new issue with a reproducible example so I can investigate.

**Comment by AyoCodess** [comment]
@EvanBacon the issue was to do my own configuration apologies for the misdirection.
