### ISSUE TITLE
[expo-maps] onMapClick is triggered when onMarkerClick is fired using AppleMaps.View

### ISSUE THREAD

**Issue by seasheepjoe** [expo/expo#37354]
### Minimal reproducible example

https://github.com/seasheepjoe/map-marker-click-issue

### Steps to reproduce

I'm using expo-maps@0.10.0 and expo@53.0.11.
To reproduce, install the dependencies using `npm`, run `npx expo prebuild` and `npx expo run:ios` and run the app on a simulator (I use an iPhone 16 Pro Max with iOS 18.0).

A marker should already be on the map, located in Paris, France. I added two console.log. One on the `onMapClick` callback and the other on `onMarkerClick` callback. Click on the marker and check the metro logs.
Two logs will appear :

- map clicked {"latitude": 51.15926975195624, "longitude": 2.4216328688335897, "target": 2}
- marker clicked {"coordinates": {"latitude": 48.8582, "longitude": 2.2945}, "id": "4803C4D1-DFC5-4F7A-B672-F63B242A345D", "systemImage": "star.fill", "target": 2, "tintColor": undefined, "title": "Paris"}

I don't think that should happen ? The `onMapClick` callback should not be fired in this case ?
Also, notice the slowness of the `onMarkerClick` callback compared to the `onMapClick` callback.

I already checked the docs of the `onMapClick` callback : "Lambda invoked when the user clicks on the map. It won't be invoked if the user clicks on POI or a marker."

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: macOS 15.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.14.0 - ~/.nvm/versions/node/v22.14.0/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.9.2 - ~/.nvm/versions/node/v22.14.0/bin/npm
      Watchman: 2025.03.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 28, 30, 33, 34, 35
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23726.103.2422.13103373
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.11 => 53.0.11
      react: 19.0.0 => 19.0.0
      react-native: 0.79.3 => 0.79.3
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

**Comment by alanjhughes** [comment]
I think this was already fixed cc @jakex7

**Comment by derlisrd** [comment]
Same issue

**Comment by lenzi-e** [comment]
I am still running into this. I created a new issue with latest versions, since this one was closed. So, I believe this issue is still relevant: https://github.com/expo/expo/issues/41820
