### ISSUE TITLE
SDK 53: Deep links don't work when the app starts initially closed

### ISSUE THREAD

**Issue by vaharoni** [expo/expo#37401]
### Minimal reproducible example

https://github.com/vaharoni/expo-deep-links-bug

### Steps to reproduce

The attached repo is a minimal reproducible example of an issue encountered in production since upgrading to Expo 53. It contains a simple Expo app that shows the Expo router path the application is displaying. 
It is linked with an applinks domain. When clicking on `https://the-applinks-domain/hello/world` one of two things happen:
1. if the app is open on the user's device, it correctly shows the message "You are in /hello/world"
2. if the app is initially closed, it wrongly shows the message "You are in the home screen"

Interestingly, this does not occur in development - only in production.

I'd be happy to send TestFlight invites for the built app to whomever wishes to test this. 

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: macOS 15.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.11.0 - ~/.nvm/versions/node/v23.11.0/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.9.2 - ~/.nvm/versions/node/v23.11.0/bin/npm
      Watchman: 2025.02.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/amitaharoni/.rvm/gems/ruby-3.4.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.11 => 53.0.11 
      expo-router: ~5.1.0 => 5.1.0 
      react: 19.0.0 => 19.0.0 
      react-dom: 19.0.0 => 19.0.0 
      react-native: 0.79.3 => 0.79.3 
      react-native-web: ~0.20.0 => 0.20.0 
    npmGlobalPackages:
      eas-cli: 16.9.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

**Comment by Dylan-Brandenburg** [comment]
I recently ran into the same issue. 
Deep links worked fine for the most part in cold start and background, I.e (appScheme:///somepage).

Universal links however did not. A link like this one https://someApp.com/somepage would work correctly when the app is opened but would never be properly resolved if it was opened from a cold start. 

After reading a bunch of source code I believe the issue is the way the team is attempting to resolve the initial Url in getLinkingConfig- although I'm not certain.


I temporarily worked around this on my end using redirectSystemPath and asynchronously calling Linking.getInitialUrl and doing some checks then, it may have side effects. It feels backwards however I wanted to keep my current path re-writing collocated for the time being

**Comment by vaharoni** [comment]
Yes, I believe it's the same. Deep links seem to work fine from cold start, e.g. when I use share intent. But universal links do not. I placed a Sentry call in `redirectSystemPath` in `+native-intent.ts` and saw `path` is unaware of the deep link on cold start. It always gets `app-scheme:///`. I haven't tried `getInitialUrl` though - will give it a try.

**Comment by msobczyk-x** [comment]
I'm experiencing the same issue and am also having issues with the deeplinks themselves. There's inconsistent URI parsing behavior between cold start and when the app is already running.

- **Cold start**: `com.example://hello/world` resolves to the `/world` path
- **App already running**: `com.example://hello/world` resolves to the `/hello/world` path

Using `redirectSystemPath` with custom handling appears to work fine and seems to be a viable workaround for now.

**Comment by vaharoni** [comment]
@msobczyk-x something like this happened to me in dev mode, and after upgrading to expo 53.0.11 from 53.0.9, this issue was fixed.

**Comment by vaharoni** [comment]
I can confirm that the workaround suggested by @msobczyk-x works. 
Here's the code I'm using for now. 

```typescript
// This is a workaround for issue https://github.com/expo/expo/issues/37401

import { useEffect } from "react";
import { Linking } from "react-native";
import { Href, useRouter } from "expo-router"; 
import { createStore, useStore } from "zustand";


// Get these constants from somewhere
const appLinkRegex = new RegExp(`${APPLINKS_HOST}/(.*)$`);
const appScheme = APP_SCHEME;


type InitialUrlState = {
  status: "initializing" | "ok" | "redirecting",
  redirectTo?: Href | null,
}

const initialUrlStore = createStore<InitialUrlState>()(() => ({
  status: 'initializing',
  redirectTo: null,
}))

// Use in +native-intent.tsx
// Example usage: 
//  export function redirectSystemPath({ initial, path }: { initial: boolean; path: string }) {
//    settleInitialUrlStore(initial, path);
//    return path;
//  }
export function settleInitialUrlStore(isColdStart: boolean, path: string) {
  // We only need to getInitialURL if the app was cold started and the path is the app's root, 
  // which is how the Expo issue manifests
  const shouldCheckInitialUrl = isColdStart && path === `${appScheme}:///`;
  if (!shouldCheckInitialUrl) {
    initialUrlStore.setState({ status: 'ok', redirectTo: null });
    return;
  }

  Linking.getInitialURL().then((url) => {
    if (url) {
      const href = url.match(appLinkRegex)?.[1];
      if (href) {
        const redirectTo = `/${href}` as Href;
        initialUrlStore.setState({ status: 'redirecting', redirectTo });
        return;
      }
    }
    initialUrlStore.setState({ status: 'ok', redirectTo: null });
  });
}

// Use in root layout
// Example usage:
//  const initialUrlCheckStatus = useInitialUrlCheckStatus();
//   
//  // ...
// 
//  // Show a spinner or splash screen while the initial URL check is in progress
//  if (initialUrlCheckStatus !== 'ok') return null;
export function useInitialUrlCheckStatus() {
  const router = useRouter();
  const status = useStore(initialUrlStore, (state) => state.status);
  const redirectTo = useStore(initialUrlStore, (state) => state.redirectTo);

  useEffect(() => {
    if (status === 'redirecting' && redirectTo) {
      // Without the setTimeout, the app crashes for some reason
      setTimeout(() => {
        router.replace(redirectTo);
        initialUrlStore.setState({ status: 'ok', redirectTo: null });
      }, 10)
    }
  }, [status, redirectTo])

  return status;
}
```

**Comment by msmith-techempower** [comment]
I am encountering the error on Expo 53.0.12.

I tried the workaround by @vaharoni but never got it working on Android emulator (BSoD).

**Comment by chrfalch** [comment]
Hi, thanks for all of the great feedback and suggestions on how to solve this - I'll look into it and see what we can do here!

**Comment by chrfalch** [comment]
Looks like this is fixed here: https://github.com/expo/expo/pull/37647 - I'll push on to get this released in SDK-53!

**Comment by msmith-techempower** [comment]
Did this happen to make it in 53.0.17 or maybe 53.0.18?

**Comment by brentonwong** [comment]
Universal Linking is still broken on iOS on 52.0.47. `useLinkingURL` from `expo-linking` is always null so can't handle it manually as others suggested.

**Comment by chrfalch** [comment]
Hi, @expo-linking version 7.1.7 should contain this fix.

**Comment by brentonwong** [comment]
Thanks @chrfalch, I've just tried 7.1.7 but it still doesn't seem to return the initial link? I'm also using expo-router `4.0.17` if that matters as well?

```
import { getInitialURL, getLinkingURL } from 'expo-linking'

export async function redirectSystemPath({ initial, path }: { initial: boolean; path: string }): Promise<string> {
  const initialUrl = await getInitialURL()
  const linkingUrl = getLinkingURL()

  console.log('initialUrl', initialUrl)
  console.log('getLinkingUrl', linkingUrl)
  console.log('redirectSystemPath', initial, path)
  return path
}
```

Clicking on a link in my simulator on ios still opens only to the root. E.g. https://www.myapp.com/articles I would expect the intiialPath or my linking url to have my path /articles but they're all null or root.

ouputs:

```
 LOG  initialUrl null
 LOG  getLinkingUrl null
 LOG  redirectSystemPath true app:///
```

<img width="436" height="390" alt="Image" src="https://github.com/user-attachments/assets/0280ea9d-5e7f-40ae-b25d-0195e7baa8b1" />

**Comment by chrfalch** [comment]
Please make sure your node_modules folder contains the changes described in this PR: https://github.com/expo/expo/pull/37647

**Comment by brentonwong** [comment]
> Please make sure your node_modules folder contains the changes described in this PR: [#37647](https://github.com/expo/expo/pull/37647)

Yep, I have the changes described in the PR to `LinkingAppDelegateSubscriber.swift` in my `node_modules`. Did a clean install of my modules as well but still not getting any url being set.

**Comment by bryanmylee** [comment]
Adding here that I'm also facing the same issue where cold-starts are not being linked properly on iOS, using Expo 52.0.47 and expo-linking 7.1.7

**Comment by Chasty** [comment]
Same issue, universal deeplinks are not working, just custom schemas, I am using.

"expo": "54.0.21",
 "react-native": "0.81.5",
"expo-linking": "8.0.8",

any idea?

**Comment by tinchogon34** [comment]
I got it working temporarily by using the useUrl hook (deprecated) for iOS and useLinkingURL for Android.

**Comment by javiercejudo** [comment]
@Chasty I've started experiencing the same issue (iOS only) since expo@54.0.14. The effect is the same as described in the original report, except I see the issue even in development.

**Comment by Chasty** [comment]
@javiercejudo our current app on prod works fine, we've upgraded.

from

"expo": "52.0.37"
"expo-linking": "7.0.5"
"react-native": "0.76.7"

to

"expo": "54.0.21"
"expo-linking": "8.0.8"
"react-native": "0.81.5"

yup, u know even in development (simulator) tapping on a deeplink is opening the web and not the app, that's why Im using --device to test it on my device.

I see the issue in release and debug builds.

**Comment by markwitt1** [comment]
Also experiencing this issue. Could you reopen the issue?

**Comment by kcrwfrd** [comment]
I'm having problems with custom scheme deep links on cold starts. `getInitialURL()` is returning null

```json
"expo": "53.0.18",
"expo-linking": "7.1.7"
```

**Comment by michbil** [comment]
EXPO 54. Bug is still there.
```
"expo": "~54.0.21",
"expo-linking": "~8.0.8",
```

**Comment by iffa** [comment]
I am also encountering this. The app needs to be initially open for even `redirectSystemPath` to function properly:

```
"expo": "54.0.25",
"expo-linking": "8.0.9",
```

**Comment by jbaudanza** [comment]
For anyone still having this issue, I have a PR here: https://github.com/expo/expo/pull/41185

**Comment by kcrwfrd** [comment]
In case any other poor souls arrive here the same way I did, the reason deep linking cold starts didn't work with my app was because we were using scenes in iOS, which seem buggy/poorly supported at the moment.

Not sure if this is specifically a RN bug or an Expo bug.

This repo is of interest:

- https://github.com/g4rb4g3/react-native-carplay/tree/master/packages/react-native-carplay
- https://github.com/g4rb4g3/react-native-carplay/blob/master/CarPlay.md

Other discussions/issues:

- https://github.com/expo/expo/discussions/24354

**Comment by markwitt1** [comment]
Any update on this?

**Comment by jbaudanza** [comment]
> Any update on this?

This should be fixed by the above referenced PR

**Comment by itsalysialynn** [comment]
Any update expo team?

**Comment by jbaudanza** [comment]
> Any update expo team?

It looks like a fix for this was released on 2025-12-04. This issue can probably be closed.
https://github.com/expo/expo/blob/main/packages/expo-modules-core/CHANGELOG.md#3026---2025-11-17

**Comment by itsalysialynn** [comment]
@jbaudanza which version of expo would this fix be on? We seem to still have issues; we are on `54.0.30`

**Comment by AdamGerthel** [comment]
I'm on `54.0.31` and am seeing intermittent crashes with deep links on iOS in development (on simulator). Am also not sure if the issue is with expo-linking or Linking from RN, but the crashes only occur when launching using any deep link. They happen around 50% of the time, and always happen before any JS code is run.

**Comment by shehanGuruge** [comment]
I am experiencing a bit of a weird issue,

**Scenario 1**
When the app is opened through a link, it navigates to the screen (AS EXPECTED)

**Scenario 2**
After the URL is handled in the previous open (Scenario 1), the app is closed, removed from the app history stack, and opened as a fresh start by tapping the app icon. I get the URL again that was handled previously. It keeps happening over and over again in a fresh start. Is there any caching involved here?
