### ISSUE TITLE
Eas build fails with "Failed to apply plugin 'expo-root-project' > Key 1.6.10 is missing in the map."

### ISSUE THREAD

**Issue by D3nC4t** [expo/expo#37405]
### Minimal reproducible example

https://github.com/D3nC4t/eas-build-error

### Steps to reproduce

To reproduce is simple:
- 1st. install expo-build-properties
- 2nd. Go to app.json and add the plugin with the setting `"kotlinVersion": "1.6.10"`
```
...
"plugins": [
  [
    "expo-build-properties",
    {
      "android": {
        "kotlinVersion": "1.6.10",
        "packagingOptions": {
          "pickFirst": [
            "**/libc++_shared.so"
          ]
        }
      }
    }
  ]
],
...
```
- 3rd. run `eas build --platform android --profile preview`

Then the build will fail with the error:
```
A problem occurred evaluating root project '<project-name>'.
> Failed to apply plugin 'expo-root-project'.
   > Key 1.6.10 is missing in the map.
```

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: macOS 15.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.16.0 - ~/.nvm/versions/node/v22.16.0/bin/node
      npm: 11.4.1 - ~/.nvm/versions/node/v22.16.0/bin/npm
      Watchman: 2025.05.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/cat/.gems/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.5, iOS 18.5, macOS 15.5, tvOS 18.5, visionOS 2.5, watchOS 11.5
    IDEs:
      Android Studio: 2024.3 AI-243.26053.27.2432.13536105
      Xcode: 16.4/16F6 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.11 => 53.0.11 
      react: 19.0.0 => 19.0.0 
      react-native: 0.79.3 => 0.79.3 
    npmGlobalPackages:
      eas-cli: 16.9.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

**Comment by D3nC4t** [comment]
Just for the record, locally there are no build issues while running the `gradlew :app:assembleRelease`, this only happens inside the EAS builds (in the remote pipeline)
<img width="447" alt="Image" src="https://github.com/user-attachments/assets/2c3ef109-b18e-4423-85fb-d859bf82a8aa" />

**Comment by D3nC4t** [comment]
Update, after deleting the local android folder, I'm able to reproduce the issue with the local command `npx expo run:android`, it seems that the problem is somewhere in the `expo-build-properties`
<img width="1417" alt="Image" src="https://github.com/user-attachments/assets/ea607c2f-649c-4414-9cb1-8d4a778881ca" />

**Comment by imckain** [comment]
Seeing same for any `kotlinVersion` being defined. Followed this related thread https://github.com/expo/expo/issues/36461.

Tried all Expo versions from 53.0.7-53.0.11. No change.

I wrote a plugin that resolved an issue getting the `kotlinVersion`, but got an issue with the key missing in the map. At this point I'm getting too deep into custom plugins for my liking, hoping to see a resolution here.

**Comment by imckain** [comment]
I was able to resolve this by setting `kotlinVersion` to 2.0.21.

I found `ExpoAutolinkingSettingsExtension.kt` which sets the base file for versions:
```
val baseFile = if (reactNativeVersionCatalog != null) {
      File(reactNativeVersionCatalog)
    } else {
      File(
        reactNative,
        "gradle/libs.versions.toml"
      )
    }
```

Since there seems to be an issue with how the version catalog should be read, I assumed it's applying the default file, `libs.versions.toml`, from React Native.

which has this list:
```
[versions]
# Android versions
minSdk = "24"
targetSdk = "35"
compileSdk = "35"
buildTools = "35.0.0"
ndkVersion = "27.1.12297006"
# Dependencies versions
agp = "8.8.2"
androidx-annotation = "1.6.0"
androidx-appcompat = "1.7.0"
androidx-autofill = "1.1.0"
androidx-swiperefreshlayout = "1.1.0"
androidx-test = "1.5.0"
androidx-tracing = "1.1.0"
assertj = "3.21.0"
binary-compatibility-validator = "0.13.2"
download = "5.4.0"
fbjni = "0.7.0"
fresco = "3.6.0"
infer-annotation = "0.18.0"
javax-annotation-api = "1.3.2"
javax-inject = "1"
jsc-android = "2026004.0.1"
jsr305 = "3.0.2"
junit = "4.13.2"
kotlin = "2.0.21"
mockito = "3.12.4"
mockito-kotlin = "3.2.0"
nexus-publish = "1.3.0"
okhttp = "4.9.2"
okio = "2.9.0"
robolectric = "4.9.2"
soloader = "0.12.1"
xstream = "1.4.20"
yoga-proguard-annotations = "1.19.0"
# Native Dependencies
boost="1_83_0"
doubleconversion="1.1.6"
fastFloat="6.1.4"
fmt="11.0.2"
folly="2024.11.18.00"
glog="0.3.5"
gtest="1.12.1"
```

Kotlin is defined as `2.0.21` added that to my build properties plugin and it built properly.

I still had to have a custom plugin for reading/setting the values but it works for now. Thanks to this comment https://github.com/expo/expo/issues/36461#issuecomment-2846152663

```
#app.config.ts
...
[
      'expo-build-properties',
      {
        android: {
          compileSdkVersion: 35,
          targetSdkVersion: 35,
          buildToolsVersion: '35.0.0',
          kotlinVersion: '2.0.21',
        },
        ios: {
          deploymentTarget: '15.1',
        },
      },
    ],
...
```

```
#plugin
// ./plugins/minSdkProjectGradlePatch.js

const { withProjectBuildGradle } = require('@expo/config-plugins');
const generateCode = require('@expo/config-plugins/build/utils/generateCode');

// https://github.com/expo/expo/issues/36461#issuecomment-2846152663
const minSdkPatchCode = `
  ext {
    buildToolsVersion = findProperty('android.buildToolsVersion') ?: '35.0.0'
    compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '35')
    targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '35')
    kotlinVersion = findProperty('android.kotlinVersion') ?: '2.0.21'
  }
`;

module.exports = function withMinSdkProjectGradlePatch(config) {
  return withProjectBuildGradle(config, async (config) => {
    if (config.modResults.contents.includes(minSdkPatchCode)) {
      return config;
    }

    const addCode = generateCode.mergeContents({
      newSrc: minSdkPatchCode,
      tag: 'minSdkPatchCode',
      src: config.modResults.contents,
      anchor: 'buildscript {',
      comment: '//',
      offset: 1,
    });

    config.modResults.contents = addCode.contents;

    console.log(
      '[minSdkProjectGradlePatch] Gradle patch applied successfully!',
    );

    return config;
  });
};

```

**Comment by D3nC4t** [comment]
> I was able to resolve this by setting `kotlinVersion` to 2.0.21.
> 
> I found `ExpoAutolinkingSettingsExtension.kt` which sets the base file for versions:
> ```
> val baseFile = if (reactNativeVersionCatalog != null) {
>       File(reactNativeVersionCatalog)
>     } else {
>       File(
>         reactNative,
>         "gradle/libs.versions.toml"
>       )
>     }
> ```
> 
> Since there seems to be an issue with how the version catalog should be read, I assumed it's applying the default file, `libs.versions.toml`, from React Native.
> 
> which has this list:
> ```
> [versions]
> # Android versions
> minSdk = "24"
> targetSdk = "35"
> compileSdk = "35"
> buildTools = "35.0.0"
> ndkVersion = "27.1.12297006"
> # Dependencies versions
> agp = "8.8.2"
> androidx-annotation = "1.6.0"
> androidx-appcompat = "1.7.0"
> androidx-autofill = "1.1.0"
> androidx-swiperefreshlayout = "1.1.0"
> androidx-test = "1.5.0"
> androidx-tracing = "1.1.0"
> assertj = "3.21.0"
> binary-compatibility-validator = "0.13.2"
> download = "5.4.0"
> fbjni = "0.7.0"
> fresco = "3.6.0"
> infer-annotation = "0.18.0"
> javax-annotation-api = "1.3.2"
> javax-inject = "1"
> jsc-android = "2026004.0.1"
> jsr305 = "3.0.2"
> junit = "4.13.2"
> kotlin = "2.0.21"
> mockito = "3.12.4"
> mockito-kotlin = "3.2.0"
> nexus-publish = "1.3.0"
> okhttp = "4.9.2"
> okio = "2.9.0"
> robolectric = "4.9.2"
> soloader = "0.12.1"
> xstream = "1.4.20"
> yoga-proguard-annotations = "1.19.0"
> # Native Dependencies
> boost="1_83_0"
> doubleconversion="1.1.6"
> fastFloat="6.1.4"
> fmt="11.0.2"
> folly="2024.11.18.00"
> glog="0.3.5"
> gtest="1.12.1"
> ```
> 
> Kotlin is defined as `2.0.21` added that to my build properties plugin and it built properly.
> 
> I still had to have a custom plugin for reading/setting the values but it works for now. Thanks to this comment https://github.com/expo/expo/issues/36461#issuecomment-2846152663
> 
> ```
> #app.config.ts
> ...
> [
>       'expo-build-properties',
>       {
>         android: {
>           compileSdkVersion: 35,
>           targetSdkVersion: 35,
>           buildToolsVersion: '35.0.0',
>           kotlinVersion: '2.0.21',
>         },
>         ios: {
>           deploymentTarget: '15.1',
>         },
>       },
>     ],
> ...
> ```
> 
> ```
> #plugin
> // ./plugins/minSdkProjectGradlePatch.js
> 
> const { withProjectBuildGradle } = require('@expo/config-plugins');
> const generateCode = require('@expo/config-plugins/build/utils/generateCode');
> 
> // https://github.com/expo/expo/issues/36461#issuecomment-2846152663
> const minSdkPatchCode = `
>   ext {
>     buildToolsVersion = findProperty('android.buildToolsVersion') ?: '35.0.0'
>     compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '35')
>     targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '35')
>     kotlinVersion = findProperty('android.kotlinVersion') ?: '2.0.21'
>   }
> `;
> 
> module.exports = function withMinSdkProjectGradlePatch(config) {
>   return withProjectBuildGradle(config, async (config) => {
>     if (config.modResults.contents.includes(minSdkPatchCode)) {
>       return config;
>     }
> 
>     const addCode = generateCode.mergeContents({
>       newSrc: minSdkPatchCode,
>       tag: 'minSdkPatchCode',
>       src: config.modResults.contents,
>       anchor: 'buildscript {',
>       comment: '//',
>       offset: 1,
>     });
> 
>     config.modResults.contents = addCode.contents;
> 
>     console.log(
>       '[minSdkProjectGradlePatch] Gradle patch applied successfully!',
>     );
> 
>     return config;
>   });
> };
> 
> ```

This does not solve my issue, I've a feature in my project that requires the version 1.6.10 to work properly, is an old library with maintenance but no evolution...

**Comment by D3nC4t** [comment]
PS, I'm able to fix my issue by disabling that feature, however it make my app slower 🙃 however allows me to use the default kotlin version set by expo

**Comment by imckain** [comment]
> This does not solve my issue, I've a feature in my project that requires the version 1.6.10 to work properly, is an old library with maintenance but no evolution...

I think until a solution is in place to allow for older versions this is not possible. Highly likely that older versions are just no longer supported. If you require that older version maybe staying on 52 is the best solution for your application.

**Comment by D3nC4t** [comment]
That's not an option, I prefer to have JSI disabled rather than using older versions of libraries... I need to have the lastest versions of all libraries so that is easy to maintain.

Also I don't see advantages of having a setting in a core library of expo if it doesn't allow to use a version of kotlin that is not the default one...

**Comment by imckain** [comment]
> That's not an option, I prefer to have JSI disabled rather than using older versions of libraries... I need to have the lastest versions of all libraries so that is easy to maintain.
> 
> Also I don't see advantages of having a setting in a core library of expo if it doesn't allow to use a version of kotlin that is not the default one...

I’m sure they’ll have some direction or a fix. With any new release there’s always some kinks to work out.

**Comment by rnqs** [comment]
Same issue with the `kotlinVersion` property in a managed Expo workflow. Even though I was using version `2.0.21`, neither the fix with the custom plugin nor the default config worked.

It’s far from ideal, but I managed to make it work by adding a post-install script. The script updates the `build.gradle` and `gradle.properties` files to make sure the correct Kotlin version is set.

```javascript
// scripts/easBuildPostInstall.js

const KOTLIN_VERSION = '2.0.21'; // Your Kotlin version
const KSP_VERSION = '2.0.21-1.0.28'; // Your KSP version (https://github.com/google/ksp/releases)

if (process.env.EAS_BUILD_PLATFORM === 'android') {
  const fs = require('fs');
  const path = require('path');

  const updateBuildGradle = () => {
    const rootDir = process.cwd();
    const gradlePath = path.join(rootDir, 'android', 'build.gradle');

    try {
      let gradleContent = fs.readFileSync(gradlePath, 'utf8');

      const dependenciesRegex = /dependencies\s*{[^}]*}/g;

      const fixedDependencies = `
dependencies {
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${KOTLIN_VERSION}"
    classpath "com.google.devtools.ksp:symbol-processing-gradle-plugin:${KSP_VERSION}"
    classpath "com.google.gms:google-services:4.4.1"
    classpath "com.android.tools.build:gradle"
    classpath "com.facebook.react:react-native-gradle-plugin"
}`;

      gradleContent = gradleContent.replace(
        dependenciesRegex,
        fixedDependencies,
      );

      gradleContent = gradleContent.replace(
        /kotlinVersion\s*=\s*findProperty\(['"\w.]+\)[^\n]*/g,
        `kotlinVersion = '${KOTLIN_VERSION}'`,
      );

      gradleContent = gradleContent.replace(
        /kotlinVersion\s*=\s*['"][^'"]+['"]/g,
        `kotlinVersion = '${KOTLIN_VERSION}'`,
      );

      gradleContent = gradleContent.replace(
        /kotlin-gradle-plugin:[0-9.]+/g,
        `kotlin-gradle-plugin:${KOTLIN_VERSION}`,
      );

      fs.writeFileSync(gradlePath, gradleContent, 'utf8');

      console.log('build.gradle dependencies fixed successfully.');
    } catch (error) {
      console.error('Error updating build.gradle:', error);
      process.exit(1);
    }
  };

  const updateGradleProperties = () => {
    const rootDir = process.cwd();
    const gradlePropsPath = path.join(rootDir, 'android', 'gradle.properties');

    try {
      if (fs.existsSync(gradlePropsPath)) {
        let gradlePropsContent = fs.readFileSync(gradlePropsPath, 'utf8');

        gradlePropsContent = gradlePropsContent.replace(
          /android\.kotlinVersion\s*=\s*[0-9.]+/g,
          `android.kotlinVersion=${KOTLIN_VERSION}`,
        );

        gradlePropsContent = gradlePropsContent.replace(
          /kotlinVersion\s*=\s*[0-9.]+/g,
          `kotlinVersion=${KOTLIN_VERSION}`,
        );

        fs.writeFileSync(gradlePropsPath, gradlePropsContent, 'utf8');
        console.log('gradle.properties kotlin version fixed successfully.');
      }
    } catch (error) {
      console.error('Error updating gradle.properties:', error);
    }
  };

  updateBuildGradle();
  updateGradleProperties();
}
```

Set up the post-install script:

```js
// package.json

{
  "scripts": {
    ...
    "eas-build-post-install": "node ./scripts/easBuildPostInstall.js"
  }
}
```

**Comment by chrysb** [comment]
I am encountering this with expo-53 as well — can't build Android

**Comment by jukkamarttinen** [comment]
Same problem here with SDK 53

**Comment by Francopf21** [comment]
In my case, leaving alone worked for me. Good luck.

    "plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 35.
            "targetSdkVersion": 35,
            "buildToolsVersion": "35.0.0"
          }
        }
      ],
    // other flags
    ]

**Comment by D3nC4t** [comment]
You are not following this thread  issue, the issue happens when selecting
a specific kotlin version

**Comment by umutsesen** [comment]
same issue latest 53.0.20. Does no one test this when pushing updates?

**Comment by Igornorlin** [comment]
Same issues here for 53.0.20

**Comment by HungryDogStudios** [comment]
Same issue here for 53.0.20

**Comment by Haider-Mukhtar** [comment]
```
"android":
{
  "compileSdkVersion": 35,
  "targetSdkVersion": 35,
  "buildToolsVersion": "35.0.0",
  "kotlinVersion": "1.9.25"
}
```

```
A problem occurred evaluating root project 'Laila'.
> Failed to apply plugin 'expo-root-project'.
   > Key 1.9.25 is missing in the map.
```

```
"react": "^19.1.1",
"react-native": "0.79.5",
"expo": "^53.0.20",
```


Same issue, any solution?

**Comment by knofte** [comment]
Same issue with 1.9.24, however not even specifying a kotlinVersion, it is injected by the build (we use clean build, so no existing android folder), and then fails because it injects wrong version. As far as I can understand.

**Comment by lukmccall** [comment]
Hey everyone! 

We've **dropped** support for Kotlin versions below `2.0` in `SDK 53`, which is why you're seeing these errors. However, you can try specifying the `kspVersion` alongside the `kotlinVersion` in your `build.gradle` file. Be aware that the build process might still fail if some of our packages use Kotlin code requiring a higher language version. 

Is there a specific package that is preventing you from upgrading to Kotlin 2.x?

**Comment by basask** [comment]
I have the same issue in my project ant it is not using kotlin at all. Maybe one of the dependencies does use it.

Going back to SDK 52 fixes the issue and for now it works for my context. I'd love to be able to use the new SDK

**Comment by lukmccall** [comment]
@basask if you provide a list of dependencies that you're using, I can help you identify which one is broken

**Comment by brax10ward** [comment]
@lukmccall is there documentation of which kotlin versions are supported? I am needing to use kotlin `2.1.21` but am getting this same error as this thread 
```
> Failed to apply plugin 'expo-root-project'.
   > Key 2.1.21 is missing in the map.

**Comment by radekaz** [comment]
Is it resolved? Will it be resolved in Expo 54?

**Comment by ghost** [comment]
Do you have any working solution?

**Comment by chr4ss12** [comment]
yes still broken, the problem is newer versions of kotlin can not be used except 2.0.21.


//edit, this works:

        kotlinVersion = "2.2.0"
        kspVersion = "2.2.0"

**Comment by Will-create** [comment]
> I was able to resolve this by setting `kotlinVersion` to 2.0.21.
> 
> I found `ExpoAutolinkingSettingsExtension.kt` which sets the base file for versions:
> 
> ```
> val baseFile = if (reactNativeVersionCatalog != null) {
>       File(reactNativeVersionCatalog)
>     } else {
>       File(
>         reactNative,
>         "gradle/libs.versions.toml"
>       )
>     }
> ```
> 
> Since there seems to be an issue with how the version catalog should be read, I assumed it's applying the default file, `libs.versions.toml`, from React Native.
> 
> which has this list:
> 
> ```
> [versions]
> # Android versions
> minSdk = "24"
> targetSdk = "35"
> compileSdk = "35"
> buildTools = "35.0.0"
> ndkVersion = "27.1.12297006"
> # Dependencies versions
> agp = "8.8.2"
> androidx-annotation = "1.6.0"
> androidx-appcompat = "1.7.0"
> androidx-autofill = "1.1.0"
> androidx-swiperefreshlayout = "1.1.0"
> androidx-test = "1.5.0"
> androidx-tracing = "1.1.0"
> assertj = "3.21.0"
> binary-compatibility-validator = "0.13.2"
> download = "5.4.0"
> fbjni = "0.7.0"
> fresco = "3.6.0"
> infer-annotation = "0.18.0"
> javax-annotation-api = "1.3.2"
> javax-inject = "1"
> jsc-android = "2026004.0.1"
> jsr305 = "3.0.2"
> junit = "4.13.2"
> kotlin = "2.0.21"
> mockito = "3.12.4"
> mockito-kotlin = "3.2.0"
> nexus-publish = "1.3.0"
> okhttp = "4.9.2"
> okio = "2.9.0"
> robolectric = "4.9.2"
> soloader = "0.12.1"
> xstream = "1.4.20"
> yoga-proguard-annotations = "1.19.0"
> # Native Dependencies
> boost="1_83_0"
> doubleconversion="1.1.6"
> fastFloat="6.1.4"
> fmt="11.0.2"
> folly="2024.11.18.00"
> glog="0.3.5"
> gtest="1.12.1"
> ```
> 
> Kotlin is defined as `2.0.21` added that to my build properties plugin and it built properly.
> 
> I still had to have a custom plugin for reading/setting the values but it works for now. Thanks to this comment [#36461 (comment)](https://github.com/expo/expo/issues/36461#issuecomment-2846152663)
> 
> ```
> #app.config.ts
> ...
> [
>       'expo-build-properties',
>       {
>         android: {
>           compileSdkVersion: 35,
>           targetSdkVersion: 35,
>           buildToolsVersion: '35.0.0',
>           kotlinVersion: '2.0.21',
>         },
>         ios: {
>           deploymentTarget: '15.1',
>         },
>       },
>     ],
> ...
> ```
> 
> ```
> #plugin
> // ./plugins/minSdkProjectGradlePatch.js
> 
> const { withProjectBuildGradle } = require('@expo/config-plugins');
> const generateCode = require('@expo/config-plugins/build/utils/generateCode');
> 
> // https://github.com/expo/expo/issues/36461#issuecomment-2846152663
> const minSdkPatchCode = `
>   ext {
>     buildToolsVersion = findProperty('android.buildToolsVersion') ?: '35.0.0'
>     compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '35')
>     targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '35')
>     kotlinVersion = findProperty('android.kotlinVersion') ?: '2.0.21'
>   }
> `;
> 
> module.exports = function withMinSdkProjectGradlePatch(config) {
>   return withProjectBuildGradle(config, async (config) => {
>     if (config.modResults.contents.includes(minSdkPatchCode)) {
>       return config;
>     }
> 
>     const addCode = generateCode.mergeContents({
>       newSrc: minSdkPatchCode,
>       tag: 'minSdkPatchCode',
>       src: config.modResults.contents,
>       anchor: 'buildscript {',
>       comment: '//',
>       offset: 1,
>     });
> 
>     config.modResults.contents = addCode.contents;
> 
>     console.log(
>       '[minSdkProjectGradlePatch] Gradle patch applied successfully!',
>     );
> 
>     return config;
>   });
> };
> ```

Thank you so much. this fixed mine too
