### ISSUE TITLE
[ios][expo-notifications]: getDevicePushTokenAsync never resolves on SDK 53

### ISSUE THREAD

**Issue by jesulonimii** [expo/expo#37516]
### Minimal reproducible example

https://github.com/JoelYourstone/expo-53-notifications-repro

### Steps to reproduce

After updating the code to Expo 53, I noticed that push notifications stopped working completely on iOS.
By investigating, I noticed that the `getDevicePushTokenAsync` method never resolves (it neither returns a result nor throws an error).

This is happening both in my development build and release build on iOS

I tried, 
- Changing my network 
- restarting my device, and another device I use for testing,
- Setting up a new push Key via EAS credentials.
-  Creating a d

But neither seems to work.
Everything works fine on Android, and on another project still running SDK 51, on the same device.

Expo notifications version:  "expo-notifications": "~0.31.3",

```
try {
					console.log("usePushNotification: start")

					const result = await Notifications.getExpoPushTokenAsync({
						projectId: Constants.expoConfig.extra.eas.projectId,
					})
					console.log("usePushNotification: Expo Push Token result", result)
					token = result.data

					console.log("usePushNotification: Expo Push Token", token)
				} catch (error) {
					console.error("usePushNotification: Error getting Expo Push Token", error)
					return
				} finally {
					console.log("usePushNotification: End")
				}
```

Above returns only 

LOG: usePushNotification: start

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: macOS 15.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.5.0 - ~/.nvm/versions/node/v23.5.0/bin/node
      npm: 10.9.2 - ~/.nvm/versions/node/v23.5.0/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.4, iOS 18.4, macOS 15.4, tvOS 18.4, visionOS 2.4, watchOS 11.4
    IDEs:
      Xcode: 16.3/16E140 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.20.0 => 0.20.14 
      babel-preset-expo: ~13.0.0 => 13.0.0 
      expo: 53.0.11 => 53.0.11 
      expo-router: ~5.1.0 => 5.1.0 
      expo-updates: ~0.28.14 => 0.28.14 
      react: 19.0.0 => 19.0.0 
      react-dom: 19.0.0 => 19.0.0 
      react-native: 0.79.3 => 0.79.3 
      react-native-web: ^0.20.0 => 0.20.0 
    npmGlobalPackages:
      eas-cli: 16.6.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

**Comment by honzza** [comment]
I’m experiencing the exact same issue, which I’ve been trying to resolve for the past few days without success. My setup is essentially identical to yours. I haven’t been able to find a solution, and this is preventing me from upgrading to SDK 53.

**Comment by learykara** [comment]
I'm facing the same problem. I feel like I've tried everything and I can't get anything to work.

**Comment by jesulonimii** [comment]
Hello @learykara @honzza ,

I found a way to resolve the issue.
Add this code to wherever you are making the `Notifications.getExpoPushTokenAsync` call

```
useEffect(() => {
		const tokenListener = Notifications.addPushTokenListener(token => {
			console.log(token);
		})

		return () => {
			if (tokenListener) {
				tokenListener.remove()
			}
		}
	}, [])
```

**Comment by honzza** [comment]
Hi @jesulonimii ,

Wow, that definitely worked! I placed it at the beginning of my app, where the other useEffect hooks are called, and it somehow resolved the issue with the stuck getExpoPushTokenAsync method. No need to make any other changes in getting and saving the push token.

Thanks for the solution!

**Comment by Julienblc** [comment]
Same issue here, gonna use the workaround waiting a clean solution

**Comment by cheeselemon** [comment]
updating the SDK to 53.0.19 seems to have resolved the issue!

**Comment by vonovak** [comment]
Hello,
this was fixed in 0.31.3 via https://github.com/expo/expo/pull/36930

Thank you

**Comment by thenbe** [comment]
> Hello, this was fixed in 0.31.3 via [#36930](https://github.com/expo/expo/pull/36930)

Is this an oversight? Because OP is already on version `0.31.3`. From OP:

> Expo notifications version: "expo-notifications": "~0.31.3",

FWIW, I am on `0.31.3` and facing the same issue.

**Comment by jordansoltman** [comment]
Also on 0.31.4 and having the same issue...

**Comment by davit-khaburdzania** [comment]
I am facing same issue on 0.31.4 
Has anyone been able to find solution?

**Comment by vonovak** [comment]
Hello everyone,
if you're still facing the problem, please open a new issue with a reproducer, thank you.

**Comment by jpaas** [comment]
Can confirm it's still happening on `expo-notifications` 0.32.5

**Comment by vonovak** [comment]
Hello,
I was not able to reproduce the issue with the repro that was shared in the original post but I tried to "infer" how the issue could be happening and introduced these changes to counter the problem: https://github.com/expo/expo/pull/39179 
I'd like to ask the people who are experiencing this problem to try out my changes in their app (just copy-paste them into the relevant file in xcode) and report back whether or not is fixes the problem for them.

If not, I'm going to need a simple reproducer for the issue: ideally just one file that I can copy-paste into my project and experience the issue myself. Without a reproducer, this is hard to fix on our end.
Thank you!

**Comment by jpaas** [comment]
Hi @vonovak thanks again for looking into this. Sorry I couldn't reply sooner. I tried your modified swift file but it didn't change anything for me. I also tried setting some breakpoints and all I can tell you is that the method is only getting called once. It is not entering that if block for when the promise is already defined. Also for what it's worth, the same code works fine on android.

I just upgraded to sdk 54 preview 11 and the results are the same. I will try to find time to create a reproducer. If I manage to build a simple reproduction, would you want to reopen this or should I log a new issue?

**Comment by vonovak** [comment]
hello @jpaas kindly tell me:

Are these line executed for you? **Please place a breakpoint at all of those lines** and share screenshot when debugger hits it, and in the debugger window, expand the variables so that the value of `promiseNotYetResolved` is visible.

**Also provide the order in which those breakpoints are hit.** Take screenshots of the entire xcode window so everything is seen.

https://github.com/expo/expo/blob/026a2c18890b0f4ac1c875ce6d37edd41f05aac0/packages/expo-notifications/ios/EXNotifications/PushToken/PushTokenModule.swift#L18

https://github.com/expo/expo/blob/026a2c18890b0f4ac1c875ce6d37edd41f05aac0/packages/expo-notifications/ios/EXNotifications/PushToken/PushTokenModule.swift#L33

https://github.com/expo/expo/blob/026a2c18890b0f4ac1c875ce6d37edd41f05aac0/packages/expo-notifications/ios/EXNotifications/PushToken/PushTokenModule.swift#L45

https://github.com/expo/expo/blob/026a2c18890b0f4ac1c875ce6d37edd41f05aac0/packages/expo-notifications/ios/EXNotifications/PushToken/PushTokenModule.swift#L51

Thank you!

**Comment by jpaas** [comment]
@vonovak those are exactly where I placed my breakpoints. Here's the sequence.
18: hit first
33: hit next
45,51: never hit

**Comment by jpaas** [comment]
@vonovak here are the screenshots

<img width="888" height="1181" alt="Image" src="https://github.com/user-attachments/assets/1a1407bf-dd0e-415b-bc58-49e19c0e760a" />

<img width="886" height="1202" alt="Image" src="https://github.com/user-attachments/assets/5d1f4aa6-ceba-4471-a751-b0a5a081a048" />

**Comment by jpaas** [comment]
Hey @vonovak I think i figured it out. I don't know how I missed it. I feel like I looked at the example in the docs 10 times, but somehow I got the call for `getDevicePushTokenAsync` in front of permission checking. Without the permission it never returns I guess. Sorry for the runaround.

Oh and also strange... Calling `getDevicePushTokenAsync` without permission on android and the ios simulator works fine. The only place it doesn't work is physical ios device.

**Comment by vonovak** [comment]
I'm going to close the issue because there's no reliable reproducer. 

It seems it may be related to permissions.

If anyone else encounters this, please add a reproducer and attach the result of `grep --recursive 'UNUserNotificationCenter.current().delegate' .` and `grep --recursive "UNUserNotificationCenter currentNotificationCenter\] setDelegate" .` when executed from the root of your repository.

Thank you

**Comment by yberstad** [comment]
@jpaas FWIW, I do not have to ask the user for permissions before getting the push token from `getDevicePushTokenAsync` on my real iOS device. 

I am currently running expo 53.0.22 and expo-notifications 0.31.4.

I had problems getting `getDevicePushTokenAsync` to resolve after upgrading from Expo 52, but my issue was that i did not implement the AppDelegate correctly with ExpoAppDelegate (I have ejected using expo prebuild)

```
@UIApplicationMain
public class AppDelegate: ExpoAppDelegate {
....
}
```

**Comment by LucasWilliams2622** [comment]
✅ Downgrading expo-notifications to "expo-notifications": "0.29.13" solved the issue
Working environment:
    "expo": "53.0.22",
    "expo-notifications": "0.29.13",

**Comment by vonovak** [comment]
@LucasWilliams2622 can you attach the result of `grep --recursive 'UNUserNotificationCenter.current().delegate' .` and `grep --recursive "UNUserNotificationCenter currentNotificationCenter\] setDelegate" .` when executed from the root of your repository?

Thank you

**Comment by LucasWilliams2622** [comment]
> [@LucasWilliams2622](https://github.com/LucasWilliams2622) can you attach the result of `grep --recursive 'UNUserNotificationCenter.current().delegate' .` and `grep --recursive "UNUserNotificationCenter currentNotificationCenter\] setDelegate" .` when executed from the root of your repository?
> 
> Thank you

I ran the commands, here’s what I got:

./node_modules/expo-notifications/ios/EXNotifications/Notifications/EXNotificationCenterDelegate.m:  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self]; 

It looks like the delegate is being set inside expo-notifications.

**Comment by JustJoostNL** [comment]
I am also (still) experiencing this issue.

These versions are installed
```json
"expo": "54.0.9",
"expo-notifications": "~0.32.11",
```

@vonovak For me only the first command gave an output:
```
./node_modules/expo-notifications/ios/EXNotifications/Notifications/NotificationCenterManager.swift:    if UNUserNotificationCenter.current().delegate != nil {
./node_modules/expo-notifications/ios/EXNotifications/Notifications/NotificationCenterManager.swift:    UNUserNotificationCenter.current().delegate = self
```

The second command did not find/output anything.

Anything we can do to help and solve this?

**Comment by vonovak** [comment]
> I am also (still) experiencing this issue.
> 
> Anything we can do to help and solve this?

@JustJoostNL yes, providing a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) that we can see the issue with would.be immensely helpful.

Thank you 

The output of the grep commands doesn't show anything wrong.

**Comment by JustJoostNL** [comment]
@vonovak I currently don't have a minimal reproducible example (I'll have a look whether I can do that), but the issue only occurs when building with XCode 26 (for iOS 26).

Does that information help too?

**Comment by vonovak** [comment]
@JustJoostNL sorry, no, that doesn't really help 🥲

**Comment by JustJoostNL** [comment]
@vonovak 

I have created an example here: https://github.com/JustJoostNL/expo-demo
(Use XCode/iOS 26 when testing)

The screen tries to fetch the device token, but the function never resolves. Which results in the screen always showing "no data". The second log also never shows in the console.

**Comment by vonovak** [comment]
Thanks! I'll take a look tomorrow.
In the mean time, maybe worth trying is to obtain push permission first and then request the token.

**Comment by JustJoostNL** [comment]
Asking for permission first does not solve the problem unfortunately. This also shouldn't matter because the push token should be available even when permissions are not granted.

**Comment by JustJoostNL** [comment]
Also important is that this only seems to be an issue on the simulator (where it did work before).

**Comment by vonovak** [comment]
> Also important is that this only seems to be an issue on the simulator (where it did work before).

Hello @JustJoostNL, when you take a look at https://docs.expo.dev/versions/latest/sdk/notifications/ we signal in several places that notifications are a device-only feature. While that is an over-simplification (indeed you _could_ run push on simulators) and we probably could and should improve the docs, we recommend you test push notifications on device.

As you mentioned even in this case, it works on device.

The issue seems to be on Apple's side: https://developer.apple.com/forums/thread/795433

Thank you

**Comment by JustJoostNL** [comment]
Hey @vonovak 

Thanks for getting back to me! Good to know that this is a bug in iOS and not Expo. If it turns out this isn’t a bug but actually how Apple wants the simulator to behave, would it be possible to throw an error or return `undefined` when the function is called on the simulator?

**Comment by vonovak** [comment]
I don't think apple wants this behavior, but if so, we can have it behave that way.
Probably the best we can do right now is a console warning.

**Comment by SGarcia710** [comment]
> I don't think apple wants this behavior, but if so, we can have it behave that way. Probably the best we can do right now is a console warning.

Based on this issue, is it impossible to have push notifications right now with expo-notifications?

**Comment by vonovak** [comment]
> Based on this issue, is it impossible to have push notifications right now with expo-notifications?

not on simulator; but it's not an issue with expo-notifications, but with iOS. All works as expected on device.

**Comment by SGarcia710** [comment]
> > Based on this issue, is it impossible to have push notifications right now with expo-notifications?
> 
> not on simulator; but it's not an issue with expo-notifications, but with iOS. All works as expected on device.

I am having the issue also on real device. Checking maybe if something is wrong my with setup.

**Comment by SGarcia710** [comment]
> > Based on this issue, is it impossible to have push notifications right now with expo-notifications?
> 
> not on simulator; but it's not an issue with expo-notifications, but with iOS. All works as expected on device.

Hello sir, none of the getToken functions are working on iOS real device.

```
    "react": "19.1.0",
    "react-native": "0.81.1",
    "expo": "54.0.10",
    "expo-constants": "18.0.9",
    "expo-device": "7.1.4",
    "expo-notifications": "0.32.11",
```


Installed expo modules to a already existing project (we are going to start using expo at our company)  But its only working on Android.

iOS is still failing, none of the promises are resolving. Any idea? For example, do i need the additional delegate methods on iOS for push notifications?

**Comment by vonovak** [comment]
hello @SGarcia710  can you please create a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) that we can see the issue with? The most effective reproducible examples are created by starting a new project from scratch and adding in only the necessary pieces to reproduce the issue.
Without this, the issue is not actionable.

**Comment by gitcaracas** [comment]
I still have the same issue, on Android works and I can get the token were as on iOS it just doesnt do anything or resolves, you don't get a catch and with this issue i cannot use push notifications for my app

**Comment by vonovak** [comment]
> I still have the same issue, on iOS it just doesnt do anything

Make sure you use a device, not a simulator

**Comment by Jamsanz** [comment]
I am also facing the same problem and I have gone through all the suggested solutions but the only thing that seems to work is downgrading expo-notifications to expo-notifications: 0.29.13

**Comment by IanMolldrem** [comment]
Bumping this issue @vonovak -

I'm aware that someone in this thread reported this issue as simulator-only, but it's also affecting physical iOS devices (including iOS 18 runtimes).

The [shared workaround](https://github.com/expo/expo/issues/37516#issuecomment-2990608031) (registering a token listener before calling `getDevicePushTokenAsync`) is working for me.

I think this indicates that retrieving the push token on devices _and_ simulators is possible, but some kind of regression in `expo-notifications` is present.

Let me know if a minimally reproducible example is still needed.

**Comment by vonovak** [comment]
> Bumping this issue @vonovak -
> 
> Let me know if a minimally reproducible example is still needed.

Hello,
Thanks for commenting. Yes, a minimal reproducer is needed (as with any issue) and wasn't provided thus far.

Thank you! 👍

**Comment by LucaL1fe** [comment]
Hey, I just want to confirm, that I although have this problem on a physical iphoneXS with a expo dev build. Android works like charm.  (Sorry for not providing a minimal Example)

although I can cofirm that:

```
useEffect(() => {
		const tokenListener = Notifications.addPushTokenListener(token => {
			console.log(token);
		})

		return () => {
			if (tokenListener) {
				tokenListener.remove()
			}
		}
	}, [])
```
(thanks @jesulonimii)

is fixing the issue for me...

**Comment by IanMolldrem** [comment]
I've found the root cause for this. Versions `0.30.0` -> `0.32.4` (inclusive) are affected. For the affected versions:

1. `PushTokenModule`'s `getDevicePushTokenAsync` is correctly invoking `registerForRemoteNotifications`.
2. `NotificationsAppDelegateSubscriber` is correctly receiving the `deviceToken` and delegating to `NotificationCenterManager`.
3. `NotificationCenterManager` calls `didRegister` on each of its delegates, **_but `PushTokenModule` is not a member of the delegates array, so the `getDevicePushTokenAsync` promise never resolves._**

**This issue was introduced with this commit:**
https://github.com/expo/expo/commit/a729e1ad7436c2fa07bb7c59f71964b8eebde912#diff-603ca1beade648e82582b1c2dfc95e0ff3f4ce62c1f4e65d6ad0f0f0de9a33d5R18

**This issue was fixed in `expo-notifications` `0.32.5` with this commit:**
https://github.com/expo/expo/commit/ea56b02f2c1214a8cbc248003f313742ea82d9dc#diff-603ca1beade648e82582b1c2dfc95e0ff3f4ce62c1f4e65d6ad0f0f0de9a33d5R17-R21

@vonovak, given this is not an iOS issue, it affects both physical and virtual devices, and push notifications work on simulators/emulators, it seems best to remove the recently added sim warning from `getDevicePushTokenAsync`, in addition to removing the recently added documentation note around PNs requiring physical devices.

Separately, would it be possible to port the `onCreate`/`onDestroy` patch from [this commit](https://github.com/expo/expo/commit/ea56b02f2c1214a8cbc248003f313742ea82d9dc#diff-603ca1beade648e82582b1c2dfc95e0ff3f4ce62c1f4e65d6ad0f0f0de9a33d5R17-R21) to versions `0.30.0` -> `0.32.4`?

I don't think a minimally reproducible example is necessary here, but it'd simply be codegen'ing a project using versions `0.30.0` -> `0.32.4` of this package.

**Comment by vonovak** [comment]
@IanMolldrem thanks for your comment.

> Separately, would it be possible to port the onCreate/onDestroy patch from [this commit](https://github.com/expo/expo/commit/ea56b02f2c1214a8cbc248003f313742ea82d9dc#diff-603ca1beade648e82582b1c2dfc95e0ff3f4ce62c1f4e65d6ad0f0f0de9a33d5R17-R21) to versions 0.30.0 -> 0.32.4?

It has already happened - as you noted, the bug is fixed from 0.32.5 onward. It's not possible to change a version once it was released.


> it seems best to remove the recently added sim warning from getDevicePushTokenAsync, in addition to removing the recently added documentation note around PNs requiring physical devices.

The warning is still valid, and we recommend to use physical devices to test push notification because there are good reasons for that - such as the inability to obtain push token on iOS simulator, and similar issues on Android emulators, depending on what kind of emulator you use. By using a real device you avoid this entire class of problems.

Thank you

**Comment by JustJoostNL** [comment]
> [@vonovak](https://github.com/vonovak), given this is not an iOS issue, it affects both physical and virtual devices...

Just saying that on `0.32.5` it still does not work for simulators, **and it is an iOS issue**.
See: https://developer.apple.com/forums/thread/795433

**Comment by IanMolldrem** [comment]
I'll spin back to test this on an iOS 26.1 simulator once they're available (next week). It seems likes this is unintended behavior, similar to the [iOS 18.4 issue](https://developer.apple.com/forums/thread/777999) which caused all kinds of networking failures.

**Comment by LucaL1fe** [comment]
npx expo install expo-notifications@~0.32.12

I updated from ~0.31.4 to ~0.32.12

For me the version upgrade fixed it 🥳

Thanks guys!

**Comment by Jeremytetu** [comment]
@LucaL1fe I also updated to ~0.32.12 but it still doesn't work for me. 
getExpoPushTokenAsync with expo 54 gives no response... 

You used it like that ?
```
useEffect(() => {
		const tokenListener = Notifications.addPushTokenListener(token => {
			console.log(token);
		})

		return () => {
			tokenListener.remove()
		}
	}, [])
```

**Comment by Andrew-Chen-Wang** [comment]
I've upgraded to the latest and tried the workaround, but nothing works:/ This only affects my device, not simulator.

**Comment by mohmmd-ishtiaq** [comment]
Same issue with:

ExpoSDK: 54 
expo-notification: 0.32.12

**Comment by LucaL1fe** [comment]
@Jeremytetu After the version update (and rebuild) there is no need for the workaround anymore. For me it works now perfectly with just: 

```
	const tokenData = await Notifications.getExpoPushTokenAsync({
        projectId: projectId,
      });
```
Just wanna mention I am on Expo53 not 54

**Comment by Andrew-Chen-Wang** [comment]
idk how I missed this, but someone already figured out my issue:

https://github.com/expo/expo/issues/37516#issuecomment-3237608142

On a physical device, you must request permission before running `await Notifications.getDevicePushTokenAsync` otherwise you'll get stuck. However, if you run on a simulator, you don't need to request permission. Regardless if you permit/deny permission, you'll be able to resolve the token.

I'm on Expo 54, expo-notifications 0.32.13

As a note, this works fine on production, testflight, and the simulator, just not on real device testing with Xcode in development

**Comment by JustJoostNL** [comment]
@vonovak The issue has been resolved for simulators with iOS 26.1. 

Can you remove this warning again?
`WARN  🟡 expo-notifications: obtaining a push token may not work on iOS simulators due to an iOS issue. To obtain a push token, use a real device. Read more: https://developer.apple.com/forums/thread/795433`

**Comment by vonovak** [comment]
@JustJoostNL let's not remove the warning altogether, people still might use iOS 26.0 simulator. The best course of action is that we show the warning conditionally only for the affected simulator runtimes. Would you be willing to open a PR for that? Thank you!

**Comment by JustJoostNL** [comment]
Yeah I am open for that! I'll see if I can find some time this week.

**Comment by Jeremytetu** [comment]
@Andrew-Chen-Wang thanks for trying to help !
but unfortunately this is what I do but still do not work. 

here is my code 

```
    const existing = await Notifications.getPermissionsAsync();
    let finalStatus = existing.status;

    if (finalStatus !== 'granted') {
      const req = await Notifications.requestPermissionsAsync();
      finalStatus = req.status;
    }
    if (finalStatus !== 'granted') {
      // Permissions refusées - log l'erreur
      await trace(uid, { step: 'perm:denied', status: finalStatus });
      return null;
    }

    // Device UUID (stable par device)
    deviceUUID = await getPersistentDeviceUUID();

    const projectId = "XXXXXX";

    Notifications.getExpoPushTokenAsync(projectId ? { projectId } : undefined),
```

Do you see anything wrong with?
Could you show yours ? please...

**Comment by Andrew-Chen-Wang** [comment]
@Jeremytetu you should use expo-device and then run an if statement like (Im on my phone so adjust since I might get the function name wrong)

```
if (Device.isDevice && __DEV__)  { await Notifications.requestPermissionsAsync() }
```

You only need to run this in DEV mode because it works in production (including testflight) just fine.

**Comment by Jeremytetu** [comment]
@Andrew-Chen-Wang but my issue is in production ^^' 
Got a timeout on my iPhone in production

**Comment by rodperottoni** [comment]
Update: the issue seems to be back in iOS 26.2 Simulators.

**Comment by JustJoostNL** [comment]
@rodperottoni seems to work perfectly fine here on iOS 26.2 simulators for me.

**Comment by lww** [comment]
Still having this issue on older devices. iPhone 12 doesn't work, newer generations return the token without any issues.

**Comment by LucaL1fe** [comment]
Back again... Maybe a different perspective. For me its working on my dev build and not on my production build. So maybe there is underlying config issue...

**Comment by tvillafane** [comment]
Setup:

- iOS 18.7.3
- iPhone Xr
- expo 53.0.25
- expo-notifications 0.32.12

This works on the real device described above.  **Upgrading to 0.32.4 did not work**. @IanMolldrem @LucaL1fe 

EDIT: this only worked on a local build, a testflight build saw the same issue.
EDIT AGAIN: make sure you have the 'expo-notifications' plugin config in app.json -> 52 didn't require it explicitly but 53 did!  

Here is the final snippet that worked for me:
```useEffect(() => {
    registerForPushNotifications().then((token) => {
      dispatch(UserSlice.registerNotificationToken({userId: user.userId, token: token}))
    }).then(() => {
      dispatch(log({ 
        message: `...`
      }))
    }).catch((e) => {
      if (Device.isDevice) {
        dispatch(log({ 
          message: `...`,
          level: LOG_LEVEL['ERROR'] 
        }))
      }
    })
  }, [])```


```
  "expo": "~53.0.27",
   "react": "19.0.0",
    "react-native": "0.79.6",
   "expo-notifications": "~0.31.5",
```
