### ISSUE TITLE
expo-image not retrieving images from cache in bare workflow

### ISSUE THREAD

**Issue by AppKidd** [expo/expo#37705]
### Minimal reproducible example

https://github.com/AppKidd/expo-image-caching-bug

### Steps to reproduce

```
npm install
npx expo run:ios
```
`onLoad` always returns with `cacheType: none`, despite `Image.getCachePathAsync` confirming the image exists in the cache. Works as expected when using Expo Go.

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: macOS 14.7.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 4.9.1 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 10.2.5 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.13 => 53.0.13 
      react: 19.0.0 => 19.0.0 
      react-native: 0.79.4 => 0.79.4 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✖ Check for app config fields that may not be synced in a non-CNG project

Issue only exists in native installation.
```

**Comment by corelli18512** [comment]
Facing the same issue here. Tested on some versions -- seems like cache is not working as expected since 2.2.0 if this helps debugging

**Comment by osmant** [comment]
Could you please try setting blurRadius={0.001}? 0.001 is just a tiny value to keep the image almost identical to the original. I’m not saying this is the solution, but from my experience, caching seems to only work if some kind of transformation is applied to the image.

I actually confirmed this by reading the source code of expo-image. It looks like expo-image does not properly utilize the caching infrastructure of the underlying SDWebImage library, which is likely why this issue occurs. If I get the chance, I’m considering opening a pull request to address it.

**Comment by AppKidd** [comment]
> Could you please try setting blurRadius={0.001}? 0.001 is just a tiny value to keep the image almost identical to the original. I’m not saying this is the solution, but from my experience, caching seems to only work if some kind of transformation is applied to the image.
> 
> I actually confirmed this by reading the source code of expo-image. It looks like expo-image does not properly utilize the caching infrastructure of the underlying SDWebImage library, which is likely why this issue occurs. If I get the chance, I’m considering opening a pull request to address it.

Thanks a lot for digging into the source. You were right – setting any blur radius value does mean that the image correctly loads from the cache.

**Comment by IhsotasTon** [comment]
same here, android working well, ios not cache (- -)

**Comment by chrislgrigg** [comment]
Looks like it's fixed in 2.3.2, thank you @jakex7!

**Comment by ahmadgabariin** [comment]
@IhsotasTon 
It is not fixed, without blurRadius {0.001}, the caching not loaded

**Comment by corelli18512** [comment]
> [@IhsotasTon](https://github.com/IhsotasTon) It is not fixed, without blurRadius {0.001}, the caching not loaded

jakex7's PR fixed the issue for me. Have you tried updating to 2.3.2?

**Comment by ahmadgabariin** [comment]
@Corelli-18512 
It is 2.3.2, but if I remove the blurRadius, it will not load from cache, and newArchitecture is false in my project.

**Comment by iankberry** [comment]
Can also confirm that if I set the blur radius in 2.3.2, caching works fine. If I remove it, caching no longer works.

**Comment by jakex7** [comment]
@ahmadgabariin @iankberry 
I've just confirmed, using the reproduction from this issue, that it's working as expected in version 2.3.2. If you still encounter any problems with cache, please open a new issue and include a reproduction that clearly demonstrates the problem.

**Comment by iankberry** [comment]
@jakex7 Thanks for checking. The repro example in this issue does appear to work for me. That is, it shows the cache path correctly even without `blurRadius`. However the loading behavior still appears to bypass the cache and load the image from the remote URL.

If I add an `onLoad` handler to the image and log out the event object, I see the following with a blur radius:
```json
{"cacheType": "disk", "source": {"height": 256, "isAnimated": false, "mediaType": null, "url": "https://models.easeup.app/avatar-render.png", "width": 256}, "target": 7498}
```

And without the blur radius:
```json
{"cacheType": "none", "source": {"height": 256, "isAnimated": false, "mediaType": null, "url": "https://models.easeup.app/avatar-render.png", "width": 256}, "target": 6698}
```
