### ISSUE TITLE
IOS Video Permission Issue: The file couldn’t be opened because you don’t have permission to view it.

### ISSUE THREAD

**Issue by yaodebian** [expo/expo#38879]
### Minimal reproducible example

https://github.com/yaodebian/video-permission-issue-example

### Steps to reproduce

<img src="https://github.com/yaodebian/video-permission-issue-example/blob/main/assets/images/IMG_0133.PNG?raw=true" width="300" /><img src="https://github.com/yaodebian/video-permission-issue-example/blob/main/assets/images/IMG_0134.PNG?raw=true" width="300" />

### Prerequisites

1. Use a real device instead of a simulator, simulator work success. And ensure you have videos in your device's photo library. My device is iOS 18.5 (iPhone 11 Pro).
2. Install dependencies:
   ```bash
   npm install
   # or
   pnpm install
   ```

### Reproduction Steps

1. **Start the application**:
   ```bash
   npm run start
   # or
   pnpm start
   ```

2. **Open the app** on your iOS device or simulator

3. **Grant permissions** when prompted for media library access

4. **Tap "Select Video from Library"** button
   - The app will request media library permissions (should be granted)
   - A list of videos will be displayed
   - **Expected**: Video thumbnails should generate successfully
   - **Actual**: Video thumbnails fail with permission errors (⚠️ indicators shown)

5. **Select a video** from the list
   - Tap on any video to select it
   - Tap "Play Video (Will Show Permission Error)" button
   - **Expected**: Video should play normally
   - **Actual**: Video playback fails with permission error

### Environment

```text
expo-env-info 1.3.4 environment info:
    System:
      OS: macOS 15.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.19.3 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.8.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.5, iOS 18.5, macOS 15.5, tvOS 18.5, visionOS 2.5, watchOS 11.5
    IDEs:
      Xcode: 16.4/16F6 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.20 => 53.0.20 
      expo-router: ~5.1.4 => 5.1.4 
      react: 19.0.0 => 19.0.0 
      react-native: 0.79.5 => 0.79.5 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

**Comment by behenate** [comment]
Most likely related to https://github.com/expo/expo/issues/36218

**Comment by yaodebian** [comment]
> Most likely related to [#36218](https://github.com/expo/expo/issues/36218)

Thanks for your reply. I think it might be the same problem. I just tried some of the methods in the issue you posted, but they didn't work. I'll try other methods later.

**Comment by yaodebian** [comment]
There is a way to solve the problem, which is to back up the video to the app album, but this method consumes too much performance.

**Comment by florian-deroo** [comment]
> Most likely related to [#36218](https://github.com/expo/expo/issues/36218)

related to:
https://github.com/expo/expo/issues/36218
https://github.com/expo/expo/issues/31857
https://github.com/expo/expo/issues/31620

**Comment by behenate** [comment]
Thanks for reporting the issue! The PR above should fix it. We should land it into SDK 54, which should be published very soon.

**Comment by branaust** [comment]
I'm still receiving a similar issue when trying to display a video thumbnail:

```
import { Pressable, Image, View, StyleSheet, Platform } from 'react-native';
import { Spacing } from '@/src/components/design-system/constants/Spacing';
import { Colors } from '@/src/components/design-system/constants/Colors';
import { useState, useCallback } from 'react';
import { useFocusEffect } from '@react-navigation/native';
import * as MediaLibrary from 'expo-media-library';
import * as VideoThumbnails from 'expo-video-thumbnails';
import useCameraActions from './useCameraActions';

export function CameraRollButton() {
  const { chooseImage } = useCameraActions();
  const [thumbnailUri, setThumbnailUri] = useState<string | null>(null);

  useFocusEffect(
    useCallback(() => {
      const loadLatestThumbnail = async () => {
        setThumbnailUri(null);

        const { status } = await MediaLibrary.requestPermissionsAsync();
        if (status !== 'granted') {
          return;
        }

        console.log({ status });

        const { assets } = await MediaLibrary.getAssetsAsync({
          first: 1,
          mediaType: [MediaLibrary.MediaType.video],
          sortBy: [[MediaLibrary.SortBy.creationTime, false]],
        });

        if (assets.length === 0) {
          return;
        }

        const asset = assets[0];

        let uriToUse = asset.uri;

        console.log({ uriToUse });

        // Try to get a local file URI (sometimes available on iOS after access)
        if (Platform.OS === 'ios') {
          try {
            const info = await MediaLibrary.getAssetInfoAsync(asset);
            if (info.localUri) {
              uriToUse = info.localUri;
            }
          } catch (e) {
            console.warn('Failed to get asset info on iOS', e);
          }
        }

        // Only attempt thumbnail generation if we have a usable URI
        // (Android works with content:// or file://, iOS only if localUri available)
        if (uriToUse) {
          try {
            const { uri: thumbUri } = await VideoThumbnails.getThumbnailAsync(
              uriToUse,
              {
                time: 2000,
              },
            );
            setThumbnailUri(thumbUri);
          } catch (e) {
            console.warn('Failed to generate video thumbnail', e);
            setThumbnailUri(null);
          }
        }
      };

      loadLatestThumbnail();
    }, []),
  );

  return (
    <Pressable style={styles.container} onPress={chooseImage}>
      {thumbnailUri ? (
        <Image
          source={{ uri: thumbnailUri }}
          style={StyleSheet.absoluteFillObject}
          resizeMode="cover"
        />
      ) : (
        // Darker gray fallback to feel more "video-like"
        <View style={styles.fallbackBackground} />
      )}
    </Pressable>
  );
}

const styles = StyleSheet.create({
  container: {
    width: Spacing.S8,
    height: Spacing.S8,
    borderRadius: Spacing.S3,
    backgroundColor: Colors.dark['gray'], // kept as base
    overflow: 'hidden',
  },
  fallbackBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.6)', // darker overlay for fallback
  },
  durationOverlay: {
    position: 'absolute',
    bottom: Spacing.S1,
    right: Spacing.S1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: Spacing.S1,
    paddingVertical: 2,
    borderRadius: 4,
  },
  durationText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '600',
  },
});
```

 LOG  {"status": "granted"}
 LOG  {"uriToUse": "ph://2548AFB1-E114-4216-9568-F18836859529/L0/001"}
 WARN  Failed to generate video thumbnail [Error: The file couldn’t be opened because you don’t have permission to view it.]

Expo SDK 55 but was failing on SDK 54 as well.

works on simulator but not on physical devices

**Comment by behenate** [comment]
@branaust Can you try on SDK 55 [**without**](https://docs.expo.dev/versions/v55.0.0/sdk/video/#playing-media-from-the-media-library:~:text=On%20iOS%20make,read%20the%20asset.) using the `localUri` property?
