### ISSUE TITLE
[SDK 54 Beta] TypeScript errors in newly created project

### ISSUE THREAD

**Issue by sultanmyrza** [expo/expo#39096]
## Description

A newly created project with Expo SDK 54 contains TypeScript errors. While `npx expo start` works without problems, the newly scaffolded project has TypeScript errors that are misleading and interfere with vibecoding.

| Screenshot 1 | Screenshot 2 | Screenshot 3 |
|---|---|---|
| <img width="400" alt="TypeScript Error 1" src="https://github.com/user-attachments/assets/894f117c-a127-4f63-99cf-56bcc4844c5e" /> | <img width="400" alt="TypeScript Error 2" src="https://github.com/user-attachments/assets/c054b016-e682-49f1-8073-5c9ed6b5edaf" /> | <img width="400" alt="TypeScript Error 3" src="https://github.com/user-attachments/assets/06ef159e-d153-45cf-be14-51bbfae2ba33" /> |

## TypeScript Errors

```log
Type '{ children: Element[]; style: { flexDirection: "row"; alignItems: "center"; gap: number; }; }' is not assignable to type 'IntrinsicAttributes & ViewProps & { lightColor?: string | undefined; darkColor?: string | undefined; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & ViewProps & { lightColor?: string | undefined; darkColor?: string | undefined; }'.
```

```log
Type '{ children: string; type: "title"; }' is not assignable to type 'IntrinsicAttributes & TextProps & { lightColor?: string | undefined; darkColor?: string | undefined; type?: "link" | "title" | "default" | "defaultSemiBold" | "subtitle" | undefined; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & TextProps & { lightColor?: string | undefined; darkColor?: string | undefined; type?: "link" | "title" | "default" | "defaultSemiBold" | "subtitle" | undefined; }'.
```

```log
Property 'style' does not exist on type 'ThemedViewProps'.
```

```log
Type '{ children: Element[]; style: { flexDirection: "row"; alignItems: "center"; gap: number; }; }' is not assignable to type 'IntrinsicAttributes & ViewProps & { lightColor?: string | undefined; darkColor?: string | undefined; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & ViewProps & { lightColor?: string | undefined; darkColor?: string | undefined; }'.ts(2322)
  ```

## Steps to Reproduce

1. Create a new project with Expo SDK 54 beta:
   ```bash
   yarn create expo-app --template default@next
   ```
2. Open the project with VSCode/Cursor
3. Observe TypeScript errors in the editor

## Expected Behavior

A newly created Expo project should not have TypeScript errors.

<details><summary>System Information</summary>

```
System:
  OS: macOS 26.0
  CPU: (8) arm64 Apple M1 Pro
  Memory: 159.23 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
  Xcode: 26.0 (Build version 17A5285i)
Binaries:
  Node: 22.18.0 - ~/.nvm/versions/node/v22.18.0/bin/node
  Yarn: 4.9.2 - ~/.nvm/versions/node/v22.18.0/bin/yarn
  npm: 10.9.3 - ~/.nvm/versions/node/v22.18.0/bin/npm
  pnpm: 10.14.0 - ~/.nvm/versions/node/v22.18.0/bin/pnpm
```

</details>

**Comment by usa709325-eng** [comment]
I want fix my problem can you do it

**Comment by YasinAkimura** [comment]
can confirm somehow only react-native-web types are loaded if I dive into it
My current fix is patching types in expo folder and remove react-native-web.d.ts

**Comment by OkuraKenG** [comment]
+1 I am having this problem too. What I will say is that `54.0.0-preview.4` worked fine but updating to `54.0.0-preview.5` or above introduced this issue. I'm thinking it's related to this: https://github.com/expo/expo/pull/39018 "Enable react-native-strict-api TS typings condition by default"

I'm having this problem with NativeWind, but same errors. 

## Investigated a bit
And yeah, applying this patch, reverting the above PR does supress the issues that you mention:
```diff
diff --git a/node_modules/expo/tsconfig.base.json b/node_modules/expo/tsconfig.base.json
index 7b5abf3..8ac4697 100644
--- a/node_modules/expo/tsconfig.base.json
+++ b/node_modules/expo/tsconfig.base.json
@@ -10,7 +10,7 @@
     "module": "preserve",
     "moduleDetection": "force",
     "moduleResolution": "bundler",
-    "customConditions": ["react-native-strict-api", "react-native"],
+    "customConditions": ["react-native"],
     "noEmit": true,
     "resolveJsonModule": true,
     "skipLibCheck": true,
```

To be clear, this probally isn't the right solution, but just sharing this as it might point to that PR introducing the errors.

From what I understand this is something that NativeWind or alike has to fix, but not sure.

**Comment by aleclarson** [comment]
The problem is that `expo/types/react-native-web.d.ts` uses `declare module 'react-native'` and assumes that `ViewProps`, `TextProps`, etc are `interface` types (which allow declaration merging). But with the new "generated types" (resolved with the custom `react-native-strict-api` condition as @OkuraKenG found), `ViewProps` et al are declared as type aliases.

#### Example of problematic type definition

https://github.com/expo/expo/blob/a5cb2d5d8fe16781c95e5577c2660610d3e98a98/packages/expo/types/react-native-web.d.ts#L4-L10

#### Example of new generated types in `react-native/types_generated`

https://github.com/aleclarson/expo/blob/683f0c72a51815223da177f83578a8cf1cb46af1/Libraries/Components/View/ViewPropTypes.d.ts#L435

**Comment by umardev500** [comment]
> +1 I am having this problem too. What I will say is that `54.0.0-preview.4` worked fine but updating to `54.0.0-preview.5` or above introduced this issue. I'm thinking it's related to this: [#39018](https://github.com/expo/expo/pull/39018) "Enable react-native-strict-api TS typings condition by default"
> 
> I'm having this problem with NativeWind, but same errors.
> 
> ## Investigated a bit
> And yeah, applying this patch, reverting the above PR does supress the issues that you mention:
> 
> diff --git a/node_modules/expo/tsconfig.base.json b/node_modules/expo/tsconfig.base.json
> index 7b5abf3..8ac4697 100644
> --- a/node_modules/expo/tsconfig.base.json
> +++ b/node_modules/expo/tsconfig.base.json
> @@ -10,7 +10,7 @@
>      "module": "preserve",
>      "moduleDetection": "force",
>      "moduleResolution": "bundler",
> -    "customConditions": ["react-native-strict-api", "react-native"],
> +    "customConditions": ["react-native"],
>      "noEmit": true,
>      "resolveJsonModule": true,
>      "skipLibCheck": true,
> To be clear, this probally isn't the right solution, but just sharing this as it might point to that PR introducing the errors.
> 
> From what I understand this is something that NativeWind or alike has to fix, but not sure.

Thanks solved

**Comment by markmccoid** [comment]
I was having an issue with the Nativewind install and "className" showing TypeScript errors. 

I found that modifying the expo/tsconfig.base.json and removing the "react-native-strict-api" as mentioned above fixed that issue.

**Comment by OkuraKenG** [comment]
I think Expo team reverted that PR looking at this commit: https://github.com/expo/expo/commit/2fd78719d288ef9792e0a4d24377ba603c5429e6 so the latest beta should resolve this issue as of today (August 25th). Switched to latest beta and not having any issues. 

(Thank you @brentvatne)

**Comment by brentvatne** [comment]
indeed @OkuraKenG! we decided to roll back the react-native-strict-api changes. this should resolve the issues reported here.

**Comment by charles4221** [comment]
@brentvatne I am using the non-beta current stable release of Expo `54.0.20` and React Native `0.81.5` and still having this exact issue. 

Expo types overriding `ViewProps`:
<img width="643" height="202" alt="Image" src="https://github.com/user-attachments/assets/df9343e9-3469-4752-bc20-29386ecb2023" />

Generated React Native types where `ViewProps` is a `type` not an `interface`:
<img width="707" height="156" alt="Image" src="https://github.com/user-attachments/assets/906cecc1-7b82-41d6-81a6-de49f291fb86" />

Example component using `ViewProps` but unable to use `children` or `style` because they "don't exist", because TypeScript thinks `ViewProps` only contains `className`

<img width="1049" height="290" alt="Image" src="https://github.com/user-attachments/assets/a26eb465-56b3-4b66-a8a8-7bc80bf4a851" />
