### ISSUE TITLE
Android app crashes with ClassNotFoundException for FileSystemFileProvider on startup

### ISSUE THREAD

**Issue by sebasbeleno** [expo/expo#39622]
### Minimal reproducible example

https://github.com/sebasbeleno/expo-filesystem-issue

### Steps to reproduce

- Create a new Expo project or use existing project with expo-file-system dependency
- Install dependencies: `npm install`
- Prebuild the app `npx expo prebuild --clean`
- Run the app on Android with development build: `npm run android`
- App crashes immediately on startup before reaching the main screen

# Relevant Logcat Data

App Package: com.sebasbeleno15.expofilesystemissue
Process ID: 4538
Timestamp: 09-12 19:48:16.714

## Main Error:

```console
09-12 19:48:16.714  4538  4538 E AndroidRuntime: FATAL EXCEPTION: main
09-12 19:48:16.714  4538  4538 E AndroidRuntime: Process: com.sebasbeleno15.expofilesystemissue, PID: 4538
09-12 19:48:16.714  4538  4538 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider expo.modules.filesystem.FileSystemFileProvider: java.lang.ClassNotFoundException: Didn't find class "expo.modules.filesystem.FileSystemFileProvider" on path: DexPathList[[zip file "/data/app/~~jao_jckRBoDRTiuUWNcOqA==/com.sebasbeleno15.expofilesystemissue-PWrlCkAPzejBxU4wkzL-wA==/base.apk"],nativeLibraryDirectories=[/data/app/~~jao_jckRBoDRTiuUWNcOqA==/com.sebasbeleno15.expofilesystemissue-PWrlCkAPzejBxU4wkzL-wA==/lib/x86_64, /data/app/~~jao_jckRBoDRTiuUWNcOqA==/com.sebasbeleno15.expofilesystemissue-PWrlCkAPzejBxU4wkzL-wA==/base.apk!/lib/x86_64, /system/lib64, /system/product/lib64]]
09-12 19:48:16.714  4538  4538 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7770)
09-12 19:48:16.714  4538  4538 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7276)
09-12 19:48:16.714  4538  4538 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6983)
09-12 19:48:16.714  4538  4538 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "expo.modules.filesystem.FileSystemFileProvider" on path: DexPathList[[zip file "/data/app/~~jao_jckRBoDRTiuUWNcOqA==/com.sebasbeleno15.expofilesystemissue-PWrlCkAPzejBxU4wkzL-wA==/base.apk"],nativeLibraryDirectories=[/data/app/~~jao_jckRBoDRTiuUWNcOqA==/com.sebasbeleno15.expofilesystemissue-PWrlCkAPzejBxU4wkzL-wA==/lib/x86_64, /data/app/~~jao_jckRBoDRTiuUWNcOqA==/com.sebasbeleno15.expofilesystemissue-PWrlCkAPzejBxU4wkzL-wA==/base.apk!/lib/x86_64, /system/lib64, /system/product/lib64]]
09-12 19:48:16.714  4538  4538 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
09-12 19:48:16.714  4538  4538 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
09-12 19:48:16.714  4538  4538 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-12 19:48:16.714  4538  4538 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
09-12 19:48:16.714  4538  4538 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:66)
09-12 19:48:16.714  4538  4538 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7754)
```

## Additional Context Lines:
```console
09-12 19:48:16.552  4538  4538 D nativeloader: Configuring clns-6 for other apk /data/app/~~jao_jckRBoDRTiuUWNcOqA==/com.sebasbeleno15.expofilesystemissue-PWrlCkAPzejBxU4wkzL-wA==/base.apk. target_sdk_version=36
09-12 19:48:16.711  4538  4538 D AndroidRuntime: Shutting down VM
09-12 19:48:16.719   839  4117 W ActivityTaskManager:   Force finishing activity com.sebasbeleno15.expofilesystemissue/.MainActivity
```

### Environment

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: Linux 6.14 Ubuntu 24.04.3 LTS 24.04.3 LTS (Noble Numbat)
      Shell: 5.2.21 - /bin/bash
    Binaries:
      Node: 23.10.0 - ~/.nvm/versions/node/v23.10.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v23.10.0/bin/yarn
      npm: 10.9.2 - ~/.nvm/versions/node/v23.10.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 35, 36
        Build Tools: 27.0.1, 34.0.0, 35.0.0, 35.0.1, 36.0.0, 36.1.0
        System Images: android-33 | Google APIs Intel x86_64 Atom, android-34 | Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom
    npmPackages:
      expo: ~54.0.3 => 54.0.3 
      react: 19.1.0 => 19.1.0 
      react-native: 0.81.4 => 0.81.4 
    npmGlobalPackages:
      eas-cli: 16.18.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
npx expo-doctor@latest
17/17 checks passed. No issues detected!
```

**Comment by Hazer** [comment]
Just made a comment here about the same error: https://github.com/expo/expo/issues/39056#issuecomment-3286668451

**Comment by sebasbeleno** [comment]
We're experiencing the same behavior on iOS as well. The app crashes during startup

**Comment by toadums** [comment]
> Just made a comment here about the same error: [#39056 (comment)](https://github.com/expo/expo/issues/39056#issuecomment-3286668451)

Thanks for posting @Hazer! I'm not using `expo-file-system` in my app (didn't have it installed previous to this issue coming up), but **installing `@19.0.12` gets android working**.

As of yesterday afternoon Android was working fine (`expo @54.0.1`, `expo-file-system @19.0.11`), but as of today the `expo-file-system` version got bumped up to `19.0.13`

**Comment by Hazer** [comment]
> We're experiencing the same behavior on iOS as well. The app crashes during startup

@sebasbeleno I'm inclined to think the iOS startup crash you're facing, is another issue, our iOS runs at the moment with 54.0.4 + 19.0.13, we currently are having only this issue with Android, and a few with Storybook RN Web, almost everything else is working, for now at least...

**Comment by joshmohrer** [comment]
Also experiencing this on 54.0.4 on Android only, works fine on iOS.

**Comment by brentvatne** [comment]
i published expo-file-system@19.0.14 which reverts https://github.com/expo/expo/pull/39134 and resolves this

> We're experiencing the same behavior on iOS as well. The app crashes during startup

i believe this is a different issue. probably related to https://github.com/expo/expo/issues/39597 which was resolved https://github.com/expo/expo/issues/39597#issuecomment-3287125182

**Comment by sebasbeleno** [comment]
Working with expo 54.0.7! Thanks @brentvatne for the quick response!

**Comment by davidwinograd1** [comment]
hm I just upgraded to expo 54.0.7. using "expo-file-system": "~19.0.14". but I still get the same error. @brentvatne ?
