### ISSUE TITLE
[SDK 54] Expo Devtools plugins not showing up in older project

### ISSUE THREAD

**Issue by sainjay** [expo/expo#39767]
### Minimal reproducible example

https://github.com/sainjay/expo54-testapp

### Steps to reproduce

Updated an Older project from Expo 53 and now Devtools plugins are not showing under `more tools`(shift+m)

<img width="460" height="92" alt="Image" src="https://github.com/user-attachments/assets/ca835776-9bf9-45d4-9d40-f33676180f66" />

created a new SDK 54 project but the devtools are showing up fine in there. Any ideas what could be going wrong with older project being updated?

<img width="466" height="97" alt="Image" src="https://github.com/user-attachments/assets/857b2688-de53-42dd-9f44-8ed8f7a4f8df" />

### Environment

```text
from older project:

 expo-env-info 2.0.7 environment info:
    System:
      OS: macOS 26.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.19.5 - ~/.nvm/versions/node/v20.19.5/bin/node
      npm: 10.8.2 - ~/.nvm/versions/node/v20.19.5/bin/npm
      Watchman: 2025.05.19.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.0, iOS 26.0, macOS 26.0, tvOS 26.0, visionOS 26.0, watchOS 26.0
      Android SDK:
        API Levels: 28, 31, 32, 33, 34, 35, 36
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0, 36.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2025.1 AI-251.26094.121.2513.14007798
      Xcode: 26.0/17A324 - /usr/bin/xcodebuild
    npmPackages:
      expo: 54.0.7 => 54.0.7 
      expo-router: ~6.0.4 => 6.0.4 
      react: 19.1.0 => 19.1.0 
      react-dom: 19.1.0 => 19.1.0 
      react-native: 0.81.4 => 0.81.4 
      react-native-web: ^0.21.0 => 0.21.1 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
from older project

12/17 checks passed. 5 checks failed. Possible issues detected:
Use the --verbose flag to see more details about passed checks.

✖ Check for lock file
Multiple lock files detected (package-lock.json, bun.lock). This may result in unexpected behavior in CI environments, such as EAS Build, which infer the package manager from the lock file.
Advice:
Remove any lock files for package managers you are not using.

✖ Check that required peer dependencies are installed
Missing peer dependency: @expo/metro-runtime
Required by: expo-router
Missing peer dependency: expo-constants
Required by: expo-router
Advice:
Install missing required peer dependencies with "npx expo install @expo/metro-runtime expo-constants"
Your app may crash outside of Expo Go without these dependencies. Native module peer dependencies must be installed directly.

✖ Check that packages match versions required by installed Expo SDK

🔧 Patch version mismatches
package      expected  found   
expo         54.0.8    54.0.7  
expo-router  ~6.0.6    6.0.4
```

**Comment by sainjay** [comment]
Fixed in Expo `54.0.9` or higher. Able to see the dev tools now!

**Comment by lagoasoft-yagosantos** [comment]
For me the problem still even after update to 54.0.9, the `redux-devtools-expo-dev-plugin` option does not appear in the dev tools options in terminal
