### ISSUE TITLE
[iOS][UI] Host component distorts header in iOS 26

### ISSUE THREAD

**Issue by lunchmate1** [expo/expo#40058]
### Minimal reproducible example

check steps to reproduce.

### Steps to reproduce

Host component seems to distort header item glass bounds in iOS 26:

```
export function HeaderRight() {
    return (
        <View style={styles.right}>
            <Host style={{ backgroundColor: "pink" }} matchContents>
                <ContextMenu>
                    <ContextMenu.Trigger>
                        <View accessibilityLabel="filter" hitSlop={{ left: 50, top: 30, bottom: 20 }}>
                            <Ionicons name="filter" size={25} color="label" style={styles.rightIcon} />
                        </View>
                    </ContextMenu.Trigger>
                    <ContextMenu.Items>
                        {menuOptions.map((option, index) =>
                            renderMenuOption(option, index)
                        )}
                    </ContextMenu.Items>
                </ContextMenu>
            </Host>
            <Button animated={Platform.Version !== "26.0"} accessibilityLabel="search" hitSlop={{ right: 50, top: 30, bottom: 20 }}>
                <Ionicons name="search" size={25} color="label" style={styles.rightIcon} />
            </Button>
        </View>
    )
}

const StackPreset: NativeStackNavigationOptions =
    process.env.EXPO_OS !== "ios" ? {}
        : {
            headerShown: true,
            headerTransparent: true,
            headerShadowVisible: Platform.Version === "26.0",
            headerLargeTitleShadowVisible: false,
            headerLargeTitle: false,
            headerBlurEffect: Platform.Version === "26.0" ? "none" : "regular",
            headerBackButtonDisplayMode: Platform.Version === "26.0" ? "minimal" : "default",
            contentStyle: {
                backgroundColor: "transparent",
            },
            headerTitle: HeaderCenter,
            headerRight: HeaderRight,
        }


export default function Layout() {
    return (
        <Stack screenOptions={ContainerStackPreset}>
            <Stack.Screen
                name="index"
                options={StackPreset}
            />
        </Stack>
    );
}
```

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/519d7bc4-1d2a-46b6-ad53-b1b753dacb64" />
<img width="1320" height="2868" alt="Image" src="https://github.com/user-attachments/assets/7ed29918-1eb3-4d35-8873-c65a30981eac" />

### Environment

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: macOS 26.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.19.0 - /usr/local/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.9.3 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.0, iOS 26.0, macOS 26.0, tvOS 26.0, visionOS 26.0, watchOS 26.0
    IDEs:
      Xcode: 26.0.1/17A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~54.0.10 => 54.0.10 
      expo-router: ~6.0.8 => 6.0.8 
      expo-updates: ~29.0.11 => 29.0.11 
      react: 19.1.0 => 19.1.0 
      react-native: 0.81.4 => 0.81.4 
    npmGlobalPackages:
      eas-cli: 16.19.3
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
16/17 checks passed. 1 checks failed. Possible issues detected:
Use the --verbose flag to see more details about passed checks.

✖ Validate packages against React Native Directory package metadata
The following issues were found when validating your dependencies against React Native Directory:
  Untested on New Architecture: react-native-nitro-text
  No metadata available: react-native-nitro-image, react-native-nitro-web-image
Advice:
Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

1 check failed, indicating possible issues with the project.
```

**Comment by intergalacticspacehighway** [comment]
@lunchmate1 can you try patch from this [PR](https://github.com/expo/expo/pull/39693) and let us know if it fixes the issue?

**Comment by lunchmate1** [comment]
@intergalacticspacehighway after a few variations of testing, seems like you're patch worked 👍 Any potential side-affects to this patch?

**Comment by intergalacticspacehighway** [comment]
@lunchmate1 No side-effects so far. In my testing I haven't faced any issues yet. We're going to merge [this soon](https://github.com/expo/expo/pull/40017) which includes that patch.

**Comment by fedeciancaglini** [comment]
@intergalacticspacehighway Hi! I'm experiencing this same issue, and I saw that [this PR](https://github.com/expo/expo/pull/40017) you mentioned just got merged, how could I get my hands on the fix? Should I just wait for the next @expo/ui release? Thanks 🙏

**Comment by intergalacticspacehighway** [comment]
@fedeciancaglini It has been cherry-picked in SDK 54, so it will be released in the next patch release. Meanwhile you can use the file changes in this [PR](https://github.com/expo/expo/pull/39693) by patching and rebuilding. Let us know if you face any issues!

**Comment by davecarlson** [comment]
I've noticed a few artifacts around my app if i use a <Host> - i'll wait for the next release to see if they go away before creating some issues

**Comment by intergalacticspacehighway** [comment]
@davecarlson you faced issues after applying the PR patch?

**Comment by intergalacticspacehighway** [comment]
The fix is released in `@expo/ui@0.2.0-beta.5` and `expo@54.0.11`

**Comment by davecarlson** [comment]
Just checked again, still see artifacts elsewhere with beta-5:

1) Page as expected

<img width="469" height="849" alt="Image" src="https://github.com/user-attachments/assets/bc3dce79-50f7-4d1f-b59d-d6f793ca4555" />

2) Click into about me, select the Title field which pops up a bottom sheet: 
<img width="495" height="1064" alt="Image" src="https://github.com/user-attachments/assets/36073b4b-583e-4a83-bfd1-b8d6f6db9760" />

3) Click back, see artifacts under on a different screen:

<img width="495" height="910" alt="Image" src="https://github.com/user-attachments/assets/a3440218-1a61-4ef5-8565-0aaf44ff2f47" />


Code for the bottom sheet: 
```
 <Host style={{ width, position: "absolute", bottom: 0 }}>
            <BottomSheet
              isOpened={isOpened}
              onIsOpenedChange={(e) => setIsOpened(e)}
            >
<TitleSelector />
</BottomSheet>
</Host>
```

**Comment by 1forh** [comment]
> The fix is released in `@expo/ui@0.2.0-beta.5` and `expo@54.0.11`

niiice, works for me!

**Comment by intergalacticspacehighway** [comment]
@davecarlson can you try this snippet. I think the artifact you're seeing is just the Host component staying mounted. 

```jsx
 {isOpened ? (
        <Host style={{ position: 'absolute', width }}>
          <BottomSheet
            isOpened={isOpened}
            onIsOpenedChange={setIsOpened}>
          <TitleSelector />
          </BottomSheet>
        </Host>
      ) : null}
```

If above does not work, it would be helpful if you can open a new issue with a minimal repro for bottomsheet. I will close this issue now since it was related to Screens header.

**Comment by joacub** [comment]
this still hapenning

**Comment by gobhi** [comment]
stil happening

**Comment by noahc1510** [comment]
+1 

I found this error in "expo": "~54.0.30" again. Has this problem been fixed with headerRightItems?


https://github.com/expo/expo/pull/39693#issuecomment-3765403171
