### ISSUE TITLE
[android][expo-image-picker] aunchImageLibraryAsync On the photo editing screen, the action button section is blurred.

### ISSUE THREAD

**Issue by ducdac** [expo/expo#40089]
### Minimal reproducible example

https://github.com/ducdac/my-app

### Steps to reproduce

`"expo-image-picker": "~17.0.8"
`
<img width="262" height="514" alt="Image" src="https://github.com/user-attachments/assets/c1c3d4d0-b35f-488e-a2c6-b610d8eb869d" />

On the photo editing screen, the action button section is blurred.
Device: Galaxy Note8
Android version: 9

`await ImagePicker.launchImageLibraryAsync({
                mediaTypes: ['images'],
                allowsEditing: true,
                aspect: [1, 1],
                quality: 0.8,
                exif: false,
                base64: false,
                allowsMultipleSelection: false,
                presentationStyle: ImagePicker.UIImagePickerPresentationStyle.FULL_SCREEN
            });`

### Environment

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: macOS 26.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.11.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 11.4.1 - /opt/homebrew/bin/npm
      Watchman: 2025.04.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.0, iOS 26.0, macOS 26.0, tvOS 26.0, visionOS 26.0, watchOS 26.0
      Android SDK:
        API Levels: 28, 29, 31, 32, 34, 35, 36
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 34.0.0, 35.0.0, 36.0.0
        System Images: android-34 | Google Play ARM 64 v8a, android-35-ext14 | Google Play ARM 64 v8a, android-35 | Google Play ARM 64 v8a, android-36 | Google APIs ARM 64 v8a, android-36 | Google Play ARM 64 v8a, android-36 | Pre-Release 16 KB Page Size Google Play ARM 64 v8a, android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.3 AI-243.24978.46.2431.13208083
      Xcode: 26.0.1/17A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~54.0.10 => 54.0.10 
      expo-router: ~6.0.8 => 6.0.8 
      react: 19.1.0 => 19.1.0 
      react-dom: 19.1.0 => 19.1.0 
      react-native: 0.81.4 => 0.81.4 
      react-native-web: ^0.21.0 => 0.21.1 
    npmGlobalPackages:
      eas-cli: 16.17.3
      expo-cli: 6.3.12
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
env: load .env.local
env: export EXPO_PUBLIC_API_URL EXPO_PUBLIC_APP_KEY EXPO_PUBLIC_SECRET_KEY GOOGLE_MAPS_API_KEY EXPO_PUBLIC_GOOGLE_MAPS_API_KEY
16/17 checks passed. 1 checks failed. Possible issues detected:
Use the --verbose flag to see more details about passed checks.

✖ Check for app config fields that may not be synced in a non-CNG project
This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, scheme, userInterfaceStyle, ios, android, plugins, androidStatusBar. 


1 check failed, indicating possible issues with the project.
```

**Comment by trangthuanbinh3696** [comment]
I have seen this issue too after upgraded to Expo SDK 54, and it only happens in light mode, while dark mode is displayed correctly.
This is because **expoCropToolbarColor** in node_modules/expo-image-picker/android/src/main/res/values/colors.xml is set to #00000000.

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Custom colors for image picker cropping interface -->
    <!-- Light mode defaults -->
    <color name="expoCropToolbarColor">#00000000</color> <!-- Transparent -->
    <color name="expoCropToolbarIconColor">#000000</color> <!-- Black icons -->
    <color name="expoCropToolbarActionTextColor">#000000</color> <!-- Black text -->
    <color name="expoCropBackButtonIconColor">#000000</color> <!-- Black back button -->
    <color name="expoCropBackgroundColor">#ffffff</color> <!-- White background -->
</resources>
```

The only workaround I’ve found is switching from Expo Go to a Development Build, changing the expoCropToolbarColor, and then rebuilding.
But I hope this issue will be resolved soon so I can go back to using Expo Go.

**Comment by MarvinVrdoljak** [comment]
Having the same issue.

**Comment by jordisala1991** [comment]
Is there a way to fix this issue other than manually editing the colors.xml file?

Edit: Could be related with this PR: https://github.com/expo/expo/pull/37573

**Comment by jordisala1991** [comment]
> I have seen this issue too after upgraded to Expo SDK 54, and it only happens in light mode, while dark mode is displayed correctly.
> This is because **expoCropToolbarColor** in node_modules/expo-image-picker/android/src/main/res/values/colors.xml is set to #00000000.
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <resources>
>     
>     
>     <color name="expoCropToolbarColor">#00000000</color> 
>     <color name="expoCropToolbarIconColor">#000000</color> 
>     <color name="expoCropToolbarActionTextColor">#000000</color> 
>     <color name="expoCropBackButtonIconColor">#000000</color> 
>     <color name="expoCropBackgroundColor">#ffffff</color> 
> </resources>
> ```
> 
> The only workaround I’ve found is switching from Expo Go to a Development Build, changing the expoCropToolbarColor, and then rebuilding.
> But I hope this issue will be resolved soon so I can go back to using Expo Go.
> 

Can you share your patch @trangthuanbinh3696?

**Comment by bonjourmauko** [comment]
I tried unsuccessfully with :

```
diff --git a/android/src/main/res/values/colors.xml b/android/src/main/res/values/colors.xml
index f10bea37ece44f48741039d20041977d474b7b2f..3f16ae89a2c17cd1e1a586b6e246c561e42a3c30 100644
--- a/android/src/main/res/values/colors.xml
+++ b/android/src/main/res/values/colors.xml
@@ -2,7 +2,7 @@
 <resources>
     <!-- Custom colors for image picker cropping interface -->
     <!-- Light mode defaults -->
-    <color name="expoCropToolbarColor">#00000000</color> <!-- Transparent -->
+    <color name="expoCropToolbarColor">#ffffff</color> <!-- White -->
     <color name="expoCropToolbarIconColor">#000000</color> <!-- Black icons -->
     <color name="expoCropToolbarActionTextColor">#000000</color> <!-- Black text -->
     <color name="expoCropBackButtonIconColor">#000000</color> <!-- Black back button -->
```

**Comment by trangthuanbinh3696** [comment]
Hi @jordisala1991, just run "npx expo install --fix" and you are good to go. This has been resolved in the latest version.

**Comment by zticinovic** [comment]
@trangthuanbinh3696 which version is that? i am on 54.0.20, issue is still there.

**Comment by jordisala1991** [comment]
Same, I just tried with latest version without success.

Also tried patching the specific color without success.

**Comment by zticinovic** [comment]
@jordisala1991 moved to react-native-image-crop-picker - works. Will use that until this is sorted

**Comment by jordisala1991** [comment]
@hirbod Can you help us with this issue? I am trying to debug why it happens, or how to change the colors but after several attempts, nothing affects that transparent color

**Comment by jordisala1991** [comment]
Hope it helps other people, this is how I fixed it on my side (I only have light mode on my app so I didnt test what happens on dark mode):

./plugins/withAndroidColors.ts:
```
import { AndroidConfig, type ConfigPlugin, withAndroidColors } from '@expo/config-plugins'

type AndroidColorProps = {
  toolbarColor?: string
  toolbarIconColor?: string
  toolbarActionTextColor?: string
  backButtonIconColor?: string
  backgroundColor?: string
}

const { Colors } = AndroidConfig

/**
 * Custom config plugin to set Android color resources for expo-image-picker crop UI
 */
const withCustomAndroidColors: ConfigPlugin<AndroidColorProps> = (config, props) => {
  const {
    toolbarColor,
    toolbarIconColor,
    toolbarActionTextColor,
    backButtonIconColor,
    backgroundColor,
  } = props

  return withAndroidColors(config, config => {
    const colorsToSet = [
      { name: 'expoCropToolbarColor', value: toolbarColor },
      { name: 'expoCropToolbarIconColor', value: toolbarIconColor },
      { name: 'expoCropToolbarActionTextColor', value: toolbarActionTextColor },
      { name: 'expoCropBackButtonIconColor', value: backButtonIconColor },
      { name: 'expoCropBackgroundColor', value: backgroundColor },
    ]

    colorsToSet.forEach(({ name, value }) => {
      Colors.assignColorValue(config.modResults, { name, value })
    })

    return config
  })
}

export default withCustomAndroidColors
```

On app.config.ts (inside plugins):
```
      [
        './plugins/withAndroidColors.ts',
        {
          toolbarColor: '#ffffff',
        },
      ],
```

Remember that if you want to use ts plugins you need to have tsx as dev dependency and have this on top of app.config.ts:
```
import 'tsx/cjs'
```


This is the only way I succesfully override that transparent color. Applying a patch on the expo-image-picker does not work (I dont know why)

**Comment by hirbod** [comment]
Hey there, I’ll try to look into this soon. As a quick note on why patching doesn’t work, you need to explicitly opt in to build from source by updating the package.json and by adding

```json
  "expo": {
    "autolinking": {
      "android": {
        "buildFromSource": ["expo-image-picker"]
      }
    }
  }
```

**Comment by leonardorib** [comment]
For folks on bare react-native projects using expo modules, you can customize the cropper UI colors by editing your project `android/app/src/main/res/values/colors.xml`. You can create this file if it doesn't exist yet. Won't require patching the package.

```xml
<resources>
<!-- ... other colors you may already have -->

 <color name="expoCropToolbarColor">#ffffff</color> <!-- White (Instead of default transparent) -->
 <color name="expoCropToolbarIconColor">#000000</color> <!-- Black icons -->
 <color name="expoCropToolbarActionTextColor">#000000</color> <!-- Black text -->
 <color name="expoCropBackButtonIconColor">#000000</color> <!-- Black back button -->
 <color name="expoCropBackgroundColor">#ffffff</color> <!-- White background -->
</resources>
```

**Comment by MrAdex77** [comment]
Hi @lukmccall, @kosmydel  👋
The issue still exists on Android.

I’ve tested this on multiple Android devices, with dark mode both enabled and disabled, and the crop toolbar colors are not applied.

I also tried applying the following config, but it doesn’t change anything:
```
     [
        "expo-image-picker",
        {
          "colors": {
            "cropToolbarColor": "#ffffff",
            "cropToolbarIconColor": "#ffffff"
          },
          "dark": {
            "colors": {
              "cropToolbarColor": "#ffffff"
            }
          }
        }
      ],
```

![Image](https://github.com/user-attachments/assets/61aefb2f-8640-442b-8e9d-1d85184934de)

Environment

Platform: Android

Expo SDK: 54.0.31

expo-image-picker version: 17.0.10

Devices tested: multiple Android devices (Android Emulator, Android 14, Android 13)

**Comment by kosmydel** [comment]
@MrAdex77 have you rebuilt your android folder?

**Comment by MrAdex77** [comment]
> [@MrAdex77](https://github.com/MrAdex77) have you rebuilt your android folder?

Yes, I also tried the example config from this issue, but the behavior is still the same.

I checked the generated files inside node_modules/expo-image-picker/android/src/main/res/ and the colors are not being updated.

values/colors.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Custom colors for image picker cropping interface -->
    <!-- Light mode defaults -->
    <color name="expoCropToolbarColor">#00000000</color> <!-- Transparent -->
    <color name="expoCropToolbarIconColor">#000000</color> <!-- Black icons -->
    <color name="expoCropToolbarActionTextColor">#000000</color> <!-- Black text -->
    <color name="expoCropBackButtonIconColor">#000000</color> <!-- Black back button -->
    <color name="expoCropBackgroundColor">#ffffff</color> <!-- White background -->
</resources>
```

values-night/colors.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Custom colors for image picker cropping interface -->
    <!-- Dark mode defaults -->
    <color name="expoCropToolbarColor">#00000000</color> <!-- Transparent -->
    <color name="expoCropToolbarIconColor">#ffffff</color> <!-- White icons -->
    <color name="expoCropToolbarActionTextColor">#ffffff</color> <!-- White text -->
    <color name="expoCropBackButtonIconColor">#ffffff</color> <!-- White back button -->
    <color name="expoCropBackgroundColor">#000000</color> <!-- Black background -->
</resources>

```

Edit: My bad, I thought this fix had already been shipped with the latest version.

**Comment by keima** [comment]
It looks like this issue has been fixed in a newer release of expo-image-picker.

Due to changes in Expo’s SDK versioning policy, the fix appears to be available only in SDK 55.
https://github.com/expo/expo/blob/sdk-55/packages/expo-image-picker/CHANGELOG.md#55011–2026-03-05

That’s unfortunate for me since I’m still on SDK 54, but I’m choosing to see it as a good reason to upgrade to SDK 55.

**Comment by naushadraien** [comment]
This issue still exists in the latest SDK version.

![Image](https://github.com/user-attachments/assets/18c3b16d-70df-4b67-9a6e-95ba356e5d69)

Environment

Platform: Android

Expo SDK: 55.0.6

expo-image-picker version: 55.0.12

**Comment by hirbod** [comment]
@keima With our AI Expo upgrade skills, I’m confident it won’t take you more than 5-10 minutes to upgrade!
