### ISSUE TITLE
Weird Splash Screen behaviour on Android - ExpoKit

### ISSUE THREAD

**Issue by otaviogaiao** [expo/expo#4076]
### Environment

  Expo CLI 2.15.4 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.10.0 - ~/.nvm/versions/node/v9.10.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v9.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: 32.0.5 => 32.0.5 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.2.1 => 3.2.1 
    npmGlobalPackages:
      expo-cli: 2.15.4

### The Issue

I'm having trouble with the Splash Screen on Android after I ejected. When the app starts the image is kinda stretching down, then a fast white flash and it resizes itself, then when the splash screen ends, I get another white flash. I'm running out of ideas.. I went to take a look at the native part, but with no success. 

This is my `drawable/splash_background.xml`:

```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">

    <item android:drawable="@color/splashBackground"/>

    <item>
        <bitmap xmlns:android="http://schemas.android.com/apk/res/android"
            android:src="@drawable/shell_launch_background_image"
            android:gravity="fill_horizontal|fill_vertical" />
    </item>


</layer-list>
```

The `shell_launch_background_image` is inside `drawable-xxxhdpi`.

My app.json is this (although I don't if its relevant after I eject)

```
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "cover"
    },
```

I'd love to know what's going on, It seems like the app first starts with a Native Splash Screen, then Javascript starts to manage it. Any solution?

iOS works flawless.

here is what's happening:

![bugsplash](https://user-images.githubusercontent.com/3965485/56773954-ed917900-6796-11e9-92ff-f0db387398a8.gif)

**Comment by bozzmob** [comment]
+1 I can confirm, I am facing this as well. I don't think this is expo specific issue though. I am having this issue in a normal react native project as well.

**Comment by otaviogaiao** [comment]
> +1 I can confirm, I am facing this as well. I don't think this is expo specific issue though. I am having this issue in a normal react native project as well.

Have you been able to find a work around?

**Comment by bozzmob** [comment]
@otaviogaiao No, nothing yet. It still flickers like that in all the apps I've built in the last few months.

**Comment by cruzach** [comment]
Hi @otaviogaiao,

Could you share a way for us to reproduce this locally? 

My guess is it must be something with the native configuration you have, but without being able to run it, it's hard to say.

-Charlie

**Comment by otaviogaiao** [comment]
> Hi @otaviogaiao,
> 
> Could you share a way for us to reproduce this locally?
> 
> My guess is it must be something with the native configuration you have, but without being able to run it, it's hard to say.
> 
> -Charlie

Sorry for the delay. I created a repo on github. The issue is present.

https://github.com/otaviogaiao/weird_splash

Let me know what else I can help with

Thanks!

**Comment by evgeny-s** [comment]
Same for me

**Comment by santiagomartinez** [comment]
Set `SHOW_LOADING_VIEW_IN_SHELL_APP` to `false` in AppConstants.java.
I don't know the reason, but the problem is similar to this:
https://forums.expo.io/t/android-splashscreen-flicker-white-and-resize/24969/3

**Comment by tattivitorino** [comment]
My problem here is that the splash screen on android is not loading at all after I ejected the app. Only the screen with the background color! IOS is ok! 

Thats my app.json

"splash": {
      "image": "./assets/imgs/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ededed"
    }

the image is in the app/src/main/res/drawable-xxxhdpi directory

I've noticed that the splash_background.xml came like this without the bitmap item:

<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">

    <item android:drawable="@color/splashBackground"/>

</layer-list>

I've tried inserting this  <item><bitmap android:gravity="center" android:src="@drawable/shell_launch_background_image" /></item> and rebuilding the app on Android Studio but it hasnt worked!

SHOW_LOADING_VIEW_IN_SHELL_APP in AppConstants.java is set to true

Any help will be appreciated!

**Comment by santiagomartinez** [comment]
Just in case, are you able to navigate to the `shell_launch_background_image` with Command+click or Ctrl+click on `@drawable/shell_launch_background_image`?

**Comment by tattivitorino** [comment]
@santiagomartinez yes!

**Comment by tattivitorino** [comment]
@santiagomartinez now it's working, but to be honest I can't say exactly what fixed it! I published the app cause I need to compile apks for testing, restarted Android Studio, rebuilt the project! anyway it's working now! But it's worth mentioning that when you eject the app the splash_background.xml is incomplete!

**Comment by tattivitorino** [comment]
Ok. here's how I solved it in case anyone gets into the same problem:
Expo SDK 33 when you eject your app there are a few things you need to do in order to get your splash screen working on android

1. app.json
I put the splash config into the android key so it won’t interfere with the IOS configs
Check this https://docs.expo.io/versions/v33.0.0/guides/splash-screens/ for limitations on resizeMode

`"android": {
      "package": “xxxxx”,
      "versionCode": 100,
      "icon": "./assets/imgs/icon-android.png",
      "splash": {
        "image": "./assets/imgs/splash.png",
        "resizeMode": "cover",
        "backgroundColor": "#ededed"
      },
      "publishBundlePath": "android/app/src/main/assets/shell-app.bundle",
      "publishManifestPath": "android/app/src/main/assets/shell-app-manifest.json"
    }`

2. splash_background.xml
This file is created without the reference to the bitmap splash screen 
This is how I fixed it:

`<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/splashBackground"/>
    <item><bitmap android:gravity="center" android:src="@drawable/splash" /></item>
</layer-list>`

3. AppConstants.java
`public static boolean SHOW_LOADING_VIEW_IN_SHELL_APP = false;`

4. Here https://romannurik.github.io/AndroidAssetStudio/index.html you can create 9 patch images for android (Simple NinePatch generator) that you can use for the splash screen
I put each image resolution into their directory and rebuild the app on android studio
You need to reference them here: 
`<item><bitmap android:gravity="center" android:src="@drawable/splash" /></item>`

**Comment by lilosir** [comment]
Same issue, it seems there are two stages of the splash screen. I tried to use another image or just remove the bitmap item, it will still show the previous image as the splash screen at the second stage.

**Comment by tsapeta** [comment]
Closing this as we no longer support ExpoKit. If you can't use managed workflow, we recommend to use bare workflow and use `expo-splash-screen` module. If you will still experience such behavior please open a new bug report.
