### ISSUE TITLE
[ios][ui] expo-glass-effect doesn't work with animated parent opacity changes

### ISSUE THREAD

**Issue by robgraeber** [expo/expo#41024]
### Steps to reproduce

To reproduce setup a reanimated view that is animating the opacity and have the children of that view be a glass view. The glass view will render as a normal view, not a glass view. `isLiquidGlassAvailable()` is also true. The glass view works without opacity animation. This also happens when using RN's Animated library.

In my particular case I have a Modal component like this:
```tsx
export function Modal({
  children,
  isShown,
  onClose,
  animationType = 'fadeIn',
  backdropOpacity = 0.6,
  keyboardAvoiding = false,
}: Props) {
  const screenHeight = useScreenSize().height;
  const { height: keyboardHeight } = useAnimatedKeyboard();
  const prevIsShown = usePrevious(isShown);
  const shouldRender = useStateObject(isShown);
  const backgroundOpacityProgress = useSharedValue(0);
  const panelOpacity = useSharedValue(0);
  const panelScale = useSharedValue(1);
  const panelTop = useSharedValue(0);
  const shouldHandleKeyboardEvents = useSharedValue(keyboardAvoiding);
  const animationTime = isShown ? 300 : 150;

  const animatedBackgroundStyle = useAnimatedStyle(
    () => ({
      backgroundColor: interpolateColor(
        backgroundOpacityProgress.value,
        [0, 1],
        [rgba('#000', 0), rgba('#000', backdropOpacity)]
      ),
    }),
    [backgroundOpacityProgress]
  );

  const animatedPanelStyle = useAnimatedStyle(
    () => ({
      // opacity: withTiming(panelOpacity.value, {
      //   duration: animationTime,
      //   easing: ease,
      // }),
      transform: [
        {
          scale: withTiming(panelScale.value, {
            duration: animationTime * 3,
            easing: easeOutElastic(1.5),
          }),
        },
      ],
      top: withTiming(panelTop.value, {
        duration: animationTime,
        easing: ease,
      }),
    }),
    [panelOpacity, panelScale, panelTop, animationTime, keyboardHeight]
  );

  const animatedKeyboardAvoidingStyle = useAnimatedStyle(
    () => ({
      // Instant when keyboard appears, smooth when dismissing
      top: shouldHandleKeyboardEvents.value
        ? -keyboardHeight.value / 2 // Instant positioning when keyboard appears
        : withTiming(0, {
            // Smooth animation when keyboard dismisses
            duration: 250,
            easing: ease,
          }),
    }),
    [keyboardHeight, shouldHandleKeyboardEvents]
  );

  useEffect(() => {
    if (isShown) {
      shouldRender.setValue(true);
    }

    backgroundOpacityProgress.value = withTiming(isShown ? 1 : 0, {
      duration: animationTime,
      easing: ease,
    });
    panelOpacity.value = isShown ? 1 : 0;

    if (animationType === 'fadeIn') {
      panelScale.value = isShown ? 1 : 0.7;
    }

    if (animationType === 'slideIn') {
      // Slide in to enter then scale out to exit.
      if (prevIsShown && !isShown) {
        panelScale.value = 0.7;
      } else {
        panelTop.value = isShown ? 0 : screenHeight / 2;
      }
    }

    if (prevIsShown && !isShown) {
      setTimeout(() => {
        shouldRender.setValue(false);
        // Resetting values for slideIn animation since animation is non-symetrical
        if (animationType === 'slideIn') {
          panelScale.value = 1;
          panelTop.value = screenHeight / 2;
        }
      }, animationTime);
    }
  }, [
    isShown,
    prevIsShown,
    animationTime,
    animationType,
    backgroundOpacityProgress,
    panelOpacity,
    panelScale,
    panelTop,
    screenHeight,
    shouldRender,
  ]);

  const isRendered = shouldRender.value;

  return (
    <Animated.View
      style={[styles.container, animatedBackgroundStyle, when(!isRendered, displayNone)]}
    >
      <Pressable style={fullSize} onPress={() => isShown && onClose && onClose()} />
      <View style={styles.panelContainer} pointerEvents="box-none">
        <Animated.View style={animatedPanelStyle}>
          <Animated.View style={animatedKeyboardAvoidingStyle}>
            <ModalContext.Provider value={{ shouldHandleKeyboardEvents, exists: true }}>
              {children}
            </ModalContext.Provider>
          </Animated.View>
        </Animated.View>
      </View>
    </Animated.View>
  );
}
```

### Environment

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: macOS 26.1
      Shell: 3.6.0 - /usr/local/bin/fish
    Binaries:
      Node: 22.11.0 - /usr/local/bin/node
      Yarn: 3.2.1 - ~/.yarn/bin/yarn
      npm: 10.9.0 - /usr/local/bin/npm
      Watchman: 2025.06.30.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.1, iOS 26.1, macOS 26.1, tvOS 26.1, visionOS 26.1, watchOS 26.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 26.1.1/17B100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~54.0.0 => 54.0.3 
      expo: 54.0.22 => 54.0.22 
      expo-router: ~6.0.14 => 6.0.14 
      expo-updates: ~29.0.12 => 29.0.12 
      react: 19.1.0 => 19.1.0 
      react-dom: 19.1.0 => 19.1.0 
      react-native: 0.81.5 => 0.81.5 
      react-native-web: ^0.21.0 => 0.21.1 
    npmGlobalPackages:
      eas-cli: 16.20.4
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Unrelated errors
```

**Comment by ptrnk0** [comment]
+1

**Comment by mvritz** [comment]
same here

**Comment by austinGENEreeve** [comment]
same

**Comment by robgraeber** [comment]
Unfortunately same bug affects https://github.com/callstack/liquid-glass which has an independent implementation.

**Comment by colby-mchenry** [comment]
No fix for this yet?

**Comment by flikQ** [comment]
I use a lot of animated entry and exists in my app - I am also trying to figure out the root cause to see if I can help with a fix.

**Comment by intergalacticspacehighway** [comment]
Thanks for creating the issue. Looking into this. This appears to be a bug that got introduced in iOS 26.1. Current workaround would be to start animating from opacity values like 0.1.

**Comment by 227Faddi** [comment]
@intergalacticspacehighway how did you do? I tried to se the initial opacity to 0.1 or 1 but none of seems to work

**Comment by clemensmol** [comment]
I ran into some issues with glass-effect not being rendered too, but I found zIndex style (somewhere in the component chain) to be the problem. Refactored some components so I could remove the zIndex and it worked!

**Comment by intergalacticspacehighway** [comment]
We have a workaround for this bug [here](https://github.com/expo/expo/pull/41225). Can you use it as a patch and let us know if it fixes it for you @robgraeber?

@227Faddi for me setting initial opacity on parent view or the view itself to 0.02 (could go lower) and then animating to 1 worked. But you can try the above solution and let us know.

**Comment by robgraeber** [comment]
Hey @intergalacticspacehighway That patch seems to partially work, however doesn't work when there's more than one layer of animated opacity (using Reanimated).

**Comment by arekkubaczkowski** [comment]
For me, animations starting with opacity > 0 also sometimes don’t work. Really hoping for a better fix.

**Comment by robgraeber** [comment]
> For me, animations starting with opacity > 0 also sometimes don’t work. Really hoping for a better fix.

Same, seem like it works 95% of the time but sometimes doesn't.

**Comment by arekkubaczkowski** [comment]
https://github.com/callstack/liquid-glass/issues/27#issuecomment-3694921766

**Comment by eessaarrtt** [comment]
We were able to stabilize GlassView on iOS by:
- Never animating `opacity` on any parent of GlassView
- Animating opacity only on inner content
- Remounting GlassView once when it becomes visible using
  useAnimatedReaction + runOnJS
- Delaying GlassView mount until after first render

This fully resolved Liquid Glass degradation in a sticky header driven
by Reanimated scroll values on iOS 26.


```

import { useTheme } from "@/contexts/ThemeContext";
import { BlurTint, BlurView } from "expo-blur";
import { GlassView, isLiquidGlassAvailable } from "expo-glass-effect";
import React, { useEffect, useState } from "react";
import { StyleSheet, useColorScheme, View, ViewProps } from "react-native";

interface GlassmorphicCardProps extends ViewProps {
  intensity?: number;
  className?: string;
  children: React.ReactNode;
  tint?: BlurTint;
  glassEffectStyle?: "clear" | "regular";
  isInteractive?: boolean;
  overflowHidden?: boolean;
}

export default function GlassmorphicCard({
  intensity = 35,
  className = "",
  children,
  tint,
  glassEffectStyle = "clear",
  isInteractive = true,
  style,
  overflowHidden = true,
  ...props
}: GlassmorphicCardProps) {
  const { currentTheme } = useTheme();
  const systemColorScheme = useColorScheme();
  const [supportsLiquidGlass, setSupportsLiquidGlass] = useState(() => isLiquidGlassAvailable());
  const [mounted, setMounted] = useState(false);

  // Проверяем доступность Liquid Glass при монтировании и обновляем при необходимости
  useEffect(() => {
    setMounted(true);
    
    // Проверяем сразу и с небольшой задержкой на случай, если модуль еще не инициализирован
    const checkAvailability = () => {
      const available = isLiquidGlassAvailable();
      setSupportsLiquidGlass((prev) => {
        // Обновляем только если значение изменилось
        if (prev !== available) {
          return available;
        }
        return prev;
      });
    };
    
    // Проверяем несколько раз с задержками для надежности
    checkAvailability();
    const timeout1 = setTimeout(checkAvailability, 50);
    const timeout2 = setTimeout(checkAvailability, 200);
    const timeout3 = setTimeout(checkAvailability, 500);
    
    return () => {
      clearTimeout(timeout1);
      clearTimeout(timeout2);
      clearTimeout(timeout3);
    };
  }, []); // Запускаем только при монтировании

  const finalTint: BlurTint = tint ?? (systemColorScheme === "dark" ? "dark" : "light");

  const tintColor =
    finalTint === "light"
      ? "rgba(255,255,255,0.0)"
      : finalTint === "dark"
      ? "rgba(0,0,0,0.6)"
      : undefined;

  // Монтируем GlassView только после того, как компонент полностью смонтирован
  if (supportsLiquidGlass && mounted) {
    return (
      <View style={[styles.wrapper, style, { overflow: overflowHidden ? "hidden" : undefined }]} {...props}>
        <GlassView
          key={`glass-${isInteractive ? 'interactive' : 'non-interactive'}-${mounted}`}
          glassEffectStyle={glassEffectStyle}
          isInteractive={isInteractive}
          tintColor={tintColor}
          style={styles.glassFill} // ключ: под клип
        />
        {children}
      </View>
    );
  }

  return (
    <BlurView
      intensity={currentTheme.components.card.blurIntensity || intensity}
      tint={finalTint}
      className={`rounded-2xl overflow-hidden ${className}`}
      style={style}
      {...props}
    >
      {children}
    </BlurView>
  );
}

const R = 24;

const styles = StyleSheet.create({
  wrapper: {
    borderRadius: R,
  },
  glassFill: {
    ...StyleSheet.absoluteFillObject,
    // “съедаем” системный край:
    top: -4,
    left: -4,
    right: -4,
    bottom: -4,
    borderRadius: R + 4,
  },
});


```

```
/**
 * Sticky Header that appears on scroll
 * Compact header with title and actions
 */

import { IconSymbol } from "@/components/ui/IconSymbol";
import { useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import { Platform, Pressable, StyleSheet, Text, View } from "react-native";
import Animated, {
  Extrapolate,
  interpolate,
  SharedValue,
  useAnimatedStyle,
  useDerivedValue,
} from "react-native-reanimated";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import GlassmorphicCard from "../home/GlassmorphicCard";
import { articleColors } from "./articleColors";

interface ArticleStickyHeaderProps {
  title: string;
  scrollY: SharedValue<number>;
  showThreshold?: number;
  bookmarked?: boolean;
  onBookmark?: () => void;
  onShare?: () => void;
}

export const ArticleStickyHeader: React.FC<ArticleStickyHeaderProps> = ({
  title,
  scrollY,
  showThreshold = 300,
  bookmarked = false,
  onBookmark,
  onShare,
}) => {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const [isVisible, setIsVisible] = useState(false);
  const [mountKey, setMountKey] = useState(0);

  // Отслеживаем видимость компонента
  const opacityValue = useDerivedValue(() => {
    return interpolate(
      scrollY.value,
      [showThreshold, showThreshold + 50],
      [0, 1],
      Extrapolate.CLAMP
    );
  });

  useEffect(() => {
    // Проверяем видимость и принудительно перемонтируем GlassView при появлении
    const checkVisibility = () => {
      const currentOpacity = opacityValue.value;
      const shouldBeVisible = currentOpacity > 0.1;
      
      if (shouldBeVisible && !isVisible) {
        setIsVisible(true);
        // Принудительно перемонтируем GlassView при первом появлении
        setMountKey(prev => prev + 1);
      } else if (!shouldBeVisible && isVisible) {
        setIsVisible(false);
      }
    };

    // Проверяем периодически
    const interval = setInterval(checkVisibility, 100);
    
    // Также проверяем сразу
    checkVisibility();

    return () => clearInterval(interval);
  }, [isVisible, opacityValue]);

  const animatedStyle = useAnimatedStyle(() => {
    const opacity = opacityValue.value;

    const translateY = interpolate(
      scrollY.value,
      [showThreshold, showThreshold + 50],
      [-20, 0],
      Extrapolate.CLAMP
    );

    return {
      opacity,
      transform: [{ translateY }],
    };
  });

  return (
    <Animated.View
      style={[
        styles.container,
        animatedStyle,
      ]}
      pointerEvents="box-none"
    >
      <GlassmorphicCard
        key={`sticky-header-${title}-${mountKey}`}
        style={styles.glassCard}
        intensity={80}
        tint="dark"
        overflowHidden={false}
        isInteractive={true}
      >
        <View style={[styles.content, { paddingTop: insets.top }]}>
        <Pressable onPress={() => router.back()} style={styles.backButton}>
          <IconSymbol name="chevron.left" size={20} color={articleColors.textPrimary} />
        </Pressable>

        <Text numberOfLines={1} style={styles.title}>
          {title}
        </Text>

        <View style={styles.actions}>
          {onBookmark && (
            <Pressable onPress={onBookmark} style={styles.actionButton}>
              <IconSymbol
                name={bookmarked ? "bookmark.fill" : "bookmark"}
                size={20}
                color={bookmarked ? articleColors.bookmark : articleColors.textPrimary}
              />
            </Pressable>
          )}
          {onShare && (
            <Pressable onPress={onShare} style={styles.actionButton}>
              <IconSymbol name="square.and.arrow.up" size={20} color={articleColors.textPrimary} />
              </Pressable>
            )}
          </View>
        </View>
      </GlassmorphicCard>
    </Animated.View>
  );
};

const styles = StyleSheet.create({
  container: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  glassCard: {
 
  },
  content: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    flex: 1,
    fontSize: 16,
    fontWeight: "700",
    color: articleColors.textPrimary,
    marginHorizontal: 8,
  },
  actions: {
    flexDirection: "row",
    gap: 8,
  },
  actionButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
});


```

**Comment by robgraeber** [comment]
I also noticed expo-glass-effect doesn't initialize during an reanimated animation (translateY in my case). I needed to set a 0.5s animation delay to guarantee the glass view finished loading.

**Comment by GibbonTech** [comment]
I noticed expo-glass-effect doesn't initialize during an reanimated animation , banged my head on the wall for 2 days cuz of u guys

**Comment by intergalacticspacehighway** [comment]
Looks like apple wants to avoid opacity values < 1 when using `UIVisualEffectView` as stated [here](https://developer.apple.com/documentation/uikit/uivisualeffectview#Set-the-correct-alpha-value) 😕. It's weird because this was working before 26.1. If the underlying API does not support it, then i don't think we can do much to support this usecase. I also have not heard from them in my opened ticket FB21158374

<img width="300" height="auto" alt="Image" src="https://github.com/user-attachments/assets/e4589e3c-c56e-4ed0-ad64-47d67ff1c157" />

**Comment by MrFunctor** [comment]
Hey @intergalacticspacehighway, when it comes to animating glass in or out, Apple recommends to set or unset the effect to ensure that the glass materializes or dematerializes with the appropriate animation instead of trying to manually animate the opacity.

So, the recommended way to animate glass out is to set the effect to `nil`:

```swift
// Animates the glass out using the dematerialize animation
UIView.animate {
  effectView.effect = nil
}
```

And to animate glass in, we set the effect (assuming it was previously `nil`):

```swift
// Animates the glass in using the materialize animation
UIView.animate {
  effectView.effect = glassEffect
}
```

For this approach to work in React Native apps, we probably need to rely on some prop, e.g., a `visible?: boolean` prop that changes from `true` to `false` (or vice-versa) and triggers the animation, or the ability to set the `glassEffectStyle` to `null` or `'none'`, which would trigger the animation on changes, or come up with some other approach.

Also, it appears that when the glass effect is removed, the content is still visible, so it needs to be manually faded out (e.g., using alpha) either inside `expo-glass-effect` or in userland.

**Comment by intergalacticspacehighway** [comment]
@MrFunctor I like the idea of animating between styles. Thanks! wyt about an API like below?

```jsx
<GlassView glassEffectStyle={{ style: "clear", animationDuration: 0.5, animate: true }} />
```

Here, `style` could be `clear`, `regular` and `none`, so it can be used to animate out and in. Other properties could be used to customise the animation if needed.


Edit: Made a draft PR - https://github.com/expo/expo/pull/42005

**Comment by MrFunctor** [comment]
@intergalacticspacehighway  For some reason, I couldn't find this mentioned in the Apple developer documentation for UIKit. I actually learned about it in a [WWDC video](https://youtu.be/uhMo6IEcR1w?si=NyJYwBg_sJbdbL4X&t=1229). Anyway, I like the API that you proposed and thanks for implementing a draft so quickly! 🚀

Just a small heads-up: while testing this approach in iOS 26.0, I realized that it is buggy, in the sense that the glass effect doesn't always disappears as expected. I found [this SO question](https://stackoverflow.com/questions/79767347/de-materialize-uivisualeffectview-with-uiglasseffect) mentioning this bug and the answers suggest workarounds like setting the `effect` first to `UIBlurEffect()` and then to `nil`, or just setting the `alpha` to `0.01`. So, since earlier versions of iOS 26 (at least 26.0) have this bug, it either needs to be mentioned in the docs, or a different animation should run specifically on the affected iOS 26 versions.

**Comment by intergalacticspacehighway** [comment]
@MrFunctor yeah, i faced it. Setting effect to `nil` is buggy, but setting it to the `UIVisualEffect` does work! I did that in this [PR](https://github.com/expo/expo/pull/42005/changes#diff-48348e423af3386b162e5dfa0894ad6a0b6db0185c14e2576cb418790d685aecR106). The alternate solution of setting alpha also works by setting opacity to 0.01 with RN/reanimated style.

**Comment by MrFunctor** [comment]
@intergalacticspacehighway Yeah, I just looked at the PR. Setting the `effect` to `UIVisualEffect()` is indeed a nice workaround!

**Comment by robgraeber** [comment]
@intergalacticspacehighway @MrFunctor To clarify, with https://github.com/expo/expo/pull/42005 would this handle parent opacity changes or will it need to be handled manually with setting the style prop? Is it possible to provide a way to tell when the glass effect didn't initialize correctly because of a parent animation so we can provide a fallback style?

**Comment by intergalacticspacehighway** [comment]
@robgraeber adding an [example](https://github.com/expo/expo/pull/42005/changes#diff-30b1286f2c0f694131329b08222fe224c19b28e63a67bf21b08cce4b07906eb0R167) in docs with a workaround for fading glass views. The PR includes an example

https://github.com/user-attachments/assets/c199930a-1ef6-4551-8ae1-581112d12ded

**Comment by eli-provenform** [comment]
Hey @intergalacticspacehighway thanks for your work on the animated/animationDuration props on Glass Effect! I use the GlassView component throughout my app and it's usually fine and renders correctly; curious if you have a solution for when we render a page and it the GlassView does not appear until we refocus the page (seemingly glass works fine if on an initially rendered page). It may be tangentially related to the above, or could be navigation related. 

The debug screen below is using this by the way:
```
     <GlassView
                style={styles.glass}
                glassEffectStyle={{
                    style: 'clear',
                    animate: true,
                    animationDuration: 2,
                }}
            />
```

https://github.com/user-attachments/assets/b96aa0dc-f4d9-47ec-a077-f1fc07c0fd2f

**Comment by Aycom366** [comment]
> Hey [@intergalacticspacehighway](https://github.com/intergalacticspacehighway) thanks for your work on the animated/animationDuration props on Glass Effect! I use the GlassView component throughout my app and it's usually fine and renders correctly; curious if you have a solution for when we render a page and it the GlassView does not appear until we refocus the page (seemingly glass works fine if on an initially rendered page). It may be tangentially related to the above, or could be navigation related.
> 
> The debug screen below is using this by the way:
> 
> ```
>      <GlassView
>                 style={styles.glass}
>                 glassEffectStyle={{
>                     style: 'clear',
>                     animate: true,
>                     animationDuration: 2,
>                 }}
>             />
> ```
> 
>  Untitled.mov

+1

**Comment by intergalacticspacehighway** [comment]
@Aycom366 @eli-provenform right now you can use below workaround that uses `useIsFocused` from react-navigation.

```jsx
const isFocused = useIsFocused();
<GlassView glassEffectStyle={isFocused ? "clear" : "none"} />
```

I am looking into a proper solution for this issue.

**Comment by smontlouis** [comment]
@intergalacticspacehighway thank you for the workaround.

using this as the glassEffectStyle object animation is not working on expo 55, for whatever reason

**Comment by AlirezaHadjar** [comment]
@intergalacticspacehighway Hey nishan, thanks for adding the `animate` key. I noticed an issue with it though. it clashes with the `isInteractive` prop. 

```tsx
<GlassView
                isInteractive
                style={styles.button}
                colorScheme="dark"
                glassEffectStyle={{
                    style: showGlass ? "clear" : "regular",
                    animate: true,
                    animationDuration: GLASS_ANIMATION_DURATION
                }}
            />
```

In the example above, the `isInteractive` prop isn't working.

**Comment by intergalacticspacehighway** [comment]
Thanks for reporting @AlirezaHadjar, https://github.com/expo/expo/pull/43330 should fix it.

**Comment by intergalacticspacehighway** [comment]
@eli-provenform can you try a patch from this PR - https://github.com/expo/expo/pull/43330? It should solve the tab navigator rendering issue.

**Comment by AlirezaHadjar** [comment]
@intergalacticspacehighway thanks for the quick response. Yes, I can confirm that the patch fixes the issue. Good work!

**Comment by eli-provenform** [comment]
@intergalacticspacehighway the issue is fixed wrt tab navigator rendering, thank you!

**Comment by intergalacticspacehighway** [comment]
We've added the opacity usage example in the latest SDK 55, also backported to SDK 54. So closing this issue https://docs.expo.dev/versions/latest/sdk/glass-effect/#known-issues

**Comment by colin-oos** [comment]
This is still an issue for me even when still using the recommended approach in the expo docs. I think the issue still persists when trying to animate the opacity of a view/component that contains glass elements as children somewhere in it. This makes it extremely difficult to use glass backgrounds for modals and stuff which need to have their entire container fade in and out.
