### ISSUE TITLE
[expo-router] The native tab doesn’t display icons in the development build

### ISSUE THREAD

**Issue by lephuvu1994** [expo/expo#41049]
### Minimal reproducible example

The app fails to display native tab icons when using an Expo SDK 54 project with a Dev Client build. This occurs on both iOS 16 and iOS 18.2, even when using SF Symbols or vector icons. The icons do not appear when the native tab is rendered

### Steps to reproduce

1. Create new project: npx create-expo-app@latest
2. Create a development build on EAS: npx expo install expo-dev-client
3. On TabLayout Change code 
```
     <NativeTabs>
        <NativeTabs.Trigger name="(room)">
          <Label>{translate("app.roomTab")}</Label>
          <Icon sf={"house.fill"} drawable="custom_home_drawable" />
        </NativeTabs.Trigger>
        <NativeTabs.Trigger name="(home)">
          <Label>{translate("app.homeTab")}</Label>
          <Icon sf={"house.fill"} drawable="custom_home_drawable" />
        </NativeTabs.Trigger>
        <NativeTabs.Trigger name="smart">
          <Label>{translate("app.smartTab")}</Label>
          <Icon sf={"house.fill"} drawable="custom_home_drawable" />
        </NativeTabs.Trigger>
        <NativeTabs.Trigger name="(settings)">
          <Label>{translate("app.settingTab")}</Label>
          <Icon sf={"house.fill"} drawable="custom_home_drawable" />
        </NativeTabs.Trigger>
    </NativeTabs>
```
4. Check UI Tab after build on the simulator or device.

![Image](https://github.com/user-attachments/assets/a3e4e468-9e87-4adb-b07a-0373ff497b28)

### Environment

```text
expo-env-info 2.0.7 environment info:
    System:
      OS: MacOS
    Binaries:
      Node: 22.14.0
      yarn: 4.9.2
    npmPackages:
      expo: ^54.0.23 => 54.0.23
      expo-updates: ~29.0.12 => 29.0.12
      react: 19.1.0 => 19.1.0
      react-dom: 19.1.0 => 19.1.0
      react-native: 0.81.5 => 0.81.5
      react-native-web: ^0.21.0 => 0.21.2
      expo-dev-client: "6.0.15"
      "expo-router": "6.0.14",
    Expo Workflow: dev client build
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

**Comment by dancamdev** [comment]
I'm having the same issue on iOS 26 as well.

If I define the icon as follows `<Icon sf="house.fill" />` I see no icon.

If I follow the [documentation](https://docs.expo.dev/router/advanced/native-tabs/#icon)

And define it like this:

```Ts
<Icon sf={{ default: 'house', selected: 'house.fill' }} />
```

I get this other error:

>  ERROR  [Error: [RNScreens] Incorrect icon format for iOS. You must provide `sfSymbol`, `imageSource` or `templateSource`.]

**Comment by dancamdev** [comment]
I got it to work by running `expo-doctor` and downgrading react-native-screens to 4.16.0

```json
"react-native-screens": "4.16.0"
```

**Comment by patovicens** [comment]
> I got it to work by running `expo-doctor` and downgrading react-native-screens to 4.16.0
> 
> "react-native-screens": "4.16.0"

Same issue and can confirm this fixed it

**Comment by Ubax** [comment]
Hi all
The react-native-screens version `4.18` introduced changes to icon API. Therefore the native tab's icons in router will not work with this version. We will upgrade the tabs API when new version of react-native-screens will be released

I'll close this issue, as there is nothing we can do. Until new version of screens is released, we recommend using 4.16 one.

**Comment by csheppard** [comment]
Hey @Ubax, how come you are waiting for another version of screens? Is it to make sure the new API is stable?

**Comment by colin-oos** [comment]
@Ubax Shouldn't the solution be to update the new API to utilize the new changes to the icon API?

**Comment by matinzd** [comment]
> Hi all The react-native-screens version `4.18` introduced changes to icon API. Therefore the native tab's icons in router will not work with this version. We will upgrade the tabs API when new version of react-native-screens will be released
> 
> I'll close this issue, as there is nothing we can do. Until new version of screens is released, we recommend using 4.16 one.

React Native Screens 4.18 is already released. What do you mean by that?

**Comment by matinzd** [comment]
You can all use expo router v7 canary release and use this API instead:

```
npm install expo-router@canary
npm install expo-symbols@canary
```

```tsx
import { isLiquidGlassAvailable } from "expo-glass-effect";
import { NativeTabs } from "expo-router/unstable-native-tabs";

export default function TabLayout() {
  return (
    <NativeTabs disableTransparentOnScrollEdge={!isLiquidGlassAvailable()}>
      <NativeTabs.Trigger name="(home)">
        <NativeTabs.Trigger.Icon sf={"house.fill"} md={"home"} />
      </NativeTabs.Trigger>
      <NativeTabs.Trigger name="(settings)">
        <NativeTabs.Trigger.Icon sf={"gear"} md={"home"} />
      </NativeTabs.Trigger>
    </NativeTabs>
  );
}
```

**Comment by RobJacobson** [comment]
We hit a related *crash* (not just missing icons) in SDK 54 when using `expo-router/unstable-native-tabs`.

**Error (iOS):** `[RNScreens] Incorrect icon format for iOS. You must provide sfSymbol, imageSource or templateSource.`

**Env:** expo `54.0.29`, expo-router `6.0.19`, react-native `0.81.5`, react-native-screens `4.18.0`, dev-client.

**Root cause:** `expo-router@6.0.19`'s native tabs adapter (`build/native-tabs/NativeBottomTabs/NativeTabsView.js`) passes a legacy icon shape to `react-native-screens`:
- returns `{ templateSource: icon.src }` or `{ sfSymbolName: icon.sf }`

But `react-native-screens@4.18.0` expects the *typed* icon object format (see `PlatformIconIOS` in screens):
- `{ type: 'templateSource', templateSource: ... }` / `{ type: 'sfSymbol', name: ... }` etc.

**Workaround/Fix:** adjust `convertOptionsIconToPropsIcon` to emit typed icon objects. Patch we applied locally:

```diff
- return { sfSymbolName: icon.sf };
+ return { ios: { type: 'sfSymbol', name: icon.sf }, type: 'sfSymbol', name: icon.sf };

- return { templateSource: icon.src };
+ return {
+   ios: { type: 'templateSource', templateSource: icon.src },
+   android: { type: 'imageSource', imageSource: icon.src },
+   type: 'templateSource',
+   templateSource: icon.src,
+ };
```

We’re using `patch-package` as a temporary workaround. Happy to open a PR if this is the right direction (probably should be implemented in the TS source rather than the built JS).

**Comment by Ubax** [comment]
This should be fixed in expo-router v6.0.20

It supports both pre 4.18 and 4.18+ versions. Note that Expo Go still supports only react-native-screens 4.16

**Comment by anmol-fzr** [comment]
using expo-router v6.0.22
using react-native-screens v4.16.0

```javascript
import { useRouter } from "expo-router";
import { Icon, Label, NativeTabs } from "expo-router/unstable-native-tabs";
import { useEffect } from "react";
import { translate } from "@/i18n";
import { useAuth } from "@/modules/auth/hooks/useAuth";
import { useAppTheme } from "@/utils/useAppTheme";

export default function TabsLayout() {
	const { isLogin } = useAuth();
	const { navigate } = useRouter();

	useEffect(() => {
		if (!isLogin) {
			navigate("/auth");
		}
	}, [isLogin, navigate]);

	const {
		theme: { colors },
	} = useAppTheme();

	return (
		<NativeTabs
			labelVisibilityMode="labeled"
			backgroundColor={colors.palette.neutral200}
			indicatorColor={colors.palette.accent200}
			iconColor={{
				default: colors.palette.neutral500,
				selected: colors.palette.accent500,
			}}
			tintColor={colors.palette.accent500}
		>
			<NativeTabs.Trigger name="index">
				<Label>{translate("tabs:home")}</Label>
				<Icon
					src={{
						default: require("../../../assets/tabs/icons/home.png"),
						selected: require("../../../assets/tabs/icons/home-selected.png"),
					}}
				/>
			</NativeTabs.Trigger>

			<NativeTabs.Trigger name="calculators">
				<Label>{translate("tabs:calculator")}</Label>
				<Icon
					src={{
						default: require("../../../assets/tabs/icons/calculator.png"),
						selected: require("../../../assets/tabs/icons/calculator-selected.png"),
					}}
				/>
			</NativeTabs.Trigger>

			<NativeTabs.Trigger name="learnings">
				<Label>{translate("tabs:learnings")}</Label>
				<Icon
					src={{
						default: require("../../../assets/tabs/icons/book.png"),
						selected: require("../../../assets/tabs/icons/book-selected.png"),
					}}
				/>
			</NativeTabs.Trigger>

			<NativeTabs.Trigger name="scams">
				<Label>{translate("tabs:scams")}</Label>
				<Icon
					src={{
						default: require("../../../assets/tabs/icons/shield.png"),
						selected: require("../../../assets/tabs/icons/shield-selected.png"),
					}}
				/>
			</NativeTabs.Trigger>

			<NativeTabs.Trigger name="profile">
				<Label>{translate("tabs:profile")}</Label>
				<Icon
					src={{
						default: require("../../../assets/tabs/icons/user.png"),
						selected: require("../../../assets/tabs/icons/user-selected.png"),
					}}
				/>
			</NativeTabs.Trigger>
		</NativeTabs>
	);
}

```

still not getting the icons in tab bar

<img width="828" height="220" alt="Image" src="https://github.com/user-attachments/assets/b498e10c-5a81-485e-92de-e8e8d745ae87" />

**Comment by meer-habib-dev** [comment]
I'm using Expo Router for native glassy tabs, but it's not showing properly, @expo 

Is there anyone else facing a similar issue?

"expo": "~54.0.32",
"expo-router": "~6.0.15",
"react-native-screens": "~4.16.0",

<img width="463" height="217" alt="Image" src="https://github.com/user-attachments/assets/ee5ec6b7-a3aa-46f9-a375-e098b0124f2b" />

**Comment by rileysay** [comment]
Same issue on SDK 55 beta. SF icons not showing

    "expo": "^55.0.0-preview.10",
    "expo-router": "~55.0.0-preview.7",
    "react-native-screens": "~4.22.0",

Testflight expo go. I guess its still packaged using the old version of screens?

**Comment by Ubax** [comment]
@rileysay Can you try with `4.23.0`?

**Comment by chrishutchinson** [comment]
@Ubax fwiw I am using `~4.23.0` and still have this issue (missing icons).

```
"expo": "55.0.0-preview.12",
"expo-router": "55.0.0-preview.9",
"react-native-screens": "~4.23.0",
```

**Comment by beautyfree** [comment]
Same issue with 
```json
"expo": "^55.0.0-preview.12",
"expo-router": "~55.0.0-preview.9",
"react-native-screens": "~4.23.0",
```

**Comment by lorenzocorallo** [comment]
> Same issue with
> 
> "expo": "^55.0.0-preview.12",
> "expo-router": "~55.0.0-preview.9",
> "react-native-screens": "~4.23.0",

Me too

**Comment by valdoth** [comment]
Same issue 
`
"expo": "~55.0.5",
"expo-router": "~55.0.4",
"react-native-screens": ""~4.23.0",
`

**Comment by ddikodroid** [comment]
> using expo-router v6.0.22 using react-native-screens v4.16.0
> 
> import { useRouter } from "expo-router";
> import { Icon, Label, NativeTabs } from "expo-router/unstable-native-tabs";
> import { useEffect } from "react";
> import { translate } from "@/i18n";
> import { useAuth } from "@/modules/auth/hooks/useAuth";
> import { useAppTheme } from "@/utils/useAppTheme";
> 
> export default function TabsLayout() {
> 	const { isLogin } = useAuth();
> 	const { navigate } = useRouter();
> 
> 	useEffect(() => {
> 		if (!isLogin) {
> 			navigate("/auth");
> 		}
> 	}, [isLogin, navigate]);
> 
> 	const {
> 		theme: { colors },
> 	} = useAppTheme();
> 
> 	return (
> 		<NativeTabs
> 			labelVisibilityMode="labeled"
> 			backgroundColor={colors.palette.neutral200}
> 			indicatorColor={colors.palette.accent200}
> 			iconColor={{
> 				default: colors.palette.neutral500,
> 				selected: colors.palette.accent500,
> 			}}
> 			tintColor={colors.palette.accent500}
> 		>
> 			<NativeTabs.Trigger name="index">
> 				<Label>{translate("tabs:home")}</Label>
> 				<Icon
> 					src={{
> 						default: require("../../../assets/tabs/icons/home.png"),
> 						selected: require("../../../assets/tabs/icons/home-selected.png"),
> 					}}
> 				/>
> 			</NativeTabs.Trigger>
> 
> 			<NativeTabs.Trigger name="calculators">
> 				<Label>{translate("tabs:calculator")}</Label>
> 				<Icon
> 					src={{
> 						default: require("../../../assets/tabs/icons/calculator.png"),
> 						selected: require("../../../assets/tabs/icons/calculator-selected.png"),
> 					}}
> 				/>
> 			</NativeTabs.Trigger>
> 
> 			<NativeTabs.Trigger name="learnings">
> 				<Label>{translate("tabs:learnings")}</Label>
> 				<Icon
> 					src={{
> 						default: require("../../../assets/tabs/icons/book.png"),
> 						selected: require("../../../assets/tabs/icons/book-selected.png"),
> 					}}
> 				/>
> 			</NativeTabs.Trigger>
> 
> 			<NativeTabs.Trigger name="scams">
> 				<Label>{translate("tabs:scams")}</Label>
> 				<Icon
> 					src={{
> 						default: require("../../../assets/tabs/icons/shield.png"),
> 						selected: require("../../../assets/tabs/icons/shield-selected.png"),
> 					}}
> 				/>
> 			</NativeTabs.Trigger>
> 
> 			<NativeTabs.Trigger name="profile">
> 				<Label>{translate("tabs:profile")}</Label>
> 				<Icon
> 					src={{
> 						default: require("../../../assets/tabs/icons/user.png"),
> 						selected: require("../../../assets/tabs/icons/user-selected.png"),
> 					}}
> 				/>
> 			</NativeTabs.Trigger>
> 		</NativeTabs>
> 	);
> }
> still not getting the icons in tab bar
> 
> <img alt="Image" width="828" height="220" src="https://private-user-images.githubusercontent.com/88301047/540557554-b498e10c-5a81-485e-92de-e8e8d745ae87.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzMxNTkxMTksIm5iZiI6MTc3MzE1ODgxOSwicGF0aCI6Ii84ODMwMTA0Ny81NDA1NTc1NTQtYjQ5OGUxMGMtNWE4MS00ODVlLTkyZGUtZThlOGQ3NDVhZTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzEwVDE2MDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZjFmOWNkYTAxNmI3YTE5MTE3MTNkMDBhYmVmZjA3M2MyYmNhNjM2MGUxZDIwMzg0MDk2OGY5MzJjZGQzOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n2kK2be_Xr1X0IYFH9aOPFpJpk3TY2b1n5jjIBGbDUA">

Have you able to solve it?

**Comment by rileysay** [comment]
It won’t work on Expo Go until the next TestFlight release, which Apple is currently taking a while to approve. Current version is bundled with the older version of screens. Believe it should work on development builds

**Comment by vicovictor** [comment]
So what is the latest compatible `react-native-screens` version that works with Expo 54 and 55 and expo-router respectively? I'm currently using `react-native-screens` 4.16.0 and need to update to at least 4.19.0 to resolve https://github.com/software-mansion/react-native-screens/issues/3834

**Comment by ddikodroid** [comment]
> So what is the latest compatible `react-native-screens` version that works with Expo 54 and 55 and expo-router respectively? I'm currently using `react-native-screens` 4.16.0 and need to update to at least 4.19.0 to resolve [software-mansion/react-native-screens#3834](https://github.com/software-mansion/react-native-screens/issues/3834)

i think the latest compatible version for sdk 54 is 4.19.0

**Comment by sun-ergo-s** [comment]
There's a new version of Expo Go on TestFlight (55.0.31) that fixed the problem for me.

**Comment by marijang** [comment]
not working with 4.25.0

**Comment by khanh-smv** [comment]
Similar issue, both icon and text does not display. Even on default template `yarn create expo-app --template default@sdk-57`

```json
"expo": "~57.0.14",
"expo-router": "~57.0.14",
"expo-glass-effect": "~57.0.1",
"react-native-screens": "~4.26.0",
```

**Comment by Ubax** [comment]
@expo-bot verify
