### ISSUE TITLE
Error while using @expo/vector-icons on snack

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#423]
Hi guys, 
im getting a wired issue when i try to use the @expo/vector-icons dependency in my snack file

here the example file:
https://snack.expo.io/r146zG8UZ

and here an capture:
![screen shot 2017-07-26 at 10 02 59 am](https://user-images.githubusercontent.com/140472/28622228-2c8a2ab6-71ea-11e7-84fd-f89e514b4836.png)

**Comment by jesseruder** [comment]
Hi @outaTiME we're looking into this. Should be fixed later today.

**Comment by outaTiME** [comment]
Thanks !!!

**Comment by jesseruder** [comment]
Fixed

**Comment by outaTiME** [comment]
Great @jesseruder it works as expected, but the snack status bar still showing "installing dependencies" with never-ending spinner ... mmm something is probably still wrong right?

**Comment by jesseruder** [comment]
Can you send me another screenshot?

**Comment by satya164** [comment]
Cannot repro with the same code

**Comment by outaTiME** [comment]
Yup, 

screenshot:
![screen shot 2017-07-26 at 4 45 33 pm](https://user-images.githubusercontent.com/140472/28640360-daf5ef18-7221-11e7-8d2f-1e49d3698191.png)

animated gif:
https://cl.ly/1P1M0I2p412u/Screen%20Recording%202017-07-26%20at%2004.47%20PM.gif

**Comment by satya164** [comment]
@outaTiME create a new snack

**Comment by outaTiME** [comment]
yup @satya164, if i create a new empty snack and paste the code it works

**Comment by jesseruder** [comment]
If you refresh the page it should also work.

**Comment by outaTiME** [comment]
If i refresh the page doesn't work, but i create a new snack and all goes fine ... i down know why something still broken with this https://snack.expo.io/r146zG8UZ ... but no problem, it was a simple example to show the reported error, thanks !!!

**Comment by jesseruder** [comment]
Thanks for letting us know! Weird that that one is still broken, I'll take a look

**Comment by outaTiME** [comment]
thanks 👍
