### ISSUE TITLE
"Expo SDK requires Expo to run" after opening app in Expo client on Android device"

### ISSUE THREAD

**Issue by ortonomy** [expo/expo#4288]
### Environment

```
Expo CLI 2.18.2 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.3.2 => 3.3.2
    npmGlobalPackages:
      expo-cli: 2.18.2
```

Android physical device running Expo Client: 2.10.6
Device is ``HuaWei ALE-L21``

### Steps to Reproduce

1. press ``a`` to run app on android device
2. runs fine
3. turn off phone
4. turn on and run expo on mac again next morning
5. press ``a`` to run on phone
6. get red screen about SDK not being present

```
NativeModulesProxy.js:28 The "ExpoNativeModulesProxy" native module is not exported through NativeModules; verify that expo-react-native-adapter's native code is linked properly
(anonymous) @ NativeModulesProxy.js:28
Constants.js:3 No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?
(anonymous) @ Constants.js:3
ExceptionsManager.js:76 The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit https://docs.expo.io to learn more about developing an Expo project.
handleException @ ExceptionsManager.js:76
ExceptionsManager.js:76 Module AppRegistry is not a registered callable module (calling runApplication)
handleException @ ExceptionsManager.js:76
```

Yo what? I'm running in Expo!!!

### Expected Behavior

pressing ``a`` allows me to run the app on device every time

### Actual Behavior

it gives me the error above, even when it worked the previous day on same install of Expo on the phone. the only way that it succeeds is if I uninstall and then reinstall the expo app from the Play Store.

### Reproducible Demo

I can't give you a demo.

**Comment by cruzach** [comment]
Hi @ortonomy,

 Sorry you're seeing this issue! Definitely some weird behavior..

Does this happen on a brand new `expo init` project? Also does it only work that one time after reinstalling, and then shows you this error again?

**Comment by blueturtle14g** [comment]
> Hi @ortonomy,
> 
> Sorry you're seeing this issue! Definitely some weird behavior..
> 
> Does this happen on a brand new `expo init` project? Also does it only work that one time after reinstalling, and then shows you this error again?

I got the same after updaing the expo-cli to 3.0.6

**Comment by josehernandezv** [comment]
Same error

**Comment by danhoffman699** [comment]
Yea I have the same issue

**Comment by cruzach** [comment]
If you're having the same behavior, please provide your SDK version, expo-cli version, and Expo Client app version. I haven't been able to reproduce this yet

**Comment by danhoffman699** [comment]
package.json
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll",
    "lint": "eslint --ext .js --ext .jsx ."
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "3.0.3",
    "@material-ui/core": "^4.3.1",
    "@unimodules/core": "^3.0.2",
    "aws-amplify": "^1.1.36",
    "aws-amplify-react-native": "^2.1.16",
    "babel-eslint": "^10.0.2",
    "cross-fetch": "^3.0.4",
    "expo": "^34.0.4",
    "immutable": "^4.0.0-rc.12",
    "prop-types": "^15.7.2",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-bson": "0.0.3",
    "react-native-gesture-handler": "^1.3.0",
    "react-navigation": "^3.11.1",
    "react-redux": "7.1.0",
    "redux": "^4.0.4",
    "redux-persist": "^5.10.0",
    "redux-persist-transform-immutable": "^5.0.0",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.2.0",
    "eslint": "^6.1.0",
    "eslint-plugin-react": "^7.14.3",
    "expo-keep-awake": "^6.0.0",
    "jest-expo": "^34.0.0",
    "schedule": "^0.4.0"
  },
  "private": true
}
```

expo-cli --version
```
3.0.9
```

Expo Client Version: 2.12.0

**Comment by cruzach** [comment]
@danhoffman699 can you try changing your dependencies to those specified in the [SDK 34 release notes](https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319)? Specifically: 
```
"react": "16.8.3"
"react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz"
```

**Comment by danhoffman699** [comment]
Will try that now, thanks

**Comment by danhoffman699** [comment]
Now I'm getting React Native Version mismatch

JavaScript version: 0.59.8,
Native version: 0.57.1"

I'm removing and reinstalling some global packages so that might help. Any suggestions?

**Comment by cruzach** [comment]
There are a few fixes [here](https://github.com/expo/expo/issues/923)

try running `expo start -c` to clear caches

**Comment by danhoffman699** [comment]
Fixed that issue, had to update app.json to match the sdkVersion

**Comment by lkoehl** [comment]
Deleting node_modules and clearing the cache doesn't work for me. Still getting this error.

**Comment by mufaddalhamidofficial** [comment]
You can just clear data of expo client app and re-run.
OR
Uninstall expo-client app and reinstall it.

Don't know why does this happen but this happens now and then with me.

**Comment by alejandropaciotti** [comment]
My 2 cents, I rebooted and it didn't happen again.

**Comment by Pesche007** [comment]
> My 2 cents, I rebooted and it didn't happen again.

You my dear sir are a true wizard of expo. So basically what I did is to uninstall expo, force clear npm cache, re-install expo and still this error popped up. Then, finally, I re-booted and it worked... Thanks

**Comment by mufaddalhamidofficial** [comment]
Congratulations

**Comment by anilozdemir96** [comment]
> > My 2 cents, I rebooted and it didn't happen again.
> 
> You my dear sir are a true wizard of expo. So basically what I did is to uninstall expo, force clear npm cache, re-install expo and still this error popped up. Then, finally, I re-booted and it worked... Thanks

Hello,

I have a same problem and i could not solve it for a week, what do you mean by "rebooting" can you help me please?

**Comment by alejandropaciotti** [comment]
Just turning off and turning on my PC.


Alejandro.Paciotti@gmail.com

**Comment by Gregoirevda** [comment]
Wipe data and cold boot start from Android Studio Virtual Devices

**Comment by Albert-Gao** [comment]
Look, guys, just make sure if your android simulator is connecting to the internet...
Be careful of turning off the firewall

**Comment by boblamceo** [comment]
just do expo-install for the packages you just installed because sometimes the version you installed is not compatible with expo.

**Comment by nicotroia** [comment]
This is happening to me about every ~10 live reloads of the app. I have to shut down the bundler and restart everything to get it back up. On `SDK 38` and `expo-cli 3.25.0`

**Comment by brentvatne** [comment]
@nicotroia - this seems to be happening most frequently due to network connectivity issues with android emulators. if you have some other information to share that would help to reproduce it that would be helpful
