### ISSUE TITLE
Can't schedule local notification on Android on latest expo client

### ISSUE THREAD

**Issue by fhelwanger** [expo/expo#4356]
## 🐛 Bug Report

Every time a try to schedule a local notification on Android using the latest version of Expo Client (the one ready for SDK 33) it throws an error `Invalid time provided`. It worked fine before updating the Expo Client.

### Environment

- Android 7.0
- Expo Client 2.11.0

### Steps to Reproduce

```js
try {
  await Notifications.scheduleLocalNotificationAsync(
    {
      title: 'Title',
      body: 'body',
    },
    {
      time: new Date(Date.now() + 10000),
    }
  );
} catch (e) {
  alert(e);
}
```

### Expected Behavior

It should schedule a location notification without throwing an error.

### Actual Behavior

It always fails regardless of the date.

### Reproducible Demo

https://snack.expo.io/@desenvolvimento.secullum/0ace06

Open this Snack via Expo Client on an Android device and it should alert the error message.

**Comment by tsapeta** [comment]
Hey @fhelwanger, could you try passing `new Date(Date.now() + 10000).toISOString()` instead?

**Comment by fhelwanger** [comment]
Then it says:

`Provided value for "time" is invalid. Please verify that it's either a number representing Unix Epoch time in milliseconds, or a valid date object`

**Comment by arkinem** [comment]
I've also tried to use the moment and convert it into unix ms timestamp. It appears that issue is on the expo api side. Few observations:
- despite the fact that I'm passing correct timestamp for my timezone, I still get UTC time back in the error message with ISO string notation, so it looks like notification is trying to be scheduled for past time
- scheduling it for 1h+ in the future doesn't solve the problem, time is still invalid.

**Comment by fhelwanger** [comment]
I think the problem is because of this change: https://github.com/expo/expo/commit/e01799d18c504186d147bdf089e298145753d2d5#diff-ae8453b34f5c87ce54242f23d4200295

On the SDK, it always convert to Number on Notifications.ts now. But as I'm using SDK 32, it's not doing that. But the updated Java code (which runs on Expo Client now) expects it to be a Number.

**Comment by IElgohary** [comment]
@fhelwanger Did you find any solution or workaround to the problem?

**Comment by guitall** [comment]
Hey guys, I got the same issue. It was working perfectly before the Expo client update to 2.7.11

**Comment by HaJo10** [comment]
Hey guys, I am getting same error since upgrading to SDK 31 from SDK 30 where it run smooth.
SDK 32 same error. 
Expo-CLi is v 2.18.7

**Comment by fhelwanger** [comment]
@IElgohary if I build an APK it works ¯\\\_(ツ)_/¯

I also think that if you use the preview version of SDK 33 (https://blog.expo.io/updated-expo-client-available-on-app-store-and-play-store-8747bd3a1364) it might work, but I haven't tested it.

**Comment by superphil0** [comment]
interesting for me this change fixed it https://github.com/expo/expo/commit/e01799d18c504186d147bdf089e298145753d2d5#diff-ae8453b34f5c87ce54242f23d4200295

Basically you can see that "time" is one time passed as number if iOs with getTime()
but with android it is passed as timeAsDateObj 

This is regarding SDK 32

**Comment by adamsolomon1986** [comment]
any workaround? I'm getting the same error.

**Comment by superphil0** [comment]
The only work around is either to upgrade to sdk 33 or to modify the notifications.js file in your node_modules

**Comment by IElgohary** [comment]
> any workaround? I'm getting the same error.

@adamsolomon1986  I have downgraded expo client on my device to [2.10.0](https://d1ahtucjixef4r.cloudfront.net/Exponent-2.10.0.apk) so now I can test. and according to @fhelwanger , it works on the apk

**Comment by HaJo10** [comment]
I tested with sdk 33 and local notifications work well on android and ios.

`import React from 'react';
import { Button, Platform, StyleSheet, Text, View } from 'react-native';
import * as Permissions from 'expo-permissions'

var moment = require('moment');

export default class App extends React.Component {

  componentDidMount() {
    this._notesChannelCreate();
  }

  _notesChannelCreate = () => {
    if (Platform.OS === 'android') {
        Expo.Notifications.createChannelAndroidAsync('notesEvents', {
        name: 'Event Notes',
        //description: '',
        sound: true,
        priority: 'max',
        vibrate: true,
        badge: true
        });
    }
  }

  _sendNotice = async () => {
    console.log('_sendNotice')
    
      const { status, expires, permissions } = Permissions.askAsync(Permissions.NOTIFICATIONS);
      
      const noteTime = moment().add( 60, 's').toDate();
      console.log('addNote, status:', status, permissions, noteTime);
  
      let noteID = null;
      
      const schedulingOptions = {
                                  time: noteTime
                                };

      const locNotificaton = {
                          title: 'Test notice',
                          body:  'test only',
                          ios: { sound: true },
                          android: { 
                                      channelID: 'notesEvents'
                                    }
                          };
      try {
          const asyncId = await Expo.Notifications.scheduleLocalNotificationAsync(  locNotificaton, 
                                                          schedulingOptions);
          console.log('asyncID:', asyncId);
          noteID = asyncId;
      }catch (error) {
          console.error('Error sending notification (zeeeyou)', error.message);
          console.log('Error sending notification (zeeeyou)', error.message);
      }
      console.log('NoteID:', noteID)
      return noteID || null;
      
  };
  
  render () {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>

        <Button
          title= 'Notification'
          onPress= { () => {
            this._sendNotice();
          } }
        />
      </View>
    );
   };
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});`

**Comment by esamelson** [comment]
Reopening because the fix has landed but has not yet been released to the play store. We're working on it and will update here when it's released!

**Comment by cruzach** [comment]
Closing since this fix was released (also we've added a new notifications module, [`expo-notifications`](https://docs.expo.io/versions/latest/sdk/notifications/), so if you're using the legacy notifications module, you should upgrade to SDK 38 👍 to use the new one)

**Comment by ltsharma** [comment]
Hi, this issue still seems exists.
Im using,
`"expo": "^39.0.0"`
`"expo-notifications": "~0.7.2"`

**Code**
```javascript
await Notifications.cancelAllScheduledNotificationsAsync();
        await Notifications.scheduleNotificationAsync({
            identifier: 'morning-1,
            content: {
                title: `Good Morning!`,
                subtitle: 'Greetings',
                body: `Have a great day`,
                sound: true,
                color: "#ffffff",
                data: {
                    to: 'new-log'
                }
            },
            trigger: {
                hour: 9,
                minute: 0,
                repeats: true
            }
        });
    }
   
    const id = await Notifications.scheduleNotificationAsync({
                identifier: 'night-notification',
                content: {
                    title: `Good Night :)`,
                    subtitle: 'Have a great sleep :D',
                    body: `Have a great sleep :D',
                    sound: true,
                    data: {
                        to: 'new-log'
                    },
                    color: "#000000"                },
                trigger: {
                    hour: 21,
                    minute: 0,
                    repeats: true
                }
            });
    }
```

But it doesn't trigger notifications properly, what i observed, it will show notifications like 3 days once or weekly once or sometimes nothing. it is not trigger on given  time at all.
The same one work fine in android simulator, don't know anyone facing this issue?

**Comment by abdymm** [comment]
> [StackOverflow link](https://stackoverflow.com/q/64264914/3447642)
> Hi, this issue still seems exists.
> Im using,
> `"expo": "^39.0.0"`
> `"expo-notifications": "~0.7.2"`
> 
> **Code**
> 
> ```js
> await Notifications.cancelAllScheduledNotificationsAsync();
>         await Notifications.scheduleNotificationAsync({
>             identifier: 'morning-1,
>             content: {
>                 title: `Good Morning!`,
>                 subtitle: 'Greetings',
>                 body: `Have a great day`,
>                 sound: true,
>                 color: "#ffffff",
>                 data: {
>                     to: 'new-log'
>                 }
>             },
>             trigger: {
>                 hour: 9,
>                 minute: 0,
>                 repeats: true
>             }
>         });
>     }
>    
>     const id = await Notifications.scheduleNotificationAsync({
>                 identifier: 'night-notification',
>                 content: {
>                     title: `Good Night :)`,
>                     subtitle: 'Have a great sleep :D',
>                     body: `Have a great sleep :D',
>                     sound: true,
>                     data: {
>                         to: 'new-log'
>                     },
>                     color: "#000000"                },
>                 trigger: {
>                     hour: 21,
>                     minute: 0,
>                     repeats: true
>                 }
>             });
>     }
> ```
> 
> But it doesn't trigger notifications properly, what i observed, it will show notifications like 3 days once or weekly once or sometimes nothing. it is not trigger on given time at all.
> The same one work fine in android simulator, don't know anyone facing this issue?

Hi  @ltsharma , i also encountered this issue, i even cannot see the notification show i just set up it in 
```
 trigger: {
          seconds: 60,
          repeats: true,
        },
```
but it doesnt show anything


did you solve this problem?

**Comment by ltsharma** [comment]
@abdymm are you checking by closing the app right? and your case seems repetitive duration notification (mine is daily repeat notifications), its working fine in simulator. But in app it didn't work properly.
found one way to get it work in device in development app
for 
``` trigger: {
                    hour: 21,
                    minute: 0,
                    repeats: true
                } 
```
it was not triggering notification when screen is on, when i lock screen, its triggering the notification.

**Comment by abdymm** [comment]
Hi @ltsharma , mine actually only works in STANDALONE APP and it doesnt work when in EXPO CLIENT on android, are you trying this in expo client android?

**Comment by ltsharma** [comment]
Im trying in bare workflow, it is more or less standalone application...

**Comment by abdymm** [comment]
oh i though youare trying in expo client like your title bro @itsharma, allright then, thanks!

**Comment by ltsharma** [comment]
Ops sorry, observed last part of question now, although issue seems same, so reported here.
