### ISSUE TITLE
undefined is not an object (evaluating 'u.default.Mode')

### ISSUE THREAD

**Issue by budziam** [expo/expo#4568]
### Environment

  Expo CLI 2.19.5 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.19.5

### Steps to Reproduce

It's hard to reproduce. I upgraded my huge project from expo 32 to 33. I really do not know what can cause a problem.
Problem exists only on iOS. Android works like a charm.

### Expected Behavior

Standalone application starts correctly.

### Actual Behavior

Standalone application is not starting. In my device logs there is something like:
`undefined is not an object (evaluating 'u.default.Mode')`

![image](https://user-images.githubusercontent.com/10908895/59364207-c2f38380-8d36-11e9-8d59-60db2e6c14ee.png)
![image](https://user-images.githubusercontent.com/10908895/59364212-c5ee7400-8d36-11e9-940c-ea2e70989d41.png)

### Reproducible Demo

It is hard to reproduce it because it only happens in a production build. Application is working correctly in a development mode ( started with an Expo app )

I started using BackgroundFetch feature so I added property `UIBackgroundModes` to my `app.json` file. Do you think it could be related?

**Comment by budziam** [comment]
I've made a little investigation. I cloned expo/expo and greped for `u.default.Mode`. It found

```js
Exponent/Supporting/kernel.ios.bundle:__d(function(g,r,i,a,m,e,d){var t=r(d[0]);Object.defineProperty(e,"__esModule",{value:!0}),e.detectFacesAsync=function(t){var o,f=arguments;return n.default.async(function(l){for(;;)switch(l.prev=l.next){case 0:if(o=f.length>1&&void 0!==f[1]?f[1]:{},u.default.detectFaces){l.next=3;break}throw new c.UnavailabilityError('expo-face-detector','detectFaces');case 3:return l.next=5,n.default.awrap(u.default.detectFaces((0,s.default)({},o,{uri:t})));case 5:return l.abrupt("return",l.sent);case 6:case"end":return l.stop()}})},e.Constants=void 0;var n=t(r(d[1])),s=t(r(d[2])),c=r(d[3]),u=t(r(d[4]));var o={Mode:u.default.Mode,Landmarks:u.default.Landmarks,Classifications:u.default.Classifications};e.Constants=o},851,[1,110,52,573,852]);
```

Interesting part is:
```js
    var o = {
        Mode: u.default.Mode,
        Landmarks: u.default.Landmarks,
        Classifications: u.default.Classifications
    };
```

Then I looked for `Mode: ` and i found:

```js
packages/expo-face-detector/src/FaceDetector.ts:  Mode: ExpoFaceDetector.Mode,
```
```ts
export const Constants = {
  Mode: ExpoFaceDetector.Mode,
  Landmarks: ExpoFaceDetector.Landmarks,
  Classifications: ExpoFaceDetector.Classifications,
};
```

So maybe there is a bug in `ExpoFaceDetector` module? It's a blind shot but I'm trying to figure it out :)

**Comment by szymonzalarski98** [comment]
I've got the same error and I can't fix it. I removed node_modules, after that I run `npm install` and still not works.

**Comment by Tynyndil** [comment]
Same Problem since yesterday , it appeared from nowhere and I just have to reload the app a few times to make it launch again.

**Comment by brentvatne** [comment]
@Tynyndil - on android or ios? client or standalone app?

**Comment by brentvatne** [comment]
@szymonzalarski98 - should be resolved on android, if you clear app data and open the app again it will work

**Comment by szymonzalarski98** [comment]
@brentvatne how can I clear app data?

**Comment by brentvatne** [comment]
@szymonzalarski98 - in the app options in android settings, may be easier to just uninstall it and then run `expo client:install:android`

**Comment by brentvatne** [comment]
@budziam - can you try to do another build of your app now?

**Comment by budziam** [comment]
@brentvatne I built it once more but it did not help. Still the same problem.

**Comment by robmilward** [comment]
I'm having the same issue with a recent project upgraded from Expo SDK 26 to 33, I am directly using the FaceDetector module within this project.

Local development works absolutely fine, there were some API changes to related libraries during the upgrade, but it was a relatively smooth process overall.

Production builds now throw this error, but the difference is for me this is on both iOS and Android.

Will update if I find anything else!

**Comment by robmilward** [comment]
So @budziam, your initial investigation was spot on. I stripped out the reference to the FaceDetector component in my project by simply removing the import and its usages within the definition of my Camera component.. and both the Android & iOS builds worked perfectly.
Fortunately I can build a working version of my application without it.

**Comment by TuninTuna** [comment]
I was having the same problem, even when I pushed the basic app after running `expo init basicapp`. What solved for me was to just run `npm install` and everything got back to normal.

**Comment by kuritz** [comment]
I also just hit this issue yesterday after upgrading from 32 to 33, when building an APK. Stripping out all `FaceDetector` usage is the only thing that has allowed my APK to launch thus far.

I tried rebuilding the APK a few times, cleared all app data on two devices, reset packager and cache, updated the CLI to latest, but none help if I use `FaceDetector`.

I cannot reproduce this error in the expo client when running `expo start --no-dev --minify`.

**Comment by brentvatne** [comment]
@kuritz - can you share a reproducible example?

**Comment by kuritz** [comment]
@brentvatne here is a stripped down example: https://github.com/kuritz/expo-test

There are 3 builds from the 3 branches. The error only occurs on the sdk 33 branch that uses face detector for me.

Hope this helps, let me know if you were looking for something else.

Here's my diagnostic printout:
```
expo diagnostics (sdk-32)

  Expo CLI 2.20.2 environment info:
    System:
      OS: Linux 4.18 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.20.2

expo diagnostics (sdk-33)

  Expo CLI 2.20.2 environment info:
    System:
      OS: Linux 4.18 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      expo: ^33.0.0 => 33.0.6 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.20.2
```

**Comment by brentvatne** [comment]
it looks like we currently exclude face detector from standalone apps: https://github.com/expo/expo/blob/c28cbbcd2b782714d98c9bf1cbace79f91e644d2/android/app/build.gradle#L230-L231

we'll look into it

**Comment by ide** [comment]
This was fixed with an update to Home for SDK 33.

**Comment by Abdelrahman-Nabil** [comment]
Still having the same issue with `FaceDetector` and SDK 33, issue appears on standalone builds only, and gets resolved when i remove `FaceDetector`

**Comment by StevenShadman** [comment]
@ide I'm having the same issue also upgrading to SDK33 running standalone android (fixed by removing face detector). Just tried deleting node modules and reinstalling with no effect. Is there anything else we need to be doing to get this new update?

**Comment by AmitPandya007** [comment]
> This was fixed with an update to Home for SDK 33.

@ide 
Will you please give a guidance how can it be fixed.

**Comment by matias91** [comment]
I'm having the same issue after upgrading to SDK34, on android only.
But I'm not using FaceDetector.
There is any solution or workaround?
Thanks
