### ISSUE TITLE
Warning about "Android App Bundles" is blocking Betatest

### ISSUE THREAD

**Issue by donni106** [expo/expo#4597]
There is a warning at setting up a Betatest for google Play for an Android apk which is blocking. I cannot setup Betatest at the moment. The Button stays grey.

German warning about the not optimized APK:

> Nicht optimiertes APK
> Warnung:
> 
> Mit diesem APK werden ungenutzter Code und ungenutzte Ressourcen an Nutzer gesendet. Deine App könnte kleiner sein, wenn du das Android App Bundle verwendet hättest. Wenn du deine App nicht für Gerätekonfigurationen optimierst, ist deine App größer und braucht länger zum Herunterladen und Installieren auf den Geräten der Nutzer. Größere Apps haben geringere Installations-Erfolgsraten und belegen mehr Speicher auf den Geräten der Nutzer.
> 
> Lösung:
> 
> Das [Android App Bundle](https://g.co/androidappbundle) ermöglicht eine automatische Optimierung für Gerätekonfigurationen. Alternativ kannst du das auch mit mehreren APKs selbst übernehmen.

There is also a canny for this topic: https://expo.canny.io/feature-requests/p/support-android-app-bundles

**I wonder how to release my apk?! Can anybody help? Should I provide more information?**

**Comment by AdamJNavarro** [comment]
Hey @donni106,

This is a warning and as far as I'm aware, it should not block you from uploading/testing any `.apks`. We've seen this before regarding Google's 64-bit warning where users had to make sure they've checked certain boxes before they could submit. I would run through the Play Console and see if that may be the case here. If you have further questions, please create a [forum post](https://forums.expo.io/) as we try to keep Github issues reserved for reproducible bugs!

Cheers,
Adam

**Comment by donni106** [comment]
Thanks @AdamJNavarro, I got that 64-bit warning also.

German warning:

> Warnung
> Dieser Release entspricht nicht der 64-Bit-Anforderung von Google Play
> 
> Die folgenden APKs oder App Bundles sind auf 64-Bit-Geräten verfügbar, haben aber nur nativen 32-Bit-Code: 83.
> 
> Ab dem 1. August 2019 müssen alle Releases der 64-Bit-Anforderung von Google Play entsprechen.
> 
> Du kannst deiner App nativen 64- und 32-Bit-Code hinzufügen. Mit dem Veröffentlichungsformat Android App Bundle erhält jede Gerätearchitektur nur den nativen Code, den sie benötigt. So wird die Größe der App-Datei nicht unnötig erhöht. [Weitere Informationen](https://developer.android.com/distribute/best-practices/develop/64-bit)

**Sadly I cannot find any checkbox to approve this.**

**Comment by donni106** [comment]
Found this in the forum:

> 4 categories with greyed out check boxes. and each box has to be green

<img width="295" alt="Bildschirmfoto 2019-06-14 um 12 15 12" src="https://user-images.githubusercontent.com/1942953/59502450-16341600-8e9e-11e9-985d-18cc05539635.png">

I will try to make them all green and hope to be able to finish the release then.

**Comment by donni106** [comment]
**YES**

<img width="292" alt="Bildschirmfoto 2019-06-14 um 12 23 07" src="https://user-images.githubusercontent.com/1942953/59502866-387a6380-8e9f-11e9-8a36-00ca3ceb7cac.png">

this results in a nice button to start betatest :)

<img width="374" alt="Bildschirmfoto 2019-06-14 um 12 23 38" src="https://user-images.githubusercontent.com/1942953/59502875-403a0800-8e9f-11e9-9c0d-a0cdcf2336e5.png">

**Comment by rahamin1** [comment]
Copied from: https://forums.expo.io/t/how-to-create-a-64-bit-expo-app/23216/8

I tried upgrading to expo 33, which is supposed to create 64-bit binaries, but I still get a warning in google play (“This release is not compliant with the Google Play 64-bit requirement”, “The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code…”)

I don't see the screen mentioned in https://github.com/expo/expo/issues/4597#issuecomment-502054776

### In Google Play Console I have the following:

- On the left hand side I see “App Release”.
- Under this, I click on “Production track -> EDIT RELEASE”. This is where I upload my APK file.
- At the bottom of this screen, I click on “REVIEW”
- Under 'REVIEW SUMMARY" I see:

![image](https://user-images.githubusercontent.com/15701347/59549348-ce2bf680-8f64-11e9-84a6-24b649055afb.png)

- When I click on “Warnings”, I see the following:

![image](https://user-images.githubusercontent.com/15701347/59549361-edc31f00-8f64-11e9-85e1-c4898a136989.png)

**Comment by donni106** [comment]
@rahamin1 

> I don't see the screen mentioned in [#4597 (comment)](https://github.com/expo/expo/issues/4597#issuecomment-502054776)

This is not a screen but a part of the sidebar in the Google Play Console.

**Comment by rahamin1** [comment]
From the main screen of the console, which buttons do you click to see this sidebar?

**Comment by donni106** [comment]
When selected the app from main dashboard screen, there should be a section like "App-Präsenz im Play Store" (German). Looks like this: 
<img width="295" alt="Bildschirmfoto 2019-06-17 um 17 45 49" src="https://user-images.githubusercontent.com/1942953/59618135-dda76d00-9127-11e9-8492-6ce6a46bfc58.png">

**Comment by rahamin1** [comment]
I see it. I already published in the past at the current state of these items. I think that we first need to handle  this: https://github.com/expo/expo/issues/4597#issuecomment-502348541

**Comment by donni106** [comment]
Ah ok yes, somehow two different topics meanwhile. I still have these two warnings.
So I thought they were blocking me, but instead the data provided were not complete.
Now publishing worked, but the warnings are still there.

**Comment by tsapeta** [comment]
Hello,
64-bit support has been released to our builders for SDK33, it's there enabled by default. To get rid of the second warning about unoptimized APK, I recommend to use `-t app-bundle` when running `expo build:android` - this will give you app bundle instead of APK.
