### ISSUE TITLE
SecureStore.setItemAsync causing error on Android API level 22

### ISSUE THREAD

**Issue by sealedHuman** [expo/expo#5003]
### Environment

  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.21.2

Targeting a standalone Android build.

### Steps to Reproduce
1. `expo init Test22` (and go through the prompts to create a simple managed app) OR see [this snack](https://snack.expo.io/@amcauliffebabelstreet/test22) OR clone [this repo](https://github.com/sealedHuman/test22)
1. `cd Test22`
1. `expo ba` (and go through the prompts)
1. Sideload the resulting apk to a Moto X running Android 5.1 via `adb install test22.apk`
1. Tap the button on the app's screen

### Expected Behavior
The text field should change from "waiting..." to "you did it".

### Actual Behavior
Nothing occurs on the app, but logcat produces this error:
`E/ExpoSecureStore: Caught unexpected exception when writing to SecureStore
    java.lang.IllegalStateException: Can't generate certificate
        at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:136)
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
        at expo.modules.securestore.SecureStoreModule$HybridAESEncrypter.initializeKeyStoreEntry(SecureStoreModule.java:499)
        at expo.modules.securestore.SecureStoreModule$HybridAESEncrypter.initializeKeyStoreEntry(SecureStoreModule.java:452)
        at expo.modules.securestore.SecureStoreModule.getKeyEntry(SecureStoreModule.java:314)
        at expo.modules.securestore.SecureStoreModule.setItemImpl(SecureStoreModule.java:112)
        at expo.modules.securestore.SecureStoreModule.setValueWithKeyAsync(SecureStoreModule.java:74)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at org.unimodules.a.c.invokeExportedMethod(ExportedModule.java:96)
        at org.unimodules.adapters.react.NativeModulesProxy.callMethod(NativeModulesProxy.java:117)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:135)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.UnsupportedOperationException: private exponent cannot be extracted
        at com.android.org.conscrypt.OpenSSLRSAPrivateKey.getPrivateExponent(OpenSSLRSAPrivateKey.java:161)
        at org.spongycastle.jcajce.provider.asymmetric.rsa.RSAUtil.a(RSAUtil.java:63)
        at org.spongycastle.jcajce.provider.asymmetric.rsa.DigestSignatureSpi.engineInitSign(DigestSignatureSpi.java:95)
        at java.security.Signature$SignatureImpl.engineInitSign(Signature.java:679)
        at java.security.Signature.initSign(Signature.java:330)
        at com.android.org.bouncycastle.x509.X509Util.calculateSignature(X509Util.java:243)
        at com.android.org.bouncycastle.x509.X509V3CertificateGenerator.generate(X509V3CertificateGenerator.java:434)
        at com.android.org.bouncycastle.x509.X509V3CertificateGenerator.generate(X509V3CertificateGenerator.java:412)
        at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:133)`

### Reproducible Demo
Note: you must build a standalone Android binary and run it on a device running API level < 23 in order to reproduce this.
* https://snack.expo.io/@amcauliffebabelstreet/test22
* https://github.com/sealedHuman/test22

**Comment by asmeikal** [comment]
Same here, same configuration, we get the error running on a PAX A920 with Android 5.1.1, and on the Android Studio emulator.

**Comment by ncailleux** [comment]
Same here, and same issue on Android 21. This issue appear for me when i switch to expo 33 sdk.

**Comment by movibra** [comment]
Karl suggests a solution for this similar issue, i think it is same:
https://stackoverflow.com/questions/48664921/cant-generate-certificate-exception-when-generating-key-pair-in-api-21

**Comment by tattivitorino** [comment]
Have any of you found a solution? @movibra  i've checked the article you suggested but can't figure out how to fix it! Any help will be appreciated!

**Comment by onka13** [comment]
I've same problem on Android 5.0 (API 21)

> "code": "E_SECURESTORE_WRITE_ERROR",
> "nativeStackAndroid": [
> {"methodName": "generateKeyPair","lineNumber": 136,"file": "AndroidKeyPairGenerator.java"},
> {"methodName": "generateKeyPair","lineNumber": 276,"file": "KeyPairGenerator.java"},
> {"methodName": "initializeKeyStoreEntry","lineNumber": 499,"file": "SecureStoreModule.java"},
> {"methodName": "initializeKeyStoreEntry","lineNumber": 452,"file": "SecureStoreModule.java"},
> {"methodName": "getKeyEntry","lineNumber": 314,"file": "SecureStoreModule.java"},
> {"methodName": "setItemImpl","lineNumber": 112,"file": "SecureStoreModule.java"},
> {"methodName": "setValueWithKeyAsync","lineNumber": 74,"file": "SecureStoreModule.java"},
> {"methodName": "invoke","lineNumber": -2,"file": "Method.java"},
> {"methodName": "invoke","lineNumber": 372,"file": "Method.java"},
> {"methodName": "invokeExportedMethod","lineNumber": 96,"file": "ExportedModule.java"}]

**Comment by sjchmiela** [comment]
Hey guys, sorry for taking so long to look into the issue. I have fixed it on `master` and will backport it to SDK34 builders once either a couple of days pass or enough post-release fixes are merged to `master`. 🙂

**Comment by ncailleux** [comment]
Hi @sjchmiela
So right now it's pushed ? If i upgrade to expo 34 and make a build , this error won't append again ?

Thanks

**Comment by changLiuUNSW** [comment]
Hi @sjchmiela 
The issue still exist in SDK 34:
https://github.com/expo/expo/issues/5236

**Comment by sjchmiela** [comment]
If your app is ejected — try upgrading to `expokit@34.0.2` and rebuilding your app.

**Comment by changLiuUNSW** [comment]
Hi @sjchmiela 
I just tried. The error still exist after upgrading to ```expokit@34.0.2```

**Comment by aniltirola** [comment]
The problem still exists. Tested with a fresh installation, then ejected.

```
// package.json:
"expo": "^34.0.1",
"expo-secure-store": "~6.0.0",
"expokit": "34.0.2",

```

Error extracted from logcat:
```
08-27 09:43:06.651 3670-3779/com.checksecurestore E/ExpoSecureStore: Caught unexpected exception when writing to SecureStore
    java.lang.IllegalStateException: Can't generate certificate
        at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:136)
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
        at expo.modules.securestore.SecureStoreModule$HybridAESEncrypter.initializeKeyStoreEntry(SecureStoreModule.java:501)
        at expo.modules.securestore.SecureStoreModule$HybridAESEncrypter.initializeKeyStoreEntry(SecureStoreModule.java:454)

```

Tested in 

- emulator, android, lollipop, api-level 21
- emulator, android, lollipop, api-level 22

**Comment by stevematdavies** [comment]
Same here expo 35 Android 28
