### ISSUE TITLE
expo ads facebook throwing error: The SDK version in the ad request is no longer supported

### ISSUE THREAD

**Issue by mojodev** [expo/expo#5028]
I have integrated facebook ads using Expo v33. but it is throwing error on app load **"The SDK version in the ad request is no longer supported for new apps. Please upgrade to one of the latest versions of the SDK"**.  next time it is throwing error like: **"Ad was re-loaded too frequently"**.
 I have seen same type of issue on github and stack overflow. one of the solution was upgrading the audiance network sdk to 5+ fix this issue. but Expo v33 already using `audience-network-sdk:5.1.1`. i already spent 6-7 hour on this issue and din't get any solution. any suggestion or solution will be appreciated.

check Reproducible Demo : [https://snack.expo.io/H1vxnXGfS](https://snack.expo.io/H1vxnXGfS)

**Error response** :
 `error Z {
  "_dispatchInstances": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "_dispatchListeners": [Function onError],
  "_targetInst": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "bubbles": undefined,
  "cancelable": undefined,
  "currentTarget": 257,
  "defaultPrevented": undefined,
  "dispatchConfig": Object {
    "registrationName": "onAdError",
  },
  "eventPhase": undefined,
  "isDefaultPrevented": [Function K],
  "isPropagationStopped": [Function K],
  "isTrusted": undefined,
  "nativeEvent": Object {
    "errorCode": 1203,
    "errorMessage": "The SDK version in the ad request is no longer supported for new apps. Please upgrade to one of the latest versions of the SDK",
  },
  "target": undefined,
  "timeStamp": 1563729189862,
  "type": undefined,
}`

**Comment by girishjjain** [comment]
👍 Same error

**Comment by girishjjain** [comment]
Any updates on this issue? Acknowledgement of the issue would help as a first step. Also, I hear Expo SDK 34 is coming out soon, hoping this gets addressed with it. Thanks.

**Comment by girishjjain** [comment]
Looks like I was bit behind v34 is already out. I tried with Expo SDK v34 and still got same error. Any guidance on when we could see this being addressed? Do we have to wait until next SDK release or could it be addressed as part of an update to `expo-ads-facebook` package? Thanks.

**Comment by lithiumtechcom** [comment]
> Looks like I was bit behind v34 is already out. I tried with Expo SDK v34 and still got same error. Any guidance on when we could see this being addressed? Do we have to wait until next SDK release or could it be addressed as part of an update to `expo-ads-facebook` package? Thanks.

Same situation as yours: eject + expo SDK 34 + FB ads 5.+
and still show "error Ad was re-loaded too frequently"

Please update facebook ads SDK soon

**Comment by RodolfoGS** [comment]
Same error in expo SDK 34, please update it.

![IMG_83E707A8FC40-1](https://user-images.githubusercontent.com/870365/62828174-78ef1880-bb94-11e9-892d-15569ab21063.jpeg)

**Comment by lithiumtechcom** [comment]
is there any update on this issue?

**Comment by morenoh149** [comment]
Encountering same issue. Happy to dedicate an engineer to fix this. Should we eject from expo to use the latest Facebook sdk?

**Comment by knightkhan** [comment]
skd 35
i am geting same problem
error SyntheticEvent {
  "_dispatchInstances": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "_dispatchListeners": [Function onError],
  "_targetInst": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "bubbles": undefined,
  "cancelable": undefined,
  "currentTarget": 219,
  "defaultPrevented": undefined,
  "dispatchConfig": Object {
    "registrationName": "onAdError",
  },
  "eventPhase": undefined,
  "isDefaultPrevented": [Function functionThatReturnsFalse],
  "isPropagationStopped": [Function functionThatReturnsFalse],
  "isTrusted": undefined,
  "nativeEvent": Object {
    "errorCode": 1002,
    "errorMessage": "Ad was re-loaded too frequently",
  },
  "target": undefined,
  "timeStamp": 1569859582688,
  "type": undefined,
}
Running application on HTC Desire 630 dual sim.
error SyntheticEvent {
  "_dispatchInstances": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "_dispatchListeners": [Function onError],
  "_targetInst": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "bubbles": undefined,
  "cancelable": undefined,
  "currentTarget": 219,
  "defaultPrevented": undefined,
  "dispatchConfig": Object {
    "registrationName": "onAdError",
  },
  "eventPhase": undefined,
  "isDefaultPrevented": [Function functionThatReturnsFalse],
  "isPropagationStopped": [Function functionThatReturnsFalse],
  "isTrusted": undefined,
  "nativeEvent": Object {
    "errorCode": 1002,
    "errorMessage": "Ad was re-loaded too frequently",
  },
  "target": undefined,
  "type": undefined,
}

**Comment by knightkhan** [comment]
audience-network-skd-5.1.1 is attacted with it 
can any one how can i update it  audience-network-skd-5.5.0 
in build gradal of expo-ads-facebook

**Comment by girishjjain** [comment]
I tried with Expo SDK v35 and this issue appears to have been resolved, at least for me it is. Lack of updates/communication from Expo team is baffling though. Doesn't look like they're are tracking this one.

**Comment by morenoh149** [comment]
sdk was updated in https://github.com/expo/expo/commit/5c9913eca88eef7beefa7d1a43cb5a38b37327b9

@girishjjain there's just too much work for too few engineers. Be polite and be helpful.

**Comment by le-van-tuan** [comment]
@morenoh149 Thank you so much, bro

**Comment by littleboy1407** [comment]
expo SDK 34 + FB ads 5.+
on Android still show "error Ad was re-loaded too frequently" but on ios working normal, pls help me @morenoh149

**Comment by SafiDS** [comment]
Just Changes Facebook SDk Version in  ...node_modules/expo-ads-facebook/android/build.gradle

dependencies {
  unimodule 'unimodules-core'
  api 'com.facebook.android:audience-network-sdk:5.+'  **//Add this**
}

Just changes this line and its working

**Comment by vandrieu** [comment]
@SafiDS here is what I did:

1. Updated `node_modules/expo-ads-facebook/android/build.gradle` to:
```
dependencies {
  unimodule 'unimodules-core'
  api 'com.facebook.android:audience-network-sdk:5.9.0'
}
```

2. Run `expo build:android -t apk`

3. Install standalone apk on my android phone

4. I still get no ads in my app

5. Look into the logs and saw this:
`interstitial error Error: The SDK version in the ad request is no longer supported for new apps. Please upgrade to one of the latest versions of the SDK`
Just like before modifying the gradle file.

Any idea what I'm doing wrong ?

I have a "normal" expo project (no expokit, no eject, no bare) with SDK 37. You too?

**Comment by girishjjain** [comment]
I believe this issue is resolved for iOS but still there for Android platform. Sounds like those using bare workflow can take care of this by upgrading the package directly (I haven't tried it though) but those using managed workflow are probably stuck? Expo SDK v38 is released today but doesn't look like this is resolved. If you're using managed workflow and have any guidance, please share. Thanks!

**Comment by cristoferraobluestream** [comment]
is this issue solved i am also having the same problem

**Comment by csumrell** [comment]
I am getting the same issue with SDK 37 and upgraded to 38 with same issue on IOS and Android

**Comment by jaymovaliya** [comment]
I am getting the same issue on SDK 38, any solution to this problem?
I am testing it on android

**Comment by jaymovaliya** [comment]
I solved it by adding these lines in android/app/build.gradle (Only on android not sure about ios)
`implementation 'com.android.support:support-annotations:28.0.0'`
`implementation 'com.facebook.android:audience-network-sdk:5.+'`
as stated by facebook documentation for android:- [https://developers.facebook.com/docs/audience-network/guides/adding-sdk/android](url)

**Comment by Jordan-Loeser** [comment]
Unfortunately I am also experiencing this issue with SDK 37 on iOS. If I am able to find a solution I will share it here.

**Comment by abudhia-oyo** [comment]
Anyone found any solution to this?
