### ISSUE TITLE
Authenticate with google doesn't redirect back to app

### ISSUE THREAD

**Issue by ozanturksever** [expo/expo#53]
Authenticate with google(on Android) redirects to google.com not to app itself.  
Can be reproduced with exp.host@notbrent/native-component-list  google auth button.

url redirected:
`https://accounts.google.com/o/oauth2/v2/auth?redirect_uri=host.exp.exponent%3A%2Foauthredirect&client_id=733666839474-29hiep386cbm9u262lvgjf96uvq8pglu.apps.googleusercontent.com&response_type=code&state=hZ3f26YcYdrzfQLpvWRm7w&scope=profile%20email&code_challenge=5xHtVcrqLe_hCKOnj_rLYgjSRZut98C8O3ATsMfS8j8&code_challenge_method=S256`

```js
Exponent.Google.logInAsync({
    behavior: 'web',
    androidClientId: '733666839474-29hiep386cbm9u262lvgjf96uvq8pglu.apps.googleusercontent.com',
    iosClientId: '733666839474-l0s6c0d1m4f844cin668iilgears8b2n.apps.googleusercontent.com',
    androidStandaloneAppClientId: '733666839474-g2i9bjpet38je9159v6aq2s822pk2rop.apps.googleusercontent.com',
    iosStandaloneAppClientId: '1052406890180-eo50cdr1fnqu0kgpg3rh8hvchb49vf98.apps.googleusercontent.com',
    scopes: ['profile', 'email'],
  })
  .then((result) => {
    if (result.type === 'success') {
      return path.success({ accessToken: result });
    }
    return path.failed({ accessToken: err });
  })
  .catch(err => path.failed({ accessToken: err }));
```

**Comment by terribleben** [comment]
@brentvatne or @janicduplessis might have more thoughts about this.

**Comment by janicduplessis** [comment]
What android version are you using?

**Comment by ozanturksever** [comment]
i am testing on 6.0.1

**Comment by brentvatne** [comment]
@janicduplessis - what's the status of this? I believe I recall seeing a fix a couple weeks ago

**Comment by janicduplessis** [comment]
Yes, we introduced a bug in sdk 14, it should be fixed now.

**Comment by ozanturksever** [comment]
it doesn't look fixed. I tried again and redirected to google.

**Comment by omerdn1** [comment]
@janicduplessis I can confirm It's not fixed, running sdk 14.

**Comment by janicduplessis** [comment]
Are you testing on a real device or the simulator? Also what browser is installed on it? I'm asking because on the Android simulator the installed browser is usually WebviewBrowser and it doesn't support app scheme redirects.

**Comment by ozanturksever** [comment]
yes, i am on a real device.

**Comment by omerdn1** [comment]
@janicduplessis Works prefectly fine on a real device, thank you for clarifying.

**Comment by terribleben** [comment]
It sounds like this was an issue with device vs. emulator and is resolved - let me know if this should still be open.

**Comment by pandananta** [comment]
I'm experiencing this same issue on sdk 28, using a real device (Google Pixel)

**Comment by Nahani** [comment]
I have the same issue on sdk 31, using real device. After loggin we are not redirect to the app but to the web page google.com

**Comment by opringle** [comment]
Also experiencing this issue with a real google pixel 3.

**Comment by gauravsaluja2006** [comment]
I'm experiencing this same issue on sdk 32 on a OnePlus5. 
Although the same code is working on iPhone.

**Comment by MonasteryJohn** [comment]
Not sure if this will help anyone else, but I found that I would run into this problem on a real device if my android package name had a mix of upper and lower case letters. 

For example, com.company.AppName would cause the redirect to google.com, whereas com.company.appname would be perfectly happy.

In my case it made no difference whether the Google oAuth credential was set to the same upper case version or not, it just didn't work that way at all.

**Comment by QuintonC** [comment]
>...
> For example, com.company.AppName would cause the redirect to google.com, whereas com.company.appname would be perfectly happy.
>...

This worked for me as well. Huge thank you (and good find) @MonasteryJohn.

**Comment by jitenderchand1** [comment]
facing the same issue. I have my package name in all lower case

**Comment by QuintonC** [comment]
> facing the same issue. I have my package name in all lower case

Which sdk? Are you detached?

**Comment by jitenderchand1** [comment]
not detached from expo. This is happing on real android device.


```
const result = await Google.logInAsync({
      behavior: 'web',
      androidStandaloneAppClientId:
        '131814552849-iwyqerbsbadf78623gjsfd.apps.googleusercontent.com',
      iosClientId:
        '131814552849-asdfsakwero9879sdhjkfs.apps.googleusercontent.com',
      scopes: ['profile', 'email']
    });
```

```"expo": "^33.0.0",
    "expo-asset": "^5.0.1",
    "expo-blur": "^5.0.1",
    "expo-linear-gradient": "^5.0.1",
    "firebase": "^6.2.4",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "^0.59.9",
    "react-native-animatable": "^1.3.2",
    "react-native-confirmation-code-input": "^1.0.4",
    "react-native-elements": "^1.1.0",
    "react-native-material-textfield": "^0.12.0",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.0",
    "react-redux": "^7.1.0",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"```

**Comment by jitenderchand1** [comment]
following code is working fine with android emulator.

```
const result = await Google.logInAsync({
      behavior: 'web',
      androidClientId:
        '131814552849-lkahdfiowyerioyowjasd.apps.googleusercontent.com',
      iosClientId:
        '131814552849-asdfkheioryuowsdknk.apps.googleusercontent.com',
      scopes: ['profile', 'email']
    });
```

While created a `clientId` I used `host.exp.exponent` as a packge name. But while creaed a standalone build by running `expo build:android` my `app.json` file has different packge name.
