### ISSUE TITLE
Expo 35 on iOS 13.0 dismissBrowser crashes app

### ISSUE THREAD

**Issue by markholland** [expo/expo#5742]
### Environment

Expo CLI 3.1.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~/n/bin/node
      Yarn: 1.12.3 - ~/n/bin/yarn
      npm: 6.11.3 - ~/n/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.7 => 4.0.7
    npmGlobalPackages:
      expo-cli: 3.1.0

iOS 13.0, doesn't occur on iOS 12

### Steps to Reproduce

Import expo-web-browser and call dismissBrowser function

### Expected Behavior

Nothing to happen

### Actual Behavior

App crashes

### Reproducible Demo
```
import React from 'react';
import { View, Button } from 'react-native';
import * as WebBrowser from 'expo-web-browser';

export default function App() {
  return (
    <View>
      <Button
        title='press me'
        onPress={() => {
          WebBrowser.dismissBrowser()
        }}
      />
    </View>
  );
}
```

**Comment by sjchmiela** [comment]
Hm… your example application haven't opened the browser to dismiss and still it tries to dismiss one, right?

**Comment by markholland** [comment]
To provide the simplest reproduction yes. The real world app would have a browser open in this situation but considering the crash happens regardless I felt it wasn't necessary to provide anything more elaborate.

**Comment by sjchmiela** [comment]
Ah, ok, I can see the problem, on it

**Comment by schellack** [comment]
We do something similar using @aws-amplify/auth, where we follow [their example for Expo users](https://aws-amplify.github.io/docs/js/authentication#a-note-for-expo-users) to call `WebBrowser.dismissBrowser()`, which causes the crash on iOS 13.

**Comment by sjchmiela** [comment]
Merged the fix to `master` and `sdk-35` release branch. It will be release in Expo client if we push an update in the middle of cycle and it has been just released as `expo-web-browser@7.0.1` for bare and ejected projects. 🙂

**Comment by suitupalex** [comment]
@sjchmiela pardon my ignorance, but does something need to be deployed on the Expo build cloud services to fix this issue?

I'm using the managed workflow and updated to `expo-web-browser@7.0.1` but I'm still getting the crash on standalone builds.

**Comment by kakemotokeita** [comment]
Me, too. I'm also using `expo-web-browser@7.0.1` , sdk 35, iOS13.1. And it's crash even in expo client app.

**Comment by DianaKoenraadt** [comment]
Hi, we're also using `expo-web-browser@7.0.1`, sdk 35, iOS 13. Same here, it crashes in Expo client (we don't have a standalone app yet)

**Comment by tomgranerod** [comment]
Having the same issue as previous posts. Any chance of a minor release of SDK 35 soonish? If not I'm forced to eject or downgrade to SDK 34.

**Comment by cruzach** [comment]
We'll be deploying the fix to our SDK 35 builders soon, just running final tests. I'll update here once we do, thanks everyone for being proactive and reporting this

**Comment by DianaKoenraadt** [comment]
@cruzach Thanks for the prompt reply. 
Can you maybe explain what it means "Fix has been deployed to SDK 35 builders"? Does that mean we have to wait for SDK 35.0.1?

**Comment by cruzach** [comment]
Sorry, should've been clearer 😅 

No, you don't have to wait. If you build your SDK 35 app now using `expo build:ios`, your new binary will have the fix

**Comment by markholland** [comment]
When will expo client be updated with the fix as it will still crash in dev on an iOS 13 simulator.

**Comment by cruzach** [comment]
The Expo Client will be updated with our next SDK release (36). Until then, you could always build your app direcrtly onto the simulator:

> To run it on your iOS Simulator, first build your expo project with the simulator flag by running `expo build:ios -t simulator`, then download the tarball with the link given upon completion when running expo build:status. Unpack the tar.gz by running `tar -xvzf your-app.tar.gz.` Then you can run it by starting an iOS Simulator instance, then running `xcrun simctl install booted <app path>` and `xcrun simctl launch booted <app identifier>`.

**Comment by iamdavidmartin** [comment]
do you have a rough estimate of when we can expect SDK 36? (days, weeks or months away?).

thanks for all you do. i love expo.

**Comment by cruzach** [comment]
Weeks, it's not too far off 😄 

Thanks, we really appreciate your support!
