### ISSUE TITLE
Hot reloading not working on multiple active devices?

### ISSUE THREAD

**Issue by daformat** [expo/expo#580]
Basically I'm having trouble with hot reloading on multiple devices. I can be successful in having one of them to hot reload, but then I have to manually reload on the others (wether they are actual physical devices or simulator instances doesn't seem to affect the outcome).

Using expo tunnel to connect (default) or LAN doesn't help getting more than one device to hot reload.

Is this a bug? A feature? Anything I'm not seeing that I should do?

**Comment by daformat** [comment]
Oh, actually, this seems to be a duplicate of a closed issue (https://github.com/expo/expo/issues/20) sorry about that…

But then, what's the status in the end, is the react native HMR implementation at fault here?

**Comment by SleeplessByte** [comment]
This isn't react-native nor expo. 

The way the current HMR is implemented (either react-native and react) only allows for one hot-loaded device connection to be active at any given time.

**Comment by daformat** [comment]
Thanks for clarification. Hope this gets changed sometime, it would tremendously help on react-native projects.

**Comment by cdock1029** [comment]
Fixed? https://github.com/facebook/react-native/commit/8b2975ad7b27ce34dcf56836685fd54ddd62086c

**Comment by ide** [comment]
^ That commit will ship with RN 0.49 which should go out with Expo SDK 22.

**Comment by tonyxiao** [comment]
So as of the latest expo sdk 27 - I'm still experiencing issue where hot reload would only ever work on one device at a time. Is it suppose to work in SDK 27?

**Comment by davidbiller** [comment]
Version 2.24.4 (2.24.4.53441)
new generated app - same prob.

**Comment by EvanBacon** [comment]
@davidbiller  I can't reproduce, working on every device I can find. Can you share some info on your devices and computer, are they all on the same network?

**Comment by davidbiller** [comment]
Its on The Simulator too. So i Hope my simulator is on The same Network 😂👌
So i reinstalled expo, and watchman. Still not working.

**Comment by EvanBacon** [comment]
Windows computer? Android simulator? I have established that this works on a mac with physical iOS and Android devices.

**Comment by davidbiller** [comment]
OS: macOS 10.13.4 (17E202)
Simulator: 
Version 10.0 (SimulatorApp-851.2 CoreSimulator-518.19) iOS
XDE:
Version 2.24.4 (2.24.4.53441)

Node modules already new installed. yarn.lock deleted. package lock deleted.

**Comment by tonyxiao** [comment]
Yea i just tried again today and same issue. Latest expo client.

**Comment by davidbiller** [comment]
Use 5.0.0 mobx than it will work @tonyxiao

**Comment by tonyxiao** [comment]
@davidbiller can you clarify? What does this have to do w/ MobX btw?

**Comment by davidbiller** [comment]
@tonyxiao there is an bug in mobx, it Dosent reRender. So you are thinking your Hot reloading is not working. Try it 👍

**Comment by tonyxiao** [comment]
hmm, however @davidbiller i'm not actually using mobx in my app at all.

**Comment by trickeyd** [comment]
I am also getting this. My project is an ejected expo project, now on RN 54.4.

Just doing my final view fixes across as many different sized displays as possible, and refreshing and navigating to certain screens is really time consuming so would be amazing to have them all hot reloading.

I'm a bit confused with this thread. Is this working for some people? And was it supposed to be fixed in RN 0.49?

**Comment by rahamin1** [comment]
@daformat I am trying to figure out how to use Expo with two devices. I tried to ask in the expo forum, but didn't get a reply. Since you seem to make it work  I assume that it is possible. :) 
How? Is there any documentation about it?

**Comment by daformat** [comment]
@rahamin1 It's been a while since I haven't used Expo but I simply scanned the QR code on both devices

**Comment by SleeplessByte** [comment]
What @daformat says is correct. Either that or use the expo app on both.
