### ISSUE TITLE
Document picker not working with publish iOS app

### ISSUE THREAD

**Issue by maharjanaman** [expo/expo#589]
I am using DocumentPicker API to upload files. Its working well with android application, both with expo client and published apps. But for some reason, its not working with iOS platform.
Do I need to define some permission or something???
I'm using sdk v20.0.0

**Comment by dikaiosune** [comment]
Hi! Thanks for the report. Could you provide an example using [Snack](https://snack.expo.io) which demonstrates this issue?

**Comment by maharjanaman** [comment]
Hello, I implemented documentpicker in same way as this
https://snack.expo.io/ryfSWKRGW
It works when testing with expo client but when testing with testflight or after publishing it to app store, it doesn't work.

**Comment by terribleben** [comment]
Hi, you may need to enable iCloud Documents for your App Id on the Apple developer website. We [document this](https://docs.expo.io/versions/latest/guides/advanced-expokit-topics.html#using-documentpicker) for ExpoKit but it seems like we may need to also add a note for standalone apps. @janicduplessis what are your thoughts?

**Comment by janicduplessis** [comment]
@terribleben Yea it's probably that it's also needed for standalone apps. I think we already edit the entitlement file in the standalone app builder so that part should work.

**Comment by janicduplessis** [comment]
@maharjanaman Could you try following the link @terribleben linked and see if it works, if it is the case we'll update the doc to mention this.

**Comment by maharjanaman** [comment]
Hello,
@janicduplessis The link provide by @terribleben only shows documentation for detach apps. I have build ipa file using exp build:ios and could find no documentations for enabling feature in such case. Could you suggest me any documentation or process. I'm really in turmoil here.

**Comment by terribleben** [comment]
@maharjanaman try logging in to the Apple Developer website and adding iCloud Documents to your app id.

**Comment by maharjanaman** [comment]
@terribleben, thanks for response. I enable iCloud on developer website but still not working. Do I need to submit new build or wait for some time period?

**Comment by terribleben** [comment]
I think you may need to re-run `exp build` now that your app id has that entitlement enabled.

**Comment by maharjanaman** [comment]
Ok I'll give it a try

**Comment by maharjanaman** [comment]
@terribleben, the issue still persists even with iCloud enabled on apple developer site. Any suggestions?

**Comment by terribleben** [comment]
Hmm, okay, maybe something else is causing the problem. Can you provide more information about what happens when you try to use it in a published app other than "doesn't work"? We can take a look.

**Comment by maharjanaman** [comment]
Hello, thanks for responses. These log came up while trying to use document picker:
- Exponent(Foundation)[836] <Notice>: *** Assertion failure in -[UIDocumentMenuViewController _commonInitWithCompletion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3600.7.47/UIDocumentMenuViewController.m:122
- Exponent(CFNetwork)[836] <Notice>: TCP Conn 0x170199160 canceled

**Comment by herdani** [comment]
+1

**Comment by charlesvinette** [comment]
Hello @herdani and @maharjanaman. Thanks for the additional info @maharjanaman we figured out the issue and you can expect a fix in the near future. Thanks!

**Comment by christiangenco** [comment]
My `DocumentPicker.getDocumentAsync()` is crashing with [a very minimal test](https://snack.expo.io/HJ4quZV2b) on iOS:

`<Button
          onPress={() => DocumentPicker.getDocumentAsync()}
          title="Crash this app on iOS"
        />`

When run on an ExpoKit detached app, I get the cryptic `libc++abi.dylib: terminating with uncaught exception of type NSException` when it crashes, even with iCloud enabled on apple developer site.

Will this be fixed soon?

**Comment by charlesvinette** [comment]
Hello guys, sorry I haven't updated the issue in a little while. A PR is up to possibly fix the issues on Standalone builds, I will keep you in the loop once it is merged. Thanks for your patience!

**Comment by christiangenco** [comment]
$15 bump: https://www.bountysource.com/issues/48965248-document-picker-not-working-with-publish-ios-app

**Comment by terribleben** [comment]
I believe this is fixed in https://github.com/expo/xdl/commit/1b22af2953088848692e2879ad8014f3d30aaf37 which will roll out alongside SDK 22 sometime this week.

**Comment by christiangenco** [comment]
On iOS 10.0.3 (15A432) on a 12.9in iPad Pro on Expo Client 2.0.1, [my minimal test](https://snack.expo.io/HJ4quZV2b) still crashes.

**Comment by charlesvinette** [comment]
Hey Christian! Thanks for the update, I will look into your example on
Monday. Have a great weekend!

**Comment by charlesvinette** [comment]
Hi @christiangenco! I just tested your app on Expo Client 2.0.1 on my phone and everything is running fine here. However I am on iOS 11. I just want to confirm, the app crashes even when ran in Client. You tap the button and it force close the Client?

**Comment by mobiusnz** [comment]
I can confirm it happens for me too - the crash occurs after you pick a file

**Comment by charlesvinette** [comment]
Ahh @mobiusnz gotcha. I believe the original issue of this thread was that the document picker doesn't open on Standalone app, the crash once you pick a file is something else.

With that said, I just tried the Snack that @christiangenco posted and selecting a file isn't crashing on my end, I'll try to have someone with 10.3 test on their device.

**Comment by mobiusnz** [comment]
I'm on 11.0.3 (I think @christiangenco might have made a typo as 11.0.3 is build 15A432)
I've done a little more testing, and the crash only appears to occur when I pick a document saved in iCloud. 
I tried again browsing through Dropbox and it didn't crash.

**Comment by charlesvinette** [comment]
Hey @mobiusnz, thanks again for the additional info. I made a gif of me using the minimal test that Christian wrote. When I tap a file that is on iCloud, it works fine. Can you tell me if anything is different when you do the same thing? Trying to find a common denominator!

Running on iPhone 7 with iOS 11

Here it is-> https://media.giphy.com/media/3o6nVa3CsdCP6MkdyM/giphy.gif

**Comment by mobiusnz** [comment]
Ah, seems to be a filetype issue. It looks like it crashes when picking any Apple iWork document (.numbers, .pages etc)

**Comment by charlesvinette** [comment]
@mobiusnz Got it, for some reason all the pages documents on my drive are grayed ou. Ill write a test one and see what happens

**Comment by christiangenco** [comment]
@mobiusnz you're right :p `s/10/11/`

Here's [a video of it crashing on my 10.5in iPad Pro from the Expo client](https://photos.app.goo.gl/ChScHILqfUTkYvN52).

**Comment by charlesvinette** [comment]
Weird! Will look into it. Thanks for the constant communication guys it helps a lot @christiangenco and @mobiusnz !

**Comment by charlesvinette** [comment]
Hey all. I am trying to figure out why I wouldn't have access to .pages/.numbers and .keynote files with DocumentPicker like you guys are doing. Using your example Christian, all files with those extensions are grayed out as you can see here:
![img_1664](https://user-images.githubusercontent.com/7192823/32010946-40292700-b981-11e7-9fd7-d82d3eb3fd12.jpeg)

**Comment by TrillCyborg** [comment]
Was @maharjanaman issue fixed? It seems like I'm having the same issue. On SDK 22. Document Picker works fine in dev and expo client but in standalone it doesn't work at all. The app doesn't crash just the Doc Picker UI doesn't open. When tapping the button that should open it the app does nothing.

I enabled the entitlements in my app id in the apple dev portal and I've added `usesIcloudStorage` to `app.json`. Really out of ideas at this point. Haven't been able to find an answer to this in this repo, forums or slack channel. I'm really looking forward to figuring this out with anyone.

**Comment by TrillCyborg** [comment]
@charlesvinette thats a relief. I was going crazy thinking I was the only one with this problem. Do you have any idea how soon 'soon' is? Just so I can figure out my launch and roadmap situation for the next few weeks

**Comment by charlesvinette** [comment]
I know exactly what needs to be fixed and will work on it this week. I will ask the team we could expect it to be live and get back to you alright?

**Comment by TrillCyborg** [comment]
Sounds good. Thanks! If you need help testing don't hesitate to reach out

**Comment by charlesvinette** [comment]
Perfect thank you very much, I also have a toy app to test so we should be able to cover testing the two of us 😎

**Comment by christiangenco** [comment]
On iOS 11.1 (15B101) on a 12.9in iPad Pro on Expo Client 2.0.4, [my minimal test](https://snack.expo.io/HJ4quZV2b) still crashes.

**Comment by charlesvinette** [comment]
Hey @christiangenco! We noticed that the DocumentPicker is crashing on iPad only, and we are investigating this issue as well as the the Picker not showing issue that @TrillCyborg mentioned.

**Comment by 0x0ece** [comment]
@charlesvinette is there any update on this? I just tried on v23 and it doesn't seem fixed. Is there any workaround to make it work on a standalone app, like overriding info.plist, or any other trick?

**Comment by charlesvinette** [comment]
Hi Emanuele! What issue are you having, the document picker is crashing or
it never shows up?

**Comment by 0x0ece** [comment]
@charlesvinette it's never showing up (iPhone iOS 11.1.1), didn't try on iPad.

**Comment by herdani** [comment]
@charlesvinette I experience the same issue: the document picker never shows up on standalone (but works with an Expo published app)

**Comment by charlesvinette** [comment]
Ok I see.  This has to do with the entitlements on Standalone builds being wrong as I mentioned above. The PR for the fix will be ready this week and I will update everyone here once it is live. As for the other bug where it crashes on iPad, I will also investigate that once the entitlements fixes are in. Thanks for your patience everyone.

**Comment by 0x0ece** [comment]
Is there a temp fix, where we can override the entitlements and make the resulting build work?

**Comment by charlesvinette** [comment]
@0x0ece Yes you can modify the entitlements of the project, you will see need to change the $(CFBundleIdentifier) in `iCloud.$(CFBundleIdentifier)` with `iCloud.<YOUR BUNDLE ID>. You need to do the same thing for iCloud Key Value Store but change $(TeamIdentifierPrefix) with your Team ID that you input when `exp build:ios`. Example: `X1X1X1X.com.company.project`

**Comment by charlesvinette** [comment]
Just an update here, my PR for the fix where the DocumentPicker doesn't show up because of entitlements is up and should be live soon. As for the crash bug on iPad, I will be updating this issue if you would like to follow it -> https://github.com/expo/expo/issues/1002#issuecomment-346719436. Have a good Friday guys!

**Comment by TrillCyborg** [comment]
Is it going to be in the next expo version or is this a server side fix for you?

**Comment by 0x0ece** [comment]
I just made a new build but it doesn't seem it's fixed, so I assume the patch hasn't landed yet?

**Comment by charlesvinette** [comment]
Nope it didn't yet, I will report back once it is.

**Comment by Damirikys** [comment]
@charlesvinette thank you, we look forward to it. It is very important for us.

**Comment by christiangenco** [comment]
On iOS 11.1.2 (15B202) on a 12.9in iPad Pro on Expo Client 2.2.0, [my minimal test](https://snack.expo.io/BkipcBlGM) still crashes.

**Comment by 0x0ece** [comment]
Just tried on iPhone, it doesn't crash but nothing new, still not working.

**Comment by herdani** [comment]
I'm not sure everyone has the same issue actually, because it's unclear what we have to do to get it right. I don't know for example if my configuration is right and that there's a bug, or if I need to do something extra to get it working.

Would it be possible to complete the doc to be sure we're all doing what's needed ? This is what I understood we need to do:

* Add "usesIcloudStorage": true in the ios part of app.json
* Enable iCloud in your App ID (on developer.apple.com) => Here we have a few things to choose:
  * "Compatible with XCode 5" or "Include Cloudkit support" ?
  * Do we have to create an iCloud Container ?

In my case I have the key in the json file, iCloud enabled (Xcode 5, no Container), but on my standalone app I still get a "DocumentPicker requires the iCloud entitlement" error message

Thanks

**Comment by charlesvinette** [comment]
Hey everyone, sorry for my late response and sorry it is taking longer than expected. We are still waiting to have this merged in. I will report back once it is.

**Comment by 0x0ece** [comment]
I have an update on my side, that I wanted to share in case others need this working asap.

I went ahead, detached, and followed all the instructions here:
https://docs.expo.io/versions/latest/guides/advanced-expokit-topics.html#using-documentpicker
In the process, I realized that my apple account was not properly set up, specifically I was missing the iCloud container, and now it's fixed.

So, by detaching, I was able to get a build with DocumentPicker working.

(now that my apple account is ok, I tried again `exp build:ios` but this isn't working yet -- I'm saying this just for completeness, @charlesvinette already mentioned the pr isn't merged yet.)

**Comment by charlesvinette** [comment]
Hey thanks a lot @0x0ece for helping out! I am still waiting to have this merged in. I didn't forget you guys! Happy Holidays

**Comment by charlesvinette** [comment]
Hey guys! Quick update, the PR has been merged and should be available in the next update. Happy New Year everyone 👍

**Comment by adhicl** [comment]
Hi, so anyone has managed to make this work? mine is still not working. I notice even if I set usesIcloudStorage to true, the certificate generated still does not turn on icloud entitlement. Should I just do manual upload for certification?

**Comment by terribleben** [comment]
Sorry everybody, this thread is the complete worst. Reopening.

**Comment by dillonhafer** [comment]
I thought this was broken for me because I enabled iCloud on my App ID in Apple's developer portal, but I didn't know I had to create a container. As soon as I created a container in Apple's developer portal my App Store app began working immediately, without the need for rebuilding.

**Comment by adhicl** [comment]
Hi @terribleben, so right now the standalone build really not working yet and not that we miss something right? I already tried adding create my own app id, add container, create provision but it still not working.
But in expo client, if I update to version 25 sdk that at least it can work

**Comment by dillonhafer** [comment]
I am only needing read access to iCloud files, so I've been getting around this right now, by using an invisible WebView to read iCloud files without the entitlement.

**Comment by EsdrasEtrenne** [comment]
Hi,@terribleben 


@herdani  had a really good question that I am confused on as well. It is clear that we need to add the the app.json the `"usesIcloudStorage" : true`, but what is not clear is what we need to do on the apple developer website. Do we need to enable icloud storage? Are there any special/specific configurations needed? Do we need to add the iCloud container?

**Comment by christiangenco** [comment]
On iOS 11.2.6 (15D100) on a 12.9in iPad Pro on Expo Client 2.3.0, [my minimal test](https://snack.expo.io/BkipcBlGM) still crashes.

**Comment by adhicl** [comment]
Any progress on this? I am stuck since I am using Expo notification too. So, if I detach then I can't use expo notif but if not then documentpicker simply not working. As a note, the imagepicker work for me in standalone build, both works in Expo Client after I update my expo sdk

**Comment by adhicl** [comment]
Hi, I just updated the expo to the newest but look like this has not been fixed yet?
When I try to run the standalone build in IOS app I got this in the log

default	07:11:29.468481 +0700	ExpoKitApp	*** Assertion failure in -[UIDocumentMenuViewController _commonInitWithCompletion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3698.34.4/UIDocumentMenuViewController.m:123

The document picker simply does not show up. But I could run it find when in EXPO client or when I detach it. I already followed all neccessary step in the documentation.
When I run exp:build ios and let EXPO handle everything, the icloud is not turned on, so I turned it on from the developer page and reconfirm the ios distribution. I tested after this step.

**Comment by AntonioSchmidt** [comment]
Hey guys! Really thanks for expo! 
Is there anyway to work around this issue without ejecting to Expokit?
I've been banging my head on the wall for hours trying to figure that out.

Thanks a lot!

**Comment by christiangenco** [comment]
@AntonioSchmidt as far as I can tell, there's no way to work around this issue even if you do eject from Expokit.

**Comment by adhicl** [comment]
I try to eject it and set the icloud from xcode and it could work. I think the problem is only on the server side build, since I still see the icloud is not enabled on apple developer at default.

**Comment by hivearts** [comment]
Hey guys, any update on this?

I have enabled icloud on developers.apple.com website and added usesIcloudStorage in app.json file, but it doesn't work when i build app with exp build:ios...

It seems that i would need to de-attach app from expo, which i think is not good idea for my project now...

Do you know when the bug should be solved?

Thanks!

**Comment by jakubste** [comment]
Hey guys.
I was into this issue lately and I managed to successfully build an app with working Document Picker. We still need to test this fix and ensure it does not break anything, but you might suspect that issue to be removed in nearly future.

**Comment by Danjavia** [comment]
I have the same issue the document picker never shows. I make the steps from above here, but not work :(

**Comment by willmoffat** [comment]
I just published an app with SDK 28.0.0 and still no luck :-(
@jakubste your last message sounded really promising, any progress to share?

**Comment by dillonhafer** [comment]
I've been using an invisible webview for the past year so I could get a document picker: https://gist.github.com/dillonhafer/04936dda21f7f0331167c8ff1cc9c5eb

**Comment by dsokal** [comment]
Hello guys,
we just pushed a fix for our builders which **should** resolve the issue, remember to rebuild your apps and please let me know if you're still experiencing the problem.
Thanks!

**Comment by dontuse** [comment]
upload in appStore
Messages:
  ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-container-environment' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
  ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-container-identifiers' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
  ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.ubiquity-container-identifiers' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
  ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-services' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
  ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.ubiquity-kvstore-identifier' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
  ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value '' for key 'com.apple.developer.icloud-container-environment' in 'Payload/ExpoKitApp.app/ExpoKitApp' is not supported. This value should be a string value of 'Production'

**Comment by jakubste** [comment]
@dontuse had you tried regenerating the provisioning profile?

**Comment by dontuse** [comment]
I tried rebuild exp build:ios -c , it made a new profile, but i have error in app loader

Package Summary:
 
1 package(s) were not uploaded because they had problems:
	/var/folders/83/8hzlhkmn3gl_qhdcvy08g77m0000gn/T/314AF401-C904-4823-8B4D-F2BA926D7FAE/1354996934.itmsp - Error Messages:
		ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-container-environment' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
		ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-container-identifiers' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
		ERROR ITMS-90164: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. According to the provisioning profile, the bundle contains a key value that is not allowed: '[ "iCloud.com.ibride.ibride-pro" ]' for the key 'com.apple.developer.ubiquity-container-identifiers' in 'Payload/ExpoKitApp.app/ExpoKitApp'"
		ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-services' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
		ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value '' for key 'com.apple.developer.icloud-container-environment' in 'Payload/ExpoKitApp.app/ExpoKitApp' is not supported. This value should be a string value of 'Production'"

**Comment by jakubste** [comment]
Ok. Are you using `usesIcloudStorage`?
I managed to build an application with `"usesIcloudStorage": true`, but had some errors (although different than you) without this flag.

**Comment by dontuse** [comment]
ios": {
      "usesIcloudStorage": true,
      "supportsTablet": false,
      "bundleIdentifier": "com.ibride.ibride-pro",
      "isRemoteJSEnabled": false
    },

**Comment by jakubste** [comment]
Have you enabled `iCloud` in the https://developer.apple.com/account/ios/identifier/bundle ?
I just run on TestFlight an app built with this flag without any problems...

**Comment by dontuse** [comment]
yes, enabled -  Compatible with Xcode 5 and  iCloud Container attached.

**Comment by dontuse** [comment]
i changed  settings to -  Include CloudKit support (requires Xcode 6) , it work

**Comment by jakubste** [comment]
Actually, in the meantime I reverted fix for the document picker. That's why it worked ;) We'll be investigating this issue again on Wednesday...

**Comment by willmoffat** [comment]
@dillonhafer Thanks for the idea of using a webview!
@jakubste no luck on a clean solution?

**Comment by jakubste** [comment]
Another attempt in fixing Document Picker is live. We'll be monitoring builds and especially your feedback if builds are successful (especially if Application Loader does not complain) - both with or without `usesIcloudStorage` flag.

**Comment by jakubste** [comment]
Turtle with (hopefully) fix for Document Picker is live. We'll be monitoring builds and your feedback.

**Comment by dontuse** [comment]
i have error again
```
[2018-07-20 14:11:40 YEKT] <main>  INFO: Transporter is searching for updated software components.
[2018-07-20 14:11:41 YEKT] <main>  INFO: Transporter is up-to-date.
[2018-07-20 14:11:41 YEKT] <main>  INFO: MD5 checksum calculation in the transporter will be skipped.
[2018-07-20 14:11:41 YEKT] <main>  INFO: Logging level set to eXtreme
[2018-07-20 14:11:41 YEKT] <main>  INFO: Logging configured successfully.
[2018-07-20 14:11:41 YEKT] <main> DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
[2018-07-20 14:11:41 YEKT] <main> DEBUG: Configuration refresh successful.
[2018-07-20 14:11:41 YEKT] <main> DEBUG: Saving configuration to local path: /Users/andrey/.itmstransporter/Defaults.properties
[2018-07-20 14:11:41 YEKT] <main>  INFO: iTMSTransporter : iTunes Store Transporter [1.9.8]
[2018-07-20 14:11:41 YEKT] <main>  INFO: OS identifier: Mac OS X 10.13.5 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
[2018-07-20 14:11:41 YEKT] <main>  INFO: Memory: [JVM] 1017M free, 1051M total, 1820M max [System] (Physical) 57M free, 8192M total (Swap) 1582M free, 2048M total
[2018-07-20 14:11:41 YEKT] <main>  INFO: Client: Application Loader 3.7 (1034)
[2018-07-20 14:11:41 YEKT] <main>  INFO: Upload mode selected.
[2018-07-20 14:11:41 YEKT] <main> DBG-X: Memory: [JVM] 1017M free, 1051M total, 1820M max [System] (Physical) 57M free, 8192M total (Swap) 1582M free, 2048M total
[2018-07-20 14:11:41 YEKT] <main> DBG-X: Memory: [JVM] 1034M free, 1063M total, 1820M max [System] (Physical) 50M free, 8192M total (Swap) 1582M free, 2048M total
[2018-07-20 14:11:41 YEKT] <main> DBG-X: Using operation named: authenticateForSession
[2018-07-20 14:11:42 YEKT] <main> DBG-X: Apple's web service operation input parameters:
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter Application = iTMSTransporter
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter BaseVersion = 1.9.6
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter Client = Application Loader
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter ClientVersion = 3.7 (1034)
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter DSToken = **hidden value**
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter ItcProviderName = XS2E2N3VKP
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter OSIdentifier = Mac OS X 10.13.5 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-07-20T14:11:41+05:00
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.556170051
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter TransporterArguments = -m upload -u dontusecascade@gmail.com -dsToken **hidden value** -itc_provider XS2E2N3VKP -f /var/folders/83/8hzlhkmn3gl_qhdcvy08g77m0000gn/T/F9B017F1-531A-4492-80CB-8C1694CE2EE7/1354996934.itmsp -checksumValidation false -indicator true -v eXtreme -Dtransporter.client=Application Loader -Dtransporter.client.version=3.7 (1034)
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter Username = dontusecascade@gmail.com
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter Version = 1.9.8
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter iTMSTransporterMode = upload
[2018-07-20 14:11:42 YEKT] <main>  INFO: id = 20180720141142-742
[2018-07-20 14:11:42 YEKT] <main> DBG-X: Apple's web service operation return value:
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter SharedSecret = **hidden value**
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter MultipartUploadsEnabled = true
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter EnableJWTForAllCalls = false
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter TxHeaders = {jenga=false, dc=PV38P00IT-CONTDELIVERY012}
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter SessionExpiration = 2018-07-24T09:11:42.802Z
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter SessionId = CM+oDBIQ4x9XffGfTwqON9BF4Jz3YA==
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
[2018-07-20 14:11:42 YEKT] <main> DBG-X: Using operation named: authenticateForTransportDiscovery
[2018-07-20 14:11:42 YEKT] <main> DBG-X: Apple's web service operation input parameters:
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter Application = iTMSTransporter
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter BaseVersion = 1.9.6
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter Client = Application Loader
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter ClientVersion = 3.7 (1034)
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter ItcProviderName = XS2E2N3VKP
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter OSIdentifier = Mac OS X 10.13.5 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-07-20T14:11:42+05:00
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter TransporterArguments = -m upload -u dontusecascade@gmail.com -dsToken **hidden value** -itc_provider XS2E2N3VKP -f /var/folders/83/8hzlhkmn3gl_qhdcvy08g77m0000gn/T/F9B017F1-531A-4492-80CB-8C1694CE2EE7/1354996934.itmsp -checksumValidation false -indicator true -v eXtreme -Dtransporter.client=Application Loader -Dtransporter.client.version=3.7 (1034)
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter Username = dontusecascade@gmail.com
[2018-07-20 14:11:42 YEKT] <main> DBG-X:   parameter Version = 1.9.8
[2018-07-20 14:11:43 YEKT] <main> DBG-X:   parameter iTMSTransporterMode = upload
[2018-07-20 14:11:43 YEKT] <main>  INFO: id = 20180720141143-246
[2018-07-20 14:11:44 YEKT] <main> DBG-X: Apple's web service operation return value:
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter EnableJWTForAllCalls = false
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter PreferredTransports = [Aspera, Signiant, DAV]
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter TransportHosts.Signiant = [sgr603.apple.com:44001]
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter SessionExpiration = 2018-07-24T09:11:43.321Z
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter TransportHosts.DAV = [itmsdav.apple.com:443]
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter TransportHosts.Aspera = [vgr503.apple.com:33001, vgr501.apple.com:33001, vgr504.apple.com:33001, vgr502.apple.com:33001]
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
[2018-07-20 14:11:44 YEKT] <main>  INFO: Examining the package at: /var/folders/83/8hzlhkmn3gl_qhdcvy08g77m0000gn/T/F9B017F1-531A-4492-80CB-8C1694CE2EE7/1354996934.itmsp
[2018-07-20 14:11:44 YEKT] <main>  INFO: Ensuring that package has well formed metadata file...
[2018-07-20 14:11:44 YEKT] <main> DEBUG: Getting case-sensitive metadata xml filename...
[2018-07-20 14:11:44 YEKT] <main>  INFO: Gathering the list of valid files from the package ...
[2018-07-20 14:11:44 YEKT] <main> DEBUG:   ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa will be verified by Apple's web service to determine if it is a valid file.
[2018-07-20 14:11:44 YEKT] <main> DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
[2018-07-20 14:11:44 YEKT] <main>  INFO: Finished gathering the list of valid files from the package.
[2018-07-20 14:11:44 YEKT] <main> DEBUG:   Case-sensitive metadata filename is: metadata.xml
[2018-07-20 14:11:44 YEKT] <main>  INFO: Performing authentication of package 1354996934.itmsp ...
[2018-07-20 14:11:44 YEKT] <main> DBG-X: Memory: [JVM] 1021M free, 1063M total, 1820M max [System] (Physical) 92M free, 8192M total (Swap) 1582M free, 2048M total
[2018-07-20 14:11:44 YEKT] <main> DBG-X: Deflated 670 bytes to 496
[2018-07-20 14:11:44 YEKT] <main> DBG-X: Using operation named: validateMetadata
[2018-07-20 14:11:44 YEKT] <main> DBG-X: Apple's web service operation input parameters:
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter Application = iTMSTransporter
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter BaseVersion = 1.9.6
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter Client = Application Loader
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter ClientVersion = 3.7 (1034)
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter Files = [ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa, metadata.xml]
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter ItcProviderName = XS2E2N3VKP
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter Metadata = <?xml version="1.0" encoding="UTF-8"?>
<package version="software5.4" xmlns="http://apple.com/itunes/importer">
    <software_assets apple_id="1354996934"
        bundle_short_version_string="1.3.14"
        bundle_version="1"
        bundle_identifier="com.ibride.ibride-pro"
        app_platform="ios">
        <asset type="bundle">
            <data_file>
                <file_name>ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa</file_name>
                <checksum type="md5">20951578094df7a36c080bd374c0668e</checksum>
                <size>220378126</size>
            </data_file>
        </asset>
    </software_assets>
</package>

[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter MetadataChecksum = f31a2c703018fa4a2eeb744ac92c8b34
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter MetadataCompressed = (suppressed)
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter OSIdentifier = Mac OS X 10.13.5 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter PackageName = 1354996934.itmsp
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter PackageSize = 220378796
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-07-20T14:11:44+05:00
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter TransporterArguments = -m upload -u dontusecascade@gmail.com -dsToken **hidden value** -itc_provider XS2E2N3VKP -f /var/folders/83/8hzlhkmn3gl_qhdcvy08g77m0000gn/T/F9B017F1-531A-4492-80CB-8C1694CE2EE7/1354996934.itmsp -checksumValidation false -indicator true -v eXtreme -Dtransporter.client=Application Loader -Dtransporter.client.version=3.7 (1034)
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter Username = dontusecascade@gmail.com
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter Version = 1.9.8
[2018-07-20 14:11:44 YEKT] <main> DBG-X:   parameter iTMSTransporterMode = upload
[2018-07-20 14:11:44 YEKT] <main>  INFO: id = 20180720141144-414
[2018-07-20 14:11:47 YEKT] <main> DBG-X: Apple's web service operation return value:
[2018-07-20 14:11:47 YEKT] <main> DBG-X:   parameter EnableJWTForAllCalls = false
[2018-07-20 14:11:47 YEKT] <main> DBG-X:   parameter SessionExpiration = 2018-07-24T09:11:44.982Z
[2018-07-20 14:11:47 YEKT] <main> DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
[2018-07-20 14:11:47 YEKT] <main> DBG-X:   parameter SoftwareMediaDescriptionFormat = binary
[2018-07-20 14:11:47 YEKT] <main> DBG-X:   parameter SoftwareMediaDescriptionThresholds = {in-app-purchase-content={extensions=[pkg], size=100000000}, ccats={extensions=[pdf], size=100000000}, product-archive={extensions=[pkg], size=100000000}, developer-id-package={extensions=[zip, pkg, dmg], size=100000000}, bundle={extensions=[zip, ipa], size=100000000}, large-icon={extensions=[jpg, png, jpeg], size=100000000}}
[2018-07-20 14:11:47 YEKT] <main> DBG-X:   parameter Success = true
[2018-07-20 14:11:47 YEKT] <main> DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
[2018-07-20 14:11:47 YEKT] <main> DBG-X:   parameter FilesToUpload = [metadata.xml, ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa]
[2018-07-20 14:11:47 YEKT] <main> DBG-X:   parameter AssetsToDescribe = [{Role=source, Filename=ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa, ShouldDescribeAsset=true, UTI=com.apple.ipa}]
[2018-07-20 14:11:47 YEKT] <main> DBG-X:   parameter CPUToken = fde01a7e-3522-48e7-b923-b8ed0ca86484/1532077906902
[2018-07-20 14:11:47 YEKT] <main> DBG-X:   parameter Checksums = {ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa=20951578094df7a36c080bd374c0668e}
[2018-07-20 14:11:47 YEKT] <main> DBG-X:   parameter FileSizes = {ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa=220378126}
[2018-07-20 14:11:47 YEKT] <main> DBG-X:   parameter ProviderNameForToken = XS2E2N3VKP
[2018-07-20 14:11:47 YEKT] <main>  INFO: The list of files requested for upload by Apple is: [metadata.xml, ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa].  These are the files that will be uploaded.
[2018-07-20 14:11:47 YEKT] <main>  INFO: Starting media analysis of assets
[2018-07-20 14:11:48 YEKT] <main> DEBUG: Handling asset: filename=ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa,uti=com.apple.ipa,role=source,describe=true
[2018-07-20 14:11:48 YEKT] <main> DEBUG: Using container type tool name and version: iOS App Describer:1.25
[2018-07-20 14:11:48 YEKT] <main> DEBUG: Using path: /var/folders/83/8hzlhkmn3gl_qhdcvy08g77m0000gn/T/F9B017F1-531A-4492-80CB-8C1694CE2EE7/1354996934.itmsp/ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa
[2018-07-20 14:13:40 YEKT] <main> DBG-X: description length:0
[2018-07-20 14:13:40 YEKT] <main> DBG-X: Asset description: 
[2018-07-20 14:13:40 YEKT] <main> DEBUG: Asset successfully described: com.apple.jingle.leghorn.software.AbstractSoftwareDescriber$1@6bd51ed8
[2018-07-20 14:13:40 YEKT] <main> DBG-X: Deflated 636 bytes to 384
[2018-07-20 14:13:40 YEKT] <main>  INFO: Asset media analysis has completed
[2018-07-20 14:13:40 YEKT] <main> DBG-X: Memory: [JVM] 1006M free, 1065M total, 1820M max [System] (Physical) 1899M free, 8192M total (Swap) 1372M free, 2048M total
[2018-07-20 14:13:40 YEKT] <main> DBG-X: Using operation named: lookupTransportDiagnostic
[2018-07-20 14:13:40 YEKT] <main> DBG-X: Apple's web service operation input parameters:
[2018-07-20 14:13:40 YEKT] <main> DBG-X:   parameter Application = iTMSTransporter
[2018-07-20 14:13:40 YEKT] <main> DBG-X:   parameter BaseVersion = 1.9.6
[2018-07-20 14:13:40 YEKT] <main> DBG-X:   parameter Client = Application Loader
[2018-07-20 14:13:40 YEKT] <main> DBG-X:   parameter ClientVersion = 3.7 (1034)
[2018-07-20 14:13:40 YEKT] <main> DBG-X:   parameter ItcProviderName = XS2E2N3VKP
[2018-07-20 14:13:40 YEKT] <main> DBG-X:   parameter OSIdentifier = Mac OS X 10.13.5 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
[2018-07-20 14:13:40 YEKT] <main> DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-07-20T14:13:40+05:00
[2018-07-20 14:13:40 YEKT] <main> DBG-X:   parameter TransporterArguments = -m upload -u dontusecascade@gmail.com -dsToken **hidden value** -itc_provider XS2E2N3VKP -f /var/folders/83/8hzlhkmn3gl_qhdcvy08g77m0000gn/T/F9B017F1-531A-4492-80CB-8C1694CE2EE7/1354996934.itmsp -checksumValidation false -indicator true -v eXtreme -Dtransporter.client=Application Loader -Dtransporter.client.version=3.7 (1034)
[2018-07-20 14:13:40 YEKT] <main> DBG-X:   parameter Username = dontusecascade@gmail.com
[2018-07-20 14:13:40 YEKT] <main> DBG-X:   parameter Version = 1.9.8
[2018-07-20 14:13:40 YEKT] <main> DBG-X:   parameter iTMSTransporterMode = upload
[2018-07-20 14:13:40 YEKT] <main>  INFO: id = 20180720141340-847
[2018-07-20 14:13:49 YEKT] <main> DBG-X: Apple's web service operation return value:
[2018-07-20 14:13:49 YEKT] <main> DBG-X:   parameter AsperaLoggingLevel = OFF
[2018-07-20 14:13:49 YEKT] <main> DBG-X:   parameter EnableJWTForAllCalls = false
[2018-07-20 14:13:49 YEKT] <main> DBG-X:   parameter SigniantLoggingLevel = OFF
[2018-07-20 14:13:49 YEKT] <main> DBG-X:   parameter SessionExpiration = 2018-07-24T09:13:41.160Z
[2018-07-20 14:13:49 YEKT] <main> DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
[2018-07-20 14:13:49 YEKT] <main> DBG-X:   testing host/port: vgr502.apple.com/33001
[2018-07-20 14:13:53 YEKT] <aspera.util.SelectThread>  INFO: The upload of the file named /var/folders/83/8hzlhkmn3gl_qhdcvy08g77m0000gn/T/c787eea4-a957-4e4f-b012-c894c1b5df0380690984445592493dir/3b7c8498-7914-45bc-84a6-5335f5a5e35b8817564237125734339.txt has started.
[2018-07-20 14:13:53 YEKT] <aspera.util.SelectThread>  INFO:      File: /var/folders/83/8hzlhkmn3gl_qhdcvy08g77m0000gn/T/c787eea4-a957-4e4f-b012-c894c1b5df0380690984445592493dir/3b7c8498-7914-45bc-84a6-5335f5a5e35b8817564237125734339.txt 11/11, 100% completed
[2018-07-20 14:13:53 YEKT] <aspera.util.SelectThread>  INFO: The status is FINISHED for the file named /var/folders/83/8hzlhkmn3gl_qhdcvy08g77m0000gn/T/c787eea4-a957-4e4f-b012-c894c1b5df0380690984445592493dir/3b7c8498-7914-45bc-84a6-5335f5a5e35b8817564237125734339.txt.
[2018-07-20 14:13:53 YEKT] <main>  INFO: The session's final state is Complete
[2018-07-20 14:13:53 YEKT] <main>  INFO: Number of files transferred: 1 .  Names of files transferred:
[2018-07-20 14:13:54 YEKT] <main>  INFO:     /var/folders/83/8hzlhkmn3gl_qhdcvy08g77m0000gn/T/c787eea4-a957-4e4f-b012-c894c1b5df0380690984445592493dir/3b7c8498-7914-45bc-84a6-5335f5a5e35b8817564237125734339.txt - Complete
[2018-07-20 14:13:54 YEKT] <main> DEBUG: Using token file path /Users/andrey/.itmstransporter/UploadTokens/MacBook-Pro-Andrey.local_XS2E2N3VKP_1354996934.itmsp.token
[2018-07-20 14:13:54 YEKT] <main> DEBUG: Attempting exclusive file lock on token file
[2018-07-20 14:13:54 YEKT] <main> DEBUG: Set token: fde01a7e-3522-48e7-b923-b8ed0ca86484/1532077906902
[2018-07-20 14:13:54 YEKT] <main> DBG-X: Memory: [JVM] 1043M free, 1076M total, 1820M max [System] (Physical) 1827M free, 8192M total (Swap) 1372M free, 2048M total
[2018-07-20 14:13:54 YEKT] <main> DBG-X: Deflated 670 bytes to 496
[2018-07-20 14:13:54 YEKT] <main> DBG-X: Using operation named: validateAssets
[2018-07-20 14:13:54 YEKT] <main> DBG-X: Apple's web service operation input parameters:
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter Application = iTMSTransporter
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter BaseVersion = 1.9.6
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter CPUToken = fde01a7e-3522-48e7-b923-b8ed0ca86484/1532077906902
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter Client = Application Loader
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter ClientVersion = 3.7 (1034)
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter Files = [ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa, metadata.xml]
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter ItcProviderName = XS2E2N3VKP
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter MetadataChecksum = f31a2c703018fa4a2eeb744ac92c8b34
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter MetadataCompressed = (suppressed)
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter OSIdentifier = Mac OS X 10.13.5 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter PackageName = 1354996934.itmsp
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter PackageSize = 220378796
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-07-20T14:13:54+05:00
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter StreamingInfoList = [com.apple.transporter.streaming.StreamableFile@1e63d216]
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter Transport = Aspera
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter TransporterArguments = -m upload -u dontusecascade@gmail.com -dsToken **hidden value** -itc_provider XS2E2N3VKP -f /var/folders/83/8hzlhkmn3gl_qhdcvy08g77m0000gn/T/F9B017F1-531A-4492-80CB-8C1694CE2EE7/1354996934.itmsp -checksumValidation false -indicator true -v eXtreme -Dtransporter.client=Application Loader -Dtransporter.client.version=3.7 (1034)
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter Username = dontusecascade@gmail.com
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter Version = 1.9.8
[2018-07-20 14:13:54 YEKT] <main> DBG-X:   parameter iTMSTransporterMode = upload
[2018-07-20 14:13:54 YEKT] <main>  INFO: id = 20180720141354-870
[2018-07-20 14:14:03 YEKT] <main> DBG-X: Apple's web service operation return value:
[2018-07-20 14:14:03 YEKT] <main> DBG-X:   parameter Errors = [ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-container-identifiers' in 'Payload/ExpoKitApp.app/ExpoKitApp'.", ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.ubiquity-container-identifiers' in 'Payload/ExpoKitApp.app/ExpoKitApp'.", ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-services' in 'Payload/ExpoKitApp.app/ExpoKitApp'.", ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.ubiquity-kvstore-identifier' in 'Payload/ExpoKitApp.app/ExpoKitApp'."]
[2018-07-20 14:14:03 YEKT] <main> DBG-X:   parameter FilesToUpload = [metadata.xml, ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa]
[2018-07-20 14:14:03 YEKT] <main> DBG-X:   parameter AssetsToDescribe = [{Role=source, Filename=ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa, ShouldDescribeAsset=true, UTI=com.apple.ipa}]
[2018-07-20 14:14:03 YEKT] <main> DBG-X:   parameter Checksums = {ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa=20951578094df7a36c080bd374c0668e}
[2018-07-20 14:14:03 YEKT] <main> DBG-X:   parameter EnableJWTForAllCalls = false
[2018-07-20 14:14:03 YEKT] <main> DBG-X:   parameter FileSizes = {ios_2F_ibride_2Fibride-app-bd02efa7-277a-41c1-a16c-fd6e19a51dbc-archive.ipa=220378126}
[2018-07-20 14:14:03 YEKT] <main> DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
[2018-07-20 14:14:03 YEKT] <main> DBG-X:   parameter SoftwareMediaDescriptionFormat = binary
[2018-07-20 14:14:03 YEKT] <main> DBG-X:   parameter ErrorCode = 1102
[2018-07-20 14:14:03 YEKT] <main> DBG-X:   parameter SoftwareMediaDescriptionThresholds = {in-app-purchase-content={extensions=[pkg], size=100000000}, ccats={extensions=[pdf], size=100000000}, product-archive={extensions=[pkg], size=100000000}, developer-id-package={extensions=[zip, pkg, dmg], size=100000000}, bundle={extensions=[zip, ipa], size=100000000}, large-icon={extensions=[jpg, png, jpeg], size=100000000}}
[2018-07-20 14:14:03 YEKT] <main> DBG-X:   parameter ErrorMessage = ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-container-identifiers' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.ubiquity-container-identifiers' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-services' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.ubiquity-kvstore-identifier' in 'Payload/ExpoKitApp.app/ExpoKitApp'.
 (1102)
[2018-07-20 14:14:03 YEKT] <main> DBG-X:   parameter Success = false
[2018-07-20 14:14:03 YEKT] <main> ERROR: ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-container-identifiers' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
[2018-07-20 14:14:03 YEKT] <main> ERROR: ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.ubiquity-container-identifiers' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
[2018-07-20 14:14:03 YEKT] <main> ERROR: ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-services' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
[2018-07-20 14:14:03 YEKT] <main> ERROR: ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.ubiquity-kvstore-identifier' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
[2018-07-20 14:14:03 YEKT] <main> DBG-X: The error code is: 1102
[2018-07-20 14:14:03 YEKT] <main>  INFO: Done performing authentication.
[2018-07-20 14:14:03 YEKT] <main> DBG-X: Returning 1




Package Summary:
 
1 package(s) were not uploaded because they had problems:
	/var/folders/83/8hzlhkmn3gl_qhdcvy08g77m0000gn/T/F9B017F1-531A-4492-80CB-8C1694CE2EE7/1354996934.itmsp - Error Messages:
		ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-container-identifiers' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
		ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.ubiquity-container-identifiers' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
		ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-services' in 'Payload/ExpoKitApp.app/ExpoKitApp'."
		ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.ubiquity-kvstore-identifier' in 'Payload/ExpoKitApp.app/ExpoKitApp'."

```

**Comment by jakubste** [comment]
If you want to user DocumentPicker these entitlements must be in signature and provisioning profile. From the message you posted it look like signing works ok, but you don't have these keys in provisioning profile. Please make sure that you enabled iCloud for your app ID on developer.apple.com. While you there, revoke the provisioning profile and run `exp bi -c`.

**Comment by dontuse** [comment]
Ок, thx. Can i just regenerate provision profile, but not generate new certificate (push and  distribution) ?

**Comment by jakubste** [comment]
I'm not sure, but probably yes.

**Comment by jakubste** [comment]
@dillonhafer @willmoffat @Danjavia @gauravverma @hivearts I would appreciate if you could test if DocumentPicker works for you.

**Comment by dillonhafer** [comment]
Cool, I'll do a build right now.

**Comment by willmoffat** [comment]
@jakubste thanks! We'll check on Monday.

**Comment by dillonhafer** [comment]
I did a fresh `exp build:ios -c` to make sure everything is clean, but I can't get a valid build

<img width="812" alt="screen shot 2018-07-21 at 11 50 13 am" src="https://user-images.githubusercontent.com/1136388/43037618-1002d5be-8cdd-11e8-9fa1-d90f2c3728c6.png">

**Comment by herdani** [comment]
Got it working too in TestFlight! 💪👍

Thanks @jakubste !

FYI, I had to do extra steps for the iCloud entitlements configuration, and thought it was worth making this explicit for everyone, so I've created a pull request for your documentation: https://github.com/expo/expo-docs/pull/337

PS/ I'm working with @willmoffat, so you can consider it's fixed for him too

**Comment by jakubste** [comment]
@herdani Great! And thank you for your PR!

**Comment by jakubste** [comment]
It looks like the issue is gone.

**Comment by kyhnlbyrk** [comment]
Hi guys,

I am on Expo 31, and I am having the error problem. 

ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-services' in 'Payload/ExpoKitApp.app/ExpoKitApp'."

"usesIcloudStorage": true written in app.json, and in the apple  developer side, icloud is enabled with container. However, I still get this error. Please help..

**Comment by jakubste** [comment]
@kyhnlbyrk try revoking your provisioning profile and generate a new one

**Comment by jakubste** [comment]
Did you also create iCloud container?

**Comment by kyhnlbyrk** [comment]
Yes I did.. 

I wrote the errors are missing.. These are the errors..

ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-services' in 'Payload/ExpoKitApp.app/ExpoKitApp'."

ERROR ITMS-90211: "Invalid Code Signing Entitlements. The signature for your app bundle contains entitlement values that are not supported. For the 'com.apple.developer.ubiquity-container-identifiers' entitlement, the values in the array must start with the prefix provided by Apple in the provisioning profile, followed by characters that are uppercase or lowercase Roman letters [A-Z, a-z], the digits 0 through 9, dot ['.'], or hyphen ['-'], and not contain any wildcard characters. Specifically, value '9383AZTAJE.*' for the key 'com.apple.developer.ubiquity-container-identifiers' in 'Payload/ExpoKitApp.app/ExpoKitApp' is not supported."

**Comment by jakubste** [comment]
what's build id of the job that generated that IPA file?

**Comment by kyhnlbyrk** [comment]
I believe it was 7dadd6ae-67bd-4c97-9a17-933c92183723 this

**Comment by kyhnlbyrk** [comment]
I had app Id before. And previous releases do not have document picker and that flag, so my app id created according to it. Is this can be the problem? Does my app id have to be created all again?

**Comment by jakubste** [comment]
I cannot see it, this number from url like `https://expo.io/builds/[build-id-here]/`?

I would not say, that you have to delete it. I think editing it and checking "iCloud" support is enough…

**Comment by kyhnlbyrk** [comment]
Aha, I just made a build and I can upload it.. I will tell if it is working when I can get it from test flight.
