### ISSUE TITLE
[Updates][Android]Crash: RuntimeException on app start: ExperienceActivity$2.onManifestCompleted on some devices

### ISSUE THREAD

**Issue by linus** [expo/expo#5917]
## 🐛 Bug Report

A large minority of Android users experience crashes on app startup. We see the error in the Google Play Console:

```
java.lang.RuntimeException: 
  at host.exp.exponent.experience.BaseExperienceActivity$2.run (BaseExperienceActivity.java:196)
  at android.app.Activity.runOnUiThread (Activity.java:5962)
  at host.exp.exponent.experience.BaseExperienceActivity.consumeErrorQueue (BaseExperienceActivity.java:174)
  at host.exp.exponent.experience.BaseExperienceActivity.addError (BaseExperienceActivity.java:63)
  at host.exp.exponent.kernel.Kernel.handleReactNativeError (Kernel.java:1090)
  at host.exp.exponent.kernel.Kernel.handleError (Kernel.java:1095)
  at host.exp.exponent.experience.ExperienceActivity.setManifest (ExperienceActivity.java:383)
  at host.exp.exponent.experience.ExperienceActivity$2$2.run (ExperienceActivity.java:214)
  at host.exp.expoview.Exponent.runOnUiThread (Exponent.java:222)
  at host.exp.exponent.experience.ExperienceActivity$2.onManifestCompleted (ExperienceActivity.java:208)
  at host.exp.exponent.AppLoader.resolve (AppLoader.java:240)
  at host.exp.exponent.AppLoader.resolve (AppLoader.java:215)
  at host.exp.exponent.AppLoader.access$000 (AppLoader.java:20)
  at host.exp.exponent.AppLoader.access$102 (AppLoader.java:20)
  at host.exp.exponent.AppLoader.access$200 (AppLoader.java:20)
  at host.exp.exponent.AppLoader.access$300 (AppLoader.java:20)
  at host.exp.exponent.AppLoader.access$600 (AppLoader.java:20)
  at host.exp.exponent.AppLoader.access$1000 (AppLoader.java:20)
  at host.exp.exponent.AppLoader.access$1102 (AppLoader.java:20)
  at host.exp.exponent.AppLoader$5.onBundleLoaded (AppLoader.java:337)
  at host.exp.expoview.Exponent$2$1.run (Exponent.java:472)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6351)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:896)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:786)
```

### Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /var/folders/tk/1c86q3t945j098jmhrnbzh7m0000gn/T/yarn--1570608949350-0.9472970268100118/node
      Yarn: 1.17.3 - /var/folders/tk/1c86q3t945j098jmhrnbzh7m0000gn/T/yarn--1570608949350-0.9472970268100118/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    IDEs:
      Xcode: 11.0/11A419c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.12.1 

App is managed and targeting Android and iOS. The error appears on Android.

### Steps to Reproduce

For certain users / conditions, the app crashes on startup.

### Expected Behavior

The app starting without a hitch.

### Actual Behavior

App crashes on startup.

### Reproducible Demo

I can't reproduce it on a device of my own.

**Comment by linus** [comment]
Looking at the relevant source lines, it seems as if Expo dislikes the manifest SDK version? I don't know how this would ever happen.

Note: We do have custom code to check for updates, fetch and reload on startup. We also do have app bundles targeting previous SDKs in the same release channel.

**Comment by cruzach** [comment]
duplicate of #5839 

@linus better to keep the conversation in just one thread

**Comment by cruzach** [comment]
> it seems as if Expo dislikes the manifest SDK version

Could you share the custom update code? I'm wondering if you're trying to apply the js update for SDK 35 to a binary that's on an older version somehow?

**Comment by linus** [comment]
Sure. The code we're using looks quite similar to the sample code referenced in the documentation for the `Updates` module:

```
const update = await Updates.checkForUpdateAsync()
if (update.isAvailable) {
  await Updates.fetchUpdateAsync()
  Updates.reloadFromCache()
}
```

I suspected it could be something along the lines of what you suggested, so changed it to:

```
const update = await Updates.checkForUpdateAsync()
if (update.isAvailable) {
  if (update.manifest.sdkVersion === Expo.Constants.manifest.sdkVersion) {
    await Updates.fetchUpdateAsync()
    Updates.reloadFromCache()
  }
}
```

(For reasons beyond my control, we have actively used version of the app on Expo 32, Expo 34 and Expo 35, all on the `default` release channel. Before pushing an update to the Expo 32 version, I suspected that something like this could go wrong, so we [asked in the forums](https://forums.expo.io/t/publish-a-lower-sdk-version-in-release-channel/28706) and were reassured that Expo would only update to the same version. I tested myself, and didn't run into problems, so the question is (if this is indeed the problem) why some users get the "older" release? Is it random, or did they get it before I pushed some other update (for Expo 35), or something else?)

**Comment by serhiipalash** [comment]
We have the same error, but only for one of our users. The error happens after user changed device from `Samsung Note 8` to `Samsung S10+`. User had our app installed on `Samsung Note 8` and now, when she installs the app on `Samsung S10+` and tries to open it, the app crashes on start.

Two days ago we released a new release with `<AppearanceProvider></AppearanceProvider>` as a global wrapper for our app and first I thought that this could cause an issue on Android. @linus do you use `AppearanceProvider` in your app?

**Comment by esamelson** [comment]
Hi there -- sorry about this bug and thanks for the report. I dig some digging and it turns out that there was an edge case we weren't handling properly when apps with different SDK versions are published and installed in a specific order. In previous SDK versions we would show an Expo error screen UI which would allow resolving the problem, but starting with SDK 35 we've removed that UI and so this error came to light. It should be fixed now if you rerun `expo build:android`, build your app with `turtle-cli@0.12.4`, or install `expokit@35.0.2` depending on which method you use to build your app.

**Comment by SousaItalo** [comment]
Hi, Guys. I'm still facing this issue on two managed apps running on SDK 35. I did the `expo build:android` last friday but the errors still coming. Is there any particular process I have to do or just run the build:android should do the job?

**Comment by esamelson** [comment]
@SousaItalo the original issue from this thread has been fixed. Is it possible your stacktrace looks like the one in [this post](https://forums.expo.io/t/high-crash-rate-on-android-sdk35/29285) instead? It's similar but slightly different and with a different cause (fatal JS errors).

**Comment by SousaItalo** [comment]
I Think you're right. Thanks @esamelson for pointing me into the right direction.

**Comment by thanh90** [comment]
i used 35.0.4 and still get this error:
Expo encountered a fatal error: Unexpected EOF no stack
host.exp.exponent.experience.BaseExperienceActivity$2.run (BaseExperienceActivity.java:197)
