### ISSUE TITLE
Uncaught Error: Module AppRegistry is not a registered callable module and Uncaught Error: undefined is not an object

### ISSUE THREAD

**Issue by AhadCove** [expo/expo#608]
I received three different errors from users using the Android version of my app in the play store.
The two errors below came from one device and I already opened another issue that I received on someone else's device. This is only on specific Android devices though and I can't reproduce it on mine. Is there anything I can do about these:

```
Uncaught Error: Module AppRegistry is not a registered callable module (calling runApplication)
value@cached-bundle-experience-%40ahadcove*** 
```

``` 
Uncaught Error: undefined is not an object (evaluating’h.getExponentPushTokenAsync’)
<unknown>@cached-bundle-experience-%40ahadcove*** 
```

**Comment by jimmylee** [comment]
Is your application using ExpoKit, or are you still attached? Trying to get more information as I can't see your code unless you provide me a snippet.

**Comment by jimmylee** [comment]
Gathering some more context from https://github.com/expo/expo/issues/607 - your application is an Expo application deployed to the App Store and you're running into bugs when you pushed an update?

**Comment by AhadCove** [comment]
@jimmylee Yes, my app is still attached. It's a Create React Native app.
And it is on the App Store already. 
After pushing an update I had two clients that ran into this error on Android. I cannot reproduce it though. The only way they got rid of it, was by deleting the app and reinstalling

**Comment by jimmylee** [comment]
@AhadCove I asked internally for some guidance on this. Sorry we don't have an immediate solution for you, but this looks like a problem we should address ASAP.

**Comment by AhadCove** [comment]
Thank you, if you need any other information, let me know

**Comment by ShayanJavadi** [comment]
did you ever figure this out? I'm having the same issue

**Comment by yanlinaung30** [comment]
same issue. In my case, am trying to release via Expo XDE. I have an app created by react-native-cli. I changed to CRNA app by this [guide](https://docs.expo.io/versions/latest/introduction/faq.html#how-do-i-get-my-existing-react-native-project-running-with-expo).
![image](https://user-images.githubusercontent.com/4996766/31113777-56aaedc0-a80a-11e7-812b-dd30d2643f0b.png)

**Comment by ShayanJavadi** [comment]
@yanlinaung30 https://github.com/expo/expo/issues/710 I fixed my issue here. I cleared my cache and changed to Yarn and it started working.

**Comment by AhadCove** [comment]
Oh wow, you had to switch to yarn,
that's weird. Did you get this error consistently?
Apparently, only one or two of my customers that had my app was getting this error randomly. I haven't heard anything in a while though and couldn't reproduce it.
But on my future builds and apps, I will use yarn, I just wish I knew why

**Comment by mehtaanshul** [comment]
![qq](https://user-images.githubusercontent.com/17105835/32403169-8ffe87cc-c159-11e7-8834-ac518f157059.jpg)
I am getting this error and i have tried clearing cache and migrating to yarn.Still not working ??

**Comment by haotangio** [comment]
I had the same issue. After trying so many times, I figured out the final working SOLUTION: uninstall Expo and never use it anymore until it's really ready for being used.

**Comment by brentvatne** [comment]
hello! 

@AhadCove - it's called `getExpoPushTokenAsync`, not `getExponentPushTokenAsync`, if you still have this error then we need to see the code that you're using (the entire file, not just one or two lines) to help you out. this is not a bug in expo, there is some error in your code.

@mehtaanshul and perhaps others with the same error that @mehtaanshul posted: this error [is described in the release notes](https://blog.expo.io/expo-sdk-v22-0-0-is-now-available-7745bfe97fc6) and also [easily googleable](https://www.google.ca/search?q=View.propTypes.style+error&oq=View.propTypes.style+error). `View.propTypes` was removed in react-native in 0.48, and unfortunately it only causes problems with development mode disabled. 

some library that you use, or your own app code, tries to use `View.propTypes.style` but that throws an error because `View.propTypes` is not an object anymore. this problem does not come from expo itself, fwiw. we do try to do our best to make upgrades as easy as possible, and we'll try to keep a closer eye out for upstream issues like this in order to make sure that they at least show up as errors in development mode.

for everyone in this thread and others who stumbled across it - "AppRegistry is not a registered callable module" just means that there is some error in your code that prevents the JS from being loaded -- the error underneath it is the error that you are looking for.

if anyone has specific error messages that they are having trouble with, please post a new issue with the information on what the error message is ("AppRegistry is not a ...." is not the actual error message)

**Comment by samassango** [comment]
@brentvatne  I am only getting this "AppRegistry is not a callable module" in iOS only in android it's working just fine.

**Comment by quincycs** [comment]
FYI i had this error on iOS and Android.  It had to do with installing MobX + decorations.  I fixed it by removing decorations, deleting node_modules, yarn install, publishing and uninstalling/reinstalling the expo app.

**Comment by terribleben** [comment]
Warning to anybody finding this thread:

"Module AppRegistry is not a registered callable module" doesn't tell us anything about your error. It is a downstream symptom in all React Native projects (at time of writing) indicating "your app had some other error before it could finish loading." You are unlikely to find any useful solution to your problem in this thread because everybody here is posting about different issues. (also see: brent's post earlier in this thread with a lot of the same explanation)

Recommended steps:

- Check your packager logs for any other errors that may have happened in advance of "Module AppRegistry is not a registered callable module"
- If the error only happens after publishing, try running your app with dev=false and minify=true to get a JS bundle closer to what you'd see in production
- Open a new issue with more information (because unfortunately we won't be able to help much if we only see this message alone)
