### ISSUE TITLE
ImagePicker.launchCameraAsync only records videos at 480x360

### ISSUE THREAD

**Issue by tywalch** [expo/expo#6224]
### Environment
```
  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.7.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.12.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.4.1
```

### Target
iPhone X iOS 13.1.3

### Steps to Reproduce

Using the the `ImagePicker.launchCameraAsync` method results in only low quality (480x360) videos regardless of the `quality` and `aspect` options passed.

### Expected Behavior

Passing a `quality` option of `1` should result in a video with the highest possible quality 

### Actual Behavior

Using the the `ImagePicker.launchCameraAsync` method results in only low quality (480x360) videos regardless of the `quality` and `aspect` options passed.

### Reproducible Demo

`VideoLauncher.js`

```
import React from "react";
import { View, TouchableHighlight, Text, StyleSheet } from "react-native";
import { EvilIcons } from "@expo/vector-icons";
// import Colors from "../constants/Colors";
let Colors = {
  tintColor: "#FFF" 
}

export default function VideoLauncher({
  icon,
  label,
  onPress,
  iconColor = Colors.tintColor,
}) {
  return (
    <View style={styles.container}>
      <TouchableHighlight
        style={styles.select}
        underlayColor="#1a1a1a"
        onPress={onPress}>
        <View style={styles.button}>
          <EvilIcons name={icon} size={64} color={iconColor}></EvilIcons>
          <Text style={{ color: "lightgrey" }}>{label}</Text>
        </View>
      </TouchableHighlight>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    height: 160,
    width: 160,
  },
  select: {
    flex: 1,
  },
  button: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "grey",
    borderRadius: 20,
    borderStyle: "dashed",
  },
});
```

`VideoUploadScreen.js`

```
import * as React from "react";
import { View } from "react-native";
import * as ImagePicker from "expo-image-picker";
import Constants from "expo-constants";
import * as Permissions from "expo-permissions";
import VideoLauncher from "../components/VideoLauncher";
// import Colors from "../constants/Colors";
let Colors = {
  tintColor: "#FFFFFF",
  successColor: "#FFFFFF" 
}

let launchTypes = {
  gallery: "launchImageLibraryAsync",
  camera: "launchCameraAsync",
};

export default class VideoUploadScreen extends React.Component {
  static navigationOptions = {
    title: "Upload Video",
  };

  state = {
    image: null,
  };

  render() {
    let { image } = this.state;

    return (
      <View
        style={{
          flex: 1,
          alignItems: "center",
          justifyContent: "space-around",
        }}>
        <VideoLauncher
          icon="image"
          label="Choose"
          onPress={() => this.pickImage(launchTypes.gallery)}
        />
        <VideoLauncher
          icon="camera"
          iconColor={Colors.successColor}
          label="Capture"
          onPress={() => this.pickImage(launchTypes.camera)}
        />
      </View>
    );
  }

  sendVideo = async ({ type, uri }) => {
    let name = "video";
    let method = "POST";
    let body = new FormData();
    body.append(name, { name, type, uri });
    let res = await fetch("http://10.0.0.11:3000/video", {
      body,
      method,
    });
    return res.json();
  };

  componentDidMount() {
    this.getPermissionAsync();
  }

  getPermissionAsync = async () => {
    if (Constants.platform.ios) {
      const camera = await Permissions.askAsync(Permissions.CAMERA);
      const roll = await Permissions.askAsync(Permissions.CAMERA_ROLL);
      if (roll.status !== "granted" && camera.status === "granted") {
        alert("Sorry, we need camera roll permissions to make this work!");
      }
    }
  };

  pickImage = async (type = launchTypes.camera) => {
    try {
      let result = await ImagePicker[type]({
        mediaTypes: ImagePicker.MediaTypeOptions.Videos,
        allowsEditing: true,
        quality: 1,
        aspect: [16, 9],
      });

      // result shows small 
      console.log("result", result);

      if (!result.cancelled) {
        await this.sendVideo(result);
        this.setState({ image: uri });
      }
    } catch (err) {
      console.error(err);
    }
  };
}
```

Any help would be much appreciated, maybe this is expected given something I don't yet understand about Expo.

**Comment by cruzach** [comment]
Hm, I just tested this in [this snack](https://snack.expo.io/@charliecruzan/imagepickerfromcameraroll35) with the same iOS version, and saw normal quality. Can you let me know if this snack doesn't work for you? If it does, it should give you a starting point to debug from

**Comment by lukmccall** [comment]
I think this will be fixed by [this PR](https://github.com/expo/expo/pull/6046).

**Comment by lukmccall** [comment]
I believe it'll be fixed in SDK 36. So I'm closing this issue right now. However, feel free to reopen it if this bug will occur.

**Comment by tywalch** [comment]
> I believe it'll be fixed in SDK 36. So I'm closing this issue right now. However, feel free to reopen it if this bug will occur.

Unfortunately it looks like I am still seeing this issue on my device. I upgraded to SDK 36.

```
  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.7.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^3.12.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.11.1
```

**Target:** `iPhone X 13.2.3`

It looks like regardless of the `VideoExportPreset` I choose, I always get back a 480x360 video from `ImagePicker.launchCameraAsync`. Could this have anything to do with how I am testing, like not building the app but instead using the Expo Client app on iOS?

With the caveat that I am completely unfamiliar with expo under the hood, I looked at the PR referenced above and it looks like the test case made for that PR would still pass given the issue I'm seeing:

```
    describe('launchImageLibraryAsync', async () => {
      it('mediaType: image', async () => {
        const image = await ImagePicker.launchImageLibraryAsync({
          mediaTypes: ImagePicker.MediaTypeOptions.Images,
        });

        testMediaObjectShape(image, 'image');
      });

      it('mediaType: video', async () => {
        const video = await ImagePicker.launchImageLibraryAsync({
          mediaTypes: ImagePicker.MediaTypeOptions.Videos,
        });

        testMediaObjectShape(video, 'video');
      });

      if (Platform.OS === 'ios' && parseInt(Platform.Version, 10) > 10) {
        it('exporPreset should affect video dimensions', async () => {
          const video = await ImagePicker.launchImageLibraryAsync({
            mediaTypes: ImagePicker.MediaTypeOptions.Videos,
            videoExportPreset: ImagePicker.VideoExportPreset.H264_640x480,
          });

          testMediaObjectShape(video, 'video');

          if (!video.cancelled) {
            expect(video.width).toBeLessThanOrEqual(640);
            expect(video.height).toBeLessThanOrEqual(480);
          }
        });
      }
    });
``` 

Namely this `expect` would allow for  different (smaller) video dimensions than those set by the dev. In this case they were explicitly set as `ImagePicker.VideoExportPreset.H264_640x480`.

```
expect(video.width).toBeLessThanOrEqual(640);
expect(video.height).toBeLessThanOrEqual(480);
```

**Comment by lukmccall** [comment]
Hi @tywalch, tests were written in this way because iOS can only decrease size. So when you provide a video recorded in small resolution then the video will be unchanged. 

Did you try pass differents `VideoExportPreset`? 
I think the way you are testing is irrelevant. It should also work on `expo-client`.

**Comment by tywalch** [comment]
> Hi @tywalch, tests were written in this way because iOS can only decrease size. So when you provide a video recorded in small resolution then the video will be unchanged.
> 
> Did you try pass differents `VideoExportPreset`?
> I think the way you are testing is irrelevant. It should also work on `expo-client`.

I tried ‘Passthrough’, ‘HighestQuality’, and ‘HEVC3840x2160’. When I get on my PC again I can put together a test component for all the types and see if any of them result in a change. I’ll paste that component here. Let me know if there’s anything else I can provide related to my local env that could help. I’ll try on my other Mac as well.

**Comment by tywalch** [comment]
Better late than never!

I am trying this now on a different macbook pro (2018 15in):

```
  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^3.12.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.11.7
```

I experience the same issue: Video records at low resolution, even the view prior to recording though the camera looks lower quality regardless of the VideoExportPreset.

**Comment by adamck** [comment]
Appears that `videoQuality` is unspecified on the picker in EXImagePicker.m.

It defaults to a lousy medium quality, per https://developer.apple.com/documentation/uikit/uiimagepickercontroller/1619154-videoquality

**Comment by tywalch** [comment]
> Appears that `videoQuality` is unspecified on the picker in EXImagePicker.m.
> 
> It defaults to a lousy medium quality, per https://developer.apple.com/documentation/uikit/uiimagepickercontroller/1619154-videoquality

I really wish I knew more about Objective C, is this a relatively quick fix? I tried to setup testing on my local for expo and had issues so I dont currently have a good way to try and implement myself.

**Comment by lukmccall** [comment]
@tywalch, I've created a demo app for you: https://github.com/lukmccall/launchCameraAsyncIssue. This app has the video quality set to hight. 

So, to run it::
- download the repo
- run `yarn` or `npm` to install dependencies 
- open `ios/*.xcworkspace` through Xcode
- select device and start app
![image](https://user-images.githubusercontent.com/9578601/80620630-8613a680-8a46-11ea-8e5d-22b9a6a2c4a4.png)

You can find a more detailed walkthrough here: https://reactnative.dev/docs/running-on-device#2-configure-code-signing.

Feel free to change the js code. I didn't test it on the real device, so something could go wrong.

It this bug fix will work, please, go to the `packge.json` and change: `"expo-image-picker": "file:./expo-image-picker"` to `"expo-image-picker": "8.0.1". Then run `yarn install --force` and test it again. Cause you're using a different workflow, it can affect image-picker behavior. So, we need to test it with and without this patch.

**Comment by lukmccall** [comment]
If you encounter any problems, please let me know ;)

**Comment by lukmccall** [comment]
Closing this issue due to inactivity. Moreover, we can't reproduce it either. If this is still a problem for you and it's reproducible using the latest SDK version, feel free to open up a new issue!

**Comment by vujevits** [comment]
I'm having the same issue, the output is a 480x360 video, in MJPG format. I tried @lukmccall your demo app and it works as expected (1080x1920), it needed a few other steps (pod install, and building the `expo-image-picker` subproject). But removing the `videoQuality` setting did not reproduce the original issue :/

I'm using expo sdk 37.
