### ISSUE TITLE
Flashmode doesn't turn on for recordasync(), but works fine for takesnapshotasync()

### ISSUE THREAD

**Issue by grantespo** [expo/expo#6361]
### Environment

Expo CLI 3.2.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.16.2 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 3.10.10 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.2/11B52 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.2.3

### Steps to Reproduce

1. Set `flashMode` to on:
          <Camera ref={ref => { this.camera = ref; }}
                  flashMode={Camera.Constants.FlashMode.on}>

2. call `recordAsync()`

### Behavior

Flash should be turned on while video is recording. Flash works for `takesnapshotasync()`, but on `recordAsync()`

**Comment by cruzach** [comment]
Thanks for reporting, this will be fixed in SDK 36:

issue- https://github.com/expo/expo/issues/6086
PR - https://github.com/expo/expo/pull/6128

**Comment by grantespo** [comment]
> Thanks for reporting, this will be fixed in SDK 36:
> 
> issue- #6086
> PR - #6128

just updated to 36.0, wasn't fixed :/

**Comment by cruzach** [comment]
Looks like setting `flashMode={Camera.Constants.FlashMode.torch}` now works in SDK 36, but recording with `flashMode={Camera.Constants.FlashMode.on}` doesn't turn on the flash, thanks for reporting again

**Comment by grantespo** [comment]
didn't realize it worked for torch :) My work around right now is this before calling `recordAsync()`

`this.setState({ isRecording: true, flashType: this.state.flashType === Camera.Constants.FlashMode.on ? Camera.Constants.FlashMode.torch: {} });`

**Comment by rndgrin** [comment]
sdk36 not working. updated to sdk37, still does not work.

**Comment by ZeinHajjAli** [comment]
I'm still having the same problem on sdk37, torch on iOS still has the flash turn off when recordAsync is called. Setting the flashMode state before or after recordAsync doesn't solve it either.

**Comment by leandroromano** [comment]
Reading this [fix](https://github.com/react-native-camera/react-native-camera/pull/1395/commits/8c6960178922492bf49fc44fbab25b638209dc4e) on react-native-camera package, i tried the same on this expo-camera. In node_modules/expo-camera/ios/EXCamera/EXCamera.m i added this line `[self updateFlashMode];` just before the line `[self.movieFileOutput startRecordingToOutputFileURL:outputURL recordingDelegate:self];` and it works. It records with flash mode torch on. The only thing is that when start record it flick flash and instantaneously it turned on during recording. May be this could fix the issue...

**Comment by nero2009** [comment]
@leandroromano After adding this `[self updateFlashMode];` to node_modules/expo-camera/ios/EXCamera/EXCamera.m the flash still goes off immediately the video starts recording.

Do I need to do anything after adding that piece of code?

**Comment by rajeshde** [comment]
> @leandroromano After adding this `[self updateFlashMode];` to node_modules/expo-camera/ios/EXCamera/EXCamera.m the flash still goes off immediately the video starts recording.
> 
> Do I need to do anything after adding that piece of code?

Yes, I faced the same even after adding `[self updateFlashMode];`

On Android turning on `torch` mode right before recordAsync() keeps the flash on ( with a blink ) while recording. But on iOS the flash is going off as soon as the video starts recording.

**Comment by leandroromano** [comment]
Im working in a bare react native project and i have updated expo-camera to version `11.2.1` and the issue does not occur anymore. I think it has been solved in some update, because actually in iOS i can record videos with flash without any flicks or bugs. I suggest to update the package or the sdk in an expo managed project, in order to get this issue fixed

**Comment by rajeshde** [comment]
I am working in a bare react native project too, and I am using expo-camera `11.2.2` which is the latest at present.

**Comment by georgez98** [comment]
Working with managed workflow (Expo 43 and expo-camera `12.0.3`) and still facing the same issue. Setting to `Camera.Constants.FlashMode.torch` or setting state before calling recordAsync does not work.

**Comment by IliasseWahbi** [comment]
Hi, still have this issue ONLY on iOS with **expo-camera** 12.2.0, **react-native** 0.68.2 and **expo** 45.0.8.
Flash works well to take a picture though.

**Comment by shrihari1999** [comment]
Why is no one talking about this? I'm having the same issue with expo 48. Flash switches off when recordasync is called

**Comment by gachezra** [comment]
I'm using expo-camera 15.0.6 with expo 51, and I still have the same problem guys were facing years ago. Will there be any fix coming soon or do we need to transition?

**Comment by LarsDanau** [comment]
Having the same issue. Both `flashMode='on'` and `enableTorch={enabled}` don't keep the torch / flashlight on when starting a recording.
