### ISSUE TITLE
SQLite database deletion / upgrading (opening downloaded DB on iOS fails)

### ISSUE THREAD

**Issue by nikki93** [expo/expo#639]
More info at: https://forums.expo.io/t/sqlite-db-doesnt-get-created-if-deleted/2295/7

Add a method to delete SQLite databases, make sure an upgrade flow is present.

**Comment by NunoCardoso** [comment]
How do we know when/if this feature is added in what sdk version?

**Comment by ide** [comment]
We generally announce things once they're released in our release notes (on blog.expo.io). If there's something you need that hasn't been announced and you have a deadline to meet, you should detach and use ExpoKit to meet your schedule.

**Comment by nikki93** [comment]
Should be fixed by https://github.com/expo/expo/commit/12aeb4aa6b871c4763dd228ee5de4def043e2a8c and most likely released in SDK 24.

**Comment by NunoCardoso** [comment]
Hi nikki93. Thanks for all. 

I am adding Sdk 24 today on my app, and it seems to work on Android but not on iOS. It still fails the first transaction of a reopened DB file. 

I upped sdk version to 24, deleted node_modules, npm install, close Expo XDE project and deleted app on iOS simulator, all to make sure I have sdk 24 running.

**Comment by mchen37** [comment]
Hi, I am experiencing the same issue. Using iOS and Expo SDK 24, redownloaded/restarted/cleaned everything as well. I am able to run a transaction on a db file and then I download a new db file to replace it. Upon attempting another transaction on the reopened db file, it fails. If I restart the app, I can query the db file fine though so there is nothing wrong with the file itself.

**Comment by NunoCardoso** [comment]
Hi Nikki. Can you reproduce this issue? If so, and if a fix is needed, will it be pushed on a minor expo version commit (say 24.0.3)?

**Comment by ide** [comment]
@mchen37 @NunoCardoso Thanks for trying out the new API and sorry it isn't working for you. It's helpful to know the issue appears to be just on iOS.

To set expectations, I believe @nikki93 hasn't currently been looking into this but we'll re-open this issue to track it.

**Comment by NunoCardoso** [comment]
Testing Expo SDK 25 now. It still doesn't work. Any change that this gets pushed in a minor release?

**Comment by rodrigore** [comment]
I'm also still fighting with this problem on iOS 😢

**Comment by NunoCardoso** [comment]
Is this patched on SDK 26? This is a reported bug since SDK 23...

**Comment by ide** [comment]
We update GitHub issues when there is a meaningful change to announce, and haven't addressed this issue. In the interest of setting expectations fairly and with integrity, we're currently not planning to work on this in SDK 27 and when this issue is addressed we will post a note here.

**Comment by mchen37** [comment]
Is there a way to close the db file in iOS? We have been trying to solve this issue for some time now, as our client is running into this, without having the user close and reopen the app.

I see here: https://github.com/expo/expo/blob/9586ae5a18ae10f0d3481906a549fff1fab64505/ios/versioned-react-native/ABI26_0_0/Expo/Core/Api/ABI26_0_0EXSQLite.m#L212
there is a function for dealloc which should close the database.

My idea was something like this:
```
var db = SQLite.openDatabase('db.db');
/* access the db */
db = null; //not sure if this triggers the dealloc?
/* download a new db.db file */
db = SQLite.openDatabase('db.db');
```

Unfortunately this does not solve the problem for us. I can't be sure what exactly causes this issue, but if anyone has an idea for a workaround that would be a lifesaver!

**Comment by cgrossde** [comment]
I have the same problem -.- I would like to repace the SQLite DB in place to support a Backup/Restore use-case.

**Comment by NunoCardoso** [comment]
So, this issue was reported around SDK 22, we are still on SDK 27 and half a year later, it is still unaddressed. 

I get it, free code and stuff, but this should be prioritized higher.

**Comment by cgrossde** [comment]
@ide and @nikki93: I just investigated this issue for iOS and android. Currently the logic works like this:
```
Map cachedDatabases = new Map<dbName, DB>
getDatabase(dbName) {
  path = pathForDatabaseName()
  if (file exists at path) {
   get database from cached databases map
  }
  if (no database cached for that name in map) {
    remove value from cachedDatabases map
    init new database
    add new database to cachedDatabases map
  }
}
```
**iOS code**
https://github.com/expo/expo/blob/12aeb4aa6b871c4763dd228ee5de4def043e2a8c/ios/Exponent/Versioned/Modules/Api/EXSQLite.m#L41
**Android code**
https://github.com/expo/expo/blob/12aeb4aa6b871c4763dd228ee5de4def043e2a8c/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/SQLiteModule.java#L173

**When does the bug occur?**
```
const DB_PATH = `${FileSystem.documentDirectory}SQLite/my.db`
let db = SQLite.openDatabase('my.db')
// Download backup of my.db from internet and replace it at DB_PATH
await FileSystem.downloadAsync('http://example.com/my.db', DB_PATH)
// Try to open downloaded db
db = SQLite.openDatabase('my.db')
```

**Why does it fail?**
Opening the downloaded DB fails because we do not get a new database instance but instead the old one from the `cachedDatabases` map. This one use a filesystem pointer pointing to the overwritten old DB file and therefore fails.

**Suggstion for a fix**

`db.close()`: Please give us the ability to "close" a DB. This `close` function would just remove the DB instance from the `cachedDatabases` map. The next `openDatabase` for a similar named DB would then create a new DB instance.

**Comment by cuibonobo** [comment]
I was recently writing a TypeORM driver for Expo and was surprised that the API has no way of 'closing' the database. To satisfy the TypeORM library's requirements for a `close()` method, I just assigned `undefined` to the database variable (similar to what @mchen37 was suggesting), but it would be much better to follow @cgrossde's suggestion and add a way to close the database.

**Comment by cgrossde** [comment]
@ide @nikki93 I created two PRs to fix it in the way suggested. I don't have a working dev environment of expo and expo-sdk. This is meant as a jumpstart for you, hope it helps ;) 

@cuibonobo: Damn, setting it to `null` also works, was assuming @mchen37 solution didn't work for iOS.

**Comment by cuibonobo** [comment]
I wanted to mention in case anyone comes looking that the PRs that @cgrossde added do allow for closing the SQLite database, but the `close` method isn't 'public': `Expo.SQLite.openDatabase()` returns a `WebSQLDatabase` object that has Expo's `SQLiteDatabase` in the `_db` property. As a result, to close the database you need to do something like this:

```javascript
// Open the database
const db = Expo.SQLite.openDatabase("db_name");

// Close the database
db._db.close();
```

To fix this, a new public `close` method would need to be added to `WebSQLDatabase` in [Expo's fork of node-websql](https://github.com/expo/node-websql).
