### ISSUE TITLE
App is always crashing in hot reload mode

### ISSUE THREAD

**Issue by onrige** [expo/expo#672]
Hey. Just updated to a new version (21), and there is a problem when hot reload is enabled. 
To reproduce: 
1) Enable hot reload
2) Try to change something (it was styles in separate file in my case) 
3) Go to background
4) Return to simulator -> there is a crash

UPD: Also there are some problems with styles all over the application, hmm

**Comment by jarlefosen** [comment]
I've experienced some issues with Hot Reload as well.
The output I get is something like 
`Connection to <URL>/debugger-proxy timed out`
For reference to a similar or same issue: https://github.com/jhen0409/react-native-debugger/issues/72

The only trait I have identified for now is that the packager logs are outputting that it's launching dev tools twice instead of only once.

```
10:06:56 PM    Launching Dev Tools...
10:06:56 PM    Launching Dev Tools...
```

In order to resolve this issue, I have to disable Hot Reload in the device before the client times out, click Restart in the Expo UI. Once it's done, I refresh the app, and then I can safely re-enable Hot Reload. Well, until it suddenly fails again.

**Comment by terribleben** [comment]
@onrige 
- is this on iOS or Android?
- What is "a crash" in this case? Does the app stop running, or do you see a red screen?

@jarlefosen are you seeing the same symptoms as the original poster (app crashing when backgrounded+foregrounded with HMR turned on)? If you're seeing a different issue, would it be possible for you to open a separate thread so we can track both?

**Comment by onrige** [comment]
@terribleben Hey. So it's happening on Simulator iOS 10.3 and after crash app stop running, I see just Home screen of Simulator.

**Comment by onrige** [comment]
@terribleben Any updates? After some magic I was able to catch this [error](https://imgur.com/a/IYs5V)

**Comment by terribleben** [comment]
I've just tried following your instructions on a SDK 21 project and I can't reproduce this behavior. Hot reloading works for me, and keeps working for a long time without crashing (I've been using one session for 30-40 minutes at the time of writing, and haven't seen a crash). Sending the simulator to the background and bringing it back doesn't have any effect, hot reload continues to work.

If you're seeing intermittent "debugger proxy timed out" messages (as mentioned in the other comment) then it's usually because the websocket connection between your device and the packager or debugger is flaky. Not sure if this is related to the original issue.

Can you provide any other info about how I might reproduce this behavior?

**Comment by onrige** [comment]
Sure. It seems this problem happens only within the RNRF package when changing some components on the fly (NavBar for example, and this component crashing when hot reloading). Should we close issue in this case? It looks like it expo bug anyway.

**Comment by smooJitter** [comment]
I am having this problem and it’s a bit frustrating. My first time using expo and I’m using both debugging and storybook.  I’m getting the same error an @onrige

**Comment by dhruvdutt** [comment]
@smooJitter Try using latest version [25.0.0](https://blog.expo.io/expo-sdk-v25-0-0-is-now-available-714d10a8c3f7). Follow [this guide](https://docs.expo.io/versions/latest/guides/up-and-running.html). It should work now.

**Comment by terribleben** [comment]
Hey all. Are people still experiencing this? I still wasn't able to reproduce the behavior. Based on @onrige's screenshot, the issue might have been an older version of React Native which was reporting an error with a null stack trace, causing the `reportFatalException` method to crash. I haven't had any reports of this recently, but let me know if it's still happening for you.

**Comment by CodeLuca** [comment]
I'm still experiencing it @terribleben

**Comment by robclouth** [comment]
I still get it. It usually happens when there's a packager error or syntax error.
I have to restart the whole bloody simulator because you can't seem to force close apps in iOS 10. You open it up and it loads at the frozen screen...

**Comment by damiangreen** [comment]
I get it on android a lot.

**Comment by terribleben** [comment]
Closing because we think this may be resolved and I haven't got more info from the original reporters. Since this thread is old-ish, I'm going to lock it in order to encourage people to open a new thread if you think you've found a similar issue. Please feel free to do that if you're seeing crashes during hot reload.
