### ISSUE TITLE
Built APK app crashes on "Exponent.Google.logInAsync"

### ISSUE THREAD

**Issue by omerdn1** [expo/expo#69]
Hey, I just built (with exp) my first apk and encountered an error with Google sdk, the app crashes on "Exponent.Google.logInAsync".
Works fine when testing inside of Exponent. Facebook login works fine as well.

Tested on Android.

**Comment by 7ynk3r** [comment]
@omerdn1, what was the problem?

**Comment by niwox** [comment]
Getting same error on android. Any fix ?

**Comment by 7ynk3r** [comment]
Use "web" for "behavior" for both dev and release.

**Comment by ide** [comment]
If you experience native crashes the best way to figure out what's going on is to look at the native device logs (https://docs.expo.io/versions/v16.0.0/guides/logging.html#optional-manually-access-device-logs) and if there's a problem with Expo, send the logs to us.

**Comment by 7ynk3r** [comment]
hi @ide 

`behavior` only works with `web`, and not with the default value `system`.

It's easy to reproduce, just follow the steps to configure a standalone android app. You'll see that only works for `behavior` equals `web`.

I've added more information to the following ticket.
https://github.com/expo/exp/issues/51

**Comment by brentvatne** [comment]
@janicduplessis - not sure what's going on here exactly, when you get a chance (after SDK17 release stuff) can you take a look and update docs if necessary or close this issue? :)

**Comment by janicduplessis** [comment]
I think I figured what the problem could be. It looks like the `androidStandaloneAppClientId` must be of type `Web application` instead of `Android`. I was able to get it working when using that. Looks like a documentation issue since it does say to use a client id of type `Android`.

Can anyone that had the issue confirm this?

**Comment by chriscohoat** [comment]
@7ynk3r for your standalone Android app did you set `behavior` to `web` and then use an Android or Web OAuth client ID?  I'm getting a 400 response from Google when I try to use a `web` behavior on a standalone Android app:

```
Custom scheme uris are not allowed for 'web' client type
```

@janicduplessis changing `androidStandaloneAppClientId` to be of type Web application doesn't seem to work for me...I still get the 12501 error.

**Comment by ecerroni** [comment]
Is the documentation going to be updated? I think it should be changed asap if it's really working only when using `behavior` to `web` and setting `androidStandaloneAppClientId` to an Android-type OAuth 2.0 client ID.

I'm experiencing similar issues where I have the expo client working perfectly while the standalone app won't login. It's not only for Google, I can't login with Facebook either.

It's on android where unfortunately behavior `web` can't be set for Facebook as it's an IOS only feature.

I'd expect that once deployed the standalone app would work out of the box. This is blocking my client release atm.

**Comment by brentvatne** [comment]
@ecerroni - can you send a pull request to update the docs? expo/expo-docs

**Comment by janicduplessis** [comment]
This should be fixed in sdk 21, the instruction in the docs are good.

**Comment by tomcrusader** [comment]
Still broken as far as we can see.
We depend on Google signin and will be unable to go to production without a fix.
Obviously double checked Google OAuth credentials and rebuilt.

```
      "ios": {
      "bundleIdentifier": "se...",
      "config": {
        "googleMapsApiKey": "AIzaSyARKW...tg8TDu-BqsfUoags",
        "googleSignIn": {
          "reservedClientId": "com.googleusercontent.apps.16...ons"
        }
      },
      "buildNumber": "1.0.0",
      "isRemoteJSEnabled": true,
      "supportsTablet": false,
      "associatedDomains": [
        "myDomain.com"
      ]
    },
    "android": {
      "package": "se......",
      "versionCode": 1,
      "config": {
        "googleSignIn":{
          "certificateHash": "1250CCD9...DE89FBEE7",
          "apiKey": "AIzaSyAnX4ln...wiqsZjFWeMaQ"
        },
        "googleMaps": {
          "apiKey": "AIzaSyARKW...8TDu-BqsfUoags"
        }
      },
```

**Comment by tomcrusader** [comment]
Several topics on this here on GitHub and StackOverflow, but no solutions. I.E doesn't work?

We depend on Google signin and will be unable to go to production without a fix.

Obviously double checked Google OAuth credentials and rebuilt.

```json
      "ios": {
      "bundleIdentifier": "se...",
      "config": {
        "googleMapsApiKey": "AIzaSyARKW...tg8TDu-BqsfUoags",
        "googleSignIn": {
          "reservedClientId": "com.googleusercontent.apps.16...ons"
        }
      },
      "buildNumber": "1.0.0",
      "isRemoteJSEnabled": true,
      "supportsTablet": false,
      "associatedDomains": [
        "myDomain.com"
      ]
    },
    "android": {
      "package": "se......",
      "versionCode": 1,
      "config": {
        "googleSignIn":{
          "certificateHash": "1250CCD9...DE89FBEE7",
          "apiKey": "AIzaSyAnX4ln...wiqsZjFWeMaQ"
        },
        "googleMaps": {
          "apiKey": "AIzaSyARKW...8TDu-BqsfUoags"
        }
      },    "extra": {
      "google": {
        "maps": "AIzaSyARK...sfUoags",
        "webClientId": "16279835...47fkoi.apps.googleusercontent.com",
        "androidStandaloneAppClientId": "16279835...1o49ik7.apps.googleusercontent.com",
        "iosStandaloneAppClientId": "16279835...qbc15ukcbons.apps.googleusercontent.com",
        "androidClientId": "162798352...c5rg.apps.googleusercontent.com",
        "iosClientId": "16279835...ec2nn6a.apps.googleusercontent.com"
      }
    }
```
```javascript
import { Google, Constants } from 'expo';
...
import { SaveByKey } from './StorageActions';

const config =
 Constants.appOwnerShip === 'standalone' ? {
   webClientId: Constants.manifest.extra.google.webClientId,
   androidStandaloneAppClientId: Constants.manifest.extra.google.androidStandaloneAppClientId,
   iosStandaloneAppClientId: Constants.manifest.extra.google.iosStandaloneAppClientId,
} :
{
  androidClientId: Constants.manifest.extra.google.androidClientId,
  iosClientId: Constants.manifest.extra.google.iosClientId,
  webClientId: Constants.manifest.extra.google.webClientId,
};

/**
 * The resulting user
 * @type {User}
 * @memberof GoogleActions
 */
let user = null;

/**
 * Login to Google and store user to AsyncStorage
 */
const GoogleLogin = () => async (dispatch) => {
  dispatch({ type: LOGIN_BUSY });

  try {
    const result = await Google.logInAsync(config);
```

https://forums.expo.io/t/google-signin-in-standalone-app/2737/7
https://github.com/expo/expo/issues/69

**Comment by jjgumucio** [comment]
I'm exactly on the same page with @tomcrusader! 
Any news on this?
I'm using the Expo sdk version 21.0.0

**Comment by robertobrogi** [comment]
Hi, i have the same problem with new version 25.0.0

` try {
            const result = await Expo.Google.logInAsync({
                androidClientId: PROPERTIES.ANDROID_CLIENT_ID,
                iosClientId: PROPERTIES.IOS_CLIENT_ID,
                behavior:'web',
                scopes: ['profile', 'email'],
            });

            if (result.type === 'success') {
                return this.getUserInfo(result.accessToken);
            } else {
                return {cancelled: true};
            }
        } catch(e) {
            return {error: true};
        }`

but in android stand alone app make a crash...

**Comment by gibrit** [comment]
i had the same error with version 25.0.0..
if we take   the code  of @tomcrusader    as  an example 
solution which  is worked for me  like ..
i hope it helps @robertobrogi  too .. 
```
const config =
 Constants.appOwnerShip === 'standalone' ? Constants.platform.ios ? {
   iosStandaloneAppClientId: Constants.manifest.extra.google.iosStandaloneAppClientId,
} :{
   androidStandaloneAppClientId: Constants.manifest.extra.google.androidStandaloneAppClientId,
}:
{
  androidClientId: Constants.manifest.extra.google.androidClientId,
  iosClientId: Constants.manifest.extra.google.iosClientId,
  webClientId: Constants.manifest.extra.google.webClientId,
};

```

**Comment by tomcrusader** [comment]
@gibrit 's solution worked in Standalone build (Android APK). Thanks

**Comment by akucukkilic** [comment]
Hello everyone, i have the same issue with new version 25.0.0 and I have tried everything above.
