### ISSUE TITLE
Camera.recordAsync quality - iOS

### ISSUE THREAD

**Issue by MylesCaley** [expo/expo#735]
Ironically, the quality property is also not working on `recordAsync()` for iOS. Thanks for getting the fix in on `takePictureAsync()` btw.

I believe the issue is the following when using `Camera.Constants.VideoQuality['4:3']` for example, it hits objc land, `EXCameraManager.m`... 

`if (options[@"quality"]) {
      [self updateSessionPreset:[[self class] captureSessionPresetForVideoResolution:(EXCameraVideoResolution)options[@"quality"]]];
    }`

In this case `options[@"quality"]`, which I believe is an NSNumber, can't be cast to `EXCameraVideoResolution`. It will return some arbitrary invalid value and `captureSessionPresetForVideoResolution` will always return the default of `AVCaptureSessionPresetHigh`

Some quick tests locally and a simple integerValue conversion and all seems happy.

`[self updateSessionPreset:[[self class] captureSessionPresetForVideoResolution:(EXCameraVideoResolution)[options[@"quality"] integerValue]]];`

We are real close to shipping our first Expo app, which is a rewrite of a swift app. Is it possible for you all to do an incremental update on the SDKv21? (we are not ejected). Or will need to wait for SDKv22 ? We have no ability to workaround that I could come up with. 

Thanks.

**Comment by ide** [comment]
We won't be able to do an incremental update to SDK 21 since we are finalizing SDK 22 and updating our build process instead. We can make sure that this bug is fixed in SDK 22, which should be available in less than two weeks from now and can notify you when it's available for iOS.

**Comment by MylesCaley** [comment]
That sounds good thanks @ide.

**Comment by terribleben** [comment]
Fix is merged and will go out with next release.

**Comment by ide** [comment]
@MylesCaley The photo and video quality fixes are going out with SDK 22, which we're planning to release very soon (tomorrow ideally). Thanks again for your helpful reports!

**Comment by jaaberg** [comment]
I still experience this as a problem on v22. On iOS I can use 0.001 and the pictures still looks decent. On android the pictures looks almost like paintings and I need to use 0.5 in quality to get decent pictures. 

It seems like the pictures are about the same size on 0.001 (50-200kb), a tenth of the size when quality not given, but the image quality on Android cannot compare to the ones on iPhone, eventhough the cameras shouldn't be that far off in quality. 

Is this intended? 

Tested on Galaxy S7 and iPhone 6.

**Comment by harrymelka** [comment]
Hi, 

I made some test on ios 11, and the size of a video is still huge.
For a video of 4 secondes it weight is 2Mo !!

Do you have any idea what can I do to fix this ?
Before you ask, I use the quality option of 0.2 and Camera.Constants.VideoQuality["720p"], but nothing changed.

`const recordingConfig = {
            quality: 0.2,//Camera.Constants.VideoQuality["720p"],
            maxDuration: 120 * 60
            // maxFileSize:
        };
`

Do you have a way to fix this ?
Thank you

Tested on iPhone 8

**Comment by aalices** [comment]
@harrymelka you cannot use numbers for setting video quality. I think the size is just okay. I recorded a 720p video using the built-in Camera app and a ~4sec video is 4,4MB. I also used iPhone 8.

**Comment by harrymelka** [comment]
@aalices thanks for your answer.
There is no solution to make the video lighter ? I need to compress it before uploading it to the server.

Except adding quality, maxFileSize or maxDuration to control it so that it not exceed 1Mo for example I have no other way to handle it without having to use things like https://github.com/shahen94/react-native-video-processing ?

Thank you

**Comment by RusseII** [comment]
Did you ever solve this? I'm wondering the same thing.

**Comment by kandarpdave** [comment]
Hey @terribleben and @ide , would it be possible for you guys to just include react-native-video-processing library in Expo SDK? (I believe it’s similar story with AirBnb Maps?) It’d be absolutely wonderful if you guys can integrate it - or even some simple video manipulation! Video and camera are getting more and more popular, and I think this’ll give people even more reason to stick with Expo! 😃 thank you Expo team! You guys are doing great!! 👏

**Comment by ide** [comment]
@kandarpdave Including a library that is not maintained by the Expo team is very expensive for us in terms of time and money and also developer trust since we need to make sure our modules stay maintained. For ad hoc use cases, ExpoKit is the sole way to include third-party modules.

Generally speaking, we are shifting most of the effort we put into new APIs into revisiting our existing ones to make them better and also into ExpoKit, which is the path forward for custom native modules and the path we believe many Expo apps will take. A recent post on the Expo blog talks more about our future investments: https://blog.expo.io/expo-for-professionals-218b7937fafb.
