### ISSUE TITLE
"androidNavigationBar" ignored when Modal is visible

### ISSUE THREAD

**Issue by quentez** [expo/expo#7799]
### Environment

```
Expo CLI 3.17.21 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.11.0 - /var/folders/wh/ctzdsw7n5j34k0xn6j71d4gh0000gn/T/yarn--1586550885404-0.2810176708311194/node
      Yarn: 1.22.4 - /var/folders/wh/ctzdsw7n5j34k0xn6j71d4gh0000gn/T/yarn--1586550885404-0.2810176708311194/yarn
      npm: 6.13.7 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.7 => 37.0.7
      react: ^16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.16.1
```

App targets: iOS and Android.

### Steps to Reproduce

1. Change the Android Navigation Bar color by adding the following to `app.json`:

```
"androidNavigationBar": {
  "barStyle": "dark-content",
  "backgroundColor": "#FFFFFF"
}
```

The Navigation Bar should now be white.

2. Use a `<Modal />` component somewhere in the app.

### Expected Behavior

The Navigation Bar appearance should not change when using the `<Modal />` component.

### Actual Behavior

The Navigation Bar reverts to its default color when using the `<Modal />` component.

### Reproducible Demo

I wasn't able to create a Snack since this requires changes to the `app.json` file.
If needed, I can build a repro case in a standalone repository.

**Comment by eliasallex** [comment]
### try using the StatusBar, on the same component as the Modal, forcing the StatusBar style.
ex:
```js
import {
    StatusBar
} from 'react-native';

const App = () => {
    return (
        <StatusBar
            backgroundColor="#FFFFFF"       // your preferences
            barStyle={ ...styleStatusBar }   // your styles
         />
        <Modal/> // Modal implementation
   );
}
```

**see more [Here](https://reactnative.dev/docs/statusbar)**

**Comment by byCedric** [comment]
Hi @quentez, thanks for the issue report! Unfortunately, I wasn't able to reproduce this on our end. If you could provide a repro that would be helpful 😄

**Comment by EzeMortal** [comment]
Same happens to me. I've set the navigation bar to white, but when the modal is opened the color changes to black.

[https://github.com/EzeMortal/expo-navigationbar-modal-bug](https://github.com/EzeMortal/expo-navigationbar-modal-bug)

**Comment by micmob** [comment]
Also experiencing this issue.

**Comment by SrBrahma** [comment]
I am having the exact same issue that was solved in react-native: https://github.com/facebook/react-native/issues/29543

I am also using https://github.com/thebylito/react-native-navigation-bar-color#readme, via EAS.

The lib works but when a modal opens, the navigation color switches back to the one defined in app.json, like

```json
"androidNavigationBar": {
  "backgroundColor": "#ffc138"
 },
```

**Comment by Car-ElWilliams** [comment]
This is still an issue, encountered it recently without any solutions

**Comment by EvanBacon** [comment]
This is an upstream Modal issue, but we now have a module `expo-navigation-bar` which can be used to dynamically change the navigation bar. You could attempt to use something [like this](https://gist.github.com/EvanBacon/d148b2425c5a0bd11b6cecb5f4b72bb8) but for navigation bar, to force the desired settings when a modal is opened.

**Comment by SrBrahma** [comment]
@EvanBacon in the issue that I linked there is a solution. Any way to apply it on expo?

**Comment by EvanBacon** [comment]
The "solution" linked above doesn't really fix the issue just changes it a bit. You can make any modification to the AndroidManifest.xml or styles.xml using [expo config plugins](https://docs.expo.dev/guides/config-plugins/).

**Comment by dragos99** [comment]
I'm still experiencing this. It's insane...

**Comment by AliMonam** [comment]
Modal change the navigation bar color on Android! Any solution?

**Comment by justinantony** [comment]
any solution to this issue.?

**Comment by vanishedvan** [comment]
Been bugging me for a few days, still an issue.

**Comment by qaws5503** [comment]
After 2 years later still are encountering this bug, is there any solution for this problem?

**Comment by davidwico** [comment]
Also experiencing this issue,
`setBackgroundColorAsync` from `expo-navigation-bar` doesn't work with react-native's `Modal`

**Comment by ucheNkadiCode** [comment]
Hopefully this helps someone! I don't use expo, but I believe the issue starts with the React native modal trying to use the default color of navigationBarColor in the res/values/styles.xml file. So by setting it to transparent and then changing it programmatically, this should solve your issue. Full answer below.

I added an answer to something similar on stackoverflow https://stackoverflow.com/a/75046007/17172147

This is the answer below. I did not test it on the status bar, but maybe you could try using "android:statusBarColor" and also setting it to @android:color/transparent as well. Good luck!

-----
I had this problem in Android as well. What I believe is happening is the react-native modal is simply taking the default `android:navigationBarColor` in the styles.xml and so every time it pops up, it overwrites the current navigation bar color until it gets dismissed. 

The flag statusBarTranslucent did not work for me. 

I was able to fix this by navigating to `res/values/styles.xml`

Then in the AppTheme style I added navigationBarColor to be transparent. 
It looks like this 

```xml
 <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:textColor">@android:color/black</item>
    <item name="android:navigationBarColor">@android:color/transparent</item> // <----This is what I added
  </style>
```

Then in my react native code, I used `react-native-navigation-bar-color`. I believe this should work with `expo-navigation-bar` since the main issue is derived from react native modal trying to overlay the default navBarColor value.

```javascript
import changeNavigationBarColor from "react-native-navigation-bar-color";

  const setDarkMode = (isDarkMode: boolean) => {
    // logic to change my app's themeProvider to dark mode
    changeNavigationBarColor(isDarkMode ? "black" : "white"); // Then I change the navigation bar color.
  };
```

**Comment by rahuldasgupta** [comment]
Still facing the same issue

**Comment by av-dias** [comment]
3 years later... any solution for this issue?

**Comment by jd615645** [comment]
still have the same issue

**Comment by biskyy** [comment]
4 years later, still here.

**Comment by symonxdd** [comment]
Almost 4,5 years later and still present, are we a joke to you 🙄

**Comment by germanfleitas** [comment]
I don't really know if this issue is exactly an expo issue. I tried the modal component from React Native and it also change the bottom navigation bar to white on its own.

I'm currently working on a project with Expo and I have the same issue described here. I tried to change the color changing the `app.json` directly and I also tried using the `expo-navigation-bar` lib without success.

**Comment by Zo-Bro-23** [comment]
It depends on system theme I think. Black on dark mode and white on light mode. But yes, still present.

**Comment by zollipaul** [comment]
this is still happening ...

**Comment by hasanzu514** [comment]
I was able to get it work with a custom expo plugin that would make the nav bar transparent. 

Create a JS file as follows:
```javascript
const { withAndroidStyles } = require('@expo/config-plugins');

const withNavigationBarColor = (config) => {
  return withAndroidStyles(config, async (config) => {
    const styles = config.modResults;

    const appThemeStyle = styles.resources.style.find(
      (style) => style.$.name === 'AppTheme'
    );

    if (appThemeStyle) {
      const existingItem = appThemeStyle.item.find(
        (item) => item.$.name === 'android:navigationBarColor'
      );

      if (existingItem) {
        existingItem._ = '@android:color/transparent';
      } else {
        appThemeStyle.item.push({
          $: { name: 'android:navigationBarColor' },
          _: '@android:color/transparent',
        });
      }
    }

    return config;
  });
};

module.exports = withNavigationBarColor;
```

To use this plugin, add it to your `app.config.js`:

```javascript
const withNavigationBarColor = require('./frontend/nav-bar-color-plugin');

module.exports = ({ config }) => {
  return {
    ...config,
    plugins: [
      ...(config.plugins || []),
      withNavigationBarColor,
    ],
  };
};
```

You can also import it in your app.json. 

I had to delete and rebuild my android dev build for it to populate correctly in styles.xml.

**Comment by tvillafane** [comment]
@hasanzu514's solution got me 95% of the way there.  Here's my first-pass TS implementation:


`withNavigationBarColor.ts:`

```
import { ConfigPlugin, withAndroidStyles } from '@expo/config-plugins'

export const withNavigationBarColor: ConfigPlugin = (config) => {
  return withAndroidStyles(config, (config) => {
    const styles = config.modResults

    const appThemeStyle = styles?.resources?.style?.find(
      (style) => style.$.name === 'AppTheme'
    )

    if (appThemeStyle) {
      const existingItem = appThemeStyle.item.find(
        (item) => item.$.name === 'android:navigationBarColor'
      )

      if (existingItem) {
        existingItem._ = '@android:color/transparent'
      } else {
        appThemeStyle.item.push({
          $: { name: 'android:navigationBarColor' },
          _: '@android:color/transparent',
        })
      }
    }

    return config
  })
}
```

and `app.config.ts`:

```
import { ExpoConfig, ConfigContext } from "@expo/config"

require("ts-node/register")

/**
 * @param config ExpoConfig coming from the static config app.json if it exists
 * 
 * You can read more about Expo's Configuration Resolution Rules here:
 * https://docs.expo.dev/workflow/configuration/#configuration-resolution-rules
 */
module.exports = ({ config }: ConfigContext): Partial<ExpoConfig> => {
  const existingPlugins = config.plugins ?? []

  return {
    ...config,
    plugins: [
      ...existingPlugins,
      require("./plugins/withSplashScreen").withSplashScreen,
      require("./plugins/withFlipperDisabled").withFlipperDisabled,
      require("./plugins/withNavigationBarColor").withNavigationBarColor
    ],
  }
}
```

**Comment by daniel-richter-hyve** [comment]
Same issue still happening :/

**Comment by moygoca1** [comment]
Same issue no matter what library I use, when the modal shows the navigation bar reverts to its default color.

**Comment by Rakhsan** [comment]
why we don't have a fix after 5 years anyone have a solution that barely works also I am using expo-navigation-bar

**Comment by DaneHarrison** [comment]
For anyone else who runs into this, I was able to find an easy workaround by switching to the [react-native-modal](https://www.npmjs.com/package/react-native-modal) library.

Old code:
```
import { Modal, Pressable, View } from "react-native";
...

<Modal
      visible={isOpen}
      transparent
      animationType="fade"
      onRequestClose={closeModal}
      statusBarTranslucent
>
    <Pressable onPress={() => !stayOpenedOnBackgroundClick && closeModal()} style={{ position: 'absolute', backgroundColor: "rgba(10,10,10,0.5)", width: "100%", height: "100%" }} />
    <View style={{ flex: 1, flexGrow: 1, justifyContent: 'center', alignSelf: 'center' }}>
        {children}
    </View>
        </Modal>
```

New code:
```
import Modal from 'react-native-modal';
...

<Modal
    isVisible={isOpen}
    onBackdropPress={() => !stayOpenedOnBackgroundClick && closeModal()}
    backdropOpacity={0.7}
    useNativeDriver
    hideModalContentWhileAnimating
    statusBarTranslucent
    deviceHeight={height + 50} <--- I had a separate issue where the modal wasnt covering the height of my tabs
>
    <View style={{ justifyContent: 'center', alignItems: 'center' }}>{children}</View>
</Modal>
```
