### ISSUE TITLE
"Not a valid SDK version" when updating to 37.0.0

### ISSUE THREAD

**Issue by caulfield2** [expo/expo#7802]
Similar to [this issue](https://github.com/expo/expo/issues/3112)

![image](https://user-images.githubusercontent.com/25783833/79029125-97107c80-7b58-11ea-83a1-1e03a9fd0bce.png)

Environment:
- macOS Catalina 10.15.4
- Pixel 3 emulator running Android R
- Expo Client 2.15.0
- expo-cli 3.17.21

Things I've tried:
- Wiping the expo cache
- Wiping versions.json
- Wiping and reinstalling node modules
- Upgrading expo-cli
- Downgrading expo-cli
- Using a different emulator
- Using a different version of Android
- Factory resetting my machine (I'm not kidding)

I'm all out of ideas here. Any additional suggestions are much appreciated.

**Comment by byCedric** [comment]
Hi @caulfield2! Oh no, factory resetting sounds like not a great developer experience, let's try to fix that! Somehow it looks like the emulator is running a "strange" Expo Client version. Normally these clients should support multiple SDK versions, but your screenshot only shows it supports SDK 30 only. Could it be related to a custom built client that is used somehow?

One thing that you could try is installing the Expo Client using the CLI, here are some steps to do that:

```
// open the emulator and check if it's accessible
// if the emulator is listed here you can continue, if not adb cant access the emulator
$ adb devices

// go to your project folder and run the client install command
// it should ask you if you want to install the latest SDK available for your project, answer with yes :)
$ expo client:install:android
```

If you run into issues with these commands, lmk! Providing the exact output would be helpful too.

Hope it helps! 😄

**Comment by caulfield2** [comment]
Hey @byCedric. I ran the commands but am still experiencing the same issue. Please see the output below. 

![image](https://user-images.githubusercontent.com/25783833/79137054-9d307400-7d77-11ea-870b-469bf54b259b.png)

**Comment by byCedric** [comment]
ok great, so just to verify. Could you make a screenshot from the "homepage" of the Client app in the Emulator when scrolled all the way at the bottom? Version `2.15.1` should be visible there 😄

**Comment by caulfield2** [comment]
![image](https://user-images.githubusercontent.com/25783833/79140623-e08de100-7d7d-11ea-9e7c-65b14dae19f8.png)

**Comment by byCedric** [comment]
Thanks, this looks great! 😄  So if you open your project with this emulator, it still shows you the same error? If it does, could you share your code or make a small public repo with this?

**Comment by caulfield2** [comment]
Correct. I am still seeing the same error. Unfortunately I am unable to share the code for this project to anyone outside my team. Is there anything else you'd recommend I try? 

I'm wondering where the client is getting the available SDK versions from. Does that have any dependency on my project (node modules, expo dependencies, etc.)?

**Comment by byCedric** [comment]
The "supported" SDK versions are [shipped with the Expo Client itself](https://github.com/expo/expo/blob/c9d34bacd9be0b0c82e37aca69d1af3f40fd6e45/android/expoview/src/main/java/host/exp/exponent/Constants.java#L72-L81). Maybe we can solve this without having to share the project code 😄 Could you share some basics, e.g. (redacted) app manifest and if its managed or bare?

**Comment by caulfield2** [comment]
So I may have made some progress. After updating the client, I made one code change in the MainActivity.java file and changed the listed sdkVersions from 30.0.0 to 37.0.0. 

![image](https://user-images.githubusercontent.com/25783833/79156627-d9c09780-7d98-11ea-97e3-44a423f04fd7.png)

Would you agree that this is the proper solution?

My app now loads, but I'm faced with a new React Native/JS issue. 

![image](https://user-images.githubusercontent.com/25783833/79156697-f361df00-7d98-11ea-8a87-2a4604a5941b.png)

**Comment by byCedric** [comment]
I'm not sure how your project is setup, so I'm not sure if this is the proper solution as you asked. You could do this and upgrade React Native to the proper version, but thats some heavy lifting that we are already doing for you 😄If you forked the Expo client, you probably have to upgrade the shipped react native internal APIs too.

Can you maybe clarify some parts of the project? (without giving exact details ofc 😄)

- Are you using managed flow, bare flow or the ExpoKit flow?
- Are you creating an app or are you doing more stuff like forking the Expo project and adding custom extensions?
- From which Expo SDK version are you upgrading from?

If you are building an app, it might be better to create a new (empty) project and copy your files over. That way, we are sure the setup is either managed (if you don't need extra RN libraries) or bare (if you do need extra RN libraries). I'm not sure if you are able to try this?

Hope it helps 😄

**Comment by CatPerry** [comment]
@caulfield2 Late to this question, but I fixed the same error by just downgrading the versions of Expo and react-native-screens: 

In the `package.json` file, change from `"expo": "~37.0.0"` and `"react-native-screens": "~2.2.0"` to the below versions.  

Then re-run `yarn install`. And lastly, run either `expo start` or `yarn start`.

```
 "dependencies": {
    "expo": "~36.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-screens": "~2.0.0",
    "react-native-web": "~0.11.7"
  },
```

**Comment by abhishekramesh** [comment]
@CatPerry 
I have the same issue, i changed my dependencies to the following listed above and performed yarn install, but i still get the same exception on running expo start.
Should i try changing this 
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
to a lower version?

**Comment by MohabAbugabal** [comment]
Hello everyone. I have the same problem and these solutions are not working? Any help, please? 
![Screen Shot 2020-07-08 at 12 01 15 PM](https://user-images.githubusercontent.com/66527143/86905701-c06a8580-c112-11ea-9310-acfedc1ec63f.png)

**Comment by tsapeta** [comment]
@MohabAbugabal Looks like you're trying to run SDK38 project on the old client version that doesn't support SDK38. Could you please update the app? If that issue still exists after updating, please open a new bug report and provide some more info.

I'm closing this issue since we didn't get similar issues for SDK38 yet, so hopefully it's been fixed. Feel free to open a new bug report if it still persists in SDK38.

**Comment by anto004** [comment]
Thanks, updating the expo app client in the simulator worked for me🙂 I had this problem when I upgraded from expo 37 to expo 38

**Comment by MohabAbugabal** [comment]
Thank you all! Yes, it's working fine now.
