### ISSUE TITLE
[expo-in-app-purchases] connectAsync() causes distracting pop-up on iOS

### ISSUE THREAD

**Issue by Strate** [expo/expo#7941]
## 🐛 Bug Report

This is actually reopen of #5919

On iOS, when initializing the InAppPurchases module with connectAsync(), the SKPaymentQueue restoreCompletedTransactions method is always called.

This causes a distracting pop-up UI prompt to appear immediately, asking the user for their Apple ID and password.

Since InAppPurchases initialization may take place during critical UI flows, like sign-in or browsing an in-app store, it would be better for connectAsync() to operate silently and not cause this UI disruption.

Basically, while connectAsync() does what it is documented to do - returns a promise that resolves to a list of past purchases - I question whether this is really a good design for iOS. Many iOS apps offer a special "Restore old purchases" button, which would be a natural place to call getPurchaseHistoryAsync() and trigger any necessary pop-up UI.

### Environment

Expo CLI 3.1.2 environment info:
System:
OS: macOS 10.14.6
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 12.9.1 - /usr/local/bin/node
Yarn: 1.17.3 - /usr/local/bin/yarn
IDEs:
Android Studio: 3.5 AI-191.8026.42.35.5900203
Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
npmPackages:
@sentry/react-native: ^1.0.7 => 1.0.7
@types/expo: ^32.0.0 => 32.0.13
@types/react-native: ^0.60.19 => 0.60.19
expo: ^35.0.0 => 35.0.0
react: 16.8.3 => 16.8.3
react-native: 0.59.10 => 0.59.10
react-navigation: ^3.13.0 => 3.13.0

(This is a bare build with expo-in-app-purchases@^7.0.0 that was ejected from Expo SDK 35 and uses react-native@0.59.10)

### Steps to Reproduce

In an iOS bare-built app:

await InAppPurchases.connectAsync();

### Expected Behavior

Nothing appears in the UI.

### Actual Behavior

The app is interrupted by a pop-up prompt for the user's Apple ID and password.

### Reproducible Demo

(sorry, I can't think of an easy way to create a repro case due to the large size of the Apple In-App Purchase infrastructure)

**Comment by Strate** [comment]
@OscarYuen resolved #5919 with this:

> It only happens in development and test flight environment. I think it is for sandbox account connection.
> In production, the pop up would not show.

This is definetely not true. Apple documentation says:

> **Important**
> Don't automatically restore purchases, especially when your app is launched. Restoring purchases prompts for the user’s App Store credentials, which interrupts the flow of your app.

https://developer.apple.com/documentation/storekit/in-app_purchase/restoring_purchased_products

So, `connectAsync()` method should not tries to restore transactions, because it can shows popup (it happens event on production, if you are not logged in to itunes account). And App should provide separated button to restore transactions.

**Comment by ide** [comment]
Closing as this has been addressed by https://github.com/expo/expo/pull/8577.

**Comment by cipriancaba** [comment]
Can we please release a new version of `expo-in-app-purchases`? the problem fixed in #8577 appears to be causing issues in production as well, rather than just on testflight

**Comment by ide** [comment]
We’re planning to do a new release this month hopefully (I don’t actually work on this) and this package will go out to npm then. If you need it sooner the code is in this repo and you should be able to npm pack it and install it locally or whatever works for your codebase (there’s nothing specific to Expo).

**Comment by cipriancaba** [comment]
I will definitely do this but I strongly believe this should be released ASAP.. this is happening to our customers in production with them being prompted to subscribe multiple times without any action.. this is really annoying and from the code change I saw this is not something we can fix OTA

**Comment by simplesthing** [comment]
Did this get released? I don't see it in https://github.com/expo/expo/blob/master/CHANGELOG.md

**Comment by Cookizza** [comment]
Hey guys this is hitting us too - I have just been through quite an extensive IAP setup and was planning to commit a few extra paragraphs to the docs - mostly around when certain appstore methods should be called.  I'd be happy to tag on extra stuff around restoring purchases if this change gets pushed out.

+1 for immediate release - as apple review requires you to have a restore purchases button removing the call from connectAsync shouldn't break any implementations.

**Comment by Abdelrahman-Nabil** [comment]
when is this fix getting released ?

**Comment by cipriancaba** [comment]
@ide can you please confirm when this is going to be released? I really don't think this issue should be closed until the fix is released, thanks

**Comment by ide** [comment]
Not sure what the release plan is or if this has/hasn't been released. Take a look at the code on npm to see if this change is included.

We can't leave issues open until the corresponding PR has been published to npm because of the coordination overhead with so many PRs and packages. Plus GitHub is set to automatically close issues once the corresponding PR has been merged into the main branch, not published to npm.

If you need this fix and it's not on npm you can take the code from here and pack it up into a local package and install it locally using standard npm tools like npm pack. This is a good technique for all JS development since it lets you make whatever changes you need in your application.

**Comment by ARMATAV** [comment]
This is super annoying - still see popups immediately upon connection in dev.
