### ISSUE TITLE
[expo-updates] Not properly handling assets with `../` in httpServerLocation

### ISSUE THREAD

**Issue by cipriancaba** [expo/expo#8423]
### Environment

Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.12.0 - /usr/local/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 5.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.20.9

I am targetting an iOS release, trying for 2 days to integrate the expo-updates and expo-splash-screen modules. App works fine in debug, crashes in production

### Steps to Reproduce

I am using version `0.2.3` of `expo-updates` in a monorepo along with version `0.2.3` of `expo-splash-screen`

I have run into the following issues:
 - entryPoint of the app, configured in `app.json` is not properly picked up by the new release of `expo-updates`, thus requiring a manual change in `create-manifest-ios` to point to the correct path, which in my case is `http://localhost:8081/src/index.assets?platform=ios&dev=false` 
 - the second issue was with the fact that that the metro bundler is configured with some watch folders for the dependent monorepo packages, which in turn picks up some assets that are in different packages.. even though my `app.json` contains `"assetBundlePatterns": ["assets/**/*"]`, it seems to pick up paths that are `assets/../../node_modules/random.json`.. I've fixed this issue by filtering the assets passed to createManifest.. This initially caused an inconsistency exception `*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not find the expected embedded asset package.json. Check that expo-updates is installed correctly.'`

### Expected Behavior

- `expo-updates` to support monorepo and correctly read `app.json` config
- `expo-updates` to filter assets correctly based on `assetBundlePatterns`
- `expo-updates` to correctly read the `entryPoint` in app.json 

### Actual Behavior

- `expo-updates` runs asset integrity check against all assets from metro bundler

### Reproducible Demo

```
//app.json
"expo": {
    "name": "app",
    "slug": "****",
    "privacy": "unlisted",
    "sdkVersion": "37.0.0",
    "assetBundlePatterns": ["assets/**/*"],
    "entryPoint": "./src/index.js"
  }

// metro.config.js
module.exports = {
  // New way
  watchFolders: [
    ...Array.from(
      new Set(getDevPaths(projectRoot).map($ => fs.realpathSync($)))
    ),
    path.resolve(__dirname, '../', 'contracts'),
    path.resolve(__dirname, '../', '../node_modules'),
  ],
  transformer: {
    assetPlugins: ['expo-asset/tools/hashAssetFiles'],
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
}
```

_*Updated due to isolating the issue to a different package, not expo-updates. Only left expo-updates issues_

**Comment by cipriancaba** [comment]
I have this extra info when running on device.. Is that a bundle downloaded via `expo-updates`? 

![IMG_6817](https://user-images.githubusercontent.com/695515/82644111-72102e80-9c19-11ea-990e-da0d19791cc3.PNG)

**Comment by byCedric** [comment]
Hi @cipriancaba! Thanks for the issue report, I'll elaborate on the issues you mentioned:

**`expo-updates` to support monorepo and correctly read `app.json` config**
We just fixed support for monorepos in `expo-updates`, that should be released soon 😄 

**`expo-updates` to filter assets correctly based on `assetBundlePatterns`**
Could you try if a more "specific" asset bundle patter works for you? (See [this comment](https://github.com/expo/expo/issues/8362#issuecomment-631353908)) If it does, we know what's going wrong here. If not we have to investigate this a bit further.

**`expo-updates` to correctly read the `entryPoint` in `app.json`**
I think this is related to the monorepos part. If the monorepo can't find the `app.json`, it can't read the `entryPoint` from this manifest. Let's keep this on the "todo" list once we publish the fixed `expo-updates`!

Hope it helps!

**Comment by cipriancaba** [comment]
Thanks for the reply @byCedric 

You can see my watched folders path in the metro config above and here is a snippet returned from `index.assets?platform=ios&dev=false`

```
[{"__packager_asset":true,"fileSystemLocation":"/Users/cipri/dev/pp/al/monorepo/node_modules/@aws-sdk/client-cognito-identity/dist/cjs","httpServerLocation":"/assets/../../node_modules/@aws-sdk/client-cognito-identity/dist/cjs","scales":[1],"files":["/Users/cipri/dev/pp/al/monorepo/node_modules/@aws-sdk/client-cognito-identity/dist/cjs/package.json"],"hash":"ba2033eea86c29e0ed84fe117b0bd13e","name":"package","type":"json","fileHashes":["ba2033eea86c29e0ed84fe117b0bd13e"]},{"__packager_asset":true,"fileSystemLocation":"/Users/cipri/dev/pp/al/monorepo/packages/app/assets/icons","httpServerLocation":"/assets/assets/icons","width":69,"height":48,"scales":[1],"files":["/Users/cipri/dev/pp/al/monorepo/packages/app/assets/icons/hamburger.png"],"hash":"2b8792f86227baa29d75dacfaaf42da7","name":"hamburger","type":"png","fileHashes":["2b8792f86227baa29d75dacfaaf42da7"]},{"__packager_asset":true,"fileSystemLocation":"/Users/cipri/dev/pp/al/monorepo/packages/app/assets/icons","httpServerLocation":"/assets/assets/icons","width":45,"height":45,"scales":[1],"files":["/Users/cipri/dev/pp/al/monorepo/packages/app/assets/icons/close.png"],"hash":"f612fca8e1a2c3be8b3363539210ebb4","name":"close","type":"png","fileHashes":["f612fca8e1a2c3be8b3363539210ebb4"]},{"__packager_asset":true,"fileSystemLocation":"/Users/cipri/dev/pp/al/monorepo/packages/app/assets/icons","httpServerLocation":"/assets/assets/icons","width":51,"height":42,"scales":[1],"files":["/Users/cipri/dev/pp/al/monorepo/packages/app/assets/icons/soundOn.png"],"hash":"79e2da170bcf327af467f0b8beb59def","name":"soundOn","type":"png","fileHashes":["79e2da170bcf327af467f0b8beb59def"]},{"__packager_asset":true,"fileSystemLocation":"/Users/cipri/dev/pp/al/monorepo/packages/app/assets/icons","httpServerLocation":"/assets/assets/icons","width":51,"height":42,"scales":[1],"files":
```

The filter I'm using now might not work in all cases, but works for mine.. Not sure if you could ignore watched folders from metro config?

```
// createManifest.js line 61
assets.filter(function(asset) {
  return !asset.httpServerLocation.startsWith("/assets/..")
}).forEach(function(asset) {
```

**Comment by byCedric** [comment]
I think you can, but that might open another can of worms 😅 [Here is a small guide](https://stackoverflow.com/questions/41813211/how-to-make-react-native-packager-ignore-certain-directories) on that.

Maybe this issue has the same cause as [#8294](https://github.com/expo/expo/issues/8294), pinging @esamelson for this one.

**Comment by esamelson** [comment]
Hi there @cipriancaba! Thanks for the report -- we have added monorepo support as well as a configurable `ENTRY_FILE` Xcode build var (same as the React Native scripts use) in expo-updates 0.2.4, so please try updating to that version in order to fix those issues.

Regarding assets -- `assetBundlePatterns` is only used when running `expo publish`, not when creating a release build. However, it does seem like we might not be properly handling assets that have `../` in the httpServerLocation returned by metro. Glad you found a workaround for now, but we'll look into a better fix for this.

**Comment by esamelson** [comment]
Hello @cipriancaba -- we've just pushed out a new version (`expo-updates@0.2.7`) that I believe should fix the asset bundling issue you're experiencing, and remove the need for filtering. Please give it a try and let us know if it fixes things for you!

**Comment by cipriancaba** [comment]
Hi @esamelson I still have the same problem with expo-updates `0.2.8`

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not find the expected embedded asset package.json. Check that expo-updates is installed correctly.'
*** First throw call stack:
(0x1859b8300 0x1856ccc1c 0x1009b9074 0x185656ec4 0x18565833c 0x18565e85c 0x18565f290 0x185668928 0x1856bf714 0x1856c59c8)

**Comment by esamelson** [comment]
@cipriancaba - any chance you could provide a fully reproducible demo? Either step by step instructions or a repo would be really helpful in debugging this and getting a fix out more quickly.

**Comment by manJudal** [comment]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not find the expected embedded asset back-icon.png. Check that expo-updates is installed correctly.' expo sdk :45 , issue with reales as working fine with simulator , Xcode : 13.3.1 , i'm new at react , any help appreciated..

**Comment by lonewolf416** [comment]
> 

For now you can manually empty the array like this "bundledAssets":[] in your app.manifest file then make build

**Comment by filipelsimoes** [comment]
> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not find the expected embedded asset back-icon.png. Check that expo-updates is installed correctly.' expo sdk :45 , issue with reales as working fine with simulator , Xcode : 13.3.1 , i'm new at react , any help appreciated..

I have the same problem, did you find a solutionn?

**Comment by lonewolf416** [comment]
> I have the same problem, did you find a solutionn?

For now you can manually empty the array like this "bundledAssets":[] in your app.manifest file then make build

**Comment by filipelsimoes** [comment]
@lonewolf416 i already did that and didn't work 
Do you have any more suggestions?
