### ISSUE TITLE
Cannot create release build: 

### ISSUE THREAD

**Issue by hanselsen** [expo/expo#8429]
### Environment

```
Expo CLI 3.20.9 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.3.2 - C:\Users\hans\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
```

Target: Android Release, Windows

### Steps to Reproduce

I had some issues that I fixed by upgrading to `expo-updates@0.2.4`.
After this, my release build always get stuck at the gradle task `createReleaseExpoManifest`.

I used 
`npm run android -- --variant=release` 
and 
`gradlew installRelease`

### Expected Behavior

Create the APK after running a release build.

### Actual Behavior

It stops after this error.

```
> Task :app:createReleaseExpoManifest FAILED
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:375:7)
    at C:\projects\myapp\node_modules\expo-updates\scripts\createManifest.js:88:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

It seems that `createManifest.js:88` refers to the `destinationDir` provider by the gradle task.

**Comment by Vivekch05** [comment]
//same issue
> Task :app:createReleaseExpoManifest FAILED
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.join (path.js:375:7)
    at D:\Project\React-Native\News-App\node_modules\expo-updates\scripts\createManifest.js:75:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
'dev' is not recognized as an internal or external command,
operable program or batch file.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createReleaseExpoManifest'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 45s
408 actionable tasks: 2 executed, 406 up-to-date

//please help

**Comment by hanselsen** [comment]
I upgraded tot `expo-updates@latest` and `expo@latest` and it is now working.
`expo-updates` is now at `0.2.5`.
`expo` is now at `37.0.12`

**Comment by hanselsen** [comment]
@brentvatne maybe Expo could tell us if this is, in fact fixed in this version? I would hate for it to be just a lucky situation.

**Comment by brettdh** [comment]
@hanselsen I'm encountering the hang with those exact versions, so I'd guess it's not fixed? 😕

**Comment by brettdh** [comment]
Er, I seem to have misread... you wrote "stuck", which is what I see - the build just hangs there doing nothing at the `app:createReleaseExpoManifest` step, until I get impatient and Ctrl-C it - but your description above shows an actual error, which I haven't seen yet.

**Comment by brettdh** [comment]
aaaand of course it turns out I'm just too impatient, and the step succeeded after about 6 minutes; longer than I remembered from earlier builds, but oh well. Ignore me. 😑
