### ISSUE TITLE
[docs] generateHexStringAsync doesn't exist in expo-auth-session 1.2.1

### ISSUE THREAD

**Issue by daniel** [expo/expo#8900]
In the [guide for authentication with Google](https://docs.expo.io/guides/authentication/#google) 
– in the example code for Firebase – **generateHexStringAsync** is imported from expo-auth-session. This function doesn't exist in expo-auth-session 1.2.1, which is the version that is installed with `expo install expo-auth-session`.

**generateHexStringAsync** was added in master 10 days ago:
https://github.com/expo/expo/blame/81a7e830490b42038ad8716283837cfa9d5d75e6/packages/expo-auth-session/build/AuthSession.d.ts#L5

**Comment by daniel** [comment]
Another problem I have is that ResponseType.IdToken doesn't exist in that version.

**Comment by byCedric** [comment]
Hi @daniel, thanks for bringing this up. The `ResponseType.IdToken` was also added in PR #8719. Looks like the documentation was deployed too early, I'm sorry for that. Version `1.3.1` was pushed to NPM, but with the `next` tag. Could you try if this works for you? (cc @EvanBacon)

**Comment by daniel** [comment]
How do I do to try it? Expo complained when I tried to use version 1.3.1.

**Comment by HOllarves** [comment]
Having the same issue. Even if I hardcode a 16 character long hex string, I'm unable to handle the response correctly because `ResponseType.IdToken` doesn't exist. I'm getting a auth code instead of an id_token following [this tutorial](https://docs.expo.io/guides/authentication/#google) (firebase tab)

I even tried hardcoding response type as `'id_token'` but I'm getting a google error:

<img width="467" alt="Screenshot 2020-06-23 at 16 34 50" src="https://user-images.githubusercontent.com/10587409/85417078-84aaba00-b56f-11ea-91ce-8d49fcb7a04c.png">

How should we proceed to use the `next` version of expo?

**Comment by EvanBacon** [comment]
This is fixed in the latest published version of auth session. You can use the latest version of `expo-auth-session` (1.4.1) with sdk 37.

**Comment by daniel** [comment]
After upgrading to Expo SDK 37.0.0 and expo-auth-session 1.4.1 I get this error:

```
Some of your project's dependencies are not compatible with currently installed expo package version:
 - expo-auth-session - expected version range: ~1.2.1 - actual version installed: ~1.4.1
Your project may not work correctly until you install the correct versions of the packages.
```

I tried to use it anyway but when authorizing Expo to use expo.io to sign in I got this error:

```
Parameter not allowed for this message type:
code_challenge_method
```

**Comment by HOllarves** [comment]
I think I’m not getting the first error because I ran `expo update` in the root of the project.

I’m still getting the same error, just as @daniel

**Comment by davitykale** [comment]
Also getting the error `code_challenge_method`.

On Expo 38 with `expo-auth-session` v1.4.1.

**Comment by HOllarves** [comment]
I'm still having this issue. Any updates about this?
