### ISSUE TITLE
[expo-gl-cpp] crashes due to EXJSValueToNumberFast() being broken on iOS 14

### ISSUE THREAD

**Issue by danmaas** [expo/expo#8971]
I just tried my (ejected, expo-gl-using) app in the iOS 14.0 beta and saw some very bizarre crashes.

After some digging, I discovered the root cause is that a utility function deep inside `expo-gl-cpp`, `EXJSValueToNumberFast()`, is broken on iOS 14. Specifically, the "fast path" guarded by `#ifdef __LP64__` produces incorrect results on integer-tagged JSValueRefs.

**Details**:

The symptom is that expo-gl throws an exception during initial context setup because `gl.getParameter(gl.VERSION)` returns a _number_ (178305504 and -2107330064 in cases I observed) rather than a string as expected.

Early in expo-gl setup, `GLView.js` calls `gl.getParameter(gl.VERSION)`, passing the constant 0x1f02 (GL_VERSION) to expo-gl-cpp's native `getParameter()` method. The first thing `getParameter()` does is `EXJS_UNPACK_ARGV(GLenum pname)` which attempts to transform a JSValueRef into that native GLenum. This macro boils down to calling `EXJSValueToNumberFast()` on the JSValueRef.

Using the Xcode debugger, I observed that the JSValueRef passed to `getParameter()` is `0xfffe000000001f02`. This is clearly a tagged integer, where the lower 2 bytes `0x1f02` correspond to the GL_VERSION constant. `EXJSValueToNumberFast()` expects small integers to look like `0xffff ....` where the first two bytes are `0xffff`. But apparently iOS 14's JavaScriptCore uses some different encoding where `0xfffe` can be a prefix of a small integer. Anyway, `EXJSValueToNumberFast()` returns the wrong result, so `getParameter()` mis-interprets GL_VERSION as an unknown constant, and returns the _address_ of the returned string to JavaScript as a number, leading to that bizarre exception.

Removing the `#ifdef __LP64__` fast path from `EXJSValueToNumberFast()`and falling back to `JSValueToNumber()` stops the crashes. (of course this sacrifices performance, and it would be ideal to fix the fast path - I looked for but could not find any documentation about changes to the tagged number format).

**Comment by wkozyra95** [comment]
Hi, thanks for the detailed description

yes you are right it seems that webkit changed tags that represent integers https://github.com/WebKit/webkit/commit/e522feb5a8bfe5ba78fd1749df342f56dc98fcb5
The same problem will be on Android when react-native will upgrade their versions

Potentials fixes are to disable fast conversion (slower) or allow both tags to be used (potentially risky). I assume that we could detect JSC version in runtime, but we plan to switch to JSI implementation(to support Hermes), so I don't want commit to much time to fix the old version.

Unfortunately, JSI API for numbers always treats them as `doubles`, so this performance hit (if there is any) is inevitable, but based on limited testing I have done on a new implementation it's not noticeable. It's possible that lower performance for numbers is balanced by improvements for other APIs.

**Comment by ide** [comment]
Fantastic diagnosis. Just wanted to say thank you for writing an issue with such good substance. We’ll take a look at fixing this in time for the iOS 14 GM release.

**Comment by danmaas** [comment]
Thanks y'all! btw, if you need any help testing expo-gl with Hermes, I'm very much looking forward to trying that out when it's ready.

**Comment by tsapeta** [comment]
I've just published `expo-gl@8.4.0` that includes a fix from #9226 🙂 For managed workflow it'll be available in SDK39 but we're going to push this fix to our builders for SDK38 soon.
Again, thanks for the good quality report!

**Comment by wkozyra95** [comment]
The fix was backported to sdk38 and deployed to production.

**Comment by Joshandrews43** [comment]
I am still getting this error on the IOS 14 beta on the IPhone 8.

Any solutions?
```
    "expo": "^38.0.10",
    "expo-gl": "8.4.0",
    "expo-gl-cpp": "8.4.0",
```

**Comment by ide** [comment]
Unless you're using the Obj-C in a bare app you will still have the bug (it's not clear from your package.json snippet). Other than that, we believe this issue has been fixed when compiling from source.

**Comment by wkozyra95** [comment]
@Joshandrews43 This issue should work in standalone builds for sdk38, but not in the client. The client version will be updated together with sdk39 release.

**Comment by Joshandrews43** [comment]
This does not work in my standalone build of IOS 14. 

Sentry logs:

```

Name | iOS
-- | --
Version | 14.0


Model | iPhone 8
-- | --
Simulator | False

exception
TypeError: glesVersion.split is not a function. (In 'glesVersion.split(/[^\d.]+/g)', 'glesVersion.split' is undefined)
```

That is from my production app.

**Comment by wkozyra95** [comment]
When did you build that app?
