### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir '/Users/USER_NAME/PROJECT_NAME/src/assets/images'

### ISSUE THREAD

**Issue by pavermakov** [expo/expo#9000]
### Summary of Issue (just a few sentences)
I have started a brand new project with expo. After selecting the blank (TypeScript) template and installing all dependencies, I have launched the project with `yarn ios`. On my simulator, an expo client opened up and attempted to load the new app, however, it had no luck. I was presented with an error message "There was a problem loading the requested app". In my terminal, I got the message specified in the title of this issue. I've made no changes to the code at all.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.1 => 38.0.4
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.13

**Comment by proteche** [comment]
can you @pavermakov  downgrade to your expo-cli to 3.21.5

**Comment by 2manoj1** [comment]
Same issue with new expo-cli project. blank project. Any solution?

**Comment by JaapWeijland** [comment]
I have the same issue with a brand new project. I altered nothing after the bootstrapping process; I only ran `npm run ios`.

**Comment by awesomeAB** [comment]
@pavermakov I guess this happens because expo tries to validate your asset checksums from `.expo-shared/assets,json` file.
Deleting this `assets.json` file from your `.expo-shared` should fix this issue.

**Comment by jim-at-jibba** [comment]
I have the same issue and removing `assets.json` does not fix my issue

**Comment by Hongshen-Yang** [comment]
have the same issue

**Comment by jpfcruz** [comment]
@byCedric I'm having the same issue and can reproduce it. Should I open a new issue?

**Comment by jpfcruz** [comment]
I'm having the same issue and can reproduce it. Should I create an issue here or for the CLI?

**Comment by sdinesmvc** [comment]
I'm having the same issue and reproduce it.

**Comment by FleetAdmiralJakob** [comment]
Same issue, any updates? Any fixes?
