### ISSUE TITLE
Invariant Violation: "main" has not been registered.

### ISSUE THREAD

**Issue by TylerKnvpp** [expo/expo#9042]
Just updated expo-cli and initialized a new project with the TypeScript Tabs template. I did not touch the code. Navigated to the project's directory and ran `yarn start` and was met with this error: 

Invariant Violation: "main" has not been registered. This can happen if: 

* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and 'AppRegistry.registerComponent' wasn't called.

-----

Tried to resolve by using registerRootComponent, but that is not working either.

**Comment by wscotten** [comment]
Upgrading to 38.0.7 seemed to fix it for me.

**Comment by cruzach** [comment]
Hey @TylerKnvpp this should be fixed in `expo` v38.0.7. Could you try upgrading and lmk if that resolves the error?

**Comment by brentvatne** [comment]
hi there! this was caused by having multiple versions of react-native-safe-area-context installed in the app. react-native doesn't handle multiple versions of a native dependency very well. as @cruzach mentioned, this should resolve itself if you update to the latest version of the expo pkg.

**Comment by cenksari** [comment]
I upgraded my projects to sdk 38.0.8. I get the same issue.

**Comment by harbi** [comment]
Having the same issue (SDK 38.0.8).

**Comment by brentvatne** [comment]
run `yarn why react-native-safe-area-context` to see if you have multiple versions of the package. i'm not sure what the equivalent is for npm - i think there isn't one - but you can look in your package-lock.json if you use that.

what you want to do here is verify that there is just a single instance of react-native-safe-area-context in your project. if there is a different version used by the `expo` package than you are using in your package.json, then change the version in your package.json to match the one from the expo package.

**Comment by mhrastnik** [comment]
I'm facing the same issue. Been trying to fix it with no success for 3 days now.

**Comment by jeffcheungkyand** [comment]
i had the same problem before. how i fixed it was trying to remove any package that have shared dependencies.
in my case react-native-gradient-buttons is using expo-linear-gradient, and i happen to install expo-linear-gradient separately afterwards

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.6.1",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",
    "expo": "~38.0.8",
    "expo-linear-gradient": "~8.0.0",
    "expo-status-bar": "^1.0.2",
    "expo-updates": "~0.2.8",
    "lodash": "^4.17.15",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz",
    "react-native-elements": "^2.0.4",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-gradient-buttons": "^2.0.1",
    "react-native-maps": "^0.27.1",
    "react-native-paper": "^3.10.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "~2.9.0",
    "react-native-unimodules": "^0.10.1",
    "react-native-web": "~0.11.7",
    "react-navigation-tabs": "^2.9.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true
}


to 


{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.6.1",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",
    "expo": "~38.0.8",
    "expo-status-bar": "^1.0.2",
    "expo-updates": "~0.2.8",
    "lodash": "^4.17.15",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz",
    "react-native-elements": "^2.0.4",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-gradient-buttons": "^2.0.1",
    "react-native-maps": "^0.27.1",
    "react-native-paper": "^3.10.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "~2.9.0",
    "react-native-unimodules": "^0.10.1",
    "react-native-web": "~0.11.7",
    "react-navigation-tabs": "^2.9.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true
}

**Comment by okeybond** [comment]
having same issue after my upgrade from 37 to 38.0.8

**Comment by duganchen** [comment]
I'm dealing this. I've isolated a react-apollo "export default compose" statement in an imported module that causes it to happen. Obviously, it's crashing so hard (when the module is being being imported) that it takes down the error handling mechanism, resulting in this error message.

Prior to the upgrade (from 37), the project was using react-apollo 2.5.8, which is listed as the stable version on GitHub. I've found that if I simply run "expo upgrade", then it leaves that version of react-apollo alone. If I remove it before or after the "expo upgrade", and then "expo install react-apollo", it installs the latest alpha, which crashes like this.

**Comment by brentvatne** [comment]
@duganchen - `expo upgrade` does not touch any of the dependencies that it knows nothing about it, and so we leave react-apollo as-is. it sounds like there is some bug with react-apollo latest and react-native@0.62/expo@sdk-38

**Comment by YuraChernii** [comment]
@brentvatne. I find such project - https://github.com/devSchacht/react-native-app/tree/l2
yesterday i could bulding this project without any problems but today i can not

**Comment by YuraChernii** [comment]
please hellppppp!!!

**Comment by cruzach** [comment]
@YuraChernii I would refrain from adding any comments that aren't providing additional information, it can result in these threads getting really long, really fast. 

We're looking into a way to better show the error that really matters here- `Invariant Violation: "main" has not been registered.` is most likely the result of another error that is showing up after upgrading your app (with a dependency you're using). 

For now, one way I have found to get the underlying error message is to run your app (I used a standalone apk, but you might be able to do this in the Expo client app, as well) is to run `adb logcat` and reproduce the error, then look through the device logs for the `"main" has not been registered` message, and check if there's an error message directly preceding it. If you need more info on how to get the native device logs, see [here](https://docs.expo.io/workflow/logging/#view-logs-from-android-device-or-emulator)

**Comment by duganchen** [comment]
I just reproduced the crash in the iOS simulator and checked the system logs. Neither "main" nor "registered" appear anywhere.

**Comment by YuraChernii** [comment]
![image](https://user-images.githubusercontent.com/67958005/86801052-4edff800-c07c-11ea-8517-45b187ed5cd0.png)
![image](https://user-images.githubusercontent.com/67958005/86801117-5d2e1400-c07c-11ea-9d15-48ab6b058855.png)
PROJECT - https://github.com/devSchacht/react-native-app/tree/l2

**Comment by cenksari** [comment]
I find a solution.

1 ) Create a fresh new project with `expo init project-name` command. This comes `expo@8.0.8` SDK version.
2 ) Select workflow (I choose "managed workflow")
3) Install all dependencies with `expo install` command. Example: `expo install @react-native-community/async-storage`
4) Go to main project and delete "**node_modules**" folder, "**package.json**", "**yarn.lock**" and "**package-lock.json**" files
5) Copy new project's "**package.json**", "**yarn.lock**" or "**package-lock.json**" files to old project
6) Run `npm install` or `yarn install` command on main project. Wait for installation
7) Run `expo start -c` command.

Tadaa. Your project successfully runs on **expo@38.0.8** SDK. You can delete your new project safely.

**Comment by YuraChernii** [comment]
i did it step by step but
![image](https://user-images.githubusercontent.com/67958005/86811075-31b02700-c086-11ea-981f-5023c8e6db5a.png)

then

![image](https://user-images.githubusercontent.com/67958005/86811180-4a204180-c086-11ea-97e8-f6e5460899ec.png)
![image](https://user-images.githubusercontent.com/67958005/86811249-5d331180-c086-11ea-9fed-e1d4b7d4cb53.png)

**Comment by duganchen** [comment]
The problem went away after I switched from Node 12 to Node 14.

**Comment by Jasmine-Bascom** [comment]
@cenksari I'm still getting the same issue after trying those steps as well.

**Comment by TylerKnvpp** [comment]
I updated the expo-cli and the issue has been resolved.

**Comment by Jasmine-Bascom** [comment]
@TylerKnvpp on updating expo-cli I still have the same issue.

**Comment by brentvatne** [comment]
- upgrade to expo@38.0.8 in your package.json
- remove your yarn.lock or package-lock.json
- remove node_modules
- run `yarn` or `npm install`
- start the app again
