### ISSUE TITLE
Could not find google-services.json 

### ISSUE THREAD

**Issue by Mersall** [expo/expo#9220]
hello, 
I'm tried to get expo push-notification work but in standalone app -android it's not work because should google-services file be placed in right place, discovered when building stand-alone this got this error every time in the log ==>  "Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use register generatedResFolders(FileCollection)
"

, I tried everything to get it done but it's still given me this error, and cant set (FCM) as documentation, igot this massage in send notification in production   ==>> "DeviceNotRegistered: The recipient device is not registered with FCM."

1- I tried publishing first 
2- tried to build new expo project and add the google-services file but got this error also 
3- tried to attach fcm API key by expo manager, 
all things failed and still have this problem 
so plz plz help the notification in my app not working and the app on play store right now 

My app.json file looks like this in expo.android as documentation said 

	"android": {
			"googleServicesFile": "./google-services.json"
		},

**Comment by brentvatne** [comment]
hello! did you add the google-services file like this? https://docs.expo.io/push-notifications/using-fcm/#client-setup

can you give me the link to your project on expo.io? eg: https://expo.io/@notbrent/hour-power

**Comment by Mersall** [comment]
> hello! did you add the google-services file like this? https://docs.expo.io/push-notifications/using-fcm/#client-setup
> 
> can you give me the link to your project on expo.io? eg: https://expo.io/@notbrent/hour-power

yes I did everything in documentation also in set FCM DOCUMENTATION

**Comment by Mersall** [comment]
> hello! did you add the google-services file like this? https://docs.expo.io/push-notifications/using-fcm/#client-setup
> 
> can you give me the link to your project on expo.io? eg: https://expo.io/@notbrent/hour-power

https://expo.io/@mersall44/cfm-sae  here is the link, thank you

**Comment by brentvatne** [comment]
from the logs on a build a couple of hours ago:

> You have provided values for both `googleServicesFile` and `googleSignIn` in your `app.json`. Since SDK37 `googleServicesFile` overrides any other `google-services.json`-related configuration. Recommended way to fix this warning is to remove `googleSignIn` configuration from your `app.json` in favor of using only `googleServicesFile` to configure Google services.

it looks like in your most recent build this issue is resolved. so that will probably fix the issue for you.

**Comment by Mersall** [comment]
> from the logs on a build a couple of hours ago:
> 
> > You have provided values for both `googleServicesFile` and `googleSignIn` in your `app.json`. Since SDK37 `googleServicesFile` overrides any other `google-services.json`-related configuration. Recommended way to fix this warning is to remove `googleSignIn` configuration from your `app.json` in favor of using only `googleServicesFile` to configure Google services.
> 
> it looks like in your most recent build this issue is resolved. so that will probably fix the issue for you.

i really appreciate your effort, Thank you, but go to add  googleSignIn manually trying to solve this problem, but actually, when removed it the problem still there with it or without it, this issue takes 3 days tried everything on the internet

**Comment by Mersall** [comment]
@brentvatne  plz any update, I'm still stuck with this !

**Comment by brentvatne** [comment]
sorry i don't have an answer for you. i can let you know that there is not any issue with this on our end, push notifications via fcm are working as expected.

it's possible that your project on google isn't configured properly.

i would try creating a new, mostly empty project and following the instructions carefully from the start and getting that working, then comparing that with your existing project.

**Comment by Mersall** [comment]
> sorry i don't have an answer for you. i can let you know that there is not any issue with this on our end, push notifications via fcm are working as expected.
> 
> it's possible that your project on google isn't configured properly.
> 
> i would try creating a new, mostly empty project and following the instructions carefully from the start and getting that working, then comparing that with your existing project.

sorry for Lately replay, but already checked this solution, making a new empty project but it's the same issue, what about this error
Could not find google-services.json 
how I can make expo find my google service file !!?

**Comment by giovaniif** [comment]
I'm going trough the same error. Any updates about that?

**Comment by SleeplessByte** [comment]
There are no updates because this is not an _expo_ issue. However, over the pas 2 months, we've set up FCM for 12 projects, and have failed a few times.

In order to set-up FCM, we follow these steps

1. created a project on http://cloud.google.com/
2. link a billing account
3. enable whichever apis we need (e.g. maps)
4. create a new project on https://firebase.google.com/
5. select the cloud.google.com project
6. add a new android application
7. enter the *correct* package name, leave SHA empty
8. download `google-services.json` and place in root of project
9. go to server tab and copy key (`<token>`)
10. add the configuration to `app.json`
11. make sure you have the _same_ package name in `app.json`
12. make at least one android build 
13. `expo fetch:android:hashes`; take the shas, put them in the field in step 7.
14. `expo push:android:upload --api-key <token>` but use the `<token>` from step 9.

Now everything works. **Note** that on step 12, it should not fail. If done everything correctly, it will build just fine.

After this we continue by adding iOS, Web app, restrict the keys in google cloud console, upload a bundle to Play Store and copy the signing key shas to step 7 as well.

Common issues we have encountered:

- incorrect package name will act as if `google-services.json` isn't there
- didn't place `google-service.json` in the root
- didn't add `package name` to `app.json` 
- didn't add google services file path to `app.json`
- used incorrect format inside `app.json` (because iOS and Android are **note** the same configuration key)

**Comment by Mersall** [comment]
> There are no updates because this is not an _expo_ issue. However, over the pas 2 months, we've set up FCM for 12 projects, and have failed a few times.
> 
> In order to set-up FCM, we follow these steps
> 
> 1. created a project on http://cloud.google.com/
> 2. link a billing account
> 3. enable whichever apis we need (e.g. maps)
> 4. create a new project on https://firebase.google.com/
> 5. select the cloud.google.com project
> 6. add a new android application
> 7. enter the _correct_ package name, leave SHA empty
> 8. download `google-services.json` and place in root of project
> 9. go to server tab and copy key (`<token>`)
> 10. add the configuration to `app.json`
> 11. make sure you have the _same_ package name in `app.json`
> 12. make at least one android build
> 13. `expo fetch:android:hashes`; take the shas, put them in the field in step 7.
> 14. `expo push:android:upload --api-key <token>` but use the `<token>` from step 9.
> 
> Now everything works. **Note** that on step 12, it should not fail. If done everything correctly, it will build just fine.
> 
> After this we continue by adding iOS, Web app, restrict the keys in google cloud console, upload a bundle to Play Store and copy the signing key shas to step 7 as well.
> 
> Common issues we have encountered:
> 
> * incorrect package name will act as if `google-services.json` isn't there
> * didn't place `google-service.json` in the root
> * didn't add `package name` to `app.json`
> * didn't add google services file path to `app.json`
> * used incorrect format inside `app.json` (because iOS and Android are **note** the same configuration key)

I'm really appreciate your offer thank you , I'm sure I do that exactly as you said  clearly also, I'm sorry to say that but it's still stuck

**Comment by SleeplessByte** [comment]
I just did this with a fresh project and it works. My guess is still one of the common issues.

**Comment by Mersall** [comment]
> I just did this with a fresh project and it works. My guess is still one of the common issues.
> 
> Did step 12 fail?

yes I'm sorry to say that , may if you have time send me your contact :)

**Comment by Mersall** [comment]
any update for this case !!!?

**Comment by SleeplessByte** [comment]
I don't have enough information to help you along. I can't reproduce your issue, so I think you're not taking a step correctly. Double check the format of `app.json`, tripple check all the steps. Create a minimal reproducible example.

Often, right above the error message `Could not find google-services.json`, there is an additional error. See if you can find that.

**Comment by kodaraj** [comment]
I got this error as well but there were few more errors after that in the log and one of them was using .jpg instead of .png for the splash image, fixing which created build successfully.

**Comment by zenkyuv** [comment]
i've git ignored google-services.json and GoogleService-Info.plist 🙈 and thats why i was getting this error ..

**Comment by simon-tannai** [comment]
Hello 👋 

I have the same issue and I did not found the how to fix it. I had checked thousands times each step of the tutorial but I always got the same error:
```shell
[stderr] Execution failed for task ':app:processReleaseGoogleServices'.
[stderr] > File google-services.json is missing. The Google Services Plugin cannot function without it. 
[stderr]    Searched Location: 
[stderr]   /home/expo/workingdir/build/android/app/src/release/google-services.json
[stderr]   /home/expo/workingdir/build/android/app/src/google-services.json
[stderr]   /home/expo/workingdir/build/android/app/src/Release/google-services.json
[stderr]   /home/expo/workingdir/build/android/app/google-services.json
```

The _google-services.json_ file is present at the root of the projet, into `android` directory and `android/app` directory:
<img width="233" alt="Capture d’écran 2022-09-09 à 16 08 07" src="https://user-images.githubusercontent.com/15647712/189369360-d54a7a96-f3ab-4205-8266-e0c9a2a7e27f.png">

In the very top the my _app/build.gradle_ file:
```gradle
apply plugin: "com.android.application"
apply plugin: "com.google.gms.google-services"
```

In the _android/build.gradle_ file:
```gradle
buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.1.0")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        classpath 'com.google.gms:google-services:4.3.13'
    }
}
```

In the _app.config.js_ file:
```javascript
  android: {
    package: 'com.socialkitchen.app',
    googleServicesFile: './google-services.json',
  },
``` 

The package name is the same in _google-services.json_:
```JSON
"android_client_info": {
    "package_name": "com.socialkitchen.app"
}
```

Any solution to fix it ?

**Comment by limeran** [comment]
> Hello 👋
> 
> I have the same issue and I did not found how to fix it. I had checked thousands times each step of the tutorial but I always got the same error:
> 
> ```shell
> [stderr] Execution failed for task ':app:processReleaseGoogleServices'.
> [stderr] > File google-services.json is missing. The Google Services Plugin cannot function without it. 
> [stderr]    Searched Location: 
> [stderr]   /home/expo/workingdir/build/android/app/src/release/google-services.json
> [stderr]   /home/expo/workingdir/build/android/app/src/google-services.json
> [stderr]   /home/expo/workingdir/build/android/app/src/Release/google-services.json
> [stderr]   /home/expo/workingdir/build/android/app/google-services.json
> ```
> 
> The _google-services.json_ file is present at the root of the projet, into `android` directory and `android/app` directory: <img alt="Capture d’écran 2022-09-09 à 16 08 07" width="233" src="https://user-images.githubusercontent.com/15647712/189369360-d54a7a96-f3ab-4205-8266-e0c9a2a7e27f.png">
> 
> In the very top the my _app/build.gradle_ file:
> 
> ```groovy-gradle
> apply plugin: "com.android.application"
> apply plugin: "com.google.gms.google-services"
> ```
> 
> In the _android/build.gradle_ file:
> 
> ```groovy-gradle
> buildscript {
>     ext {
>         buildToolsVersion = "29.0.3"
>         minSdkVersion = 21
>         compileSdkVersion = 31
>         targetSdkVersion = 31
>     }
>     repositories {
>         google()
>         mavenCentral()
>         jcenter()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle:4.1.0")
> 
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
> 
>         classpath 'com.google.gms:google-services:4.3.13'
>     }
> }
> ```
> 
> In the _app.config.js_ file:
> 
> ```js
>   android: {
>     package: 'com.socialkitchen.app',
>     googleServicesFile: './google-services.json',
>   },
> ```
> 
> The package name is the same in _google-services.json_:
> 
> ```json
> "android_client_info": {
>     "package_name": "com.socialkitchen.app"
> }
> ```
> 
> Any solution to fix it ?

I have same issue, did you manage to resolve it?

**Comment by serkan-bayram** [comment]
> > Hello 👋
> > I have the same issue and I did not found how to fix it. I had checked thousands times each step of the tutorial but I always got the same error:
> > ```shell
> > [stderr] Execution failed for task ':app:processReleaseGoogleServices'.
> > [stderr] > File google-services.json is missing. The Google Services Plugin cannot function without it. 
> > [stderr]    Searched Location: 
> > [stderr]   /home/expo/workingdir/build/android/app/src/release/google-services.json
> > [stderr]   /home/expo/workingdir/build/android/app/src/google-services.json
> > [stderr]   /home/expo/workingdir/build/android/app/src/Release/google-services.json
> > [stderr]   /home/expo/workingdir/build/android/app/google-services.json
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The _google-services.json_ file is present at the root of the projet, into `android` directory and `android/app` directory: <img alt="Capture d’écran 2022-09-09 à 16 08 07" width="233" src="https://user-images.githubusercontent.com/15647712/189369360-d54a7a96-f3ab-4205-8266-e0c9a2a7e27f.png">
> > In the very top the my _app/build.gradle_ file:
> > ```
> > apply plugin: "com.android.application"
> > apply plugin: "com.google.gms.google-services"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the _android/build.gradle_ file:
> > ```
> > buildscript {
> >     ext {
> >         buildToolsVersion = "29.0.3"
> >         minSdkVersion = 21
> >         compileSdkVersion = 31
> >         targetSdkVersion = 31
> >     }
> >     repositories {
> >         google()
> >         mavenCentral()
> >         jcenter()
> >     }
> >     dependencies {
> >         classpath("com.android.tools.build:gradle:4.1.0")
> > 
> >         // NOTE: Do not place your application dependencies here; they belong
> >         // in the individual module build.gradle files
> > 
> >         classpath 'com.google.gms:google-services:4.3.13'
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the _app.config.js_ file:
> > ```js
> >   android: {
> >     package: 'com.socialkitchen.app',
> >     googleServicesFile: './google-services.json',
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The package name is the same in _google-services.json_:
> > ```json
> > "android_client_info": {
> >     "package_name": "com.socialkitchen.app"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any solution to fix it ?
> 
> I have same issue, did you manage to resolve it?

make sure google-services.json is not in .gitignore

**Comment by johnjjung** [comment]
I discovered that if you have `google-services.json` in .gitignore, during the prebuild it'll hide it from `./google-services.json`

So if you just do a global gitignore and remove it from the file .gitignore it'll work

**Comment by viAtom** [comment]
> I discovered that if you have `google-services.json` in .gitignore, during the prebuild it'll hide it from `./google-services.json`
> 
> So if you just do a global gitignore and remove it from the file .gitignore it'll work

That's exactly it, spent more than 3 hours going around to find out if you put it in .gitignore it's over, thanks for your feedback, really appreciate it.

**Comment by arnabdotpy** [comment]
> I discovered that if you have `google-services.json` in .gitignore, during the prebuild it'll hide it from `./google-services.json`
> 
> So if you just do a global gitignore and remove it from the file .gitignore it'll work

Thanks a lot, I spent around 4 hours figuring this out.

**Comment by SleeplessByte** [comment]
You can provide it as an [EAS environment "file"](https://docs.expo.dev/build-reference/variables/#how-to-upload-a-secret-file-and-use-it-in-my-app-config). However, there are no secrets inside `google-services.json`. The contents will be included inside the built APK/AAB, so there is *no reason to keep it out of GitHub*.
