### ISSUE TITLE
[Unhandled promise rejection: Error: Location provider is unavailable. Make sure that location services are enabled.]

### ISSUE THREAD

**Issue by fromsujay** [expo/expo#9377]
I have just upgraded my app from Expo SDK 37.0.0 to 38.0.0. The app works fine on iOS but on Android I get the following warning and the app doesn't geolocate me on the map. On Expo SDK 37 this feature was working perfectly fine.

Expected result : The app should geolocate me (the user) based on my position. 
Actual result : The app doesn't geolocate me (the user) based on my position. The problem is specific to Android. On iOS this feature works fine. Warning :

> [Unhandled promise rejection: Error: Location provider is unavailable. Make sure that location services are enabled.]

Development environment :
- Expo SDK 38.0.0
- React Native 0.62
- Maps provider : Google Maps on Android
- react-native-maps: 0.27.1
- React: 16.11.0
- Device : Honor 8X/Android 10

What have I tried so far ?

- Ran expo upgrade once more to ensure that all of my packages were set to the correct version.
- Deleted package-lock.json and node_modules and ran npm install.
- Set Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.High })
- Set Location.getCurrentPositionAsync({ enableHighAccuracy: true })
- Set Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Lowest })
- Set Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Low })
- Set Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced })
- An upgrade to Expo SDK 39.0.0 shows no improvement. The error is the same.

```
import * as Location from 'expo-location';
import * as Permissions from 'expo-permissions';

async _getLocationAsync() {
  let { status } = await Permissions.askAsync(Permissions.LOCATION);
  if (status !== 'granted') {
    /* If user hasn't granted permission to geolocate himself herself */
    Alert.alert(
      "User location not detected",
      "You haven't granted permission to detect your location.",
      [{ text: 'OK', onPress: () => console.log('OK Pressed') }]
    );
  }

  let location = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.High });
  this.setState({
    userLat: location.coords.latitude,
    userLng: location.coords.longitude,
    navGeoStatus: true,
    lat: location.coords.latitude,
    lng: location.coords.longitude
  });
}
```

**Comment by AdamJNavarro** [comment]
Hey @fromsujay, Is this issue occurring on a physical Android device or are you running on an emulator?

Cheers,
Adam

**Comment by fromsujay** [comment]
Hello @AdamJNavarro,
Thanks for your reply. This issue is occurring on a physical Android device Honor 8X running on Android 10.

**Comment by GrzegorzBrdej** [comment]
Hi, @AdamJNavarro I have the same issue on emulator Pixel 2 XL API 30 and few others

**Comment by Rooib** [comment]
Any updates on this? I experience this issue as well in sdk 39 @AdamJNavarro

**Comment by fromsujay** [comment]
Hi @AdamJNavarro ,
I am loosing users because of this problem. This is an entrepreneurial project at the beginning of it's journey. More users using Huawei P20 and Samsung S8 have reported having the same problem in production.

**Comment by PrBF** [comment]
Same problem here... No solution found yet?

**Comment by dpdunn10** [comment]
I'm also experiencing this issue in SDK 39. Hopefully this is resolved soon as location services are the foundation of my app.

**Comment by luizverissimo** [comment]
I'm also get this issue in SDK 39 on LG X Style phone.

**Comment by dpdunn10** [comment]
I was able to get around this issue by replacing
`const { status } = await Permissions.askAsync(Permissions.LOCATION);`
with
`const { status } = await Location.requestPermissionsAsync();`
Hopefully this works for everyone else.

**Comment by fromsujay** [comment]
> I was able to get around this issue by replacing
> `const { status } = await Permissions.askAsync(Permissions.LOCATION);`
> with
> `const { status } = await Location.requestPermissionsAsync();`
> Hopefully this works for everyone else.

`const { status } = await Permissions.askAsync(Permissions.LOCATION);`
and
`const { status } = await Location.requestPermissionsAsync();`

are both working. The problem is that 
`let location = await Location.getCurrentPositionAsync({});` 
is not returning a promise resolving to an object of type LocationObject. I have tried passing in options as well as 
`let location = await Location.getLastKnownPositionAsync();` 
without any success. Nevertheless, thanks for sharing your solution. It might help someone. But my problem is still intact.

**Comment by skulegirl** [comment]
This issue is cropping up for me too, both with SDK 39 and the Beta release of SDK 40. I have only tested on Android emulators so far, but will have a tester with a physical device try against SDK 39 and report back. 

On the emulator, all permissions are granted, and calls to hasServicesEnabledAsync and requestPermissionsAsync are both done and return true/granted before the calls to getLastKnownPositionAsync and getCurrentPositionAsync are made. getLastKnownPositionAsync always returns null, and getCurrentPositionAsync always throws the "Location provider unavailable" exception.

**Comment by JosephLep** [comment]
Also getting this issue on released SDK 40.  During the beta I was able to solve this issue - but the same codebase outside of beta does not work.

**Comment by skulegirl** [comment]
I did manage to get someone to test on SDK 39 on a physical device and the issue seems to not exist there at least...

**Comment by fromsujay** [comment]
The issue is still intact at least on the following mobile phones Honor 8x (Android 10), Samsung S8 (Android 9) and Huawei P20 and cruelly needs a more persistent solution.

I have implemented a shabby solution but it's only temporary. This workaround produces unpredictable behaviour on the mentioned devices and is certainly not a good UX for my app. I have been consistently loosing users due to this issue. Here is the temporary solution. It may help someone in my situation :

```
async _getLocationAsync() {
  try {
    let { status } = await Permissions.askAsync(Permissions.LOCATION);
    if (status !== 'granted') {
      // if user hasnt granted permission to geolocate himself herself
      Alert.alert(
        "User location not detected",
        "You haven't granted permission to detect your location.",
        [{ text: 'OK', onPress: () => console.log('OK Pressed') }]
      );
    }
    try {
      let isLocationServicesEnabled = await Location.hasServicesEnabledAsync();
      let location = await Location.getCurrentPositionAsync();
      this.setState({
        userLat: location.coords.latitude,
        userLng: location.coords.longitude,
        navGeoStatus: true,
        lat: location.coords.latitude,
        lng: location.coords.longitude
      });
    } catch (error) {
      console.log('getCurrentPositionAsync error',error);
      let location = await Location.getLastKnownPositionAsync();
      if (location == null) {
        Alert.alert(
          "Geolocation failed",
          "Your position could not be detected",
          [{ text: "OK", onPress: () => console.log("OK Pressed") }]
        );
      } else {
        this.setState({
          userLat: location.coords.latitude,
          userLng: location.coords.longitude,
          navGeoStatus: true,
          lat: location.coords.latitude,
          lng: location.coords.longitude
        });
      }
    }
  } catch (error) {
    console.log('askAsync error',error);
  }
}
```  

Because of the issue in question `Location.getCurrentPositionAsync()` does not resolve into an object of type location. But `Location.hasServicesEnabledAsync();` somehow nudges the device and `Location.getLastKnownPositionAsync();` resolves into an object of type Location which I use to locate the user. But this approach has several problems :
1. The last known position may not be up to date.
2. The `Location.getLastKnownPositionAsync();` may return null in some cases.
3. Unpredictable behavior on the above mentioned devices.

Has anyone found a better solution ?

**Comment by brentvatne** [comment]
if you are having this issue in an Android emulator, make sure that you have set a location in the emulator!

here's an example of me doing this - notice the window on the right:

<img width="1246" alt="Screen Shot 2020-12-28 at 8 22 09 PM" src="https://user-images.githubusercontent.com/90494/103258582-7a1c1380-494a-11eb-97a2-20096c20b599.png">

also see these docs: https://docs.expo.io/versions/v40.0.0/sdk/location/#enabling-emulator-location

**Comment by fromsujay** [comment]
@brentvatne I have been testing my app on a physical device throughout and not on an emulator. As I said earlier I am still struggling with getting geolocation to work in my app. I am surprised you closed this issue.
This situation is still as I have described above. Geolocation is still not operational. In the project I shared with you, geolocation is dysfunctional.

**Comment by fromsujay** [comment]
@brentvatne Thanks for your understanding.

**Comment by brentvatne** [comment]
i was able to repro this in an emulator using android 11 (api 30) with this code: https://gist.github.com/brentvatne/47fa9898517397bc5b3f1f5fb0af7641

**Comment by franamu** [comment]
same issue here with api 30 expo sdk 40, on Emulator is working fine in a fisical device.

**Comment by BartekH** [comment]
After update do SDK 40 I faced the same issue, the missing part was:
`
 "android": {
      "permissions": ["ACCESS_BACKGROUND_LOCATION"]
    },
` in `app.json`

**Comment by fromsujay** [comment]
> After update do SDK 40 I faced the same issue, the missing part was:
> `"android": { "permissions": ["ACCESS_BACKGROUND_LOCATION"] },` in `app.json`

Hello @BartekH ,
Thanks for sharing your solution. The problem is that ACCESS_BACKGROUND_LOCATION is allowed only for apps that requires a continuous/regular monitoring of the user's position like food delivery, navigational/driving apps. Unless you can justify that your app requirement continuous monitoring of the user's position, the Google Play Store will not approve the app. They implemented this policy change roughly sometime during the summer of 2020.

Could you please tell me that your app was approved/deployed on Google Play and that it is not an app that requires continuous monitoring of the user's position ?

Thanks for your help.

**Comment by BartekH** [comment]
Ahh ok, I see. Thanks for explanation.
My app requires regular monitoring of the user's position. We are still in MVP state, but I will investigate this case related to Google Play Store, didn't know about it.

**Comment by fromsujay** [comment]
If your app needs regular monitoring of the user's position, then you are likely to be fine. All the best.

**Comment by abrahamjsb** [comment]
Hello I was reading all this feed because a I was facing the same issue. However, As experiment, I set  `Location.getCurrentPositionAsync({accuracy: 6})` and suddenly start to work properly. Let me know if this solutions works for someone else.

**Comment by kirchmann** [comment]
> Hello I was reading all this feed because a I was facing the same issue. However, As experiment, I set `Location.getCurrentPositionAsync({accuracy: 6})` and suddenly start to work properly. Let me know if this solutions works for someone else.

thanks, that worked for me! :)

**Comment by brentvatne** [comment]
related: #12063 - this will ship in sdk 41

**Comment by fromsujay** [comment]
If this bug is corrected in SDK 41, it will be a huge relief for me.

**Comment by ArtRabbit** [comment]
I can still see this bug in SDK 41. I'm testing on an actual device (Huawei p40 pro) and also had users report the same issue. I've tried setting different accuracy levels as suggested above, which makes no difference. Location services are definitely enabled. Logging getProviderStatusAsync() returns: {
  "backgroundModeEnabled": true,
  "gpsAvailable": true,
  "locationServicesEnabled": true,
  "networkAvailable": true,
  "passiveAvailable": true,
}
I can get the getLastKnownPositionAsync() but getCurrentPositionAsync() always returns:
Error: Location provider is unavailable. Make sure that location services are enabled.
I'm using the permissions setup from the Location module, eg. getting permissions with: 
Location.requestForegroundPermissionsAsync()
They are granted and Location.hasServicesEnabledAsync() also confirms this.
I have 
"ACCESS_COARSE_LOCATION",
"ACCESS_FINE_LOCATION",
"FOREGROUND_SERVICE"   
in my manifest.
Is there any other workaround or any update planned for this? We have a location sensitive app and can't provide our service to Android users at the moment.

**Comment by fromsujay** [comment]
I confirm that the problem still persists even after migrating to Expo SDK 41. I believe the problem is with the implementation of `Location.getCurrentPositionAsync()` method in Android since it doesn't return a promise resolving to an object of type LocationObject.

Here is my implementation after upgrading to Expo SDK 41. When I launch the app both methods `Location.getCurrentPositionAsync()` and  `Location.getLastKnownPositionAsync()` don't work and I have to alert the user with the message in the screenshot. When I relaunch the app, the method `Location.getCurrentPositionAsync()` still doesn't work but the method `Location.getLastKnownPositionAsync()` works and the last known position of the device is found. But this is not a good user experience for several reasons. The last known position of the device may not be the user's current position. I test on an Honor 8x (Android 10).

In app.json, Android object, I ask for the following permissions. This is an Android specific problem. On iOS, I haven't encountered problems with these methods.

```
"permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION"
] 
``` 

```
async _getLocationAsync() {
  try {
    let { status } = await Location.requestForegroundPermissionsAsync();
    if (status !== 'granted') {
      // if user hasnt granted permission to geolocate himself herself
      Alert.alert(
        "User location not detected",
        "You haven't granted permission to detect your location.",
        [{ text: 'OK', onPress: () => console.log('OK Pressed') }]
      );
    }
    try {
      let isLocationServicesEnabled = await Location.hasServicesEnabledAsync();
      let location = await Location.getCurrentPositionAsync();
      this.setState({
        userLat: location.coords.latitude,
        userLng: location.coords.longitude,
        navGeoStatus: true,
      }, () => this.goToUserPosition());
    } catch (error) {
      console.log('getCurrentPositionAsync error',error);
      let location = await Location.getLastKnownPositionAsync();
      if (location == null) {
        Alert.alert(
          "Geolocation failed",
          "Your position could not be detected",
          [{ text: "OK", onPress: () => console.log("OK Pressed") }]
        );
      } else {
        this.setState({
          userLat: location.coords.latitude,
          userLng: location.coords.longitude,
          navGeoStatus: true,
        }, () => this.goToUserPosition());
      }
    }
  } catch (error) {
    console.log('askAsync error',error);
  }
}
```
![image](https://user-images.githubusercontent.com/23614875/116535373-f9fbbf80-a8e3-11eb-8ebf-807adf7653ed.png)

**Comment by hanselsen** [comment]
Indeed still on SDK 41. Tried all the above, but I cannot seem to pinpoint where it is coming from.
@brentvatne could you please mention the recommended steps/workarounds?

**Comment by minawk** [comment]
> Indeed still on SDK 41. Tried all the above, but I cannot seem to pinpoint where it is coming from.
> @brentvatne could you please mention the recommended steps/workarounds?
> 
> I put the line in a try-catch clause and requested the providerStatus:
> 
> ```
> try {
>     await Location.getCurrentPositionAsyc({
>         accuracy: Location.Accuracy.High, //also tried other values
>         enableHighAccuracy: true //to be sure
>     });
> } catch(e) { // <-- is indeed the "Location provider is unavailable. Make sure location services are enabled."
>     const status = await Location.getProviderStatusAsync();
> }
> ```
> 
> Where status is
> 
> ```
> {
>     backgroundModeEnabled: true,
>     gpsAvailable: true,
>     locationServicesEnabled: true, // <-- weird this. Right?
>     networkAvailable: true,
>     passiveAvailable: true
> }
> ```

Same for me on SDK 41.

**Comment by ajbtechservices** [comment]
Yep, still a problem...

**Comment by ArtRabbit** [comment]
Tried @laborin's trick. Unfortunately no joy with a Huawei p40 pro (android 10). Location just keeps failing even with the airplane mode trick. I did notice that before turning on and off airplane mode the location took quite some time to fail, afterwards it failed rapidly.

**Comment by pedrolarap** [comment]
> Hola @AdamJNavarro ,
> 
> Gracias por su respuesta. Este problema ocurre en un dispositivo Android físico Honor 8X que se ejecuta en Android 10.
> 
> Saludos,
> Sujay
seems crazy, but I solved this error by changing:



> Acabo de actualizar mi aplicación de Expo SDK 37.0.0 a 38.0.0. La aplicación funciona bien en iOS, pero en Android recibo la siguiente advertencia y la aplicación no me geolocaliza en el mapa. En Expo SDK 37, esta función funcionaba perfectamente.
> 
> Resultado esperado: la aplicación debería geolocalizarme (el usuario) en función de mi posición.
> Resultado real: la aplicación no me geolocaliza (el usuario) en función de mi posición. El problema es específico de Android. En iOS, esta función funciona bien. Advertencia :
> 
> > [Rechazo de promesa no gestionada: Error: el proveedor de ubicación no está disponible. Asegúrese de que los servicios de ubicación estén habilitados.]
> 
> Entorno de desarrollo :
> 
> * Expo SDK 38.0.0
> * Reaccionar nativo 0.62
> * Proveedor de mapas: Google Maps en Android
> * reaccionar-mapas-nativos: 0.27.1
> * Reaccionar: 16.11.0
> * Dispositivo: Honor 8X / Android 10
> 
> ¿Qué he probado hasta ahora?
> 
> * Ejecuté la actualización de expo una vez más para asegurarme de que todos mis paquetes estuvieran configurados con la versión correcta.
> * Se eliminó package-lock.json y node_modules y se ejecutó npm install.
> * Establecer Location.getCurrentPositionAsync ({precisión: Location.Accuracy.High})
> * Establecer Location.getCurrentPositionAsync ({enableHighAccuracy: true})
> * Establecer Location.getCurrentPositionAsync ({precisión: Location.Accuracy.Lowest})
> * Establecer Location.getCurrentPositionAsync ({precisión: Location.Accuracy.Low})
> * Establecer Location.getCurrentPositionAsync ({precisión: Location.Accuracy.Balanced})
> * Una actualización a Expo SDK 39.0.0 no muestra ninguna mejora. El error es el mismo.
> 
> ```
> import * as Location from 'expo-location';
> import * as Permissions from 'expo-permissions';
> 
> async _getLocationAsync() {
>   let { status } = await Permissions.askAsync(Permissions.LOCATION);
>   if (status !== 'granted') {
>     /* If user hasn't granted permission to geolocate himself herself */
>     Alert.alert(
>       "User location not detected",
>       "You haven't granted permission to detect your location.",
>       [{ text: 'OK', onPress: () => console.log('OK Pressed') }]
>     );
>   }
> 
>   let location = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.High });
>   this.setState({
>     userLat: location.coords.latitude,
>     userLng: location.coords.longitude,
>     navGeoStatus: true,
>     lat: location.coords.latitude,
>     lng: location.coords.longitude
>   });
> }
> ```
seems crazy, but I solved this error by changing:
resultPermissions = await Permissions.askAsync(Permissions.location)
to
resultPermissions = await Permissions.askAsync(Permissions.LOCATION)

https://1.bp.blogspot.com/-svdkidwaynM/YK3LgPxkt_I/AAAAAAAAF1w/A_9SFjzPy9goKQyZsdyqJRouH76BXf_9ACNcBGAsYHQ/s1440/Captura%2Bde%2BPantalla%2B2021-05-26%2Ba%2Bla%2528s%2529%2B12.14.07%2Ba.%25C2%25A0m..png

**Comment by chris-chapin** [comment]
Is anyone working on this issue? I have the same problem (no location provider) when the device (old Android 7 Motorola) is in airplane mode. Works fine with WiFi connection. My permissions are ACCESS_COARSE_LOCATION, ACCESS_FINE_LOCATION, FOREGROUND_SERVICE, and I also added ACCESS_BACKGROUND_LOCATION (as a suggested workaround above though I shouldn't need it).

Getting the user's GPS location in the mountains where no cel signal exists is a core function of my app. I see that other apps like Gaia GPS are locating GPS coordinates in airplane mode so I know it is not the device.

**Comment by hanselsen** [comment]
@byCedric this seems to be a very active issue. Can you tell us something about it?

**Comment by ViniciusCMelo** [comment]
This is happening to me aswell, works fine on Redmi note 8 and Samsung A51, but on my Redmi note 8 pro does not work.

**Comment by chris-chapin** [comment]
I figured out what my problem was: a typo in the accuracy enum which originated from replacing deprecated geolocation\navigation API with expo-location (code included below). The frustrating part is the typo would give me GPS coordinates if I had a cel\wifi\network connection. I successfully get GPS coordinates now on all my Android configs (Android 7.1.1 physical device and Android 8/9/10/11 AVDs) while in Airplane mode. I do not need ACCESS_BACKGROUND_LOCATION permission either.

Here's the relevant code and permissions configurations in case it helps someone else out.

`const { status } = await Location.requestForegroundPermissionsAsync();
 if (status !== 'granted') {
   return;
 }

 try {
   this.watchPosition = await Location.watchPositionAsync({
     accuracy: Location.Accuracy.High,                                      // <-- typo was here: accuracy: Location.High
     timeInterval: 5000
   }, position => this.parseCoordinates(position.coords));
 }
 catch (error) {}`

Android permission (managed workflow)

"android": {
      "permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION",
        "FOREGROUND_SERVICE"
      ]

**Comment by basit3407** [comment]
> Hello I was reading all this feed because a I was facing the same issue. However, As experiment, I set `Location.getCurrentPositionAsync({accuracy: 6})` and suddenly start to work properly. Let me know if this solutions works for someone else.

This worked for me too. thanks

**Comment by ibrofro** [comment]
> {accuracy: 6}

Work for me thanks

**Comment by ibrofro** [comment]
> Hello I was reading all this feed because a I was facing the same issue. However, As experiment, I set `Location.getCurrentPositionAsync({accuracy: 6})` and suddenly start to work properly. Let me know if this solutions works for someone else.

Works for me too thanks.

**Comment by enesakin1** [comment]
Yesterday, before I sleep, my app was working perfectly but now It's throwing the same error. And I didn't even change my code since yesterday.

**Comment by peepeepoopooexpo** [comment]
Same problem for me, @enesakin1. My app is on the play store and worked great a day ago, now none of my users with Android can use it... 

I did notice that it works fine if I'm using an app like "Fake GPS" to spoof my location, I'm not sure if that information will help anyone solve this but I hope it does.

**Comment by itsGabriel** [comment]
@enesakin1 Having same problem with redmi note 8.

**Comment by rfink** [comment]
@enesakin1 Same issue on a variety of Android devices

**Comment by kamarajcalm** [comment]
Location.installWebGeolocationPolyfill();
   so that u can use 
navigator.geolocation.getCurrentPosition(
  position => {
    const location = JSON.stringify(position);

    this.setState({ location });
  },
  error => Alert.alert(error.message),
  { enableHighAccuracy: true, timeout: 20000, maximumAge: 1000 }
);

**Comment by keharv** [comment]
I've tried all of the solutions in this thread, and I'm still receiving the error.

**Comment by enesakin1** [comment]
You can use `watchPositionAsync()` and remove it in handling function for temp solution. Don't forget to remove it also in `componentWillUnmount() ` for possible unmount situation.

**Comment by keharv** [comment]
Update: Using Location.getLastKnownPositionAsync(options) is a good temporary fix, but Location.getCurrentPositionAsync() isn't working.

**Comment by itsGabriel** [comment]
@keharv sometimes this method can be returned with null data

**Comment by josh-gree** [comment]
This is a real PIA - my app works on emulators perfectly fine - but fails randomly with;

```
{
  "nativeStackAndroid": [
    {
      "lineNumber": 2,
      "file": "LocationModule.java",
      "methodName": "onLocationAvailability",
      "class": "expo.modules.location.LocationModule$1"
    },
    {
      "lineNumber": 4,
      "file": null,
      "methodName": "a",
      "class": "f.f.b.e.f.m.w"
    },
    {
      "lineNumber": 3,
      "file": "com.google.android.gms:play-services-base@@17.5.0",
      "methodName": "d",
      "class": "com.google.android.gms.common.api.internal.k"
    },
    {
      "lineNumber": 3,
      "file": "com.google.android.gms:play-services-base@@17.5.0",
      "methodName": "handleMessage",
      "class": "com.google.android.gms.common.api.internal.k$c"
    },
    {
      "lineNumber": 107,
      "file": "Handler.java",
      "methodName": "dispatchMessage",
      "class": "android.os.Handler"
    },
    {
      "lineNumber": 213,
      "file": "Looper.java",
      "methodName": "loop",
      "class": "android.os.Looper"
    },
    {
      "lineNumber": 8,
      "file": "MessageQueueThreadImpl.java",
      "methodName": "run",
      "class": "com.facebook.react.bridge.queue.MessageQueueThreadImpl$4"
    },
    {
      "lineNumber": 929,
      "file": "Thread.java",
      "methodName": "run",
      "class": "java.lang.Thread"
    }
  ],
  "userInfo": null,
  "message": "Location provider is unavailable. Make sure that location services are enabled.",
  "code": "E_LOCATION_UNAVAILABLE",
  "line": 2693,
  "column": 45,
  "sourceURL": "app.bundle"
}
```

on a physical `HUAWEI P smart 2019` - can we get some update from the dev team on the status of this issue please?

**Comment by CristyanCiton** [comment]
that solved my problem:

try {
     location = await Location.getCurrentPositionAsync({
          accuracy: Location.Accuracy.BestForNavigation,
          LocationActivityType: Location.ActivityType.OtherNavigation,
          maximumAge: 5000,
          timeout: 15000,
     });
} catch {
     location = await Location.getLastKnownPositionAsync({
          accuracy: Location.Accuracy.BestForNavigation,
          LocationActivityType: Location.ActivityType.OtherNavigation,
          maxAge: 5000,
          timeout: 15000,
     });
}

apparently the method "getCurrentPositionAsync" should return null when not finding location but is returning an exception.

**Comment by ARM-Visionpool** [comment]
Still broken. I'm running into this issue with the latest version of Android phone and latest Expo SDK 42.

**Comment by avidianity** [comment]
Have read the whole thread and tested out all solutions mentioned above. expo-locations still doesn't work. Using Realme C2 and Itel phones.

**Comment by JohnMendes** [comment]
desse jeito esta funcionando, mas com instabilidade. 

const { granted } = await Location.requestForegroundPermissionsAsync();
    if (granted) {
      try {
        let location = await Location.getCurrentPositionAsync({
          enableHighAccuracy: true,
          accuracy: Location.Accuracy.BestForNavigation,
          LocationActivityType: Location.ActivityType.OtherNavigation,
          maximumAge: 5000,
          timeout: 15000,
        });
        setStdLatitude(location);
      } catch {
        let location = await Location.getLastKnownPositionAsync({
          accuracy: Location.Accuracy.BestForNavigation,
          LocationActivityType: Location.ActivityType.OtherNavigation,
          maximumAge: 5000,
          timeout: 15000,
        });
        setStdLatitude(location);
      }
    }

**Comment by byCedric** [comment]
Hi everyone, I'm closing this issue to merge the discussion into #14248. If you are still running into this issue, please [take a look at this comment](https://github.com/expo/expo/issues/14248#issuecomment-915099538).
