### ISSUE TITLE
ExpoKit (Android) Cannot Link Native Modules

### ISSUE THREAD

**Issue by Daadler6** [expo/expo#947]
We've recently detached from Expo to ExpoKit to give us the ability to use native modules and external react-native libraries that are not supported by Expo. For iOS the detachment process has been smooth but on Android I have yet to be able to link a single module. I've traced the issue down to the MainApplication.java currently ExpoKit has the MainReactPackage commented out with the comment  "Needed for react-native link". Because this MainReactPackage() is commented out we are getting the following errors when running 'react-native link' on Android. ```java.lang.IllegalStateException: Application instance isn't a react-application```.

I've since switched my MainApplication.java as follows.

```import android.support.multidex.MultiDexApplication;

import com.facebook.react.ReactPackage;

import java.util.Arrays;
import java.util.List;

// Needed for `react-native link`
import com.facebook.react.shell.MainReactPackage;

public class MainApplication extends MultiDexApplication {

  // Needed for `react-native link`
  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        // Add your own packages here!
        // TODO: add cool native modules

        // Needed for `react-native link`
         new MainReactPackage()
    );
  }
}
```

But now get the following error on start up.
![image](https://user-images.githubusercontent.com/10039096/32675645-9759e798-c625-11e7-85f6-1e0dc09299b7.png)

**Comment by brentvatne** [comment]
Hi there!

I investigated this and suspect that the detach template is out of date in SDK23, sorry for the hassle. I haven't confirmed this with our Android lead yet, but I was able to get a project running with a third party native module by not including the `MainReactPackage()` in `getPackages()`, as follows:

```
package com.lol.lool;

import android.support.multidex.MultiDexApplication;

import com.facebook.react.ReactPackage;

import java.util.Arrays;
import java.util.List;

// Needed for `react-native link`
import com.facebook.react.ReactApplication;
import com.facebook.react.shell.MainReactPackage;
import com.github.xinthink.rnmk.ReactMaterialKitPackage;

public class MainApplication extends MultiDexApplication {

  // Needed for `react-native link`
  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        // Add your own packages here!
        // TODO: add cool native modules

        // Needed for `react-native link`
        // new MainReactPackage(),
        new ReactMaterialKitPackage()
    );
  }
}
```

@jesseruder can provide more context when he has time. Let me know if this works for you.

**Comment by Daadler6** [comment]
@brentvatne thanks for the reply! After diving deeper into the subject it appears that the package I am trying to implement (https://github.com/wix/react-native-notifications/blob/master/docs/installation.md)  expects the application as an argument. Because the main activity does not implement the ReactApplication interface the error ```java.lang.IllegalStateException: Application instance isn't a react-application``` is being thrown. I am going to keep plugging away and see if I can get this to work and I will report back. If anyone has any suggestions let me know!

**Comment by Daadler6** [comment]
@brentvatne - Sorry for leaving this out here for so long. I was able to solve this issue by using the following code. It works by implementing the ReactApplication interface in MainApplication as a normal ```react-native init`` project would have it setup. I would love to know if @jesseruder as I wouldn't consider myself too comfortable with Java code. But this will work for now

```package (Your Project as given by expo);

import android.support.multidex.MultiDexApplication;


import com.facebook.react.ReactPackage;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;

import com.wix.reactnativenotifications.RNNotificationsPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends MultiDexApplication implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
              //new MainReactPackage(),
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
            // Add your own packages here!
            // TODO: add cool native modules

            // Needed for `react-native link`
            // new MainReactPackage()
            new RNNotificationsPackage(MainApplication.this)
    );
  }

}
```

**Comment by onka13** [comment]
I've a similar problem about expokit. After detached 2 different library I tried to link. But NativeModules always empty. Here is my first code;

```
package host.exp.exponent;


import com.facebook.react.ReactPackage;

import java.util.Arrays;
import java.util.List;

// Needed for `react-native link`
// import com.facebook.react.ReactApplication;
import com.wix.reactnativenotifications.RNNotificationsPackage;
import com.reactlibrary.RNIapPackage;
import com.facebook.react.shell.MainReactPackage;

public class MainApplication extends ExpoApplication {

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  // Needed for `react-native link`
  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        // Add your own packages here!
        // TODO: add native modules!

        // Needed for `react-native link`
        new MainReactPackage(),
            new RNNotificationsPackage(MainApplication.this),
            new RNIapPackage()
    );
  }

  @Override
  public String gcmSenderId() {
    return getString(R.string.gcm_defaultSenderId);
  }

  @Override
  public boolean shouldUseInternetKernel() {
    return BuildVariantConstants.USE_INTERNET_KERNEL;
  }
}
```


Then I tried like this;

```
package host.exp.exponent;


import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;

import java.util.Arrays;
import java.util.List;

// Needed for `react-native link`
import com.facebook.react.ReactApplication;
import com.wix.reactnativenotifications.RNNotificationsPackage;
import com.reactlibrary.RNIapPackage;
import com.facebook.react.shell.MainReactPackage;

public class MainApplication extends ExpoApplication implements ReactApplication {

    @Override
    public boolean isDebug() {
        return BuildConfig.DEBUG;
    }

    // Needed for `react-native link`
    public List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
                // Add your own packages here!
                // TODO: add native modules!

                // Needed for `react-native link`
                new MainReactPackage(),
                new RNNotificationsPackage(MainApplication.this),
                new RNIapPackage()
        );
    }

    @Override
    public String gcmSenderId() {
        return getString(R.string.gcm_defaultSenderId);
    }

    @Override
    public boolean shouldUseInternetKernel() {
        return BuildVariantConstants.USE_INTERNET_KERNEL;
    }

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

        @Override
        public boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return MainApplication.this.getPackages();
        }
    };
}
```


Testing in js;

```
import React, { Component } from 'react';
import {
    StyleSheet, View, Text, Button, NativeModules
} from 'react-native'
import { NavigationActions } from 'react-navigation'

import BaseComponent from '../base/BaseComponent'

console.log('NativeModules', NativeModules.RNIapModule, NativeModules.WixRNNotifications)
```

That prints
`NativeModules1418 undefined undefined
`
By the way I created a new project with 'react-native init'. That works very well. What am I missing? Please help.

My package.json;

```
{
  "name": "Test1",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.8.1",
    "jest-expo": "24.0.0",
    "react-test-renderer": "16.0.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^24.0.0",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz",
    "react-native-easy-toast": "^1.0.9",
    "react-native-iap": "^0.1.10",
    "react-native-notifications": "^1.1.17",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-tab-navigator": "^0.3.4",
    "react-navigation": "^1.0.0-beta.21"
  }
}
```

**Comment by chochihim** [comment]
I have similar problem with @onka13. Cannot make libraries which expect `MainApplication` to be implementing `ReactApplication` work.

@brentvatne can I say project with ExpoKit is not compatible with those libraries? If yes I think I need to give ExpoKit up and use regular react native project instead.

**Comment by onka13** [comment]
Hi @chochihim I finally realised that this issue is about sdk 24. It's working on sdk 23.

**Comment by chochihim** [comment]
@onka13 can you share how do you amend the MainApplication.java on sdk 23?

**Comment by onka13** [comment]
@chochihim  Sure,

```
public class MainActivity extends ExponentActivity {

  @Override
  public String publishedUrl() {
    return "exp://exp.host/@.../testproject1";
  }

  @Override
  public String developmentUrl() {
    return ExponentBuildConstants.DEVELOPMENT_URL;
  }

  @Override
  public List<String> sdkVersions() {
    return new ArrayList<>(Arrays.asList("23.0.0"));
  }

  @Override
  public List<ReactPackage> reactPackages() {
    return ((MainApplication) getApplication()).getPackages();
  }

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  @Override
  public Bundle initialProps(Bundle expBundle) {
    // Add extra initialProps here
    return expBundle;
  }
}
```


```
public class MainApplication extends MultiDexApplication {

  // Needed for `react-native link`
  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        // Add your own packages here!
        // TODO: add cool native modules

        // Needed for `react-native link`
        // new MainReactPackage(),
            new RNIapPackage()
    );
  }
}
```

**Comment by chochihim** [comment]
@Daadler6 May I ask if your android build still works after amending the `MainApplication` to implement `ReactApplication`?

**Comment by jesseruder** [comment]
Hi everyone. I pushed out an update to the detach code. If you re-run `exp detach` you should get it. Can you try that and let me know if it works?

**Comment by chochihim** [comment]
@jesseruder really thanks for the update! I definitely will try it after Christmas holidays and let you know the result.

**Comment by chochihim** [comment]
@jesseruder it is still not working. 

Do I need to amend `MainApplication.java` as @Daadler6 did if errors like `java.lang.IllegalStateException: Application instance isn't a react-application` occur? Can't `ExpoApplication` implements `ReactApplication` in the first place?

**Comment by Daadler6** [comment]
@chochihim - Sorry for the late reply been out for the holidays. The issue was during a POC to get push notifications to work and we have since moved on w/o implementing the code above. With that said we plan to make push notifications a feature in the coming weeks which will re-open this issue for us. I'll be sure to keep you updated on my findings.

**Comment by Daadler6** [comment]
Update on the issue: I actually decided on using https://github.com/zo0r/react-native-push-notification for Push Notifications as opposed to the Wix one for many reasons.  With that said I was able to validate that the Wix one would work on a detached Expo Build if you were willing to make changes to the MainApplication file as I posted above. I am going to close this issue because the title doesn't really fit what is going on. Native Modules do work on detached Expo I would just argue that you could avoid ones that require the application to be passed in... these don't seem to fit with Expo out of the box for the time being and seeing as I am not a Java expert I can not offer up a better solution. Thanks @brentvatne and @jesseruder  - For taking a look into this if you guys need any help in the future feel free to reach out here or on expo slack.

**Comment by onka13** [comment]
@ianmark89 I couldn't test it on sdk 24 again. It's working on sdk23.

**Comment by ianmark89** [comment]
@onka13 Expo push notification is not working with android link native on sdk25. It open another instance of the app when tab on notification.

**Comment by AdamJNavarro** [comment]
Hey @ianmark89, Expo's Push Notifications API is not compatible with a detached/ejected project that relies on ExpoKit. Your project has to be a standard Expo project (pure JS) in order to use our Push Notif API. You'll have to find alternate means to add push notifs to your project.

**Comment by vinnichase** [comment]
I'm facing the same issue NativeModules is always empty. Somehow the react-native-vector-icons are linked and loaded correctly, even when i comment out the package in MainApplication. But when i delete the android folder, `exp start` still compiles and builds the package which makes me think, that expokit comletely ignores the android folder.

**Comment by esamelson** [comment]
Hi @vinnichase - the original issue here was solved. Do you think you could open a new issue with a reproducible test case? That would help us figure out how to help you much faster.
