### ISSUE TITLE
Negative text must be set and non-empty

### ISSUE THREAD

**Issue by clems36** [expo/expo#9683]
### Summary of Issue

Calling `LocalAuthentication.authenticateAsync` with `disableDeviceFallback: true` gives me that error on android

### Environment 

`"expo-local-authentication": "~9.1.1"`

```
Expo CLI 3.23.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-navigation: ^4.0.10 => 4.4.0
```

### Reproducible Demo

It's hard for me to transform my project into a small reproducible demo at the moment.
 
### Expected Behavior vs Actual Behavior

I would expect `disableDeviceFallback: true` to only allow me to use fingerprint authentication on android as it does on iOS. It crashes instead:
![Screenshot 2020-08-11 at 17 47 38](https://user-images.githubusercontent.com/6041593/89918806-c9abae00-dbfa-11ea-8c06-e6643d80cb6f.png)

**Comment by byCedric** [comment]
Hi @clems36, thanks for the report. It appears we don't set a default `cancelLabel` value, while I think we should. Until this is resolved, you can make it work by manually adding this to your `authenticateAsync`. E.g.:

```
LocalAuthentication.authenticateAsync({
	promptMessage: 'Please authenticate',
	disableDeviceFallback: true,
	cancelLabel: 'Cancel',
})
```

I'll keep this issue open until that's resolved.

**Comment by clems36** [comment]
Hey @byCedric, that perfectly works, thank you for the quick answer :)

**Comment by toviszsolt** [comment]
@byCedric In the meantime, the reporter has closed the issue and it does not seem to have been resolved.

An error message is still displayed, please check if the `default` value of `cancelLabel` has been added and if an update has been applied on `npm`. Thank you

**Comment by webcode2** [comment]
So happy right now, Problem resolved, thanks a lot

**Comment by miran248** [comment]
This problem still exists in expo 49! Saw it on android 10, but not (yet) on android 13.

**Comment by Zeusmist** [comment]
3 years later this bug still exists. Thanks for the solution @byCedric
